import type { RawTopic } from '../types';

const topic: RawTopic = {
  slug: 'amtstraeger',
  title: 'Aktuelle Amtsträger',
  description: 'Wer hat aktuell welches wichtige Amt inne? (Stand 2026)',
  flashcards: [
    {
      front: 'Wer ist seit dem 6. Mai 2025 Bundeskanzler der Bundesrepublik Deutschland?',
      back: 'Friedrich Merz (CDU). Er führt eine Koalition aus CDU/CSU und SPD.',
    },
    {
      front: 'Wer ist Bundespräsident der Bundesrepublik Deutschland (Stand 2026)?',
      back: 'Frank-Walter Steinmeier.',
    },
    {
      front: 'Wer ist Bundestagspräsidentin (Stand 2026)?',
      back: 'Julia Klöckner (CDU).',
    },
    {
      front: 'Wer ist Präsident des Bundesverfassungsgerichts (Stand 2026)?',
      back: 'Stephan Harbarth.',
    },
    {
      front: 'Wer ist Ministerpräsidentin des Saarlandes (Stand 2026)?',
      back: 'Anke Rehlinger (SPD).',
    },
    {
      front: 'Wer ist Minister für Inneres, Bauen und Sport im Saarland (Stand 2026)?',
      back: 'Reinhold Jost.',
    },
    {
      front: 'Wer ist Staatssekretär im saarländischen Ministerium für Inneres, Bauen und Sport (Stand 2026)?',
      back: 'Torsten Lang.',
    },
    {
      front: 'Wer ist Präsidentin der EU-Kommission (Stand 2026)?',
      back: 'Ursula von der Leyen.',
    },
    {
      front: 'Wer ist Präsident des Europäischen Rates (Stand 2026)?',
      back: 'António Costa.',
    },
    {
      front: 'Wer ist Präsidentin des Europäischen Parlaments (Stand 2026)?',
      back: 'Roberta Metsola.',
    },
    {
      front: 'Wer ist NATO-Generalsekretär (Stand 2026)?',
      back: 'Mark Rutte.',
    },
    {
      front: 'Wer ist UN-Generalsekretär (Stand 2026)?',
      back: 'António Guterres.',
    },
    {
      front: 'Wer ist seit Januar 2025 Präsident der USA?',
      back: 'Donald Trump.',
    },
    {
      front: 'Welche Parteien bilden die Bundesregierung unter Friedrich Merz (Stand 2026)?',
      back: 'CDU/CSU und SPD (Große Koalition).',
    },
    {
      front: 'Welcher Partei gehört Anke Rehlinger, Ministerpräsidentin des Saarlandes, an?',
      back: 'Der SPD (Sozialdemokratische Partei Deutschlands).',
    },
    {
      front: 'Welcher Partei gehört Friedrich Merz an?',
      back: 'Der CDU (Christlich Demokratische Union Deutschlands).',
    },
    {
      front: 'Seit wann ist Friedrich Merz Bundeskanzler?',
      back: 'Seit dem 6. Mai 2025.',
    },
    {
      front: 'Wer war Bundeskanzler unmittelbar vor Friedrich Merz?',
      back: 'Olaf Scholz (SPD).',
    },
    {
      front: 'Welchem Land gehört António Costa an, der Präsident des Europäischen Rates?',
      back: 'Portugal. Er war zuvor Ministerpräsident Portugals.',
    },
    {
      front: 'Welche Institution leitet Roberta Metsola?',
      back: 'Das Europäische Parlament. Sie ist dessen Präsidentin.',
    },
    {
      front: 'Wer war NATO-Generalsekretär vor Mark Rutte?',
      back: 'Jens Stoltenberg (Norwegen).',
    },
  ],
  questions: [
    {
      type: 'mc',
      prompt: 'Wer ist seit dem 6. Mai 2025 Bundeskanzler der Bundesrepublik Deutschland?',
      options: ['Olaf Scholz', 'Friedrich Merz', 'Markus Söder', 'Robert Habeck'],
      correct: [1],
      explanation: 'Friedrich Merz (CDU) wurde am 6. Mai 2025 zum Bundeskanzler gewählt und führt eine Koalition aus CDU/CSU und SPD.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Wer ist Bundespräsident der Bundesrepublik Deutschland (Stand 2026)?',
      options: ['Frank-Walter Steinmeier', 'Joachim Gauck', 'Christian Wulff', 'Friedrich Merz'],
      correct: [0],
      explanation: 'Frank-Walter Steinmeier ist Bundespräsident. Er wurde erstmals 2017 gewählt und 2022 wiedergewählt.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Wer ist Bundestagspräsidentin (Stand 2026)?',
      options: ['Bärbel Bas', 'Annalena Baerbock', 'Julia Klöckner', 'Katrin Göring-Eckardt'],
      correct: [2],
      explanation: 'Julia Klöckner (CDU) ist Bundestagspräsidentin. Ihre Vorgängerin war Bärbel Bas (SPD).',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Wer ist Präsident des Bundesverfassungsgerichts (Stand 2026)?',
      options: ['Andreas Voßkuhle', 'Stephan Harbarth', 'Peter Huber', 'Doris König'],
      correct: [1],
      explanation: 'Stephan Harbarth ist Präsident des Bundesverfassungsgerichts. Er übernahm das Amt 2020 von Andreas Voßkuhle.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Wer ist Ministerpräsidentin des Saarlandes (Stand 2026)?',
      options: ['Annegret Kramp-Karrenbauer', 'Heiko Maas', 'Peter Hans', 'Anke Rehlinger'],
      correct: [3],
      explanation: 'Anke Rehlinger (SPD) ist Ministerpräsidentin des Saarlandes. Sie trat 2022 die Nachfolge von Tobias Hans an.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Wer ist Minister für Inneres, Bauen und Sport im Saarland (Stand 2026)?',
      options: ['Reinhold Jost', 'Klaus Bouillon', 'Stephan Toscani', 'Torsten Lang'],
      correct: [0],
      explanation: 'Reinhold Jost ist Minister für Inneres, Bauen und Sport im Saarland. Torsten Lang ist der Staatssekretär in diesem Ministerium.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Wer ist Staatssekretär im saarländischen Ministerium für Inneres, Bauen und Sport (Stand 2026)?',
      options: ['Torsten Lang', 'Reinhold Jost', 'Roland Theis', 'Jürgen Barke'],
      correct: [0],
      explanation: 'Torsten Lang ist Staatssekretär im Ministerium für Inneres, Bauen und Sport des Saarlandes unter Minister Reinhold Jost.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Wer ist Präsidentin der Europäischen Kommission (Stand 2026)?',
      options: ['Christine Lagarde', 'Ursula von der Leyen', 'Federica Mogherini', 'Margrethe Vestager'],
      correct: [1],
      explanation: 'Ursula von der Leyen (CDU/EVP) ist Präsidentin der Europäischen Kommission und wurde in dieser Funktion für eine zweite Amtszeit bestätigt.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Wer ist Präsident des Europäischen Rates (Stand 2026)?',
      options: ['Charles Michel', 'António Costa', 'Donald Tusk', 'Herman Van Rompuy'],
      correct: [1],
      explanation: 'António Costa (Portugal) ist Präsident des Europäischen Rates. Er übernahm das Amt von Charles Michel.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Wer ist Präsidentin des Europäischen Parlaments (Stand 2026)?',
      options: ['Roberta Metsola', 'David Sassoli', 'Ursula von der Leyen', 'Simone Schmiedtbauer'],
      correct: [0],
      explanation: 'Roberta Metsola (Malta, EVP) ist Präsidentin des Europäischen Parlaments.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Wer ist NATO-Generalsekretär (Stand 2026)?',
      options: ['Jens Stoltenberg', 'Anders Fogh Rasmussen', 'Mark Rutte', 'Jaap de Hoop Scheffer'],
      correct: [2],
      explanation: 'Mark Rutte (Niederlande) ist NATO-Generalsekretär. Er übernahm das Amt 2024 von Jens Stoltenberg.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Wer ist UN-Generalsekretär (Stand 2026)?',
      options: ['Ban Ki-moon', 'António Guterres', 'Kofi Annan', 'Boutros Boutros-Ghali'],
      correct: [1],
      explanation: 'António Guterres (Portugal) ist seit 2017 UN-Generalsekretär und wurde für eine zweite Amtszeit bis 2026 bestätigt.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Wer ist seit Januar 2025 Präsident der Vereinigten Staaten von Amerika?',
      options: ['Joe Biden', 'Kamala Harris', 'Ron DeSantis', 'Donald Trump'],
      correct: [3],
      explanation: 'Donald Trump ist seit seiner Amtseinführung im Januar 2025 wieder US-Präsident (seine zweite Amtszeit).',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welche Koalition regiert Deutschland unter Bundeskanzler Friedrich Merz (Stand 2026)?',
      options: ['CDU/CSU und FDP', 'SPD und Grüne', 'CDU/CSU und SPD', 'CDU/CSU, SPD und FDP'],
      correct: [2],
      explanation: 'Die Bundesregierung unter Friedrich Merz (CDU) besteht aus einer Koalition von CDU/CSU und SPD.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welcher Partei gehört Anke Rehlinger, Ministerpräsidentin des Saarlandes, an?',
      options: ['CDU', 'SPD', 'Grüne', 'FDP'],
      correct: [1],
      explanation: 'Anke Rehlinger ist Mitglied der SPD (Sozialdemokratische Partei Deutschlands).',
      difficulty: 1,
    },
    {
      type: 'truefalse',
      prompt: 'Friedrich Merz gehört der SPD an.',
      options: ['Wahr', 'Falsch'],
      correct: [1],
      explanation: 'Falsch. Friedrich Merz ist Mitglied der CDU (Christlich Demokratische Union). Er ist seit dem 6. Mai 2025 Bundeskanzler.',
      difficulty: 1,
    },
    {
      type: 'truefalse',
      prompt: 'Ursula von der Leyen ist Präsidentin des Europäischen Parlaments.',
      options: ['Wahr', 'Falsch'],
      correct: [1],
      explanation: 'Falsch. Ursula von der Leyen ist Präsidentin der Europäischen Kommission. Präsidentin des Europäischen Parlaments ist Roberta Metsola.',
      difficulty: 2,
    },
    {
      type: 'truefalse',
      prompt: 'Mark Rutte ist NATO-Generalsekretär (Stand 2026).',
      options: ['Wahr', 'Falsch'],
      correct: [0],
      explanation: 'Wahr. Mark Rutte (Niederlande) übernahm 2024 das Amt des NATO-Generalsekretärs von Jens Stoltenberg.',
      difficulty: 2,
    },
    {
      type: 'truefalse',
      prompt: 'Das Saarland wird (Stand 2026) von einer CDU-Ministerpräsidentin regiert.',
      options: ['Wahr', 'Falsch'],
      correct: [1],
      explanation: 'Falsch. Ministerpräsidentin des Saarlandes ist Anke Rehlinger, die der SPD angehört.',
      difficulty: 1,
    },
    {
      type: 'truefalse',
      prompt: 'António Costa ist Präsident des Europäischen Rates (Stand 2026).',
      options: ['Wahr', 'Falsch'],
      correct: [0],
      explanation: 'Wahr. António Costa (Portugal) ist seit Dezember 2024 Präsident des Europäischen Rates und löste Charles Michel ab.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welches Amt bekleidet Stephan Harbarth (Stand 2026)?',
      options: ['Bundesjustizminister', 'Präsident des Bundesverfassungsgerichts', 'Bundestagspräsident', 'Generalbundesanwalt'],
      correct: [1],
      explanation: 'Stephan Harbarth ist Präsident des Bundesverfassungsgerichts in Karlsruhe.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Wer war unmittelbarer Amtsvorgänger von Friedrich Merz als Bundeskanzler?',
      options: ['Angela Merkel', 'Gerhard Schröder', 'Olaf Scholz', 'Armin Laschet'],
      correct: [2],
      explanation: 'Olaf Scholz (SPD) war von Dezember 2021 bis Mai 2025 Bundeskanzler und wurde von Friedrich Merz abgelöst.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welcher Portugiese leitet (Stand 2026) die Vereinten Nationen als Generalsekretär?',
      options: ['António Costa', 'António Guterres', 'Marcelo Rebelo de Sousa', 'José Manuel Barroso'],
      correct: [1],
      explanation: 'António Guterres ist als UN-Generalsekretär tätig. António Costa ist hingegen Präsident des Europäischen Rates – beide sind Portugiesen.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Wer ist Präsidentin des Europäischen Parlaments (Stand 2026)?',
      options: ['Ursula von der Leyen', 'Christine Lagarde', 'Roberta Metsola', 'Federica Mogherini'],
      correct: [2],
      explanation: 'Roberta Metsola aus Malta (EVP) ist Präsidentin des Europäischen Parlaments.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Seit wann ist Donald Trump erneut US-Präsident (zweite Amtszeit)?',
      options: ['Januar 2024', 'November 2024', 'Januar 2025', 'März 2025'],
      correct: [2],
      explanation: 'Donald Trump wurde im November 2024 gewählt und trat seine zweite Amtszeit als US-Präsident im Januar 2025 an.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Wer ist Bundestagspräsidentin (Stand 2026)?',
      options: ['Julia Klöckner', 'Bärbel Bas', 'Franziska Giffey', 'Nancy Faeser'],
      correct: [0],
      explanation: 'Julia Klöckner (CDU) ist Bundestagspräsidentin. Ihre Vorgängerin Bärbel Bas (SPD) hatte dieses Amt in der vorherigen Legislaturperiode inne.',
      difficulty: 2,
    },
    {
      type: 'fill',
      prompt: 'Der Bundespräsident der Bundesrepublik Deutschland heißt Frank-Walter ___.',
      options: ['Steinmeier', 'Steinbrück', 'Steinbach', 'Steiner'],
      correct: [0],
      explanation: 'Frank-Walter Steinmeier ist Bundespräsident. Er wurde 2017 erstmals und 2022 für eine zweite Amtszeit gewählt.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welches Amt hat Mark Rutte inne (Stand 2026)?',
      options: ['Präsident des Europäischen Rates', 'NATO-Generalsekretär', 'Ministerpräsident der Niederlande', 'UN-Generalsekretär'],
      correct: [1],
      explanation: 'Mark Rutte ist NATO-Generalsekretär. Als Ministerpräsident der Niederlande wurde er inzwischen abgelöst.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welches Amt hat António Costa inne (Stand 2026)?',
      options: ['UN-Generalsekretär', 'NATO-Generalsekretär', 'Präsident des Europäischen Rates', 'Präsident der Europäischen Kommission'],
      correct: [2],
      explanation: 'António Costa ist Präsident des Europäischen Rates. Nicht zu verwechseln mit António Guterres, dem UN-Generalsekretär.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Welches Ressort leitet Reinhold Jost im Saarland (Stand 2026)?',
      options: ['Finanzen und Europa', 'Wirtschaft, Innovation, Digitales und Energie', 'Inneres, Bauen und Sport', 'Bildung und Kultur'],
      correct: [2],
      explanation: 'Reinhold Jost ist Minister für Inneres, Bauen und Sport im Saarland.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Welchem Staatenbund gehört Roberta Metsola an (Heimatland)?',
      options: ['Italien', 'Malta', 'Luxemburg', 'Zypern'],
      correct: [1],
      explanation: 'Roberta Metsola kommt aus Malta und ist Mitglied der Nationalist Party (EVP-Mitglied).',
      difficulty: 3,
    },
    {
      type: 'truefalse',
      prompt: 'Der UN-Generalsekretär António Guterres kommt aus Spanien.',
      options: ['Wahr', 'Falsch'],
      correct: [1],
      explanation: 'Falsch. António Guterres kommt aus Portugal, nicht aus Spanien.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Wer war NATO-Generalsekretär unmittelbar vor Mark Rutte?',
      options: ['Anders Fogh Rasmussen', 'Jaap de Hoop Scheffer', 'Jens Stoltenberg', 'George Robertson'],
      correct: [2],
      explanation: 'Jens Stoltenberg (Norwegen) war von 2014 bis 2024 NATO-Generalsekretär und wurde von Mark Rutte abgelöst.',
      difficulty: 2,
    },
  ],
};

export default topic;
