import type { RawTopic } from '../types';

const topic: RawTopic = {
  slug: 'antonyme',
  title: 'Antonyme',
  description: 'Gegenteile von Wörtern erkennen.',
  flashcards: [
    { front: 'zentral', back: 'dezentral' },
    { front: 'hell', back: 'dunkel' },
    { front: 'Erfolg', back: 'Misserfolg' },
    { front: 'künstlich', back: 'natürlich' },
    { front: 'sparsam', back: 'verschwenderisch' },
    { front: 'transparent', back: 'undurchsichtig' },
    { front: 'optimistisch', back: 'pessimistisch' },
    { front: 'abstrakt', back: 'konkret' },
    { front: 'modern', back: 'altmodisch' },
    { front: 'Mehrheit', back: 'Minderheit' },
    { front: 'objektiv', back: 'subjektiv' },
    { front: 'aktiv', back: 'passiv' },
    { front: 'konstruktiv', back: 'destruktiv' },
    { front: 'progressiv', back: 'konservativ' },
    { front: 'explizit', back: 'implizit' },
    { front: 'flexibel', back: 'starr / unflexibel' },
    { front: 'effizient', back: 'ineffizient' },
    { front: 'legal', back: 'illegal' },
    { front: 'relevant', back: 'irrelevant' },
    { front: 'Zustimmung', back: 'Ablehnung' },
    { front: 'mutig', back: 'feige' },
    { front: 'großzügig', back: 'geizig' },
  ],
  questions: [
    {
      type: 'mc',
      prompt: 'Was ist das Gegenteil von "zentral"?',
      options: ['dezentral', 'mittig', 'wichtig', 'örtlich'],
      correct: [0],
      explanation: 'Das Gegenteil von zentral ist dezentral – also nicht von einer Mitte aus gesteuert.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist das Gegenteil von "hell"?',
      options: ['strahlend', 'leuchtend', 'dunkel', 'klar'],
      correct: [2],
      explanation: 'Das Gegenteil von hell ist dunkel.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist das Gegenteil von "Erfolg"?',
      options: ['Leistung', 'Misserfolg', 'Ergebnis', 'Fortschritt'],
      correct: [1],
      explanation: 'Das Gegenteil von Erfolg ist Misserfolg.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist das Gegenteil von "künstlich"?',
      options: ['synthetisch', 'industriell', 'gefärbt', 'natürlich'],
      correct: [3],
      explanation: 'Das Gegenteil von künstlich ist natürlich.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist das Gegenteil von "sparsam"?',
      options: ['haushälterisch', 'verschwenderisch', 'bedächtig', 'wirtschaftlich'],
      correct: [1],
      explanation: 'Das Gegenteil von sparsam ist verschwenderisch.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist das Gegenteil von "transparent"?',
      options: ['klar', 'offen', 'undurchsichtig', 'sichtbar'],
      correct: [2],
      explanation: 'Das Gegenteil von transparent ist undurchsichtig.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was ist das Gegenteil von "optimistisch"?',
      options: ['hoffnungsvoll', 'pessimistisch', 'zuversichtlich', 'positiv'],
      correct: [1],
      explanation: 'Das Gegenteil von optimistisch ist pessimistisch.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist das Gegenteil von "abstrakt"?',
      options: ['theoretisch', 'vage', 'komplex', 'konkret'],
      correct: [3],
      explanation: 'Das Gegenteil von abstrakt ist konkret – also greifbar und gegenständlich.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was ist das Gegenteil von "modern"?',
      options: ['zeitgemäß', 'aktuell', 'altmodisch', 'innovativ'],
      correct: [2],
      explanation: 'Das Gegenteil von modern ist altmodisch.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist das Gegenteil von "Mehrheit"?',
      options: ['Menge', 'Minderheit', 'Gesamtheit', 'Gruppe'],
      correct: [1],
      explanation: 'Das Gegenteil von Mehrheit ist Minderheit.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist das Gegenteil von "objektiv"?',
      options: ['sachlich', 'neutral', 'subjektiv', 'unvoreingenommen'],
      correct: [2],
      explanation: 'Das Gegenteil von objektiv ist subjektiv – also von persönlichen Ansichten geprägt.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was ist das Gegenteil von "aktiv"?',
      options: ['tätig', 'rührig', 'beteiligt', 'passiv'],
      correct: [3],
      explanation: 'Das Gegenteil von aktiv ist passiv.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist das Gegenteil von "konstruktiv"?',
      options: ['aufbauend', 'lösungsorientiert', 'destruktiv', 'förderlich'],
      correct: [2],
      explanation: 'Das Gegenteil von konstruktiv ist destruktiv.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was ist das Gegenteil von "progressiv"?',
      options: ['fortschrittlich', 'modern', 'dynamisch', 'konservativ'],
      correct: [3],
      explanation: 'Das Gegenteil von progressiv ist konservativ.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was ist das Gegenteil von "explizit"?',
      options: ['deutlich', 'klar', 'implizit', 'ausdrücklich'],
      correct: [2],
      explanation: 'Das Gegenteil von explizit ist implizit – also nicht ausdrücklich formuliert, sondern mitgemeint.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Was ist das Gegenteil von "flexibel"?',
      options: ['anpassungsfähig', 'beweglich', 'wandelbar', 'starr'],
      correct: [3],
      explanation: 'Das Gegenteil von flexibel ist starr oder unflexibel.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist das Gegenteil von "effizient"?',
      options: ['wirkungsvoll', 'produktiv', 'ineffizient', 'leistungsstark'],
      correct: [2],
      explanation: 'Das Gegenteil von effizient ist ineffizient.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was ist das Gegenteil von "legal"?',
      options: ['rechtmäßig', 'erlaubt', 'gestattet', 'illegal'],
      correct: [3],
      explanation: 'Das Gegenteil von legal ist illegal.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist das Gegenteil von "relevant"?',
      options: ['bedeutsam', 'wesentlich', 'irrelevant', 'wichtig'],
      correct: [2],
      explanation: 'Das Gegenteil von relevant ist irrelevant – also ohne Bedeutung für den Sachverhalt.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was ist das Gegenteil von "Zustimmung"?',
      options: ['Einverständnis', 'Billigung', 'Erlaubnis', 'Ablehnung'],
      correct: [3],
      explanation: 'Das Gegenteil von Zustimmung ist Ablehnung.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist das Gegenteil von "mutig"?',
      options: ['tapfer', 'beherzt', 'feige', 'entschlossen'],
      correct: [2],
      explanation: 'Das Gegenteil von mutig ist feige.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist das Gegenteil von "großzügig"?',
      options: ['freigiebig', 'edelmütig', 'generös', 'geizig'],
      correct: [3],
      explanation: 'Das Gegenteil von großzügig ist geizig.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist das Gegenteil von "laut"?',
      options: ['dröhnend', 'hallend', 'grell', 'leise'],
      correct: [3],
      explanation: 'Das Gegenteil von laut ist leise.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist das Gegenteil von "komplex"?',
      options: ['vielschichtig', 'einfach', 'verschachtelt', 'verworren'],
      correct: [1],
      explanation: 'Das Gegenteil von komplex ist einfach oder simpel.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist das Gegenteil von "anonym"?',
      options: ['unbekannt', 'namenlos', 'namentlich', 'verborgen'],
      correct: [2],
      explanation: 'Das Gegenteil von anonym ist namentlich oder namentlich bekannt.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was ist das Gegenteil von "obligatorisch"?',
      options: ['verpflichtend', 'verbindlich', 'vorgeschrieben', 'freiwillig'],
      correct: [3],
      explanation: 'Das Gegenteil von obligatorisch (= verpflichtend) ist freiwillig.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Was ist das Gegenteil von "stationär"?',
      options: ['ortsfest', 'fest installiert', 'mobil', 'ruhend'],
      correct: [2],
      explanation: 'Das Gegenteil von stationär ist mobil.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was ist das Gegenteil von "dominant"?',
      options: ['beherrschend', 'führend', 'untergeordnet', 'mächtig'],
      correct: [2],
      explanation: 'Das Gegenteil von dominant ist untergeordnet oder submissiv.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was ist das Gegenteil von "chronisch"?',
      options: ['dauerhaft', 'anhaltend', 'wiederkehrend', 'akut'],
      correct: [3],
      explanation: 'Das Gegenteil von chronisch (= dauerhaft) ist akut (= plötzlich/kurzfristig).',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Was ist das Gegenteil von "stabil"?',
      options: ['beständig', 'fest', 'instabil', 'dauerhaft'],
      correct: [2],
      explanation: 'Das Gegenteil von stabil ist instabil.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist das Gegenteil von "öffentlich"?',
      options: ['allgemein', 'staatlich', 'privat', 'gemeinschaftlich'],
      correct: [2],
      explanation: 'Das Gegenteil von öffentlich ist privat.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist das Gegenteil von "Anfang"?',
      options: ['Beginn', 'Start', 'Auftakt', 'Ende'],
      correct: [3],
      explanation: 'Das Gegenteil von Anfang ist Ende.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist das Gegenteil von "freiwillig"?',
      options: ['selbstbestimmt', 'spontan', 'unaufgefordert', 'verpflichtend'],
      correct: [3],
      explanation: 'Das Gegenteil von freiwillig ist verpflichtend oder obligatorisch.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist das Gegenteil von "fiktiv"?',
      options: ['erfunden', 'imaginär', 'erdacht', 'real'],
      correct: [3],
      explanation: 'Das Gegenteil von fiktiv ist real oder wirklich.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was ist das Gegenteil von "konvex"?',
      options: ['gewölbt', 'rund', 'geschwungen', 'konkav'],
      correct: [3],
      explanation: 'Das Gegenteil von konvex (nach außen gewölbt) ist konkav (nach innen gewölbt).',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Was ist das Gegenteil von "seriös"?',
      options: ['ernsthaft', 'zuverlässig', 'vertrauenswürdig', 'unseriös'],
      correct: [3],
      explanation: 'Das Gegenteil von seriös ist unseriös.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist das Gegenteil von "rational"?',
      options: ['vernünftig', 'logisch', 'irrational', 'durchdacht'],
      correct: [2],
      explanation: 'Das Gegenteil von rational ist irrational.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was ist das Gegenteil von "Expansion"?',
      options: ['Wachstum', 'Ausdehnung', 'Ausweitung', 'Kontraktion'],
      correct: [3],
      explanation: 'Das Gegenteil von Expansion ist Kontraktion – also Verkleinerung oder Schrumpfung.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Was ist das Gegenteil von "loyal"?',
      options: ['treu', 'ergeben', 'vertrauensvoll', 'verräterisch'],
      correct: [3],
      explanation: 'Das Gegenteil von loyal ist verräterisch oder illoyal.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was ist das Gegenteil von "nüchtern"?',
      options: ['sachlich', 'besonnen', 'betrunken', 'klar'],
      correct: [2],
      explanation: 'Das Gegenteil von nüchtern ist betrunken (im wörtlichen Sinn) oder auch enthusiastisch/überschwänglich (im übertragenen Sinn).',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was ist das Gegenteil von "Zunahme"?',
      options: ['Steigerung', 'Anstieg', 'Abnahme', 'Zuwachs'],
      correct: [2],
      explanation: 'Das Gegenteil von Zunahme ist Abnahme.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist das Gegenteil von "uniform"?',
      options: ['einheitlich', 'gleich', 'identisch', 'vielfältig'],
      correct: [3],
      explanation: 'Das Gegenteil von uniform (= einheitlich) ist vielfältig oder divers.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was ist das Gegenteil von "introvertiert"?',
      options: ['verschlossen', 'schüchtern', 'zurückgezogen', 'extrovertiert'],
      correct: [3],
      explanation: 'Das Gegenteil von introvertiert ist extrovertiert.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was ist das Gegenteil von "exklusiv"?',
      options: ['hochwertig', 'auserwählt', 'selten', 'inklusiv'],
      correct: [3],
      explanation: 'Das Gegenteil von exklusiv (= ausschließend) ist inklusiv (= einschließend).',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Was ist das Gegenteil von "permanent"?',
      options: ['dauerhaft', 'beständig', 'unveränderlich', 'temporär'],
      correct: [3],
      explanation: 'Das Gegenteil von permanent ist temporär – also vorübergehend.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was ist das Gegenteil von "vertikal"?',
      options: ['steil', 'senkrecht', 'aufrecht', 'horizontal'],
      correct: [3],
      explanation: 'Das Gegenteil von vertikal (= senkrecht) ist horizontal (= waagerecht).',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was ist das Gegenteil von "Fleiß"?',
      options: ['Ausdauer', 'Eifer', 'Hingabe', 'Faulheit'],
      correct: [3],
      explanation: 'Das Gegenteil von Fleiß ist Faulheit.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist das Gegenteil von "präzise"?',
      options: ['genau', 'exakt', 'akkurat', 'ungenau'],
      correct: [3],
      explanation: 'Das Gegenteil von präzise ist ungenau oder vage.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist das Gegenteil von "Harmonie"?',
      options: ['Einklang', 'Übereinstimmung', 'Gleichklang', 'Disharmonie'],
      correct: [3],
      explanation: 'Das Gegenteil von Harmonie ist Disharmonie oder Konflikt.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist das Gegenteil von "intuitiv"?',
      options: ['spontan', 'instinktiv', 'unbewusst', 'rational'],
      correct: [3],
      explanation: 'Das Gegenteil von intuitiv ist rational oder analytisch.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was ist das Gegenteil von "Zuversicht"?',
      options: ['Vertrauen', 'Hoffnung', 'Optimismus', 'Verzweiflung'],
      correct: [3],
      explanation: 'Das Gegenteil von Zuversicht ist Verzweiflung oder Pessimismus.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was ist das Gegenteil von "gerecht"?',
      options: ['fair', 'billig', 'rechtmäßig', 'ungerecht'],
      correct: [3],
      explanation: 'Das Gegenteil von gerecht ist ungerecht.',
      difficulty: 1,
    },
    {
      type: 'fill',
      prompt: 'Nenne das Gegenteil von "hell".',
      correct: ['dunkel', 'finster'],
      explanation: 'Das Gegenteil von hell ist dunkel oder finster.',
      difficulty: 1,
    },
    {
      type: 'fill',
      prompt: 'Nenne das Gegenteil von "sparsam".',
      correct: ['verschwenderisch', 'freigiebig'],
      explanation: 'Das Gegenteil von sparsam ist verschwenderisch.',
      difficulty: 1,
    },
    {
      type: 'fill',
      prompt: 'Nenne das Gegenteil von "aktiv".',
      correct: ['passiv', 'untätig'],
      explanation: 'Das Gegenteil von aktiv ist passiv oder untätig.',
      difficulty: 1,
    },
    {
      type: 'fill',
      prompt: 'Nenne das Gegenteil von "transparent".',
      correct: ['undurchsichtig', 'opak', 'intransparent'],
      explanation: 'Das Gegenteil von transparent ist undurchsichtig oder opak.',
      difficulty: 2,
    },
    {
      type: 'fill',
      prompt: 'Nenne das Gegenteil von "konstruktiv".',
      correct: ['destruktiv', 'zerstörerisch'],
      explanation: 'Das Gegenteil von konstruktiv ist destruktiv.',
      difficulty: 2,
    },
    {
      type: 'fill',
      prompt: 'Nenne das Gegenteil von "obligatorisch".',
      correct: ['freiwillig', 'optional', 'fakultativ'],
      explanation: 'Das Gegenteil von obligatorisch ist freiwillig, optional oder fakultativ.',
      difficulty: 3,
    },
  ],
};

export default topic;
