import type { RawTopic } from '../types';

const topic: RawTopic = {
  slug: 'demokratie-wahlen',
  title: 'Demokratie, Wahlen & Parteien',
  description: 'Wahlgrundsätze, Wahlsystem und Parteien in Deutschland.',
  flashcards: [
    {
      front: 'Welche 5 Wahlgrundsätze gelten in Deutschland gemäß Art. 38 GG?',
      back: 'Allgemein, unmittelbar, frei, gleich und geheim. Alle Bürgerinnen und Bürger mit Wahlberechtigung dürfen wählen, ohne Zwischenpersonen, ohne Druck, mit gleichem Stimmgewicht und ohne Offenbarung ihrer Wahlentscheidung.',
    },
    {
      front: 'Was bedeutet das Wahlprinzip "allgemein"?',
      back: 'Jede wahlberechtigte Person darf an der Wahl teilnehmen, unabhängig von Geschlecht, Herkunft, Bildung, Einkommen oder Religion. Ausschlüsse sind nur in eng begrenzten gesetzlichen Ausnahmefällen zulässig.',
    },
    {
      front: 'Was bedeutet das Wahlprinzip "unmittelbar"?',
      back: 'Die Wählerinnen und Wähler wählen ihre Abgeordneten direkt, ohne Wahlmänner oder andere Zwischenstufen. Das Wahlergebnis ergibt sich unmittelbar aus den abgegebenen Stimmen.',
    },
    {
      front: 'Was bedeutet das Wahlprinzip "frei"?',
      back: 'Die Wahlentscheidung darf nicht durch Druck, Zwang oder unzulässige Beeinflussung gesteuert werden. Jede Wählerin und jeder Wähler entscheidet ohne staatlichen oder privaten Zwang.',
    },
    {
      front: 'Was bedeutet das Wahlprinzip "gleich"?',
      back: 'Jede Stimme hat dasselbe Gewicht (Zählwert- und Erfolgswertgleichheit). Niemandes Stimme zählt mehr als die einer anderen Person.',
    },
    {
      front: 'Was bedeutet das Wahlprinzip "geheim"?',
      back: 'Die Wahlentscheidung ist vertraulich. Niemand darf gezwungen werden, die eigene Wahl offenzulegen. Wahlkabinen und versiegelte Umschläge sichern das geheime Wahlrecht.',
    },
    {
      front: 'Was ist die Erststimme bei der Bundestagswahl?',
      back: 'Mit der Erststimme wählt man eine Direktkandidatin oder einen Direktkandidaten im eigenen Wahlkreis. Wer die meisten Erststimmen im Wahlkreis erhält, zieht direkt als Abgeordneter in den Bundestag ein (Direktmandat).',
    },
    {
      front: 'Was ist die Zweitstimme bei der Bundestagswahl?',
      back: 'Mit der Zweitstimme wählt man eine Partei (Landesliste). Die Zweitstimme ist wahlentscheidend für die Sitzverteilung im Bundestag und damit für die Stärke der Fraktionen.',
    },
    {
      front: 'Was ist die 5-Prozent-Hürde?',
      back: 'Eine Partei muss bundesweit mindestens 5 % der Zweitstimmen oder 3 Direktmandate erhalten, um in den Bundestag einzuziehen. Sie soll eine Zersplitterung des Parlaments verhindern.',
    },
    {
      front: 'Was versteht man unter "personalisierter Verhältniswahl"?',
      back: 'Das deutsche Wahlsystem verbindet die Verhältniswahl (Zweitstimme bestimmt Sitzverteilung) mit der Persönlichkeitswahl (Erststimme für Direktkandidaten). Dadurch sind sowohl Parteienproporz als auch persönliche Repräsentation möglich.',
    },
    {
      front: 'Ab welchem Alter darf man in Deutschland den Bundestag wählen (aktives Wahlrecht)?',
      back: 'Das aktive Wahlrecht beim Bundestag beginnt mit dem vollendeten 18. Lebensjahr.',
    },
    {
      front: 'Wie lange dauert eine Wahlperiode des Deutschen Bundestages?',
      back: 'Eine Wahlperiode dauert regulär 4 Jahre. Danach finden Neuwahlen statt. In Ausnahmefällen kann der Bundestag früher aufgelöst werden.',
    },
    {
      front: 'Was ist der Unterschied zwischen repräsentativer und direkter Demokratie?',
      back: 'Bei der repräsentativen Demokratie wählt das Volk Vertreterinnen und Vertreter, die politische Entscheidungen treffen (z. B. Bundestagswahl). Bei der direkten Demokratie entscheiden die Bürgerinnen und Bürger selbst über Sachfragen (z. B. Volksentscheid). Deutschland ist hauptsächlich eine repräsentative Demokratie.',
    },
    {
      front: 'Welche Aufgaben haben Parteien laut Art. 21 GG?',
      back: 'Parteien wirken bei der politischen Willensbildung des Volkes mit. Sie informieren, mobilisieren, rekrutieren politisches Personal, vermitteln zwischen Bürgerinnen und Bürgern sowie staatlichen Organen und formulieren politische Programme.',
    },
    {
      front: 'Was ist eine Koalition?',
      back: 'Eine Koalition ist ein Regierungsbündnis aus mindestens zwei Parteien, die gemeinsam eine Regierungsmehrheit bilden und einen Koalitionsvertrag schließen. Seit dem 6. Mai 2025 regiert eine Koalition aus CDU/CSU und SPD unter Bundeskanzler Friedrich Merz.',
    },
    {
      front: 'Was ist die Opposition im Parlament?',
      back: 'Die Opposition umfasst die Fraktionen im Parlament, die nicht an der Regierung beteiligt sind. Sie kontrolliert die Regierung, stellt Alternativvorschläge vor und übt konstruktive Kritik.',
    },
    {
      front: 'Wann fand die letzte Bundestagswahl statt, und welcher Bundestag wurde gewählt?',
      back: 'Die letzte Bundestagswahl fand am 23. Februar 2025 statt. Sie konstituierte den 21. Deutschen Bundestag mit 630 Sitzen.',
    },
    {
      front: 'Wer ist seit dem 6. Mai 2025 Bundeskanzler Deutschlands?',
      back: 'Friedrich Merz (CDU) ist seit dem 6. Mai 2025 Bundeskanzler der Bundesrepublik Deutschland. Er führt eine Koalitionsregierung aus CDU/CSU und SPD.',
    },
    {
      front: 'Welche Fraktionen sind im 21. Bundestag (Stand 2026) vertreten?',
      back: 'Im 21. Bundestag sind folgende Fraktionen vertreten: CDU/CSU, AfD, SPD, Bündnis 90/Die Grünen und Die Linke. Zusätzlich ist der SSW als Einzelvertretung im Bundestag präsent.',
    },
    {
      front: 'Was ist ein Direktmandat?',
      back: 'Ein Direktmandat erhält die Kandidatin oder der Kandidat, die bzw. der in einem Wahlkreis die meisten Erststimmen auf sich vereint. Direktmandate werden unabhängig vom Zweitstimmenergebnis vergeben.',
    },
    {
      front: 'Wie viele Sitze hat der 21. Deutsche Bundestag?',
      back: 'Der 21. Deutsche Bundestag hat 630 Sitze. Die Sitzanzahl wurde durch die Wahlrechtsreform 2023 auf 630 festgelegt, um das Parlament zu verkleinern.',
    },
  ],
  questions: [
    {
      type: 'mc',
      prompt: 'Wie viele Wahlgrundsätze enthält Art. 38 GG für Bundestagswahlen?',
      options: ['3', '4', '5', '6'],
      correct: [2],
      explanation: 'Art. 38 GG nennt fünf Wahlgrundsätze: allgemein, unmittelbar, frei, gleich und geheim.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet das Wahlprinzip "unmittelbar"?',
      options: [
        'Die Wahl findet ohne Wahlkabine statt.',
        'Die Abgeordneten werden direkt ohne Zwischenpersonen gewählt.',
        'Die Stimmenauszählung erfolgt sofort nach Wahlschluss.',
        'Alle Bürgerinnen und Bürger dürfen wählen.',
      ],
      correct: [1],
      explanation: '"Unmittelbar" bedeutet, dass keine Wahlmänner oder andere Zwischenstufen zwischen Wählerin bzw. Wähler und Abgeordneten stehen.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welcher Wahlgrundsatz schützt davor, dass jemand zur Stimmabgabe gezwungen wird?',
      options: ['Gleich', 'Geheim', 'Frei', 'Allgemein'],
      correct: [2],
      explanation: 'Das Prinzip "frei" schützt vor Zwang und unzulässiger Beeinflussung bei der Wahlentscheidung.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Mit welcher Stimme wählt man bei der Bundestagswahl eine Partei (Landesliste)?',
      options: ['Erststimme', 'Drittststimme', 'Zweitstimme', 'Direktstimme'],
      correct: [2],
      explanation: 'Mit der Zweitstimme wählt man eine Partei bzw. deren Landesliste. Sie ist maßgeblich für die Sitzverteilung im Bundestag.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was bestimmt die Zweitstimme bei der Bundestagswahl hauptsächlich?',
      options: [
        'Welche Person Bundeskanzlerin oder Bundeskanzler wird.',
        'Die Sitzverteilung der Parteien im Bundestag.',
        'Wer Direktmandat im Wahlkreis erhält.',
        'Die Anzahl der Wahlkreise.',
      ],
      correct: [1],
      explanation: 'Die Zweitstimme ist die wahlentscheidende Stimme für die proportionale Sitzverteilung der Parteien im Bundestag.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Ab welchem Alter gilt das aktive Wahlrecht für die Bundestagswahl?',
      options: ['16 Jahre', '18 Jahre', '21 Jahre', '25 Jahre'],
      correct: [1],
      explanation: 'Das aktive Wahlrecht für die Bundestagswahl besteht ab Vollendung des 18. Lebensjahres (Art. 38 Abs. 2 GG).',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Wie lange dauert eine reguläre Wahlperiode des Deutschen Bundestages?',
      options: ['3 Jahre', '4 Jahre', '5 Jahre', '6 Jahre'],
      correct: [1],
      explanation: 'Eine Wahlperiode des Bundestages beträgt regulär 4 Jahre (Art. 39 GG).',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welche Mindesthürde muss eine Partei bei der Bundestagswahl überwinden, um in den Bundestag einzuziehen?',
      options: [
        '3 % der Zweitstimmen oder 1 Direktmandat',
        '5 % der Zweitstimmen oder 3 Direktmandate',
        '5 % der Erststimmen oder 5 Direktmandate',
        '10 % der Zweitstimmen oder 5 Direktmandate',
      ],
      correct: [1],
      explanation: 'Die 5-Prozent-Klausel: Eine Partei benötigt mindestens 5 % der Zweitstimmen oder 3 Direktmandate, um in den Bundestag einzuziehen.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Wie nennt man das deutsche Wahlsystem, das Verhältnis- und Persönlichkeitswahl verbindet?',
      options: [
        'Mehrheitswahlrecht',
        'Personalisierte Verhältniswahl',
        'Absolute Mehrheitswahl',
        'Panaschiertes Wahlrecht',
      ],
      correct: [1],
      explanation: 'Das deutsche Wahlsystem heißt "personalisierte Verhältniswahl": Die Erststimme wählt eine Person (Direktkandidat), die Zweitstimme bestimmt die Proportionalverteilung.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Wann fand die letzte Bundestagswahl statt?',
      options: [
        '26. September 2021',
        '12. März 2024',
        '23. Februar 2025',
        '15. Oktober 2025',
      ],
      correct: [2],
      explanation: 'Die letzte Bundestagswahl fand am 23. Februar 2025 statt und konstituierte den 21. Deutschen Bundestag.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Wie viele Sitze hat der 21. Deutsche Bundestag?',
      options: ['598', '709', '630', '736'],
      correct: [2],
      explanation: 'Der 21. Deutsche Bundestag hat 630 Sitze, festgelegt durch die Wahlrechtsreform von 2023.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Wer ist seit dem 6. Mai 2025 Bundeskanzler der Bundesrepublik Deutschland?',
      options: [
        'Olaf Scholz (SPD)',
        'Friedrich Merz (CDU)',
        'Robert Habeck (Grüne)',
        'Alice Weidel (AfD)',
      ],
      correct: [1],
      explanation: 'Friedrich Merz (CDU) wurde am 6. Mai 2025 zum Bundeskanzler gewählt und führt eine Koalition aus CDU/CSU und SPD.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welche Koalition regiert Deutschland seit Mai 2025?',
      options: [
        'CDU/CSU und FDP',
        'SPD, Grüne und FDP',
        'CDU/CSU und SPD',
        'CDU/CSU, SPD und Grüne',
      ],
      correct: [2],
      explanation: 'Seit dem 6. Mai 2025 regiert eine Große Koalition aus CDU/CSU und SPD unter Bundeskanzler Friedrich Merz.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welche der folgenden Parteien ist KEINE Fraktion im 21. Deutschen Bundestag (Stand 2026)?',
      options: ['AfD', 'FDP', 'Die Linke', 'SPD'],
      correct: [1],
      explanation: 'Die FDP scheiterte bei der Bundestagswahl 2025 an der 5-Prozent-Hürde und ist nicht im 21. Bundestag vertreten.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'In welchem Artikel des Grundgesetzes sind die Aufgaben der Parteien verankert?',
      options: ['Art. 20 GG', 'Art. 21 GG', 'Art. 38 GG', 'Art. 63 GG'],
      correct: [1],
      explanation: 'Art. 21 GG regelt die Rolle der Parteien: Sie wirken bei der politischen Willensbildung des Volkes mit.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was unterscheidet die repräsentative von der direkten Demokratie?',
      options: [
        'In der repräsentativen Demokratie gibt es keine Wahlen.',
        'In der direkten Demokratie entscheiden gewählte Vertreter für das Volk.',
        'In der repräsentativen Demokratie entscheiden gewählte Vertreter, in der direkten Demokratie die Bürgerinnen und Bürger selbst.',
        'Repräsentative Demokratie ist nur in Monarchien möglich.',
      ],
      correct: [2],
      explanation: 'Bei der repräsentativen Demokratie werden Vertreter gewählt, die Entscheidungen treffen. Bei der direkten Demokratie stimmen Bürgerinnen und Bürger direkt über Sachfragen ab.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist eine Opposition im parlamentarischen System?',
      options: [
        'Die Partei, die den Bundespräsidenten stellt.',
        'Parteien im Parlament, die nicht an der Regierung beteiligt sind.',
        'Eine außerparlamentarische Bewegung gegen die Regierung.',
        'Die Mehrheitsfraktion im Bundesrat.',
      ],
      correct: [1],
      explanation: 'Die parlamentarische Opposition umfasst Fraktionen, die nicht der Regierungskoalition angehören, und übt Kontrolle sowie Kritik an der Regierung aus.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was erhält eine Kandidatin oder ein Kandidat, der bzw. die im Wahlkreis die meisten Erststimmen gewinnt?',
      options: ['Listenplatz', 'Direktmandat', 'Ehrenmandat', 'Fraktionsvorsitz'],
      correct: [1],
      explanation: 'Wer in einem Wahlkreis die relative Mehrheit der Erststimmen erhält, gewinnt das Direktmandat und zieht direkt in den Bundestag ein.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welche Fraktion ist zusätzlich zu den Fraktionen im 21. Bundestag als Einzelvertretung präsent?',
      options: ['Die Basis', 'BSW', 'SSW', 'FDP'],
      correct: [2],
      explanation: 'Der SSW (Südschleswigscher Wählerverband) ist als Vertretung der dänischen Minderheit von der 5-Prozent-Hürde befreit und im 21. Bundestag als Einzelvertretung präsent.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Welches Prinzip soll die 5-Prozent-Hürde hauptsächlich verhindern?',
      options: [
        'Zu hohe Wahlbeteiligung',
        'Übermäßige Machtkonzentration bei einer Partei',
        'Zersplitterung des Parlaments in viele kleine Parteien',
        'Wahlbetrug durch kleine Parteien',
      ],
      correct: [2],
      explanation: 'Die 5-Prozent-Hürde soll verhindern, dass zu viele Kleinstparteien ins Parlament einziehen und die Regierungsbildung erschweren.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welcher Wahlgrundsatz wird verletzt, wenn eine Wählerin unter Druck gesetzt wird, eine bestimmte Partei zu wählen?',
      options: ['Gleich', 'Allgemein', 'Frei', 'Unmittelbar'],
      correct: [2],
      explanation: 'Druck oder Zwang bei der Wahlentscheidung verletzt den Grundsatz der freien Wahl.',
      difficulty: 2,
    },
    {
      type: 'truefalse',
      prompt: 'Die Erststimme bestimmt hauptsächlich die Sitzverteilung der Parteien im Deutschen Bundestag.',
      options: ['Wahr', 'Falsch'],
      correct: [1],
      explanation: 'Falsch. Die Zweitstimme (Partei/Landesliste) ist entscheidend für die Sitzverteilung im Bundestag. Die Erststimme bestimmt, wer das Direktmandat im Wahlkreis erhält.',
      difficulty: 1,
    },
    {
      type: 'truefalse',
      prompt: 'Der 21. Deutsche Bundestag wurde am 23. Februar 2025 gewählt.',
      options: ['Wahr', 'Falsch'],
      correct: [0],
      explanation: 'Wahr. Die Bundestagswahl fand am 23. Februar 2025 statt und brachte den 21. Bundestag hervor.',
      difficulty: 1,
    },
    {
      type: 'truefalse',
      prompt: 'Deutschland ist hauptsächlich eine direkte Demokratie, in der Bürgerinnen und Bürger über alle Gesetze abstimmen.',
      options: ['Wahr', 'Falsch'],
      correct: [1],
      explanation: 'Falsch. Deutschland ist eine repräsentative Demokratie. Bürgerinnen und Bürger wählen Vertreter, die dann politische Entscheidungen treffen. Direkte Volksabstimmungen auf Bundesebene gibt es nicht.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welche Partei stellt seit dem 6. Mai 2025 den Bundeskanzler?',
      options: ['SPD', 'AfD', 'CDU', 'Bündnis 90/Die Grünen'],
      correct: [2],
      explanation: 'Die CDU stellt mit Friedrich Merz den Bundeskanzler. Er führt eine Koalition aus CDU/CSU und SPD.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was legt ein Koalitionsvertrag fest?',
      options: [
        'Die Kandidatenlisten der Parteien für die nächste Wahl.',
        'Gemeinsame politische Ziele und Vorhaben der Regierungsparteien.',
        'Die Geschäftsordnung des Bundestages.',
        'Die Amtszeit der Bundesministerin bzw. des Bundesministers.',
      ],
      correct: [1],
      explanation: 'Ein Koalitionsvertrag ist eine schriftliche Vereinbarung zwischen den Regierungsparteien über gemeinsame politische Ziele, Projekte und die Aufteilung der Ministerien.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welcher Grundsatz stellt sicher, dass niemand bei der Wahl benachteiligt wird und jede Stimme gleich viel zählt?',
      options: ['Frei', 'Geheim', 'Gleich', 'Unmittelbar'],
      correct: [2],
      explanation: 'Der Grundsatz "gleich" stellt sicher, dass jede abgegebene Stimme denselben Zähl- und Erfolgswert hat.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welche Aussage zu Art. 21 GG ist korrekt?',
      options: [
        'Parteien sind in Deutschland verboten.',
        'Parteien wirken bei der politischen Willensbildung des Volkes mit.',
        'Parteien dürfen keine Mitglieder aufnehmen.',
        'Nur staatlich anerkannte Parteien dürfen an Wahlen teilnehmen.',
      ],
      correct: [1],
      explanation: 'Art. 21 GG regelt die Mitwirkung der Parteien bei der politischen Willensbildung des Volkes und legt Grundbedingungen für deren innere Ordnung fest.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welche Mindeststimmanzahl (Zweitstimmen) benötigt eine Partei alternativ zur 5-Prozent-Hürde, um in den Bundestag einzuziehen?',
      options: [
        '1 Direktmandat',
        '2 Direktmandate',
        '3 Direktmandate',
        '5 Direktmandate',
      ],
      correct: [2],
      explanation: 'Als Alternative zur 5-Prozent-Hürde reichen 3 gewonnene Direktmandate, damit eine Partei proportional in den Bundestag einzieht (Grundmandatsklausel).',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Welche der folgenden Aussagen zur Bundestagswahl 2025 ist korrekt?',
      options: [
        'Die SPD wurde stärkste Kraft im Bundestag.',
        'Der 20. Bundestag wurde gewählt.',
        'Die Wahl fand am 23. Februar 2025 statt.',
        'Friedrich Merz kandidierte für die SPD.',
      ],
      correct: [2],
      explanation: 'Die Bundestagswahl 2025 fand am 23. Februar 2025 statt und konstituierte den 21. Deutschen Bundestag.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist KEIN Merkmal der repräsentativen Demokratie?',
      options: [
        'Bürgerinnen und Bürger wählen Volksvertreter.',
        'Volksvertreter entscheiden im Namen der Bevölkerung.',
        'Bürgerinnen und Bürger stimmen direkt über jedes Gesetz ab.',
        'Regelmäßige Wahlen finden statt.',
      ],
      correct: [2],
      explanation: 'Die direkte Abstimmung über jedes Gesetz ist ein Merkmal der direkten Demokratie, nicht der repräsentativen. In der repräsentativen Demokratie übernehmen gewählte Vertreter diese Aufgabe.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welche Fraktionen bilden die Regierungskoalition im 21. Deutschen Bundestag?',
      options: [
        'CDU/CSU und Bündnis 90/Die Grünen',
        'SPD und Bündnis 90/Die Grünen',
        'CDU/CSU und SPD',
        'AfD und CDU/CSU',
      ],
      correct: [2],
      explanation: 'Die Regierungskoalition im 21. Bundestag besteht aus CDU/CSU und SPD unter Bundeskanzler Friedrich Merz (seit 6. Mai 2025).',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welche Parteien bilden die Opposition im 21. Deutschen Bundestag (Stand 2026)?',
      options: [
        'CDU/CSU, AfD und SPD',
        'AfD, Bündnis 90/Die Grünen und Die Linke',
        'SPD und Bündnis 90/Die Grünen',
        'AfD und CDU/CSU',
      ],
      correct: [1],
      explanation: 'Da CDU/CSU und SPD die Regierungskoalition bilden, stellen AfD, Bündnis 90/Die Grünen und Die Linke die Opposition im 21. Bundestag.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welcher Wahlgrundsatz stellt sicher, dass die Wahlentscheidung vertraulich bleibt?',
      options: ['Allgemein', 'Frei', 'Gleich', 'Geheim'],
      correct: [3],
      explanation: 'Der Grundsatz "geheim" garantiert, dass niemand erfahren darf, wen jemand gewählt hat. Wahlkabinen und verschlossene Umschläge sichern dieses Recht.',
      difficulty: 1,
    },
    {
      type: 'fill',
      prompt: 'Das deutsche Wahlsystem heißt __________ Verhältniswahl, weil es Direktwahl und Proporzverteilung verbindet.',
      options: ['personalisierte', 'absolute', 'relative', 'gemischte'],
      correct: [0],
      explanation: 'Das System heißt "personalisierte Verhältniswahl", weil die persönliche Direktwahl (Erststimme) mit der proportionierten Listenverteilung (Zweitstimme) kombiniert wird.',
      difficulty: 2,
    },
  ],
};

export default topic;
