import type { RawTopic } from '../types';

const topic: RawTopic = {
  slug: 'edv-abkuerzungen',
  title: 'EDV-Abkürzungen',
  description: 'Wichtige Abkürzungen aus der IT verstehen.',
  flashcards: [
    { front: 'CPU', back: 'Central Processing Unit – der Hauptprozessor eines Computers, der Befehle ausführt und Berechnungen durchführt.' },
    { front: 'RAM', back: 'Random Access Memory – flüchtiger Arbeitsspeicher, der Daten temporär während des Betriebs speichert.' },
    { front: 'ROM', back: 'Read Only Memory – dauerhafter Festwertspeicher, der nur gelesen, aber nicht verändert werden kann.' },
    { front: 'HDD', back: 'Hard Disk Drive – magnetische Festplatte zur dauerhaften Datenspeicherung.' },
    { front: 'SSD', back: 'Solid State Drive – Flash-basierter Datenspeicher ohne bewegliche Teile, schneller als eine HDD.' },
    { front: 'USB', back: 'Universal Serial Bus – genormte Schnittstelle zum Anschluss von Peripheriegeräten an einen Computer.' },
    { front: 'URL', back: 'Uniform Resource Locator – eindeutige Adresse einer Ressource im Internet (z. B. einer Webseite).' },
    { front: 'HTML', back: 'HyperText Markup Language – Auszeichnungssprache zur Strukturierung von Webseiten.' },
    { front: 'HTTP', back: 'HyperText Transfer Protocol – Protokoll zur Übertragung von Webseiten im Internet.' },
    { front: 'HTTPS', back: 'HyperText Transfer Protocol Secure – verschlüsselte Variante von HTTP (mit TLS/SSL).' },
    { front: 'FTP', back: 'File Transfer Protocol – Protokoll zur Übertragung von Dateien zwischen Client und Server.' },
    { front: 'IP', back: 'Internet Protocol – Grundprotokoll zur Adressierung und Weiterleitung von Datenpaketen im Netzwerk.' },
    { front: 'DNS', back: 'Domain Name System – übersetzt Domainnamen (z. B. example.com) in IP-Adressen.' },
    { front: 'LAN', back: 'Local Area Network – lokales Netzwerk, das Computer in einem begrenzten Bereich verbindet.' },
    { front: 'WAN', back: 'Wide Area Network – weiträumiges Netzwerk, das mehrere lokale Netzwerke verbindet (z. B. das Internet).' },
    { front: 'WLAN', back: 'Wireless Local Area Network – drahtloses lokales Netzwerk (Wi-Fi).' },
    { front: 'PDF', back: 'Portable Document Format – plattformunabhängiges Dateiformat für Dokumente, entwickelt von Adobe.' },
    { front: 'GUI', back: 'Graphical User Interface – grafische Benutzeroberfläche zur visuellen Bedienung von Software.' },
    { front: 'OS', back: 'Operating System – Betriebssystem, das Hardware und Software verwaltet (z. B. Windows, Linux).' },
    { front: 'BIOS', back: 'Basic Input/Output System – Firmware, die beim Start eines Computers die Hardware initialisiert.' },
    { front: 'SQL', back: 'Structured Query Language – Datenbanksprache zum Abfragen und Verwalten relationaler Datenbanken.' },
    { front: 'API', back: 'Application Programming Interface – Schnittstelle, über die Programme miteinander kommunizieren können.' },
    { front: 'IDE', back: 'Integrated Development Environment – integrierte Entwicklungsumgebung für Programmierer (z. B. Visual Studio Code).' },
    { front: 'OOP', back: 'Objektorientierte Programmierung – Programmierparadigma, das auf Objekten und Klassen basiert.' },
    { front: 'CSS', back: 'Cascading Style Sheets – Stylesheet-Sprache zur Gestaltung von HTML-Webseiten.' },
    { front: 'VPN', back: 'Virtual Private Network – verschlüsselter Tunnel für sichere Verbindungen über das Internet.' },
    { front: 'DSL', back: 'Digital Subscriber Line – Technik zur Breitband-Internetübertragung über Telefonleitungen.' },
    { front: 'GPU', back: 'Graphics Processing Unit – Grafikprozessor für die Berechnung von Bildern und 3D-Grafiken.' },
    { front: 'OCR', back: 'Optical Character Recognition – optische Zeichenerkennung, die Text aus Bildern liest.' },
    { front: 'ERP', back: 'Enterprise Resource Planning – integrierte Unternehmenssoftware zur Verwaltung von Geschäftsprozessen.' },
    { front: 'CMS', back: 'Content Management System – Software zur Verwaltung digitaler Inhalte (z. B. WordPress).' },
    { front: 'SaaS', back: 'Software as a Service – Bereitstellung von Software über das Internet als Dienst (Abonnementmodell).' },
    { front: 'KI / AI', back: 'Künstliche Intelligenz / Artificial Intelligence – Simulation menschlicher Intelligenz durch Computer.' },
    { front: 'IoT', back: 'Internet of Things – Vernetzung physischer Geräte und Alltagsgegenstände mit dem Internet.' },
    { front: 'ASCII', back: 'American Standard Code for Information Interchange – zeichenkodierter Standard für Buchstaben und Sonderzeichen.' },
    { front: 'RGB', back: 'Red Green Blue – additives Farbmodell aus drei Grundfarben für Bildschirmdarstellung.' },
    { front: 'PIN', back: 'Personal Identification Number – persönliche Geheimzahl zur Authentifizierung.' },
    { front: 'PNG', back: 'Portable Network Graphics – verlustfreies Rastergrafik-Format mit Transparenzunterstützung.' },
    { front: 'JPEG', back: 'Joint Photographic Experts Group – verlustbehaftetes Bildformat, optimiert für Fotos.' },
    { front: 'MB / GB / KB', back: 'Megabyte / Gigabyte / Kilobyte – Einheiten für Dateigrößen und Speicherkapazitäten (1 KB = 1.024 Byte).' },
  ],
  questions: [
    {
      type: 'mc',
      prompt: 'Wofür steht die Abkürzung "CPU"?',
      options: ['Central Processing Unit', 'Computer Power Unit', 'Core Program Utility', 'Central Program Uploader'],
      correct: [0],
      explanation: 'CPU steht für Central Processing Unit – der Hauptprozessor, der Befehle ausführt.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "RAM" in der EDV?',
      options: ['Read Access Memory', 'Random Access Memory', 'Rapid Array Memory', 'Remote Application Module'],
      correct: [1],
      explanation: 'RAM steht für Random Access Memory – der flüchtige Arbeitsspeicher des Computers.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Wofür steht "USB"?',
      options: ['Universal System Bus', 'Unified Serial Backup', 'User Service Block', 'Universal Serial Bus'],
      correct: [3],
      explanation: 'USB steht für Universal Serial Bus – eine genormte Schnittstelle für Peripheriegeräte.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist die korrekte Auflösung von "URL"?',
      options: ['Universal Resource Locator', 'Unified Reference Link', 'Uniform Resource Locator', 'User Request Language'],
      correct: [2],
      explanation: 'URL steht für Uniform Resource Locator – die eindeutige Adresse einer Ressource im Internet.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Wofür steht "HTML"?',
      options: ['HyperText Markup Language', 'High Transfer Markup Logic', 'HyperText Management Language', 'Hybrid Text Modeling Layer'],
      correct: [0],
      explanation: 'HTML steht für HyperText Markup Language – die Auszeichnungssprache für Webseiten.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "HTTP" in der Webtechnologie?',
      options: ['HyperText Transfer Process', 'HyperText Transfer Protocol', 'High Traffic Transmission Protocol', 'Hybrid Transfer Text Procedure'],
      correct: [1],
      explanation: 'HTTP steht für HyperText Transfer Protocol – das Protokoll zur Übertragung von Webseiten.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Wodurch unterscheidet sich HTTPS von HTTP?',
      options: ['HTTPS ist schneller als HTTP', 'HTTPS überträgt größere Dateien', 'HTTPS verwendet Verschlüsselung (TLS/SSL)', 'HTTPS ist eine ältere Version von HTTP'],
      correct: [2],
      explanation: 'HTTPS (HyperText Transfer Protocol Secure) verschlüsselt die Datenübertragung mittels TLS/SSL.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Wofür steht "FTP"?',
      options: ['Fast Transfer Protocol', 'File Transfer Protocol', 'Fixed Transfer Procedure', 'Flexible Text Protocol'],
      correct: [1],
      explanation: 'FTP steht für File Transfer Protocol – ein Protokoll zur Übertragung von Dateien zwischen Client und Server.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "IP" im Kontext von Netzwerken?',
      options: ['Internal Process', 'Integrated Protocol', 'Internet Protocol', 'Interface Procedure'],
      correct: [2],
      explanation: 'IP steht für Internet Protocol – das Grundprotokoll zur Adressierung und Weiterleitung von Datenpaketen.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welche Funktion hat das "DNS"?',
      options: [
        'Es verschlüsselt Internetverbindungen',
        'Es übersetzt Domainnamen in IP-Adressen',
        'Es verwaltet Benutzerkonten im Netzwerk',
        'Es komprimiert Dateiübertragungen',
      ],
      correct: [1],
      explanation: 'DNS (Domain Name System) übersetzt lesbare Domainnamen wie example.com in numerische IP-Adressen.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was ist ein "LAN"?',
      options: ['Large Area Node', 'Local Area Network', 'Linked Access Network', 'Logical Application Node'],
      correct: [1],
      explanation: 'LAN steht für Local Area Network – ein lokales Netzwerk in einem begrenzten Bereich.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Wofür steht "WAN"?',
      options: ['Wireless Access Node', 'Wide Area Network', 'Web Application Network', 'Wired Area Node'],
      correct: [1],
      explanation: 'WAN steht für Wide Area Network – ein weiträumiges Netzwerk, das mehrere lokale Netzwerke verbindet.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "WLAN"?',
      options: ['Wide Local Area Node', 'Wireless Local Area Network', 'Web Linked Access Network', 'Wired Local Application Node'],
      correct: [1],
      explanation: 'WLAN steht für Wireless Local Area Network – das drahtlose lokale Netzwerk (Wi-Fi).',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Wofür steht "PDF"?',
      options: ['Portable Document Format', 'Printed Data File', 'Personal Data Format', 'Public Document Framework'],
      correct: [0],
      explanation: 'PDF steht für Portable Document Format – ein plattformunabhängiges Dokumentformat von Adobe.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "GUI"?',
      options: ['General User Input', 'Graphical User Interface', 'Global Utility Index', 'Guided User Integration'],
      correct: [1],
      explanation: 'GUI steht für Graphical User Interface – die grafische Benutzeroberfläche zur visuellen Bedienung.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Wofür steht "OS" in der Informatik?',
      options: ['Output System', 'Online Service', 'Operating System', 'Object Storage'],
      correct: [2],
      explanation: 'OS steht für Operating System – das Betriebssystem, das Hardware und Software verwaltet.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist das "BIOS"?',
      options: [
        'Basic Input/Output System – Firmware zur Hardware-Initialisierung beim Start',
        'Binary Input/Output Software – Programmierschnittstelle für Treiber',
        'Basic Integrated Operating Shell – Kommandozeilen-Betriebssystem',
        'Built-In Output System – Grafikkarten-Firmware',
      ],
      correct: [0],
      explanation: 'BIOS steht für Basic Input/Output System – die Firmware, die beim Computerstart die Hardware initialisiert.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Wofür steht "SQL"?',
      options: ['Structured Query Language', 'Simple Queue Logic', 'System Query Layer', 'Standard Question Language'],
      correct: [0],
      explanation: 'SQL steht für Structured Query Language – die Sprache zur Abfrage und Verwaltung relationaler Datenbanken.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "API"?',
      options: ['Automated Program Integration', 'Application Programming Interface', 'Advanced Protocol Index', 'Access Point Interface'],
      correct: [1],
      explanation: 'API steht für Application Programming Interface – eine Schnittstelle, über die Programme miteinander kommunizieren.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Wofür steht "IDE" in der Softwareentwicklung?',
      options: ['Integrated Data Engine', 'Intelligent Design Environment', 'Integrated Development Environment', 'Interactive Display Editor'],
      correct: [2],
      explanation: 'IDE steht für Integrated Development Environment – eine integrierte Entwicklungsumgebung mit Editor, Debugger und Build-Tools.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "OOP"?',
      options: ['Object Oriented Programming', 'Online Operation Protocol', 'Ordered Output Processing', 'Open Object Platform'],
      correct: [0],
      explanation: 'OOP steht für Objektorientierte Programmierung – ein Paradigma, das auf Objekten und Klassen basiert.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Wofür steht "CSS"?',
      options: ['Cascading Style Sheets', 'Computer Styling System', 'Content Structure Script', 'Centralized Style Source'],
      correct: [0],
      explanation: 'CSS steht für Cascading Style Sheets – eine Stylesheet-Sprache zur Gestaltung von HTML-Webseiten.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "VPN"?',
      options: ['Virtual Private Network', 'Verified Public Node', 'Variable Protocol Network', 'Virtual Protocol Node'],
      correct: [0],
      explanation: 'VPN steht für Virtual Private Network – eine verschlüsselte Verbindung über das öffentliche Internet.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Wofür steht "DSL"?',
      options: ['Data Synchronization Layer', 'Digital Subscriber Line', 'Dynamic Server Link', 'Direct Signal Loop'],
      correct: [1],
      explanation: 'DSL steht für Digital Subscriber Line – eine Technik zur Breitband-Internetübertragung über Telefonleitungen.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was ist eine "GPU"?',
      options: ['General Programming Unit', 'Graphics Processing Unit', 'Global Protocol Utility', 'Graphical Power Unit'],
      correct: [1],
      explanation: 'GPU steht für Graphics Processing Unit – ein Grafikprozessor für Bildberechnungen und 3D-Grafiken.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Wofür steht "OCR"?',
      options: ['Online Content Repository', 'Optical Character Recognition', 'Output Control Register', 'Open Code Runtime'],
      correct: [1],
      explanation: 'OCR steht für Optical Character Recognition – Technologie zur automatischen Texterkennung aus Bildern oder Scans.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "ERP"?',
      options: ['Extended Resource Protocol', 'Enterprise Resource Planning', 'Electronic Record Processing', 'Embedded Runtime Platform'],
      correct: [1],
      explanation: 'ERP steht für Enterprise Resource Planning – integrierte Software zur Verwaltung von Unternehmensprozessen.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Wofür steht "CMS"?',
      options: ['Central Messaging System', 'Content Management System', 'Computer Monitoring Service', 'Collaborative Media Suite'],
      correct: [1],
      explanation: 'CMS steht für Content Management System – Software zur Erstellung und Verwaltung digitaler Inhalte.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "SaaS"?',
      options: ['Secure and Scalable System', 'Software as a Service', 'Server and Application Suite', 'Storage as a Solution'],
      correct: [1],
      explanation: 'SaaS steht für Software as a Service – Bereitstellung von Software über das Internet als abonnierter Dienst.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Wofür steht "KI" bzw. englisch "AI"?',
      options: [
        'Komplexe Informationsverarbeitung / Automated Information',
        'Künstliche Intelligenz / Artificial Intelligence',
        'Kritische Infrastruktur / Advanced Infrastructure',
        'Kollaborative Integration / Application Integration',
      ],
      correct: [1],
      explanation: 'KI/AI steht für Künstliche Intelligenz / Artificial Intelligence – die Simulation menschlicher Intelligenz durch Computer.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "IoT"?',
      options: ['Integration of Technology', 'Internet of Things', 'Index of Traffic', 'Interface on Transfer'],
      correct: [1],
      explanation: 'IoT steht für Internet of Things – die Vernetzung physischer Geräte und Alltagsgegenstände mit dem Internet.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Wofür steht "ASCII"?',
      options: [
        'American Standard Code for Information Interchange',
        'Automated System for Character Input and Indexing',
        'Advanced Standard Coding and Information Interface',
        'American Software Code and Integration Index',
      ],
      correct: [0],
      explanation: 'ASCII steht für American Standard Code for Information Interchange – ein 7-Bit-Zeichenkodierungsstandard.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "RGB" im Kontext von Bildschirmen?',
      options: ['Raster Graphics Bytes', 'Red Green Blue', 'Resolution Graphics Bit', 'Rendered Graphics Base'],
      correct: [1],
      explanation: 'RGB steht für Red Green Blue – das additive Farbmodell aus drei Grundfarben für Bildschirmdarstellung.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Wofür steht "PIN"?',
      options: ['Personal Information Node', 'Private Interface Number', 'Personal Identification Number', 'Protected Input Notation'],
      correct: [2],
      explanation: 'PIN steht für Personal Identification Number – eine persönliche Geheimzahl zur Authentifizierung.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "ROM"?',
      options: ['Random Output Memory', 'Read Only Memory', 'Rewritable Optical Media', 'Registered Operating Module'],
      correct: [1],
      explanation: 'ROM steht für Read Only Memory – dauerhafter Speicher, der nur gelesen werden kann.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist der Unterschied zwischen HDD und SSD?',
      options: [
        'HDDs nutzen Flash-Speicher, SSDs nutzen Magnetscheiben',
        'HDDs sind schneller als SSDs',
        'SSDs nutzen Flash-Speicher ohne bewegliche Teile, HDDs nutzen rotierende Magnetscheiben',
        'SSDs können keine Daten dauerhaft speichern',
      ],
      correct: [2],
      explanation: 'SSDs (Solid State Drive) nutzen Flash-Speicher und haben keine beweglichen Teile, HDD (Hard Disk Drive) hingegen nutzen rotierende Magnetscheiben.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Wofür steht "PNG"?',
      options: ['Printed Network Graphic', 'Portable Network Graphics', 'Pixel Node Generator', 'Public Network Gateway'],
      correct: [1],
      explanation: 'PNG steht für Portable Network Graphics – ein verlustfreies Bildformat mit Transparenzunterstützung.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet die Abkürzung "JPEG"?',
      options: [
        'Joint Processing and Encoding Group',
        'Java Platform Encoding and Graphics',
        'Joint Photographic Experts Group',
        'Justified Picture Encoding and Generation',
      ],
      correct: [2],
      explanation: 'JPEG steht für Joint Photographic Experts Group – das Gremium, das dieses verlustbehaftete Bildformat standardisiert hat.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Wie viele Byte hat ein Kilobyte (KB) nach dem Binärsystem?',
      options: ['100 Byte', '1.000 Byte', '1.024 Byte', '2.048 Byte'],
      correct: [2],
      explanation: '1 Kilobyte (KB) entspricht im Binärsystem 2^10 = 1.024 Byte.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welche Aussage zu "SaaS" ist korrekt?',
      options: [
        'SaaS-Software wird auf dem lokalen Computer installiert',
        'SaaS-Dienste werden über das Internet bereitgestellt und meist per Abonnement bezahlt',
        'SaaS steht für Secure and Scalable Systems',
        'SaaS bezeichnet ausschließlich Open-Source-Software',
      ],
      correct: [1],
      explanation: 'SaaS (Software as a Service) bezeichnet über das Internet angebotene Software, die typischerweise per Abonnement genutzt wird.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Wofür steht "VPN" und wofür wird es hauptsächlich genutzt?',
      options: [
        'Virtual Processing Node – zur Beschleunigung von Downloads',
        'Verified Public Network – zur Freigabe öffentlicher Ressourcen',
        'Virtual Private Network – zur verschlüsselten, sicheren Verbindung über das Internet',
        'Variable Packet Network – zur Optimierung von Datenpaketen',
      ],
      correct: [2],
      explanation: 'VPN (Virtual Private Network) ermöglicht verschlüsselte Verbindungen über das öffentliche Internet und schützt Daten vor unbefugtem Zugriff.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was beschreibt "IoT" am besten?',
      options: [
        'Eine Programmiersprache für Webanwendungen',
        'Die Vernetzung physischer Geräte mit dem Internet zur Datenerfassung und -steuerung',
        'Ein Verschlüsselungsprotokoll für E-Mails',
        'Ein Standard für mobile Bezahlsysteme',
      ],
      correct: [1],
      explanation: 'IoT (Internet of Things) bezeichnet die Vernetzung von Alltagsgeräten (Sensoren, Maschinen, Haushaltsgeräten) mit dem Internet.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welche Technologie steckt hinter "OCR"?',
      options: [
        'Automatische Spracherkennung per Mikrofon',
        'Optische Zeichenerkennung – Text wird aus Bildern oder Scans maschinell gelesen',
        'Online-Komprimierung von Rastergrafiken',
        'Verschlüsselung optischer Datenträger',
      ],
      correct: [1],
      explanation: 'OCR (Optical Character Recognition) ist eine Technologie, die gedruckten oder handgeschriebenen Text aus Bildern oder Scans erkennt und digitalisiert.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Wofür steht "ERP" und in welchem Bereich wird es eingesetzt?',
      options: [
        'Electronic Record Protocol – für medizinische Patientenakten',
        'Enterprise Resource Planning – integrierte Software für Unternehmensprozesse',
        'Extended Runtime Platform – für Cloud-Anwendungen',
        'Embedded Resource Processor – für Mikrocontroller-Entwicklung',
      ],
      correct: [1],
      explanation: 'ERP (Enterprise Resource Planning) ist eine integrierte Unternehmenssoftware, die Prozesse wie Einkauf, Produktion, Vertrieb und Buchhaltung verbindet.',
      difficulty: 3,
    },
  ],
};

export default topic;
