import type { RawTopic } from '../types';

const topic: RawTopic = {
  slug: 'eu',
  title: 'EU & internationale Organisationen',
  description: 'Aufbau, Organe und Grundlagen der Europäischen Union.',
  flashcards: [
    {
      front: 'Wie viele Mitgliedstaaten hat die EU aktuell (Stand 2026)?',
      back: '27 Mitgliedstaaten. Großbritannien verließ die EU im Jahr 2020 (Brexit).',
    },
    {
      front: 'Wann und durch welchen Vertrag wurde die Europäische Union offiziell gegründet?',
      back: 'Durch den Vertrag von Maastricht, der 1992 unterzeichnet wurde und am 1. November 1993 in Kraft trat.',
    },
    {
      front: 'Was waren die Vorläufer der EU und wann wurden sie gegründet?',
      back: 'Die Europäische Wirtschaftsgemeinschaft (EWG) und die Europäische Atomgemeinschaft (Euratom) wurden durch die Römischen Verträge von 1957 gegründet.',
    },
    {
      front: 'Welche vier Grundfreiheiten garantiert der EU-Binnenmarkt?',
      back: 'Freier Warenverkehr, freier Personenverkehr, freier Dienstleistungsverkehr und freier Kapital- und Zahlungsverkehr.',
    },
    {
      front: 'Was ist der Schengen-Raum?',
      back: 'Ein Gebiet, in dem Personen ohne Grenzkontrollen reisen können. Er umfasst die meisten EU-Staaten sowie einige Nicht-EU-Länder (z. B. Norwegen, Schweiz).',
    },
    {
      front: 'Wo hat die Europäische Kommission ihren Sitz?',
      back: 'In Brüssel (Belgien).',
    },
    {
      front: 'Wo hat das Europäische Parlament seinen offiziellen Sitz?',
      back: 'Der offizielle Sitz ist Straßburg (Frankreich). Ausschusssitzungen und zusätzliche Plenartagungen finden in Brüssel statt.',
    },
    {
      front: 'Wo hat der Europäische Gerichtshof (EuGH) seinen Sitz?',
      back: 'In Luxemburg-Stadt (Luxemburg).',
    },
    {
      front: 'Wo hat die Europäische Zentralbank (EZB) ihren Sitz?',
      back: 'In Frankfurt am Main (Deutschland).',
    },
    {
      front: 'Wer ist die Präsidentin der Europäischen Kommission (Stand 2026)?',
      back: 'Ursula von der Leyen.',
    },
    {
      front: 'Wer ist der Präsident des Europäischen Rates (Stand 2026)?',
      back: 'António Costa (Portugal).',
    },
    {
      front: 'Wer ist die Präsidentin des Europäischen Parlaments (Stand 2026)?',
      back: 'Roberta Metsola (Malta).',
    },
    {
      front: 'Wie viele Länder gehören der Eurozone an (Stand 2026)?',
      back: '21 Länder. Bulgarien ist seit 2026 das jüngste Mitglied der Eurozone.',
    },
    {
      front: 'Was ist die Hauptaufgabe der Europäischen Kommission?',
      back: 'Sie ist das Exekutivorgan der EU, hat das Initiativrecht für EU-Gesetze, überwacht die Anwendung des EU-Rechts und vertritt die EU nach außen.',
    },
    {
      front: 'Was ist der Unterschied zwischen dem Rat der EU (Ministerrat) und dem Europäischen Rat?',
      back: 'Der Rat der EU (Ministerrat) setzt sich aus Fachministern der Mitgliedstaaten zusammen und beschließt Gesetze. Der Europäische Rat besteht aus den Staats- und Regierungschefs und legt die politischen Leitlinien fest.',
    },
    {
      front: 'Welche Aufgabe hat der Europäische Rechnungshof?',
      back: 'Er prüft die Einnahmen und Ausgaben der EU und kontrolliert die ordnungsgemäße Verwendung der EU-Mittel. Sein Sitz ist in Luxemburg.',
    },
    {
      front: 'Was versteht man unter dem ordentlichen Gesetzgebungsverfahren der EU?',
      back: 'Das Verfahren, bei dem Europäisches Parlament und Rat der EU gleichberechtigt Gesetze beschließen (früher Mitentscheidungsverfahren). Die Kommission hat das Initiativrecht.',
    },
    {
      front: 'Welche Institutionen bilden gemeinsam die Haushaltsbehörde der EU?',
      back: 'Das Europäische Parlament und der Rat der EU beschließen gemeinsam den EU-Haushalt.',
    },
    {
      front: 'Wofür steht die Abkürzung EuGH und was ist seine Aufgabe?',
      back: 'EuGH steht für Europäischer Gerichtshof. Er sichert die einheitliche Auslegung und Anwendung des EU-Rechts und entscheidet über Streitigkeiten zwischen EU-Organen, Mitgliedstaaten und Einzelpersonen.',
    },
    {
      front: 'Was ist das Subsidiaritätsprinzip in der EU?',
      back: 'Die EU darf nur tätig werden, wenn Ziele auf EU-Ebene besser erreicht werden können als auf nationaler, regionaler oder lokaler Ebene.',
    },
  ],
  questions: [
    {
      type: 'mc',
      prompt: 'Wie viele Mitgliedstaaten hat die Europäische Union im Jahr 2026?',
      options: ['25', '27', '28', '30'],
      correct: [1],
      explanation: 'Die EU hat seit dem Brexit (Austritt Großbritanniens am 31. Januar 2020) 27 Mitgliedstaaten.',
      difficulty: 1,
    },
    {
      type: 'truefalse',
      prompt: 'Die EU hat 27 Mitgliedstaaten.',
      options: ['Richtig', 'Falsch'],
      correct: [0],
      explanation: 'Seit dem Brexit (2020) hat die EU 27 Mitgliedstaaten.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Wann trat der Vertrag von Maastricht in Kraft, der die Europäische Union begründete?',
      options: ['1989', '1992', '1993', '1995'],
      correct: [2],
      explanation: 'Der Vertrag von Maastricht wurde 1992 unterzeichnet, trat aber am 1. November 1993 in Kraft.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Durch welche Verträge wurden die EWG und Euratom im Jahr 1957 gegründet?',
      options: ['Vertrag von Maastricht', 'Vertrag von Lissabon', 'Römische Verträge', 'Schengener Abkommen'],
      correct: [2],
      explanation: 'Die Europäische Wirtschaftsgemeinschaft (EWG) und Euratom wurden 1957 durch die Römischen Verträge gegründet.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welche der folgenden ist KEINE der vier Grundfreiheiten des EU-Binnenmarktes?',
      options: ['Freier Warenverkehr', 'Freier Personenverkehr', 'Freier Informationsverkehr', 'Freier Kapitalverkehr'],
      correct: [2],
      explanation: 'Die vier Grundfreiheiten sind: Waren-, Personen-, Dienstleistungs- und Kapitalverkehr. Einen "freien Informationsverkehr" als Grundfreiheit gibt es nicht.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Wo hat die Europäische Kommission ihren Hauptsitz?',
      options: ['Luxemburg', 'Straßburg', 'Frankfurt am Main', 'Brüssel'],
      correct: [3],
      explanation: 'Die Europäische Kommission hat ihren Sitz in Brüssel, Belgien.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'In welcher Stadt hat der Europäische Gerichtshof (EuGH) seinen Sitz?',
      options: ['Brüssel', 'Straßburg', 'Luxemburg', 'Den Haag'],
      correct: [2],
      explanation: 'Der Europäische Gerichtshof (EuGH) hat seinen Sitz in Luxemburg-Stadt.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Wo befindet sich der offizielle Sitz des Europäischen Parlaments?',
      options: ['Brüssel', 'Straßburg', 'Luxemburg', 'Wien'],
      correct: [1],
      explanation: 'Der offizielle Sitz des Europäischen Parlaments ist Straßburg (Frankreich), obwohl auch in Brüssel Plenarsitzungen und Ausschusssitzungen stattfinden.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'In welcher Stadt hat die Europäische Zentralbank (EZB) ihren Sitz?',
      options: ['Berlin', 'Wien', 'Frankfurt am Main', 'Zürich'],
      correct: [2],
      explanation: 'Die Europäische Zentralbank (EZB) hat ihren Sitz in Frankfurt am Main, Deutschland.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Wer ist die Präsidentin der Europäischen Kommission (Stand 2026)?',
      options: ['Christine Lagarde', 'Roberta Metsola', 'Ursula von der Leyen', 'Angela Merkel'],
      correct: [2],
      explanation: 'Ursula von der Leyen ist Präsidentin der Europäischen Kommission.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Wer ist der Präsident des Europäischen Rates (Stand 2026)?',
      options: ['António Costa', 'Charles Michel', 'Donald Tusk', 'Mario Draghi'],
      correct: [0],
      explanation: 'António Costa aus Portugal ist seit Dezember 2024 Präsident des Europäischen Rates.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Wer ist die Präsidentin des Europäischen Parlaments (Stand 2026)?',
      options: ['Ursula von der Leyen', 'Christine Lagarde', 'Federica Mogherini', 'Roberta Metsola'],
      correct: [3],
      explanation: 'Roberta Metsola aus Malta ist Präsidentin des Europäischen Parlaments.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Wie viele Länder gehören der Eurozone (Stand 2026) an?',
      options: ['19', '20', '21', '27'],
      correct: [2],
      explanation: 'Seit dem Beitritt Bulgariens im Jahr 2026 umfasst die Eurozone 21 Länder.',
      difficulty: 2,
    },
    {
      type: 'truefalse',
      prompt: 'Bulgarien ist seit 2026 Mitglied der Eurozone.',
      options: ['Richtig', 'Falsch'],
      correct: [0],
      explanation: 'Bulgarien trat 2026 der Eurozone bei und ist damit das 21. Land, das den Euro als offizielle Währung eingeführt hat.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welches EU-Organ hat das alleinige Initiativrecht für EU-Rechtsakte?',
      options: ['Europäisches Parlament', 'Rat der EU', 'Europäische Kommission', 'Europäischer Rat'],
      correct: [2],
      explanation: 'Das Initiativrecht für Gesetzgebungsvorschläge liegt grundsätzlich bei der Europäischen Kommission.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was unterscheidet den Europäischen Rat vom Rat der EU (Ministerrat)?',
      options: [
        'Der Europäische Rat besteht aus Fachministern, der Ministerrat aus Staats- und Regierungschefs',
        'Der Europäische Rat besteht aus Staats- und Regierungschefs, der Ministerrat aus Fachministern',
        'Beide Organe sind identisch, nur unterschiedlich benannt',
        'Der Europäische Rat ist ein Beratungsgremium ohne Entscheidungsbefugnis',
      ],
      correct: [1],
      explanation: 'Der Europäische Rat setzt sich aus den Staats- und Regierungschefs zusammen und gibt die politischen Leitlinien vor. Der Rat der EU (Ministerrat) besteht aus Fachministern und ist am Gesetzgebungsverfahren beteiligt.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welches Organ prüft die ordnungsgemäße Verwendung der EU-Haushaltsmittel?',
      options: ['Europäische Zentralbank', 'Europäischer Gerichtshof', 'Europäischer Rechnungshof', 'Europäische Kommission'],
      correct: [2],
      explanation: 'Der Europäische Rechnungshof mit Sitz in Luxemburg ist das unabhängige Prüforgan der EU und kontrolliert die Einnahmen und Ausgaben der EU.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was garantiert der Schengen-Raum seinen Mitgliedern?',
      options: [
        'Eine gemeinsame Währung',
        'Reisen ohne Grenzkontrollen',
        'Eine gemeinsame Außenpolitik',
        'Gegenseitige Militärhilfe',
      ],
      correct: [1],
      explanation: 'Im Schengen-Raum können Personen ohne Passkontrollen zwischen den Mitgliedstaaten reisen. Er umfasst die meisten EU-Staaten sowie Nicht-EU-Länder wie Norwegen und die Schweiz.',
      difficulty: 1,
    },
    {
      type: 'truefalse',
      prompt: 'Alle EU-Mitgliedstaaten sind auch Mitglieder des Schengen-Raums.',
      options: ['Richtig', 'Falsch'],
      correct: [1],
      explanation: 'Nicht alle EU-Staaten gehören dem Schengen-Raum an (z. B. Irland hat eine Sonderregelung). Umgekehrt sind auch Nicht-EU-Länder wie Norwegen und die Schweiz Teil des Schengen-Raums.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welches Verfahren ist das Standardverfahren der EU-Gesetzgebung, bei dem Parlament und Rat gleichberechtigt entscheiden?',
      options: ['Anhörungsverfahren', 'Zustimmungsverfahren', 'Ordentliches Gesetzgebungsverfahren', 'Vertragsverletzungsverfahren'],
      correct: [2],
      explanation: 'Im ordentlichen Gesetzgebungsverfahren (früher Mitentscheidungsverfahren) sind Europäisches Parlament und Rat der EU gleichberechtigte Gesetzgeber.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Welche EU-Institution ist für die Geldpolitik in der Eurozone zuständig?',
      options: ['Europäische Kommission', 'Europäischer Rat', 'Europäische Zentralbank (EZB)', 'Europäischer Rechnungshof'],
      correct: [2],
      explanation: 'Die Europäische Zentralbank (EZB) ist für die Geldpolitik der Eurozone zuständig. Ihr Hauptziel ist die Preisstabilität.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was besagt das Subsidiaritätsprinzip der EU?',
      options: [
        'Die EU hat in allen Bereichen Vorrang vor nationalem Recht',
        'Die EU handelt nur, wenn Ziele auf EU-Ebene besser erreicht werden als auf nationaler Ebene',
        'Mitgliedstaaten dürfen keine eigenen Gesetze mehr erlassen',
        'Alle EU-Entscheidungen müssen einstimmig getroffen werden',
      ],
      correct: [1],
      explanation: 'Das Subsidiaritätsprinzip besagt, dass die EU nur tätig wird, wenn die angestrebten Ziele auf EU-Ebene besser verwirklicht werden können als auf nationaler, regionaler oder lokaler Ebene.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'In welchem Jahr verließ Großbritannien die EU (Brexit)?',
      options: ['2016', '2018', '2019', '2020'],
      correct: [3],
      explanation: 'Großbritannien verließ die EU offiziell am 31. Januar 2020. Das Referendum fand 2016 statt.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welcher Grundsatz besagt, dass EU-Recht dem nationalen Recht vorgeht?',
      options: ['Subsidiaritätsprinzip', 'Verhältnismäßigkeitsprinzip', 'Vorrang des Unionsrechts', 'Solidaritätsprinzip'],
      correct: [2],
      explanation: 'Der Vorrang des Unionsrechts (Anwendungsvorrang) besagt, dass EU-Recht im Konfliktfall dem nationalen Recht vorgeht. Dies wurde vom EuGH in der Rechtssache Costa/ENEL (1964) festgestellt.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Welches EU-Organ besteht aus direkt gewählten Abgeordneten der EU-Bürgerinnen und -Bürger?',
      options: ['Europäischer Rat', 'Rat der EU', 'Europäische Kommission', 'Europäisches Parlament'],
      correct: [3],
      explanation: 'Das Europäische Parlament ist das einzige direkt von den EU-Bürgerinnen und -Bürgern gewählte Organ der EU. Die Europawahl findet alle fünf Jahre statt.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Wie oft finden die Wahlen zum Europäischen Parlament statt?',
      options: ['Alle 3 Jahre', 'Alle 4 Jahre', 'Alle 5 Jahre', 'Alle 6 Jahre'],
      correct: [2],
      explanation: 'Das Europäische Parlament wird alle fünf Jahre direkt von den Bürgerinnen und Bürgern der EU gewählt.',
      difficulty: 1,
    },
    {
      type: 'truefalse',
      prompt: 'Die Europäische Zentralbank hat ihren Sitz in Brüssel.',
      options: ['Richtig', 'Falsch'],
      correct: [1],
      explanation: 'Die EZB hat ihren Sitz in Frankfurt am Main, Deutschland - nicht in Brüssel.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welche Verträge bildeten die Grundlage für die Europäische Wirtschaftsgemeinschaft (EWG)?',
      options: ['Vertrag von Maastricht (1992)', 'Römische Verträge (1957)', 'Vertrag von Lissabon (2007)', 'Schengener Abkommen (1985)'],
      correct: [1],
      explanation: 'Die Römischen Verträge von 1957 gründeten die EWG und Euratom und traten 1958 in Kraft.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was ist die Hauptaufgabe des Europäischen Rates?',
      options: [
        'EU-Gesetze beschließen',
        'Den EU-Haushalt kontrollieren',
        'Politische Leitlinien und Prioritäten der EU festlegen',
        'EU-Recht auslegen und anwenden',
      ],
      correct: [2],
      explanation: 'Der Europäische Rat, bestehend aus den Staats- und Regierungschefs der EU, legt die allgemeinen politischen Leitlinien und Prioritäten der EU fest, beschließt aber keine Rechtsakte.',
      difficulty: 2,
    },
    {
      type: 'fill',
      prompt: 'Der Vertrag von ________ (1992/1993) begründete offiziell die Europäische Union.',
      options: ['Maastricht', 'Lissabon', 'Amsterdam', 'Nizza'],
      correct: [0],
      explanation: 'Der Vertrag von Maastricht wurde 1992 unterzeichnet und trat am 1. November 1993 in Kraft. Er gründete die Europäische Union und führte u. a. den Euro als gemeinsame Währung ein.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welche der folgenden Aufgaben fällt in die Zuständigkeit des Europäischen Parlaments?',
      options: [
        'Ernennung der Richter des EuGH ohne Beteiligung anderer Organe',
        'Kontrolle der Europäischen Kommission und Mitentscheidung bei EU-Gesetzen',
        'Festlegung der Zinspolitik der Eurozone',
        'Ausschließliche Verwaltung des EU-Haushalts',
      ],
      correct: [1],
      explanation: 'Das Europäische Parlament kontrolliert die Kommission (z. B. durch Misstrauensvotum), wirkt am Gesetzgebungsverfahren mit und beschließt gemeinsam mit dem Rat den EU-Haushalt.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Wann wurde das Schengener Abkommen unterzeichnet?',
      options: ['1957', '1985', '1992', '1997'],
      correct: [1],
      explanation: 'Das Schengener Abkommen wurde am 14. Juni 1985 in Schengen (Luxemburg) unterzeichnet. Es trat 1995 in Kraft.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Welches Organ der EU kann ein Misstrauensvotum gegen die Europäische Kommission einbringen?',
      options: ['Europäischer Rat', 'Rat der EU', 'Europäisches Parlament', 'Europäischer Rechnungshof'],
      correct: [2],
      explanation: 'Das Europäische Parlament kann der Europäischen Kommission durch ein Misstrauensvotum (Zwei-Drittel-Mehrheit) das Misstrauen aussprechen, was zum Rücktritt der gesamten Kommission führt.',
      difficulty: 3,
    },
    {
      type: 'truefalse',
      prompt: 'Der Europäische Rechnungshof hat seinen Sitz in Luxemburg.',
      options: ['Richtig', 'Falsch'],
      correct: [0],
      explanation: 'Der Europäische Rechnungshof hat seinen Sitz in Luxemburg-Stadt und prüft die ordnungsgemäße Verwendung der EU-Finanzmittel.',
      difficulty: 2,
    },
  ],
};

export default topic;
