import type { RawTopic } from '../types';

const topic: RawTopic = {
  slug: 'fremdwoerter',
  title: 'Fremdwörter',
  description: 'Bedeutung gebräuchlicher Fremd- und Lehnwörter kennen.',
  flashcards: [
    { front: 'obligatorisch', back: 'verpflichtend, vorgeschrieben' },
    { front: 'authentisch', back: 'echt, ursprünglich, glaubwürdig' },
    { front: 'pragmatisch', back: 'sachlich, praktisch orientiert, lösungsorientiert' },
    { front: 'Konsens', back: 'Übereinstimmung, gemeinsame Meinung, Einigkeit' },
    { front: 'Diskrepanz', back: 'Abweichung, Widerspruch, Unstimmigkeit' },
    { front: 'kompatibel', back: 'vereinbar, verträglich, passend' },
    { front: 'Restriktion', back: 'Einschränkung, Begrenzung, Beschränkung' },
    { front: 'Prävention', back: 'Vorbeugung, Verhütung, Vorsorge' },
    { front: 'Toleranz', back: 'Duldung, Akzeptanz, Nachsicht' },
    { front: 'Innovation', back: 'Neuerung, Erneuerung, neue Idee oder Entwicklung' },
    { front: 'Plausibilität', back: 'Nachvollziehbarkeit, Glaubwürdigkeit, Einleuchtigkeit' },
    { front: 'Diplomatie', back: 'Taktgefühl, geschicktes Verhandeln, Feinfühligkeit im Umgang' },
    { front: 'Diskretion', back: 'Verschwiegenheit, Zurückhaltung, Takt' },
    { front: 'Eloquenz', back: 'Redegewandtheit, sprachliche Gewandtheit, Beredsamkeit' },
    { front: 'Resilienz', back: 'Widerstandsfähigkeit, psychische Belastbarkeit, Erholungsfähigkeit' },
    { front: 'ambivalent', back: 'zwiespältig, doppeldeutig, widersprüchliche Gefühle habend' },
    { front: 'evident', back: 'offensichtlich, eindeutig, klar ersichtlich' },
    { front: 'profund', back: 'tiefgründig, gründlich, umfassend (z.B. profundes Wissen)' },
    { front: 'prägnant', back: 'treffend, knapp und aussagekräftig, auf den Punkt gebracht' },
    { front: 'marginal', back: 'geringfügig, am Rande, unbedeutend' },
    { front: 'dezidiert', back: 'entschieden, ausdrücklich, bestimmt' },
    { front: 'sukzessive', back: 'schrittweise, nach und nach, allmählich' },
    { front: 'eklatant', back: 'offensichtlich, auffallend, krass (meist negativ)' },
    { front: 'redundant', back: 'überflüssig, doppelt vorhanden, unnötig wiederholend' },
  ],
  questions: [
    {
      type: 'mc',
      prompt: 'Was bedeutet "obligatorisch"?',
      options: ['verpflichtend', 'freiwillig', 'selten', 'zusätzlich'],
      correct: [0],
      explanation: 'Obligatorisch bedeutet verpflichtend, vorgeschrieben. Etwas Obligatorisches muss getan werden.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "authentisch"?',
      options: ['gefälscht', 'echt und glaubwürdig', 'vorgetäuscht', 'übertrieben'],
      correct: [1],
      explanation: 'Authentisch bedeutet echt, ursprünglich und glaubwürdig – nicht nachgeahmt oder verfälscht.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Eine pragmatische Lösung ist ...',
      options: ['theoretisch und abstrakt', 'aufwendig und kompliziert', 'praktisch und lösungsorientiert', 'idealistisch und visionär'],
      correct: [2],
      explanation: 'Pragmatisch bedeutet sachlich-praktisch orientiert, auf Machbarkeit und Wirksamkeit ausgerichtet.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was versteht man unter einem "Konsens"?',
      options: ['einen Widerspruch', 'eine Übereinstimmung', 'einen Konflikt', 'eine Ablehnung'],
      correct: [1],
      explanation: 'Konsens bezeichnet die gemeinsame Übereinstimmung oder Einigkeit mehrerer Personen oder Gruppen.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "Diskrepanz"?',
      options: ['Harmonie', 'Übereinstimmung', 'Abweichung oder Widerspruch', 'Ergänzung'],
      correct: [2],
      explanation: 'Diskrepanz bezeichnet eine Abweichung, Unstimmigkeit oder einen Widerspruch zwischen zwei Dingen.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Zwei Systeme sind "kompatibel". Das bedeutet:',
      options: ['Sie widersprechen sich', 'Sie sind vereinbar und verträglich', 'Sie sind veraltet', 'Sie sind identisch'],
      correct: [1],
      explanation: 'Kompatibel bedeutet vereinbar, verträglich oder passend – die Systeme funktionieren miteinander.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist eine "Restriktion"?',
      options: ['eine Erweiterung', 'eine Einschränkung oder Begrenzung', 'eine Förderung', 'eine Erlaubnis'],
      correct: [1],
      explanation: 'Restriktion bedeutet Einschränkung, Begrenzung oder Beschränkung – etwas wird limitiert.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "Prävention"?',
      options: ['Bestrafung', 'Aufarbeitung', 'Vorbeugung', 'Wiedergutmachung'],
      correct: [2],
      explanation: 'Prävention bedeutet Vorbeugung oder Verhütung – Maßnahmen, die etwas Unerwünschtes verhindern sollen.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "Toleranz" im gesellschaftlichen Sinne?',
      options: ['Ablehnung anderer Meinungen', 'Duldung und Akzeptanz anderer Ansichten', 'Gleichgültigkeit', 'Zustimmung zu allem'],
      correct: [1],
      explanation: 'Toleranz bedeutet die Duldung und Akzeptanz anderer Überzeugungen, Verhaltensweisen oder Lebensweisen.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was versteht man unter "Innovation"?',
      options: ['Bewahrung des Bestehenden', 'Neuerung oder neue Entwicklung', 'Rückschritt', 'Wiederholung'],
      correct: [1],
      explanation: 'Innovation bezeichnet eine Neuerung, neue Idee oder Entwicklung, die einen Fortschritt bringt.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist "Plausibilität"?',
      options: ['Unverständlichkeit', 'Nachvollziehbarkeit und Glaubwürdigkeit', 'Beweisbarkeit', 'Widersprüchlichkeit'],
      correct: [1],
      explanation: 'Plausibilität bezeichnet die Eigenschaft, nachvollziehbar, einleuchtend und glaubwürdig zu sein.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "Diplomatie" im zwischenmenschlichen Bereich?',
      options: ['Unverblümte Direktheit', 'Taktgefühl und geschicktes Verhandeln', 'Gleichgültigkeit', 'Sturheit'],
      correct: [1],
      explanation: 'Diplomatie bezeichnet im Alltag taktvolles, feinfühliges und geschicktes Verhalten im Umgang mit anderen.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "Diskretion"?',
      options: ['Offenheit', 'Gesprächigkeit', 'Verschwiegenheit und Zurückhaltung', 'Neugier'],
      correct: [2],
      explanation: 'Diskretion bedeutet Verschwiegenheit, Takt und die Fähigkeit, vertrauliche Informationen für sich zu behalten.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Eine eloquente Person ist ...',
      options: ['sprachlich ungewandt', 'redegewandt und ausdrucksstark', 'verschwiegen', 'schüchtern'],
      correct: [1],
      explanation: 'Eloquenz bezeichnet Redegewandtheit und sprachliche Gewandtheit – eloquente Menschen drücken sich treffend aus.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was versteht man unter "Resilienz"?',
      options: ['Empfindlichkeit gegenüber Stress', 'Widerstandsfähigkeit und psychische Belastbarkeit', 'Abhängigkeit von anderen', 'Kreativität'],
      correct: [1],
      explanation: 'Resilienz bezeichnet die Fähigkeit, Krisen und Belastungen zu bewältigen und gestärkt daraus hervorzugehen.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "ambivalent"?',
      options: ['eindeutig positiv', 'eindeutig negativ', 'zwiespältig, widersprüchliche Gefühle habend', 'gleichgültig'],
      correct: [2],
      explanation: 'Ambivalent bedeutet zwiespältig – man hat gleichzeitig gegensätzliche Gefühle oder Meinungen zu etwas.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Etwas ist "evident". Was bedeutet das?',
      options: ['zweifelhaft', 'offensichtlich und klar ersichtlich', 'verborgen', 'kompliziert'],
      correct: [1],
      explanation: 'Evident bedeutet offensichtlich, eindeutig und ohne Zweifel erkennbar.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "profund" im Zusammenhang mit Wissen?',
      options: ['oberflächlich', 'tief, gründlich und umfassend', 'lückenhaft', 'veraltet'],
      correct: [1],
      explanation: 'Profund bedeutet tiefgründig, gründlich und umfassend – profundes Wissen ist fundiertes Expertenwissen.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Eine "prägnante" Aussage ist ...',
      options: ['lang und ausführlich', 'unverständlich', 'knapp, treffend und aussagekräftig', 'mehrdeutig'],
      correct: [2],
      explanation: 'Prägnant bedeutet auf den Punkt gebracht – kurz, treffend und ausdrucksstark.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "marginal"?',
      options: ['bedeutend und zentral', 'geringfügig und am Rande', 'offensichtlich', 'dringend'],
      correct: [1],
      explanation: 'Marginal bedeutet geringfügig, unbedeutend oder am Rande – ein marginaler Unterschied ist kaum spürbar.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "dezidiert"?',
      options: ['zögerlich und unentschlossen', 'entschieden und ausdrücklich', 'beiläufig', 'heimlich'],
      correct: [1],
      explanation: 'Dezidiert bedeutet entschieden, bestimmt und ausdrücklich – ohne Zweideutigkeit oder Zögern.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "sukzessive"?',
      options: ['plötzlich und abrupt', 'schrittweise und nach und nach', 'zufällig', 'rückwärts'],
      correct: [1],
      explanation: 'Sukzessive bedeutet schrittweise, allmählich, nach und nach – also in aufeinanderfolgenden Schritten.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Ein "eklatanter" Fehler ist ein ...',
      options: ['versteckter Fehler', 'kleiner, unbedeutender Fehler', 'offensichtlicher, krasser Fehler', 'beabsichtigter Fehler'],
      correct: [2],
      explanation: 'Eklatant bedeutet offensichtlich und auffallend – meist im negativen Sinne für grobe Verstöße oder Fehler.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "redundant"?',
      options: ['notwendig und unverzichtbar', 'überflüssig und doppelt vorhanden', 'präzise und treffend', 'veraltet'],
      correct: [1],
      explanation: 'Redundant bedeutet überflüssig, unnötig wiederholend – redundante Informationen wurden bereits genannt.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "Konformität"?',
      options: ['Eigenständigkeit', 'Anpassung an Normen und Erwartungen', 'Widerstand', 'Kreativität'],
      correct: [1],
      explanation: 'Konformität bezeichnet die Anpassung an gesellschaftliche Normen, Regeln oder Gruppenerwartungen.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "transparent"?',
      options: ['undurchsichtig und verborgen', 'durchsichtig, offen und nachvollziehbar', 'komplex', 'streng'],
      correct: [1],
      explanation: 'Transparent bedeutet im übertragenen Sinne offen, klar und nachvollziehbar – ohne versteckte Absichten.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was versteht man unter "Effizienz"?',
      options: ['Verschwendung von Mitteln', 'Wirksamkeit bei minimalem Aufwand', 'Langsamkeit', 'Fehlerlosigkeit'],
      correct: [1],
      explanation: 'Effizienz bezeichnet das Verhältnis von Ergebnis zu Aufwand – effizient ist, wer mit wenig Mitteln viel erreicht.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "Integrität"?',
      options: ['Unehrlichkeit', 'Unterwürfigkeit', 'Aufrichtigkeit und moralische Unversehrtheit', 'Gleichgültigkeit'],
      correct: [2],
      explanation: 'Integrität bezeichnet Aufrichtigkeit, Ehrlichkeit und moralische Unversehrtheit – eine integre Person handelt nach ethischen Grundsätzen.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "Kompetenz"?',
      options: ['Unwissenheit', 'Zuständigkeit und Fähigkeit', 'Gleichgültigkeit', 'Sturheit'],
      correct: [1],
      explanation: 'Kompetenz bezeichnet die Fähigkeit, Zuständigkeit und Sachkenntnis, eine Aufgabe erfolgreich zu erfüllen.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist ein "Konsensus"?',
      options: ['ein Streit', 'eine allgemeine Übereinstimmung', 'ein Missverständnis', 'eine Abstimmung'],
      correct: [1],
      explanation: 'Konsensus (auch: Konsens) bedeutet allgemeine Übereinstimmung oder breite Einigkeit in einer Gruppe.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "Diversität"?',
      options: ['Gleichförmigkeit', 'Vielfalt und Unterschiedlichkeit', 'Einheitlichkeit', 'Isolation'],
      correct: [1],
      explanation: 'Diversität bedeutet Vielfalt und Unterschiedlichkeit – z.B. kulturelle, soziale oder persönliche Verschiedenheit.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "Objektivität"?',
      options: ['Voreingenommenheit', 'Sachlichkeit und Unvoreingenommenheit', 'Emotionalität', 'Einseitigkeit'],
      correct: [1],
      explanation: 'Objektivität bezeichnet Sachlichkeit und Unvoreingenommenheit – objektive Urteile sind nicht von persönlichen Gefühlen beeinflusst.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was versteht man unter "Hierarchie"?',
      options: ['Gleichrangigkeit aller Beteiligten', 'Stufenordnung von Rang und Macht', 'zufällige Verteilung von Aufgaben', 'Demokratie'],
      correct: [1],
      explanation: 'Hierarchie bezeichnet eine Rangordnung, in der Positionen nach Macht, Autorität oder Wichtigkeit gestuft sind.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "Kooperation"?',
      options: ['Konkurrenz', 'Zusammenarbeit', 'Ablehnung', 'Isolation'],
      correct: [1],
      explanation: 'Kooperation bedeutet Zusammenarbeit und gemeinsames Handeln zum Erreichen eines gemeinsamen Ziels.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "Kontraproduktiv"?',
      options: ['sehr nützlich', 'dem angestrebten Ziel entgegenwirkend', 'neutral', 'förderlich'],
      correct: [1],
      explanation: 'Kontraproduktiv bedeutet, dass etwas dem angestrebten Ziel schadet oder entgegenwirkt, statt es zu fördern.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "Latenz"?',
      options: ['sofortige Wirkung', 'verborgenes Vorhandensein oder Verzögerung', 'Übertreibung', 'Auflösung'],
      correct: [1],
      explanation: 'Latenz bezeichnet das verborgene Vorhandensein oder eine Verzögerung – etwas ist latent vorhanden, aber nicht sichtbar.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "Kausalität"?',
      options: ['Zufälligkeit', 'Ursache-Wirkungs-Zusammenhang', 'Gleichzeitigkeit', 'Ähnlichkeit'],
      correct: [1],
      explanation: 'Kausalität bezeichnet den Ursache-Wirkungs-Zusammenhang – eine Ursache führt zu einer bestimmten Wirkung.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "Implication" bzw. "Implikation"?',
      options: ['direkte Aussage', 'Mitbedeutung, logische Folge oder Einbeziehung', 'Widerspruch', 'Verneinung'],
      correct: [1],
      explanation: 'Implikation bezeichnet eine logische Folge oder etwas, das miteingeschlossen oder mitbedeutet wird.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "Prognose"?',
      options: ['Rückblick auf vergangene Ereignisse', 'Vorhersage über zukünftige Entwicklungen', 'Fehlerbericht', 'Analyse vergangener Fehler'],
      correct: [1],
      explanation: 'Prognose bedeutet Vorhersage – eine begründete Aussage über zukünftige Ereignisse oder Entwicklungen.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "Abstrahieren"?',
      options: ['ins Detail gehen', 'das Wesentliche verallgemeinern und vereinfachen', 'konkret beschreiben', 'widersprechen'],
      correct: [1],
      explanation: 'Abstrahieren bedeutet, das Wesentliche zu verallgemeinern und von konkreten Einzelheiten zu lösen.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "kohärent"?',
      options: ['zusammenhanglos', 'widersprüchlich', 'in sich stimmig und zusammenhängend', 'überflüssig'],
      correct: [2],
      explanation: 'Kohärent bedeutet in sich stimmig, logisch zusammenhängend und widerspruchsfrei.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "Synonym"?',
      options: ['ein Wort mit entgegengesetzter Bedeutung', 'ein Wort mit gleicher oder ähnlicher Bedeutung', 'ein Fremdwort', 'ein veraltetes Wort'],
      correct: [1],
      explanation: 'Ein Synonym ist ein Wort mit gleicher oder sehr ähnlicher Bedeutung wie ein anderes Wort.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "Antonym"?',
      options: ['ein bedeutungsgleiches Wort', 'ein Gegensatzwort', 'ein Oberbegriff', 'ein Unterbegriff'],
      correct: [1],
      explanation: 'Ein Antonym ist ein Wort mit entgegengesetzter Bedeutung – z.B. "kalt" ist das Antonym von "heiß".',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "signifikant"?',
      options: ['bedeutungslos', 'bedeutsam, wesentlich, statistisch relevant', 'zufällig', 'gering'],
      correct: [1],
      explanation: 'Signifikant bedeutet bedeutsam, wesentlich oder statistisch nachweisbar – ein signifikanter Unterschied ist klar messbar.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "Ambiguität"?',
      options: ['Eindeutigkeit', 'Mehrdeutigkeit oder Doppeldeutigkeit', 'Einfachheit', 'Vollständigkeit'],
      correct: [1],
      explanation: 'Ambiguität bezeichnet Mehrdeutigkeit – ein Begriff oder eine Situation kann auf mehrere Weisen verstanden werden.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "Persistenz"?',
      options: ['kurzfristige Erscheinung', 'Beharrlichkeit und Dauerhaftigkeit', 'Veränderlichkeit', 'Zufälligkeit'],
      correct: [1],
      explanation: 'Persistenz bedeutet Beharrlichkeit, Ausdauer und Dauerhaftigkeit – etwas Persistentes bleibt dauerhaft bestehen.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Was ist ein "Synonym" für "dezidiert"?',
      options: ['zögernd', 'ausdrücklich und entschieden', 'beiläufig', 'versteckt'],
      correct: [1],
      explanation: 'Dezidiert bedeutet entschieden und ausdrücklich – man äußert seine Meinung klar und unmissverständlich.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "Neutralität"?',
      options: ['parteiische Haltung', 'Unparteilichkeit und Ausgewogenheit', 'Sturheit', 'Feindseligkeit'],
      correct: [1],
      explanation: 'Neutralität bezeichnet Unparteilichkeit – neutral zu sein bedeutet, keiner Seite zu bevorzugen.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "eklatant" in dem Satz: "Das ist ein eklatanter Regelverstoß"?',
      options: ['kleiner und verzeihlicher', 'offensichtlicher und grober', 'zufälliger', 'nicht nachweisbarer'],
      correct: [1],
      explanation: 'Eklatant bedeutet offensichtlich, grob und nicht zu übersehen – ein eklatanter Verstoß ist besonders schwerwiegend.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "redundante Information"?',
      options: ['fehlende Information', 'überflüssige, bereits genannte Information', 'geheime Information', 'wichtige Kerninformation'],
      correct: [1],
      explanation: 'Redundante Informationen sind überflüssig, weil sie dasselbe noch einmal ausdrücken, was bereits gesagt wurde.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "resümieren"?',
      options: ['beginnen', 'zusammenfassen', 'widersprechen', 'erweitern'],
      correct: [1],
      explanation: 'Resümieren bedeutet zusammenfassen – die wichtigsten Punkte werden abschließend gebündelt dargestellt.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "explizit"?',
      options: ['versteckt und angedeutet', 'ausdrücklich und eindeutig formuliert', 'zufällig', 'überflüssig'],
      correct: [1],
      explanation: 'Explizit bedeutet ausdrücklich, klar und eindeutig formuliert – ohne Interpretationsspielraum.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "implizit"?',
      options: ['ausdrücklich benannt', 'mitgemeint, aber nicht direkt ausgesprochen', 'unwichtig', 'widersprochen'],
      correct: [1],
      explanation: 'Implizit bedeutet mitgemeint, aber nicht direkt ausgesprochen – etwas wird vorausgesetzt oder angedeutet.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "Anomalie"?',
      options: ['Regelmäßigkeit', 'Abweichung vom Normalen', 'Übereinstimmung', 'Verbesserung'],
      correct: [1],
      explanation: 'Anomalie bezeichnet eine Abweichung von der Norm oder dem Erwarteten – etwas Ungewöhnliches oder Regelwidriges.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "Legitimität"?',
      options: ['Gesetzwidrigkeit', 'Rechtmäßigkeit und Anerkennung', 'Geheimhaltung', 'Zufälligkeit'],
      correct: [1],
      explanation: 'Legitimität bezeichnet Rechtmäßigkeit und allgemeine Anerkennung – eine legitime Entscheidung gilt als berechtigt und akzeptiert.',
      difficulty: 2,
    },
    {
      type: 'fill',
      prompt: 'Jemand, der Fakten offen und nachvollziehbar kommuniziert, handelt ___________.',
      correct: [0],
      options: ['transparent'],
      explanation: 'Transparentes Handeln bedeutet Offenheit und Nachvollziehbarkeit – man verbirgt keine wesentlichen Informationen.',
      difficulty: 1,
    },
    {
      type: 'fill',
      prompt: 'Das schrittweise Einführen einer neuen Regelung bezeichnet man als ___________ Umsetzung.',
      correct: [0],
      options: ['sukzessive'],
      explanation: 'Sukzessive bedeutet schrittweise, nach und nach – also nicht auf einmal, sondern in Etappen.',
      difficulty: 2,
    },
    {
      type: 'fill',
      prompt: 'Wer vertrauliche Informationen für sich behält, verhält sich mit ___________.',
      correct: [0],
      options: ['Diskretion'],
      explanation: 'Diskretion bedeutet Verschwiegenheit und Takt im Umgang mit vertraulichen Informationen.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "konsequent"?',
      options: ['sprunghaft und unbeständig', 'folgerichtig und beharrlich', 'zögerlich', 'nachgiebig'],
      correct: [1],
      explanation: 'Konsequent bedeutet folgerichtig, beharrlich und zielstrebig – man handelt durchgängig nach einem Prinzip.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "Kompromiss"?',
      options: ['vollständige Ablehnung einer Seite', 'gegenseitiges Nachgeben zur Einigung', 'Streit ohne Ergebnis', 'einseitige Entscheidung'],
      correct: [1],
      explanation: 'Ein Kompromiss entsteht, wenn beide Seiten nachgeben, um eine gemeinsame Lösung zu finden.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "Solidarität"?',
      options: ['Gleichgültigkeit gegenüber anderen', 'Zusammenhalt und gegenseitige Unterstützung', 'Konkurrenzdenken', 'Isolation'],
      correct: [1],
      explanation: 'Solidarität bezeichnet den Zusammenhalt und die gegenseitige Unterstützung in einer Gruppe oder Gemeinschaft.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "Priorität"?',
      options: ['Unwichtigkeit', 'Vorrangigkeit und Vorrang', 'Zufälligkeit', 'Gleichwertigkeit'],
      correct: [1],
      explanation: 'Priorität bezeichnet den Vorrang – etwas mit hoher Priorität wird zuerst oder bevorzugt behandelt.',
      difficulty: 1,
    },
  ],
};

export default topic;
