import type { RawTopic } from '../types';

const topic: RawTopic = {
  slug: 'geografie',
  title: 'Geografie',
  description: 'Deutschland, Europa und die Welt.',
  flashcards: [
    { front: 'Was ist die Hauptstadt Deutschlands?', back: 'Berlin' },
    { front: 'Was ist die Hauptstadt Bayerns?', back: 'München' },
    { front: 'Was ist die Hauptstadt Nordrhein-Westfalens?', back: 'Düsseldorf' },
    { front: 'Was ist die Hauptstadt des Saarlandes?', back: 'Saarbrücken' },
    { front: 'Was ist die Hauptstadt Brandenburgs?', back: 'Potsdam' },
    { front: 'Was ist die Hauptstadt Thüringens?', back: 'Erfurt' },
    { front: 'Was ist die Hauptstadt Sachsens?', back: 'Dresden' },
    { front: 'Was ist die Hauptstadt Hamburgs?', back: 'Hamburg (Stadtstaat)' },
    { front: 'Was ist die Hauptstadt Bremens?', back: 'Bremen (Stadtstaat)' },
    { front: 'Was ist die Hauptstadt Baden-Württembergs?', back: 'Stuttgart' },
    { front: 'Was ist die Hauptstadt Hessens?', back: 'Wiesbaden' },
    { front: 'Was ist die Hauptstadt Rheinland-Pfalz?', back: 'Mainz' },
    { front: 'Was ist die Hauptstadt Schleswig-Holsteins?', back: 'Kiel' },
    { front: 'Was ist die Hauptstadt Mecklenburg-Vorpommerns?', back: 'Schwerin' },
    { front: 'Was ist die Hauptstadt Sachsen-Anhalts?', back: 'Magdeburg' },
    { front: 'Was ist die Hauptstadt Niedersachsens?', back: 'Hannover' },
    { front: 'Wie viele Bundesländer hat Deutschland?', back: '16 Bundesländer' },
    { front: 'Wie viele Nachbarländer hat Deutschland?', back: '9 Nachbarländer: Dänemark, Polen, Tschechien, Österreich, Schweiz, Frankreich, Luxemburg, Belgien, Niederlande' },
    { front: 'Welcher ist der längste Fluss Deutschlands?', back: 'Der Rhein (865 km auf deutschem Gebiet)' },
    { front: 'Welcher ist der höchste Berg Deutschlands?', back: 'Die Zugspitze (2.962 m)' },
    { front: 'Was ist die Hauptstadt Frankreichs?', back: 'Paris' },
    { front: 'Was ist die Hauptstadt Italiens?', back: 'Rom' },
    { front: 'Was ist die Hauptstadt Spaniens?', back: 'Madrid' },
    { front: 'Welcher Ozean ist der größte der Welt?', back: 'Der Pazifik (Pazifischer Ozean)' },
    { front: 'Welcher ist der längste Fluss der Welt?', back: 'Der Nil (ca. 6.650 km), oft auch der Amazonas genannt' },
    { front: 'Welcher ist der höchste Berg der Welt?', back: 'Der Mount Everest (8.849 m) im Himalaya' },
    { front: 'Welches ist das flächenmäßig größte Land der Welt?', back: 'Russland (ca. 17,1 Millionen km²)' },
    { front: 'Wie viele Kontinente gibt es?', back: '7 Kontinente: Afrika, Antarktika, Asien, Australien/Ozeanien, Europa, Nordamerika, Südamerika' },
  ],
  questions: [
    {
      type: 'mc',
      prompt: 'Was ist die Hauptstadt des Saarlandes?',
      options: ['Saarbrücken', 'Mainz', 'Kaiserslautern', 'Trier'],
      correct: [0],
      explanation: 'Die Hauptstadt des Saarlandes ist Saarbrücken.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist die Hauptstadt Bayerns?',
      options: ['Nürnberg', 'Augsburg', 'München', 'Regensburg'],
      correct: [2],
      explanation: 'Die Hauptstadt Bayerns ist München.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist die Hauptstadt von Nordrhein-Westfalen?',
      options: ['Köln', 'Düsseldorf', 'Dortmund', 'Essen'],
      correct: [1],
      explanation: 'Die Hauptstadt von Nordrhein-Westfalen ist Düsseldorf, obwohl Köln die bevölkerungsreichste Stadt ist.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist die Hauptstadt Deutschlands?',
      options: ['Frankfurt am Main', 'Hamburg', 'Bonn', 'Berlin'],
      correct: [3],
      explanation: 'Die Hauptstadt Deutschlands ist Berlin. Bonn war von 1949 bis 1990 Hauptstadt der Bundesrepublik.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Wie viele Bundesländer hat Deutschland?',
      options: ['12', '14', '16', '18'],
      correct: [2],
      explanation: 'Deutschland hat 16 Bundesländer, darunter drei Stadtstaaten: Berlin, Hamburg und Bremen.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Wie viele Nachbarländer hat Deutschland?',
      options: ['7', '8', '9', '10'],
      correct: [2],
      explanation: 'Deutschland hat 9 Nachbarländer: Dänemark, Polen, Tschechien, Österreich, Schweiz, Frankreich, Luxemburg, Belgien und die Niederlande.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welches dieser Länder ist KEIN Nachbarland Deutschlands?',
      options: ['Luxemburg', 'Schweden', 'Österreich', 'Belgien'],
      correct: [1],
      explanation: 'Schweden ist kein Nachbarland Deutschlands. Die 9 Nachbarländer sind: Dänemark, Polen, Tschechien, Österreich, Schweiz, Frankreich, Luxemburg, Belgien und die Niederlande.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welcher ist der längste Fluss Deutschlands?',
      options: ['Elbe', 'Donau', 'Rhein', 'Weser'],
      correct: [2],
      explanation: 'Der Rhein ist mit etwa 865 km auf deutschem Gebiet der längste Fluss Deutschlands. Die Donau ist zwar länger insgesamt, hat aber weniger Kilometer in Deutschland.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welcher ist der höchste Berg Deutschlands?',
      options: ['Feldberg', 'Brocken', 'Zugspitze', 'Watzmann'],
      correct: [2],
      explanation: 'Die Zugspitze ist mit 2.962 m der höchste Berg Deutschlands. Sie liegt an der Grenze zwischen Deutschland und Österreich.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist die Hauptstadt Brandenburgs?',
      options: ['Brandenburg an der Havel', 'Potsdam', 'Cottbus', 'Frankfurt (Oder)'],
      correct: [1],
      explanation: 'Die Hauptstadt Brandenburgs ist Potsdam, bekannt für seine Schlösser und Gärten, besonders das Schloss Sanssouci.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was ist die Hauptstadt Thüringens?',
      options: ['Weimar', 'Jena', 'Gera', 'Erfurt'],
      correct: [3],
      explanation: 'Die Hauptstadt Thüringens ist Erfurt. Weimar und Jena sind zwar bekannte Städte Thüringens, aber nicht die Landeshauptstadt.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was ist die Hauptstadt Sachsens?',
      options: ['Leipzig', 'Chemnitz', 'Dresden', 'Zwickau'],
      correct: [2],
      explanation: 'Die Hauptstadt Sachsens ist Dresden, bekannt als "Elbflorenz".',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist die Hauptstadt Hessens?',
      options: ['Frankfurt am Main', 'Wiesbaden', 'Kassel', 'Darmstadt'],
      correct: [1],
      explanation: 'Die Hauptstadt Hessens ist Wiesbaden, nicht Frankfurt am Main, das zwar größer, aber nicht Landeshauptstadt ist.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was ist die Hauptstadt Rheinland-Pfalz?',
      options: ['Koblenz', 'Ludwigshafen', 'Trier', 'Mainz'],
      correct: [3],
      explanation: 'Die Hauptstadt von Rheinland-Pfalz ist Mainz am Rhein.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist die Hauptstadt Schleswig-Holsteins?',
      options: ['Lübeck', 'Kiel', 'Flensburg', 'Neumünster'],
      correct: [1],
      explanation: 'Die Hauptstadt Schleswig-Holsteins ist Kiel, bekannt als Fördestadt und Standort der Kieler Woche.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist die Hauptstadt Mecklenburg-Vorpommerns?',
      options: ['Rostock', 'Greifswald', 'Schwerin', 'Stralsund'],
      correct: [2],
      explanation: 'Die Hauptstadt Mecklenburg-Vorpommerns ist Schwerin mit seinem bekannten Schweriner Schloss.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was ist die Hauptstadt Sachsen-Anhalts?',
      options: ['Halle (Saale)', 'Dessau-Roßlau', 'Magdeburg', 'Wittenberg'],
      correct: [2],
      explanation: 'Die Hauptstadt Sachsen-Anhalts ist Magdeburg an der Elbe.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was ist die Hauptstadt Niedersachsens?',
      options: ['Braunschweig', 'Osnabrück', 'Hannover', 'Göttingen'],
      correct: [2],
      explanation: 'Die Hauptstadt Niedersachsens ist Hannover.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist die Hauptstadt Frankreichs?',
      options: ['Lyon', 'Marseille', 'Bordeaux', 'Paris'],
      correct: [3],
      explanation: 'Die Hauptstadt Frankreichs ist Paris, eine der bevölkerungsreichsten Städte Europas.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist die Hauptstadt Italiens?',
      options: ['Mailand', 'Rom', 'Florenz', 'Neapel'],
      correct: [1],
      explanation: 'Die Hauptstadt Italiens ist Rom, die "Ewige Stadt" und Sitz des Vatikans.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist die Hauptstadt Spaniens?',
      options: ['Barcelona', 'Sevilla', 'Madrid', 'Valencia'],
      correct: [2],
      explanation: 'Die Hauptstadt Spaniens ist Madrid, die größte Stadt des Landes.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist die Hauptstadt Polens?',
      options: ['Krakau', 'Warschau', 'Breslau', 'Danzig'],
      correct: [1],
      explanation: 'Die Hauptstadt Polens ist Warschau (polnisch: Warszawa).',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist die Hauptstadt der Niederlande?',
      options: ['Rotterdam', 'Utrecht', 'Den Haag', 'Amsterdam'],
      correct: [3],
      explanation: 'Die Hauptstadt der Niederlande ist Amsterdam. Den Haag ist zwar Regierungssitz, aber nicht die Hauptstadt.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was ist die Hauptstadt Österreichs?',
      options: ['Salzburg', 'Innsbruck', 'Wien', 'Graz'],
      correct: [2],
      explanation: 'Die Hauptstadt Österreichs ist Wien, gleichzeitig die größte Stadt des Landes.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist die Hauptstadt der Schweiz?',
      options: ['Zürich', 'Genf', 'Bern', 'Basel'],
      correct: [2],
      explanation: 'Die Hauptstadt der Schweiz ist Bern (Bundesstadt). Zürich ist zwar größer, aber nicht die Hauptstadt.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welcher Ozean ist der größte der Welt?',
      options: ['Atlantischer Ozean', 'Indischer Ozean', 'Pazifischer Ozean', 'Arktischer Ozean'],
      correct: [2],
      explanation: 'Der Pazifische Ozean ist mit einer Fläche von etwa 165 Millionen km² der größte Ozean der Welt.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Wie viele Ozeane gibt es auf der Erde?',
      options: ['3', '4', '5', '6'],
      correct: [2],
      explanation: 'Es gibt 5 Ozeane: Pazifischer Ozean, Atlantischer Ozean, Indischer Ozean, Arktischer Ozean (Nordpolarmeer) und Antarktischer Ozean (Südpolarmeer).',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welcher ist der höchste Berg der Welt?',
      options: ['K2', 'Kangchendzönga', 'Mount Everest', 'Lhotse'],
      correct: [2],
      explanation: 'Der Mount Everest im Himalaya ist mit 8.849 m der höchste Berg der Welt.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welches ist das flächenmäßig größte Land der Welt?',
      options: ['Kanada', 'China', 'USA', 'Russland'],
      correct: [3],
      explanation: 'Russland ist mit ca. 17,1 Millionen km² das flächenmäßig größte Land der Welt.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Wie viele Kontinente gibt es?',
      options: ['5', '6', '7', '8'],
      correct: [2],
      explanation: 'Es gibt 7 Kontinente: Afrika, Antarktika, Asien, Australien/Ozeanien, Europa, Nordamerika und Südamerika.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welcher Kontinent ist der größte?',
      options: ['Afrika', 'Amerika', 'Asien', 'Australien'],
      correct: [2],
      explanation: 'Asien ist mit ca. 44,6 Millionen km² der größte Kontinent der Erde.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Wo liegt die Zugspitze?',
      options: ['Nur in Deutschland', 'An der Grenze zwischen Deutschland und Österreich', 'Nur in Österreich', 'An der Grenze zwischen Deutschland und der Schweiz'],
      correct: [1],
      explanation: 'Die Zugspitze liegt an der Grenze zwischen Deutschland (Bayern) und Österreich (Tirol).',
      difficulty: 2,
    },
    {
      type: 'truefalse',
      prompt: 'Hamburg ist ein Stadtstaat und gleichzeitig ein Bundesland.',
      options: ['Wahr', 'Falsch'],
      correct: [0],
      explanation: 'Hamburg ist tatsächlich ein Stadtstaat und gleichzeitig eines der 16 deutschen Bundesländer. Die anderen Stadtstaaten sind Berlin und Bremen.',
      difficulty: 1,
    },
    {
      type: 'truefalse',
      prompt: 'Der Rhein entspringt in Deutschland.',
      options: ['Wahr', 'Falsch'],
      correct: [1],
      explanation: 'Der Rhein entspringt in der Schweiz (im Kanton Graubünden) und fließt dann durch Deutschland, bevor er in den Niederlanden in die Nordsee mündet.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Welches Bundesland grenzt im Norden direkt an Dänemark?',
      options: ['Mecklenburg-Vorpommern', 'Hamburg', 'Schleswig-Holstein', 'Niedersachsen'],
      correct: [2],
      explanation: 'Schleswig-Holstein grenzt als einziges deutsches Bundesland direkt an Dänemark.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'In welchem Bundesland liegt der Brocken, der höchste Berg Norddeutschlands?',
      options: ['Niedersachsen', 'Thüringen', 'Sachsen-Anhalt', 'Sachsen'],
      correct: [2],
      explanation: 'Der Brocken (1.141 m) liegt im Harz in Sachsen-Anhalt und ist der höchste Berg Norddeutschlands.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Welche Hauptstadt liegt weiter östlich: Warschau oder Wien?',
      options: ['Wien', 'Warschau', 'Beide liegen auf dem gleichen Längengrad', 'Das lässt sich nicht bestimmen'],
      correct: [1],
      explanation: 'Warschau (ca. 21° östl. Länge) liegt weiter östlich als Wien (ca. 16° östl. Länge).',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Was ist die Hauptstadt von Belgien?',
      options: ['Antwerpen', 'Gent', 'Brüssel', 'Lüttich'],
      correct: [2],
      explanation: 'Die Hauptstadt Belgiens ist Brüssel (französisch: Bruxelles, niederländisch: Brussel), gleichzeitig Sitz der EU-Kommission.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welcher Fluss fließt durch die Bundeshauptstadt Berlin?',
      options: ['Elbe', 'Oder', 'Spree', 'Havel'],
      correct: [2],
      explanation: 'Durch Berlin fließt die Spree. Die Havel bildet im Westen die Grenze Berlins zu Brandenburg.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was ist die Hauptstadt Luxemburgs?',
      options: ['Trier', 'Esch-sur-Alzette', 'Luxemburg (Stadt)', 'Echternach'],
      correct: [2],
      explanation: 'Die Hauptstadt des Großherzogtums Luxemburg ist die Stadt Luxemburg (Luxemburg-Stadt).',
      difficulty: 2,
    },
  ],
};

export default topic;
