import type { RawTopic } from '../types';

const topic: RawTopic = {
  slug: 'geschichte',
  title: 'Geschichte',
  description: 'Wichtige Eckdaten der deutschen und Weltgeschichte.',
  flashcards: [
    {
      front: 'Wann begann und endete der Erste Weltkrieg?',
      back: 'Der Erste Weltkrieg dauerte von 1914 bis 1918.',
    },
    {
      front: 'In welchem Jahr wurde die Weimarer Republik gegründet?',
      back: 'Die Weimarer Republik wurde 1919 nach dem Ende des Ersten Weltkriegs gegründet.',
    },
    {
      front: 'Wann übernahm Adolf Hitler die Macht in Deutschland?',
      back: 'Die Machtergreifung Hitlers fand am 30. Januar 1933 statt, als er zum Reichskanzler ernannt wurde.',
    },
    {
      front: 'Wann begann der Zweite Weltkrieg?',
      back: 'Der Zweite Weltkrieg begann am 1. September 1939 mit dem deutschen Überfall auf Polen.',
    },
    {
      front: 'Wann endete der Zweite Weltkrieg in Europa?',
      back: 'Der Zweite Weltkrieg in Europa endete am 8. Mai 1945 mit der bedingungslosen Kapitulation Deutschlands (Tag der Befreiung).',
    },
    {
      front: 'Wann wurden die BRD und die DDR gegründet?',
      back: 'Die Bundesrepublik Deutschland (BRD) und die Deutsche Demokratische Republik (DDR) wurden beide 1949 gegründet.',
    },
    {
      front: 'Wann wurde die Berliner Mauer gebaut?',
      back: 'Der Bau der Berliner Mauer begann in der Nacht vom 12. auf den 13. August 1961.',
    },
    {
      front: 'Wann fiel die Berliner Mauer?',
      back: 'Die Berliner Mauer fiel am 9. November 1989.',
    },
    {
      front: 'Wann fand die deutsche Wiedervereinigung statt?',
      back: 'Die deutsche Wiedervereinigung fand am 3. Oktober 1990 statt. Dieser Tag wird als "Tag der Deutschen Einheit" gefeiert.',
    },
    {
      front: 'Wann begann die Französische Revolution?',
      back: 'Die Französische Revolution begann 1789 mit dem Sturm auf die Bastille am 14. Juli 1789.',
    },
    {
      front: 'In welchem Jahr entdeckte Christoph Kolumbus Amerika?',
      back: 'Christoph Kolumbus erreichte am 12. Oktober 1492 die Bahamas und "entdeckte" damit Amerika für Europa.',
    },
    {
      front: 'Wann begann die Reformation durch Martin Luther?',
      back: 'Die Reformation begann 1517, als Martin Luther seine 95 Thesen an die Schlosskirche zu Wittenberg schlug (31. Oktober 1517).',
    },
    {
      front: 'Wann erfand Johannes Gutenberg den Buchdruck mit beweglichen Lettern?',
      back: 'Johannes Gutenberg erfand den Buchdruck mit beweglichen Metalllettern um 1450. Die Gutenberg-Bibel entstand etwa 1452–1455.',
    },
    {
      front: 'Wann wurde die Vereinten Nationen (UNO) gegründet?',
      back: 'Die Vereinten Nationen (UNO) wurden am 26. Juni 1945 mit der Unterzeichnung der UN-Charta in San Francisco gegründet.',
    },
    {
      front: 'Wann endete das Weströmische Reich?',
      back: 'Das Weströmische Reich endete im Jahr 476 n. Chr. mit der Absetzung des letzten weströmischen Kaisers Romulus Augustulus.',
    },
    {
      front: 'Was war das Attentat von Sarajevo und in welchem Jahr fand es statt?',
      back: 'Am 28. Juni 1914 wurde der österreichisch-ungarische Thronfolger Erzherzog Franz Ferdinand in Sarajevo ermordet. Dieses Ereignis gilt als unmittelbarer Auslöser des Ersten Weltkriegs.',
    },
    {
      front: 'Was versteht man unter dem "Versailler Vertrag" und wann wurde er unterzeichnet?',
      back: 'Der Versailler Vertrag war der Friedensvertrag nach dem Ersten Weltkrieg. Er wurde am 28. Juni 1919 unterzeichnet und legte Deutschland schwere Kriegsreparationen und Gebietsabtretungen auf.',
    },
    {
      front: 'Was war die Kristallnacht und wann fand sie statt?',
      back: 'Die Kristallnacht (Reichspogromnacht) war ein von den Nationalsozialisten organisierter Pogrom gegen Juden in der Nacht vom 9. auf den 10. November 1938. Synagogen wurden zerstört, jüdische Geschäfte geplündert und Tausende Menschen verhaftet.',
    },
    {
      front: 'Wann und wo begann der Dreißigjährige Krieg?',
      back: 'Der Dreißigjährige Krieg begann 1618 mit dem Prager Fenstersturz und endete 1648 mit dem Westfälischen Frieden.',
    },
    {
      front: 'Was war der Marshallplan?',
      back: 'Der Marshallplan (Europäisches Wiederaufbauprogramm) war ein US-amerikanisches Hilfsprogramm zum wirtschaftlichen Wiederaufbau Westeuropas nach dem Zweiten Weltkrieg (1948–1952).',
    },
  ],
  questions: [
    {
      type: 'mc',
      prompt: 'Wann fand die deutsche Wiedervereinigung statt?',
      options: ['3. Oktober 1990', '9. November 1989', '1. Januar 1991', '23. Mai 1949'],
      correct: [0],
      explanation: 'Am 3. Oktober 1990 wurde Deutschland wiedervereinigt. Dieser Tag wird als "Tag der Deutschen Einheit" gefeiert.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'In welchem Jahr wurde die Berliner Mauer gebaut?',
      options: ['1955', '1949', '1961', '1968'],
      correct: [2],
      explanation: 'Der Bau der Berliner Mauer begann in der Nacht vom 12. auf den 13. August 1961, um die Massenflucht von DDR-Bürgern in den Westen zu stoppen.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Wann fiel die Berliner Mauer?',
      options: ['3. Oktober 1990', '9. November 1989', '1. Juli 1990', '18. März 1990'],
      correct: [1],
      explanation: 'Die Berliner Mauer fiel am 9. November 1989, als die DDR-Regierung die Grenzöffnung verkündete.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Wann begann der Zweite Weltkrieg?',
      options: ['3. September 1939', '1. August 1914', '1. September 1939', '10. Mai 1940'],
      correct: [2],
      explanation: 'Der Zweite Weltkrieg begann am 1. September 1939 mit dem deutschen Überfall auf Polen.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'An welchem Datum endete der Zweite Weltkrieg in Europa?',
      options: ['2. September 1945', '8. Mai 1945', '7. Mai 1945', '30. April 1945'],
      correct: [1],
      explanation: 'Am 8. Mai 1945 unterzeichnete Deutschland die bedingungslose Kapitulation. Dieser Tag gilt als offizielles Kriegsende in Europa.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'In welchem Jahr entdeckte Christoph Kolumbus Amerika?',
      options: ['1488', '1498', '1492', '1502'],
      correct: [2],
      explanation: 'Christoph Kolumbus erreichte am 12. Oktober 1492 die Bahamas und damit als erster Europäer der Neuzeit den amerikanischen Kontinent.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Wann schlug Martin Luther seine 95 Thesen an und leitete damit die Reformation ein?',
      options: ['1517', '1521', '1509', '1530'],
      correct: [0],
      explanation: 'Am 31. Oktober 1517 soll Martin Luther seine 95 Thesen an die Tür der Schlosskirche zu Wittenberg geschlagen haben. Dieses Datum gilt als Beginn der Reformation.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Wann wurde die Weimarer Republik in Deutschland gegründet?',
      options: ['1918', '1919', '1920', '1921'],
      correct: [1],
      explanation: 'Die Weimarer Republik wurde 1919 gegründet. Die Weimarer Verfassung trat am 14. August 1919 in Kraft.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Wann wurde Hitler zum Reichskanzler ernannt (Machtergreifung)?',
      options: ['30. Januar 1933', '5. März 1933', '23. März 1933', '28. Februar 1933'],
      correct: [0],
      explanation: 'Adolf Hitler wurde am 30. Januar 1933 von Reichspräsident Paul von Hindenburg zum Reichskanzler ernannt.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'In welchem Jahr wurden BRD und DDR gegründet?',
      options: ['1945', '1947', '1949', '1951'],
      correct: [2],
      explanation: 'Die Bundesrepublik Deutschland (BRD) wurde am 23. Mai 1949 gegründet, die Deutsche Demokratische Republik (DDR) am 7. Oktober 1949.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Wann begann die Französische Revolution?',
      options: ['1776', '1799', '1789', '1815'],
      correct: [2],
      explanation: 'Die Französische Revolution begann 1789 mit dem Sturm auf die Bastille am 14. Juli 1789.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Wann wurde die Vereinten Nationen (UNO) gegründet?',
      options: ['1945', '1946', '1919', '1948'],
      correct: [0],
      explanation: 'Die UNO wurde am 26. Juni 1945 mit der Unterzeichnung der UN-Charta in San Francisco gegründet.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Wann erfand Johannes Gutenberg den Buchdruck mit beweglichen Lettern?',
      options: ['Um 1350', 'Um 1450', 'Um 1550', 'Um 1250'],
      correct: [1],
      explanation: 'Johannes Gutenberg erfand den Buchdruck mit beweglichen Metalllettern um 1450. Die Gutenberg-Bibel entstand etwa 1452–1455.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welches Ereignis gilt als unmittelbarer Auslöser des Ersten Weltkriegs?',
      options: [
        'Die Julikrise und Mobilmachung Russlands',
        'Das Attentat auf Erzherzog Franz Ferdinand in Sarajevo',
        'Der deutsche Einmarsch in Belgien',
        'Die Versenkung der Lusitania',
      ],
      correct: [1],
      explanation: 'Das Attentat auf den österreichisch-ungarischen Thronfolger Erzherzog Franz Ferdinand am 28. Juni 1914 in Sarajevo gilt als unmittelbarer Auslöser des Ersten Weltkriegs.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'In welchem Jahr endete das Weströmische Reich?',
      options: ['395 n. Chr.', '476 n. Chr.', '533 n. Chr.', '410 n. Chr.'],
      correct: [1],
      explanation: 'Das Weströmische Reich endete 476 n. Chr. mit der Absetzung des letzten Kaisers Romulus Augustulus durch den germanischen Heerführer Odoaker.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welcher Vertrag beendete den Ersten Weltkrieg offiziell?',
      options: ['Vertrag von Versailles', 'Vertrag von Brest-Litowsk', 'Münchner Abkommen', 'Vertrag von Utrecht'],
      correct: [0],
      explanation: 'Der Vertrag von Versailles, unterzeichnet am 28. Juni 1919, beendete offiziell den Ersten Weltkrieg und legte Deutschland schwere Bedingungen auf.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was war die Kristallnacht und wann fand sie statt?',
      options: [
        'Ein Generalstreik der Arbeiter, 1936',
        'Ein antisemitischer Pogrom, 9./10. November 1938',
        'Die Verbrennung von Büchern, 10. Mai 1933',
        'Ein Anschlag auf das Reichstagsgebäude, 27. Februar 1933',
      ],
      correct: [1],
      explanation: 'Die Kristallnacht (Reichspogromnacht) war ein von den Nationalsozialisten organisierter Pogrom in der Nacht vom 9. auf den 10. November 1938, bei dem Synagogen brannten und jüdische Geschäfte zerstört wurden.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Wann begann der Dreißigjährige Krieg?',
      options: ['1608', '1618', '1628', '1648'],
      correct: [1],
      explanation: 'Der Dreißigjährige Krieg begann 1618 mit dem Prager Fenstersturz und verwüstete weite Teile Mitteleuropas bis zum Westfälischen Frieden 1648.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Mit welchem Vertrag endete der Dreißigjährige Krieg?',
      options: ['Vertrag von Versailles', 'Prager Frieden', 'Westfälischer Frieden', 'Augsburger Religionsfrieden'],
      correct: [2],
      explanation: 'Der Dreißigjährige Krieg endete 1648 mit dem Westfälischen Frieden (Verträge von Münster und Osnabrück).',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was war der Marshallplan?',
      options: [
        'Ein militärisches Bündnis der Westmächte nach 1945',
        'Ein US-amerikanisches Wiederaufbauprogramm für Westeuropa nach dem Zweiten Weltkrieg',
        'Ein Verteilungsplan für deutsche Kriegsgefangene',
        'Ein Grenzziehungsplan nach dem Zweiten Weltkrieg',
      ],
      correct: [1],
      explanation: 'Der Marshallplan (Europäisches Wiederaufbauprogramm, ERP) war ein US-amerikanisches Hilfsprogramm zum wirtschaftlichen Wiederaufbau Westeuropas nach dem Zweiten Weltkrieg (1948–1952).',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Wann wurde das Grundgesetz der Bundesrepublik Deutschland verabschiedet?',
      options: ['8. Mai 1949', '23. Mai 1949', '7. Oktober 1949', '14. August 1919'],
      correct: [1],
      explanation: 'Das Grundgesetz der Bundesrepublik Deutschland wurde am 23. Mai 1949 verkündet und trat damit in Kraft.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Wann trat Deutschland der NATO bei?',
      options: ['1949', '1951', '1955', '1957'],
      correct: [2],
      explanation: 'Die Bundesrepublik Deutschland trat am 9. Mai 1955 der NATO bei.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Wann wurde die Europäische Wirtschaftsgemeinschaft (EWG) gegründet?',
      options: ['1951', '1957', '1963', '1945'],
      correct: [1],
      explanation: 'Die Europäische Wirtschaftsgemeinschaft (EWG) wurde durch die Römischen Verträge am 25. März 1957 gegründet und trat am 1. Januar 1958 in Kraft.',
      difficulty: 3,
    },
    {
      type: 'truefalse',
      prompt: 'Der Tag der Deutschen Einheit wird am 9. November gefeiert.',
      options: ['Wahr', 'Falsch'],
      correct: [1],
      explanation: 'Falsch. Der Tag der Deutschen Einheit wird am 3. Oktober gefeiert, dem Tag der Wiedervereinigung 1990. Der 9. November ist zwar historisch bedeutsam (Mauerfall 1989), ist aber kein offizieller Feiertag.',
      difficulty: 1,
    },
    {
      type: 'truefalse',
      prompt: 'Der Erste Weltkrieg dauerte von 1914 bis 1918.',
      options: ['Wahr', 'Falsch'],
      correct: [0],
      explanation: 'Wahr. Der Erste Weltkrieg begann im August 1914 und endete am 11. November 1918 mit dem Waffenstillstand von Compiegne.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Wann fand die Konferenz von Jalta statt, bei der die Nachkriegsordnung Europas beschlossen wurde?',
      options: ['Januar 1945', 'Februar 1945', 'Juli 1945', 'August 1945'],
      correct: [1],
      explanation: 'Die Konferenz von Jalta fand vom 4. bis 11. Februar 1945 statt. Churchill, Roosevelt und Stalin einigten sich dort auf die Neuordnung Europas nach dem Zweiten Weltkrieg.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Welche Stadt war Hauptstadt der Weimarer Republik?',
      options: ['Frankfurt am Main', 'Berlin', 'Weimar', 'München'],
      correct: [1],
      explanation: 'Die Hauptstadt der Weimarer Republik war Berlin. Der Name "Weimarer Republik" leitet sich von der Stadt Weimar ab, wo 1919 die Nationalversammlung tagte und die Verfassung beschlossen wurde.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was war die Ursache für den Eintritt der USA in den Ersten Weltkrieg 1917?',
      options: [
        'Der Angriff auf Pearl Harbor',
        'Die Versenkung der Lusitania und der uneingeschränkte U-Boot-Krieg Deutschlands',
        'Das Attentat in Sarajevo',
        'Die russische Revolution',
      ],
      correct: [1],
      explanation: 'Hauptgründe für den US-Kriegseintritt 1917 waren der uneingeschränkte deutsche U-Boot-Krieg und die Versenkung des Passagierschiffs Lusitania (1915). Die USA erklärten Deutschland am 6. April 1917 den Krieg.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'In welchem Jahr wurde Karl der Große zum Kaiser des Frankenreichs gekrönt?',
      options: ['768', '800', '814', '843'],
      correct: [1],
      explanation: 'Karl der Große wurde am 25. Dezember 800 n. Chr. in Rom von Papst Leo III. zum Kaiser der Römer gekrönt.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Was versteht man unter der "Stunde Null" in der deutschen Geschichte?',
      options: [
        'Den Beginn des Zweiten Weltkriegs 1939',
        'Das Ende des Zweiten Weltkriegs 1945 als Neubeginn Deutschlands',
        'Den Beginn der Weimarer Republik 1919',
        'Den Fall der Berliner Mauer 1989',
      ],
      correct: [1],
      explanation: 'Als "Stunde Null" bezeichnet man das Ende des Zweiten Weltkriegs im Mai 1945, das für Deutschland einen totalen Zusammenbruch und gleichzeitig einen Neuanfang bedeutete.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Wann wurde die DDR offiziell aufgelöst und trat der BRD bei?',
      options: ['9. November 1989', '18. März 1990', '1. Juli 1990', '3. Oktober 1990'],
      correct: [3],
      explanation: 'Die DDR trat am 3. Oktober 1990 der Bundesrepublik Deutschland bei. Mit diesem Datum endete die staatliche Existenz der DDR und die deutsche Wiedervereinigung war vollzogen.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welcher deutsche Kaiser dankte am Ende des Ersten Weltkriegs ab?',
      options: ['Wilhelm I.', 'Friedrich III.', 'Wilhelm II.', 'Karl I.'],
      correct: [2],
      explanation: 'Kaiser Wilhelm II. dankte am 9. November 1918 ab und floh ins niederländische Exil. Damit endete die Monarchie in Deutschland.',
      difficulty: 2,
    },
    {
      type: 'truefalse',
      prompt: 'Die Vereinten Nationen (UNO) wurden bereits vor dem Ende des Zweiten Weltkriegs gegründet.',
      options: ['Wahr', 'Falsch'],
      correct: [0],
      explanation: 'Wahr. Die UN-Charta wurde am 26. Juni 1945 unterzeichnet, also noch vor dem offiziellen Ende des Zweiten Weltkriegs im Pazifik (2. September 1945). Sie trat am 24. Oktober 1945 in Kraft.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Was war die Bedeutung des Augsburger Religionsfriedens von 1555?',
      options: [
        'Er beendete den Dreißigjährigen Krieg',
        'Er anerkannte erstmals rechtlich die Koexistenz von Katholizismus und Luthertum im Reich',
        'Er legte die Grenzen des Heiligen Römischen Reichs fest',
        'Er beendete die Kreuzzüge',
      ],
      correct: [1],
      explanation: 'Der Augsburger Religionsfrieden von 1555 anerkannte erstmals rechtlich die Koexistenz von Katholizismus und Luthertum im Heiligen Römischen Reich Deutscher Nation nach dem Grundsatz "cuius regio, eius religio".',
      difficulty: 3,
    },
  ],
};

export default topic;
