import type { RawTopic } from '../types';

const topic: RawTopic = {
  slug: 'gewaltenteilung',
  title: 'Gewaltenteilung & Föderalismus',
  description: 'Legislative, Exekutive, Judikative und der Bundesstaat.',
  flashcards: [
    {
      front: 'Was versteht man unter Gewaltenteilung?',
      back: 'Die Aufteilung der Staatsgewalt in drei unabhängige Bereiche: Legislative (gesetzgebend), Exekutive (ausführend) und Judikative (rechtsprechend), um Machtmissbrauch zu verhindern.',
    },
    {
      front: 'Wer hat das Prinzip der Gewaltenteilung maßgeblich geprägt?',
      back: 'Charles de Montesquieu (1689–1755), französischer Philosoph und Staatstheoretiker, beschrieb die Gewaltenteilung in seinem Werk "Vom Geist der Gesetze" (1748).',
    },
    {
      front: 'Was ist die Legislative?',
      back: 'Die gesetzgebende Gewalt. Auf Bundesebene: Bundestag und Bundesrat. Auf Landesebene: die Landtage (bzw. Bürgerschaft in Hamburg und Bremen, Abgeordnetenhaus in Berlin).',
    },
    {
      front: 'Was ist die Exekutive?',
      back: 'Die vollziehende (ausführende) Gewalt. Sie setzt Gesetze um und verwaltet den Staat. Dazu gehören Regierung, Ministerien, Behörden, Polizei und öffentlicher Dienst.',
    },
    {
      front: 'Was ist die Judikative?',
      back: 'Die rechtsprechende Gewalt. Sie wendet das Recht an und kontrolliert Legislative und Exekutive. Dazu gehören alle Gerichte, z. B. Verwaltungsgerichte, Amtsgerichte und das Bundesverfassungsgericht.',
    },
    {
      front: 'Was bedeutet "Checks and Balances"?',
      back: 'Das System gegenseitiger Kontrolle und Hemmung der drei Staatsgewalten, sodass keine Gewalt die anderen dominieren kann. Beispiel: Gesetze werden vom Parlament beschlossen, aber vom Bundesverfassungsgericht auf Verfassungsmäßigkeit geprüft.',
    },
    {
      front: 'Was ist Föderalismus?',
      back: 'Ein Staatsaufbau, bei dem die Staatsgewalt auf mehrere Ebenen verteilt ist: Bund, Länder und Kommunen. Die Bundesrepublik Deutschland ist ein föderaler Bundesstaat.',
    },
    {
      front: 'Wie viele Bundesländer hat Deutschland?',
      back: '16 Bundesländer: Bayern, Baden-Württemberg, Brandenburg, Bremen, Hamburg, Hessen, Mecklenburg-Vorpommern, Niedersachsen, Nordrhein-Westfalen, Rheinland-Pfalz, Saarland, Sachsen, Sachsen-Anhalt, Schleswig-Holstein, Thüringen und Berlin.',
    },
    {
      front: 'Was ist der Bundesrat?',
      back: 'Der Bundesrat ist die Vertretung der 16 Bundesländer auf Bundesebene. Er wirkt an der Gesetzgebung und Verwaltung des Bundes sowie in Angelegenheiten der Europäischen Union mit.',
    },
    {
      front: 'Was ist der Unterschied zwischen ausschließlicher und konkurrierender Gesetzgebung?',
      back: 'Bei der ausschließlichen Gesetzgebung darf nur der Bund Gesetze erlassen (z. B. Außenpolitik, Verteidigung). Bei der konkurrierenden Gesetzgebung können die Länder tätig werden, solange und soweit der Bund keine Regelung getroffen hat (z. B. Strafrecht, Arbeitsrecht).',
    },
    {
      front: 'Was ist das Subsidiaritätsprinzip?',
      back: 'Das Prinzip, dass staatliche Aufgaben möglichst auf der niedrigsten geeigneten Ebene wahrgenommen werden sollen. Übergeordnete Ebenen sollen nur eingreifen, wenn untergeordnete Ebenen eine Aufgabe nicht ausreichend erfüllen können.',
    },
    {
      front: 'Was regelt Artikel 28 GG zur kommunalen Selbstverwaltung?',
      back: 'Art. 28 Abs. 2 GG garantiert den Gemeinden das Recht, alle Angelegenheiten der örtlichen Gemeinschaft im Rahmen der Gesetze in eigener Verantwortung zu regeln (kommunale Selbstverwaltungsgarantie).',
    },
    {
      front: 'Welche Staatsorgane gehören zur Exekutive auf Bundesebene?',
      back: 'Bundeskanzler:in, Bundesminister:innen, Bundesministerien, nachgeordnete Bundesbehörden (z. B. Bundeskriminalamt, Bundespolizei) sowie der Bundespräsident in seiner vollziehenden Funktion.',
    },
    {
      front: 'Was ist der Unterschied zwischen Bundesstaat und Einheitsstaat?',
      back: 'Im Bundesstaat (wie Deutschland) haben die Gliedstaaten (Länder) eigene Verfassungen, Parlamente und Regierungen mit echter Gesetzgebungskompetenz. Im Einheitsstaat (z. B. Frankreich) sind die Regionen der Zentralgewalt untergeordnet.',
    },
    {
      front: 'Welche Gerichte gehören zur Judikative auf Bundesebene?',
      back: 'Bundesverfassungsgericht, Bundesgerichtshof (ordentliche Gerichtsbarkeit), Bundesverwaltungsgericht, Bundesarbeitsgericht, Bundessozialgericht und Bundesfinanzhof.',
    },
    {
      front: 'Was ist die Aufgabe des Bundesverfassungsgerichts?',
      back: 'Das Bundesverfassungsgericht wacht über die Einhaltung des Grundgesetzes, entscheidet über Verfassungsbeschwerden, prüft die Verfassungsmäßigkeit von Gesetzen und löst Streitigkeiten zwischen Verfassungsorganen.',
    },
    {
      front: 'Was bedeutet Gewaltenverschränkung?',
      back: 'Obwohl die drei Gewalten getrennt sind, gibt es Verflechtungen: z. B. ernennt der Bundestag den Bundeskanzler (Exekutive), und die Regierung hat das Recht zur Gesetzesinitiative (Legislative). Diese Verschränkung sichert gegenseitige Kontrolle.',
    },
    {
      front: 'Welche Aufgaben haben die Bundesländer in der Exekutive?',
      back: 'Die Länder vollziehen in der Regel die Bundesgesetze als eigene Angelegenheit (Art. 83 GG). Sie verfügen über eigene Landesregierungen, Landesbehörden und die Landespolizei. Bildung, Polizei und Kultur sind Kernbereiche der Länderzuständigkeit.',
    },
    {
      front: 'Was sind Stadtstaaten in Deutschland?',
      back: 'Drei der 16 Bundesländer sind Stadtstaaten: Berlin, Hamburg und Bremen. In ihnen fallen Stadt- und Landesebene zusammen. Ihre Parlamente heißen Abgeordnetenhaus (Berlin) bzw. Bürgerschaft (Hamburg, Bremen).',
    },
    {
      front: 'Was versteht man unter der Gesetzgebungskompetenz der Länder?',
      back: 'Die Länder haben die Gesetzgebungskompetenz, soweit das Grundgesetz sie nicht dem Bund verliehen hat (Art. 70 GG). Typische Länderbereiche: Schulrecht, Polizeirecht, Kommunalrecht, Hochschulrecht.',
    },
  ],
  questions: [
    {
      type: 'mc',
      prompt: 'Welche Staatsgewalt übt die Polizei aus?',
      options: ['Exekutive', 'Legislative', 'Judikative', 'Föderative'],
      correct: [0],
      explanation: 'Die Polizei gehört zur vollziehenden Gewalt (Exekutive), die Gesetze und staatliche Anordnungen umsetzt.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Wer beschrieb die Gewaltenteilung erstmals systematisch in seinem Werk "Vom Geist der Gesetze"?',
      options: ['Jean-Jacques Rousseau', 'Immanuel Kant', 'Charles de Montesquieu', 'John Locke'],
      correct: [2],
      explanation: 'Charles de Montesquieu (1748) formulierte das klassische Modell der Dreiteilung in Legislative, Exekutive und Judikative, das die modernen Demokratien entscheidend beeinflusst hat.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welches Organ gehört zur Legislative auf Bundesebene?',
      options: ['Bundesregierung', 'Bundesverwaltungsgericht', 'Bundeskriminalamt', 'Bundesrat'],
      correct: [3],
      explanation: 'Der Bundesrat ist neben dem Bundestag Teil der bundesgesetzgebenden Organe (Legislative). Bundesregierung und BKA sind Exekutive, das Bundesverwaltungsgericht ist Judikative.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Wie viele Bundesländer hat die Bundesrepublik Deutschland?',
      options: ['13', '14', '15', '16'],
      correct: [3],
      explanation: 'Deutschland besteht aus 16 Bundesländern. Seit der Wiedervereinigung 1990 umfasst die Bundesrepublik die 11 westdeutschen Länder sowie die 5 neuen Länder (Brandenburg, Mecklenburg-Vorpommern, Sachsen, Sachsen-Anhalt, Thüringen) und Berlin.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist die Hauptaufgabe der Judikative?',
      options: [
        'Gesetze beschließen',
        'Recht sprechen und Gesetze auf ihre Rechtmäßigkeit prüfen',
        'Gesetze ausführen und die öffentliche Ordnung wahren',
        'Die Bundesregierung kontrollieren',
      ],
      correct: [1],
      explanation: 'Die Judikative (rechtsprechende Gewalt) wendet das geltende Recht in konkreten Fällen an und überprüft im Rahmen der Verfassungsgerichtsbarkeit die Gesetzmäßigkeit staatlichen Handelns.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welches Gericht ist das höchste Verfassungsgericht in Deutschland?',
      options: ['Bundesgerichtshof', 'Bundesverwaltungsgericht', 'Bundesverfassungsgericht', 'Oberlandesgericht'],
      correct: [2],
      explanation: 'Das Bundesverfassungsgericht in Karlsruhe ist das höchste deutsche Gericht und wacht über die Einhaltung des Grundgesetzes. Es ist kein Rechtsmittelgericht, sondern ein reines Verfassungsgericht.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was beschreibt das Subsidiaritätsprinzip?',
      options: [
        'Der Bund hat Vorrang vor den Ländern in allen Bereichen.',
        'Aufgaben sollen auf der niedrigsten geeigneten Ebene wahrgenommen werden.',
        'Kommunen dürfen keine eigenen Gesetze erlassen.',
        'Alle staatlichen Entscheidungen müssen zentral getroffen werden.',
      ],
      correct: [1],
      explanation: 'Das Subsidiaritätsprinzip besagt, dass übergeordnete Ebenen nur dann eingreifen sollen, wenn die untergeordnete Ebene eine Aufgabe nicht ausreichend erfüllen kann. Es ist Grundlage des föderalen Systems und des EU-Rechts.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welcher Artikel des Grundgesetzes garantiert die kommunale Selbstverwaltung?',
      options: ['Art. 20 GG', 'Art. 28 GG', 'Art. 79 GG', 'Art. 83 GG'],
      correct: [1],
      explanation: 'Art. 28 Abs. 2 GG garantiert den Gemeinden das Recht, alle Angelegenheiten der örtlichen Gemeinschaft in eigener Verantwortung zu regeln. Diese kommunale Selbstverwaltungsgarantie ist unveräußerlich.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welcher Bereich fällt in Deutschland in die ausschließliche Gesetzgebungskompetenz des Bundes?',
      options: ['Schulrecht', 'Polizeirecht', 'Verteidigung und Außenpolitik', 'Hochschulrecht'],
      correct: [2],
      explanation: 'Verteidigung und auswärtige Angelegenheiten gehören zur ausschließlichen Gesetzgebung des Bundes (Art. 73 GG). Schul-, Polizei- und Hochschulrecht liegen dagegen im Wesentlichen bei den Ländern.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welche Funktion hat der Bundesrat im deutschen Rechtssystem?',
      options: [
        'Er ist die zweite Kammer des Parlaments und vertritt die Bevölkerung direkt.',
        'Er vertritt die Interessen der 16 Bundesländer auf Bundesebene.',
        'Er ist das oberste Gericht für Verwaltungsstreitigkeiten.',
        'Er wählt den Bundespräsidenten allein.',
      ],
      correct: [1],
      explanation: 'Der Bundesrat ist das Organ, durch das die Länder an der Gesetzgebung und Verwaltung des Bundes mitwirken. Die Mitglieder sind nicht direkt gewählt, sondern Vertreter der Landesregierungen.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was versteht man unter konkurrierender Gesetzgebung?',
      options: [
        'Nur der Bund darf in diesem Bereich Gesetze erlassen.',
        'Nur die Länder dürfen in diesem Bereich Gesetze erlassen.',
        'Die Länder dürfen Gesetze erlassen, solange und soweit der Bund keine Regelung getroffen hat.',
        'Bund und Länder erlassen gemeinsam Gesetze in einem Ausschuss.',
      ],
      correct: [2],
      explanation: 'Bei der konkurrierenden Gesetzgebung (Art. 72 GG) haben die Länder die Befugnis zur Gesetzgebung, solange und soweit der Bund von seiner Gesetzgebungszuständigkeit keinen Gebrauch gemacht hat. Beispiele: Strafrecht, bürgerliches Recht, Arbeitsrecht.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welche der folgenden Städte ist KEIN Stadtstaat (Bundesland)?',
      options: ['Hamburg', 'Bremen', 'Berlin', 'München'],
      correct: [3],
      explanation: 'München ist die Hauptstadt des Freistaates Bayern, aber selbst kein Bundesland. Stadtstaaten, in denen Stadt und Land identisch sind, sind nur Hamburg, Bremen und Berlin.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet Gewaltenverschränkung?',
      options: [
        'Die drei Gewalten sind vollkommen voneinander getrennt und haben keinerlei Berührungspunkte.',
        'Es gibt trotz Trennung der Gewalten gegenseitige Einwirkungen und Kontrollen zwischen den Gewalten.',
        'Die Exekutive untersteht vollständig der Legislative.',
        'Nur die Judikative kann die anderen Gewalten kontrollieren.',
      ],
      correct: [1],
      explanation: 'Gewaltenverschränkung beschreibt die notwendigen Überschneidungen der Gewalten, z. B. das Recht der Regierung zur Gesetzesinitiative oder die Wahl des Bundeskanzlers durch den Bundestag. Diese Verflechtungen ermöglichen gegenseitige Kontrolle.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welches Gericht ist für Streitigkeiten im öffentlichen Recht (z. B. gegen Verwaltungsentscheidungen) auf Bundesebene zuständig?',
      options: ['Bundesgerichtshof', 'Bundesarbeitsgericht', 'Bundesverwaltungsgericht', 'Bundessozialgericht'],
      correct: [2],
      explanation: 'Das Bundesverwaltungsgericht ist die oberste Instanz der Verwaltungsgerichtsbarkeit. Es entscheidet in letzter Instanz über Streitigkeiten des öffentlichen Rechts, also z. B. Klagen gegen Behördenentscheidungen.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welche Aussage zur Gewaltenteilung im Grundgesetz ist korrekt?',
      options: [
        'Das Grundgesetz kennt keine ausdrückliche Gewaltenteilung.',
        'Die Gewaltenteilung ist in Art. 20 Abs. 2 GG verankert.',
        'Die Gewaltenteilung gilt nur für die Bundesebene, nicht für die Länder.',
        'Alle drei Gewalten sind dem Bundespräsidenten unterstellt.',
      ],
      correct: [1],
      explanation: 'Art. 20 Abs. 2 GG bestimmt, dass die Staatsgewalt vom Volke ausgeht und durch besondere Organe der Gesetzgebung, der vollziehenden Gewalt und der Rechtsprechung ausgeübt wird – die verfassungsrechtliche Verankerung der Gewaltenteilung.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Wer wählt den Bundeskanzler oder die Bundeskanzlerin?',
      options: ['Das gesamte Volk in einer Direktwahl', 'Der Bundespräsident allein', 'Der Bundestag', 'Der Bundesrat'],
      correct: [2],
      explanation: 'Der Bundeskanzler wird gemäß Art. 63 GG vom Bundestag auf Vorschlag des Bundespräsidenten gewählt. Dies ist ein Beispiel für die Gewaltenverschränkung: die Legislative wählt das Oberhaupt der Exekutive.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welchem Prinzip des Föderalismus entspricht es, wenn der Bund erst tätig wird, wenn die Länder eine Aufgabe nicht bewältigen können?',
      options: ['Zentralisierungsprinzip', 'Subsidiaritätsprinzip', 'Unitarismusprinzip', 'Konvergenzprinzip'],
      correct: [1],
      explanation: 'Das Subsidiaritätsprinzip fordert, dass höhere staatliche Ebenen nur dann eingreifen, wenn niedrigere Ebenen eine Aufgabe nicht hinreichend erfüllen können. Es schützt die Eigenständigkeit der Länder und Kommunen.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welche Organe bilden die Legislative auf Landesebene?',
      options: ['Landesregierung und Landesministerien', 'Landtage (bzw. Bürgerschaft/Abgeordnetenhaus)', 'Landgerichte und Oberlandesgerichte', 'Landratsämter und Kreistage'],
      correct: [1],
      explanation: 'Die gesetzgebende Gewalt auf Landesebene liegt bei den Landesparlamenten: in den Flächenländern heißen sie Landtage, in Hamburg und Bremen Bürgerschaft und in Berlin Abgeordnetenhaus.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist eine Verfassungsbeschwerde?',
      options: [
        'Eine Beschwerde an den Bundesrat gegen ein Bundesgesetz',
        'Ein Rechtsmittel, mit dem jede Person eine Verletzung ihrer Grundrechte durch staatliche Stellen beim Bundesverfassungsgericht rügen kann',
        'Eine Klage der Bundesregierung gegen ein Land',
        'Ein Antrag der Opposition gegen Regierungsentscheidungen',
      ],
      correct: [1],
      explanation: 'Die Verfassungsbeschwerde (Art. 93 Abs. 1 Nr. 4a GG) ermöglicht es jeder Person, eine Verletzung ihrer Grundrechte durch öffentliche Gewalt beim Bundesverfassungsgericht zu rügen – nach Ausschöpfung des Rechtsweges.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welcher Bereich ist typischerweise Ländersache in Deutschland?',
      options: ['Außenpolitik', 'Verteidigung', 'Schulrecht und Bildung', 'Zollrecht'],
      correct: [2],
      explanation: 'Bildung und Schulrecht sind klassische Bereiche der Länderkompetenz (Kulturhoheit der Länder). Außenpolitik, Verteidigung und Zollrecht hingegen sind Bundeskompetenzen.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist der Bundesgerichtshof (BGH)?',
      options: [
        'Das Verfassungsgericht des Bundes',
        'Das oberste Gericht der ordentlichen Gerichtsbarkeit (Zivil- und Strafsachen)',
        'Das oberste Verwaltungsgericht',
        'Das Gericht für Arbeitsstreitigkeiten auf Bundesebene',
      ],
      correct: [1],
      explanation: 'Der Bundesgerichtshof ist die oberste Instanz der ordentlichen Gerichtsbarkeit und entscheidet in Revisionssachen in Zivil- und Strafsachen. Sitz ist in Karlsruhe (Zivilsenate) und Leipzig (Strafsenate).',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Wie heißt das Organ, das die Bundesgesetze mehrheitlich beschließt?',
      options: ['Bundesrat', 'Bundestag', 'Bundesverfassungsgericht', 'Bundesregierung'],
      correct: [1],
      explanation: 'Der Bundestag ist das direkt vom Volk gewählte Parlament und beschließt als Hauptorgan der Legislative die Bundesgesetze. Der Bundesrat hat bei vielen Gesetzen ein Mitwirkungsrecht.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet es, dass Deutschland ein Bundesstaat ist?',
      options: [
        'Alle Gesetze werden zentral vom Bund erlassen.',
        'Die Länder haben keine eigene Regierung.',
        'Die Staatsgewalt ist auf Bund und Länder verteilt, die jeweils eigene Verfassungen und Kompetenzen haben.',
        'Die Kommunen sind direkt dem Bund unterstellt.',
      ],
      correct: [2],
      explanation: 'Als Bundesstaat verfügt Deutschland über eine vertikale Gewaltenteilung: Bund und Länder haben jeweils eigene Verfassungen, Parlamente, Regierungen und Gesetzgebungskompetenzen. Dies unterscheidet den Bundesstaat vom Einheitsstaat.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welcher Artikel des Grundgesetzes legt fest, dass die Länder die Bundesgesetze grundsätzlich als eigene Angelegenheit ausführen?',
      options: ['Art. 28 GG', 'Art. 70 GG', 'Art. 83 GG', 'Art. 93 GG'],
      correct: [2],
      explanation: 'Art. 83 GG bestimmt: "Die Länder führen die Bundesgesetze als eigene Angelegenheit aus, soweit dieses Grundgesetz nichts anderes bestimmt oder zulässt." Dies ist Ausdruck des föderalen Prinzips der Verwaltungskompetenz der Länder.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Welche der folgenden Aussagen zu den Stadtstaaten ist korrekt?',
      options: [
        'Es gibt vier Stadtstaaten: Berlin, Hamburg, Bremen und Frankfurt.',
        'Stadtstaaten haben kein eigenes Landesparlament.',
        'In Stadtstaaten fallen Stadt- und Landesebene zusammen; es gibt drei davon.',
        'Stadtstaaten unterliegen der direkten Bundesverwaltung.',
      ],
      correct: [2],
      explanation: 'Deutschland hat genau drei Stadtstaaten: Berlin, Hamburg und Bremen. In ihnen sind Stadt und Land identisch. Sie haben eigene Parlamente (Abgeordnetenhaus bzw. Bürgerschaft) und Senatsregierungen.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was ist der Unterschied zwischen zustimmungspflichtigen und einspruchspflichtigen Bundesgesetzen bezüglich des Bundesrates?',
      options: [
        'Bei zustimmungspflichtigen Gesetzen kann der Bundesrat nur Einspruch erheben, der überstimmt werden kann; bei einspruchspflichtigen muss er zustimmen.',
        'Bei zustimmungspflichtigen Gesetzen muss der Bundesrat ausdrücklich zustimmen; bei einspruchspflichtigen kann der Bundestag den Einspruch des Bundesrates überstimmen.',
        'Es gibt keinen Unterschied – der Bundesrat hat in beiden Fällen ein absolutes Vetorecht.',
        'Zustimmungspflichtige Gesetze betreffen nur die Außenpolitik.',
      ],
      correct: [1],
      explanation: 'Bei zustimmungspflichtigen Gesetzen (z. B. solchen, die Länderinteressen berühren) ist die ausdrückliche Zustimmung des Bundesrates notwendig. Bei einspruchspflichtigen Gesetzen kann der Bundestag den Einspruch des Bundesrates mit der entsprechenden Mehrheit zurückweisen.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Welche Behörde ist das zentrale Strafverfolgungsorgan auf Bundesebene?',
      options: ['Landespolizei', 'Bundeskriminalamt (BKA)', 'Bundesverfassungsgericht', 'Bundeswehr'],
      correct: [1],
      explanation: 'Das Bundeskriminalamt (BKA) ist die Zentralstelle für das deutsche Polizeiwesen auf Bundesebene und gehört zur Exekutive. Es koordiniert die Strafverfolgung bei schweren Delikten mit länderübergreifender oder internationaler Bedeutung.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was versteht man unter der Kulturhoheit der Länder?',
      options: [
        'Der Bund finanziert alle Kultureinrichtungen der Länder.',
        'Die Länder haben die Gesetzgebungskompetenz und Verwaltungshoheit im Bereich Kultur, Bildung und Wissenschaft.',
        'Der Bundesrat beschließt bundeseinheitliche Lehrpläne.',
        'Kulturelle Aufgaben obliegen ausschließlich den Kommunen.',
      ],
      correct: [1],
      explanation: 'Die Kulturhoheit der Länder ist ein Kernprinzip des deutschen Föderalismus: Die Länder sind für Schule, Hochschule, Kultur und Rundfunk zuständig. Deshalb gibt es in Deutschland unterschiedliche Schulsysteme je nach Bundesland.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was ist das Wesentliche am Prinzip der Checks and Balances?',
      options: [
        'Alle drei Gewalten sind strikt voneinander getrennt und haben keinen Einfluss aufeinander.',
        'Die Exekutive kontrolliert sowohl Legislative als auch Judikative.',
        'Jede Gewalt kann die anderen in bestimmtem Umfang kontrollieren und hemmen, um Machtmissbrauch zu verhindern.',
        'Das Volk kontrolliert direkt alle drei Gewalten durch Volksabstimmungen.',
      ],
      correct: [2],
      explanation: 'Checks and Balances bezeichnet das System gegenseitiger Kontrolle der Staatsgewalten. Beispiele: Das Bundesverfassungsgericht (Judikative) prüft Gesetze der Legislative; der Bundestag (Legislative) kann der Regierung (Exekutive) das Vertrauen entziehen.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welche Ebene der staatlichen Gliederung ist in Deutschland für die Bauleitplanung (Bebauungsplan) zuständig?',
      options: ['Bundesebene', 'Landesebene', 'Kommunale Ebene (Gemeinden)', 'Europäische Union'],
      correct: [2],
      explanation: 'Die Bauleitplanung, also die Erstellung von Flächennutzungsplänen und Bebauungsplänen, ist eine klassische Aufgabe der kommunalen Selbstverwaltung. Die Gemeinden entscheiden im Rahmen der Gesetze eigenverantwortlich über die Bodennutzung in ihrem Gebiet.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welches Prinzip besagt, dass die Staatsgewalt an Recht und Gesetz gebunden ist?',
      options: ['Demokratieprinzip', 'Rechtsstaatsprinzip', 'Föderalismusgebot', 'Subsidiaritätsprinzip'],
      correct: [1],
      explanation: 'Das Rechtsstaatsprinzip (Art. 20 Abs. 3 GG) verpflichtet Legislative, Exekutive und Judikative an die verfassungsmäßige Ordnung sowie an Gesetz und Recht. Es ist eng mit der Gewaltenteilung verknüpft.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Wie werden die Mitglieder des Bundesrates bestimmt?',
      options: [
        'Sie werden direkt von den Bürgerinnen und Bürgern der Länder gewählt.',
        'Sie werden vom Bundestag ernannt.',
        'Sie sind Mitglieder der jeweiligen Landesregierungen und werden von diesen entsandt.',
        'Sie werden vom Bundespräsidenten berufen.',
      ],
      correct: [2],
      explanation: 'Die Mitglieder des Bundesrates sind Mitglieder der Landesregierungen (Ministerpräsident:innen und Minister:innen). Sie werden nicht gewählt, sondern von den Landesregierungen entsandt und abberufen.',
      difficulty: 2,
    },
    {
      type: 'truefalse',
      prompt: 'Der Bundestag ist das direkt vom Volk gewählte Parlament auf Bundesebene und gehört zur Legislative.',
      options: ['Wahr', 'Falsch'],
      correct: [0],
      explanation: 'Richtig. Der Bundestag wird alle vier Jahre direkt vom Volk gewählt und ist das zentrale Gesetzgebungsorgan (Legislative) auf Bundesebene. Er wählt zudem den Bundeskanzler und kontrolliert die Regierung.',
      difficulty: 1,
    },
    {
      type: 'truefalse',
      prompt: 'Das Bundesverfassungsgericht in Berlin ist das höchste deutsche Gericht.',
      options: ['Wahr', 'Falsch'],
      correct: [1],
      explanation: 'Falsch. Das Bundesverfassungsgericht hat seinen Sitz in Karlsruhe, nicht in Berlin. Es ist zwar das höchste Verfassungsgericht, steht aber nicht über den anderen obersten Bundesgerichten im Sinne einer Instanzenhierarchie.',
      difficulty: 2,
    },
    {
      type: 'truefalse',
      prompt: 'Im deutschen Föderalismus haben die Länder eigene Verfassungen und Gesetzgebungskompetenzen.',
      options: ['Wahr', 'Falsch'],
      correct: [0],
      explanation: 'Richtig. Jedes der 16 Bundesländer hat eine eigene Landesverfassung, ein eigenes Parlament und eigene Gesetzgebungskompetenzen, insbesondere in den Bereichen, die das Grundgesetz nicht dem Bund vorbehält.',
      difficulty: 1,
    },
  ],
};

export default topic;
