import type { RawTopic } from '../types';

const topic: RawTopic = {
  slug: 'grammatik',
  title: 'Grammatik',
  description: 'Die vier Fälle und die Wortarten.',
  flashcards: [
    {
      front: 'Was sind die vier grammatischen Fälle im Deutschen?',
      back: 'Nominativ, Genitiv, Dativ, Akkusativ.',
    },
    {
      front: 'Mit welcher Frage erkennt man den Nominativ?',
      back: 'Wer oder was? – Der Nominativ bezeichnet das Subjekt des Satzes.',
    },
    {
      front: 'Mit welcher Frage erkennt man den Genitiv?',
      back: 'Wessen? – Der Genitiv drückt Zugehörigkeit oder Besitz aus.',
    },
    {
      front: 'Mit welcher Frage erkennt man den Dativ?',
      back: 'Wem? – Der Dativ bezeichnet häufig das indirekte Objekt (Empfänger).',
    },
    {
      front: 'Mit welcher Frage erkennt man den Akkusativ?',
      back: 'Wen oder was? – Der Akkusativ bezeichnet das direkte Objekt.',
    },
    {
      front: 'Wie lautet die Deklination des bestimmten Artikels "der" (maskulin) in allen vier Fällen?',
      back: 'Nominativ: der – Genitiv: des – Dativ: dem – Akkusativ: den.',
    },
    {
      front: 'Wie lautet die Deklination des bestimmten Artikels "die" (feminin) in allen vier Fällen?',
      back: 'Nominativ: die – Genitiv: der – Dativ: der – Akkusativ: die.',
    },
    {
      front: 'Wie lautet die Deklination des bestimmten Artikels "das" (neutrum) in allen vier Fällen?',
      back: 'Nominativ: das – Genitiv: des – Dativ: dem – Akkusativ: das.',
    },
    {
      front: 'Was ist ein Nomen (Substantiv)?',
      back: 'Ein Nomen bezeichnet Personen, Dinge, Tiere oder abstrakte Begriffe. Es wird großgeschrieben und hat ein Genus (maskulin, feminin, neutrum).',
    },
    {
      front: 'Was ist ein Verb?',
      back: 'Ein Verb drückt eine Handlung, einen Vorgang oder einen Zustand aus (z. B. laufen, sein, werden). Es ist das Prädikat im Satz.',
    },
    {
      front: 'Was ist ein Adjektiv?',
      back: 'Ein Adjektiv beschreibt oder charakterisiert ein Nomen (z. B. schnell, groß, schön). Es kann gesteigert werden: Positiv – Komparativ – Superlativ.',
    },
    {
      front: 'Was ist ein Adverb?',
      back: 'Ein Adverb beschreibt näheres zu Verben, Adjektiven oder anderen Adverbien (z. B. sehr, dort, gestern). Es wird nicht dekliniert.',
    },
    {
      front: 'Was ist eine Präposition?',
      back: 'Eine Präposition steht vor einem Nomen oder Pronomen und gibt das Verhältnis zu anderen Satzteilen an (z. B. in, auf, mit, durch). Präpositionen regieren einen bestimmten Kasus.',
    },
    {
      front: 'Was ist eine Konjunktion?',
      back: 'Eine Konjunktion verbindet Wörter, Satzglieder oder Sätze (z. B. und, aber, weil, obwohl). Man unterscheidet koordinierende und subordinierende Konjunktionen.',
    },
    {
      front: 'Was ist ein Pronomen?',
      back: 'Ein Pronomen vertritt oder begleitet ein Nomen (z. B. er, sie, es, dieser, mein). Es passt sich in Kasus, Numerus und Genus an das Bezugswort an.',
    },
    {
      front: 'Wie werden Adjektive gesteigert? Nenne die drei Stufen am Beispiel "schnell".',
      back: 'Positiv: schnell – Komparativ: schneller – Superlativ: am schnellsten (schnellste).',
    },
    {
      front: 'Was ist ein Numerale?',
      back: 'Ein Numerale ist ein Zahlwort (z. B. eins, drei, zwanzig). Es gibt Kardinalzahlen (ein, zwei …) und Ordinalzahlen (erste, zweite …).',
    },
    {
      front: 'Was ist eine Interjektion?',
      back: 'Eine Interjektion ist ein Ausrufewort, das Gefühle oder Reaktionen ausdrückt (z. B. oh, ach, hurra, autsch). Sie steht meist allein und bildet kein Satzglied.',
    },
    {
      front: 'Was versteht man unter Deklination?',
      back: 'Deklination ist die Beugung von Nomen, Pronomen, Artikeln und Adjektiven nach Kasus, Numerus und Genus.',
    },
    {
      front: 'Wie lautet der Genitiv Singular von "das Kind"?',
      back: 'des Kindes – Neutrum, Genitiv Singular mit der Endung -(e)s.',
    },
  ],
  questions: [
    {
      type: 'mc',
      prompt: 'In welchem Fall (Kasus) steht das Nomen in folgendem Satz? "Der Lehrer erklärt den Schülern die Aufgabe." – "den Schülern"',
      options: ['Nominativ', 'Genitiv', 'Dativ', 'Akkusativ'],
      correct: [2],
      explanation: '"Den Schülern" beantwortet die Frage "Wem?" und steht daher im Dativ.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welche Frage stellt man, um den Akkusativ zu ermitteln?',
      options: ['Wer oder was?', 'Wessen?', 'Wem?', 'Wen oder was?'],
      correct: [3],
      explanation: 'Der Akkusativ wird mit "Wen oder was?" erfragt und bezeichnet meist das direkte Objekt.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welche Wortart ist das Wort "schnell" im Satz "Er läuft schnell"?',
      options: ['Adjektiv', 'Adverb', 'Verb', 'Nomen'],
      correct: [1],
      explanation: 'Im Satz "Er läuft schnell" bezieht sich "schnell" auf das Verb "läuft" und wird daher als Adverb verwendet.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Wie lautet der Genitiv Singular von "die Frau"?',
      options: ['der Frau', 'die Frau', 'den Frauen', 'dem Frauen'],
      correct: [0],
      explanation: 'Femininum im Genitiv Singular: "der Frau" (keine Endung am Nomen, Artikeländerung von "die" zu "der").',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welche Wortart ist "weil" im Satz "Er bleibt zu Hause, weil er krank ist"?',
      options: ['Präposition', 'Adverb', 'Konjunktion', 'Pronomen'],
      correct: [2],
      explanation: '"Weil" ist eine subordinierende Konjunktion, die einen Nebensatz einleitet.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'In welchem Fall steht "des Lehrers" im Satz "Das Buch des Lehrers liegt auf dem Tisch"?',
      options: ['Nominativ', 'Genitiv', 'Dativ', 'Akkusativ'],
      correct: [1],
      explanation: '"Des Lehrers" beantwortet die Frage "Wessen Buch?" und steht im Genitiv.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welche Steigerungsform ist korrekt? Positiv: "gut"',
      options: ['gut – guter – am gutsten', 'gut – besser – am besten', 'gut – mehr gut – am meisten gut', 'gut – güter – am gütsten'],
      correct: [1],
      explanation: '"Gut" hat eine unregelmäßige Steigerung: Positiv gut – Komparativ besser – Superlativ am besten.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welche Wortart ist "drei" im Satz "Ich habe drei Äpfel gekauft"?',
      options: ['Adjektiv', 'Adverb', 'Numerale', 'Pronomen'],
      correct: [2],
      explanation: '"Drei" ist ein Kardinalzahlwort und gehört zur Wortart Numerale.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welches Satzglied ist "Maria" im Satz "Maria liest ein Buch"?',
      options: ['Prädikat', 'Objekt', 'Subjekt', 'Adverbiale'],
      correct: [2],
      explanation: '"Maria" steht im Nominativ und beantwortet die Frage "Wer liest?". Es ist das Subjekt.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welche Präposition verlangt immer den Dativ?',
      options: ['durch', 'für', 'mit', 'ohne'],
      correct: [2],
      explanation: '"Mit" ist eine reine Dativpräposition. "Durch", "für" und "ohne" regieren den Akkusativ.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Wie lautet der Akkusativ Singular (maskulin) des bestimmten Artikels?',
      options: ['der', 'die', 'das', 'den'],
      correct: [3],
      explanation: 'Im Akkusativ Singular maskulin lautet der bestimmte Artikel "den".',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welches Wort ist ein Pronomen im Satz "Er hat ihr das Buch gegeben"?',
      options: ['hat', 'gegeben', 'ihr', 'Buch'],
      correct: [2],
      explanation: '"Ihr" ist ein Personalpronomen im Dativ (3. Person Singular Feminin) und vertritt eine Person.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'In welchem Fall steht "dem Kind" im Satz "Die Mutter gibt dem Kind die Hand"?',
      options: ['Nominativ', 'Genitiv', 'Dativ', 'Akkusativ'],
      correct: [2],
      explanation: '"Dem Kind" beantwortet "Wem gibt die Mutter die Hand?" – das ist der Dativ.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welche Wortart ist "auf" im Satz "Das Buch liegt auf dem Tisch"?',
      options: ['Konjunktion', 'Adverb', 'Präposition', 'Adjektiv'],
      correct: [2],
      explanation: '"Auf" steht vor dem Nomen "Tisch" und gibt ein räumliches Verhältnis an – es ist eine Präposition.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welches ist der korrekte Komparativ von "hoch"?',
      options: ['hocher', 'höcher', 'höher', 'hocherer'],
      correct: [2],
      explanation: '"Hoch" bildet den Komparativ unregelmäßig: höher (mit Umlaut und ohne Stamm-Erweiterung "ch").',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welches Satzglied ist "ein Buch" im Satz "Maria liest ein Buch"?',
      options: ['Subjekt', 'Prädikat', 'Akkusativobjekt', 'Dativobjekt'],
      correct: [2],
      explanation: '"Ein Buch" beantwortet "Wen oder was liest Maria?" und steht im Akkusativ. Es ist das Akkusativobjekt.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welche Wortart ist "sehr" im Satz "Das Wetter ist sehr schön"?',
      options: ['Adjektiv', 'Adverb', 'Konjunktion', 'Numerale'],
      correct: [1],
      explanation: '"Sehr" verstärkt das Adjektiv "schön" und ist ein Adverb (Gradpartikel).',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Wie lautet der Superlativ von "klein"?',
      options: ['am kleinen', 'am kleinsten', 'am kleineren', 'am wenigsten klein'],
      correct: [1],
      explanation: 'Der Superlativ von "klein" lautet "am kleinsten" (Positiv klein – Komparativ kleiner – Superlativ am kleinsten).',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'In welchem Fall steht das unterstrichene Wort? "Wir gedenken [der Opfer]."',
      options: ['Nominativ', 'Genitiv', 'Dativ', 'Akkusativ'],
      correct: [1],
      explanation: '"Gedenken" regiert den Genitiv. "Der Opfer" beantwortet "Wessen gedenken wir?" – Genitiv Plural.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Welche Wortart ist "dieser" im Satz "Dieser Mann ist mein Vater"?',
      options: ['Adjektiv', 'Pronomen (Demonstrativpronomen)', 'Nomen', 'Adverb'],
      correct: [1],
      explanation: '"Dieser" ist ein Demonstrativpronomen, das auf eine bestimmte Person oder Sache hinweist.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welche Konjunktion leitet einen Kausalsatz ein?',
      options: ['obwohl', 'damit', 'weil', 'wenn'],
      correct: [2],
      explanation: '"Weil" leitet einen Kausalsatz (Begründung) ein. "Obwohl" = konzessiv, "damit" = final, "wenn" = konditional/temporal.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'In welchem Fall steht "den Hund" im Satz "Das Kind streichelt den Hund"?',
      options: ['Nominativ', 'Genitiv', 'Dativ', 'Akkusativ'],
      correct: [3],
      explanation: '"Den Hund" beantwortet "Wen oder was streichelt das Kind?" – Akkusativ Singular maskulin.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welcher Satz enthält einen Genitiv?',
      options: [
        'Der Hund läuft schnell.',
        'Das Haus des Nachbarn ist groß.',
        'Ich gebe dem Kind ein Buch.',
        'Sie sieht den Mann.',
      ],
      correct: [1],
      explanation: '"Des Nachbarn" ist Genitiv – er zeigt Zugehörigkeit an (Wessen Haus?).',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was ist ein Interjektion? Welches Wort ist eine Interjektion?',
      options: ['laufen', 'schön', 'hurra', 'wegen'],
      correct: [2],
      explanation: '"Hurra" ist eine Interjektion – ein Ausrufewort, das eine Emotion oder Reaktion ausdrückt.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welche Wortart ist "mein" im Satz "Das ist mein Buch"?',
      options: ['Adjektiv', 'Pronomen (Possessivpronomen)', 'Artikel', 'Adverb'],
      correct: [1],
      explanation: '"Mein" ist ein Possessivpronomen (auch Possessivartikel), das Besitz ausdrückt.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Wie lautet der Dativ Plural von "das Kind" mit bestimmtem Artikel?',
      options: ['die Kinder', 'der Kinder', 'den Kindern', 'dem Kinder'],
      correct: [2],
      explanation: 'Dativ Plural: "den Kindern" – im Dativ Plural erhalten Nomen die Endung -n (sofern nicht bereits vorhanden).',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was ist das Prädikat im Satz "Die Schüler lösen die Aufgabe"?',
      options: ['Die Schüler', 'lösen', 'die Aufgabe', 'Schüler'],
      correct: [1],
      explanation: 'Das Prädikat ist die finite Verbform. Hier: "lösen".',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welche Endung erhält ein maskulines Nomen im Genitiv Singular in der Regel?',
      options: ['-e', '-en', '-(e)s', '-er'],
      correct: [2],
      explanation: 'Maskuline und neutrale Nomen erhalten im Genitiv Singular die Endung -(e)s, z. B. "des Mannes", "des Kindes".',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welche Präposition regiert ausschließlich den Akkusativ?',
      options: ['von', 'bei', 'durch', 'nach'],
      correct: [2],
      explanation: '"Durch" regiert immer den Akkusativ. "Von", "bei" und "nach" regieren immer den Dativ.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welcher Satz enthält ein Dativobjekt?',
      options: [
        'Er kauft ein Auto.',
        'Sie hilft dem Kollegen.',
        'Wir sehen das Haus.',
        'Der Hund bellt laut.',
      ],
      correct: [1],
      explanation: '"Dem Kollegen" steht im Dativ (Wem hilft sie?). Das Verb "helfen" regiert den Dativ.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welche Wortart ist "und" im Satz "Peter und Maria gehen ins Kino"?',
      options: ['Präposition', 'Adverb', 'Konjunktion', 'Pronomen'],
      correct: [2],
      explanation: '"Und" ist eine koordinierende Konjunktion, die gleichrangige Satzglieder verbindet.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist die Grundform (Infinitiv) des Verbs in "Sie sind gegangen"?',
      options: ['sein', 'gehen', 'gegangen', 'sind'],
      correct: [1],
      explanation: 'Das Vollverb ist "gegangen" – sein Infinitiv lautet "gehen". "Sind" ist das Hilfsverb.',
      difficulty: 2,
    },
    {
      type: 'truefalse',
      prompt: 'Das Subjekt eines Satzes steht immer im Nominativ.',
      options: ['Richtig', 'Falsch'],
      correct: [0],
      explanation: 'Ja, das Subjekt steht stets im Nominativ – es beantwortet die Frage "Wer oder was?".',
      difficulty: 1,
    },
    {
      type: 'truefalse',
      prompt: 'Adjektive können nicht gesteigert werden, wenn sie bereits eine absolute Eigenschaft ausdrücken (z. B. "tot", "schwanger").',
      options: ['Richtig', 'Falsch'],
      correct: [0],
      explanation: 'Sogenannte absolute Adjektive wie "tot" oder "einzigartig" lassen sich semantisch nicht steigern, da sie keine Grade zulassen.',
      difficulty: 3,
    },
    {
      type: 'truefalse',
      prompt: 'Die Präposition "wegen" regiert den Akkusativ.',
      options: ['Richtig', 'Falsch'],
      correct: [1],
      explanation: '"Wegen" regiert den Genitiv (wegen des Regens). Im Umgangssprachlichen wird oft fälschlich der Dativ verwendet.',
      difficulty: 3,
    },
    {
      type: 'truefalse',
      prompt: 'Nomen werden im Deutschen immer großgeschrieben.',
      options: ['Richtig', 'Falsch'],
      correct: [0],
      explanation: 'Im Deutschen werden alle Nomen (Substantive) großgeschrieben – das ist ein grundlegendes Rechtschreibprinzip.',
      difficulty: 1,
    },
    {
      type: 'fill',
      prompt: 'Ergänzen Sie: Der Kasus, der mit "Wessen?" erfragt wird, heißt ___.',
      correct: ['Genitiv'],
      explanation: 'Der Genitiv wird mit der Frage "Wessen?" ermittelt und drückt Zugehörigkeit aus.',
      difficulty: 1,
    },
    {
      type: 'fill',
      prompt: 'Ergänzen Sie: Das Verb "geben" regiert zwei Objekte – ein ___ (Wem?) und ein ___ (Wen/Was?).',
      correct: ['Dativobjekt', 'Akkusativobjekt'],
      explanation: '"Geben" hat ein indirektes Objekt im Dativ (Empfänger) und ein direktes Objekt im Akkusativ (Sache).',
      difficulty: 2,
    },
    {
      type: 'fill',
      prompt: 'Wie lautet der Superlativ von "groß"? Antwort: am ___.',
      correct: ['größten'],
      explanation: '"Groß" steigert sich unregelmäßig mit Umlaut: groß – größer – am größten.',
      difficulty: 2,
    },
  ],
};

export default topic;
