import type { RawTopic } from '../types';

const topic: RawTopic = {
  slug: 'grundgesetz',
  title: 'Grundgesetz & Grundrechte',
  description: 'Aufbau des Grundgesetzes und die wichtigsten Grundrechte.',
  flashcards: [
    {
      front: 'Wann trat das Grundgesetz in Kraft?',
      back: 'Am 23. Mai 1949.',
    },
    {
      front: 'Was besagt Artikel 1 Abs. 1 GG?',
      back: '"Die Würde des Menschen ist unantastbar. Sie zu achten und zu schützen ist Verpflichtung aller staatlichen Gewalt."',
    },
    {
      front: 'Was regelt Artikel 2 GG?',
      back: 'Das Recht auf freie Entfaltung der Persönlichkeit sowie das Recht auf Leben und körperliche Unversehrtheit. Die Freiheit der Person ist unverletzlich.',
    },
    {
      front: 'Was regelt Artikel 3 GG?',
      back: 'Die Gleichheit vor dem Gesetz. Abs. 2: Männer und Frauen sind gleichberechtigt. Abs. 3: Niemand darf wegen Geschlecht, Abstammung, Rasse, Sprache, Heimat, Herkunft, Glauben oder politischer Anschauung benachteiligt oder bevorzugt werden.',
    },
    {
      front: 'Was regelt Artikel 4 GG?',
      back: 'Die Freiheit des Glaubens, des Gewissens und die Freiheit des religiösen und weltanschaulichen Bekenntnisses. Die ungestörte Religionsausübung wird gewährleistet.',
    },
    {
      front: 'Was regelt Artikel 5 GG?',
      back: 'Das Recht, seine Meinung in Wort, Schrift und Bild frei zu äußern und zu verbreiten (Meinungsfreiheit) sowie die Pressefreiheit und die Freiheit der Berichterstattung durch Rundfunk und Film.',
    },
    {
      front: 'Was regelt Artikel 8 GG?',
      back: 'Die Versammlungsfreiheit: Alle Deutschen haben das Recht, sich ohne Anmeldung oder Erlaubnis friedlich und ohne Waffen zu versammeln.',
    },
    {
      front: 'Was sind die vier Staatsprinzipien des Artikels 20 GG?',
      back: 'Die Bundesrepublik Deutschland ist (1) ein demokratischer und (2) sozialer (3) Bundesstaat. Dazu gilt das Prinzip des (4) Rechtsstaates. Diese Prinzipien sind durch die Ewigkeitsklausel geschützt.',
    },
    {
      front: 'Was regelt Artikel 20 Abs. 2 GG zur Gewaltenteilung?',
      back: 'Die Staatsgewalt wird durch besondere Organe der Gesetzgebung (Legislative), der vollziehenden Gewalt (Exekutive) und der Rechtsprechung (Judikative) ausgeübt.',
    },
    {
      front: 'Was besagt das Widerstandsrecht in Artikel 20 Abs. 4 GG?',
      back: 'Gegen jeden, der es unternimmt, die verfassungsmäßige Ordnung zu beseitigen, haben alle Deutschen das Recht zum Widerstand, wenn andere Abhilfe nicht möglich ist.',
    },
    {
      front: 'Was ist die Ewigkeitsklausel und wo steht sie?',
      back: 'In Artikel 79 Abs. 3 GG. Sie schützt bestimmte Grundsätze (insbes. Art. 1 und Art. 20 GG) vor Verfassungsänderungen – diese Artikel dürfen niemals geändert werden.',
    },
    {
      front: 'Was sind Menschenrechte im Sinne des GG?',
      back: 'Grundrechte, die jedem Menschen zustehen, unabhängig von der Staatsangehörigkeit – z. B. die Menschenwürde (Art. 1), Glaubensfreiheit (Art. 4) und das Recht auf Leben (Art. 2 Abs. 2).',
    },
    {
      front: 'Was sind Deutschengrundrechte (Bürgerrechte) im GG?',
      back: 'Grundrechte, die nur deutschen Staatsangehörigen zustehen, z. B. Versammlungsfreiheit (Art. 8), Vereinigungsfreiheit (Art. 9), Freizügigkeit (Art. 11) und Berufsfreiheit (Art. 12).',
    },
    {
      front: 'Welche Artikel des GG enthalten die Grundrechte?',
      back: 'Die Grundrechte sind in den Artikeln 1 bis 19 des Grundgesetzes geregelt.',
    },
    {
      front: 'Was besagt Artikel 1 Abs. 3 GG?',
      back: 'Die Grundrechte binden Gesetzgebung, vollziehende Gewalt und Rechtsprechung als unmittelbar geltendes Recht.',
    },
    {
      front: 'Was ist die Wesensgehaltsgarantie (Art. 19 Abs. 2 GG)?',
      back: 'In keinem Fall darf ein Grundrecht in seinem Wesensgehalt angetastet werden – selbst wenn ein Gesetz ein Grundrecht einschränkt, muss sein Kernbereich erhalten bleiben.',
    },
    {
      front: 'Was regelt Artikel 19 Abs. 4 GG?',
      back: 'Der Rechtswegarantie: Wird jemand durch die öffentliche Gewalt in seinen Rechten verletzt, steht ihm der Rechtsweg offen.',
    },
    {
      front: 'Was regelt Artikel 14 GG?',
      back: 'Das Eigentumsgrundrecht: Eigentum und Erbrecht werden gewährleistet. Eigentum verpflichtet – sein Gebrauch soll zugleich dem Wohle der Allgemeinheit dienen. Eine Enteignung ist nur zum Wohle der Allgemeinheit und gegen Entschädigung zulässig.',
    },
    {
      front: 'Was regelt Artikel 9 GG?',
      back: 'Die Vereinigungsfreiheit: Alle Deutschen haben das Recht, Vereine und Gesellschaften zu bilden. Vereinigungen, deren Zwecke oder Tätigkeit den Strafgesetzen zuwiderlaufen, sind verboten.',
    },
    {
      front: 'Was regelt Artikel 16a GG?',
      back: 'Das Asylrecht: Politisch Verfolgte genießen Asylrecht. Das Grundrecht gilt jedoch nicht, wenn Personen aus einem sicheren Drittstaat oder einem EU-Mitgliedstaat einreisen.',
    },
  ],
  questions: [
    {
      type: 'mc',
      prompt: 'Wann trat das Grundgesetz der Bundesrepublik Deutschland in Kraft?',
      options: [
        '8. Mai 1945',
        '23. Mai 1949',
        '3. Oktober 1990',
        '1. Januar 1871',
      ],
      correct: [1],
      explanation: 'Das Grundgesetz trat am 23. Mai 1949 in Kraft. Dieser Tag gilt als Gründungstag der Bundesrepublik Deutschland.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was besagt Artikel 1 Abs. 1 GG?',
      options: [
        'Alle Menschen sind vor dem Gesetz gleich.',
        'Jeder hat das Recht auf freie Meinungsäußerung.',
        'Die Würde des Menschen ist unantastbar.',
        'Deutschland ist ein demokratischer Rechtsstaat.',
      ],
      correct: [2],
      explanation: 'Art. 1 Abs. 1 GG lautet: „Die Würde des Menschen ist unantastbar. Sie zu achten und zu schützen ist Verpflichtung aller staatlichen Gewalt."',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welcher Artikel des Grundgesetzes garantiert die Versammlungsfreiheit?',
      options: [
        'Artikel 4 GG',
        'Artikel 5 GG',
        'Artikel 9 GG',
        'Artikel 8 GG',
      ],
      correct: [3],
      explanation: 'Art. 8 GG garantiert die Versammlungsfreiheit: Alle Deutschen haben das Recht, sich friedlich und ohne Waffen zu versammeln.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welcher Artikel des GG schützt die Meinungsfreiheit und Pressefreiheit?',
      options: [
        'Artikel 3 GG',
        'Artikel 5 GG',
        'Artikel 8 GG',
        'Artikel 12 GG',
      ],
      correct: [1],
      explanation: 'Art. 5 GG schützt die Meinungsfreiheit, Pressefreiheit sowie die Freiheit der Berichterstattung durch Rundfunk und Film.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was regelt Artikel 3 Abs. 1 GG?',
      options: [
        'Das Recht auf körperliche Unversehrtheit',
        'Die Gleichheit aller Menschen vor dem Gesetz',
        'Die Glaubens- und Gewissensfreiheit',
        'Das Verbot von Sondergerichten',
      ],
      correct: [1],
      explanation: 'Art. 3 Abs. 1 GG lautet: „Alle Menschen sind vor dem Gesetz gleich." Abs. 2 ergänzt die Gleichberechtigung von Mann und Frau.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'In welchem Artikel des GG ist das Widerstandsrecht verankert?',
      options: [
        'Artikel 20 Abs. 2 GG',
        'Artikel 20 Abs. 4 GG',
        'Artikel 79 Abs. 3 GG',
        'Artikel 19 Abs. 4 GG',
      ],
      correct: [1],
      explanation: 'Das Widerstandsrecht steht in Art. 20 Abs. 4 GG. Es gibt Deutschen das Recht zum Widerstand gegen jeden, der die verfassungsmäßige Ordnung beseitigen will, wenn andere Abhilfe nicht möglich ist.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Wie viele Staatsprinzipien enthält Artikel 20 GG?',
      options: [
        'Zwei (Demokratie und Bundesstaat)',
        'Drei (Demokratie, Rechtsstaat, Sozialstaat)',
        'Vier (Demokratie, Sozialstaat, Bundesstaat, Rechtsstaat)',
        'Fünf (inkl. Neutralitätsprinzip)',
      ],
      correct: [2],
      explanation: 'Art. 20 GG verankert vier Staatsprinzipien: Deutschland ist ein demokratischer und sozialer Bundesstaat. Hinzu kommt das Rechtsstaatsprinzip.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was ist die sogenannte "Ewigkeitsklausel" des Grundgesetzes?',
      options: [
        'Art. 1 Abs. 1 GG – die Menschenwürde',
        'Art. 20 Abs. 4 GG – das Widerstandsrecht',
        'Art. 79 Abs. 3 GG – der Schutz bestimmter Verfassungsgrundsätze vor Änderungen',
        'Art. 93 GG – das Bundesverfassungsgericht',
      ],
      correct: [2],
      explanation: 'Art. 79 Abs. 3 GG (Ewigkeitsklausel) schützt die Grundsätze der Art. 1 und 20 GG vor Verfassungsänderungen. Sie können auch mit 2/3-Mehrheit nicht geändert werden.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welche Aussage zur Gewaltenteilung im Grundgesetz ist korrekt?',
      options: [
        'Die Gewaltenteilung ist in Art. 1 GG geregelt.',
        'Es gibt im GG nur zwei Gewalten: Gesetzgebung und Rechtsprechung.',
        'Art. 20 Abs. 2 GG regelt die Aufteilung in Legislative, Exekutive und Judikative.',
        'Die Gewaltenteilung gilt nur auf Bundesebene, nicht in den Ländern.',
      ],
      correct: [2],
      explanation: 'Art. 20 Abs. 2 GG bestimmt, dass die Staatsgewalt durch besondere Organe der Gesetzgebung (Legislative), der vollziehenden Gewalt (Exekutive) und der Rechtsprechung (Judikative) ausgeübt wird.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was unterscheidet Menschenrechte von Deutschengrundrechten im GG?',
      options: [
        'Menschenrechte gelten nur für Kinder, Deutschenrechte für Erwachsene.',
        'Menschenrechte stehen jedem Menschen zu, Deutschengrundrechte nur deutschen Staatsangehörigen.',
        'Deutschengrundrechte können nicht eingeschränkt werden, Menschenrechte schon.',
        'Es gibt keinen Unterschied; alle Grundrechte stehen allen Menschen zu.',
      ],
      correct: [1],
      explanation: 'Menschenrechte (z. B. Art. 1, 2, 4 GG) stehen jedem Menschen zu. Deutschengrundrechte (z. B. Art. 8, 9, 11, 12 GG) sind auf deutsche Staatsangehörige beschränkt.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welcher Artikel des GG enthält die Wesensgehaltsgarantie für Grundrechte?',
      options: [
        'Artikel 1 Abs. 2 GG',
        'Artikel 14 Abs. 1 GG',
        'Artikel 19 Abs. 2 GG',
        'Artikel 79 Abs. 3 GG',
      ],
      correct: [2],
      explanation: 'Art. 19 Abs. 2 GG lautet: „In keinem Fall darf ein Grundrecht in seinem Wesensgehalt angetastet werden." Der Kernbereich jedes Grundrechts bleibt auch bei gesetzlichen Einschränkungen geschützt.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was garantiert die Rechtswegarantie des Artikels 19 Abs. 4 GG?',
      options: [
        'Das Recht auf einen kostenlosen Anwalt',
        'Den Zugang zu Gerichten bei Verletzung von Rechten durch die öffentliche Gewalt',
        'Das Recht auf ein Volksbegehren',
        'Den Schutz vor Doppelbestrafung',
      ],
      correct: [1],
      explanation: 'Art. 19 Abs. 4 GG garantiert: Wird jemand durch die öffentliche Gewalt in seinen Rechten verletzt, steht ihm der Rechtsweg offen. Dies sichert die gerichtliche Kontrolle staatlichen Handelns.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welcher Artikel des GG schützt Eigentum und Erbrecht?',
      options: [
        'Artikel 11 GG',
        'Artikel 12 GG',
        'Artikel 13 GG',
        'Artikel 14 GG',
      ],
      correct: [3],
      explanation: 'Art. 14 GG schützt Eigentum und Erbrecht. Enteignungen sind nur zum Wohle der Allgemeinheit und gegen angemessene Entschädigung zulässig. Außerdem gilt: Eigentum verpflichtet.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was regelt Artikel 4 GG?',
      options: [
        'Die Berufsfreiheit',
        'Die Gleichberechtigung von Mann und Frau',
        'Die Freiheit des Glaubens, des Gewissens und des religiösen Bekenntnisses',
        'Die Unverletzlichkeit der Wohnung',
      ],
      correct: [2],
      explanation: 'Art. 4 GG schützt die Freiheit des Glaubens, des Gewissens und des religiösen und weltanschaulichen Bekenntnisses sowie die ungestörte Religionsausübung.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welche Artikel des GG zählen zu den Grundrechten?',
      options: [
        'Artikel 1 bis 19 GG',
        'Artikel 1 bis 20 GG',
        'Artikel 1 bis 33 GG',
        'Artikel 20 bis 37 GG',
      ],
      correct: [0],
      explanation: 'Die Grundrechte sind in den Artikeln 1 bis 19 des Grundgesetzes verankert. Art. 20 ff. enthalten die Staatsstrukturprinzipien.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was besagt Artikel 1 Abs. 3 GG?',
      options: [
        'Die Grundrechte können durch einfaches Gesetz eingeschränkt werden.',
        'Die Grundrechte binden Gesetzgebung, vollziehende Gewalt und Rechtsprechung als unmittelbar geltendes Recht.',
        'Grundrechte gelten nur für deutsche Staatsbürger.',
        'Grundrechte können durch Volksentscheid abgeschafft werden.',
      ],
      correct: [1],
      explanation: 'Art. 1 Abs. 3 GG bestimmt, dass die Grundrechte Gesetzgebung, Exekutive und Judikative als unmittelbar geltendes Recht binden – sie sind also direkt anwendbar, nicht nur Programmsätze.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welches Grundrecht ist ein sogenanntes Deutschengrundrecht?',
      options: [
        'Menschenwürde (Art. 1 GG)',
        'Recht auf Leben (Art. 2 Abs. 2 GG)',
        'Glaubensfreiheit (Art. 4 GG)',
        'Versammlungsfreiheit (Art. 8 GG)',
      ],
      correct: [3],
      explanation: 'Die Versammlungsfreiheit (Art. 8 GG) gilt nur für "alle Deutschen". Menschenwürde, Recht auf Leben und Glaubensfreiheit hingegen stehen jedem Menschen zu (Menschenrechte).',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was regelt Artikel 2 Abs. 2 GG?',
      options: [
        'Das Recht auf Bildung und Ausbildung',
        'Das Recht auf Leben und körperliche Unversehrtheit sowie die Unverletzlichkeit der persönlichen Freiheit',
        'Das Recht auf soziale Absicherung',
        'Das Recht auf Wohnraum',
      ],
      correct: [1],
      explanation: 'Art. 2 Abs. 2 GG schützt das Recht auf Leben und körperliche Unversehrtheit sowie die persönliche Freiheit. Eingriffe sind nur aufgrund eines Gesetzes zulässig.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welcher Artikel des GG regelt die Vereinigungsfreiheit?',
      options: [
        'Artikel 5 GG',
        'Artikel 7 GG',
        'Artikel 9 GG',
        'Artikel 11 GG',
      ],
      correct: [2],
      explanation: 'Art. 9 GG schützt die Vereinigungsfreiheit. Alle Deutschen haben das Recht, Vereine und Gesellschaften zu bilden. Vereinigungen mit gesetzwidrigen Zwecken sind verboten.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Darf das Grundgesetz in Teilen geändert werden, die durch Art. 79 Abs. 3 GG geschützt sind?',
      options: [
        'Ja, mit einfacher Mehrheit im Bundestag',
        'Ja, wenn Bundestag und Bundesrat jeweils mit Zweidrittelmehrheit zustimmen',
        'Nein, diese Teile sind absolut unveränderbar',
        'Nur in Kriegszeiten und mit Zustimmung des Bundesverfassungsgerichts',
      ],
      correct: [2],
      explanation: 'Art. 79 Abs. 3 GG (Ewigkeitsklausel) schließt jede Änderung der in Art. 1 und 20 GG niedergelegten Grundsätze aus – selbst eine Zweidrittelmehrheit kann diese Kernbereiche nicht ändern.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Welche Aussage zur Meinungsfreiheit (Art. 5 GG) ist korrekt?',
      options: [
        'Die Meinungsfreiheit ist schrankenlos und kann nicht eingeschränkt werden.',
        'Die Meinungsfreiheit findet ihre Schranken u. a. in den allgemeinen Gesetzen und dem Recht der persönlichen Ehre.',
        'Die Meinungsfreiheit gilt nur für deutsche Staatsbürger.',
        'Die Meinungsfreiheit schützt nur mündliche Äußerungen.',
      ],
      correct: [1],
      explanation: 'Art. 5 Abs. 2 GG nennt ausdrücklich Schranken der Meinungsfreiheit: allgemeine Gesetze, gesetzliche Bestimmungen zum Schutze der Jugend und das Recht der persönlichen Ehre.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Welches Organ ist für den Schutz des Grundgesetzes in letzter Instanz zuständig?',
      options: [
        'Der Bundesrat',
        'Das Bundesverwaltungsgericht',
        'Das Bundesverfassungsgericht',
        'Der Bundesjustizminister',
      ],
      correct: [2],
      explanation: 'Das Bundesverfassungsgericht (BVerfG) in Karlsruhe ist Hüter des Grundgesetzes. Es entscheidet u. a. über Verfassungsbeschwerden und prüft die Verfassungsmäßigkeit von Gesetzen.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was regelt Artikel 16a GG?',
      options: [
        'Die doppelte Staatsbürgerschaft',
        'Das Asylrecht für politisch Verfolgte',
        'Die Auslieferung deutscher Staatsbürger',
        'Das Verbot der Ausbürgerung',
      ],
      correct: [1],
      explanation: 'Art. 16a GG gewährt politisch Verfolgten Asylrecht in Deutschland. Das Grundrecht gilt jedoch nicht für Einreisende aus sicheren Drittstaaten oder EU-Mitgliedstaaten.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was gilt für Grundrechtseinschränkungen nach Art. 19 Abs. 1 GG?',
      options: [
        'Grundrechte können nur durch Volksabstimmung eingeschränkt werden.',
        'Ein Gesetz, das ein Grundrecht einschränkt, muss allgemein gelten und darf nicht nur für einen Einzelfall gelten.',
        'Grundrechte können durch Verwaltungsvorschriften eingeschränkt werden.',
        'Nur der Bundesrat kann Grundrechtseinschränkungen beschließen.',
      ],
      correct: [1],
      explanation: 'Art. 19 Abs. 1 GG bestimmt: Soweit ein Grundrecht durch Gesetz eingeschränkt werden kann, muss das Gesetz allgemein gelten. Einzelfallgesetze (Maßnahmegesetze) gegen bestimmte Personen sind verboten.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Welcher Artikel des GG regelt die Berufsfreiheit?',
      options: [
        'Artikel 11 GG',
        'Artikel 12 GG',
        'Artikel 13 GG',
        'Artikel 14 GG',
      ],
      correct: [1],
      explanation: 'Art. 12 GG schützt die Berufsfreiheit: Alle Deutschen haben das Recht, Beruf, Arbeitsplatz und Ausbildungsstätte frei zu wählen. Die Berufsausübung kann durch Gesetz geregelt werden.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was regelt Artikel 13 GG?',
      options: [
        'Die Freizügigkeit im Bundesgebiet',
        'Die Unverletzlichkeit der Wohnung',
        'Das Briefgeheimnis',
        'Das Petitionsrecht',
      ],
      correct: [1],
      explanation: 'Art. 13 GG schützt die Unverletzlichkeit der Wohnung. Durchsuchungen dürfen nur durch den Richter, bei Gefahr im Verzuge auch durch andere gesetzlich bestimmte Organe angeordnet werden.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet, dass Deutschland laut Art. 20 GG ein "Sozialstaat" ist?',
      options: [
        'Alle Bürger erhalten ein bedingungsloses Grundeinkommen.',
        'Der Staat ist verpflichtet, für soziale Gerechtigkeit und Sicherheit zu sorgen.',
        'Nur Gewerkschaften dürfen politische Entscheidungen treffen.',
        'Privatunternehmen sind verboten.',
      ],
      correct: [1],
      explanation: 'Das Sozialstaatsprinzip (Art. 20 Abs. 1 GG) verpflichtet den Staat, für ein Mindestmaß an sozialer Gerechtigkeit und Sicherheit zu sorgen, z. B. durch Sozialversicherungssysteme und staatliche Fürsorge.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welcher Artikel des GG regelt die Freizügigkeit?',
      options: [
        'Artikel 8 GG',
        'Artikel 10 GG',
        'Artikel 11 GG',
        'Artikel 13 GG',
      ],
      correct: [2],
      explanation: 'Art. 11 GG gewährt allen Deutschen die Freizügigkeit im gesamten Bundesgebiet – also das Recht, an jedem Ort in Deutschland zu wohnen und sich aufzuhalten. Es ist ein Deutschengrundrecht.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welchen Schutz bietet Artikel 10 GG?',
      options: [
        'Den Schutz der Versammlungsfreiheit',
        'Das Brief-, Post- und Fernmeldegeheimnis',
        'Den Schutz vor Diskriminierung',
        'Das Recht auf informationelle Selbstbestimmung',
      ],
      correct: [1],
      explanation: 'Art. 10 GG schützt das Brief-, Post- und Fernmeldegeheimnis. Beschränkungen sind nur aufgrund eines Gesetzes zulässig.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was ist mit "Grundgesetzbindung der Staatsgewalt" gemeint?',
      options: [
        'Nur die Bundesregierung muss sich an das GG halten.',
        'Das GG bindet alle drei Gewalten: Gesetzgebung, Exekutive und Judikative.',
        'Das GG gilt nur für Bundesbehörden, nicht für Landesbehörden.',
        'Das GG ist nur für Gerichte verbindlich.',
      ],
      correct: [1],
      explanation: 'Gemäß Art. 1 Abs. 3 GG binden die Grundrechte Gesetzgebung, vollziehende Gewalt und Rechtsprechung als unmittelbar geltendes Recht – also alle drei Staatgewalten auf allen Ebenen.',
      difficulty: 2,
    },
    {
      type: 'truefalse',
      prompt: 'Die Menschenwürde (Art. 1 Abs. 1 GG) kann durch ein verfassungsänderndes Gesetz mit Zweidrittelmehrheit eingeschränkt werden.',
      options: ['Richtig', 'Falsch'],
      correct: [1],
      explanation: 'Falsch. Die Menschenwürde ist durch die Ewigkeitsklausel (Art. 79 Abs. 3 GG) absolut geschützt. Sie kann auch durch eine verfassungsändernde Zweidrittelmehrheit nicht angetastet werden.',
      difficulty: 2,
    },
    {
      type: 'truefalse',
      prompt: 'Artikel 8 GG (Versammlungsfreiheit) ist ein Deutschengrundrecht und gilt nicht für Ausländer.',
      options: ['Richtig', 'Falsch'],
      correct: [0],
      explanation: 'Richtig. Art. 8 GG gewährt "allen Deutschen" das Recht zur Versammlung. Für Ausländer kann die Versammlungsfreiheit jedoch aus der allgemeinen Handlungsfreiheit (Art. 2 Abs. 1 GG) abgeleitet werden.',
      difficulty: 2,
    },
    {
      type: 'truefalse',
      prompt: 'Das Grundgesetz wurde am 8. Mai 1949 vom Parlamentarischen Rat beschlossen.',
      options: ['Richtig', 'Falsch'],
      correct: [0],
      explanation: 'Richtig. Der Parlamentarische Rat beschloss das Grundgesetz am 8. Mai 1949. In Kraft getreten ist es dann am 23. Mai 1949 nach Genehmigung durch die Militärgouverneure und die Ratifizierung durch die Länderparlamente.',
      difficulty: 3,
    },
    {
      type: 'fill',
      prompt: 'Ergänze den Wortlaut von Art. 1 Abs. 1 GG: "Die Würde des Menschen ist ___."',
      options: ['unantastbar', 'heilig', 'unveräußerlich', 'unverletzlich'],
      correct: [0],
      explanation: 'Der genaue Wortlaut lautet: "Die Würde des Menschen ist unantastbar." Dieser Kernsatz ist das Fundament des gesamten Grundgesetzes.',
      difficulty: 1,
    },
  ],
};

export default topic;
