import type { RawTopic } from '../types';

const topic: RawTopic = {
  slug: 'hardware',
  title: 'Hardware & Rechneraufbau',
  description: 'Komponenten eines Computers und ihre Aufgaben.',
  flashcards: [
    {
      front: 'Was ist die CPU und welche Hauptaufgabe hat sie?',
      back: 'Die CPU (Central Processing Unit) ist der Hauptprozessor des Computers. Sie führt Berechnungen und logische Operationen aus und steuert den Ablauf von Programmen.',
    },
    {
      front: 'Was ist das ALU (Arithmetic Logic Unit)?',
      back: 'Das ALU (Rechenwerk) ist ein Teil der CPU und führt arithmetische Operationen (Addition, Subtraktion usw.) sowie logische Verknüpfungen (AND, OR, NOT) durch.',
    },
    {
      front: 'Was ist das Steuerwerk (Control Unit) der CPU?',
      back: 'Das Steuerwerk koordiniert alle Abläufe innerhalb der CPU. Es interpretiert Befehle, steuert den Datentransport und synchronisiert die Zusammenarbeit aller Komponenten.',
    },
    {
      front: 'Was beschreibt der Takt einer CPU (gemessen in GHz)?',
      back: 'Der Takt gibt an, wie viele Rechenoperationen die CPU pro Sekunde ausführen kann. 1 GHz entspricht einer Milliarde Taktzyklen pro Sekunde. Ein höherer Takt bedeutet in der Regel mehr Rechenleistung.',
    },
    {
      front: 'Was ist RAM und warum ist er flüchtig?',
      back: 'RAM (Random Access Memory) ist der Arbeitsspeicher des Computers. Er speichert temporär Daten und Programme, auf die die CPU zugreift. Er ist flüchtig, da sein Inhalt beim Abschalten der Stromversorgung verloren geht.',
    },
    {
      front: 'Was ist ROM und worin unterscheidet er sich von RAM?',
      back: 'ROM (Read Only Memory) ist ein Nur-Lese-Speicher, dessen Inhalt dauerhaft gespeichert ist und ohne Strom erhalten bleibt (nichtflüchtig). Er enthält z. B. das BIOS. Im Gegensatz zum RAM kann er nicht einfach beschrieben werden.',
    },
    {
      front: 'Was ist der Unterschied zwischen HDD und SSD?',
      back: 'Eine HDD (Hard Disk Drive) speichert Daten magnetisch auf rotierenden Scheiben – sie ist langsamer und anfälliger für mechanische Schäden. Eine SSD (Solid State Drive) nutzt Flash-Speicher, hat keine beweglichen Teile und ist deutlich schneller. Beide sind nichtflüchtige Speicher.',
    },
    {
      front: 'Was ist das Mainboard (Hauptplatine)?',
      back: 'Das Mainboard ist die zentrale Leiterplatte des Computers. Es verbindet alle Komponenten (CPU, RAM, Grafikkarte, Speicher usw.) miteinander und stellt Steckplätze sowie Anschlüsse bereit.',
    },
    {
      front: 'Welche Aufgabe hat das Netzteil?',
      back: 'Das Netzteil wandelt die Wechselspannung aus der Steckdose (230 V) in Gleichspannungen um (z. B. 12 V, 5 V, 3,3 V), die die Komponenten des Computers benötigen.',
    },
    {
      front: 'Was ist eine GPU und wofür wird sie eingesetzt?',
      back: 'Die GPU (Graphics Processing Unit) ist ein spezieller Prozessor auf der Grafikkarte, der für die Bildberechnung und -ausgabe zuständig ist. Moderne GPUs werden auch für parallele Berechnungen (z. B. KI, Wissenschaft) genutzt.',
    },
    {
      front: 'Was ist BIOS und was ist UEFI?',
      back: 'Das BIOS (Basic Input/Output System) ist eine Firmware, die beim Systemstart grundlegende Hardware prüft und das Betriebssystem lädt. UEFI (Unified Extensible Firmware Interface) ist der modernere Nachfolger mit erweiterter Funktionalität, grafischer Oberfläche und Unterstützung großer Festplatten.',
    },
    {
      front: 'Was ist Cache-Speicher und wozu dient er?',
      back: 'Der Cache ist ein sehr schneller Pufferspeicher, der sich direkt in oder nahe der CPU befindet (L1, L2, L3). Er speichert häufig benötigte Daten, damit die CPU nicht ständig auf den langsameren RAM zugreifen muss.',
    },
    {
      front: 'Was beschreibt die Von-Neumann-Architektur?',
      back: 'Die Von-Neumann-Architektur ist das Grundprinzip moderner Computer. Sie definiert fünf Einheiten: Rechenwerk (ALU), Steuerwerk, Speicherwerk, Eingabewerk und Ausgabewerk – alle verbunden über ein gemeinsames Bus-System. Programm und Daten liegen im selben Speicher.',
    },
    {
      front: 'Was ist ein Bus-System im Computer?',
      back: 'Ein Bus ist ein gemeinsames Leitungssystem (elektrische Verbindungen), über das Daten, Adressen und Steuersignale zwischen den Komponenten eines Computers übertragen werden. Wichtige Busse sind der Datenbus, Adressbus und Steuerbus.',
    },
    {
      front: 'Nenne drei typische Eingabegeräte.',
      back: 'Tastatur, Maus und Scanner sind typische Eingabegeräte. Sie übermitteln Informationen oder Befehle vom Nutzer an den Computer.',
    },
    {
      front: 'Nenne drei typische Ausgabegeräte.',
      back: 'Monitor, Drucker und Lautsprecher sind typische Ausgabegeräte. Sie geben verarbeitete Daten in wahrnehmbarer Form an den Nutzer aus.',
    },
    {
      front: 'Was versteht man unter Peripheriegeräten?',
      back: 'Peripheriegeräte sind alle externen Geräte, die an einen Computer angeschlossen werden, aber nicht zu seinem Kernaufbau gehören – z. B. Tastatur, Maus, Drucker, Scanner, externe Festplatten und Webcams.',
    },
    {
      front: 'Was unterscheidet flüchtigen von nichtflüchtigem Speicher?',
      back: 'Flüchtiger Speicher (z. B. RAM) verliert seinen Inhalt, sobald die Stromversorgung unterbrochen wird. Nichtflüchtiger Speicher (z. B. HDD, SSD, ROM, Flash-Speicher) behält seine Daten auch ohne Strom dauerhaft.',
    },
    {
      front: 'Was ist der Unterschied zwischen Datenbus, Adressbus und Steuerbus?',
      back: 'Der Datenbus überträgt die eigentlichen Daten. Der Adressbus gibt an, von welcher Speicheradresse gelesen oder geschrieben wird. Der Steuerbus überträgt Steuersignale (z. B. Lese- oder Schreibbefehl) zwischen den Komponenten.',
    },
    {
      front: 'Was bedeutet "Bit-Breite" beim Prozessor (z. B. 32-Bit vs. 64-Bit)?',
      back: 'Die Bit-Breite gibt an, wie viele Bits eine CPU gleichzeitig verarbeiten kann. Ein 64-Bit-Prozessor kann mehr Daten auf einmal verarbeiten und mehr RAM adressieren als ein 32-Bit-Prozessor (max. 4 GB RAM bei 32 Bit).',
    },
  ],
  questions: [
    {
      type: 'mc',
      prompt: 'Welche Komponente wird als das "Gehirn" des Computers bezeichnet?',
      options: ['RAM', 'Festplatte', 'CPU', 'Netzteil'],
      correct: [2],
      explanation: 'Die CPU (Central Processing Unit) führt alle Berechnungen und logischen Operationen aus und gilt daher als das Gehirn des Computers.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet die Abkürzung RAM?',
      options: ['Read Access Memory', 'Random Access Memory', 'Rapid Arithmetic Module', 'Read And Modify'],
      correct: [1],
      explanation: 'RAM steht für Random Access Memory (Speicher mit wahlfreiem Zugriff) und bezeichnet den flüchtigen Arbeitsspeicher des Computers.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welcher Speicher verliert seinen Inhalt, wenn die Stromversorgung unterbrochen wird?',
      options: ['ROM', 'SSD', 'RAM', 'HDD'],
      correct: [2],
      explanation: 'RAM ist flüchtiger Speicher – sein Inhalt geht beim Ausschalten des Computers verloren. ROM, HDD und SSD sind nichtflüchtig.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist der Hauptvorteil einer SSD gegenüber einer HDD?',
      options: ['Günstigerer Preis pro Gigabyte', 'Höhere Speicherkapazität', 'Schnellere Zugriffszeiten und keine beweglichen Teile', 'Bessere Kompatibilität mit älteren Systemen'],
      correct: [2],
      explanation: 'SSDs nutzen Flash-Speicher ohne bewegliche mechanische Teile, was zu deutlich schnelleren Lese- und Schreibgeschwindigkeiten sowie höherer Robustheit führt.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welche Einheit wird für den Takt einer CPU verwendet?',
      options: ['Megabyte (MB)', 'Gigahertz (GHz)', 'Gigabyte (GB)', 'Megapixel (MP)'],
      correct: [1],
      explanation: 'Der CPU-Takt wird in Hertz (Hz) bzw. Gigahertz (GHz) gemessen. 1 GHz entspricht einer Milliarde Taktzyklen pro Sekunde.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist die Aufgabe des Steuerwerks (Control Unit) in der CPU?',
      options: ['Arithmetische Berechnungen durchführen', 'Daten dauerhaft speichern', 'Den Ablauf von Befehlen koordinieren und steuern', 'Die Grafik berechnen'],
      correct: [2],
      explanation: 'Das Steuerwerk koordiniert alle Abläufe der CPU, interpretiert Befehle und steuert den Datentransport zwischen den Einheiten.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Wofür steht die Abkürzung ALU?',
      options: ['Automatic Load Unit', 'Arithmetic Logic Unit', 'Advanced Lookup Unit', 'Adaptive Language Unit'],
      correct: [1],
      explanation: 'ALU steht für Arithmetic Logic Unit (Rechenwerk). Sie führt arithmetische und logische Operationen in der CPU durch.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welche Funktion hat das BIOS?',
      options: ['Es speichert Benutzerdateien dauerhaft', 'Es ist eine Firmware, die beim Start die Hardware prüft und das Betriebssystem lädt', 'Es regelt die Stromversorgung der Komponenten', 'Es berechnet die Grafikausgabe'],
      correct: [1],
      explanation: 'Das BIOS (Basic Input/Output System) ist eine Firmware, die beim Systemstart einen Hardware-Selbsttest (POST) durchführt und anschließend das Betriebssystem von einem Datenträger lädt.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was ist UEFI?',
      options: ['Eine Art Arbeitsspeicher', 'Der Nachfolger des BIOS mit erweitertem Funktionsumfang', 'Ein Dateisystem für SSDs', 'Ein Busstandard für Grafikkarten'],
      correct: [1],
      explanation: 'UEFI (Unified Extensible Firmware Interface) ist der moderne Nachfolger des BIOS. Es bietet eine grafische Oberfläche, schnellere Startzeiten und unterstützt große Festplatten (über 2 TB via GPT).',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welche Aussage zum Cache-Speicher ist korrekt?',
      options: ['Cache ist langsamer als RAM', 'Cache ist ein nichtflüchtiger Massenspeicher', 'Cache ist ein schneller Pufferspeicher zwischen CPU und RAM', 'Cache ersetzt die Festplatte'],
      correct: [2],
      explanation: 'Der Cache ist ein sehr schneller Zwischenspeicher, der häufig benötigte Daten bereithält, damit die CPU nicht ständig auf den langsameren RAM zugreifen muss. Es gibt Cacheebenen L1, L2 und L3.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welches Grundprinzip beschreibt die Von-Neumann-Architektur?',
      options: ['Getrennte Speicher für Programme und Daten', 'Programme und Daten liegen im gleichen Speicher und werden über einen gemeinsamen Bus übertragen', 'Nur Ausgabegeräte sind mit dem Prozessor verbunden', 'Mehrere CPUs arbeiten unabhängig ohne gemeinsamen Speicher'],
      correct: [1],
      explanation: 'Bei der Von-Neumann-Architektur befinden sich Programme und Daten im selben Speicher. Alle Einheiten (Rechenwerk, Steuerwerk, Speicher, Ein-/Ausgabe) sind über ein gemeinsames Bus-System verbunden.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welche der folgenden Komponenten ist ein Ausgabegerät?',
      options: ['Tastatur', 'Maus', 'Scanner', 'Drucker'],
      correct: [3],
      explanation: 'Ein Drucker ist ein Ausgabegerät, da er Informationen vom Computer in eine für den Menschen wahrnehmbare Form (Papierausdruck) bringt. Tastatur, Maus und Scanner sind Eingabegeräte.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist das Mainboard?',
      options: ['Der größte Massenspeicher im PC', 'Die zentrale Leiterplatte, die alle Komponenten verbindet', 'Ein spezieller Cache-Speicher', 'Das Betriebssystem des Computers'],
      correct: [1],
      explanation: 'Das Mainboard (Hauptplatine) ist die zentrale Leiterplatte. Es verbindet CPU, RAM, Grafikkarte, Speicher und alle anderen Komponenten miteinander.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welche Aufgabe hat das Netzteil im Computer?',
      options: ['Es speichert das BIOS dauerhaft', 'Es wandelt Netzwechselspannung in Gleichspannungen für die Komponenten um', 'Es steuert den Datenaustausch über das Netzwerk', 'Es erhöht die Taktfrequenz der CPU'],
      correct: [1],
      explanation: 'Das Netzteil (PSU – Power Supply Unit) wandelt die 230-V-Wechselspannung aus der Steckdose in die von den Komponenten benötigten Gleichspannungen (z. B. 12 V, 5 V, 3,3 V) um.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welcher Speicher ist nichtflüchtig?',
      options: ['RAM', 'CPU-Register', 'Cache (L1)', 'ROM'],
      correct: [3],
      explanation: 'ROM (Read Only Memory) ist nichtflüchtig – sein Inhalt bleibt auch ohne Stromversorgung erhalten. RAM, CPU-Register und Cache sind flüchtige Speicher.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was überträgt der Adressbus?',
      options: ['Die eigentlichen Nutzdaten', 'Steuersignale wie Lese- oder Schreibbefehle', 'Die Speicheradressen, auf die zugegriffen wird', 'Die Taktfrequenz der CPU'],
      correct: [2],
      explanation: 'Der Adressbus überträgt die Speicheradressen, auf die die CPU zugreifen möchte. Die Breite des Adressbusses bestimmt, wie viel Arbeitsspeicher adressiert werden kann.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Welches Gerät ist ein Eingabegerät?',
      options: ['Monitor', 'Lautsprecher', 'Beamer', 'Scanner'],
      correct: [3],
      explanation: 'Ein Scanner liest Vorlagen ein und überträgt die Daten in den Computer – er ist ein Eingabegerät. Monitor, Lautsprecher und Beamer sind Ausgabegeräte.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welche CPU-Cache-Ebene ist am schnellsten und liegt am nächsten an der CPU?',
      options: ['L3-Cache', 'L2-Cache', 'L1-Cache', 'Festplatten-Cache'],
      correct: [2],
      explanation: 'Der L1-Cache ist der kleinste, aber schnellste Cache-Speicher und befindet sich direkt im CPU-Kern. L2 und L3 sind größer, aber langsamer.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Was beschreibt der Begriff "Peripheriegerät"?',
      options: ['Alle internen Bauteile auf dem Mainboard', 'Externe Geräte, die an den Computer angeschlossen werden', 'Nur Geräte, die Daten ausgeben', 'Der Speicher außerhalb der CPU'],
      correct: [1],
      explanation: 'Peripheriegeräte sind externe Geräte, die an den Computer angeschlossen werden, aber nicht zu seinem Kernaufbau gehören – z. B. Drucker, Tastatur, Maus, externe Laufwerke.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welche Aussage zur HDD ist korrekt?',
      options: ['Eine HDD speichert Daten in Flash-Chips ohne bewegliche Teile', 'Eine HDD nutzt magnetische Scheiben und mechanische Schreib-/Leseköpfe', 'Eine HDD ist schneller als eine SSD', 'Eine HDD ist ein flüchtiger Speicher'],
      correct: [1],
      explanation: 'Eine HDD (Hard Disk Drive) speichert Daten magnetisch auf rotierenden Scheiben (Plattern). Mechanische Schreib-/Leseköpfe bewegen sich über die Scheiben, was sie langsamer und empfindlicher macht als SSDs.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welche Einheit beschreibt die Von-Neumann-Architektur NICHT als Grundeinheit?',
      options: ['Rechenwerk (ALU)', 'Steuerwerk', 'Drucker', 'Speicherwerk'],
      correct: [2],
      explanation: 'Die Von-Neumann-Architektur definiert fünf Grundeinheiten: Rechenwerk (ALU), Steuerwerk, Speicherwerk, Eingabewerk und Ausgabewerk. Der Drucker selbst ist kein definiertes Grundelement der Architektur.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Was ist ein wesentlicher Vorteil von UEFI gegenüber dem herkömmlichen BIOS?',
      options: ['UEFI benötigt weniger Strom', 'UEFI unterstützt Festplatten über 2 TB und bietet eine grafische Oberfläche', 'UEFI ist auf jedem Mainboard ab 1990 vorhanden', 'UEFI ersetzt den RAM'],
      correct: [1],
      explanation: 'UEFI unterstützt im Gegensatz zum alten BIOS Festplatten über 2 TB (über GPT-Partitionstabellen), bietet eine grafische Benutzeroberfläche, schnellere Bootzeiten und verbesserte Sicherheitsfunktionen (Secure Boot).',
      difficulty: 2,
    },
    {
      type: 'truefalse',
      prompt: 'Eine SSD ist ein flüchtiger Speicher, da sie Flash-Technologie verwendet.',
      options: ['Wahr', 'Falsch'],
      correct: [1],
      explanation: 'Falsch. Eine SSD ist ein nichtflüchtiger Speicher – sie behält Daten auch ohne Stromversorgung. Die Flash-Technologie ermöglicht dies, im Gegensatz zum flüchtigen RAM.',
      difficulty: 1,
    },
    {
      type: 'truefalse',
      prompt: 'Das Mainboard verbindet alle Hauptkomponenten eines Computers miteinander.',
      options: ['Wahr', 'Falsch'],
      correct: [0],
      explanation: 'Wahr. Das Mainboard ist die zentrale Platine, die CPU, RAM, Grafikkarte, Speicher und alle anderen Komponenten über Steckplätze und Leiterbahnen miteinander verbindet.',
      difficulty: 1,
    },
    {
      type: 'truefalse',
      prompt: 'Bei der Von-Neumann-Architektur sind Programme und Daten in getrennten Speicherbereichen abgelegt.',
      options: ['Wahr', 'Falsch'],
      correct: [1],
      explanation: 'Falsch. Das Prinzip der Von-Neumann-Architektur ist gerade, dass Programme (Befehle) und Daten im selben Speicher abgelegt werden. Dies ist ein wichtiges Merkmal dieser Architektur.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Wie viele GHz entsprechen 2.500 MHz?',
      options: ['0,25 GHz', '25 GHz', '2,5 GHz', '250 GHz'],
      correct: [2],
      explanation: '1 GHz = 1.000 MHz. Daher entsprechen 2.500 MHz genau 2,5 GHz. Diese Umrechnung ist beim Vergleich von CPU-Taktraten relevant.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welche Aussage zur GPU ist richtig?',
      options: ['Die GPU ist für die Verwaltung des Arbeitsspeichers zuständig', 'Die GPU ist ein spezialisierter Prozessor für Bildberechnung und parallele Berechnungen', 'Die GPU ersetzt bei modernen Computern die CPU vollständig', 'Die GPU ist ein Eingabegerät'],
      correct: [1],
      explanation: 'Die GPU (Graphics Processing Unit) auf der Grafikkarte ist spezialisiert auf die Verarbeitung grafischer Daten und parallele Berechnungen. Sie unterstützt heute auch KI-Berechnungen und wissenschaftliche Simulationen.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welche der folgenden Geräte sind sowohl Eingabe- als auch Ausgabegeräte (E/A-Geräte)?',
      options: ['Drucker und Scanner', 'Touchscreen und Headset mit Mikrofon', 'Tastatur und Monitor', 'Maus und Lautsprecher'],
      correct: [1],
      explanation: 'Touchscreens empfangen Eingaben (Berührungen) und zeigen Ausgaben an. Ein Headset mit Mikrofon gibt Audio aus und nimmt Audio auf. Beide sind daher bidirektionale E/A-Geräte.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Welche Aussage zum ROM ist korrekt?',
      options: ['ROM verliert seine Daten bei Stromunterbrechung', 'ROM ist schneller als RAM', 'ROM enthält dauerhaft gespeicherte Daten, z. B. die Firmware', 'ROM kann vom Benutzer beliebig beschrieben werden'],
      correct: [2],
      explanation: 'ROM (Read Only Memory) ist nichtflüchtiger Speicher, der dauerhaft Daten enthält – typischerweise die Firmware wie das BIOS/UEFI. Er verliert seine Daten nicht bei Stromausfall.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was beschreibt der Begriff "Busbreite" in einem Computersystem?',
      options: ['Die physische Länge der Verbindungskabel', 'Die Anzahl der Bits, die gleichzeitig über einen Bus übertragen werden können', 'Die Taktfrequenz des Busses in GHz', 'Die maximale Anzahl an Peripheriegeräten'],
      correct: [1],
      explanation: 'Die Busbreite gibt an, wie viele Bits gleichzeitig über den Bus übertragen werden können. Eine breitere Busbreite (z. B. 64 Bit statt 32 Bit) erlaubt eine schnellere Datenübertragung.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Welche Komponente ist für die dauerhafte Speicherung des Betriebssystems zuständig?',
      options: ['RAM', 'CPU-Cache', 'Festplatte (HDD oder SSD)', 'Netzteil'],
      correct: [2],
      explanation: 'Das Betriebssystem wird dauerhaft auf einem nichtflüchtigen Massenspeicher (HDD oder SSD) gespeichert. Beim Start wird es in den flüchtigen RAM geladen, um ausgeführt zu werden.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welche Einheit der Von-Neumann-Architektur ist für die Verbindung aller anderen Einheiten verantwortlich?',
      options: ['Das Rechenwerk (ALU)', 'Das Steuerwerk', 'Das Bus-System', 'Das Speicherwerk'],
      correct: [2],
      explanation: 'Das Bus-System (bestehend aus Daten-, Adress- und Steuerbus) verbindet in der Von-Neumann-Architektur alle Einheiten miteinander und ermöglicht den Datenaustausch zwischen ihnen.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Was ist ein typisches Merkmal eines 64-Bit-Prozessors im Vergleich zu einem 32-Bit-Prozessor?',
      options: ['Er hat doppelt so viele CPU-Kerne', 'Er kann mehr als 4 GB RAM adressieren', 'Er taktet mit doppelter Frequenz', 'Er benötigt kein Betriebssystem'],
      correct: [1],
      explanation: 'Ein 32-Bit-Prozessor kann maximal 4 GB RAM adressieren (2³²). Ein 64-Bit-Prozessor kann theoretisch bis zu 16 Exabyte adressieren, was für moderne Anwendungen entscheidend ist.',
      difficulty: 3,
    },
    {
      type: 'truefalse',
      prompt: 'Der L1-Cache ist langsamer als der L3-Cache, dafür aber größer.',
      options: ['Wahr', 'Falsch'],
      correct: [1],
      explanation: 'Falsch. Der L1-Cache ist der schnellste, aber kleinste Cache-Speicher. Der L3-Cache ist größer, aber langsamer. Je näher der Cache am CPU-Kern liegt, desto schneller und kleiner ist er.',
      difficulty: 2,
    },
  ],
};

export default topic;
