import type { RawTopic } from '../types';

const topic: RawTopic = {
  slug: 'internationale-politik',
  title: 'Internationale Politik',
  description: 'Wichtige internationale Organisationen und Bündnisse.',
  flashcards: [
    {
      front: 'Wann wurde die United Nations (UN/Vereinte Nationen) gegründet?',
      back: 'Am 24. Oktober 1945, nach dem Ende des Zweiten Weltkriegs. Der offizielle Gründungstag ist der UN-Tag.',
    },
    {
      front: 'Wo hat die UN ihren Hauptsitz?',
      back: 'New York City, USA. Weitere wichtige Büros befinden sich in Genf, Wien und Nairobi.',
    },
    {
      front: 'Welche 5 Staaten sind ständige Mitglieder des UN-Sicherheitsrats mit Vetorecht?',
      back: 'USA, Russland, China, Frankreich und das Vereinigte Königreich (P5).',
    },
    {
      front: 'Wie viele Mitglieder hat die UN insgesamt (Stand 2025)?',
      back: '193 Mitgliedstaaten. Der Vatikan und Palästina sind Beobachterstaaten ohne Stimmrecht.',
    },
    {
      front: 'Wer ist aktueller UN-Generalsekretär (Stand 2026)?',
      back: 'António Guterres (Portugal), im Amt seit 1. Januar 2017, wiedergewählt für eine zweite Amtszeit bis Ende 2026.',
    },
    {
      front: 'Was ist die NATO und wie viele Mitglieder hat sie (Stand 2026)?',
      back: 'Die NATO (North Atlantic Treaty Organization) ist ein westliches Verteidigungsbündnis mit 32 Mitgliedstaaten. Gegründet 1949.',
    },
    {
      front: 'Wer ist aktueller NATO-Generalsekretär (Stand 2026)?',
      back: 'Mark Rutte (Niederlande), im Amt seit Oktober 2024. Er folgte Jens Stoltenberg nach.',
    },
    {
      front: 'Was ist der Artikel 5 des NATO-Vertrags?',
      back: 'Die Beistandsklausel: Ein Angriff auf ein NATO-Mitglied gilt als Angriff auf alle Mitglieder. Grundlage der kollektiven Verteidigung.',
    },
    {
      front: 'Was ist die G7 und welche Staaten gehören ihr an?',
      back: 'Die G7 ist ein informelles Forum der sieben führenden westlichen Industrienationen: USA, Kanada, Deutschland, Frankreich, Italien, Japan und das Vereinigte Königreich. Die EU nimmt als Gast teil.',
    },
    {
      front: 'Was ist der Unterschied zwischen G7 und G20?',
      back: 'Die G7 umfasst 7 westliche Industrienationen. Die G20 umfasst 19 führende Wirtschaftsnationen plus EU und Afrikanische Union (inkl. China, Indien, Brasilien etc.) und repräsentiert einen Großteil des globalen BIP.',
    },
    {
      front: 'Was ist die WHO und wo hat sie ihren Sitz?',
      back: 'Die WHO (World Health Organization / Weltgesundheitsorganisation) ist eine UN-Sonderorganisation für internationale Gesundheitsfragen. Sitz: Genf, Schweiz.',
    },
    {
      front: 'Was ist der IWF und wo hat er seinen Sitz?',
      back: 'Der IWF (Internationaler Währungsfonds) überwacht das internationale Währungssystem und gewährt Kredite an Länder in Zahlungsbilanzschwierigkeiten. Sitz: Washington D.C., USA.',
    },
    {
      front: 'Was ist die Weltbank und was ist ihr Hauptziel?',
      back: 'Die Weltbank (World Bank) ist eine internationale Finanzinstitution mit Sitz in Washington D.C. Sie vergibt Kredite und Zuschüsse an Entwicklungsländer zur Armutsbekämpfung und Förderung wirtschaftlicher Entwicklung.',
    },
    {
      front: 'Was ist die OPEC und wo hat sie ihren Sitz?',
      back: 'Die OPEC (Organization of the Petroleum Exporting Countries) koordiniert die Erdölpolitik ihrer Mitglieder. Sitz: Wien, Österreich. Gegründet 1960.',
    },
    {
      front: 'Was ist der Europarat und wo hat er seinen Sitz?',
      back: 'Der Europarat ist eine internationale Organisation zum Schutz der Menschenrechte, Demokratie und Rechtsstaatlichkeit. Sitz: Straßburg, Frankreich. Er ist KEIN Organ der Europäischen Union.',
    },
    {
      front: 'Was ist die EMRK?',
      back: 'Die Europäische Menschenrechtskonvention (EMRK) wurde 1950 vom Europarat verabschiedet. Sie garantiert grundlegende Menschenrechte. Der Europäische Gerichtshof für Menschenrechte (EGMR) in Straßburg wacht über ihre Einhaltung.',
    },
    {
      front: 'Was ist die WTO und was ist ihre Aufgabe?',
      back: 'Die WTO (World Trade Organization / Welthandelsorganisation) regelt den internationalen Handel und löst Handelsstreitigkeiten zwischen Mitgliedstaaten. Sitz: Genf, Schweiz.',
    },
    {
      front: 'Was ist die OSZE?',
      back: 'Die OSZE (Organisation für Sicherheit und Zusammenarbeit in Europa) ist die weltweit größte regionale Sicherheitsorganisation. Sie befasst sich mit Konfliktprävention, Krisenmanagement und Demokratieförderung. Sitz: Wien.',
    },
    {
      front: 'Was ist UNESCO und für welche Bereiche ist sie zuständig?',
      back: 'UNESCO (United Nations Educational, Scientific and Cultural Organization) ist eine UN-Sonderorganisation für Bildung, Wissenschaft, Kultur und Kommunikation. Sitz: Paris, Frankreich.',
    },
    {
      front: 'Was ist UNICEF und wofür steht die Abkürzung?',
      back: 'UNICEF (United Nations International Children\'s Emergency Fund) ist ein UN-Kinderhilfswerk, das sich weltweit für die Rechte und das Wohlergehen von Kindern einsetzt. Sitz: New York.',
    },
    {
      front: 'Wer ist seit Januar 2025 US-Präsident?',
      back: 'Donald Trump (Republikaner), der bei der Wahl im November 2024 gewann und am 20. Januar 2025 als 47. Präsident vereidigt wurde.',
    },
    {
      front: 'Was ist das Kyoto-Protokoll und wann wurde es verabschiedet?',
      back: 'Das Kyoto-Protokoll (1997) ist ein internationales Klimaschutzabkommen unter der UN, das verbindliche Ziele zur Reduktion von Treibhausgasemissionen für Industrieländer festlegt.',
    },
  ],
  questions: [
    {
      type: 'mc',
      prompt: 'Wie viele ständige Mitglieder hat der UN-Sicherheitsrat?',
      options: ['5', '10', '15', '7'],
      correct: [0],
      explanation: 'Es gibt 5 ständige Mitglieder mit Vetorecht: USA, Russland, China, Frankreich und das Vereinigte Königreich.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'In welchem Jahr wurde die UN gegründet?',
      options: ['1939', '1948', '1945', '1950'],
      correct: [2],
      explanation: 'Die UN wurde am 24. Oktober 1945 nach dem Ende des Zweiten Weltkriegs gegründet.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Wo befindet sich der Hauptsitz der Vereinten Nationen?',
      options: ['Washington D.C.', 'Genf', 'New York City', 'Brüssel'],
      correct: [2],
      explanation: 'Der Hauptsitz der UN liegt in New York City, USA.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welcher Staat ist KEIN ständiges Mitglied des UN-Sicherheitsrats?',
      options: ['Frankreich', 'Deutschland', 'Russland', 'China'],
      correct: [1],
      explanation: 'Deutschland ist kein ständiges Mitglied. Die P5 sind USA, Russland, China, Frankreich und das Vereinigte Königreich.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Wer ist aktueller UN-Generalsekretär (Stand 2026)?',
      options: ['Ban Ki-moon', 'Kofi Annan', 'António Guterres', 'Mark Rutte'],
      correct: [2],
      explanation: 'António Guterres aus Portugal ist seit dem 1. Januar 2017 UN-Generalsekretär.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Wie viele Mitgliedstaaten hat die NATO (Stand 2026)?',
      options: ['28', '30', '32', '35'],
      correct: [2],
      explanation: 'Die NATO hat 32 Mitgliedstaaten. Schweden trat 2024 als 32. Mitglied bei.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Wer ist aktueller NATO-Generalsekretär (Stand 2026)?',
      options: ['Jens Stoltenberg', 'Ursula von der Leyen', 'Mark Rutte', 'Charles Michel'],
      correct: [2],
      explanation: 'Mark Rutte (Niederlande) ist seit Oktober 2024 NATO-Generalsekretär. Er folgte Jens Stoltenberg.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Wann wurde die NATO gegründet?',
      options: ['1945', '1949', '1955', '1961'],
      correct: [1],
      explanation: 'Die NATO (North Atlantic Treaty Organization) wurde am 4. April 1949 mit dem Nordatlantikvertrag gegründet.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was regelt Artikel 5 des NATO-Vertrags?',
      options: [
        'Die Aufnahme neuer Mitglieder',
        'Den Verteidigungshaushalt der Mitglieder',
        'Die kollektive Beistandspflicht bei Angriff auf ein Mitglied',
        'Den Rückzug aus der NATO',
      ],
      correct: [2],
      explanation: 'Artikel 5 ist die Beistandsklausel: Ein Angriff auf ein Mitglied gilt als Angriff auf alle.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welche Länder gehören zur G7?',
      options: [
        'USA, Kanada, Deutschland, Frankreich, Italien, Japan, Vereinigtes Königreich',
        'USA, China, Deutschland, Frankreich, Indien, Japan, Brasilien',
        'USA, Kanada, Deutschland, Russland, Frankreich, Japan, Vereinigtes Königreich',
        'USA, Kanada, Deutschland, Australien, Frankreich, Japan, Vereinigtes Königreich',
      ],
      correct: [0],
      explanation: 'Die G7 besteht aus: USA, Kanada, Deutschland, Frankreich, Italien, Japan und dem Vereinigten Königreich.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Wie setzt sich die G20 zusammen?',
      options: [
        '19 führende Wirtschaftsnationen plus EU und Afrikanische Union',
        '20 Staaten ohne die EU',
        'nur die 7 größten Industriestaaten',
        'alle EU-Mitgliedstaaten',
      ],
      correct: [0],
      explanation: 'Die G20 besteht aus 19 führenden Wirtschaftsnationen plus der EU und (seit 2023) der Afrikanischen Union.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Wo hat die WHO ihren Sitz?',
      options: ['New York', 'Brüssel', 'Genf', 'Wien'],
      correct: [2],
      explanation: 'Die WHO (Weltgesundheitsorganisation) hat ihren Hauptsitz in Genf, Schweiz.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Für welchen Bereich ist die WHO zuständig?',
      options: ['Welthandel', 'Internationale Gesundheit', 'Währungsstabilität', 'Bildung und Kultur'],
      correct: [1],
      explanation: 'Die WHO (World Health Organization) ist die UN-Sonderorganisation für internationale Gesundheitsfragen.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Wo hat der Internationale Währungsfonds (IWF) seinen Sitz?',
      options: ['Genf', 'New York', 'Brüssel', 'Washington D.C.'],
      correct: [3],
      explanation: 'Der IWF hat seinen Sitz in Washington D.C., USA.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist die Hauptaufgabe des IWF?',
      options: [
        'Förderung von Bildung in Entwicklungsländern',
        'Überwachung des internationalen Währungssystems und Kreditvergabe',
        'Regulierung des internationalen Handels',
        'Koordination der Erdölproduktion',
      ],
      correct: [1],
      explanation: 'Der IWF überwacht das internationale Währungssystem und gewährt Kredite an Länder in Zahlungsbilanzschwierigkeiten.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Wo hat die Weltbank ihren Sitz?',
      options: ['Genf', 'New York', 'Washington D.C.', 'London'],
      correct: [2],
      explanation: 'Die Weltbank hat ihren Hauptsitz in Washington D.C., USA.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist das Hauptziel der Weltbank?',
      options: [
        'Bekämpfung der Inflation in Industrieländern',
        'Regulierung des Welthandels',
        'Armutsbekämpfung und Entwicklungsförderung durch Kredite',
        'Koordination der NATO-Streitkräfte',
      ],
      correct: [2],
      explanation: 'Die Weltbank vergibt Kredite und Zuschüsse an Entwicklungsländer zur Armutsbekämpfung und wirtschaftlichen Entwicklung.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Wo hat die OPEC ihren Sitz?',
      options: ['Riad', 'Abu Dhabi', 'Wien', 'Genf'],
      correct: [2],
      explanation: 'Die OPEC (Organisation erdölexportierender Länder) hat ihren Sitz in Wien, Österreich.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Wofür steht die Abkürzung OPEC?',
      options: [
        'Organization of Petroleum Exporting Countries',
        'Organization of Political and Economic Cooperation',
        'Office of Peace and Economic Control',
        'Organization of Pacific and European Countries',
      ],
      correct: [0],
      explanation: 'OPEC steht für "Organization of the Petroleum Exporting Countries" (Organisation erdölexportierender Länder).',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Wo hat der Europarat seinen Sitz?',
      options: ['Brüssel', 'Luxemburg', 'Straßburg', 'Wien'],
      correct: [2],
      explanation: 'Der Europarat hat seinen Sitz in Straßburg, Frankreich.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist die wichtigste Aufgabe des Europarats?',
      options: [
        'Koordination der EU-Wirtschaftspolitik',
        'Schutz von Menschenrechten, Demokratie und Rechtsstaatlichkeit',
        'Verwaltung des Schengen-Raums',
        'Leitung der NATO-Operationen',
      ],
      correct: [1],
      explanation: 'Der Europarat ist eine internationale Organisation zum Schutz der Menschenrechte, Demokratie und Rechtsstaatlichkeit.',
      difficulty: 2,
    },
    {
      type: 'truefalse',
      prompt: 'Der Europarat ist ein Organ der Europäischen Union.',
      options: ['Wahr', 'Falsch'],
      correct: [1],
      explanation: 'Falsch. Der Europarat ist eine eigenständige internationale Organisation und KEIN Organ der EU. Er hat 46 Mitgliedstaaten, die EU 27.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was ist die EMRK?',
      options: [
        'Europäischer Mechanismus zur Regulierung von Kapital',
        'Europäische Menschenrechtskonvention',
        'Europäische Militärische Rahmenkonvention',
        'Europäische Meeres- und Rohstoffkonvention',
      ],
      correct: [1],
      explanation: 'EMRK steht für Europäische Menschenrechtskonvention, verabschiedet 1950 vom Europarat.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welches Gericht wacht über die Einhaltung der EMRK?',
      options: [
        'Europäischer Gerichtshof (EuGH) in Luxemburg',
        'Internationaler Gerichtshof in Den Haag',
        'Europäischer Gerichtshof für Menschenrechte (EGMR) in Straßburg',
        'Bundesverfassungsgericht in Karlsruhe',
      ],
      correct: [2],
      explanation: 'Der Europäische Gerichtshof für Menschenrechte (EGMR) in Straßburg überwacht die Einhaltung der EMRK.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Was ist die Hauptaufgabe der WTO?',
      options: [
        'Förderung von Entwicklungsländern durch Kredite',
        'Regelung des internationalen Handels und Beilegung von Handelsstreitigkeiten',
        'Koordination der globalen Gesundheitspolitik',
        'Überwachung der Menschenrechte',
      ],
      correct: [1],
      explanation: 'Die WTO (Welthandelsorganisation) regelt den internationalen Handel und löst Handelsstreitigkeiten zwischen Mitgliedstaaten.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Wo hat die WTO ihren Sitz?',
      options: ['New York', 'Wien', 'Washington D.C.', 'Genf'],
      correct: [3],
      explanation: 'Die WTO (World Trade Organization) hat ihren Sitz in Genf, Schweiz.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Wofür steht OSZE?',
      options: [
        'Organisation für Sicherheit und Zusammenarbeit in Europa',
        'Osteuropäische Sicherheits- und Zolleinheit',
        'Organisation solidarischer Zusammenschlüsse Europas',
        'Ökonomische Sicherheitszone Europa',
      ],
      correct: [0],
      explanation: 'OSZE steht für "Organisation für Sicherheit und Zusammenarbeit in Europa". Sie ist die weltweit größte regionale Sicherheitsorganisation.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Wo hat die OSZE ihren Hauptsitz?',
      options: ['Brüssel', 'Straßburg', 'Wien', 'Genf'],
      correct: [2],
      explanation: 'Die OSZE hat ihren Hauptsitz in Wien, Österreich.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Für welche Bereiche ist die UNESCO zuständig?',
      options: [
        'Militär und Sicherheit',
        'Bildung, Wissenschaft, Kultur und Kommunikation',
        'Welthandel und Währung',
        'Gesundheit und Ernährung',
      ],
      correct: [1],
      explanation: 'UNESCO ist die UN-Sonderorganisation für Bildung (Education), Wissenschaft (Science), Kultur (Culture) und Kommunikation.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Wo hat die UNESCO ihren Sitz?',
      options: ['Genf', 'New York', 'London', 'Paris'],
      correct: [3],
      explanation: 'Die UNESCO hat ihren Hauptsitz in Paris, Frankreich.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Wer ist seit Januar 2025 Präsident der USA?',
      options: ['Joe Biden', 'Kamala Harris', 'Donald Trump', 'Ron DeSantis'],
      correct: [2],
      explanation: 'Donald Trump (Republikaner) wurde am 20. Januar 2025 als 47. US-Präsident vereidigt, nachdem er die Wahl im November 2024 gewann.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist UNICEF?',
      options: [
        'Eine UN-Organisation für Währungsfragen',
        'Ein UN-Kinderhilfswerk',
        'Eine NATO-Unterorganisation',
        'Ein europäisches Bildungsinstitut',
      ],
      correct: [1],
      explanation: 'UNICEF (United Nations International Children\'s Emergency Fund) ist das UN-Kinderhilfswerk, das sich für Rechte und Wohlergehen von Kindern einsetzt.',
      difficulty: 1,
    },
    {
      type: 'truefalse',
      prompt: 'Der IWF und die Weltbank haben beide ihren Sitz in Washington D.C.',
      options: ['Wahr', 'Falsch'],
      correct: [0],
      explanation: 'Wahr. Sowohl der Internationale Währungsfonds (IWF) als auch die Weltbank haben ihren Sitz in Washington D.C., USA.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welches der folgenden Länder ist KEIN Mitglied der G7?',
      options: ['Japan', 'Italien', 'China', 'Kanada'],
      correct: [2],
      explanation: 'China ist kein G7-Mitglied. Die G7 besteht aus USA, Kanada, Deutschland, Frankreich, Italien, Japan und dem Vereinigten Königreich.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'In welchem Jahr wurde das Kyoto-Protokoll verabschiedet?',
      options: ['1990', '1997', '2002', '2005'],
      correct: [1],
      explanation: 'Das Kyoto-Protokoll wurde 1997 verabschiedet und legte verbindliche Ziele zur Reduktion von Treibhausgasemissionen fest.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Wie viele Mitgliedstaaten hat die UN (Stand 2025)?',
      options: ['151', '167', '193', '206'],
      correct: [2],
      explanation: 'Die UN hat 193 Mitgliedstaaten. Nahezu alle anerkannten Staaten der Welt sind Mitglied.',
      difficulty: 2,
    },
    {
      type: 'truefalse',
      prompt: 'Russland ist ein ständiges Mitglied des UN-Sicherheitsrats mit Vetorecht.',
      options: ['Wahr', 'Falsch'],
      correct: [0],
      explanation: 'Wahr. Russland ist als Rechtsnachfolger der Sowjetunion eines der fünf ständigen Mitglieder (P5) des UN-Sicherheitsrats.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welche Organisation wurde 1945 gegründet, um den Weltfrieden zu sichern?',
      options: ['NATO', 'EU', 'Vereinte Nationen (UN)', 'OSZE'],
      correct: [2],
      explanation: 'Die Vereinten Nationen (UN) wurden 1945 mit dem primären Ziel gegründet, den Weltfrieden und die internationale Sicherheit zu wahren.',
      difficulty: 1,
    },
  ],
};

export default topic;
