import type { RawTopic } from '../types';

const topic: RawTopic = {
  slug: 'it-sicherheit',
  title: 'IT-Sicherheit & digitale Verwaltung',
  description: 'Datenschutz, Sicherheitsbegriffe und E-Government.',
  flashcards: [
    {
      front: 'Was sind die drei Schutzziele der IT-Sicherheit (CIA-Triade)?',
      back: 'Vertraulichkeit (Confidentiality), Integrität (Integrity) und Verfügbarkeit (Availability). Diese drei Ziele bilden das Grundgerüst der Informationssicherheit.',
    },
    {
      front: 'Was versteht man unter Vertraulichkeit in der IT-Sicherheit?',
      back: 'Vertraulichkeit bedeutet, dass Informationen nur von autorisierten Personen eingesehen werden können. Unbefugte dürfen keinen Zugriff auf schützenswerte Daten erhalten.',
    },
    {
      front: 'Was bedeutet Integrität als Schutzziel?',
      back: 'Integrität bedeutet, dass Daten vollständig und unverändert sind. Manipulationen oder unbeabsichtigte Veränderungen sollen erkannt und verhindert werden.',
    },
    {
      front: 'Was bedeutet Verfügbarkeit als Schutzziel?',
      back: 'Verfügbarkeit bedeutet, dass autorisierte Nutzer jederzeit auf Systeme und Daten zugreifen können, wenn sie diese benötigen. Ausfälle und Störungen sollen minimiert werden.',
    },
    {
      front: 'Was ist der Unterschied zwischen einem Virus und einem Wurm?',
      back: 'Ein Virus benötigt eine Wirtsdatei und verbreitet sich durch Ausführen infizierter Dateien. Ein Wurm ist eigenständig und verbreitet sich selbstständig über Netzwerke, ohne eine Wirtsdatei zu benötigen.',
    },
    {
      front: 'Was ist ein Trojaner (Trojanisches Pferd)?',
      back: 'Ein Trojaner ist Schadsoftware, die sich als nützliches Programm tarnt. Im Hintergrund führt er schädliche Aktionen aus, z. B. das Ausspionieren von Daten oder das Öffnen von Hintertüren.',
    },
    {
      front: 'Was ist Ransomware?',
      back: 'Ransomware ist Erpressungssoftware, die Daten auf dem befallenen System verschlüsselt und anschließend ein Lösegeld (englisch: ransom) für die Entschlüsselung fordert.',
    },
    {
      front: 'Was ist Phishing?',
      back: 'Phishing ist ein Angriff, bei dem Kriminelle gefälschte E-Mails oder Webseiten nutzen, um Nutzer zur Preisgabe vertraulicher Daten (Passwörter, Kreditkartendaten) zu verleiten.',
    },
    {
      front: 'Was ist Social Engineering?',
      back: 'Social Engineering bezeichnet die Manipulation von Menschen, um sie zur Preisgabe vertraulicher Informationen oder zur Ausführung bestimmter Handlungen zu bewegen, z. B. durch Vortäuschen einer falschen Identität.',
    },
    {
      front: 'Was ist der Unterschied zwischen symmetrischer und asymmetrischer Verschlüsselung?',
      back: 'Bei symmetrischer Verschlüsselung wird derselbe Schlüssel zum Ver- und Entschlüsseln verwendet (z. B. AES). Bei asymmetrischer Verschlüsselung gibt es ein Schlüsselpaar: einen öffentlichen Schlüssel (zum Verschlüsseln) und einen privaten Schlüssel (zum Entschlüsseln), z. B. RSA.',
    },
    {
      front: 'Wofür steht SSL/TLS und wofür wird es verwendet?',
      back: 'SSL (Secure Sockets Layer) und TLS (Transport Layer Security) sind Protokolle zur verschlüsselten Übertragung von Daten im Internet. TLS ist der Nachfolger von SSL. HTTPS verwendet TLS zur sicheren Kommunikation zwischen Browser und Webserver.',
    },
    {
      front: 'Was ist eine Firewall?',
      back: 'Eine Firewall ist ein Sicherheitssystem, das den Netzwerkverkehr überwacht und kontrolliert. Sie erlaubt oder blockiert Datenpakete anhand von Regeln, um unautorisierten Zugriff zu verhindern.',
    },
    {
      front: 'Was ist Zwei-Faktor-Authentifizierung (2FA)?',
      back: 'Bei der Zwei-Faktor-Authentifizierung wird die Identität eines Nutzers durch zwei unabhängige Faktoren geprüft, z. B. Passwort (Wissen) und ein Einmalcode per SMS oder App (Besitz). Sie erhöht die Sicherheit erheblich.',
    },
    {
      front: 'Was ist die DSGVO und seit wann gilt sie?',
      back: 'Die DSGVO (Datenschutz-Grundverordnung) ist eine EU-Verordnung, die den Umgang mit personenbezogenen Daten regelt. Sie gilt seit dem 25. Mai 2018 und ist in allen EU-Mitgliedstaaten unmittelbar anwendbar.',
    },
    {
      front: 'Was sind personenbezogene Daten laut DSGVO?',
      back: 'Personenbezogene Daten sind alle Informationen, die sich auf eine identifizierte oder identifizierbare natürliche Person beziehen, z. B. Name, Adresse, E-Mail-Adresse, IP-Adresse oder Gesundheitsdaten.',
    },
    {
      front: 'Was ist das BSI?',
      back: 'Das BSI ist das Bundesamt für Sicherheit in der Informationstechnik. Es ist die zentrale Cybersicherheitsbehörde des Bundes in Deutschland und berät Behörden, Unternehmen und Bürger zu IT-Sicherheitsthemen.',
    },
    {
      front: 'Was ist das Online-Zugangsgesetz (OZG)?',
      back: 'Das OZG verpflichtet Bund, Länder und Kommunen, ihre Verwaltungsleistungen digital anzubieten. Ziel ist es, Bürgerinnen und Bürgern sowie Unternehmen den Zugang zu Behördenleistungen über Online-Portale zu ermöglichen.',
    },
    {
      front: 'Was ist die eID-Funktion des Personalausweises?',
      back: 'Die eID (elektronische Identität) ist eine Funktion des deutschen Personalausweises, mit der Bürgerinnen und Bürger sich online gegenüber Behörden und Unternehmen eindeutig und sicher ausweisen können.',
    },
    {
      front: 'Was ist De-Mail?',
      back: 'De-Mail ist ein staatlich regulierter Dienst für den rechtsverbindlichen und vertraulichen elektronischen Nachrichtenversand in Deutschland. Er ermöglicht die nachweisbare Kommunikation zwischen Bürgern, Behörden und Unternehmen.',
    },
    {
      front: 'Was versteht man unter Datensparsamkeit?',
      back: 'Datensparsamkeit (auch Datenvermeidung) ist ein Grundsatz des Datenschutzes: Es sollen nur so viele personenbezogene Daten erhoben und verarbeitet werden, wie für den jeweiligen Zweck unbedingt erforderlich sind.',
    },
    {
      front: 'Was ist Spam?',
      back: 'Spam bezeichnet unerwünschte, massenhaft versendete elektronische Nachrichten, meist Werbung oder betrügerische Inhalte. Spam-Mails können auch Schadsoftware oder Phishing-Links enthalten.',
    },
    {
      front: 'Was ist Spyware?',
      back: 'Spyware ist Schadsoftware, die unbemerkt Informationen über den Nutzer sammelt und an Dritte überträgt, z. B. Surfverhalten, Tastatureingaben oder Passwörter.',
    },
  ],
  questions: [
    {
      type: 'mc',
      prompt: 'Wofür steht die Abkürzung DSGVO?',
      options: [
        'Datenschutz-Grundverordnung',
        'Datensicherheits-Grundverordnung',
        'Daten-Service-und-Gebührenverordnung',
        'Digitale-Sicherheits-Grundverordnung',
      ],
      correct: [0],
      explanation: 'DSGVO steht für Datenschutz-Grundverordnung der EU. Sie gilt seit dem 25. Mai 2018 und regelt den Umgang mit personenbezogenen Daten.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Seit wann gilt die Datenschutz-Grundverordnung (DSGVO) in der EU?',
      options: [
        '1. Januar 2016',
        '25. Mai 2018',
        '1. März 2020',
        '25. Mai 2020',
      ],
      correct: [1],
      explanation: 'Die DSGVO ist seit dem 25. Mai 2018 in allen EU-Mitgliedstaaten verbindlich anwendbar.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welche drei Schutzziele bilden die sogenannte CIA-Triade der IT-Sicherheit?',
      options: [
        'Kontrolle, Integrität, Anonymität',
        'Vertraulichkeit, Integrität, Verfügbarkeit',
        'Verschlüsselung, Identifizierung, Autorisierung',
        'Vertraulichkeit, Identität, Autorisierung',
      ],
      correct: [1],
      explanation: 'Die CIA-Triade besteht aus Vertraulichkeit (Confidentiality), Integrität (Integrity) und Verfügbarkeit (Availability).',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist die Aufgabe des BSI?',
      options: [
        'Bundesbehörde für Steuerliche Informatik',
        'Betrieb des Sicherheits-Intranets für Behörden',
        'Bundesamt für Sicherheit in der Informationstechnik',
        'Bundesstelle für Softwarelizenzen und IT-Infrastruktur',
      ],
      correct: [2],
      explanation: 'Das BSI ist das Bundesamt für Sicherheit in der Informationstechnik. Es ist die zentrale Cybersicherheitsbehörde des Bundes in Deutschland.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was versteht man unter Phishing?',
      options: [
        'Das Abfangen von Netzwerkpaketen zur Analyse',
        'Das Einschleusen von Schadsoftware über infizierte USB-Sticks',
        'Das Vortäuschen seriöser Kommunikation, um Nutzer zur Preisgabe vertraulicher Daten zu verleiten',
        'Das Überwachen von Mitarbeitercomputer durch die IT-Abteilung',
      ],
      correct: [2],
      explanation: 'Phishing bezeichnet den Versuch, durch gefälschte E-Mails oder Webseiten sensible Daten wie Passwörter oder Kreditkartennummern zu erschleichen.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was unterscheidet einen Computerwurm von einem Computervirus?',
      options: [
        'Ein Wurm verschlüsselt Dateien, ein Virus löscht sie',
        'Ein Wurm verbreitet sich selbstständig über Netzwerke, ein Virus benötigt eine Wirtsdatei',
        'Ein Virus verbreitet sich über das Internet, ein Wurm nur über lokale Netzwerke',
        'Ein Wurm ist harmloser als ein Virus',
      ],
      correct: [1],
      explanation: 'Ein Computerwurm ist eigenständig und verbreitet sich ohne Wirtsdatei über Netzwerke. Ein Virus hängt sich an vorhandene Dateien und benötigt deren Ausführung zur Verbreitung.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was ist Ransomware?',
      options: [
        'Software zum Wiederherstellen verlorener Daten',
        'Ein Antivirenprogramm für den öffentlichen Dienst',
        'Schadsoftware, die Daten verschlüsselt und Lösegeld fordert',
        'Ein Tool zur sicheren Dateiübertragung',
      ],
      correct: [2],
      explanation: 'Ransomware (Erpressungssoftware) verschlüsselt Daten auf dem Zielsystem und fordert anschließend ein Lösegeld (englisch: ransom) für die Entschlüsselung.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welches Protokoll wird genutzt, um eine verschlüsselte Verbindung zwischen Browser und Webserver herzustellen?',
      options: [
        'FTP',
        'SMTP',
        'TLS/SSL',
        'IMAP',
      ],
      correct: [2],
      explanation: 'TLS (Transport Layer Security), früher SSL, ist das Protokoll, das bei HTTPS-Verbindungen für die Verschlüsselung der Kommunikation zwischen Browser und Webserver sorgt.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was ist der Unterschied zwischen symmetrischer und asymmetrischer Verschlüsselung?',
      options: [
        'Symmetrische Verschlüsselung ist immer sicherer als asymmetrische',
        'Bei symmetrischer Verschlüsselung wird derselbe Schlüssel zum Ver- und Entschlüsseln genutzt, bei asymmetrischer ein Schlüsselpaar',
        'Asymmetrische Verschlüsselung verwendet nur einen Schlüssel, symmetrische zwei',
        'Symmetrische Verschlüsselung wird nur im Internet verwendet',
      ],
      correct: [1],
      explanation: 'Symmetrische Verschlüsselung (z. B. AES) nutzt einen gemeinsamen Schlüssel. Asymmetrische Verschlüsselung (z. B. RSA) nutzt ein Paar aus öffentlichem und privatem Schlüssel.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was ist eine Firewall?',
      options: [
        'Ein Programm zur Datensicherung',
        'Eine Hardwarekomponente zur Kühlung von Servern',
        'Ein System zur Überwachung und Filterung des Netzwerkverkehrs',
        'Ein verschlüsselter Datenspeicher',
      ],
      correct: [2],
      explanation: 'Eine Firewall überwacht den ein- und ausgehenden Netzwerkverkehr und entscheidet anhand von Regeln, welche Datenpakete erlaubt oder gesperrt werden.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist Social Engineering?',
      options: [
        'Die technische Analyse sozialer Netzwerke auf Sicherheitslücken',
        'Die Manipulation von Menschen zur Preisgabe vertraulicher Informationen',
        'Das Erstellen sicherer Passwörter mithilfe sozialer Kriterien',
        'Ein Verfahren zur Datenverschlüsselung in sozialen Einrichtungen',
      ],
      correct: [1],
      explanation: 'Beim Social Engineering nutzen Angreifer psychologische Tricks, um Menschen zu manipulieren und zur Herausgabe von Zugangsdaten oder anderen vertraulichen Informationen zu bewegen.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was versteht man unter der Zwei-Faktor-Authentifizierung (2FA)?',
      options: [
        'Die Verwendung von zwei verschiedenen Passwörtern',
        'Das Einloggen über zwei verschiedene Geräte gleichzeitig',
        'Die Identitätsprüfung durch zwei unabhängige Faktoren, z. B. Passwort und Einmalcode',
        'Ein Verfahren, bei dem zwei Personen einen Vorgang gemeinsam freigeben',
      ],
      correct: [2],
      explanation: 'Bei der 2FA werden zwei unabhängige Faktoren zur Identifizierung genutzt: z. B. etwas, das man weiß (Passwort), und etwas, das man besitzt (Smartphone mit Authenticator-App).',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist das Online-Zugangsgesetz (OZG)?',
      options: [
        'Ein Gesetz zur Regulierung von Online-Shops',
        'Eine EU-Verordnung zum Datenschutz im E-Commerce',
        'Ein Bundesgesetz, das Behörden zur digitalen Bereitstellung ihrer Verwaltungsleistungen verpflichtet',
        'Ein Gesetz zur Regelung der Internetnutzung in Schulen',
      ],
      correct: [2],
      explanation: 'Das OZG (Online-Zugangsgesetz) verpflichtet Bund, Länder und Kommunen, ihre Verwaltungsleistungen über Online-Portale zugänglich zu machen.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Wofür steht die eID-Funktion im deutschen Personalausweis?',
      options: [
        'Elektronische Identifikation zur sicheren Online-Authentifizierung',
        'Erweiterte Identitätsdaten für Behörden',
        'Elektronische Indexdatei für Verwaltungsvorgänge',
        'Einheitliche Identifikationsnummer für EU-Bürger',
      ],
      correct: [0],
      explanation: 'Die eID (elektronische Identität) ermöglicht es Bürgerinnen und Bürgern, sich online gegenüber Behörden und Unternehmen sicher und eindeutig auszuweisen.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was ist De-Mail?',
      options: [
        'Ein kostenloses E-Mail-Programm des Bundes',
        'Ein staatlich regulierter Dienst für rechtsverbindliche elektronische Kommunikation in Deutschland',
        'Eine verschlüsselte Messenger-App für Behörden',
        'Ein EU-weites System für digitale Behördenpost',
      ],
      correct: [1],
      explanation: 'De-Mail ist ein Dienst für den nachweisbaren und vertraulichen elektronischen Nachrichtenversand in Deutschland, der rechtliche Verbindlichkeit ähnlich wie ein Einschreiben bietet.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet der Grundsatz der Datensparsamkeit?',
      options: [
        'Daten sollen möglichst kostengünstig gespeichert werden',
        'Es sollen nur so viele personenbezogene Daten erhoben werden, wie für den Zweck unbedingt erforderlich',
        'Daten müssen nach spätestens einem Jahr gelöscht werden',
        'Behörden dürfen keine Daten ohne schriftliche Genehmigung speichern',
      ],
      correct: [1],
      explanation: 'Datensparsamkeit (auch Datenminimierung) ist ein Grundprinzip des Datenschutzes: Die Erhebung und Verarbeitung personenbezogener Daten ist auf das notwendige Minimum zu beschränken.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was sind personenbezogene Daten im Sinne der DSGVO?',
      options: [
        'Nur Name und Geburtsdatum einer Person',
        'Ausschließlich biometrische Daten wie Fingerabdrücke',
        'Alle Informationen, die sich auf eine identifizierte oder identifizierbare natürliche Person beziehen',
        'Daten, die nur von Behörden verarbeitet werden dürfen',
      ],
      correct: [2],
      explanation: 'Laut DSGVO sind personenbezogene Daten alle Informationen, die eine natürliche Person direkt oder indirekt identifizierbar machen, z. B. Name, IP-Adresse, E-Mail oder Standortdaten.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was ist ein Backup?',
      options: [
        'Eine Sicherheitskopie von Daten, um diese bei Verlust wiederherstellen zu können',
        'Ein Verfahren zur Verschlüsselung sensibler Daten',
        'Eine Software zum Schutz vor Schadsoftware',
        'Ein Protokoll zur sicheren Datenübertragung',
      ],
      correct: [0],
      explanation: 'Ein Backup ist eine Datensicherungskopie, die es ermöglicht, Daten nach einem Verlust (z. B. durch Ransomware, Hardware-Ausfall) wiederherzustellen. Regelmäßige Backups sind ein grundlegendes Sicherheitskonzept.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welche der folgenden Eigenschaften kennzeichnet ein sicheres Passwort?',
      options: [
        'Mindestens 6 Zeichen, nur Buchstaben',
        'Der eigene Geburtstag in Zahlen',
        'Mindestens 12 Zeichen mit Groß- und Kleinbuchstaben, Zahlen und Sonderzeichen',
        'Der Nutzername rückwärts geschrieben',
      ],
      correct: [2],
      explanation: 'Ein sicheres Passwort ist lang (mindestens 12 Zeichen) und kombiniert Groß- und Kleinbuchstaben, Zahlen sowie Sonderzeichen. Persönliche Daten wie Geburtsdaten sind zu vermeiden.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist Spyware?',
      options: [
        'Eine Software zur Fernwartung von Computern',
        'Schadsoftware, die unbemerkt Informationen über den Nutzer sammelt und weiterleitet',
        'Ein Überwachungsprogramm für Systemressourcen',
        'Eine App zum Schutz der Privatsphäre im Internet',
      ],
      correct: [1],
      explanation: 'Spyware ist Schadsoftware, die heimlich Nutzerdaten wie Tastatureingaben, Passwörter oder das Surfverhalten ausspioniert und an Dritte überträgt.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was versteht man unter HTTPS?',
      options: [
        'Ein E-Mail-Protokoll mit Spam-Schutz',
        'Eine Variante des HTTP-Protokolls, die Daten verschlüsselt überträgt',
        'Ein Netzwerkprotokoll zur Dateiübertragung',
        'Ein Sicherheitsstandard für WLAN-Netzwerke',
      ],
      correct: [1],
      explanation: 'HTTPS (Hypertext Transfer Protocol Secure) ist die verschlüsselte Version von HTTP. Die Verschlüsselung erfolgt über TLS und schützt die Daten zwischen Browser und Webserver.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welche Aufgabe hat ein Antivirenprogramm?',
      options: [
        'Es sichert Daten automatisch in der Cloud',
        'Es erkennt und entfernt Schadsoftware auf einem Computer',
        'Es filtert unerwünschte E-Mails aus dem Postfach',
        'Es verschlüsselt Dateien auf der Festplatte',
      ],
      correct: [1],
      explanation: 'Antivirenprogramme erkennen bekannte Schadsoftware (Viren, Trojaner, Würmer etc.) anhand von Signaturen oder Verhaltensanalysen und entfernen sie vom System.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist Spam?',
      options: [
        'Eine Methode zur Datenverschlüsselung',
        'Unerwünschte, massenhaft versendete elektronische Nachrichten',
        'Ein Angriff auf die Verfügbarkeit eines Webservers',
        'Ein Verfahren zur sicheren Nutzeridentifizierung',
      ],
      correct: [1],
      explanation: 'Spam bezeichnet unerwünschte E-Mails oder Nachrichten, die in großen Mengen versendet werden. Sie enthalten oft Werbung, Betrugsversuche oder Schadsoftware.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welches Schutzziel der IT-Sicherheit wird verletzt, wenn ein Server durch einen Angriff nicht mehr erreichbar ist?',
      options: [
        'Vertraulichkeit',
        'Integrität',
        'Verfügbarkeit',
        'Authentizität',
      ],
      correct: [2],
      explanation: 'Ein Angriff, der dazu führt, dass ein System nicht mehr erreichbar ist (z. B. ein DDoS-Angriff), verletzt das Schutzziel Verfügbarkeit.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was ist ein Trojaner in der IT-Sicherheit?',
      options: [
        'Eine Art Firewall für Netzwerke',
        'Ein Verschlüsselungsalgorithmus für sensible Daten',
        'Schadsoftware, die sich als nützliches Programm tarnt und im Hintergrund schädliche Aktionen ausführt',
        'Ein Protokoll zur sicheren Authentifizierung',
      ],
      correct: [2],
      explanation: 'Ein Trojaner (Trojanisches Pferd) tarnt sich als harmlose oder nützliche Software, führt jedoch im Hintergrund schädliche Funktionen aus, z. B. Datendiebstahl oder das Öffnen von Hintertüren.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist der öffentliche Schlüssel bei asymmetrischer Verschlüsselung?',
      options: [
        'Ein Schlüssel, der nur dem Empfänger bekannt ist und zum Entschlüsseln dient',
        'Ein frei verfügbarer Schlüssel, mit dem Nachrichten für den Empfänger verschlüsselt werden',
        'Ein Master-Schlüssel, der alle anderen Schlüssel verwaltet',
        'Ein Schlüssel, der täglich automatisch erneuert wird',
      ],
      correct: [1],
      explanation: 'Bei asymmetrischer Verschlüsselung ist der öffentliche Schlüssel frei verfügbar. Jeder kann ihn nutzen, um eine Nachricht für den Inhaber des passenden privaten Schlüssels zu verschlüsseln.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Welche Behörde ist in Deutschland zentral für Cybersicherheit zuständig?',
      options: [
        'Bundesnetzagentur (BNetzA)',
        'Bundesamt für Sicherheit in der Informationstechnik (BSI)',
        'Bundeskriminalamt (BKA)',
        'Bundesamt für Verfassungsschutz (BfV)',
      ],
      correct: [1],
      explanation: 'Das BSI (Bundesamt für Sicherheit in der Informationstechnik) ist die zentrale Cybersicherheitsbehörde Deutschlands. Es berät Behörden, Unternehmen und Bürger und setzt Sicherheitsstandards.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist die elektronische Akte (E-Akte) in der öffentlichen Verwaltung?',
      options: [
        'Eine verschlüsselte E-Mail-Kommunikation zwischen Behörden',
        'Die digitale Führung von Verwaltungsakten anstelle von Papierakten',
        'Ein Cloud-Dienst für Bürgerdaten',
        'Eine App zur Terminvereinbarung mit Behörden',
      ],
      correct: [1],
      explanation: 'Die E-Akte bezeichnet die vollständig digitale Führung von Verwaltungsakten. Sie ersetzt Papierakten und ermöglicht effizientere, orts- und zeitunabhängige Bearbeitung von Verwaltungsvorgängen.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Wann spricht man von einer Datenpanne im Sinne der DSGVO?',
      options: [
        'Wenn ein Computer abstürzt und Daten verloren gehen',
        'Wenn eine Sicherheitsverletzung zum unbeabsichtigten oder unrechtmäßigen Zugriff, Verlust oder zur Vernichtung personenbezogener Daten führt',
        'Wenn ein Mitarbeiter seine Zugangsdaten vergisst',
        'Wenn ein Antivirenprogramm einen Fehler meldet',
      ],
      correct: [1],
      explanation: 'Eine Datenpanne (Datenschutzverletzung) liegt laut DSGVO vor, wenn personenbezogene Daten unbeabsichtigt oder unrechtmäßig vernichtet, verloren, verändert oder unbefugt offengelegt werden. Solche Vorfälle sind der Aufsichtsbehörde zu melden.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Was versteht man unter einem DDoS-Angriff?',
      options: [
        'Das Entschlüsseln verschlüsselter Dateien ohne Schlüssel',
        'Das Einschleusen von Schadsoftware über E-Mail-Anhänge',
        'Einen Angriff, bei dem viele Computer gleichzeitig ein Zielsystem mit Anfragen überfluten, um es zum Ausfall zu bringen',
        'Das systematische Ausprobieren von Passwörtern',
      ],
      correct: [2],
      explanation: 'Ein DDoS-Angriff (Distributed Denial of Service) nutzt viele verteilte Systeme, um ein Ziel mit Anfragen zu überlasten und so die Verfügbarkeit des Dienstes zu unterbrechen.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Was ist das Prinzip der Datenvermeidung nach DSGVO?',
      options: [
        'Daten dürfen grundsätzlich nicht elektronisch gespeichert werden',
        'Personenbezogene Daten sollen so weit wie möglich anonymisiert oder gar nicht erst erhoben werden',
        'Behörden müssen alle Daten nach 30 Tagen löschen',
        'Nur öffentliche Stellen dürfen personenbezogene Daten speichern',
      ],
      correct: [1],
      explanation: 'Datenvermeidung und Datensparsamkeit bedeuten, dass personenbezogene Daten nur erhoben werden sollen, wenn dies für den jeweiligen Zweck notwendig ist, und dass Anonymisierung bevorzugt werden soll.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Welche Aussage zur eID-Funktion des deutschen Personalausweises ist korrekt?',
      options: [
        'Die eID ist nur für den Einsatz bei Bundesbehörden zugelassen',
        'Mit der eID kann man sich online gegenüber Behörden und Unternehmen authentifizieren',
        'Die eID erfordert immer eine PIN aus drei Ziffern',
        'Die eID-Funktion ist standardmäßig deaktiviert und kann nicht aktiviert werden',
      ],
      correct: [1],
      explanation: 'Die eID des deutschen Personalausweises ermöglicht die sichere Online-Identifizierung gegenüber Behörden und auch gegenüber privaten Unternehmen. Sie nutzt eine 6-stellige PIN.',
      difficulty: 2,
    },
    {
      type: 'truefalse',
      prompt: 'TLS ist der Nachfolger von SSL und wird für verschlüsselte HTTPS-Verbindungen genutzt.',
      options: ['Wahr', 'Falsch'],
      correct: [0],
      explanation: 'Diese Aussage ist korrekt. TLS (Transport Layer Security) hat SSL (Secure Sockets Layer) abgelöst und ist das heute verwendete Protokoll für die Verschlüsselung von HTTPS-Verbindungen.',
      difficulty: 1,
    },
    {
      type: 'truefalse',
      prompt: 'Ein Computervirus kann sich ohne menschliche Interaktion selbstständig über Netzwerke verbreiten.',
      options: ['Wahr', 'Falsch'],
      correct: [1],
      explanation: 'Falsch. Ein Computervirus benötigt eine Wirtsdatei und wird durch menschliche Interaktion (z. B. Ausführen einer infizierten Datei) verbreitet. Ein Wurm hingegen verbreitet sich selbstständig.',
      difficulty: 2,
    },
    {
      type: 'truefalse',
      prompt: 'Das Online-Zugangsgesetz (OZG) verpflichtet Behörden in Deutschland, ihre Verwaltungsleistungen digital anzubieten.',
      options: ['Wahr', 'Falsch'],
      correct: [0],
      explanation: 'Korrekt. Das OZG verpflichtet Bund, Länder und Kommunen zur Digitalisierung ihrer Verwaltungsleistungen und zur Bereitstellung über Online-Portale.',
      difficulty: 1,
    },
  ],
};

export default topic;
