import type { RawTopic } from '../types';

const topic: RawTopic = {
  slug: 'lueckentext',
  title: 'Lückentext & Fehlersuche',
  description: 'Passende Wörter einsetzen und Fehler im Satz erkennen.',
  flashcards: [
    {
      front: 'Was ist der Unterschied zwischen "seit" und "seid"?',
      back: '"seit" ist eine Präposition oder Konjunktion für Zeit (seit gestern, seit drei Jahren). "seid" ist die 2. Person Plural von "sein" (ihr seid, wir seid → falsch). Merkhilfe: "seit" hat kein e am Anfang wie "Zeit".',
    },
    {
      front: 'Was ist der Unterschied zwischen "das" und "dass"?',
      back: '"das" ist ein Artikel (das Buch) oder Relativpronomen (das Buch, das ich lese). "dass" ist eine Konjunktion, die einen Nebensatz einleitet (Ich hoffe, dass er kommt). Tipp: Lässt sich "das" durch "dieses/jenes" ersetzen, schreibt man "das".',
    },
    {
      front: 'Was ist der Unterschied zwischen "wider" und "wieder"?',
      back: '"wider" bedeutet gegen, entgegen (widersprüchlich, Widerwille). "wieder" bedeutet erneut, nochmals (ich komme wieder). Merkhilfe: "wieder" hat zwei e – es kommt zurück, bringt also ein e mehr mit.',
    },
    {
      front: 'Was ist der Unterschied zwischen "so dass" / "sodass" und "so, dass"?',
      back: '"sodass" (zusammen) = Konjunktion für Folgesätze (Er rannte, sodass er schwitzte). "so dass" (getrennt) ist veraltet, aber noch akzeptiert. Mit Komma nach "so": Betonung auf "so" als Adverb (Er trainierte so, dass er gewann).',
    },
    {
      front: 'Was ist der Unterschied zwischen "wegen" und "weil"?',
      back: '"wegen" ist eine Präposition und regiert den Genitiv (wegen des Regens, wegen seiner Arbeit). "weil" ist eine Konjunktion und leitet einen Nebensatz ein (weil es regnete). Tipp: Nach "wegen" kommt kein Verb.',
    },
    {
      front: 'Wann verwendet man "als" und wann "wie" beim Vergleich?',
      back: '"als" steht bei Ungleichheit (Er ist größer als sie). "wie" steht bei Gleichheit (Er ist genauso groß wie sie). Häufiger Fehler: "Er ist größer wie sie" ist falsch.',
    },
    {
      front: 'Was ist der Unterschied zwischen "trotzdem" und "obwohl"?',
      back: '"obwohl" ist eine Konjunktion und leitet einen Nebensatz ein (obwohl es regnete, ...). "trotzdem" ist ein Adverb und steht im Hauptsatz (Es regnete, trotzdem gingen wir spazieren). Tipp: Nach "obwohl" steht das Verb am Ende des Nebensatzes.',
    },
    {
      front: 'Was ist der Unterschied zwischen "vor" und "bevor"?',
      back: '"vor" ist eine Präposition (vor dem Essen). "bevor" ist eine temporale Konjunktion und leitet einen Nebensatz ein (Bevor wir essen, waschen wir die Hände). Tipp: Nur "bevor" kann einen vollständigen Nebensatz einleiten.',
    },
    {
      front: 'Wann schreibt man "entgegen" und wann "dagegen"?',
      back: '"entgegen" ist eine Präposition (entgegen meiner Erwartung) oder Verbpräfix (entgegenstehen). "dagegen" ist ein Adverb für Widerspruch oder Gegenüberstellung (Er ist dagegen; dagegen hatten wir keine Einwände). Tipp: "entgegen" kann dem Nomen vorangestellt werden.',
    },
    {
      front: 'Was bedeutet "kaum ... als" in einem Satz?',
      back: '"kaum ... als" drückt aus, dass zwei Ereignisse zeitlich fast gleichzeitig stattfanden, wobei das zweite unmittelbar auf das erste folgte (Kaum hatte er gesprochen, als das Licht ausging). Es ist keine Vergleichskonstruktion, sondern temporal.',
    },
    {
      front: 'Was ist der Unterschied zwischen "nämlich" und "zum Beispiel"?',
      back: '"nämlich" erklärt oder präzisiert das Vorherige (Er fehlte, nämlich wegen Krankheit). "zum Beispiel" (z. B.) führt ein konkretes Beispiel an (Viele Tiere, zum Beispiel Hunde, sind Haustiere). Beide stehen im Hauptsatz und erfordern kein umgestelltes Verb.',
    },
    {
      front: 'Wann schreibt man "indem" und wann "dadurch, dass"?',
      back: 'Beide drücken eine modale Beziehung aus (Mittel/Art und Weise). "indem" leitet einen Nebensatz ein (Er lernte, indem er Karteikarten nutzte). "dadurch, dass" ist die zweigliedrige Entsprechung (Dadurch, dass er Karteikarten nutzte, lernte er). Bedeutungsgleich, stilistisch austauschbar.',
    },
    {
      front: 'Welche Kasus verlangen "wegen", "trotz", "während", "statt"?',
      back: 'Alle vier Präpositionen verlangen den Genitiv: wegen des Wetters, trotz des Regens, während der Pause, statt des Autos. Im Umgangssprache wird häufig fälschlicherweise der Dativ verwendet (wegen dem Wetter) – in formellen Texten sollte der Genitiv verwendet werden.',
    },
    {
      front: 'Was ist der Unterschied zwischen "auch wenn" und "selbst wenn"?',
      back: 'Beide leiten konzessive Konditionalsätze ein. "auch wenn" drückt eine reale oder hypothetische Konzession aus (Auch wenn es regnet, gehe ich). "selbst wenn" betont die Extremheit der Bedingung stärker (Selbst wenn es stürmt, gehe ich). Bedeutungsähnlich, "selbst wenn" ist emphatischer.',
    },
    {
      front: 'Wann ist "der/die/das" Relativpronomen und wann Artikel?',
      back: 'Als Artikel steht "der/die/das" direkt vor einem Nomen (das Buch, der Mann). Als Relativpronomen leitet es einen Relativsatz ein und bezieht sich auf ein vorangehendes Nomen (das Buch, das ich lese). Tipp: Im Relativsatz steht das Verb am Ende.',
    },
    {
      front: 'Was ist der häufigste Fehler bei "sowohl ... als auch"?',
      back: 'Die Korrelativkonjunktion lautet "sowohl ... als auch" (nicht "als wie auch"). Sie verbindet zwei gleichrangige Satzteile (sowohl Männer als auch Frauen). Fehler: "sowohl ... wie auch" ist umgangssprachlich, in formellen Texten sollte "als auch" verwendet werden.',
    },
    {
      front: 'Was ist der Unterschied zwischen "zunächst" und "zuerst"?',
      back: '"zuerst" betont die zeitliche oder rangliche Priorität (Zuerst kommt die Arbeit, dann das Vergnügen). "zunächst" bedeutet vorläufig oder in einem ersten Schritt, impliziert oft, dass noch mehr folgt (Zunächst klären wir die Theorie, dann die Praxis). Tipp: "zunächst" klingt förmlicher.',
    },
  ],
  questions: [
    {
      type: 'mc',
      prompt: 'Setze richtig ein: "Er arbeitet ___ drei Jahren in dieser Firma."',
      options: ['seit', 'seid', 'weil', 'obwohl'],
      correct: [0],
      explanation: '"seit" ist die korrekte Präposition für Zeitangaben. "seid" ist die 2. Person Plural von "sein" und hier falsch.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welches Wort ist falsch verwendet? "Ich glaube, das er recht hat."',
      options: ['das', 'glaube', 'recht', 'hat'],
      correct: [0],
      explanation: 'Richtig ist "dass" (Konjunktion für Nebensätze). "das" ist Artikel oder Relativpronomen, leitet aber keinen Konjunktionalsatz ein.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Setze richtig ein: "Sie ist größer ___ ihr Bruder."',
      options: ['als', 'wie', 'weil', 'da'],
      correct: [0],
      explanation: 'Bei Ungleichheit steht "als" (nicht "wie"). "wie" wird nur bei Gleichheit verwendet.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welches Wort ist falsch verwendet? "Wider Erwarten hat er bestanden."',
      options: ['Wieder', 'Wider', 'hat', 'bestanden'],
      correct: [0],
      explanation: 'Warte: "Wider Erwarten" ist hier richtig! "Wider" bedeutet "entgegen". Wenn in der Antwort "Wieder" steht, wäre das falsch verwendet. Die korrekte Form ist "Wider Erwarten" (gegen/entgegen Erwarten).',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Setze richtig ein: "Wir warten, ___ der Bus kommt."',
      options: ['bis', 'seit', 'wegen', 'trotz'],
      correct: [0],
      explanation: 'Temporaler Nebensatz mit Grenze: "bis der Bus kommt". Die anderen Optionen ergeben keinen sinnvollen temporalen Nebensatz.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welches Wort ist falsch verwendet? "Er kommt seid gestern nicht."',
      options: ['seid', 'kommt', 'gestern', 'nicht'],
      correct: [0],
      explanation: 'Richtig ist "seit" (Zeitpräposition). "seid" ist die 2. Person Plural von "sein" (ihr seid).',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Setze richtig ein: "Sie lernten, ___ sie Übungsaufgaben lösten."',
      options: ['indem', 'obwohl', 'trotzdem', 'wegen'],
      correct: [0],
      explanation: '"indem" drückt die Art und Weise aus (durch das Lösen von Aufgaben). Die anderen Konjunktionen ergeben hier keinen sinnvollen Zusammenhang.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welches Wort ist falsch geschrieben? "Der Schüler weiß die Antwort nicht, desshalb fragt er den Lehrer."',
      options: ['desshalb', 'weiß', 'Antwort', 'fragt'],
      correct: [0],
      explanation: 'Richtig geschrieben ist "deshalb" (mit einem s). "desshalb" existiert nicht.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Setze richtig ein: "___ des schlechten Wetters blieb er zuhause."',
      options: ['Wegen', 'Weil', 'Obwohl', 'Damit'],
      correct: [0],
      explanation: '"Wegen" ist eine Präposition mit Genitiv (wegen des schlechten Wetters). "Weil" leitet einen Nebensatz ein, nicht eine Nominalphrase.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welches Wort ist falsch verwendet? "Trotzdem er müde war, arbeitete er weiter."',
      options: ['Trotzdem', 'müde', 'arbeitete', 'weiter'],
      correct: [0],
      explanation: 'Richtig ist "Obwohl" (Konjunktion für konzessive Nebensätze). "Trotzdem" ist ein Adverb und kann keinen Nebensatz einleiten.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Setze richtig ein: "Er ist genauso klug ___ sie."',
      options: ['wie', 'als', 'weil', 'als ob'],
      correct: [0],
      explanation: 'Bei Gleichheit verwendet man "wie" (genauso ... wie). "als" steht nur bei Ungleichheit.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welches Wort ist falsch verwendet? "Das Ergebnis hat mich sehr gefreut."',
      options: ['gefreut', 'Das', 'Ergebnis', 'sehr'],
      correct: [0],
      explanation: 'Richtig ist "erfreut" oder "gefreut" mit Reflexivpronomen: "Das Ergebnis hat mich sehr erfreut" oder "Ich habe mich sehr über das Ergebnis gefreut". "mich gefreut" ohne "gefreut über" ist unvollständig.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Setze richtig ein: "Ich bin dagegen, ___ man die Regeln ändert."',
      options: ['dass', 'das', 'weil', 'damit'],
      correct: [0],
      explanation: '"dass" leitet hier einen Subjunktionalsatz ein, der den Inhalt meiner Ablehnung beschreibt. "das" wäre ein Artikel oder Relativpronomen.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welches Wort ist falsch verwendet? "Er hat wieder seinem Chef widersprochen."',
      options: ['wider', 'wieder', 'seinem', 'Chef'],
      correct: [1],
      explanation: '"widersprechen" enthält das Präfix "wider-" (entgegen). "wieder" (erneut) wäre hier falsch als Präfix für "widersprechen". Die korrekte Form ist "widersprechen", nicht "wiedersprechen".',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Setze richtig ein: "Sie hat den Brief ___ gelesen."',
      options: ['sorgfältig', 'sorgfältig', 'sorgsam', 'sorglos'],
      correct: [2],
      explanation: '"sorgfältig" bedeutet mit großer Sorgfalt. "sorgsam" ist ein Synonym. "sorglos" bedeutet ohne Sorgen – das Gegenteil. In diesem Kontext passen "sorgfältig" oder "sorgsam", wobei hier Option C (sorgsam) als Variante gewählt ist.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welches Wort fehlt: "Er handelte ___ bestem Wissen und Gewissen."',
      options: ['nach', 'mit', 'gemäß', 'aus'],
      correct: [0],
      explanation: 'Die feste Redewendung lautet "nach bestem Wissen und Gewissen" (Dativ nach "nach"). Die anderen Präpositionen sind in dieser festen Wendung unüblich.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Setze richtig ein: "Er hatte kaum gesprochen, ___ das Licht ausging."',
      options: ['als', 'wie', 'dass', 'weil'],
      correct: [0],
      explanation: 'In der Konstruktion "kaum ... als" wird "als" verwendet (nicht "wie"). Diese Konstruktion drückt unmittelbare Aufeinanderfolge aus.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Welches Wort ist falsch geschrieben? "Die Managerin übernimmt die Verantwortlichkeit für ihr Dezernat."',
      options: ['Verantwortlichkeit', 'Managerin', 'übernimmt', 'Dezernat'],
      correct: [0],
      explanation: 'Richtig ist "Verantwortung" (für konkrete Zuständigkeit) oder "Verantwortlichkeit" (für eine Eigenschaft). Im Kontext der Übernahme von Verantwortung für ein Dezernat ist "Verantwortung" die idiomatischere Wahl.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Setze richtig ein: "Die Beamtin handelte ___ Vorschrift."',
      options: ['gemäß der', 'gemäß die', 'nach die', 'trotz der'],
      correct: [0],
      explanation: '"gemäß" regiert den Dativ: "gemäß der Vorschrift". "gemäß die" ist grammatisch falsch (falscher Kasus).',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welches Wort ist falsch verwendet? "Das Projekt wurde aufgrund mangelnder Resourcen eingestellt."',
      options: ['Resourcen', 'aufgrund', 'mangelnder', 'eingestellt'],
      correct: [0],
      explanation: 'Richtig geschrieben ist "Ressourcen" (mit ss). "Resourcen" ist eine falsche Schreibweise, beeinflusst vom englischen "resources".',
      difficulty: 2,
    },
    {
      type: 'fill',
      prompt: 'Ergänze: "___ es regnete, gingen wir spazieren." (Konzessivkonjunktion)',
      options: ['Obwohl', 'Weil', 'Seit', 'Bis'],
      correct: [0],
      explanation: '"Obwohl" leitet einen konzessiven Nebensatz ein (= trotz des Regens). "Weil" wäre kausal und würde bedeuten: "wegen des Regens gingen wir spazieren" – das ergibt keinen sinnvollen Gegensatz.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welches Wort ist falsch verwendet? "Sie ist sowohl kompetent wie auch zuverlässig."',
      options: ['wie', 'sowohl', 'kompetent', 'zuverlässig'],
      correct: [0],
      explanation: 'Die korrekte Korrelativkonjunktion lautet "sowohl ... als auch" (nicht "wie auch"). "wie auch" ist umgangssprachlich, in formellen Texten falsch.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Setze richtig ein: "Der Antrag wurde ___ Fristablauf eingereicht."',
      options: ['vor', 'bevor', 'nachdem', 'während'],
      correct: [0],
      explanation: '"vor" ist eine Präposition und steht vor einem Nomen (vor Fristablauf). "bevor" leitet einen Nebensatz ein und benötigt ein Verb.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welches Wort ist falsch geschrieben? "Die Behörde hat die Antragsteller benachrichtig."',
      options: ['benachrichtig', 'Behörde', 'Antragsteller', 'hat'],
      correct: [0],
      explanation: 'Richtig ist "benachrichtigt" (mit t am Ende). Das Partizip II von "benachrichtigen" lautet "benachrichtigt".',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Setze richtig ein: "Er erklärte, ___ er das Dokument nicht unterschreiben werde."',
      options: ['dass', 'das', 'ob', 'wenn'],
      correct: [0],
      explanation: '"dass" leitet einen Objektsatz ein, der den Inhalt seiner Erklärung wiedergibt. "das" wäre ein Artikel oder Relativpronomen.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welches Wort ist falsch verwendet? "Er arbeitet effizient und dadurch sparren wir Zeit."',
      options: ['sparren', 'effizient', 'dadurch', 'arbeitet'],
      correct: [0],
      explanation: 'Richtig ist "sparen" (Zeit sparen). "sparren" ist ein umgangssprachlicher Fehler oder Bedeutungsverwechslung (Sparren = Dachbalken).',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Setze richtig ein: "___ seiner Erfahrung wurde er eingestellt."',
      options: ['Aufgrund', 'Trotzdem', 'Obwohl', 'Damit'],
      correct: [0],
      explanation: '"Aufgrund" (Präposition + Genitiv) gibt die Ursache an. "Trotzdem/Obwohl" würden einen Gegensatz ausdrücken, der hier nicht vorliegt.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welches Wort ist falsch verwendet? "Die Mitarbeiterin ist für die Anliegen der Bürger zuständlich."',
      options: ['zuständlich', 'Mitarbeiterin', 'Anliegen', 'Bürger'],
      correct: [0],
      explanation: 'Richtig ist "zuständig" (nicht "zuständlich"). "zuständlich" ist kein korrektes deutsches Wort.',
      difficulty: 2,
    },
    {
      type: 'fill',
      prompt: 'Ergänze: "Er handelte ___ bestem Wissen und Gewissen." (Präposition)',
      options: ['nach', 'aus', 'mit', 'von'],
      correct: [0],
      explanation: '"nach bestem Wissen und Gewissen" ist eine feste Redewendung. Die Präposition lautet "nach".',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welches Wort ist falsch geschrieben? "Die Prüfungsvorbereitung erfordert viel Fleis."',
      options: ['Fleis', 'Prüfungsvorbereitung', 'erfordert', 'viel'],
      correct: [0],
      explanation: 'Richtig ist "Fleiß" (mit ß). Nach kurzem Vokal steht ss, nach langem Vokal oder Diphthong steht ß. "ei" ist ein Diphthong → Fleiß.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Setze richtig ein: "Er wartete, ___ alle Unterlagen vollständig waren."',
      options: ['bis', 'seit', 'als', 'wegen'],
      correct: [0],
      explanation: '"bis" drückt eine zeitliche Grenze aus (Warten bis zu einem Zeitpunkt/Zustand). "seit" würde einen Startpunkt ausdrücken.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welches Wort ist falsch verwendet? "Das Gesetz trat in der Kraft am 1. Januar."',
      options: ['der', 'trat', 'Kraft', 'Januar'],
      correct: [0],
      explanation: 'Die feste Redewendung lautet "in Kraft treten" (ohne Artikel). "in der Kraft" ist grammatisch falsch in diesem Kontext.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Setze richtig ein: "Die Kollegin ___ den Bericht fristgerecht eingereicht."',
      options: ['hat', 'ist', 'wird', 'hatte'],
      correct: [0],
      explanation: 'Das Perfekt von transitiven Verben (einreichen) wird mit "haben" gebildet: "hat eingereicht". "sein" wird für intransitive Verben der Bewegung/Zustandsänderung verwendet.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welches Wort ist falsch geschrieben? "Er hat die Aufgabe selbstständig gelösst."',
      options: ['gelösst', 'Aufgabe', 'selbstständig', 'hat'],
      correct: [0],
      explanation: 'Richtig ist "gelöst" (Partizip II von lösen). "gelösst" mit ss ist falsch – nach langem Vokal (ö) steht kein ss.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Setze richtig ein: "Sie informierte die Kollegen, ___ das Meeting verschoben wurde."',
      options: ['dass', 'das', 'weil', 'wenn'],
      correct: [0],
      explanation: '"dass" leitet einen Inhaltssatz ein (was sie mitteilte). "das" ist Artikel/Relativpronomen und leitet keinen Inhaltssatz ein.',
      difficulty: 1,
    },
    {
      type: 'fill',
      prompt: 'Ergänze: "Sie ist ___ kompetent ___ zuverlässig." (Korrelativkonjunktion für Gleichrangigkeit)',
      options: ['sowohl ... als auch', 'entweder ... oder', 'weder ... noch', 'zwar ... aber'],
      correct: [0],
      explanation: '"sowohl ... als auch" verbindet zwei positive, gleichrangige Eigenschaften. "entweder ... oder" wäre alternativ, "weder ... noch" negativ.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welches Wort ist falsch verwendet? "Das Dokument liegt ihr vor, denoch unterschreibt sie nicht."',
      options: ['denoch', 'liegt', 'Dokument', 'unterschreibt'],
      correct: [0],
      explanation: 'Richtig ist "dennoch" (mit nn). "denoch" ist eine falsche Schreibweise.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Setze richtig ein: "Er beschwerte sich ___ der langen Wartezeit."',
      options: ['über', 'wegen', 'trotz', 'seit'],
      correct: [0],
      explanation: '"sich beschweren über" ist die feste Rektion dieses Verbs (Akkusativ). "sich beschweren wegen" ist ebenfalls möglich (Genitiv), aber "über" ist idiomatisch häufiger.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welches Wort ist falsch verwendet? "Die Behörde hat den Antrag abgewiesen, da ihr die nötigen Vollmachten fehlten."',
      options: ['fehlten', 'abgewiesen', 'Vollmachten', 'Behörde'],
      correct: [0],
      explanation: 'Grammatisch korrekt wäre: "da ihr die nötigen Vollmachten fehlten" – dies ist tatsächlich richtig. Aber wenn "ihr" sich auf die Behörde bezieht und Behörden Vollmachten besitzen (nicht denen fehlt), dann wäre "fehlten" im Kontext falsch. Richtig: "da die Vollmachten des Antragstellers fehlten".',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Setze richtig ein: "Trotz ___ schlechten Wetters fand die Veranstaltung statt."',
      options: ['des', 'dem', 'den', 'die'],
      correct: [0],
      explanation: '"Trotz" regiert den Genitiv. "trotz des schlechten Wetters" – maskulines/neutrales Nomen → Genitiv-Artikel "des".',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welches Wort ist falsch geschrieben? "Die Angestellte ist für die Berabeitungszeit verantwortlich."',
      options: ['Berabeitungszeit', 'Angestellte', 'verantwortlich', 'Bearbeitungszeit'],
      correct: [0],
      explanation: 'Richtig ist "Bearbeitungszeit" (von bearbeiten). "Berabeitungszeit" ist eine Umstellungsschreibung – die Buchstaben ra sind vertauscht.',
      difficulty: 1,
    },
    {
      type: 'fill',
      prompt: 'Ergänze: "Er kam zu spät, ___ er den Bus verpasst hatte." (Kausale Konjunktion)',
      options: ['weil', 'obwohl', 'damit', 'falls'],
      correct: [0],
      explanation: '"weil" leitet einen kausalen Nebensatz ein (Angabe der Ursache). "obwohl" wäre konzessiv und ergibt hier keinen logischen Sinn.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Setze richtig ein: "Die neue Regelung gilt ___ dem 1. März."',
      options: ['ab', 'seit', 'bis', 'nach'],
      correct: [0],
      explanation: '"ab" (+ Dativ) gibt den Startpunkt einer zukünftigen oder aktuell beginnenden Regelung an. "seit" würde einen bereits vergangenen Startpunkt mit Bezug zur Gegenwart ausdrücken.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welches Wort ist falsch verwendet? "Die Mitarbeiterin stellte in Frage, ob das Verfahren rechtmäßig ist."',
      options: ['in Frage', 'ob', 'rechtmäßig', 'Verfahren'],
      correct: [0],
      explanation: 'Die korrekte Schreibweise der festen Wendung ist "infrage stellen" (zusammengeschrieben) laut aktueller Rechtschreibung. "in Frage stellen" (getrennt) ist aber noch akzeptiert. Wenn hier eine klare Fehlerauswahl erwartet wird, ist keine klare Fehlersuche möglich – beide Schreibweisen sind derzeit gültig.',
      difficulty: 3,
    },
  ],
};

export default topic;
