import type { RawTopic } from '../types';

const topic: RawTopic = {
  slug: 'netzwerke-datenbanken',
  title: 'Netzwerke & Datenbanken',
  description: 'Netzwerkgrundlagen, Protokolle und relationale Datenbanken.',
  flashcards: [
    {
      front: 'Was bedeutet LAN?',
      back: 'LAN steht für Local Area Network – ein lokales Netzwerk, das Computer in einem begrenzten geografischen Bereich (z. B. Bürogebäude) verbindet.',
    },
    {
      front: 'Was bedeutet WAN?',
      back: 'WAN steht für Wide Area Network – ein Weitverkehrsnetz, das geografisch weit entfernte Standorte verbindet, z. B. das Internet.',
    },
    {
      front: 'Was ist eine IP-Adresse?',
      back: 'Eine IP-Adresse ist eine eindeutige numerische Adresse, die Geräten in einem Netzwerk zugewiesen wird. IPv4 verwendet 32 Bit (z. B. 192.168.1.1), IPv6 verwendet 128 Bit.',
    },
    {
      front: 'Was ist eine MAC-Adresse?',
      back: 'Eine MAC-Adresse (Media Access Control) ist eine weltweit eindeutige Hardware-Adresse einer Netzwerkkarte, bestehend aus 48 Bit (6 Byte) in hexadezimaler Schreibweise.',
    },
    {
      front: 'Was ist der Unterschied zwischen Router und Switch?',
      back: 'Ein Router verbindet verschiedene Netzwerke und leitet Datenpakete anhand von IP-Adressen weiter. Ein Switch verbindet Geräte innerhalb eines Netzwerks und leitet Daten anhand von MAC-Adressen weiter.',
    },
    {
      front: 'Was ist ein Hub?',
      back: 'Ein Hub ist ein einfaches Netzwerkgerät, das Datenpakete an alle angeschlossenen Geräte sendet (Broadcast). Er gilt als veraltet und wurde weitgehend durch Switches ersetzt.',
    },
    {
      front: 'Was ist DNS?',
      back: 'DNS (Domain Name System) ist ein Dienst zur Namensauflösung: Es übersetzt Domainnamen wie www.example.com in IP-Adressen, damit Computer miteinander kommunizieren können.',
    },
    {
      front: 'Was ist DHCP?',
      back: 'DHCP (Dynamic Host Configuration Protocol) weist Netzwerkgeräten automatisch IP-Adressen und weitere Netzwerkkonfigurationen (Gateway, DNS) zu.',
    },
    {
      front: 'Was ist das OSI-Modell?',
      back: 'Das OSI-Modell (Open Systems Interconnection) beschreibt die Kommunikation in Netzwerken in 7 Schichten: Bitübertragung, Sicherung, Vermittlung, Transport, Sitzung, Darstellung, Anwendung.',
    },
    {
      front: 'Was ist TCP/IP?',
      back: 'TCP/IP ist das grundlegende Protokollsystem des Internets. TCP (Transmission Control Protocol) sorgt für zuverlässige, geordnete Datenübertragung; IP (Internet Protocol) adressiert und leitet Pakete.',
    },
    {
      front: 'Was ist ein Primärschlüssel in einer Datenbank?',
      back: 'Ein Primärschlüssel (Primary Key) ist ein eindeutiges Attribut oder eine Kombination von Attributen, das/die jeden Datensatz in einer Tabelle eindeutig identifiziert. Er darf nicht NULL sein.',
    },
    {
      front: 'Was ist ein Fremdschlüssel in einer Datenbank?',
      back: 'Ein Fremdschlüssel (Foreign Key) ist ein Attribut in einer Tabelle, das auf den Primärschlüssel einer anderen Tabelle verweist und so eine Beziehung zwischen Tabellen herstellt.',
    },
    {
      front: 'Was bedeutet SQL?',
      back: 'SQL (Structured Query Language) ist die standardisierte Abfragesprache für relationale Datenbanken. Mit SQL können Daten abgefragt (SELECT), eingefügt (INSERT), geändert (UPDATE) und gelöscht (DELETE) werden.',
    },
    {
      front: 'Was ist Normalisierung in Datenbanken?',
      back: 'Normalisierung ist ein Prozess, der Datenbankstrukturen optimiert, um Redundanzen zu vermeiden und Datenintegrität zu gewährleisten. Sie erfolgt in mehreren Normalformen (1NF, 2NF, 3NF usw.).',
    },
    {
      front: 'Was ist ein ER-Modell?',
      back: 'Das ER-Modell (Entity-Relationship-Modell) ist eine grafische Darstellungsmethode für Datenbankstrukturen. Es zeigt Entitäten (Objekte), deren Attribute und die Beziehungen zwischen ihnen.',
    },
    {
      front: 'Was ist NoSQL?',
      back: 'NoSQL bezeichnet nicht-relationale Datenbanksysteme, die keine festen Tabellenschemata verwenden. Sie eignen sich für große, unstrukturierte Datenmengen (z. B. MongoDB, Redis, Cassandra).',
    },
    {
      front: 'Was ist eine Firewall?',
      back: 'Eine Firewall ist ein Sicherheitssystem, das den Netzwerkverkehr anhand von Regeln überwacht und kontrolliert. Sie schützt Netzwerke vor unerlaubtem Zugriff.',
    },
    {
      front: 'Was ist Bandbreite?',
      back: 'Bandbreite beschreibt die maximale Datenmenge, die pro Zeiteinheit über eine Netzwerkverbindung übertragen werden kann. Sie wird in Bit pro Sekunde (bps, Mbps, Gbps) angegeben.',
    },
    {
      front: 'Was ist das HTTP-Protokoll?',
      back: 'HTTP (Hypertext Transfer Protocol) ist das Protokoll zur Übertragung von Webseiten im Internet. HTTPS ist die verschlüsselte Variante und verwendet TLS/SSL zur Absicherung.',
    },
    {
      front: 'Was ist FTP?',
      back: 'FTP (File Transfer Protocol) ist ein Protokoll zur Übertragung von Dateien zwischen Client und Server über ein Netzwerk. Es verwendet standardmäßig Port 21.',
    },
    {
      front: 'Was ist SMTP?',
      back: 'SMTP (Simple Mail Transfer Protocol) ist das Standardprotokoll zum Versenden von E-Mails zwischen Mailservern. Es verwendet standardmäßig Port 25 (oder 587 für verschlüsselte Übertragung).',
    },
    {
      front: 'Was ist ein DBMS?',
      back: 'Ein DBMS (Datenbank-Management-System) ist eine Software zur Verwaltung von Datenbanken. Es stellt Funktionen für Zugriff, Speicherung, Sicherheit und Datenpflege bereit (z. B. MySQL, PostgreSQL, Oracle).',
    },
  ],
  questions: [
    {
      type: 'mc',
      prompt: 'Wofür ist das DNS zuständig?',
      options: [
        'Übersetzung von Domainnamen in IP-Adressen',
        'Verschlüsselung von Daten',
        'Vergabe von Passwörtern',
        'Komprimierung von Dateien',
      ],
      correct: [0],
      explanation: 'DNS (Domain Name System) löst Namen wie example.com in IP-Adressen auf.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Wie viele Bits hat eine IPv4-Adresse?',
      options: ['16 Bit', '64 Bit', '128 Bit', '32 Bit'],
      correct: [3],
      explanation: 'IPv4-Adressen bestehen aus 32 Bit, die in vier Oktette aufgeteilt werden (z. B. 192.168.1.1).',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Wie viele Bits hat eine IPv6-Adresse?',
      options: ['32 Bit', '128 Bit', '64 Bit', '256 Bit'],
      correct: [1],
      explanation: 'IPv6-Adressen bestehen aus 128 Bit und ermöglichen eine deutlich größere Adressierbarkeit als IPv4.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welches Gerät verbindet verschiedene Netzwerke und leitet Datenpakete anhand von IP-Adressen weiter?',
      options: ['Hub', 'Switch', 'Router', 'Modem'],
      correct: [2],
      explanation: 'Der Router arbeitet auf der Vermittlungsschicht (Layer 3) des OSI-Modells und leitet Pakete anhand von IP-Adressen zwischen Netzwerken weiter.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welches Protokoll weist Netzwerkgeräten automatisch IP-Adressen zu?',
      options: ['FTP', 'SMTP', 'HTTP', 'DHCP'],
      correct: [3],
      explanation: 'DHCP (Dynamic Host Configuration Protocol) vergibt IP-Adressen und Netzwerkkonfigurationen automatisch an Clients.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Aus wie vielen Schichten besteht das OSI-Referenzmodell?',
      options: ['4', '5', '7', '9'],
      correct: [2],
      explanation: 'Das OSI-Modell besteht aus 7 Schichten: Bitübertragung, Sicherung, Vermittlung, Transport, Sitzung, Darstellung und Anwendung.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Auf welcher OSI-Schicht arbeitet ein Switch?',
      options: ['Schicht 1 (Bitübertragung)', 'Schicht 2 (Sicherungsschicht)', 'Schicht 3 (Vermittlungsschicht)', 'Schicht 4 (Transportschicht)'],
      correct: [1],
      explanation: 'Ein Switch arbeitet auf der Sicherungsschicht (Layer 2) und leitet Frames anhand von MAC-Adressen weiter.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Welche Netzwerktopologie verbindet alle Geräte mit einem zentralen Knoten?',
      options: ['Bus-Topologie', 'Ring-Topologie', 'Stern-Topologie', 'Maschen-Topologie'],
      correct: [2],
      explanation: 'Bei der Stern-Topologie sind alle Geräte mit einem zentralen Gerät (z. B. Switch) verbunden. Fällt der zentrale Knoten aus, ist das gesamte Netzwerk betroffen.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welche Netzwerktopologie nutzt ein gemeinsames Übertragungsmedium, auf das alle Geräte zugreifen?',
      options: ['Stern-Topologie', 'Bus-Topologie', 'Ring-Topologie', 'Baum-Topologie'],
      correct: [1],
      explanation: 'Bei der Bus-Topologie teilen sich alle Geräte ein gemeinsames Kabel. Datenpakete werden an alle gesendet, aber nur vom Zielgerät verarbeitet.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welcher Standard-Port wird von HTTP verwendet?',
      options: ['443', '21', '80', '25'],
      correct: [2],
      explanation: 'HTTP verwendet standardmäßig Port 80. HTTPS verwendet Port 443, FTP Port 21 und SMTP Port 25.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was unterscheidet HTTPS von HTTP?',
      options: [
        'HTTPS ist schneller als HTTP',
        'HTTPS verwendet eine verschlüsselte Verbindung via TLS/SSL',
        'HTTPS benötigt keinen Port',
        'HTTPS kann nur Bilder übertragen',
      ],
      correct: [1],
      explanation: 'HTTPS (Hypertext Transfer Protocol Secure) verschlüsselt die Datenübertragung mithilfe von TLS (Transport Layer Security) und schützt so vor Abhören und Manipulation.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was ist ein Primärschlüssel in einer relationalen Datenbank?',
      options: [
        'Ein Attribut, das auf eine andere Tabelle verweist',
        'Ein verschlüsseltes Kennwort für Datenbankzugriff',
        'Ein eindeutiges Attribut, das jeden Datensatz identifiziert',
        'Eine automatisch generierte Sicherungskopie',
      ],
      correct: [2],
      explanation: 'Der Primärschlüssel identifiziert jeden Datensatz eindeutig. Er darf nicht NULL sein und muss innerhalb der Tabelle einmalig sein.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welche SQL-Anweisung wird verwendet, um Datensätze aus einer Tabelle abzufragen?',
      options: ['INSERT', 'DELETE', 'UPDATE', 'SELECT'],
      correct: [3],
      explanation: 'SELECT wird verwendet, um Daten aus einer oder mehreren Tabellen abzufragen. Mit WHERE, ORDER BY und JOIN kann die Abfrage präzisiert werden.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welche SQL-Anweisung fügt neue Datensätze in eine Tabelle ein?',
      options: ['INSERT INTO', 'ADD INTO', 'UPDATE', 'CREATE'],
      correct: [0],
      explanation: 'INSERT INTO fügt neue Zeilen in eine Tabelle ein. Die Syntax lautet: INSERT INTO tabelle (spalte1, spalte2) VALUES (wert1, wert2).',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist der Zweck eines Fremdschlüssels?',
      options: [
        'Daten zu verschlüsseln',
        'Eine Beziehung zwischen zwei Tabellen herzustellen',
        'Doppelte Einträge zu erzeugen',
        'Die Tabelle zu sperren',
      ],
      correct: [1],
      explanation: 'Ein Fremdschlüssel verweist auf den Primärschlüssel einer anderen Tabelle und stellt so eine referenzielle Integrität zwischen den Tabellen sicher.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was versteht man unter Redundanz in Datenbanken?',
      options: [
        'Fehlende Datensätze in Tabellen',
        'Zu viele Primärschlüssel',
        'Mehrfaches Speichern gleicher Daten',
        'Fehlende Indizes',
      ],
      correct: [2],
      explanation: 'Redundanz bedeutet, dass dieselben Daten mehrfach gespeichert werden. Dies kann zu Inkonsistenzen führen und wird durch Normalisierung reduziert.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welches Protokoll wird zum Versenden von E-Mails verwendet?',
      options: ['POP3', 'IMAP', 'SMTP', 'FTP'],
      correct: [2],
      explanation: 'SMTP (Simple Mail Transfer Protocol) ist das Protokoll zum Versenden von E-Mails. POP3 und IMAP werden dagegen zum Empfangen von E-Mails verwendet.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was ist ein WLAN?',
      options: [
        'Ein kabelgebundenes lokales Netzwerk',
        'Ein drahtloses lokales Netzwerk',
        'Ein Weitverkehrsnetz',
        'Ein virtuelles privates Netzwerk',
      ],
      correct: [1],
      explanation: 'WLAN (Wireless Local Area Network) ist ein drahtloses lokales Netzwerk, das Geräte über Funkwellen (meist nach IEEE 802.11) verbindet.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was beschreibt das Client-Server-Modell?',
      options: [
        'Alle Geräte haben gleiche Rollen im Netzwerk',
        'Clients stellen Ressourcen bereit, Server rufen diese ab',
        'Server stellen Dienste bereit, Clients rufen diese ab',
        'Nur Server können Daten senden',
      ],
      correct: [2],
      explanation: 'Im Client-Server-Modell bieten Server Dienste oder Ressourcen an (z. B. Webseiten, Dateien), und Clients fordern diese Dienste an.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist der Unterschied zwischen einer relationalen und einer NoSQL-Datenbank?',
      options: [
        'Relationale Datenbanken speichern keine Daten',
        'NoSQL-Datenbanken verwenden ausschließlich SQL',
        'Relationale Datenbanken nutzen Tabellen mit festem Schema; NoSQL ist flexibler und schemalos',
        'Es gibt keinen Unterschied',
      ],
      correct: [2],
      explanation: 'Relationale Datenbanken organisieren Daten in Tabellen mit festem Schema. NoSQL-Systeme (z. B. MongoDB) sind flexibler und eignen sich für unstrukturierte oder sich ändernde Datenstrukturen.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Welche Normalform besagt, dass alle Nicht-Schlüsselattribute voll funktional vom Primärschlüssel abhängig sein müssen?',
      options: ['Erste Normalform (1NF)', 'Zweite Normalform (2NF)', 'Dritte Normalform (3NF)', 'Vierte Normalform (4NF)'],
      correct: [1],
      explanation: 'Die zweite Normalform (2NF) fordert, dass alle Nicht-Schlüsselattribute vollständig vom gesamten Primärschlüssel abhängig sind, nicht nur von einem Teil davon.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Was ist eine Firewall?',
      options: [
        'Ein Gerät zum Verstärken von WLAN-Signalen',
        'Ein System zur Kontrolle des Netzwerkverkehrs anhand von Regeln',
        'Ein Protokoll zur Datenverschlüsselung',
        'Ein Betriebssystem für Server',
      ],
      correct: [1],
      explanation: 'Eine Firewall überwacht und filtert den Netzwerkverkehr basierend auf vordefinierten Sicherheitsregeln und schützt so vor unerwünschten Zugriffen.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist FTP und auf welchem Port läuft es standardmäßig?',
      options: [
        'File Transfer Protocol, Port 80',
        'File Transfer Protocol, Port 21',
        'Fast Transfer Protocol, Port 443',
        'File Transport Protocol, Port 22',
      ],
      correct: [1],
      explanation: 'FTP (File Transfer Protocol) ist ein Protokoll zur Dateiübertragung und verwendet standardmäßig Port 21 für die Steuerverbindung.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was ist eine MAC-Adresse?',
      options: [
        'Eine logische Netzwerkadresse, die vom Router vergeben wird',
        'Eine eindeutige Hardware-Adresse einer Netzwerkkarte mit 48 Bit',
        'Eine IP-Adresse im IPv6-Format',
        'Eine Adresse für E-Mail-Server',
      ],
      correct: [1],
      explanation: 'Eine MAC-Adresse (Media Access Control) ist eine physikalische Adresse, die vom Hersteller in die Netzwerkkarte eingebrannt wird. Sie besteht aus 48 Bit (6 Byte) in hexadezimaler Darstellung.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welche SQL-Anweisung ändert bestehende Datensätze in einer Tabelle?',
      options: ['ALTER', 'MODIFY', 'UPDATE', 'CHANGE'],
      correct: [2],
      explanation: 'UPDATE wird verwendet, um bestehende Datensätze zu ändern. Die Syntax lautet: UPDATE tabelle SET spalte = wert WHERE bedingung.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welche Schicht des OSI-Modells ist für die logische Adressierung (IP) und das Routing zuständig?',
      options: ['Schicht 1 (Bitübertragung)', 'Schicht 2 (Sicherung)', 'Schicht 3 (Vermittlung)', 'Schicht 4 (Transport)'],
      correct: [2],
      explanation: 'Die Vermittlungsschicht (Layer 3) ist für logische Adressierung (IP-Adressen) und das Routing von Datenpaketen zwischen Netzwerken zuständig.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Was beschreibt ein ER-Modell?',
      options: [
        'Einen Netzwerkplan mit Routern und Switches',
        'Eine grafische Darstellung von Entitäten und deren Beziehungen für Datenbankplanung',
        'Ein Verschlüsselungsverfahren für Datenbanken',
        'Ein Protokoll zur Datenübertragung',
      ],
      correct: [1],
      explanation: 'Das Entity-Relationship-Modell (ER-Modell) dient der grafischen Darstellung von Datenbankstrukturen: Es zeigt Entitäten, ihre Attribute und die Beziehungen zwischen ihnen.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welche Aussage über einen Hub ist korrekt?',
      options: [
        'Ein Hub leitet Daten gezielt an den Empfänger weiter',
        'Ein Hub sendet Daten an alle angeschlossenen Geräte (Broadcast)',
        'Ein Hub verbindet verschiedene Netzwerke miteinander',
        'Ein Hub verschlüsselt alle übertragenen Daten',
      ],
      correct: [1],
      explanation: 'Ein Hub sendet alle eingehenden Datenpakete an sämtliche angeschlossenen Ports (Broadcast). Im Gegensatz dazu leitet ein Switch Pakete gezielt weiter.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was versteht man unter Bandbreite in einem Netzwerk?',
      options: [
        'Die Anzahl der angeschlossenen Geräte',
        'Die maximale Datenmenge, die pro Zeiteinheit übertragen werden kann',
        'Die Länge eines Netzwerkkabels',
        'Die Anzahl der verfügbaren IP-Adressen',
      ],
      correct: [1],
      explanation: 'Bandbreite beschreibt die theoretische maximale Übertragungskapazität einer Netzwerkverbindung, gemessen in Bit pro Sekunde (bps, Mbps, Gbps).',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welche SQL-Anweisung löscht Datensätze aus einer Tabelle?',
      options: ['REMOVE', 'DROP', 'DELETE', 'CLEAR'],
      correct: [2],
      explanation: 'DELETE löscht Datensätze aus einer Tabelle: DELETE FROM tabelle WHERE bedingung. DROP würde die gesamte Tabelle entfernen.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welche Aussage zur Ring-Topologie ist korrekt?',
      options: [
        'Alle Geräte sind mit einem zentralen Switch verbunden',
        'Daten werden in einer Richtung von Gerät zu Gerät weitergegeben',
        'Es gibt einen gemeinsamen Bus, auf den alle Geräte zugreifen',
        'Jedes Gerät ist mit jedem anderen direkt verbunden',
      ],
      correct: [1],
      explanation: 'Bei der Ring-Topologie sind Geräte ringförmig verbunden. Datenpakete werden in einer festen Richtung von Gerät zu Gerät weitergegeben, bis sie den Empfänger erreichen.',
      difficulty: 2,
    },
    {
      type: 'truefalse',
      prompt: 'TCP garantiert eine zuverlässige, geordnete Datenübertragung, während UDP keine Garantie für die Zustellung bietet.',
      options: ['Wahr', 'Falsch'],
      correct: [0],
      explanation: 'TCP (Transmission Control Protocol) stellt durch Bestätigungen und Neuübertragungen eine zuverlässige Datenübertragung sicher. UDP (User Datagram Protocol) ist verbindungslos und bietet keine Zustellgarantie, ist aber schneller.',
      difficulty: 2,
    },
    {
      type: 'truefalse',
      prompt: 'Ein Primärschlüssel in einer Datenbanktabelle darf den Wert NULL enthalten.',
      options: ['Wahr', 'Falsch'],
      correct: [1],
      explanation: 'Ein Primärschlüssel darf niemals NULL sein. Er muss jeden Datensatz eindeutig identifizieren und daher immer einen Wert haben.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist das Ziel der Normalisierung in relationalen Datenbanken?',
      options: [
        'Die Datenbank zu verschlüsseln',
        'Redundanzen zu reduzieren und Datenintegrität zu gewährleisten',
        'Die Abfragegeschwindigkeit zu verringern',
        'Primärschlüssel zu entfernen',
      ],
      correct: [1],
      explanation: 'Normalisierung strukturiert Tabellen so, dass Datenredundanz minimiert und Anomalien beim Einfügen, Ändern und Löschen vermieden werden.',
      difficulty: 2,
    },
  ],
};

export default topic;
