import type { RawTopic } from '../types';

const topic: RawTopic = {
  slug: 'oberbegriffe',
  title: 'Oberbegriffe',
  description: 'Den passenden Oberbegriff zu einer Wortgruppe finden.',
  flashcards: [
    {
      front: 'Rose, Tulpe, Nelke, Lilie',
      back: 'Oberbegriff: Blumen',
    },
    {
      front: 'Eiche, Buche, Fichte, Birke',
      back: 'Oberbegriff: Bäume',
    },
    {
      front: 'Hammer, Säge, Schraubenzieher, Zange',
      back: 'Oberbegriff: Werkzeuge',
    },
    {
      front: 'Sofa, Stuhl, Schrank, Bett',
      back: 'Oberbegriff: Möbel',
    },
    {
      front: 'Geige, Klavier, Flöte, Trompete',
      back: 'Oberbegriff: Musikinstrumente',
    },
    {
      front: 'Hund, Katze, Pferd, Elefant',
      back: 'Oberbegriff: Säugetiere',
    },
    {
      front: 'Adler, Meise, Storch, Amsel',
      back: 'Oberbegriff: Vögel',
    },
    {
      front: 'See, Fluss, Bach, Teich',
      back: 'Oberbegriff: Gewässer',
    },
    {
      front: 'Gold, Silber, Platin, Palladium',
      back: 'Oberbegriff: Edelmetalle',
    },
    {
      front: 'Freude, Trauer, Angst, Wut',
      back: 'Oberbegriff: Gefühle / Emotionen',
    },
    {
      front: 'Arzt, Lehrer, Anwalt, Ingenieur',
      back: 'Oberbegriff: Berufe',
    },
    {
      front: 'Auto, Bus, Zug, Motorrad',
      back: 'Oberbegriff: Fahrzeuge',
    },
    {
      front: 'Apfel, Birne, Kirsche, Pflaume',
      back: 'Oberbegriff: Obst',
    },
    {
      front: 'Karotte, Brokkoli, Spinat, Lauch',
      back: 'Oberbegriff: Gemüse',
    },
    {
      front: 'Rot, Blau, Grün, Gelb',
      back: 'Oberbegriff: Farben',
    },
    {
      front: 'Nord, Süd, Ost, West',
      back: 'Oberbegriff: Himmelsrichtungen',
    },
    {
      front: 'Was ist ein Oberbegriff?',
      back: 'Ein Oberbegriff (Hyperonym) bezeichnet eine übergeordnete Kategorie, der mehrere Unterbegriffe angehören. Beispiel: "Tier" ist der Oberbegriff von "Hund", "Katze", "Vogel".',
    },
    {
      front: 'Was ist ein Unterbegriff?',
      back: 'Ein Unterbegriff (Hyponym) ist ein spezifischerer Begriff, der einer übergeordneten Kategorie angehört. Beispiel: "Rose" ist ein Unterbegriff von "Blume".',
    },
  ],
  questions: [
    // --- BLUMEN & PFLANZEN ---
    {
      type: 'mc',
      prompt: 'Rose, Tulpe, Nelke gehören zu …?',
      options: ['Blumen', 'Bäume', 'Kräuter', 'Sträucher'],
      correct: [0],
      explanation: 'Rose, Tulpe und Nelke sind Blumen.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welches Wort passt NICHT in die Reihe: Rose, Tulpe, Eiche, Nelke?',
      options: ['Rose', 'Tulpe', 'Eiche', 'Nelke'],
      correct: [2],
      explanation: 'Eiche ist ein Baum, keine Blume. Rose, Tulpe und Nelke sind Blumen.',
      difficulty: 1,
    },
    {
      type: 'fill',
      prompt: 'Nenne den Oberbegriff für: Minze, Basilikum, Thymian, Rosmarin.',
      options: ['Kräuter', 'Gewürze', 'Blumen', 'Gemüse'],
      correct: [0],
      explanation: 'Minze, Basilikum, Thymian und Rosmarin sind Kräuter (auch als Küchenkräuter oder Gewürzkräuter bezeichnet).',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Eiche, Buche, Fichte, Birke gehören zu …?',
      options: ['Sträucher', 'Bäume', 'Blumen', 'Pilze'],
      correct: [1],
      explanation: 'Eiche, Buche, Fichte und Birke sind Bäume.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welches Wort passt NICHT in die Reihe: Eiche, Buche, Rose, Birke?',
      options: ['Eiche', 'Buche', 'Rose', 'Birke'],
      correct: [2],
      explanation: 'Rose ist eine Blume, kein Baum. Eiche, Buche und Birke sind Bäume.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Kiefer, Fichte, Tanne, Lärche gehören zu …?',
      options: ['Laubbäume', 'Nadelbäume', 'Sträucher', 'Farne'],
      correct: [1],
      explanation: 'Kiefer, Fichte, Tanne und Lärche sind Nadelbäume.',
      difficulty: 2,
    },
    // --- WERKZEUGE ---
    {
      type: 'mc',
      prompt: 'Hammer, Säge, Schraubenzieher, Zange gehören zu …?',
      options: ['Küchenutensilien', 'Werkzeuge', 'Sportgeräte', 'Möbel'],
      correct: [1],
      explanation: 'Hammer, Säge, Schraubenzieher und Zange sind Werkzeuge.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welches Wort passt NICHT in die Reihe: Hammer, Zange, Säge, Topf?',
      options: ['Hammer', 'Zange', 'Säge', 'Topf'],
      correct: [3],
      explanation: 'Topf ist ein Küchengerät, kein Werkzeug. Hammer, Zange und Säge sind Werkzeuge.',
      difficulty: 1,
    },
    {
      type: 'fill',
      prompt: 'Nenne den Oberbegriff für: Meißel, Hobel, Bohrer, Feile.',
      options: ['Werkzeuge', 'Maschinen', 'Geräte', 'Instrumente'],
      correct: [0],
      explanation: 'Meißel, Hobel, Bohrer und Feile sind (Hand-)Werkzeuge.',
      difficulty: 2,
    },
    // --- MÖBEL ---
    {
      type: 'mc',
      prompt: 'Sofa, Stuhl, Schrank, Bett gehören zu …?',
      options: ['Elektrogeräte', 'Möbel', 'Baumaterialien', 'Haushaltsgeräte'],
      correct: [1],
      explanation: 'Sofa, Stuhl, Schrank und Bett sind Möbel.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welches Wort passt NICHT in die Reihe: Sofa, Stuhl, Kühlschrank, Bett?',
      options: ['Sofa', 'Stuhl', 'Kühlschrank', 'Bett'],
      correct: [2],
      explanation: 'Kühlschrank ist ein Haushaltsgerät, kein Möbelstück. Sofa, Stuhl und Bett sind Möbel.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Kommode, Sideboard, Vitrine, Regal gehören zu …?',
      options: ['Aufbewahrungsmöbel', 'Sitzgelegenheiten', 'Küchengeräte', 'Beleuchtung'],
      correct: [0],
      explanation: 'Kommode, Sideboard, Vitrine und Regal dienen der Aufbewahrung und sind Aufbewahrungsmöbel.',
      difficulty: 2,
    },
    // --- MUSIKINSTRUMENTE ---
    {
      type: 'mc',
      prompt: 'Geige, Klavier, Flöte, Trompete gehören zu …?',
      options: ['Sportgeräte', 'Werkzeuge', 'Musikinstrumente', 'Elektrogeräte'],
      correct: [2],
      explanation: 'Geige, Klavier, Flöte und Trompete sind Musikinstrumente.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welches Wort passt NICHT in die Reihe: Geige, Cello, Bratsche, Trompete?',
      options: ['Geige', 'Cello', 'Bratsche', 'Trompete'],
      correct: [3],
      explanation: 'Trompete ist ein Blasinstrument. Geige, Cello und Bratsche sind Streichinstrumente.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Flöte, Oboe, Klarinette, Fagott gehören zu …?',
      options: ['Schlaginstrumente', 'Streichinstrumente', 'Holzblasinstrumente', 'Tasteninstrumente'],
      correct: [2],
      explanation: 'Flöte, Oboe, Klarinette und Fagott sind Holzblasinstrumente.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Pauke, Trommel, Becken, Xylofon gehören zu …?',
      options: ['Blasinstrumente', 'Schlaginstrumente', 'Streichinstrumente', 'Zupfinstrumente'],
      correct: [1],
      explanation: 'Pauke, Trommel, Becken und Xylofon sind Schlaginstrumente.',
      difficulty: 2,
    },
    // --- SÄUGETIERE ---
    {
      type: 'mc',
      prompt: 'Hund, Katze, Pferd, Elefant gehören zu …?',
      options: ['Vögel', 'Reptilien', 'Säugetiere', 'Fische'],
      correct: [2],
      explanation: 'Hund, Katze, Pferd und Elefant sind Säugetiere.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welches Wort passt NICHT in die Reihe: Hund, Katze, Adler, Pferd?',
      options: ['Hund', 'Katze', 'Adler', 'Pferd'],
      correct: [2],
      explanation: 'Adler ist ein Vogel, kein Säugetier. Hund, Katze und Pferd sind Säugetiere.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Löwe, Tiger, Leopard, Gepard gehören zu …?',
      options: ['Nagetiere', 'Raubtiere', 'Huftiere', 'Beuteltiere'],
      correct: [1],
      explanation: 'Löwe, Tiger, Leopard und Gepard sind Raubtiere (genauer: Großkatzen).',
      difficulty: 2,
    },
    {
      type: 'fill',
      prompt: 'Nenne den Oberbegriff für: Maus, Ratte, Eichhörnchen, Hamster.',
      options: ['Nagetiere', 'Säugetiere', 'Kleintiere', 'Haustiere'],
      correct: [0],
      explanation: 'Maus, Ratte, Eichhörnchen und Hamster sind Nagetiere.',
      difficulty: 2,
    },
    // --- VÖGEL ---
    {
      type: 'mc',
      prompt: 'Adler, Meise, Storch, Amsel gehören zu …?',
      options: ['Fische', 'Insekten', 'Reptilien', 'Vögel'],
      correct: [3],
      explanation: 'Adler, Meise, Storch und Amsel sind Vögel.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welches Wort passt NICHT in die Reihe: Adler, Falke, Bussard, Pinguin?',
      options: ['Adler', 'Falke', 'Bussard', 'Pinguin'],
      correct: [3],
      explanation: 'Pinguin ist zwar ein Vogel, aber im Gegensatz zu Adler, Falke und Bussard kein Greifvogel und kann nicht fliegen.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Adler, Habicht, Falke, Bussard gehören zu …?',
      options: ['Zugvögel', 'Greifvögel', 'Singvögel', 'Wasservögel'],
      correct: [1],
      explanation: 'Adler, Habicht, Falke und Bussard sind Greifvögel.',
      difficulty: 2,
    },
    // --- GEWÄSSER ---
    {
      type: 'mc',
      prompt: 'See, Fluss, Bach, Teich gehören zu …?',
      options: ['Landschaften', 'Gewässer', 'Gebirge', 'Täler'],
      correct: [1],
      explanation: 'See, Fluss, Bach und Teich sind Gewässer.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welches Wort passt NICHT in die Reihe: See, Fluss, Bach, Gebirge?',
      options: ['See', 'Fluss', 'Bach', 'Gebirge'],
      correct: [3],
      explanation: 'Gebirge ist eine Landform, kein Gewässer. See, Fluss und Bach sind Gewässer.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Atlantik, Pazifik, Indik, Nordpolarmeer gehören zu …?',
      options: ['Seen', 'Flüsse', 'Ozeane', 'Meere'],
      correct: [2],
      explanation: 'Atlantik, Pazifik, Indik und Nordpolarmeer sind die vier großen Ozeane der Erde.',
      difficulty: 2,
    },
    {
      type: 'fill',
      prompt: 'Nenne den Oberbegriff für: Rhein, Donau, Elbe, Oder.',
      options: ['Flüsse', 'Seen', 'Bäche', 'Kanäle'],
      correct: [0],
      explanation: 'Rhein, Donau, Elbe und Oder sind Flüsse (genauer: große Flüsse in Deutschland bzw. Mitteleuropa).',
      difficulty: 1,
    },
    // --- EDELMETALLE & METALLE ---
    {
      type: 'mc',
      prompt: 'Gold, Silber, Platin, Palladium gehören zu …?',
      options: ['Edelsteine', 'Edelmetalle', 'Legierungen', 'Mineralien'],
      correct: [1],
      explanation: 'Gold, Silber, Platin und Palladium sind Edelmetalle.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welches Wort passt NICHT in die Reihe: Gold, Silber, Eisen, Platin?',
      options: ['Gold', 'Silber', 'Eisen', 'Platin'],
      correct: [2],
      explanation: 'Eisen ist ein Metall, aber kein Edelmetall. Gold, Silber und Platin sind Edelmetalle.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Diamant, Rubin, Smaragd, Saphir gehören zu …?',
      options: ['Edelmetalle', 'Mineralien', 'Edelsteine', 'Kristalle'],
      correct: [2],
      explanation: 'Diamant, Rubin, Smaragd und Saphir sind Edelsteine.',
      difficulty: 2,
    },
    // --- GEFÜHLE ---
    {
      type: 'mc',
      prompt: 'Freude, Trauer, Angst, Wut gehören zu …?',
      options: ['Eigenschaften', 'Gefühle', 'Gedanken', 'Handlungen'],
      correct: [1],
      explanation: 'Freude, Trauer, Angst und Wut sind Gefühle (Emotionen).',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welches Wort passt NICHT in die Reihe: Freude, Glück, Begeisterung, Melancholie?',
      options: ['Freude', 'Glück', 'Begeisterung', 'Melancholie'],
      correct: [3],
      explanation: 'Melancholie ist ein negatives/trauriges Gefühl, während Freude, Glück und Begeisterung positive Gefühle sind.',
      difficulty: 2,
    },
    {
      type: 'fill',
      prompt: 'Nenne den Oberbegriff für: Neid, Eifersucht, Gier, Hochmut.',
      options: ['Laster', 'Gefühle', 'Charakterzüge', 'Sünden'],
      correct: [0],
      explanation: 'Neid, Eifersucht, Gier und Hochmut gelten als Laster (moralisch negative Eigenschaften oder Gefühle).',
      difficulty: 3,
    },
    // --- BERUFE ---
    {
      type: 'mc',
      prompt: 'Arzt, Lehrer, Anwalt, Ingenieur gehören zu …?',
      options: ['Hobbys', 'Berufe', 'Titel', 'Eigenschaften'],
      correct: [1],
      explanation: 'Arzt, Lehrer, Anwalt und Ingenieur sind Berufe.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welches Wort passt NICHT in die Reihe: Arzt, Chirurg, Internist, Lehrer?',
      options: ['Arzt', 'Chirurg', 'Internist', 'Lehrer'],
      correct: [3],
      explanation: 'Lehrer ist kein medizinischer Beruf. Arzt, Chirurg und Internist gehören alle zum medizinischen Bereich.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Tischler, Maurer, Elektriker, Klempner gehören zu …?',
      options: ['Akademische Berufe', 'Handwerksberufe', 'Kaufmännische Berufe', 'Sozialberufe'],
      correct: [1],
      explanation: 'Tischler, Maurer, Elektriker und Klempner sind Handwerksberufe.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Richter, Staatsanwalt, Rechtsanwalt, Notar gehören zu …?',
      options: ['Medizinische Berufe', 'Technische Berufe', 'Juristische Berufe', 'Pädagogische Berufe'],
      correct: [2],
      explanation: 'Richter, Staatsanwalt, Rechtsanwalt und Notar sind juristische Berufe.',
      difficulty: 2,
    },
    // --- FAHRZEUGE ---
    {
      type: 'mc',
      prompt: 'Auto, Bus, Zug, Motorrad gehören zu …?',
      options: ['Maschinen', 'Fahrzeuge', 'Transportmittel', 'Geräte'],
      correct: [1],
      explanation: 'Auto, Bus, Zug und Motorrad sind Fahrzeuge.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welches Wort passt NICHT in die Reihe: Auto, Bus, Zug, Flugzeug?',
      options: ['Auto', 'Bus', 'Zug', 'Flugzeug'],
      correct: [3],
      explanation: 'Flugzeug ist ein Luftfahrzeug. Auto, Bus und Zug sind Landfahrzeuge.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Jacht, Kutter, Fregatte, U-Boot gehören zu …?',
      options: ['Luftfahrzeuge', 'Schienenfahrzeuge', 'Wasserfahrzeuge', 'Kraftfahrzeuge'],
      correct: [2],
      explanation: 'Jacht, Kutter, Fregatte und U-Boot sind Wasserfahrzeuge (Schiffe bzw. Boote).',
      difficulty: 2,
    },
    {
      type: 'fill',
      prompt: 'Nenne den Oberbegriff für: Airbus, Boeing, Helikopter, Zeppelin.',
      options: ['Luftfahrzeuge', 'Transportmittel', 'Flugzeuge', 'Maschinen'],
      correct: [0],
      explanation: 'Airbus, Boeing (Flugzeugtypen), Helikopter und Zeppelin sind Luftfahrzeuge.',
      difficulty: 2,
    },
    // --- OBST ---
    {
      type: 'mc',
      prompt: 'Apfel, Birne, Kirsche, Pflaume gehören zu …?',
      options: ['Gemüse', 'Nüsse', 'Obst', 'Beeren'],
      correct: [2],
      explanation: 'Apfel, Birne, Kirsche und Pflaume sind Obstarten.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welches Wort passt NICHT in die Reihe: Apfel, Birne, Karotte, Kirsche?',
      options: ['Apfel', 'Birne', 'Karotte', 'Kirsche'],
      correct: [2],
      explanation: 'Karotte ist Gemüse, kein Obst. Apfel, Birne und Kirsche sind Obst.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Erdbeere, Himbeere, Heidelbeere, Johannisbeere gehören zu …?',
      options: ['Kernobst', 'Steinobst', 'Beerenobst', 'Zitrusfrüchte'],
      correct: [2],
      explanation: 'Erdbeere, Himbeere, Heidelbeere und Johannisbeere sind Beerenobst.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Orange, Zitrone, Grapefruit, Mandarine gehören zu …?',
      options: ['Tropenfrüchte', 'Beerenobst', 'Zitrusfrüchte', 'Kernobst'],
      correct: [2],
      explanation: 'Orange, Zitrone, Grapefruit und Mandarine sind Zitrusfrüchte.',
      difficulty: 1,
    },
    // --- GEMÜSE ---
    {
      type: 'mc',
      prompt: 'Karotte, Brokkoli, Spinat, Lauch gehören zu …?',
      options: ['Obst', 'Kräuter', 'Gemüse', 'Pilze'],
      correct: [2],
      explanation: 'Karotte, Brokkoli, Spinat und Lauch sind Gemüsesorten.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welches Wort passt NICHT in die Reihe: Karotte, Tomate, Apfel, Zucchini?',
      options: ['Karotte', 'Tomate', 'Apfel', 'Zucchini'],
      correct: [2],
      explanation: 'Apfel ist Obst, kein Gemüse. Karotte, Tomate und Zucchini sind Gemüse.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Kartoffel, Rübe, Rettich, Sellerie gehören zu …?',
      options: ['Blattgemüse', 'Fruchtgemüse', 'Wurzel- und Knollengemüse', 'Hülsenfrüchte'],
      correct: [2],
      explanation: 'Kartoffel, Rübe, Rettich und Sellerie wachsen unter der Erde und sind Wurzel- bzw. Knollengemüse.',
      difficulty: 3,
    },
    {
      type: 'fill',
      prompt: 'Nenne den Oberbegriff für: Erbsen, Bohnen, Linsen, Kichererbsen.',
      options: ['Hülsenfrüchte', 'Gemüse', 'Samen', 'Körner'],
      correct: [0],
      explanation: 'Erbsen, Bohnen, Linsen und Kichererbsen sind Hülsenfrüchte.',
      difficulty: 2,
    },
    // --- FARBEN ---
    {
      type: 'mc',
      prompt: 'Rot, Blau, Grün, Gelb gehören zu …?',
      options: ['Töne', 'Farben', 'Nuancen', 'Muster'],
      correct: [1],
      explanation: 'Rot, Blau, Grün und Gelb sind Farben.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welches Wort passt NICHT in die Reihe: Rot, Blau, Gelb, Cyan?',
      options: ['Rot', 'Blau', 'Gelb', 'Cyan'],
      correct: [3],
      explanation: 'Rot, Blau und Gelb sind die drei Grundfarben (Primärfarben im Malerbereich). Cyan ist eine Sekundärfarbe.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Scharlach, Bordeaux, Karmesin, Rubinrot gehören zu …?',
      options: ['Blautöne', 'Rottöne', 'Grüntöne', 'Gelbtöne'],
      correct: [1],
      explanation: 'Scharlach, Bordeaux, Karmesin und Rubinrot sind verschiedene Rottöne.',
      difficulty: 2,
    },
    // --- HIMMELSRICHTUNGEN ---
    {
      type: 'mc',
      prompt: 'Nord, Süd, Ost, West gehören zu …?',
      options: ['Jahreszeiten', 'Himmelsrichtungen', 'Koordinaten', 'Winde'],
      correct: [1],
      explanation: 'Nord, Süd, Ost und West sind die vier Haupthimmelsrichtungen.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welches Wort passt NICHT in die Reihe: Norden, Süden, Westen, Frühling?',
      options: ['Norden', 'Süden', 'Westen', 'Frühling'],
      correct: [3],
      explanation: 'Frühling ist eine Jahreszeit, keine Himmelsrichtung. Norden, Süden und Westen sind Himmelsrichtungen.',
      difficulty: 1,
    },
    {
      type: 'fill',
      prompt: 'Nenne den Oberbegriff für: Nordost, Nordwest, Südost, Südwest.',
      options: ['Nebenhimmelsrichtungen', 'Himmelsrichtungen', 'Windrichtungen', 'Koordinaten'],
      correct: [0],
      explanation: 'Nordost, Nordwest, Südost und Südwest sind die vier Nebenhimmelsrichtungen.',
      difficulty: 2,
    },
    // --- JAHRESZEITEN & MONATE ---
    {
      type: 'mc',
      prompt: 'Frühling, Sommer, Herbst, Winter gehören zu …?',
      options: ['Monate', 'Jahreszeiten', 'Feiertage', 'Klimazonen'],
      correct: [1],
      explanation: 'Frühling, Sommer, Herbst und Winter sind die vier Jahreszeiten.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Januar, Februar, März, April gehören zu …?',
      options: ['Jahreszeiten', 'Wochentage', 'Monate', 'Feiertage'],
      correct: [2],
      explanation: 'Januar, Februar, März und April sind Monate.',
      difficulty: 1,
    },
    // --- SPORT & BEWEGUNG ---
    {
      type: 'mc',
      prompt: 'Fußball, Tennis, Basketball, Volleyball gehören zu …?',
      options: ['Mannschaftssportarten', 'Ballsportarten', 'Wintersportarten', 'Kampfsportarten'],
      correct: [1],
      explanation: 'Fußball, Tennis, Basketball und Volleyball sind Ballsportarten.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welches Wort passt NICHT in die Reihe: Fußball, Basketball, Volleyball, Schwimmen?',
      options: ['Fußball', 'Basketball', 'Volleyball', 'Schwimmen'],
      correct: [3],
      explanation: 'Schwimmen ist eine Wassersportart, keine Ballsportart. Fußball, Basketball und Volleyball sind Ballsportarten.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Ski alpin, Biathlon, Eishockey, Eiskunstlauf gehören zu …?',
      options: ['Sommersportarten', 'Wintersportarten', 'Wassersportarten', 'Leichtathletik'],
      correct: [1],
      explanation: 'Ski alpin, Biathlon, Eishockey und Eiskunstlauf sind Wintersportarten.',
      difficulty: 1,
    },
    // --- KLEIDUNG ---
    {
      type: 'mc',
      prompt: 'Hemd, Hose, Jacke, Kleid gehören zu …?',
      options: ['Accessoires', 'Kleidung', 'Textilien', 'Stoffe'],
      correct: [1],
      explanation: 'Hemd, Hose, Jacke und Kleid sind Kleidungsstücke.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welches Wort passt NICHT in die Reihe: Hemd, Hose, Schal, Schuh?',
      options: ['Hemd', 'Hose', 'Schal', 'Schuh'],
      correct: [3],
      explanation: 'Schuh ist ein Schuhwerk, kein Kleidungsstück im engeren Sinne. Hemd, Hose und Schal sind Kleidungsstücke.',
      difficulty: 2,
    },
    // --- KÖRPERTEILE ---
    {
      type: 'mc',
      prompt: 'Arm, Bein, Kopf, Rumpf gehören zu …?',
      options: ['Organe', 'Körperteile', 'Gliedmaßen', 'Knochen'],
      correct: [1],
      explanation: 'Arm, Bein, Kopf und Rumpf sind Körperteile des Menschen.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Herz, Lunge, Leber, Niere gehören zu …?',
      options: ['Körperteile', 'Knochen', 'Organe', 'Muskeln'],
      correct: [2],
      explanation: 'Herz, Lunge, Leber und Niere sind innere Organe.',
      difficulty: 1,
    },
    // --- NAHRUNGSMITTEL ALLGEMEIN ---
    {
      type: 'mc',
      prompt: 'Weizen, Roggen, Hafer, Gerste gehören zu …?',
      options: ['Hülsenfrüchte', 'Getreide', 'Kräuter', 'Gemüse'],
      correct: [1],
      explanation: 'Weizen, Roggen, Hafer und Gerste sind Getreidearten.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Milch, Käse, Butter, Joghurt gehören zu …?',
      options: ['Tierprodukte', 'Milchprodukte', 'Nahrungsergänzungsmittel', 'Fette'],
      correct: [1],
      explanation: 'Milch, Käse, Butter und Joghurt sind Milchprodukte.',
      difficulty: 1,
    },
    {
      type: 'fill',
      prompt: 'Nenne den Oberbegriff für: Bier, Wein, Whisky, Wodka.',
      options: ['Alkoholische Getränke', 'Getränke', 'Spirituosen', 'Weine'],
      correct: [0],
      explanation: 'Bier, Wein, Whisky und Wodka sind alkoholische Getränke.',
      difficulty: 1,
    },
    // --- LÄNDER & GEOGRAPHIE ---
    {
      type: 'mc',
      prompt: 'Deutschland, Frankreich, Italien, Spanien gehören zu …?',
      options: ['Kontinente', 'Bundesländer', 'Europäische Länder', 'Hauptstädte'],
      correct: [2],
      explanation: 'Deutschland, Frankreich, Italien und Spanien sind europäische Länder.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Alpen, Himalaya, Anden, Rocky Mountains gehören zu …?',
      options: ['Wüsten', 'Gebirge', 'Täler', 'Hochplateaus'],
      correct: [1],
      explanation: 'Alpen, Himalaya, Anden und Rocky Mountains sind Gebirge.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welches Wort passt NICHT in die Reihe: Berlin, Paris, London, Bayern?',
      options: ['Berlin', 'Paris', 'London', 'Bayern'],
      correct: [3],
      explanation: 'Bayern ist ein deutsches Bundesland, keine Hauptstadt. Berlin, Paris und London sind Hauptstädte.',
      difficulty: 1,
    },
    // --- TIERE ALLGEMEIN ---
    {
      type: 'mc',
      prompt: 'Forelle, Lachs, Hering, Karpfen gehören zu …?',
      options: ['Meerestiere', 'Fische', 'Krustentiere', 'Weichtiere'],
      correct: [1],
      explanation: 'Forelle, Lachs, Hering und Karpfen sind Fische.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Frosch, Kröte, Salamander, Molch gehören zu …?',
      options: ['Reptilien', 'Amphibien', 'Insekten', 'Würmer'],
      correct: [1],
      explanation: 'Frosch, Kröte, Salamander und Molch sind Amphibien.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Schlange, Eidechse, Krokodil, Schildkröte gehören zu …?',
      options: ['Amphibien', 'Insekten', 'Reptilien', 'Säugetiere'],
      correct: [2],
      explanation: 'Schlange, Eidechse, Krokodil und Schildkröte sind Reptilien.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Biene, Ameise, Käfer, Schmetterling gehören zu …?',
      options: ['Spinnentiere', 'Insekten', 'Würmer', 'Krustentiere'],
      correct: [1],
      explanation: 'Biene, Ameise, Käfer und Schmetterling sind Insekten.',
      difficulty: 1,
    },
    // --- GEBÄUDE & ORTE ---
    {
      type: 'mc',
      prompt: 'Kirche, Moschee, Synagoge, Tempel gehören zu …?',
      options: ['Verwaltungsgebäude', 'Gotteshäuser', 'Schulen', 'Kulturzentren'],
      correct: [1],
      explanation: 'Kirche, Moschee, Synagoge und Tempel sind Gotteshäuser (Religionsstätten).',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Grundschule, Gymnasium, Berufsschule, Universität gehören zu …?',
      options: ['Kindergärten', 'Bildungseinrichtungen', 'Behörden', 'Kultureinrichtungen'],
      correct: [1],
      explanation: 'Grundschule, Gymnasium, Berufsschule und Universität sind Bildungseinrichtungen.',
      difficulty: 1,
    },
    // --- SONSTIGES / GEMISCHT ---
    {
      type: 'mc',
      prompt: 'Welches Wort passt NICHT in die Reihe: Hammer, Säge, Zange, Pinsel?',
      options: ['Hammer', 'Säge', 'Zange', 'Pinsel'],
      correct: [3],
      explanation: 'Pinsel ist ein Malwerkzeug, während Hammer, Säge und Zange klassische Handwerkzeuge sind.',
      difficulty: 2,
    },
    {
      type: 'fill',
      prompt: 'Nenne den Oberbegriff für: Rose, Jasmin, Lavendel, Flieder.',
      options: ['Duftpflanzen', 'Blumen', 'Sträucher', 'Gartenpflanzen'],
      correct: [0],
      explanation: 'Rose, Jasmin, Lavendel und Flieder sind bekannte Duftpflanzen.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Stethoskop, Skalpell, Spritze, Pinzette gehören zu …?',
      options: ['Laborgeräte', 'Medizinische Instrumente', 'Werkzeuge', 'Hilfsmittel'],
      correct: [1],
      explanation: 'Stethoskop, Skalpell, Spritze und Pinzette sind medizinische Instrumente.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welches Wort passt NICHT in die Reihe: Freude, Trauer, Angst, Intelligenz?',
      options: ['Freude', 'Trauer', 'Angst', 'Intelligenz'],
      correct: [3],
      explanation: 'Intelligenz ist eine kognitive Eigenschaft, kein Gefühl. Freude, Trauer und Angst sind Gefühle.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Kugelschreiber, Füller, Bleistift, Filzstift gehören zu …?',
      options: ['Büromaterial', 'Schreibgeräte', 'Zeichenmittel', 'Kunstbedarf'],
      correct: [1],
      explanation: 'Kugelschreiber, Füller, Bleistift und Filzstift sind Schreibgeräte.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welches Wort passt NICHT in die Reihe: Geige, Cello, Kontrabass, Klarinette?',
      options: ['Geige', 'Cello', 'Kontrabass', 'Klarinette'],
      correct: [3],
      explanation: 'Klarinette ist ein Blasinstrument. Geige, Cello und Kontrabass sind Streichinstrumente.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Regen, Schnee, Hagel, Graupel gehören zu …?',
      options: ['Naturkatastrophen', 'Niederschlagsformen', 'Wetterphänomene', 'Aggregatzustände'],
      correct: [1],
      explanation: 'Regen, Schnee, Hagel und Graupel sind verschiedene Formen von Niederschlag.',
      difficulty: 2,
    },
    {
      type: 'fill',
      prompt: 'Nenne den Oberbegriff für: Euro, Dollar, Pfund, Yen.',
      options: ['Währungen', 'Zahlungsmittel', 'Devisen', 'Geldeinheiten'],
      correct: [0],
      explanation: 'Euro, Dollar, Pfund und Yen sind Währungen verschiedener Länder bzw. Währungsräume.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Kreuz, Herz, Pik, Karo gehören zu …?',
      options: ['Figuren', 'Kartensymbole', 'Spielkartenfarben', 'Kartenspielwerte'],
      correct: [2],
      explanation: 'Kreuz, Herz, Pik und Karo sind die vier Spielkartenfarben (Suits) im deutschen und internationalen Kartenspiel.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welches Wort passt NICHT in die Reihe: Birke, Buche, Eiche, Bambus?',
      options: ['Birke', 'Buche', 'Eiche', 'Bambus'],
      correct: [3],
      explanation: 'Bambus ist ein Gras, kein Laubbaum. Birke, Buche und Eiche sind Laubbäume.',
      difficulty: 3,
    },
  ],
};

export default topic;
