import type { RawTopic } from '../types';

const topic: RawTopic = {
  slug: 'politisches-system',
  title: 'Politisches System',
  description: 'Die fünf Verfassungsorgane und der Gesetzgebungsprozess.',
  flashcards: [
    {
      front: 'Welche fünf Verfassungsorgane der Bundesrepublik Deutschland nennt das Grundgesetz?',
      back: 'Bundestag, Bundesrat, Bundesregierung, Bundespräsident und Bundesverfassungsgericht.',
    },
    {
      front: 'Was ist die zentrale Aufgabe des Bundestages?',
      back: 'Der Bundestag ist das direkt vom Volk gewählte Parlament. Er beschließt Bundesgesetze, wählt den Bundeskanzler und kontrolliert die Bundesregierung.',
    },
    {
      front: 'Wie viele Sitze hat der 21. Deutsche Bundestag und wann wurde er gewählt?',
      back: 'Der 21. Deutsche Bundestag hat 630 Sitze und wurde am 23. Februar 2025 gewählt.',
    },
    {
      front: 'Wer ist seit dem 6. Mai 2025 Bundeskanzler und welcher Koalition gehört er an?',
      back: 'Friedrich Merz (CDU) ist seit dem 6. Mai 2025 Bundeskanzler. Er führt eine Koalition aus CDU/CSU und SPD.',
    },
    {
      front: 'Was ist die Hauptaufgabe des Bundesrates?',
      back: 'Der Bundesrat vertritt die 16 Bundesländer auf Bundesebene. Er wirkt an der Bundesgesetzgebung und Verwaltung des Bundes mit und kann Einspruch gegen Gesetze einlegen oder diesen zustimmen.',
    },
    {
      front: 'Wer ist aktuell Bundespräsident der Bundesrepublik Deutschland?',
      back: 'Frank-Walter Steinmeier ist Bundespräsident.',
    },
    {
      front: 'Welche Aufgaben hat der Bundespräsident im Gesetzgebungsverfahren?',
      back: 'Der Bundespräsident fertigt vom Bundestag und Bundesrat beschlossene Gesetze aus und verkündet sie im Bundesgesetzblatt. Er prüft dabei die formelle und materielle Verfassungsmäßigkeit.',
    },
    {
      front: 'Was ist das konstruktive Misstrauensvotum?',
      back: 'Das konstruktive Misstrauensvotum (Art. 67 GG) erlaubt dem Bundestag, den Bundeskanzler nur dann abzusetzen, wenn er gleichzeitig mit absoluter Mehrheit einen Nachfolger wählt. So soll Regierungslosigkeit verhindert werden.',
    },
    {
      front: 'Was ist die Vertrauensfrage und welche Folgen kann sie haben?',
      back: 'Der Bundeskanzler kann dem Bundestag die Vertrauensfrage stellen (Art. 68 GG). Erhält er keine Mehrheit, kann der Bundespräsident auf Vorschlag des Kanzlers den Bundestag auflösen und Neuwahlen ansetzen.',
    },
    {
      front: 'Wie wird der Bundeskanzler gewählt?',
      back: 'Der Bundeskanzler wird auf Vorschlag des Bundespräsidenten vom Bundestag mit absoluter Mehrheit (Kanzlermehrheit) gewählt (Art. 63 GG).',
    },
    {
      front: 'Was ist der Unterschied zwischen einem Zustimmungsgesetz und einem Einspruchsgesetz?',
      back: 'Zustimmungsgesetze bedürfen der ausdrücklichen Zustimmung des Bundesrates – ohne diese können sie nicht in Kraft treten. Einspruchsgesetze kann der Bundesrat nur verzögernd ablehnen; der Bundestag kann den Einspruch mit entsprechender Mehrheit überstimmen.',
    },
    {
      front: 'Wer hat das Recht zur Gesetzesinitiative (Initiativrecht)?',
      back: 'Das Initiativrecht steht der Bundesregierung, dem Bundestag (mindestens 5 % der Mitglieder oder eine Fraktion) und dem Bundesrat zu.',
    },
    {
      front: 'Wie viele Lesungen durchläuft ein Gesetzentwurf im Bundestag?',
      back: 'Ein Gesetzentwurf durchläuft drei Lesungen im Bundestag: 1. Lesung (Einbringung und Überweisung an Ausschüsse), 2. Lesung (Ausschussbericht, Einzelberatung, Abstimmung über Änderungen), 3. Lesung (Schlussabstimmung).',
    },
    {
      front: 'Welche Aufgabe hat das Bundesverfassungsgericht?',
      back: 'Das Bundesverfassungsgericht in Karlsruhe wacht über die Einhaltung des Grundgesetzes. Es entscheidet u. a. über Normenkontrolle, Organstreitigkeiten, Verfassungsbeschwerden und Parteienverbote.',
    },
    {
      front: 'Wer ist aktuell Präsident des Bundesverfassungsgerichts?',
      back: 'Stephan Harbarth ist Präsident des Bundesverfassungsgerichts.',
    },
    {
      front: 'Wer ist aktuell Bundestagspräsidentin?',
      back: 'Julia Klöckner ist Bundestagspräsidentin des 21. Deutschen Bundestages.',
    },
    {
      front: 'Was versteht man unter dem Vermittlungsausschuss?',
      back: 'Der Vermittlungsausschuss ist ein gemeinsames Gremium von Bundestag und Bundesrat, das bei Meinungsverschiedenheiten zwischen beiden Kammern über Gesetzentwürfe einen Kompromiss aushandeln soll.',
    },
    {
      front: 'Welche Amtszeit hat der Bundespräsident und wie oft kann er wiedergewählt werden?',
      back: 'Der Bundespräsident wird für fünf Jahre gewählt und kann einmal wiedergewählt werden. Er wird von der Bundesversammlung gewählt.',
    },
    {
      front: 'Was ist die Bundesversammlung und welche Aufgabe hat sie?',
      back: 'Die Bundesversammlung besteht aus allen Mitgliedern des Bundestages und einer gleichen Anzahl von Mitgliedern, die von den Landesparlamenten gewählt werden. Ihre einzige Aufgabe ist die Wahl des Bundespräsidenten.',
    },
    {
      front: 'Welche Mehrheit benötigt der Bundestag, um einen Einspruch des Bundesrates zurückzuweisen?',
      back: 'Wurde der Einspruch des Bundesrates mit absoluter Mehrheit beschlossen, braucht der Bundestag ebenfalls eine absolute Mehrheit zur Zurückweisung. Bei einer Zwei-Drittel-Mehrheit im Bundesrat benötigt der Bundestag ebenfalls eine Zwei-Drittel-Mehrheit.',
    },
  ],
  questions: [
    {
      type: 'mc',
      prompt: 'Welches der folgenden Organe ist KEIN Verfassungsorgan der Bundesrepublik Deutschland?',
      options: ['Bundestag', 'Bundesverfassungsgericht', 'Bundesrechnungshof', 'Bundesrat'],
      correct: [2],
      explanation: 'Der Bundesrechnungshof ist eine oberste Bundesbehörde, aber kein Verfassungsorgan. Die fünf Verfassungsorgane sind Bundestag, Bundesrat, Bundesregierung, Bundespräsident und Bundesverfassungsgericht.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Wie viele Sitze hat der 21. Deutsche Bundestag?',
      options: ['598', '736', '630', '709'],
      correct: [2],
      explanation: 'Der 21. Deutsche Bundestag, gewählt am 23. Februar 2025, hat 630 Sitze.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Wer ist seit dem 6. Mai 2025 Bundeskanzler der Bundesrepublik Deutschland?',
      options: ['Olaf Scholz', 'Friedrich Merz', 'Armin Laschet', 'Robert Habeck'],
      correct: [1],
      explanation: 'Friedrich Merz (CDU) wurde am 6. Mai 2025 zum Bundeskanzler gewählt und führt eine Koalition aus CDU/CSU und SPD.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welche Koalition bildet die Bundesregierung unter Friedrich Merz?',
      options: ['CDU/CSU und FDP', 'SPD und Grüne', 'CDU/CSU und SPD', 'CDU/CSU, SPD und FDP'],
      correct: [2],
      explanation: 'Die Bundesregierung unter Friedrich Merz ist eine Koalition aus CDU/CSU und SPD (Große Koalition).',
      difficulty: 1,
    },
    {
      type: 'truefalse',
      prompt: 'Der Bundestag wird direkt vom Volk gewählt.',
      options: ['Richtig', 'Falsch'],
      correct: [0],
      explanation: 'Richtig. Der Bundestag ist das einzige direkt vom Volk gewählte Verfassungsorgan auf Bundesebene.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Auf welcher Grundlage wählt der Bundestag den Bundeskanzler?',
      options: [
        'Mit einfacher Mehrheit auf Vorschlag des Bundesrates',
        'Mit absoluter Mehrheit auf Vorschlag des Bundespräsidenten',
        'Mit Zwei-Drittel-Mehrheit auf Vorschlag der stärksten Fraktion',
        'Durch Direktwahl der Bevölkerung',
      ],
      correct: [1],
      explanation: 'Gemäß Art. 63 GG schlägt der Bundespräsident einen Kandidaten vor, der vom Bundestag mit absoluter Mehrheit (Kanzlermehrheit) gewählt wird.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was beschreibt das konstruktive Misstrauensvotum (Art. 67 GG)?',
      options: [
        'Der Bundestag kann den Bundeskanzler jederzeit mit einfacher Mehrheit abwählen.',
        'Der Bundespräsident kann den Bundeskanzler entlassen, wenn das Vertrauen entzogen wird.',
        'Der Bundestag kann den Bundeskanzler nur absetzen, wenn er gleichzeitig einen Nachfolger mit absoluter Mehrheit wählt.',
        'Der Bundesrat kann dem Bundeskanzler das Misstrauen aussprechen.',
      ],
      correct: [2],
      explanation: 'Das konstruktive Misstrauensvotum verhindert Regierungslosigkeit: Der Bundestag kann den Kanzler nur absetzen, wenn er gleichzeitig einen neuen Kanzler mit absoluter Mehrheit wählt.',
      difficulty: 2,
    },
    {
      type: 'truefalse',
      prompt: 'Beim konstruktiven Misstrauensvotum reicht eine einfache Mehrheit im Bundestag aus.',
      options: ['Richtig', 'Falsch'],
      correct: [1],
      explanation: 'Falsch. Das konstruktive Misstrauensvotum erfordert eine absolute Mehrheit (Kanzlermehrheit) der Mitglieder des Bundestages.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was kann geschehen, wenn der Bundeskanzler die Vertrauensfrage stellt und keine Mehrheit erhält?',
      options: [
        'Der Kanzler muss sofort zurücktreten.',
        'Der Bundespräsident kann auf Vorschlag des Kanzlers den Bundestag auflösen.',
        'Der Bundesrat übernimmt die Regierungsgeschäfte.',
        'Es findet automatisch eine Neuwahl statt.',
      ],
      correct: [1],
      explanation: 'Gemäß Art. 68 GG kann der Bundespräsident auf Antrag des Bundeskanzlers den Bundestag auflösen, wenn dieser die Vertrauensfrage verloren hat. Die Auflösung ist aber keine automatische Folge.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Wer hat das Initiativrecht für Bundesgesetze?',
      options: [
        'Nur die Bundesregierung',
        'Bundesregierung, Bundestag und Bundesrat',
        'Bundestag und Bundesrat, aber nicht die Bundesregierung',
        'Bundespräsident, Bundesregierung und Bundestag',
      ],
      correct: [1],
      explanation: 'Das Initiativrecht steht der Bundesregierung, dem Bundestag (Fraktionen oder 5 % der Mitglieder) und dem Bundesrat zu.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'In welcher Reihenfolge durchläuft ein Gesetzentwurf die drei Lesungen im Bundestag?',
      options: [
        'Schlussabstimmung – Ausschussberatung – Einbringung',
        'Einbringung und Überweisung – Ausschussbericht und Einzelberatung – Schlussabstimmung',
        'Ausschussberatung – Einbringung – Schlussabstimmung',
        'Einbringung – Schlussabstimmung – Ausschussberatung',
      ],
      correct: [1],
      explanation: 'Die erste Lesung dient der Einbringung und Überweisung an Ausschüsse. In der zweiten Lesung werden der Ausschussbericht diskutiert und Änderungen abgestimmt. Die dritte Lesung endet mit der Schlussabstimmung.',
      difficulty: 2,
    },
    {
      type: 'truefalse',
      prompt: 'Zustimmungsgesetze können ohne Zustimmung des Bundesrates in Kraft treten, wenn der Bundestag einen Einspruch zurückweist.',
      options: ['Richtig', 'Falsch'],
      correct: [1],
      explanation: 'Falsch. Bei Zustimmungsgesetzen ist die ausdrückliche Zustimmung des Bundesrates zwingend erforderlich. Ohne diese Zustimmung kann das Gesetz nicht in Kraft treten – der Bundestag kann eine Ablehnung nicht überstimmen.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was ist der Unterschied zwischen Zustimmungsgesetzen und Einspruchsgesetzen?',
      options: [
        'Beide können vom Bundestag ohne Mitwirkung des Bundesrates verabschiedet werden.',
        'Zustimmungsgesetze erfordern die ausdrückliche Zustimmung des Bundesrates; bei Einspruchsgesetzen kann der Bundestag den Einspruch überstimmen.',
        'Einspruchsgesetze erfordern zwingend die Zustimmung des Bundesrates; Zustimmungsgesetze nicht.',
        'Es gibt keinen rechtlichen Unterschied zwischen beiden Gesetzkategorien.',
      ],
      correct: [1],
      explanation: 'Bei Zustimmungsgesetzen muss der Bundesrat aktiv zustimmen. Bei Einspruchsgesetzen kann der Bundesrat nur einen aufschiebenden Einspruch einlegen, den der Bundestag mit qualifizierter Mehrheit zurückweisen kann.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welche Aufgabe hat der Vermittlungsausschuss?',
      options: [
        'Er vermittelt bei Streitigkeiten zwischen Bundesregierung und Bundesverfassungsgericht.',
        'Er handelt Kompromisse zwischen Bundestag und Bundesrat bei strittigen Gesetzentwürfen aus.',
        'Er entscheidet abschließend über die Verfassungsmäßigkeit von Gesetzen.',
        'Er berät den Bundespräsidenten bei der Ausfertigung von Gesetzen.',
      ],
      correct: [1],
      explanation: 'Der Vermittlungsausschuss ist ein gemeinsames Gremium von Bundestag und Bundesrat. Er tritt zusammen, wenn beide Organe keine Einigung über einen Gesetzentwurf erzielen können, und sucht einen Kompromiss.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welches Verfassungsorgan fertigt Gesetze aus und verkündet sie im Bundesgesetzblatt?',
      options: ['Bundestag', 'Bundesrat', 'Bundesregierung', 'Bundespräsident'],
      correct: [3],
      explanation: 'Der Bundespräsident fertigt die vom Bundestag und Bundesrat beschlossenen Gesetze aus und verkündet sie im Bundesgesetzblatt. Dabei prüft er auch die Verfassungsmäßigkeit.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Wer ist aktuell Bundespräsident der Bundesrepublik Deutschland?',
      options: ['Joachim Gauck', 'Frank-Walter Steinmeier', 'Friedrich Merz', 'Stephan Harbarth'],
      correct: [1],
      explanation: 'Frank-Walter Steinmeier ist Bundespräsident der Bundesrepublik Deutschland.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Wer ist aktuell Präsident des Bundesverfassungsgerichts?',
      options: ['Andreas Voßkuhle', 'Stephan Harbarth', 'Julia Klöckner', 'Peter Frank'],
      correct: [1],
      explanation: 'Stephan Harbarth ist Präsident des Bundesverfassungsgerichts in Karlsruhe.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Wer ist aktuell Präsidentin des Deutschen Bundestages?',
      options: ['Bärbel Bas', 'Julia Klöckner', 'Annalena Baerbock', 'Katrin Göring-Eckardt'],
      correct: [1],
      explanation: 'Julia Klöckner ist Bundestagspräsidentin des 21. Deutschen Bundestages.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welche Aufgabe hat das Bundesverfassungsgericht?',
      options: [
        'Es beschließt Bundesgesetze und kontrolliert die Exekutive.',
        'Es vertritt die Länder auf Bundesebene und wirkt an der Gesetzgebung mit.',
        'Es wacht über die Einhaltung des Grundgesetzes und entscheidet u. a. über Verfassungsbeschwerden.',
        'Es fertigt Gesetze aus und leitet sie an die Länder weiter.',
      ],
      correct: [2],
      explanation: 'Das Bundesverfassungsgericht ist Hüter des Grundgesetzes. Es entscheidet über Normenkontrolle, Organstreitigkeiten, Verfassungsbeschwerden, Parteienverbote und weitere verfassungsrechtliche Fragen.',
      difficulty: 1,
    },
    {
      type: 'truefalse',
      prompt: 'Der Bundesrat wird direkt vom Volk gewählt.',
      options: ['Richtig', 'Falsch'],
      correct: [1],
      explanation: 'Falsch. Der Bundesrat besteht aus Mitgliedern der Landesregierungen, die von diesen entsandt werden. Er wird nicht direkt gewählt.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welche Mehrheit ist für die Wahl des Bundeskanzlers durch den Bundestag erforderlich?',
      options: [
        'Einfache Mehrheit der abgegebenen Stimmen',
        'Zwei-Drittel-Mehrheit der Mitglieder des Bundestages',
        'Absolute Mehrheit der Mitglieder des Bundestages',
        'Drei-Viertel-Mehrheit der Mitglieder des Bundestages',
      ],
      correct: [2],
      explanation: 'Der Bundeskanzler wird mit absoluter Mehrheit (Kanzlermehrheit) der Mitglieder des Bundestages gewählt, d. h. mehr als die Hälfte aller Bundestagsmitglieder muss für ihn stimmen.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was versteht man unter der "Kanzlermehrheit"?',
      options: [
        'Die Mehrheit der abgegebenen Stimmen im Bundestag',
        'Die Mehrheit der Stimmen im Bundesrat',
        'Die absolute Mehrheit aller Mitglieder des Bundestages',
        'Eine Zwei-Drittel-Mehrheit der Bundestagsmitglieder',
      ],
      correct: [2],
      explanation: 'Als Kanzlermehrheit bezeichnet man die absolute Mehrheit aller Mitglieder des Bundestages (nicht nur der Anwesenden). Sie wird für die Wahl des Bundeskanzlers und das konstruktive Misstrauensvotum benötigt.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Wann fand die letzte Bundestagswahl statt, aus der der 21. Bundestag hervorging?',
      options: ['26. September 2021', '23. Februar 2025', '12. März 2023', '14. Oktober 2024'],
      correct: [1],
      explanation: 'Der 21. Deutsche Bundestag wurde am 23. Februar 2025 gewählt.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Wie lange beträgt die Amtszeit des Bundespräsidenten?',
      options: ['4 Jahre', '6 Jahre', '5 Jahre', '7 Jahre'],
      correct: [2],
      explanation: 'Der Bundespräsident wird für fünf Jahre gewählt. Eine einmalige Wiederwahl ist zulässig.',
      difficulty: 1,
    },
    {
      type: 'truefalse',
      prompt: 'Der Bundespräsident kann beliebig oft wiedergewählt werden.',
      options: ['Richtig', 'Falsch'],
      correct: [1],
      explanation: 'Falsch. Gemäß Art. 54 GG ist der Bundespräsident nur einmal wiederwählbar, d. h. er kann insgesamt zwei Amtszeiten von je fünf Jahren bekleiden.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Wie setzt sich die Bundesversammlung zusammen?',
      options: [
        'Aus allen Mitgliedern des Bundestages und des Bundesrates',
        'Aus allen Mitgliedern des Bundestages und einer gleichen Anzahl von Vertretern der Länderparlamente',
        'Ausschließlich aus den Ministerpräsidenten der Länder',
        'Aus Vertretern aller Verfassungsorgane',
      ],
      correct: [1],
      explanation: 'Die Bundesversammlung besteht aus allen Mitgliedern des Bundestages und einer gleichen Anzahl von Mitgliedern, die von den Volksvertretungen der Länder gewählt werden. Sie hat die einzige Aufgabe, den Bundespräsidenten zu wählen.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welche einzige Aufgabe hat die Bundesversammlung?',
      options: [
        'Verabschiedung des Bundeshaushalts',
        'Wahl des Bundespräsidenten',
        'Wahl des Bundeskanzlers',
        'Änderung des Grundgesetzes',
      ],
      correct: [1],
      explanation: 'Die Bundesversammlung kommt ausschließlich zur Wahl des Bundespräsidenten zusammen. Sie hat keine weiteren gesetzgeberischen Aufgaben.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'An welchem Gericht kann ein Bürger Verfassungsbeschwerde einreichen, wenn er seine Grundrechte verletzt sieht?',
      options: ['Bundesgerichtshof', 'Bundesverwaltungsgericht', 'Bundesverfassungsgericht', 'Oberverwaltungsgericht'],
      correct: [2],
      explanation: 'Verfassungsbeschwerden wegen der Verletzung von Grundrechten können beim Bundesverfassungsgericht in Karlsruhe eingereicht werden.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Wo hat das Bundesverfassungsgericht seinen Sitz?',
      options: ['Berlin', 'Bonn', 'Frankfurt am Main', 'Karlsruhe'],
      correct: [3],
      explanation: 'Das Bundesverfassungsgericht hat seinen Sitz in Karlsruhe.',
      difficulty: 1,
    },
    {
      type: 'truefalse',
      prompt: 'Die Bundesregierung hat kein Initiativrecht für Gesetzesvorhaben.',
      options: ['Richtig', 'Falsch'],
      correct: [1],
      explanation: 'Falsch. Die Bundesregierung gehört neben dem Bundestag und dem Bundesrat zu den drei Organen mit Initiativrecht und bringt in der Praxis die meisten Gesetzentwürfe ein.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welcher Artikel des Grundgesetzes regelt das konstruktive Misstrauensvotum?',
      options: ['Art. 63 GG', 'Art. 67 GG', 'Art. 68 GG', 'Art. 54 GG'],
      correct: [1],
      explanation: 'Das konstruktive Misstrauensvotum ist in Art. 67 GG geregelt. Art. 63 GG regelt die Wahl des Bundeskanzlers, Art. 68 GG die Vertrauensfrage.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Welcher Artikel des Grundgesetzes regelt die Vertrauensfrage des Bundeskanzlers?',
      options: ['Art. 54 GG', 'Art. 63 GG', 'Art. 67 GG', 'Art. 68 GG'],
      correct: [3],
      explanation: 'Die Vertrauensfrage des Bundeskanzlers ist in Art. 68 GG geregelt. Erhält der Kanzler nicht die Mehrheit der Mitglieder des Bundestages, kann der Bundespräsident auf seinen Antrag den Bundestag auflösen.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Welche Mehrheit benötigt der Bundestag, um den Einspruch des Bundesrates zurückzuweisen, wenn der Bundesrat mit Zwei-Drittel-Mehrheit abgelehnt hat?',
      options: [
        'Einfache Mehrheit',
        'Absolute Mehrheit',
        'Zwei-Drittel-Mehrheit',
        'Drei-Viertel-Mehrheit',
      ],
      correct: [2],
      explanation: 'Hat der Bundesrat seinen Einspruch mit Zwei-Drittel-Mehrheit beschlossen, kann der Bundestag diesen nur mit ebenfalls einer Zwei-Drittel-Mehrheit (mindestens jedoch absolute Mehrheit) zurückweisen.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Welche Partei führt Friedrich Merz, der aktuelle Bundeskanzler?',
      options: ['SPD', 'FDP', 'CDU', 'CSU'],
      correct: [2],
      explanation: 'Friedrich Merz ist Vorsitzender der CDU (Christlich Demokratische Union) und seit dem 6. Mai 2025 Bundeskanzler.',
      difficulty: 1,
    },
    {
      type: 'truefalse',
      prompt: 'Der Bundesrat vertritt die Interessen der deutschen Bundesländer auf Bundesebene.',
      options: ['Richtig', 'Falsch'],
      correct: [0],
      explanation: 'Richtig. Der Bundesrat ist das Verfassungsorgan, durch das die 16 Bundesländer an der Gesetzgebung und Verwaltung des Bundes sowie in Angelegenheiten der Europäischen Union mitwirken.',
      difficulty: 1,
    },
  ],
};

export default topic;
