import type { RawTopic } from '../types';

const topic: RawTopic = {
  slug: 'programmier-grundlagen',
  title: 'Programmier-Grundlagen',
  description: 'Konzepte des Programmierens – sprachunabhängig.',
  flashcards: [
    {
      front: 'Was ist eine Variable?',
      back: 'Eine Variable ist ein benannter Speicherplatz im Arbeitsspeicher, der einen Wert aufnehmen kann. Der Wert einer Variablen kann sich während der Programmausführung ändern.',
    },
    {
      front: 'Was ist eine Konstante?',
      back: 'Eine Konstante ist ein benannter Speicherplatz, dessen Wert nach der ersten Zuweisung nicht mehr verändert werden kann. Konstanten dienen dazu, unveränderliche Werte klar zu benennen (z. B. PI = 3,14159).',
    },
    {
      front: 'Welche grundlegenden Datentypen gibt es?',
      back: 'Ganzzahl (Integer), Kommazahl (Gleitkommazahl/Float), Zeichenkette (String), Wahrheitswert (Boolean). Manche Sprachen kennen zusätzlich Zeichen (Character) als eigenen Typ.',
    },
    {
      front: 'Was ist ein Wahrheitswert (Boolean)?',
      back: 'Ein Datentyp, der genau zwei Zustände annehmen kann: wahr (true) oder falsch (false). Wahrheitswerte sind das Ergebnis von Vergleichs- und logischen Ausdrücken.',
    },
    {
      front: 'Was versteht man unter einer Zeichenkette (String)?',
      back: 'Eine geordnete Folge von Zeichen (Buchstaben, Ziffern, Sonderzeichen). Zeichenketten werden üblicherweise in Anführungszeichen geschrieben, z. B. "Hallo Welt".',
    },
    {
      front: 'Was sind arithmetische Operatoren?',
      back: 'Operatoren für Grundrechenarten: Addition (+), Subtraktion (−), Multiplikation (×), Division (÷) und Modulo (Rest bei ganzzahliger Division). Sie verknüpfen numerische Werte zu einem neuen Wert.',
    },
    {
      front: 'Was ist der Modulo-Operator?',
      back: 'Der Modulo-Operator (%) liefert den Rest einer ganzzahligen Division. Beispiel: 10 mod 3 = 1, weil 10 = 3 × 3 + 1. Er wird oft verwendet, um zu prüfen, ob eine Zahl gerade oder ungerade ist.',
    },
    {
      front: 'Was sind Vergleichsoperatoren?',
      back: 'Operatoren, die zwei Werte miteinander vergleichen und einen Wahrheitswert (wahr/falsch) liefern: gleich (==), ungleich (≠), kleiner (<), größer (>), kleiner-gleich (≤), größer-gleich (≥).',
    },
    {
      front: 'Was sind logische Operatoren?',
      back: 'UND (AND/∧): beide Bedingungen müssen wahr sein. ODER (OR/∨): mindestens eine Bedingung muss wahr sein. NICHT (NOT/¬): kehrt den Wahrheitswert um.',
    },
    {
      front: 'Was ist eine Sequenz in der Programmierung?',
      back: 'Eine Sequenz ist die einfachste Kontrollstruktur: Anweisungen werden nacheinander, in der angegebenen Reihenfolge, von oben nach unten ausgeführt.',
    },
    {
      front: 'Was ist eine Verzweigung (if/else)?',
      back: 'Eine Verzweigung wertet eine Bedingung aus. Ist sie wahr, wird der if-Zweig ausgeführt; ist sie falsch, der else-Zweig (sofern vorhanden). So können Programme unterschiedliche Pfade einschlagen.',
    },
    {
      front: 'Was ist der Unterschied zwischen einer kopf- und einer fußgesteuerten Schleife?',
      back: 'Kopfgesteuert (while): Die Bedingung wird VOR dem Schleifenrumpf geprüft – der Rumpf kann 0-mal ausgeführt werden. Fußgesteuert (do-while/repeat-until): Die Bedingung wird NACH dem Rumpf geprüft – der Rumpf wird mindestens 1-mal ausgeführt.',
    },
    {
      front: 'Was ist eine Zählschleife (for-Schleife)?',
      back: 'Eine Schleife mit einem Zähler, Startwert, Endwert und Schrittweite. Der Schleifenrumpf wird eine im Voraus bekannte Anzahl von Malen ausgeführt. Beispiel im Pseudocode: FÜR i VON 1 BIS 10 SCHRITTWEITE 1.',
    },
    {
      front: 'Was ist eine Endlosschleife und wann tritt sie auf?',
      back: 'Eine Endlosschleife wird nie beendet, weil ihre Abbruchbedingung niemals falsch (bzw. wahr bei repeat-until) wird. Sie entsteht meist durch einen Programmierfehler, z. B. wenn der Zähler nicht verändert wird.',
    },
    {
      front: 'Was ist eine Funktion (Methode)?',
      back: 'Ein benannter, wiederverwendbarer Codeblock, der eine bestimmte Aufgabe erfüllt. Funktionen können Parameter entgegennehmen und einen Rückgabewert liefern. Sie fördern Modularität und Lesbarkeit.',
    },
    {
      front: 'Was sind Parameter und Rückgabewert einer Funktion?',
      back: 'Parameter sind Eingabewerte, die einer Funktion beim Aufruf übergeben werden. Der Rückgabewert ist das Ergebnis, das die Funktion nach ihrer Ausführung zurückliefert. Eine Funktion ohne Rückgabewert wird oft als Prozedur bezeichnet.',
    },
    {
      front: 'Was ist ein Algorithmus?',
      back: 'Eine eindeutige, endliche Folge von Anweisungen zur Lösung eines Problems. Ein Algorithmus muss terminieren (enden), korrekt sein und für alle gültigen Eingaben ein Ergebnis liefern.',
    },
    {
      front: 'Was ist ein Array (Feld/Liste)?',
      back: 'Eine geordnete Sammlung von Elementen desselben (oder kompatiblen) Datentyps, auf die über einen Index zugegriffen wird. Der Index beginnt meist bei 0. Arrays haben eine feste oder dynamische Größe.',
    },
    {
      front: 'Was ist Variablen-Gültigkeit (Scope)?',
      back: 'Der Bereich im Programm, in dem eine Variable sichtbar und verwendbar ist. Lokale Variablen gelten nur innerhalb eines Blocks (z. B. einer Funktion). Globale Variablen sind im gesamten Programm sichtbar.',
    },
    {
      front: 'Was sind Kommentare im Quellcode?',
      back: 'Kommentare sind Texte im Quellcode, die vom Compiler/Interpreter ignoriert werden. Sie dienen der Erklärung und Dokumentation des Codes für Entwickler:innen.',
    },
    {
      front: 'Was ist Pseudocode?',
      back: 'Eine informal strukturierte, sprachunabhängige Beschreibung eines Algorithmus in menschlich lesbarer Form. Pseudocode verwendet keine strenge Syntax einer Programmiersprache, folgt aber einer klaren Logik.',
    },
    {
      front: 'Was ist die Wahrheitstabelle für UND (AND)?',
      back: 'wahr  UND wahr  = wahr\nwahr  UND falsch = falsch\nfalsch UND wahr  = falsch\nfalsch UND falsch = falsch\nErgebnis ist nur dann wahr, wenn BEIDE Operanden wahr sind.',
    },
  ],
  questions: [
    {
      type: 'mc',
      prompt: 'Was versteht man unter einer Variablen?',
      options: [
        'Ein unveränderlicher Wert, der einmalig gesetzt wird',
        'Ein benannter Speicherplatz, dessen Wert sich ändern kann',
        'Eine Folge von Anweisungen zur Lösung eines Problems',
        'Ein Operator, der zwei Werte vergleicht',
      ],
      correct: [1],
      explanation: 'Eine Variable ist ein benannter Speicherplatz im Arbeitsspeicher, dem während der Programmausführung verschiedene Werte zugewiesen werden können.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ergibt der logische Ausdruck "wahr UND falsch"?',
      options: ['falsch', 'wahr', 'undefiniert', 'beides'],
      correct: [0],
      explanation: 'Bei UND (Konjunktion) muss BEIDES wahr sein. "wahr UND falsch" ergibt falsch, da einer der Operanden falsch ist.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ergibt der logische Ausdruck "falsch ODER wahr"?',
      options: ['falsch', 'undefiniert', 'wahr', 'falsch und wahr'],
      correct: [2],
      explanation: 'Bei ODER (Disjunktion) reicht es, wenn mindestens ein Operand wahr ist. "falsch ODER wahr" ergibt wahr.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ergibt "NICHT wahr"?',
      options: ['wahr', 'falsch', 'undefiniert', 'null'],
      correct: [1],
      explanation: 'Der NICHT-Operator (Negation) kehrt den Wahrheitswert um: NICHT wahr = falsch.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welcher Datentyp ist geeignet, um die Anzahl von Schüler:innen in einer Klasse zu speichern?',
      options: ['Kommazahl (Float)', 'Zeichenkette (String)', 'Ganzzahl (Integer)', 'Wahrheitswert (Boolean)'],
      correct: [2],
      explanation: 'Anzahlen sind immer ganze Zahlen – dafür ist der Ganzzahl-Datentyp (Integer) am besten geeignet.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welcher Datentyp speichert den Wert "Hallo Welt"?',
      options: ['Integer', 'Boolean', 'Float', 'String'],
      correct: [3],
      explanation: 'Text (Buchstabenfolgen) wird als Zeichenkette (String) gespeichert.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist der Unterschied zwischen einer Variablen und einer Konstanten?',
      options: [
        'Konstanten können nur Zahlen speichern, Variablen beliebige Werte',
        'Variablen können ihren Wert ändern, Konstanten nicht',
        'Variablen sind immer global, Konstanten immer lokal',
        'Es gibt keinen Unterschied, beides sind Synonyme',
      ],
      correct: [1],
      explanation: 'Der wesentliche Unterschied: Der Wert einer Variablen kann sich ändern, der einer Konstanten ist nach der Initialisierung fest.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was liefert der Ausdruck 17 mod 5?',
      options: ['3', '2', '4', '1'],
      correct: [1],
      explanation: '17 ÷ 5 = 3 Rest 2, denn 5 × 3 = 15, und 17 − 15 = 2. Modulo liefert den Rest der ganzzahligen Division.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welche Kontrollstruktur führt Anweisungen Schritt für Schritt, eine nach der anderen aus?',
      options: ['Verzweigung', 'Sequenz', 'Schleife', 'Rekursion'],
      correct: [1],
      explanation: 'Die Sequenz ist die grundlegende Kontrollstruktur: Anweisungen werden in der angegebenen Reihenfolge nacheinander ausgeführt.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welche Aussage zur kopfgesteuerten Schleife (while) ist korrekt?',
      options: [
        'Der Schleifenrumpf wird mindestens einmal ausgeführt',
        'Die Bedingung wird nach dem Schleifenrumpf geprüft',
        'Die Bedingung wird vor dem Schleifenrumpf geprüft',
        'Die Schleife zählt immer von 1 bis 10',
      ],
      correct: [2],
      explanation: 'Bei der kopfgesteuerten Schleife (while) wird die Bedingung VOR jedem Durchlauf geprüft. Ist sie von Anfang an falsch, wird der Rumpf gar nicht ausgeführt.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welche Aussage zur fußgesteuerten Schleife (do-while / repeat-until) ist korrekt?',
      options: [
        'Der Rumpf wird mindestens einmal ausgeführt',
        'Die Bedingung wird vor dem ersten Durchlauf geprüft',
        'Der Rumpf kann 0-mal ausgeführt werden',
        'Sie besitzt immer einen Zähler',
      ],
      correct: [0],
      explanation: 'Bei der fußgesteuerten Schleife wird die Bedingung NACH dem Schleifenrumpf geprüft, weshalb der Rumpf immer mindestens einmal ausgeführt wird.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was ist eine Endlosschleife?',
      options: [
        'Eine Schleife, die genau 1000-mal ausgeführt wird',
        'Eine Schleife ohne Schleifenrumpf',
        'Eine Schleife, deren Abbruchbedingung niemals erreicht wird',
        'Eine Schleife mit zwei Zählvariablen',
      ],
      correct: [2],
      explanation: 'Eine Endlosschleife entsteht, wenn die Abbruchbedingung nie erfüllt wird, z. B. weil der Zähler nicht verändert wird. Das Programm "hängt".',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was unterscheidet eine Zählschleife (for) von einer while-Schleife?',
      options: [
        'Die Zählschleife kann keine Bedingungen prüfen',
        'Die Zählschleife hat einen eingebauten Zähler mit Start-, End- und Schrittwert',
        'Die while-Schleife läuft immer mindestens einmal',
        'Die Zählschleife ist fußgesteuert',
      ],
      correct: [1],
      explanation: 'Die for-Schleife (Zählschleife) integriert Zählvariable, Startwert, Endwert und Schrittweite direkt im Schleifenkopf. Die while-Schleife prüft nur eine allgemeine Bedingung.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was gibt eine Funktion zurück, wenn sie als Rückgabetyp "void" (oder nichts) deklariert ist?',
      options: [
        'Den Wert 0',
        'Einen Wahrheitswert',
        'Keinen Wert – sie gibt nichts zurück',
        'Die Anzahl der Anweisungen im Funktionskörper',
      ],
      correct: [2],
      explanation: 'Eine Funktion ohne Rückgabewert (void / Prozedur) führt Anweisungen aus, liefert dem Aufrufer aber kein Ergebnis zurück.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was ist der Zweck von Parametern in einer Funktion?',
      options: [
        'Sie speichern das Ergebnis der Funktion permanent',
        'Sie übergeben Eingabewerte an die Funktion, damit sie damit arbeiten kann',
        'Sie definieren den Rückgabetyp der Funktion',
        'Sie sind Platzhalter für globale Variablen',
      ],
      correct: [1],
      explanation: 'Parameter sind Eingabewerte, die beim Funktionsaufruf übergeben werden. Sie ermöglichen es, dass eine Funktion mit verschiedenen Werten aufgerufen werden kann.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welche drei Eigenschaften muss ein Algorithmus erfüllen?',
      options: [
        'Er muss in Java geschrieben, kommentiert und kompilierbar sein',
        'Er muss terminieren, korrekt sein und für alle gültigen Eingaben ein Ergebnis liefern',
        'Er muss schnell, kurz und in Pseudocode formuliert sein',
        'Er muss eine Schleife, eine Verzweigung und eine Funktion enthalten',
      ],
      correct: [1],
      explanation: 'Ein Algorithmus muss (1) terminieren (enden), (2) korrekt sein (das richtige Ergebnis liefern) und (3) für alle zulässigen Eingaben definiert sein.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was ist der Index des ersten Elements in einem Array (typischerweise)?',
      options: ['1', '0', '-1', 'Es gibt keinen Index'],
      correct: [1],
      explanation: 'In den meisten Programmiersprachen beginnt die Indizierung eines Arrays bei 0. Das erste Element hat also den Index 0.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was beschreibt der Begriff "Scope" (Gültigkeitsbereich) einer Variablen?',
      options: [
        'Die maximale Zahl, die eine Variable speichern kann',
        'Den Bereich im Programm, in dem die Variable sichtbar und verwendbar ist',
        'Den Datentyp der Variablen',
        'Die Anzahl der Bytes, die eine Variable belegt',
      ],
      correct: [1],
      explanation: 'Der Scope legt fest, wo im Quellcode auf eine Variable zugegriffen werden darf. Lokale Variablen sind nur im umgebenden Block gültig, globale im gesamten Programm.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welchen Zweck erfüllen Kommentare im Quellcode?',
      options: [
        'Sie werden vom Compiler ausgeführt und beeinflussen das Programm',
        'Sie dienen der Dokumentation und werden vom Compiler ignoriert',
        'Sie deklarieren Variablen ohne Datentyp',
        'Sie beschleunigen die Ausführung des Programms',
      ],
      correct: [1],
      explanation: 'Kommentare sind für Menschen gedacht, nicht für den Computer. Sie erklären, was der Code tut, und werden bei der Übersetzung ignoriert.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist Pseudocode?',
      options: [
        'Ein Fehler im Quellcode, der nicht auffällt',
        'Eine sprachunabhängige, informelle Beschreibung eines Algorithmus',
        'Eine spezielle Programmiersprache für Anfänger',
        'Kommentare, die als Code getarnt sind',
      ],
      correct: [1],
      explanation: 'Pseudocode beschreibt die Logik eines Algorithmus in verständlicher, menschenlesbarer Form – ohne strenge Syntaxregeln einer Programmiersprache.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ergibt "falsch UND falsch"?',
      options: ['wahr', 'falsch', 'undefiniert', 'wahr und falsch'],
      correct: [1],
      explanation: 'UND ist nur dann wahr, wenn BEIDE Operanden wahr sind. "falsch UND falsch" ergibt falsch.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ergibt "falsch ODER falsch"?',
      options: ['undefiniert', 'wahr', 'falsch', 'null'],
      correct: [2],
      explanation: 'ODER ist wahr, wenn mindestens ein Operand wahr ist. Sind beide falsch, ist das Ergebnis ebenfalls falsch.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welcher Vergleichsoperator prüft, ob zwei Werte NICHT gleich sind?',
      options: ['==', '<', '≠ (bzw. !=)', '>'],
      correct: [2],
      explanation: 'Der Operator ≠ (in vielen Sprachen != oder <>) liefert wahr, wenn die beiden verglichenen Werte verschieden sind.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welche Aussage zu Gleitkommazahlen (Float) ist korrekt?',
      options: [
        'Gleitkommazahlen können keine negativen Werte darstellen',
        'Gleitkommazahlen speichern Zahlen mit Nachkommastellen',
        'Gleitkommazahlen sind immer ganzzahlig',
        'Gleitkommazahlen sind identisch mit Zeichenketten',
      ],
      correct: [1],
      explanation: 'Der Datentyp Gleitkommazahl (Float / Double) speichert Zahlen mit Nachkommastellen, z. B. 3,14 oder -0,5.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist der Rückgabewert des folgenden Pseudocodes?\n\nFUNKTION addiere(a, b)\n  RÜCKGABE a + b\nENDE\nErgebnis = addiere(3, 7)',
      options: ['3', '7', '10', '37'],
      correct: [2],
      explanation: 'Die Funktion addiert die Parameter a und b. Mit a=3 und b=7 ergibt die Addition 10.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Wie oft wird der Schleifenrumpf im folgenden Pseudocode ausgeführt?\n\ni = 1\nSOLANGE i <= 3\n  i = i + 1\nENDE',
      options: ['2-mal', '3-mal', '4-mal', '0-mal'],
      correct: [1],
      explanation: 'i startet bei 1: Durchlauf 1 (i=1→2), Durchlauf 2 (i=2→3), Durchlauf 3 (i=3→4). Dann ist i=4 > 3, die Schleife endet. Insgesamt 3 Durchläufe.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welche Kontrollstruktur ist geeignet, um je nach Bedingung unterschiedliche Code-Pfade auszuführen?',
      options: ['Sequenz', 'Zählschleife', 'Verzweigung (if/else)', 'Kommentar'],
      correct: [2],
      explanation: 'Die Verzweigung (if/else) wertet eine Bedingung aus und führt je nach Ergebnis (wahr/falsch) einen anderen Codeblock aus.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was wird in einem Array über den Index angesprochen?',
      options: [
        'Der Datentyp des Arrays',
        'Die Gesamtgröße des Arrays',
        'Ein einzelnes Element an einer bestimmten Position',
        'Der Name des Arrays',
      ],
      correct: [2],
      explanation: 'Über den Index (eine ganzzahlige Position) wird auf ein konkretes Element des Arrays zugegriffen, z. B. Zahlen[2] für das dritte Element (Index 0-basiert).',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welche Aussage beschreibt eine lokale Variable korrekt?',
      options: [
        'Sie ist im gesamten Programm sichtbar',
        'Sie ist nur innerhalb des Blocks gültig, in dem sie deklariert wurde',
        'Sie behält ihren Wert nach Programmende',
        'Sie kann nicht verändert werden',
      ],
      correct: [1],
      explanation: 'Lokale Variablen existieren nur innerhalb ihres Gültigkeitsbereichs (z. B. einer Funktion oder eines Schleifenblocks). Außerhalb sind sie nicht zugänglich.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was ist das Ergebnis von NICHT (wahr ODER falsch)?',
      options: ['wahr', 'falsch', 'undefiniert', 'wahr und falsch'],
      correct: [1],
      explanation: 'Zuerst wird der innere Ausdruck ausgewertet: wahr ODER falsch = wahr. Dann NICHT wahr = falsch.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Welche Aussage zu Funktionen ist FALSCH?',
      options: [
        'Funktionen können Parameter haben',
        'Funktionen können einen Rückgabewert haben',
        'Funktionen fördern die Wiederverwendbarkeit von Code',
        'Funktionen dürfen nur einmal im Programm aufgerufen werden',
      ],
      correct: [3],
      explanation: 'Funktionen können beliebig oft aufgerufen werden – das ist gerade ihr Zweck. Die anderen Aussagen sind korrekt.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was ist der Hauptvorteil von Funktionen (Modularisierung)?',
      options: [
        'Das Programm wird schneller',
        'Code muss nicht wiederholt werden und ist übersichtlicher',
        'Variablen werden automatisch global',
        'Schleifen werden überflüssig',
      ],
      correct: [1],
      explanation: 'Durch Funktionen wird Code wiederverwendbar und das Programm übersichtlicher. Gleiche Aufgaben müssen nicht mehrfach implementiert werden.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welcher der folgenden Werte ist kein gültiger Wahrheitswert (Boolean)?',
      options: ['wahr', 'falsch', '42', 'true'],
      correct: [2],
      explanation: 'Boolean-Werte sind ausschließlich wahr (true) oder falsch (false). Die Zahl 42 ist kein Wahrheitswert, sondern ein Integer.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welche Schleifenart eignet sich am besten, wenn die Anzahl der Wiederholungen vorab bekannt ist?',
      options: ['while-Schleife', 'do-while-Schleife', 'Zählschleife (for)', 'Keine Schleife, eine Funktion ist besser'],
      correct: [2],
      explanation: 'Wenn die Wiederholungsanzahl bereits vor der Schleife bekannt ist, bietet sich die Zählschleife (for) an, da sie Zähler, Start- und Endwert kompakt im Kopf definiert.',
      difficulty: 2,
    },
    {
      type: 'truefalse',
      prompt: 'Eine fußgesteuerte Schleife (do-while) wird mindestens einmal ausgeführt, auch wenn die Bedingung von Anfang an falsch ist.',
      options: ['Wahr', 'Falsch'],
      correct: [0],
      explanation: 'Richtig. Bei der fußgesteuerten Schleife wird der Rumpf zuerst ausgeführt, danach erst die Bedingung geprüft – daher immer mindestens ein Durchlauf.',
      difficulty: 2,
    },
    {
      type: 'truefalse',
      prompt: 'Pseudocode muss in einer bestimmten Programmiersprache geschrieben sein, um gültig zu sein.',
      options: ['Wahr', 'Falsch'],
      correct: [1],
      explanation: 'Falsch. Pseudocode ist bewusst sprachunabhängig und informal – er soll die Logik beschreiben, ohne an eine konkrete Syntax gebunden zu sein.',
      difficulty: 1,
    },
    {
      type: 'truefalse',
      prompt: 'Der Wert einer Konstanten kann nach ihrer Initialisierung im Programm beliebig oft geändert werden.',
      options: ['Wahr', 'Falsch'],
      correct: [1],
      explanation: 'Falsch. Eine Konstante ist nach ihrer Initialisierung unveränderlich – das ist ihr definierendes Merkmal gegenüber einer Variablen.',
      difficulty: 1,
    },
    {
      type: 'fill',
      prompt: 'Der Operator, der den Rest einer ganzzahligen Division zurückgibt, heißt ___.',
      correct: [0],
      options: ['Modulo', 'Division', 'Addition', 'Subtraktion'],
      explanation: 'Der Modulo-Operator (%) liefert den Rest der ganzzahligen Division, z. B. 10 mod 3 = 1.',
      difficulty: 1,
    },
  ],
};

export default topic;
