import type { RawTopic } from '../types';

const topic: RawTopic = {
  slug: 'rechtschreibung',
  title: 'Rechtschreibung',
  description: 'Richtige Schreibweise: das/dass, Groß-/Kleinschreibung, s/ss/ß, häufige Fehlerwörter.',
  flashcards: [
    {
      front: 'Wann schreibt man "dass" (mit Doppel-s)?',
      back: 'Als Konjunktion, die einen Nebensatz einleitet, der sich nicht durch "dieses" oder "welches" ersetzen lässt. Beispiel: "Ich hoffe, dass du kommst." (≠ "dieses kommt")',
    },
    {
      front: 'Wann schreibt man "das" (mit einem s)?',
      back: '"Das" ist ein Artikel oder Relativpronomen und lässt sich durch "dieses" oder "welches" ersetzen. Beispiel: "Das Buch, das ich lese." → "Dieses Buch, welches ich lese."',
    },
    {
      front: 'Regel: s, ss oder ß?',
      back: 'Nach kurzem Vokal steht ss (Fluss, muss). Nach langem Vokal oder Diphthong steht ß (Straße, Grüße, heiß). Am Satzende und vor t steht ß (du grüßt, er fließt).',
    },
    {
      front: 'Was ist das Dehnungs-h und wann steht es?',
      back: 'Das Dehnungs-h zeigt einen langen Vokal an und steht vor l, m, n, r. Beispiele: fahren, Wahl, Zahl, nehmen, Uhr, Stuhl. Es steht NICHT vor anderen Konsonanten.',
    },
    {
      front: 'Heißt es "Adresse" oder "Addresse"?',
      back: 'Adresse – mit einem d und Doppel-s. Häufiger Fehler: "Addresse" (doppeltes d) oder "Adrese" (einfaches s).',
    },
    {
      front: 'Heißt es "Rythmus" oder "Rhythmus"?',
      back: 'Rhythmus – mit rh, y und th. Das Wort stammt aus dem Griechischen. Häufige Fehler: "Rythmus", "Rhythhmus".',
    },
    {
      front: 'Wann schreibt man Nomen (Substantive) groß?',
      back: 'Nomen schreibt man immer groß. Das gilt auch für substantivierte Verben und Adjektive: das Laufen, das Gute, das Beste, das Schreiben.',
    },
    {
      front: 'Wie lautet die Regel zur Höflichkeitsform "Sie"?',
      back: 'Das Anrede-Pronomen "Sie" (formelle Anrede) und die zugehörigen Formen "Ihr", "Ihnen", "Ihre" schreibt man groß. Das Personalpronomen "sie" (3. Person Plural) bleibt klein.',
    },
    {
      front: 'Unterschied: "seit" vs. "seid"',
      back: '"Seit" ist eine Präposition oder Konjunktion der Zeit: "seit drei Jahren". "Seid" ist die 2. Person Plural von "sein": "Ihr seid pünktlich." Merkhilfe: se-i-d → se-i-n.',
    },
    {
      front: 'Unterschied: "wider" vs. "wieder"',
      back: '"Wider" bedeutet "gegen" (widersprechen, widerrufen). "Wieder" bedeutet "erneut" oder "zurück" (wiederkommen, wieder arbeiten). Merkhilfe: wieder = wie + der (zeitlich).',
    },
    {
      front: 'Heißt es "Tip" oder "Tipp"?',
      back: 'Tipp – mit Doppel-p (nach kurzem i). Ebenso: tippen. Häufiger Fehler: "Tip" (ein p). Im Englischen ist "tip" korrekt, im Deutschen gilt "Tipp".',
    },
    {
      front: 'Schreibt man "Stress" oder "Streß"?',
      back: 'Stress – mit Doppel-s am Ende (nach kurzem e). Häufiger Fehler: "Streß" (veraltete Schreibweise vor der Rechtschreibreform 1996).',
    },
    {
      front: 'Wann werden Adjektive großgeschrieben?',
      back: 'Adjektive werden großgeschrieben, wenn sie substantiviert (nominalisiert) werden: "das Gute", "alles Wichtige", "nichts Neues", "der Erste". In festen Eigennamen: "die Alte Welt".',
    },
    {
      front: 'Was bedeutet Substantivierung und wie erkennt man sie?',
      back: 'Substantivierung = Verben, Adjektive oder andere Wortarten werden wie Nomen verwendet. Erkennungszeichen: Ein Artikel (der, die, das) oder Pronomen (alles, nichts, etwas) steht davor. Beispiel: "das Schreiben", "etwas Schönes".',
    },
    {
      front: 'Heißt es "Standard" oder "Standart"?',
      back: 'Standard – mit st am Anfang und ohne h. Häufige Fehler: "Standart" (mit t am Ende) ist falsch. Merkhilfe: Standard → Norm, kein "Standart".',
    },
    {
      front: 'Wann schreibt man Verben nach "beim" groß?',
      back: 'Beim + substantiviertes Verb → Großschreibung: "beim Laufen", "beim Schreiben", "beim Essen". Das Verb wird zum Nomen (Gerundium) und erhält daher einen Großbuchstaben.',
    },
    {
      front: 'Wie lautet die ss/ß-Regel nach der Rechtschreibreform (1996)?',
      back: 'Nach kurzen Vokalen → ss: Fluss, Schloss, muss, dass. Nach langen Vokalen und Diphthongen → ß: Straße, Maß, heiß, außen. Das "ß" in Großbuchstaben: SS (z. B. STRASSE) oder ẞ.',
    },
    {
      front: 'Heißt es "empfelen" oder "empfehlen"?',
      back: 'Empfehlen – mit pf und ohne h nach dem e: empfehlen, ich empfehle, Empfehlung. Häufige Fehler: "Empfelung" (ein l), "Empfhelen".',
    },
    {
      front: 'Was ist der Unterschied zwischen "als" und "wie" beim Vergleich?',
      back: '"Als" steht bei Ungleichheit: "Er ist größer als ich." "Wie" steht bei Gleichheit: "Er ist so groß wie ich." Häufiger Fehler: "größer wie ich" ist umgangssprachlich, aber standardsprachlich falsch.',
    },
    {
      front: 'Wie schreibt man Farben als Nomen?',
      back: 'Farben als Nomen werden großgeschrieben: "das Rot der Ampel", "in Blau gekleidet", "ein leuchtendes Grün". Als Adjektiv klein: "das rote Auto", "blaue Augen".',
    },
  ],
  questions: [
    {
      type: 'mc',
      prompt: 'Welches Wort ist richtig geschrieben?',
      options: ['Adresse', 'Addresse', 'Adresze', 'Addrese'],
      correct: [0],
      explanation: 'Adresse schreibt man mit einem d und Doppel-s.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist richtig: "Ich hoffe, ___ du kommst."',
      options: ['dass', 'das', 'daß', 'dasz'],
      correct: [0],
      explanation: 'Als Konjunktion steht "dass" – es lässt sich nicht durch "dieses" ersetzen.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welcher Satz verwendet "das" korrekt?',
      options: [
        'Ich weiß, das er kommt.',
        'Das Buch, das ich lese, ist spannend.',
        'Sie sagt, das alles gut wird.',
        'Er hofft, das sie gewinnt.',
      ],
      correct: [1],
      explanation: '"Das Buch, das ich lese" – hier ist "das" ein Relativpronomen (= welches ich lese). In den anderen Sätzen wäre "dass" korrekt.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Wie lautet die korrekte Schreibweise?',
      options: ['Rythmus', 'Rhythhmus', 'Rhythmus', 'Rhytmus'],
      correct: [2],
      explanation: 'Rhythmus schreibt man mit rh, y und th – griechische Herkunft.',
      difficulty: 2,
    },
    {
      type: 'truefalse',
      prompt: '"Seit" und "seid" können in jedem Satz austauschbar verwendet werden.',
      options: ['Richtig', 'Falsch'],
      correct: [1],
      explanation: '"Seit" ist eine Präposition/Konjunktion (zeitlich), "seid" ist die 2. Person Plural von "sein". Sie sind NICHT austauschbar.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welcher Satz ist korrekt?',
      options: [
        'Ihr seid seit langer Zeit nicht mehr hier gewesen.',
        'Ihr seit seid langer Zeit nicht mehr hier gewesen.',
        'Ihr seid seid langer Zeit nicht mehr hier gewesen.',
        'Ihr seit seit langer Zeit nicht mehr hier gewesen.',
      ],
      correct: [0],
      explanation: '"seid" = Verb (ihr seid), "seit" = Präposition (seit langer Zeit). Beides richtig kombiniert ergibt den korrekten Satz.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welches Wort ist FALSCH geschrieben?',
      options: ['Stress', 'Fluss', 'Straße', 'Standart'],
      correct: [3],
      explanation: '"Standart" ist falsch – korrekt ist "Standard" (aus dem Englischen/Französischen, mit d am Ende).',
      difficulty: 1,
    },
    {
      type: 'fill',
      prompt: 'Ergänzen Sie: "Ich gehe ___ Laufen." (Präposition + substantiviertes Verb)',
      correct: ['zum Laufen'],
      explanation: 'Substantivierte Verben schreibt man groß: "zum Laufen". Das Verb "laufen" wird hier zum Nomen.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welcher Satz enthält eine korrekt großgeschriebene Substantivierung?',
      options: [
        'Das laufen macht Spaß.',
        'Das Laufen macht Spaß.',
        'das Laufen macht Spaß.',
        'das laufen macht Spaß.',
      ],
      correct: [1],
      explanation: 'Substantivierte Verben schreibt man groß: "das Laufen". Außerdem beginnt ein Satz mit einem Großbuchstaben.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Wie wird "Tipp" (Ratschlag) korrekt geschrieben?',
      options: ['Tip', 'Tipp', 'Tiipp', 'Typp'],
      correct: [1],
      explanation: 'Im Deutschen schreibt man "Tipp" mit Doppel-p (kurzes i → Konsonantenverdopplung). "Tip" ist die englische Schreibweise.',
      difficulty: 1,
    },
    {
      type: 'truefalse',
      prompt: 'Das ß wird nach der Rechtschreibreform nach kurzem Vokal verwendet (z. B. "Fluß").',
      options: ['Richtig', 'Falsch'],
      correct: [1],
      explanation: 'Seit der Rechtschreibreform 1996 gilt: Nach kurzem Vokal steht ss (Fluss), nach langem Vokal/Diphthong steht ß (Straße).',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welches Wort schreibt man mit ß?',
      options: ['Fluss', 'muss', 'Strasse', 'heiß'],
      correct: [3],
      explanation: '"heiß" hat einen Diphthong (ei) → ß. "Fluss" und "muss" haben kurze Vokale → ss. "Strasse" ist falsch, korrekt ist "Straße".',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welcher Satz ist orthografisch korrekt?',
      options: [
        'Sie wiedersprach dem Vorschlag.',
        'Sie widersprach dem Vorschlag.',
        'Sie wiedersprechen dem Vorschlag.',
        'Sie widerspricht dem Vorschlag nicht wider.',
      ],
      correct: [1],
      explanation: '"widersprechen" verwendet "wider" (= gegen), nicht "wieder" (= erneut). Also: "Sie widersprach".',
      difficulty: 2,
    },
    {
      type: 'fill',
      prompt: 'Schreiben Sie das Wort für "Rhythmus" korrekt aus.',
      correct: ['Rhythmus'],
      explanation: 'Rhythmus – rh, y, th, u, s. Griechische Herkunft. Kein "Rythmus" oder "Rhythhmus".',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welche Schreibweise der Höflichkeitsform ist korrekt?',
      options: [
        'Können sie mir helfen?',
        'Können Sie mir helfen?',
        'Können SIE mir helfen?',
        'können Sie mir helfen?',
      ],
      correct: [1],
      explanation: 'Das Anrede-Pronomen "Sie" (formelle Anrede) schreibt man groß. Der Satzanfang wird ebenfalls großgeschrieben.',
      difficulty: 1,
    },
    {
      type: 'truefalse',
      prompt: '"Ihr" in der Bedeutung von "euer" (2. Person Plural Possessivpronomen) wird groß geschrieben, wenn es als Höflichkeitsanrede verwendet wird.',
      options: ['Richtig', 'Falsch'],
      correct: [0],
      explanation: 'In der förmlichen Anrede wird "Ihr" (= Ihr Brief, Ihre Daten) großgeschrieben. Als normales Possessivpronomen (euer) bleibt es klein.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Welches Wort enthält ein Dehnungs-h?',
      options: ['Stahl', 'Straße', 'Stress', 'stark'],
      correct: [0],
      explanation: '"Stahl" enthält ein Dehnungs-h (nach dem langen a, vor l). Bei "Straße", "Stress" und "stark" gibt es kein Dehnungs-h.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welche Wörter enthalten ein Dehnungs-h? (Wählen Sie die korrekte Aussage)',
      options: [
        'fahren, Wahl, nehmen – alle drei haben Dehnungs-h',
        'fahren, Wahl, nehmen – keines hat Dehnungs-h',
        'Nur "fahren" hat ein Dehnungs-h',
        'Nur "Wahl" hat ein Dehnungs-h',
      ],
      correct: [0],
      explanation: 'Alle drei: fahren (fah-ren), Wahl (Wahl), nehmen (neh-men) haben ein Dehnungs-h vor l, r bzw. m.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: '"Nichts ___ passiert." – Welche Schreibweise ist korrekt?',
      options: ['Schlimmes', 'schlimmes', 'Schlimms', 'schlimms'],
      correct: [0],
      explanation: 'Nach "nichts" wird das Adjektiv substantiviert und daher großgeschrieben: "nichts Schlimmes".',
      difficulty: 2,
    },
    {
      type: 'truefalse',
      prompt: '"Alles gute zum Geburtstag" ist korrekt geschrieben.',
      options: ['Richtig', 'Falsch'],
      correct: [1],
      explanation: 'Nach "alles" wird das Adjektiv substantiviert: "Alles Gute" – Großschreibung ist erforderlich.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welcher Vergleichssatz ist standardsprachlich korrekt?',
      options: [
        'Er läuft schneller wie ich.',
        'Er läuft schneller als ich.',
        'Er läuft schneller wie als ich.',
        'Er läuft so schnell als ich.',
      ],
      correct: [1],
      explanation: 'Bei Ungleichheit steht "als": "schneller als ich". "Wie" steht nur bei Gleichheit: "so schnell wie ich".',
      difficulty: 2,
    },
    {
      type: 'fill',
      prompt: 'Vervollständigen Sie: "Er hat sie ___ drei Jahren nicht gesehen." (seit/seid)',
      correct: ['seit'],
      explanation: '"seit" ist die Präposition für Zeitangaben. "Seid" wäre die Verbform von "sein" (2. Person Plural).',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welches Wort ist korrekt geschrieben?',
      options: ['Empfehlung', 'Empfelung', 'Empfhlung', 'Emfehlung'],
      correct: [0],
      explanation: '"Empfehlung" – mit pf, eh (Dehnungs-h) und ll. Abgeleitet von "empfehlen".',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welcher Satz verwendet "wieder" korrekt?',
      options: [
        'Er handelte der Anweisung wieder.',
        'Sie kam wieder nach Hause.',
        'Das ist wider meinen Erwartungen.',
        'Wider sehen macht Freude.',
      ],
      correct: [1],
      explanation: '"wieder nach Hause kommen" = erneut/zurück → "wieder". "widersprechen", "widerrufen" verwenden "wider" (= gegen).',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Wie wird das Wort für "gegensätzlich/entgegen" korrekt geschrieben?',
      options: ['wiedersprüchlich', 'widersprüchlich', 'wiederspüchlich', 'widerspüchlich'],
      correct: [1],
      explanation: '"widersprüchlich" – mit "wider" (= gegen). Das Präfix "wider-" bedeutet "gegen" oder "entgegen".',
      difficulty: 2,
    },
    {
      type: 'truefalse',
      prompt: '"Das Beste ist gerade gut genug." – "Beste" ist hier korrekt großgeschrieben.',
      options: ['Richtig', 'Falsch'],
      correct: [0],
      explanation: '"das Beste" – nach dem Artikel "das" wird das Adjektiv substantiviert und daher großgeschrieben.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welches Wort wird mit ss geschrieben?',
      options: ['Maß', 'heiß', 'Fluss', 'Straße'],
      correct: [2],
      explanation: '"Fluss" hat einen kurzen Vokal (u) → ss. "Maß", "heiß", "Straße" haben lange Vokale oder Diphthonge → ß.',
      difficulty: 1,
    },
    {
      type: 'fill',
      prompt: 'Schreiben Sie das Substantiv: "Sie gab mir einen guten ___." (Ratschlag, englisch: tip)',
      correct: ['Tipp'],
      explanation: 'Im Deutschen schreibt man "Tipp" mit Doppel-p. "Tip" ist die englische Schreibweise.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welche Schreibweise von "Standard" ist korrekt?',
      options: ['Standard', 'Standart', 'Standardd', 'Stanndard'],
      correct: [0],
      explanation: '"Standard" endet auf -ard (nicht -art). Das Wort kommt aus dem Englischen/Französischen.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'In welchem Satz ist die Groß-/Kleinschreibung vollständig korrekt?',
      options: [
        'beim schreiben muss man auf die rechtschreibung achten.',
        'Beim Schreiben muss man auf die Rechtschreibung achten.',
        'Beim schreiben muss man auf die Rechtschreibung achten.',
        'beim Schreiben muss man auf die rechtschreibung achten.',
      ],
      correct: [1],
      explanation: '"Beim Schreiben" – substantiviertes Verb → groß. "Rechtschreibung" – Nomen → groß. Satzanfang → groß.',
      difficulty: 2,
    },
    {
      type: 'truefalse',
      prompt: 'Nach der deutschen Rechtschreibung schreibt man "daß" immer noch mit ß.',
      options: ['Richtig', 'Falsch'],
      correct: [1],
      explanation: 'Seit der Rechtschreibreform 1996 gilt: "dass" wird mit ss geschrieben, da der Vokal kurz ist. Die alte Schreibung "daß" ist veraltet.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welches Wort ist korrekt geschrieben?',
      options: ['Wiederruf', 'Widerruf', 'Wiederuf', 'Wideruf'],
      correct: [1],
      explanation: '"Widerruf" – mit "wider" (= gegen/zurück) und Doppel-r (wider + rufen → Widerruf). Nicht "wieder" (= erneut).',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Wie wird "etwas ___ erzählen" (Neues) korrekt geschrieben?',
      options: [
        'etwas neues erzählen',
        'etwas Neues erzählen',
        'Etwas Neues erzählen',
        'etwas NEUES erzählen',
      ],
      correct: [1],
      explanation: 'Nach "etwas" wird das Adjektiv substantiviert: "etwas Neues" – Großschreibung. "Etwas" am Satzanfang würde auch großgeschrieben, aber hier steht es in der Satzmitte.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welche Aussage über das Dehnungs-h ist FALSCH?',
      options: [
        'Es steht vor l, m, n, r um einen langen Vokal anzuzeigen.',
        'Beispiele sind: fahren, Stuhl, nehmen.',
        'Es steht grundsätzlich nach jedem langen Vokal.',
        'Es fehlt in Wörtern wie "Weg" oder "Tag".',
      ],
      correct: [2],
      explanation: 'Das Dehnungs-h steht NUR vor bestimmten Konsonanten (l, m, n, r), nicht grundsätzlich nach jedem langen Vokal. "Weg" und "Tag" haben lange Vokale, aber kein Dehnungs-h.',
      difficulty: 3,
    },
    {
      type: 'fill',
      prompt: 'Ergänzen Sie korrekt: "Könnten ___ mir bitte Ihren Namen nennen?" (Höflichkeitsanrede)',
      correct: ['Sie'],
      explanation: 'Das Höflichkeitspronomen "Sie" (formelle Anrede) schreibt man immer groß, auch in der Satzmitte.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welcher Satz ist korrekt?',
      options: [
        'Das war das beste was ich je gesehen habe.',
        'Das war das Beste, was ich je gesehen habe.',
        'das war das Beste, was ich je gesehen habe.',
        'Das war Das Beste, was ich je gesehen habe.',
      ],
      correct: [1],
      explanation: '"das Beste" – Superlativ nach Artikel, substantiviert → Großschreibung. Komma vor "was" (Relativsatz). Satzanfang groß.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welches der folgenden Wörter ist FALSCH geschrieben?',
      options: ['Empfehlung', 'Rhythmus', 'Adresse', 'Streß'],
      correct: [3],
      explanation: '"Streß" ist die veraltete Schreibweise. Seit der Rechtschreibreform 1996 schreibt man "Stress" mit ss (kurzer Vokal e).',
      difficulty: 1,
    },
    {
      type: 'truefalse',
      prompt: 'In dem Satz "Sie haben Ihre Unterlagen vergessen" ist "Ihre" korrekt großgeschrieben.',
      options: ['Richtig', 'Falsch'],
      correct: [0],
      explanation: '"Ihre" ist hier die Höflichkeitsform (formelle Anrede) und wird daher großgeschrieben. In der normalen 3. Person wäre "ihre" kleingeschrieben.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welcher Satz ist grammatikalisch und orthografisch korrekt?',
      options: [
        'Er ist schneller als ich gedacht hatte.',
        'Er ist schneller wie ich gedacht hatte.',
        'Er ist schneller als wie ich gedacht hatte.',
        'Er ist so schnell als ich gedacht hatte.',
      ],
      correct: [0],
      explanation: 'Bei Ungleichheit steht "als" – also "schneller als". "Wie" verwendet man nur bei Gleichheit (so … wie).',
      difficulty: 2,
    },
  ],
};

export default topic;
