import type { RawTopic } from '../types';

const topic: RawTopic = {
  slug: 'recht',
  title: 'Recht',
  description: 'Rechtsgebiete, BGB und Geschäftsfähigkeit.',
  flashcards: [
    {
      front: 'Was ist der Unterschied zwischen öffentlichem Recht und Privatrecht?',
      back: 'Öffentliches Recht regelt Beziehungen zwischen Staat und Bürger (Über-/Unterordnungsverhältnis). Privatrecht regelt Beziehungen zwischen gleichgestellten Rechtssubjekten (Bürger untereinander).',
    },
    {
      front: 'Welche 5 Bücher enthält das BGB?',
      back: '1. Buch: Allgemeiner Teil; 2. Buch: Schuldrecht; 3. Buch: Sachenrecht; 4. Buch: Familienrecht; 5. Buch: Erbrecht.',
    },
    {
      front: 'Was bedeutet Geschäftsunfähigkeit und ab wann liegt sie vor?',
      back: 'Geschäftsunfähige können keine wirksamen Willenserklärungen abgeben. Kinder unter 7 Jahren sind geschäftsunfähig (§ 104 BGB).',
    },
    {
      front: 'Was regelt § 106 BGB?',
      back: '§ 106 BGB regelt die beschränkte Geschäftsfähigkeit: Minderjährige vom vollendeten 7. bis zum vollendeten 17. Lebensjahr sind beschränkt geschäftsfähig.',
    },
    {
      front: 'Was ist der "Taschengeldparagraph" (§ 110 BGB)?',
      back: 'Ein von einem beschränkt Geschäftsfähigen ohne Einwilligung der Eltern geschlossener Vertrag gilt als wirksam, wenn er mit Mitteln bewirkt wird, die ihm zu diesem Zweck oder zur freien Verfügung überlassen wurden.',
    },
    {
      front: 'Ab welchem Alter ist man in Deutschland strafrechtlich voll verantwortlich?',
      back: 'Ab 18 Jahren gilt man als Erwachsener im Strafrecht. Zwischen 14 und 17 Jahren gilt das Jugendstrafrecht (Jugendgerichtsgesetz, JGG).',
    },
    {
      front: 'Was ist Deliktsfähigkeit?',
      back: 'Deliktsfähigkeit ist die Fähigkeit, für unerlaubte Handlungen (Delikte) zivilrechtlich haftbar zu sein. Kinder unter 7 Jahren sind nicht deliktsfähig (§ 828 BGB).',
    },
    {
      front: 'Was ist Strafmündigkeit und ab welchem Alter besteht sie?',
      back: 'Strafmündigkeit ist die Fähigkeit, strafrechtlich zur Verantwortung gezogen zu werden. In Deutschland beginnt sie mit Vollendung des 14. Lebensjahres (§ 19 StGB).',
    },
    {
      front: 'Was ist der Unterschied zwischen einem Vergehen und einem Verbrechen im Strafrecht?',
      back: 'Verbrechen sind Taten mit einer Mindeststrafe von 1 Jahr Freiheitsstrafe (§ 12 Abs. 1 StGB). Vergehen sind Taten mit einer geringeren Mindeststrafe oder Geldstrafe (§ 12 Abs. 2 StGB).',
    },
    {
      front: 'Was versteht man unter Vertragsfreiheit?',
      back: 'Vertragsfreiheit ist der Grundsatz, dass jeder frei entscheiden kann, ob, mit wem und zu welchen Bedingungen er einen Vertrag abschließt (Abschlussfreiheit, Inhaltsfreiheit, Formfreiheit).',
    },
    {
      front: 'Was ist das Amtsgericht und welche Zuständigkeit hat es?',
      back: 'Das Amtsgericht ist das unterste Gericht der ordentlichen Gerichtsbarkeit. Es ist zuständig für Zivilsachen bis 5.000 Euro Streitwert, Strafsachen mit geringer Schwere, Familiensachen und Erbsachen.',
    },
    {
      front: 'Wie ist der Instanzenzug der ordentlichen Gerichtsbarkeit in Deutschland?',
      back: 'Amtsgericht (1. Instanz) → Landgericht (2. Instanz / Berufung) → Oberlandesgericht (3. Instanz / Revision) → Bundesgerichtshof (BGH, höchste Instanz).',
    },
    {
      front: 'Was ist Verwaltungsrecht?',
      back: 'Das Verwaltungsrecht ist ein Teilgebiet des öffentlichen Rechts und regelt die Tätigkeit der Verwaltungsbehörden sowie die Rechtsbeziehungen zwischen Behörden und Bürgern.',
    },
    {
      front: 'Was regelt das Schuldrecht (2. Buch BGB)?',
      back: 'Das Schuldrecht regelt Schuldverhältnisse, also rechtliche Beziehungen, aus denen eine Partei von der anderen eine Leistung fordern kann (z.B. Kauf, Miete, Darlehen, Schadensersatz).',
    },
    {
      front: 'Ab welchem Alter ist man in Deutschland volljährig?',
      back: 'In Deutschland tritt die Volljährigkeit mit Vollendung des 18. Lebensjahres ein (§ 2 BGB). Damit erlangt man die volle Geschäftsfähigkeit.',
    },
    {
      front: 'Was ist das Strafgesetzbuch (StGB)?',
      back: 'Das StGB ist das zentrale Gesetz des deutschen Strafrechts. Es enthält den Allgemeinen Teil (Grundlagen der Strafbarkeit) und den Besonderen Teil (konkrete Straftatbestände wie Diebstahl, Betrug, Körperverletzung).',
    },
    {
      front: 'Was regelt das Sachenrecht (3. Buch BGB)?',
      back: 'Das Sachenrecht regelt die Rechtsbeziehungen von Personen zu Sachen, insbesondere Eigentum, Besitz, Pfandrecht und Grundpfandrechte (z.B. Hypothek, Grundschuld).',
    },
    {
      front: 'Was ist der Unterschied zwischen Zivilrecht und Strafrecht?',
      back: 'Zivilrecht regelt private Rechtsbeziehungen zwischen gleichgeordneten Personen (z.B. Verträge, Schadensersatz). Strafrecht ist öffentliches Recht und regelt staatliche Reaktionen auf strafbare Handlungen (Strafe, Geldstrafe, Freiheitsstrafe).',
    },
    {
      front: 'Was ist ein Verwaltungsakt?',
      back: 'Ein Verwaltungsakt ist eine hoheitliche Maßnahme einer Behörde zur Regelung eines Einzelfalls im öffentlich-rechtlichen Bereich (§ 35 VwVfG). Beispiel: Baugenehmigung, Bußgeldbescheid.',
    },
    {
      front: 'Was ist das Bundesverwaltungsgericht?',
      back: 'Das Bundesverwaltungsgericht (BVerwG) in Leipzig ist das oberste Gericht der Verwaltungsgerichtsbarkeit in Deutschland. Es entscheidet über Revisionen gegen Urteile der Oberverwaltungsgerichte.',
    },
  ],
  questions: [
    {
      type: 'mc',
      prompt: 'Ab welchem Alter ist man in Deutschland voll geschäftsfähig?',
      options: ['18 Jahre', '14 Jahre', '16 Jahre', '21 Jahre'],
      correct: [0],
      explanation: 'Mit Vollendung des 18. Lebensjahres ist man volljährig und voll geschäftsfähig (§ 2 BGB).',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Kinder unter welchem Alter sind nach § 104 BGB geschäftsunfähig?',
      options: ['14 Jahren', '7 Jahren', '10 Jahren', '6 Jahren'],
      correct: [1],
      explanation: 'Gemäß § 104 Nr. 1 BGB sind Kinder, die das 7. Lebensjahr noch nicht vollendet haben, geschäftsunfähig.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welcher Paragraph des BGB regelt die beschränkte Geschäftsfähigkeit Minderjähriger?',
      options: ['§ 110 BGB', '§ 104 BGB', '§ 106 BGB', '§ 828 BGB'],
      correct: [2],
      explanation: '§ 106 BGB regelt die beschränkte Geschäftsfähigkeit von Minderjährigen zwischen dem 7. und dem vollendeten 17. Lebensjahr.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was regelt der sogenannte "Taschengeldparagraph" § 110 BGB?',
      options: [
        'Die Pflicht der Eltern, ihrem Kind Taschengeld zu zahlen',
        'Die Wirksamkeit von Verträgen, die Minderjährige mit eigenen Mitteln erfüllen',
        'Das Recht Minderjähriger auf ein eigenes Bankkonto',
        'Die Strafbarkeit bei Missbrauch von Taschengeld',
      ],
      correct: [1],
      explanation: '§ 110 BGB bestimmt, dass ein Vertrag eines beschränkt Geschäftsfähigen als wirksam gilt, wenn er mit ihm zur Verfügung gestellten Mitteln erfüllt wird.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Ab welchem Alter beginnt in Deutschland die Strafmündigkeit?',
      options: ['16 Jahren', '18 Jahren', '12 Jahren', '14 Jahren'],
      correct: [3],
      explanation: 'Gemäß § 19 StGB ist schuldlos, wer bei Begehung der Tat noch nicht 14 Jahre alt ist. Ab 14 Jahren beginnt die Strafmündigkeit.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welches ist das Merkmal, das ein Verbrechen von einem Vergehen unterscheidet?',
      options: [
        'Verbrechen erfordern Vorsatz, Vergehen können fahrlässig begangen werden',
        'Verbrechen sind nur solche gegen den Staat',
        'Verbrechen haben eine Mindestfreiheitsstrafe von 1 Jahr',
        'Verbrechen werden nur vom Bundesgerichtshof verhandelt',
      ],
      correct: [2],
      explanation: 'Nach § 12 Abs. 1 StGB sind Verbrechen rechtswidrige Taten, die im Mindestmaß mit Freiheitsstrafe von einem Jahr oder darüber bedroht sind.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Zu welchem Rechtsgebiet gehört das Bürgerliche Gesetzbuch (BGB)?',
      options: ['Öffentliches Recht', 'Strafrecht', 'Privatrecht', 'Verwaltungsrecht'],
      correct: [2],
      explanation: 'Das BGB ist das zentrale Gesetz des deutschen Privatrechts (Zivilrechts) und regelt Rechtsverhältnisse zwischen gleichgeordneten Rechtssubjekten.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Aus wie vielen Büchern besteht das BGB?',
      options: ['3', '4', '6', '5'],
      correct: [3],
      explanation: 'Das BGB besteht aus 5 Büchern: Allgemeiner Teil, Schuldrecht, Sachenrecht, Familienrecht und Erbrecht.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welches Buch des BGB regelt Kaufverträge und Schadensersatzansprüche?',
      options: ['1. Buch (Allgemeiner Teil)', '4. Buch (Familienrecht)', '3. Buch (Sachenrecht)', '2. Buch (Schuldrecht)'],
      correct: [3],
      explanation: 'Das 2. Buch des BGB (Schuldrecht) regelt Schuldverhältnisse wie Kauf, Miete, Werkvertrag und Schadensersatz.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welches Gericht ist in der ordentlichen Gerichtsbarkeit die höchste Instanz?',
      options: ['Oberlandesgericht', 'Bundesverwaltungsgericht', 'Landgericht', 'Bundesgerichtshof'],
      correct: [3],
      explanation: 'Der Bundesgerichtshof (BGH) in Karlsruhe ist das oberste Gericht der ordentlichen Gerichtsbarkeit in Deutschland.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welches Gericht ist in Zivilsachen bis 5.000 Euro Streitwert erstinstanzlich zuständig?',
      options: ['Landgericht', 'Oberlandesgericht', 'Amtsgericht', 'Arbeitsgericht'],
      correct: [2],
      explanation: 'Das Amtsgericht ist erstinstanzlich für Zivilsachen zuständig, wenn der Streitwert 5.000 Euro nicht übersteigt (§ 23 GVG).',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welchem Rechtsgebiet ist das Strafgesetzbuch (StGB) zuzuordnen?',
      options: ['Privatrecht', 'Zivilrecht', 'Öffentliches Recht', 'Handelsrecht'],
      correct: [2],
      explanation: 'Das Strafrecht ist ein Teilgebiet des öffentlichen Rechts. Der Staat verfolgt Straftäter im öffentlichen Interesse.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was versteht man unter dem Begriff "Deliktsfähigkeit"?',
      options: [
        'Die Fähigkeit, Straftaten zu begehen',
        'Die Fähigkeit, zivilrechtlich für unerlaubte Handlungen zu haften',
        'Die Fähigkeit, vor Gericht zu klagen',
        'Die Fähigkeit, Verträge abzuschließen',
      ],
      correct: [1],
      explanation: 'Deliktsfähigkeit (§ 828 BGB) bezeichnet die Fähigkeit, für unerlaubte Handlungen zivilrechtlich auf Schadensersatz in Anspruch genommen zu werden.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welches Gericht ist für die Berufung gegen ein Urteil des Amtsgerichts in Zivilsachen zuständig?',
      options: ['Oberlandesgericht', 'Bundesgerichtshof', 'Landgericht', 'Verwaltungsgericht'],
      correct: [2],
      explanation: 'Das Landgericht ist die Berufungsinstanz für Urteile des Amtsgerichts in Zivilsachen.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welche der folgenden Aussagen zur Vertragsfreiheit ist korrekt?',
      options: [
        'Vertragsfreiheit gilt nur für Kaufleute',
        'Jeder kann frei entscheiden, ob und mit wem er einen Vertrag abschließt',
        'Verträge müssen stets schriftlich geschlossen werden',
        'Vertragsfreiheit ist im Strafgesetzbuch verankert',
      ],
      correct: [1],
      explanation: 'Die Vertragsfreiheit umfasst die Abschlussfreiheit (ob), die Partnerwahlfreiheit (mit wem) und die Inhaltsfreiheit (zu welchen Bedingungen). Sie gilt grundsätzlich für alle Privatpersonen.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Ein 8-jähriges Kind kauft allein ohne Wissen der Eltern ein Computerspiel für 30 Euro und bezahlt es mit eigenem Taschengeld. Was gilt rechtlich?',
      options: [
        'Der Vertrag ist nichtig, weil das Kind minderjährig ist',
        'Der Vertrag ist wirksam gemäß § 110 BGB (Taschengeldparagraph)',
        'Der Vertrag ist schwebend unwirksam bis zur elterlichen Genehmigung',
        'Der Vertrag ist nur wirksam, wenn das Spiel altersgerecht ist',
      ],
      correct: [1],
      explanation: 'Da das Kind den Kaufpreis vollständig mit eigenen Mitteln bezahlt hat, ist der Vertrag nach § 110 BGB wirksam.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Welchem Rechtsgebiet ist das Verwaltungsrecht zuzuordnen?',
      options: ['Privatrecht', 'Zivilrecht', 'Handelsrecht', 'Öffentliches Recht'],
      correct: [3],
      explanation: 'Das Verwaltungsrecht ist ein Teilgebiet des öffentlichen Rechts und regelt die Beziehungen zwischen Behörden und Bürgern.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist ein Verwaltungsakt gemäß § 35 VwVfG?',
      options: [
        'Ein Gesetz, das die Regierung erlässt',
        'Ein Vertrag zwischen zwei Behörden',
        'Eine hoheitliche Maßnahme einer Behörde zur Regelung eines Einzelfalls',
        'Ein Urteil des Verwaltungsgerichts',
      ],
      correct: [2],
      explanation: 'Ein Verwaltungsakt ist eine hoheitliche Maßnahme einer Behörde zur Regelung eines Einzelfalls mit Außenwirkung (§ 35 VwVfG), z.B. eine Baugenehmigung oder ein Bußgeldbescheid.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welche Gerichtsbarkeit ist für Streitigkeiten zwischen Arbeitnehmer und Arbeitgeber zuständig?',
      options: ['Ordentliche Gerichtsbarkeit', 'Verwaltungsgerichtsbarkeit', 'Finanzgerichtsbarkeit', 'Arbeitsgerichtsbarkeit'],
      correct: [3],
      explanation: 'Für Streitigkeiten aus dem Arbeitsverhältnis ist die Arbeitsgerichtsbarkeit zuständig (Arbeitsgericht → Landesarbeitsgericht → Bundesarbeitsgericht).',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welches ist das 4. Buch des BGB?',
      options: ['Sachenrecht', 'Schuldrecht', 'Erbrecht', 'Familienrecht'],
      correct: [3],
      explanation: 'Das 4. Buch des BGB regelt das Familienrecht (z.B. Ehe, Unterhalt, elterliche Sorge). Das 5. Buch behandelt das Erbrecht.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Ein 16-jähriger schließt ohne Einwilligung der Eltern einen Handyvertrag ab. Welchen rechtlichen Status hat dieser Vertrag zunächst?',
      options: [
        'Nichtig',
        'Sofort wirksam',
        'Schwebend unwirksam',
        'Wirksam nach 14 Tagen',
      ],
      correct: [2],
      explanation: 'Verträge beschränkt Geschäftsfähiger ohne Einwilligung der Eltern sind schwebend unwirksam und werden erst mit nachträglicher Genehmigung der Eltern wirksam (§ 108 BGB).',
      difficulty: 3,
    },
    {
      type: 'truefalse',
      prompt: 'Das Strafrecht ist dem Privatrecht zuzuordnen.',
      options: ['Wahr', 'Falsch'],
      correct: [1],
      explanation: 'Das Strafrecht ist ein Teilgebiet des öffentlichen Rechts, nicht des Privatrechts. Es regelt das Verhältnis zwischen Staat und Bürger.',
      difficulty: 1,
    },
    {
      type: 'truefalse',
      prompt: 'Ein 6-jähriges Kind ist nach dem BGB geschäftsunfähig.',
      options: ['Wahr', 'Falsch'],
      correct: [0],
      explanation: 'Kinder, die das 7. Lebensjahr noch nicht vollendet haben, sind gemäß § 104 Nr. 1 BGB geschäftsunfähig.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welches Gericht ist oberstes Gericht der Verwaltungsgerichtsbarkeit?',
      options: ['Bundesverfassungsgericht', 'Bundesgerichtshof', 'Oberverwaltungsgericht', 'Bundesverwaltungsgericht'],
      correct: [3],
      explanation: 'Das Bundesverwaltungsgericht (BVerwG) in Leipzig ist das oberste Gericht der Verwaltungsgerichtsbarkeit in Deutschland.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was ist die Mindestfreiheitsstrafe, ab der eine Tat als Verbrechen gilt?',
      options: ['6 Monate', '2 Jahre', '1 Jahr', '3 Jahre'],
      correct: [2],
      explanation: 'Verbrechen sind nach § 12 Abs. 1 StGB Taten, die im Mindestmaß mit Freiheitsstrafe von einem Jahr bedroht sind.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welcher Grundsatz besagt, dass Verträge grundsätzlich formfrei geschlossen werden können?',
      options: ['Vertragsfreiheit', 'Privatautonomie', 'Formfreiheit', 'Vertragsautonomie'],
      correct: [2],
      explanation: 'Der Grundsatz der Formfreiheit besagt, dass Verträge grundsätzlich auch mündlich oder durch schlüssiges Verhalten geschlossen werden können. Er ist Teil der Vertragsfreiheit.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Welche Aussage zur beschränkten Geschäftsfähigkeit ist korrekt?',
      options: [
        'Beschränkt Geschäftsfähige können keinerlei Verträge abschließen',
        'Beschränkt Geschäftsfähige können lediglich vorteilhafte Rechtsgeschäfte ohne Einwilligung der Eltern vornehmen',
        'Beschränkt Geschäftsfähige sind voll für ihre Handlungen haftbar',
        'Beschränkt Geschäftsfähige sind Personen zwischen 14 und 21 Jahren',
      ],
      correct: [1],
      explanation: 'Beschränkt Geschäftsfähige (7–17 Jahre) können lediglich rechtlich vorteilhafte Geschäfte (z.B. eine Schenkung annehmen) ohne Einwilligung der Eltern wirksam vornehmen (§ 107 BGB).',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'In welchem Gesetz ist das Jugendstrafrecht geregelt?',
      options: ['Strafgesetzbuch (StGB)', 'Bürgerliches Gesetzbuch (BGB)', 'Jugendgerichtsgesetz (JGG)', 'Strafprozessordnung (StPO)'],
      correct: [2],
      explanation: 'Das Jugendstrafrecht für Straftäter zwischen 14 und 17 Jahren (sowie bedingt Heranwachsende) ist im Jugendgerichtsgesetz (JGG) geregelt.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was gehört zum Allgemeinen Teil des BGB (1. Buch)?',
      options: [
        'Vorschriften über Kaufverträge und Miete',
        'Regelungen zu Ehe und Familie',
        'Grundlegende Regelungen wie Rechtsfähigkeit, Willenserklärung und Verjährung',
        'Vorschriften über Eigentum und Besitz',
      ],
      correct: [2],
      explanation: 'Der Allgemeine Teil des BGB enthält grundlegende Regelungen, die für alle anderen Bücher gelten: Personen, Sachen, Rechtsgeschäfte, Willenserklärungen, Fristen und Verjährung.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welche Gerichtsbarkeit ist für Steuersachen zuständig?',
      options: ['Ordentliche Gerichtsbarkeit', 'Sozialgerichtsbarkeit', 'Finanzgerichtsbarkeit', 'Verwaltungsgerichtsbarkeit'],
      correct: [2],
      explanation: 'Für Steuerstreitigkeiten ist die Finanzgerichtsbarkeit zuständig (Finanzgericht → Bundesfinanzhof).',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welche Aussage zum Unterschied zwischen öffentlichem Recht und Privatrecht ist korrekt?',
      options: [
        'Im Privatrecht besteht ein Über-/Unterordnungsverhältnis zwischen den Parteien',
        'Im öffentlichen Recht stehen sich die Parteien gleichgeordnet gegenüber',
        'Das öffentliche Recht regelt Beziehungen, an denen der Staat hoheitlich beteiligt ist',
        'Das Privatrecht umfasst das Strafrecht und das Verwaltungsrecht',
      ],
      correct: [2],
      explanation: 'Das öffentliche Recht regelt Rechtsverhältnisse, bei denen der Staat hoheitlich handelt (Über-/Unterordnungsverhältnis). Das Privatrecht regelt die Beziehungen gleichgeordneter Rechtssubjekte.',
      difficulty: 2,
    },
    {
      type: 'truefalse',
      prompt: 'Diebstahl ist im deutschen Recht ein Verbrechen, da er mit mindestens einem Jahr Freiheitsstrafe bestraft wird.',
      options: ['Wahr', 'Falsch'],
      correct: [1],
      explanation: 'Einfacher Diebstahl (§ 242 StGB) ist ein Vergehen, da er mit Freiheitsstrafe bis zu 5 Jahren oder Geldstrafe bestraft wird (Mindeststrafe unter 1 Jahr). Erst schwerer Diebstahl (§ 243 StGB) kann als Verbrechen eingestuft werden.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Welche Instanz ist in der ordentlichen Gerichtsbarkeit zwischen dem Landgericht und dem Bundesgerichtshof angesiedelt?',
      options: ['Amtsgericht', 'Bundesverwaltungsgericht', 'Oberlandesgericht', 'Oberverwaltungsgericht'],
      correct: [2],
      explanation: 'Der Instanzenzug lautet: Amtsgericht → Landgericht → Oberlandesgericht → Bundesgerichtshof. Das Oberlandesgericht ist die dritte Instanz.',
      difficulty: 2,
    },
  ],
};

export default topic;
