import type { RawTopic } from '../types';

const topic: RawTopic = {
  slug: 'software-cloud',
  title: 'Software & Cloud',
  description: 'Software-Arten, Betriebssysteme und Cloud-Grundlagen.',
  flashcards: [
    {
      front: 'Was ist Systemsoftware?',
      back: 'Systemsoftware umfasst alle Programme, die den Betrieb des Computers ermöglichen und steuern – insbesondere das Betriebssystem, Treiber und Dienstprogramme. Sie bildet die Grundlage für Anwendungssoftware.',
    },
    {
      front: 'Was ist Anwendungssoftware?',
      back: 'Anwendungssoftware (auch: Applikationssoftware) sind Programme, die der Nutzer für konkrete Aufgaben einsetzt, z. B. Textverarbeitung (Word), Browser (Firefox) oder Tabellenkalkulation (Excel).',
    },
    {
      front: 'Welche Hauptaufgaben hat ein Betriebssystem?',
      back: '1. Prozessverwaltung (CPU-Zuteilung)\n2. Speicherverwaltung (RAM-Zuweisung)\n3. Geräteverwaltung (Hardware-Zugriff via Treiber)\n4. Dateiverwaltung (Dateisystem)\n5. Benutzerverwaltung und Zugriffsschutz',
    },
    {
      front: 'Was ist ein Gerätetreiber?',
      back: 'Ein Gerätetreiber (englisch: driver) ist ein Softwareprogramm, das dem Betriebssystem ermöglicht, mit einer bestimmten Hardware (z. B. Drucker, Grafikkarte) zu kommunizieren. Ohne den passenden Treiber wird das Gerät nicht erkannt.',
    },
    {
      front: 'Was unterscheidet Open-Source-Software von proprietärer Software?',
      back: 'Open-Source-Software: Quellcode ist öffentlich einsehbar, frei nutzbar und veränderbar (z. B. Linux, LibreOffice).\nPropietäre Software: Quellcode ist geheim, Nutzung nur unter Lizenz erlaubt (z. B. Windows, Microsoft Office).',
    },
    {
      front: 'Was ist SaaS?',
      back: 'SaaS = Software as a Service. Software wird über das Internet als Dienst bereitgestellt und muss nicht lokal installiert werden. Beispiele: Microsoft 365, Google Workspace, Salesforce.',
    },
    {
      front: 'Was ist PaaS?',
      back: 'PaaS = Platform as a Service. Anbieter stellt eine Plattform (Laufzeitumgebung, Middleware, Entwicklungswerkzeuge) bereit, auf der Kunden eigene Anwendungen entwickeln und betreiben. Beispiele: Google App Engine, Microsoft Azure App Service.',
    },
    {
      front: 'Was ist IaaS?',
      back: 'IaaS = Infrastructure as a Service. Anbieter stellt virtualisierte IT-Infrastruktur bereit (Server, Speicher, Netzwerk). Der Kunde verwaltet Betriebssystem und Anwendungen selbst. Beispiele: Amazon EC2, Microsoft Azure VMs, Google Compute Engine.',
    },
    {
      front: 'Was ist eine Public Cloud?',
      back: 'Eine Public Cloud ist eine Cloud-Umgebung, die von einem externen Anbieter (z. B. AWS, Azure, Google Cloud) betrieben und über das öffentliche Internet mehreren Kunden gleichzeitig zur Verfügung gestellt wird.',
    },
    {
      front: 'Was ist eine Private Cloud?',
      back: 'Eine Private Cloud ist eine Cloud-Infrastruktur, die ausschließlich für eine Organisation betrieben wird – entweder intern im eigenen Rechenzentrum oder bei einem Dienstleister als dedizierte Umgebung.',
    },
    {
      front: 'Was ist eine Hybrid Cloud?',
      back: 'Eine Hybrid Cloud kombiniert Public Cloud und Private Cloud. Daten und Anwendungen können zwischen beiden Umgebungen ausgetauscht werden, was Flexibilität und Skalierbarkeit erhöht.',
    },
    {
      front: 'Was versteht man unter Virtualisierung?',
      back: 'Virtualisierung bezeichnet die Erstellung virtueller (nicht physischer) Versionen von Ressourcen wie Servern, Betriebssystemen oder Netzwerken. Ein Hypervisor teilt die Hardware-Ressourcen auf mehrere virtuelle Maschinen (VMs) auf.',
    },
    {
      front: 'Was ist der Unterschied zwischen einem Compiler und einem Interpreter?',
      back: 'Compiler: Übersetzt den gesamten Quellcode vor der Ausführung in Maschinencode (z. B. C, C++).\nInterpreter: Übersetzt und führt den Code Zeile für Zeile zur Laufzeit aus (z. B. Python, JavaScript in Browsern).',
    },
    {
      front: 'Nennen Sie drei verbreitete Desktop-Betriebssysteme.',
      back: '1. Microsoft Windows (proprietär, größte Verbreitung im privaten und gewerblichen Bereich)\n2. macOS (proprietär, von Apple, nur auf Apple-Hardware)\n3. Linux (Open Source, viele Distributionen wie Ubuntu, Debian)',
    },
    {
      front: 'Nennen Sie zwei verbreitete mobile Betriebssysteme.',
      back: '1. Android (Google, Open Source, größter Marktanteil bei Smartphones)\n2. iOS (Apple, proprietär, ausschließlich auf Apple-Geräten)',
    },
    {
      front: 'Was ist ein Software-Update bzw. Patch?',
      back: 'Ein Update ist eine neue Softwareversion mit Verbesserungen oder neuen Funktionen. Ein Patch ist eine gezielte Korrektur für Fehler oder Sicherheitslücken. Regelmäßige Patches sind essenziell für die IT-Sicherheit.',
    },
    {
      front: 'Was ist eine Softwarelizenz?',
      back: 'Eine Softwarelizenz ist ein rechtlicher Vertrag, der regelt, wie eine Software genutzt werden darf (z. B. Einzelplatz-, Mehrplatz- oder Volumenlizenz). Sie legt Rechte und Einschränkungen für den Nutzer fest.',
    },
    {
      front: 'Nennen Sie Beispiele für gängige Dateiformate und ihre Verwendung.',
      back: '.pdf – plattformunabhängige Dokumente\n.docx – Word-Dokumente\n.xlsx – Excel-Tabellen\n.jpg/.png – Bilder\n.mp4 – Videos\n.csv – Tabellendaten im Textformat\n.zip – komprimierte Archive',
    },
    {
      front: 'Was ist ein Hypervisor?',
      back: 'Ein Hypervisor (auch: Virtual Machine Monitor) ist Software, die mehrere virtuelle Maschinen auf einer physischen Hardware verwaltet und betreibt. Typ 1 läuft direkt auf der Hardware (z. B. VMware ESXi), Typ 2 läuft auf einem Betriebssystem (z. B. VirtualBox).',
    },
    {
      front: 'Was bedeutet "Skalierbarkeit" in der Cloud?',
      back: 'Skalierbarkeit bedeutet, dass Cloud-Ressourcen (Rechenleistung, Speicher) flexibel und bedarfsgerecht erhöht (Scale-up/Scale-out) oder verringert werden können, ohne neue Hardware anschaffen zu müssen.',
    },
  ],
  questions: [
    {
      type: 'mc',
      prompt: 'Wofür steht die Abkürzung "SaaS"?',
      options: [
        'Storage as a Service',
        'System as a Service',
        'Software as a Service',
        'Security as a Service',
      ],
      correct: [2],
      explanation: 'SaaS = Software as a Service: Software wird über das Internet bereitgestellt, z. B. Microsoft 365 oder Google Workspace. Der Nutzer installiert nichts lokal.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welches der folgenden Betriebssysteme ist Open Source?',
      options: ['Windows 11', 'macOS Ventura', 'iOS 17', 'Ubuntu Linux'],
      correct: [3],
      explanation: 'Ubuntu Linux basiert auf dem Linux-Kernel, der unter der GPL-Lizenz als Open Source veröffentlicht ist. Windows, macOS und iOS sind proprietäre Betriebssysteme.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist die Hauptaufgabe eines Betriebssystems?',
      options: [
        'Textdokumente erstellen und bearbeiten',
        'Hardware-Ressourcen verwalten und Anwendungen eine Laufzeitumgebung bereitstellen',
        'Netzwerkpakete im Internet weiterleiten',
        'Datenbanken strukturieren und abfragen',
      ],
      correct: [1],
      explanation: 'Das Betriebssystem verwaltet die Hardware-Ressourcen (CPU, RAM, Geräte) und stellt Anwendungsprogrammen eine standardisierte Schnittstelle (API) zur Verfügung.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welches Cloud-Modell stellt dem Kunden virtuelle Server und Netzwerkinfrastruktur bereit, ohne Betriebssystem oder Anwendungen zu liefern?',
      options: ['SaaS', 'PaaS', 'IaaS', 'DaaS'],
      correct: [2],
      explanation: 'IaaS (Infrastructure as a Service) liefert virtuelle Hardware (Server, Speicher, Netzwerk). Der Kunde installiert und verwaltet Betriebssystem und Software selbst. Beispiele: Amazon EC2, Azure VMs.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Microsoft Azure App Service ist ein Beispiel für welches Cloud-Servicemodell?',
      options: ['IaaS', 'PaaS', 'SaaS', 'FaaS'],
      correct: [1],
      explanation: 'Azure App Service ist ein PaaS-Angebot (Platform as a Service): Microsoft stellt die Plattform (Laufzeitumgebung, Skalierung, Patches) bereit, der Entwickler deployt nur seinen Anwendungscode.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welche Aussage beschreibt eine Hybrid Cloud korrekt?',
      options: [
        'Eine Cloud, die ausschließlich intern im Unternehmen betrieben wird',
        'Eine Cloud, die mehreren öffentlichen Anbietern gleichzeitig gehört',
        'Eine Kombination aus Public Cloud und Private Cloud mit Datenaustausch zwischen beiden',
        'Eine Cloud ausschließlich für staatliche Behörden',
      ],
      correct: [2],
      explanation: 'Die Hybrid Cloud kombiniert Public-Cloud- und Private-Cloud-Umgebungen. Daten und Workloads können zwischen beiden bewegt werden, was Flexibilität und Compliance-Anforderungen vereint.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was ist ein Gerätetreiber?',
      options: [
        'Ein Programm zum Komprimieren von Dateien',
        'Software, die dem Betriebssystem die Kommunikation mit einer bestimmten Hardware ermöglicht',
        'Ein Dienstprogramm zur Festplattenformatierung',
        'Eine Schnittstelle zwischen zwei Anwendungsprogrammen',
      ],
      correct: [1],
      explanation: 'Ein Treiber (driver) übersetzt die allgemeinen Befehle des Betriebssystems in hardware-spezifische Steuerbefehle, z. B. für Drucker, Grafikkarten oder Netzwerkadapter.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was charakterisiert proprietäre Software?',
      options: [
        'Der Quellcode ist öffentlich einsehbar und frei veränderbar',
        'Die Software darf ohne Einschränkungen kopiert und weitergegeben werden',
        'Nutzung und Weitergabe sind durch Lizenzbedingungen des Herstellers eingeschränkt',
        'Die Software wird ausschließlich von Behörden entwickelt',
      ],
      correct: [2],
      explanation: 'Proprietäre Software ist urheberrechtlich geschützt. Nutzungsrechte werden per Lizenz erteilt; der Quellcode ist nicht öffentlich. Beispiele: Microsoft Windows, Adobe Photoshop.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welches der folgenden Programme zählt zur Systemsoftware?',
      options: ['Microsoft Word', 'Mozilla Firefox', 'Windows-Gerätetreiber', 'VLC Media Player'],
      correct: [2],
      explanation: 'Gerätetreiber gehören zur Systemsoftware, da sie die Hardware-Kommunikation des Betriebssystems unterstützen. Word, Firefox und VLC sind Anwendungssoftware.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was versteht man unter Virtualisierung im IT-Kontext?',
      options: [
        'Die verschlüsselte Übertragung von Daten im Netzwerk',
        'Das Erstellen virtueller Ressourcen (z. B. Server, Betriebssysteme) auf physischer Hardware',
        'Das grafische Darstellen von Datenbankinhalten',
        'Das automatische Backup von Dateien in der Cloud',
      ],
      correct: [1],
      explanation: 'Virtualisierung ermöglicht es, auf einer physischen Maschine mehrere virtuelle Maschinen (VMs) mit eigenen Betriebssystemen zu betreiben. Ein Hypervisor teilt dazu die Hardware-Ressourcen auf.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welches mobile Betriebssystem hat weltweit den größten Marktanteil bei Smartphones?',
      options: ['iOS', 'Android', 'Windows Mobile', 'HarmonyOS'],
      correct: [1],
      explanation: 'Android (Google) hat mit über 70 % den größten weltweiten Marktanteil bei Smartphones. iOS (Apple) folgt auf Platz zwei. Windows Mobile wurde eingestellt.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist der Unterschied zwischen einem Compiler und einem Interpreter?',
      options: [
        'Ein Compiler übersetzt Quellcode zur Laufzeit Zeile für Zeile; ein Interpreter übersetzt ihn vollständig vorab',
        'Compiler und Interpreter sind identisch; beide übersetzen zur Laufzeit',
        'Ein Compiler übersetzt den gesamten Quellcode vorab in Maschinencode; ein Interpreter übersetzt und führt den Code zur Laufzeit Zeile für Zeile aus',
        'Ein Compiler wird nur für Webanwendungen eingesetzt; ein Interpreter nur für Desktop-Apps',
      ],
      correct: [2],
      explanation: 'Compiler (z. B. für C, C++) erzeugen eine ausführbare Datei vor der Ausführung. Interpreter (z. B. für Python, JavaScript) übersetzen und führen Zeile für Zeile zur Laufzeit aus.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welches Dateiformat wird typischerweise für plattformunabhängige, nicht veränderbare Dokumente verwendet?',
      options: ['.docx', '.xlsx', '.pdf', '.csv'],
      correct: [2],
      explanation: 'Das PDF-Format (Portable Document Format, Adobe) ist auf allen Plattformen einheitlich darstellbar und verhindert unbeabsichtigte Änderungen. Es ist der Standard für amtliche Dokumente.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welche Aussage zu Software-Patches ist korrekt?',
      options: [
        'Patches sind neue Programmversionen mit vollständig überarbeiteter Benutzeroberfläche',
        'Patches beheben gezielt Fehler oder Sicherheitslücken in bestehender Software',
        'Patches können nur manuell eingespielt werden und nie automatisch',
        'Patches betreffen ausschließlich Betriebssysteme, nicht Anwendungssoftware',
      ],
      correct: [1],
      explanation: 'Ein Patch ist eine gezielte Softwarekorrektur für bekannte Fehler oder Sicherheitslücken. Er ist kleiner als ein vollständiges Update und kann für Betriebssysteme wie Anwendungen erscheinen.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Amazon EC2 (Elastic Compute Cloud) ist ein Beispiel für welches Cloud-Servicemodell?',
      options: ['SaaS', 'PaaS', 'NaaS', 'IaaS'],
      correct: [3],
      explanation: 'Amazon EC2 ist IaaS: AWS stellt virtuelle Server bereit, der Kunde wählt und betreibt Betriebssystem und Anwendungen selbst. Die physische Hardware verwaltet AWS.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was beschreibt die Prozessverwaltung eines Betriebssystems?',
      options: [
        'Das Speichern und Lesen von Dateien auf der Festplatte',
        'Die Zuteilung von CPU-Rechenzeit an laufende Prozesse (Scheduling)',
        'Die Verwaltung von Benutzerkonten und Passwörtern',
        'Das Laden von Treibern beim Systemstart',
      ],
      correct: [1],
      explanation: 'Die Prozessverwaltung (Scheduling) entscheidet, welcher Prozess wann CPU-Zeit erhält. Das Betriebssystem wechselt sehr schnell zwischen Prozessen, sodass Multitasking möglich wird.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welches Lizenzmodell erlaubt es, Software kostenlos zu nutzen, zu verändern und weiterzugeben?',
      options: ['Volumenlizenz', 'Einzelplatzlizenz', 'Freie Open-Source-Lizenz (z. B. GPL)', 'Shareware-Lizenz'],
      correct: [2],
      explanation: 'Freie Open-Source-Lizenzen wie die GPL (GNU General Public License) erlauben Nutzung, Modifikation und Weitergabe. Der Quellcode muss offengelegt werden. Shareware erlaubt nur zeitlich begrenzte kostenlose Nutzung.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was ist ein Hypervisor vom Typ 1?',
      options: [
        'Software, die auf einem vorhandenen Betriebssystem (Host-OS) läuft, z. B. VirtualBox',
        'Eine Anwendung zur Verwaltung von Cloud-Speicher',
        'Software, die direkt auf der Hardware läuft und keine Host-OS-Schicht benötigt, z. B. VMware ESXi',
        'Ein Protokoll zur verschlüsselten Netzwerkverbindung',
      ],
      correct: [2],
      explanation: 'Typ-1-Hypervisoren (bare-metal) laufen direkt auf der Hardware ohne Betriebssystem darunter (z. B. VMware ESXi, Microsoft Hyper-V). Typ-2-Hypervisoren (hosted) laufen auf einem Host-OS (z. B. VirtualBox, VMware Workstation).',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Welche der folgenden Aussagen zu macOS ist korrekt?',
      options: [
        'macOS ist Open Source und kann auf beliebiger Hardware installiert werden',
        'macOS ist ein proprietäres Betriebssystem von Apple und offiziell nur für Apple-Hardware lizenziert',
        'macOS basiert auf dem Windows-NT-Kernel',
        'macOS wird von Microsoft entwickelt und vertrieben',
      ],
      correct: [1],
      explanation: 'macOS ist proprietäre Software von Apple und offiziell ausschließlich für Apple-Hardware (Mac) lizenziert. Es basiert auf einem BSD-UNIX-Kern (Darwin), nicht auf dem Windows-Kernel.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet Skalierbarkeit in der Cloud?',
      options: [
        'Die Fähigkeit, Daten sicher zu verschlüsseln',
        'Die Möglichkeit, Ressourcen flexibel und bedarfsgerecht zu erhöhen oder zu reduzieren',
        'Das automatische Erstellen von Datensicherungen',
        'Die geografische Verteilung von Rechenzentren',
      ],
      correct: [1],
      explanation: 'Skalierbarkeit ist ein Kernvorteil der Cloud: Rechenleistung, Speicher und weitere Ressourcen lassen sich nach Bedarf schnell hoch- oder herunterskalieren, ohne neue Hardware kaufen zu müssen.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welches Dateiformat wird üblicherweise für den tabellarischen Datenaustausch zwischen verschiedenen Anwendungen genutzt?',
      options: ['.pdf', '.mp4', '.csv', '.exe'],
      correct: [2],
      explanation: 'CSV (Comma-Separated Values) ist ein einfaches Textformat für tabellarische Daten, das von nahezu allen Tabellenkalkulationsprogrammen und Datenbanken importiert und exportiert werden kann.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Google Workspace (Gmail, Docs, Drive) ist ein Beispiel für welches Cloud-Modell?',
      options: ['IaaS', 'PaaS', 'SaaS', 'BaaS'],
      correct: [2],
      explanation: 'Google Workspace ist SaaS (Software as a Service): Komplette Anwendungen werden über den Browser genutzt, ohne lokale Installation. Der Nutzer verwaltet weder Infrastruktur noch Plattform.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welche Aussage zur Speicherverwaltung eines Betriebssystems ist korrekt?',
      options: [
        'Das Betriebssystem weist laufenden Prozessen RAM-Bereiche zu und schützt sie voreinander',
        'Die Speicherverwaltung kümmert sich ausschließlich um die Festplattenpartitionierung',
        'Speicherverwaltung ist ausschließlich Aufgabe der Anwendungsprogramme',
        'Das Betriebssystem erlaubt allen Prozessen, auf denselben RAM-Bereich zuzugreifen',
      ],
      correct: [0],
      explanation: 'Das Betriebssystem verwaltet den RAM: Es weist jedem Prozess einen eigenen Speicherbereich zu und verhindert, dass Prozesse gegenseitig in ihren Speicher schreiben (Speicherschutz).',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was ist eine Volumenlizenz?',
      options: [
        'Eine kostenlose Lizenz für Non-Profit-Organisationen',
        'Eine Lizenz, die die gleichzeitige Nutzung einer Software auf einer festgelegten Anzahl von Geräten oder durch eine Anzahl von Nutzern erlaubt',
        'Eine Lizenz ausschließlich für Server-Betriebssysteme',
        'Eine zeitlich unbegrenzte Einzelplatzlizenz ohne Supportleistungen',
      ],
      correct: [1],
      explanation: 'Volumenlizenzen (z. B. Microsoft Open License) erlauben Organisationen, Software für eine definierte Anzahl von Arbeitsplätzen oder Nutzern kostengünstig zu lizenzieren, statt Einzellizenzen zu kaufen.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was ist der Unterschied zwischen einer Public Cloud und einer Private Cloud?',
      options: [
        'Public Cloud ist kostenlos; Private Cloud ist kostenpflichtig',
        'Public Cloud nutzt öffentliche Hardware; Private Cloud speichert Daten auf USB-Sticks',
        'Public Cloud wird von einem externen Anbieter für viele Kunden betrieben; Private Cloud wird exklusiv für eine Organisation betrieben',
        'Public Cloud ist unsicherer, weil sie keine Verschlüsselung unterstützt',
      ],
      correct: [2],
      explanation: 'In der Public Cloud teilen sich viele Kunden dieselbe Infrastruktur eines Anbieters (z. B. AWS). Die Private Cloud ist dediziert für eine Organisation – mehr Kontrolle, aber auch mehr Eigenverantwortung.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welche Programmiersprache wird typischerweise mit einem Interpreter ausgeführt?',
      options: ['C', 'C++', 'Python', 'Rust'],
      correct: [2],
      explanation: 'Python wird standardmäßig durch einen Interpreter (CPython) ausgeführt: Der Code wird zur Laufzeit Zeile für Zeile übersetzt. C, C++ und Rust werden kompiliert.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welche Aussage zu Android ist korrekt?',
      options: [
        'Android ist ein proprietäres Betriebssystem, das ausschließlich von Google-Geräten genutzt werden darf',
        'Android basiert auf dem Linux-Kernel und ist als Open-Source-Projekt (AOSP) verfügbar',
        'Android wurde von Apple entwickelt und später an Google verkauft',
        'Android verwendet den gleichen Kernel wie Windows 11',
      ],
      correct: [1],
      explanation: 'Android basiert auf dem Linux-Kernel. Das Android Open Source Project (AOSP) stellt den Kern frei zur Verfügung; viele Hersteller nutzen Android auf ihren Geräten, ergänzt um eigene Anpassungen.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welche der folgenden Tätigkeiten fällt unter die Geräteverwaltung des Betriebssystems?',
      options: [
        'Erstellen von Benutzerpasswörtern',
        'Formatieren von Textdokumenten',
        'Ansprechen eines Druckers über den passenden Treiber',
        'Verschlüsseln von E-Mails',
      ],
      correct: [2],
      explanation: 'Die Geräteverwaltung des Betriebssystems koordiniert den Zugriff auf Hardware-Geräte wie Drucker, Tastatur oder USB-Sticks – vermittelt durch Gerätetreiber.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was versteht man unter einer Shareware-Lizenz?',
      options: [
        'Software, die dauerhaft kostenlos genutzt werden darf',
        'Software, die zunächst kostenlos ausprobiert werden kann, für deren Weiterbenutzung aber eine Bezahlung erforderlich ist',
        'Software mit offenem Quellcode, die beliebig verändert werden darf',
        'Eine Lizenz für gemeinschaftlich entwickelte Open-Source-Software',
      ],
      correct: [1],
      explanation: 'Shareware darf kostenlos ausprobiert werden (oft zeitlich oder funktional eingeschränkt). Für die volle oder dauerhafte Nutzung ist eine Lizenzgebühr zu entrichten.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welches Format wird für komprimierte Dateiarchive standardmäßig unter Windows verwendet?',
      options: ['.tar', '.gz', '.zip', '.iso'],
      correct: [2],
      explanation: 'Das ZIP-Format ist das unter Windows am weitesten verbreitete Archivformat für komprimierte Dateien. Es wird nativ von Windows Explorer unterstützt. TAR und GZ sind typisch für Linux/Unix.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist das Ziel der Dateiverwaltung eines Betriebssystems?',
      options: [
        'Das Sortieren von E-Mails nach Absender',
        'Das Organisieren von Dateien und Verzeichnissen auf Speichermedien über ein Dateisystem',
        'Das automatische Erstellen von Präsentationen',
        'Das Verwalten von Netzwerkadressen (IP-Adressen)',
      ],
      correct: [1],
      explanation: 'Die Dateiverwaltung des Betriebssystems organisiert Dateien und Ordner auf Speichermedien (Festplatte, SSD) über ein Dateisystem (z. B. NTFS, ext4, APFS) und steuert Lese- und Schreibzugriffe.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welches der folgenden Cloud-Szenarien beschreibt PaaS am besten?',
      options: [
        'Ein Unternehmen mietet virtuelle Server und verwaltet das Betriebssystem selbst',
        'Ein Entwickler nutzt eine bereitgestellte Entwicklungsplattform, um eine Web-App zu deployen, ohne sich um Infrastruktur zu kümmern',
        'Mitarbeiter nutzen eine fertige Buchhaltungssoftware im Browser',
        'Ein Behörde betreibt ihre Server ausschließlich intern',
      ],
      correct: [1],
      explanation: 'PaaS liefert Entwicklern eine fertige Plattform (Laufzeitumgebung, Datenbankdienste, Skalierung). Der Entwickler kümmert sich nur um seinen Code, nicht um Server oder Betriebssystem.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Welche Aussage zur GPL (GNU General Public License) ist korrekt?',
      options: [
        'GPL-lizenzierte Software darf nur für private Zwecke genutzt werden',
        'Wer GPL-Software verändert und weitergibt, muss den Quellcode ebenfalls unter GPL veröffentlichen',
        'GPL erlaubt die Einbindung in proprietäre Software ohne Einschränkungen',
        'GPL-Lizenzen sind nur für staatliche Institutionen gedacht',
      ],
      correct: [1],
      explanation: 'Die GPL ist eine Copyleft-Lizenz: Wer GPL-Software verändert und weitergibt, muss den veränderten Quellcode ebenfalls unter der GPL veröffentlichen (Weitergabe-Pflicht). Linux-Kernel steht unter GPL.',
      difficulty: 3,
    },
    {
      type: 'truefalse',
      prompt: 'iOS von Apple ist ein Open-Source-Betriebssystem, das auf beliebiger Hardware installiert werden kann.',
      options: ['Wahr', 'Falsch'],
      correct: [1],
      explanation: 'Falsch. iOS ist proprietäre Software von Apple und ausschließlich auf Apple-Geräten (iPhone, iPad) lizenziert. Es ist kein Open-Source-Betriebssystem.',
      difficulty: 1,
    },
    {
      type: 'truefalse',
      prompt: 'In der Cloud lassen sich Ressourcen flexibel skalieren, ohne neue Hardware kaufen zu müssen.',
      options: ['Wahr', 'Falsch'],
      correct: [0],
      explanation: 'Wahr. Skalierbarkeit ist ein zentraler Vorteil der Cloud: Ressourcen (CPU, RAM, Speicher) können schnell und bedarfsgerecht angepasst werden, was On-Premises-Hardware so nicht ermöglicht.',
      difficulty: 1,
    },
  ],
};

export default topic;
