import type { RawTopic } from '../types';

const topic: RawTopic = {
  slug: 'softwareentwicklung',
  title: 'Softwareentwicklung & Projektmanagement',
  description: 'Vorgehensmodelle, Phasen und Projektmanagement-Grundlagen.',
  flashcards: [
    {
      front: 'Welche fünf klassischen Phasen hat der Software-Lebenszyklus?',
      back: 'Analyse, Entwurf (Design), Implementierung, Test und Wartung/Pflege.',
    },
    {
      front: 'Was unterscheidet Lastenheft und Pflichtenheft?',
      back: 'Das Lastenheft beschreibt, WAS der Auftraggeber möchte (Anforderungen). Das Pflichtenheft beschreibt, WIE der Auftragnehmer diese Anforderungen umsetzen wird (Lösungskonzept).',
    },
    {
      front: 'Wie ist das Wasserfallmodell aufgebaut?',
      back: 'Das Wasserfallmodell ist ein sequenzielles Vorgehensmodell: Jede Phase muss vollständig abgeschlossen sein, bevor die nächste beginnt. Ein Rücksprung in frühere Phasen ist nur begrenzt vorgesehen.',
    },
    {
      front: 'Was ist das V-Modell in der Softwareentwicklung?',
      back: 'Das V-Modell ist ein Vorgehensmodell, das Entwicklungsphasen (linker Ast) mit entsprechenden Testphasen (rechter Ast) verknüpft. Jeder Entwicklungsphase ist eine korrespondierende Testart zugeordnet.',
    },
    {
      front: 'Welche drei Rollen gibt es in Scrum?',
      back: 'Product Owner (verantwortet das Produkt und das Backlog), Scrum Master (sorgt für die Einhaltung des Scrum-Prozesses) und das Entwicklungsteam (setzt die Anforderungen um).',
    },
    {
      front: 'Was ist ein Sprint in Scrum?',
      back: 'Ein Sprint ist eine feste Zeitbox (meist 1–4 Wochen), in der das Entwicklungsteam ein potenziell auslieferbares Produktinkrement erarbeitet.',
    },
    {
      front: 'Was ist das Product Backlog?',
      back: 'Das Product Backlog ist eine geordnete Liste aller Anforderungen und gewünschten Funktionen eines Produkts. Es wird vom Product Owner verwaltet und priorisiert.',
    },
    {
      front: 'Wozu dient das Daily Scrum?',
      back: 'Das Daily Scrum ist ein tägliches, maximal 15-minütiges Meeting des Entwicklungsteams zur Synchronisation. Jedes Mitglied beantwortet: Was habe ich gestern getan? Was plane ich heute? Gibt es Hindernisse?',
    },
    {
      front: 'Was ist Kanban in der Softwareentwicklung?',
      back: 'Kanban ist eine agile Methode, die den Arbeitsfluss mit einem Board visualisiert (z. B. Spalten: To Do, In Progress, Done). Aufgaben werden als Karten dargestellt, der Work-in-Progress (WIP) wird begrenzt.',
    },
    {
      front: 'Welche drei Größen bilden das Magische Dreieck des Projektmanagements?',
      back: 'Zeit (Termine), Kosten (Budget) und Qualität/Umfang (Leistungsumfang). Eine Änderung an einer Größe beeinflusst stets mindestens eine der anderen.',
    },
    {
      front: 'Was versteht man unter einem Algorithmus?',
      back: 'Ein Algorithmus ist eine eindeutige, endliche Folge von Anweisungen zur Lösung eines Problems. Er muss terminieren, eindeutig und ausführbar sein.',
    },
    {
      front: 'Was ist Pseudocode?',
      back: 'Pseudocode ist eine informelle, sprachunabhängige Beschreibung eines Algorithmus in menschenlesbarer Form. Er dient als Zwischenstufe zwischen natürlicher Sprache und konkretem Programmcode.',
    },
    {
      front: 'Was ist ein Flussdiagramm (Flowchart)?',
      back: 'Ein Flussdiagramm ist eine grafische Darstellung eines Algorithmus oder Prozesses mit genormten Symbolen (Rechteck = Aktion, Raute = Entscheidung, Oval = Start/Ende).',
    },
    {
      front: 'Was ist UML und wofür wird es eingesetzt?',
      back: 'UML (Unified Modeling Language) ist eine standardisierte grafische Modellierungssprache für Software. Sie wird zur Visualisierung, Spezifikation und Dokumentation von Softwaresystemen eingesetzt (z. B. Klassendiagramm, Sequenzdiagramm, Anwendungsfalldiagramm).',
    },
    {
      front: 'Was ist der Unterschied zwischen Unit-Test, Integrationstest und Systemtest?',
      back: 'Unit-Test: Prüft einzelne Komponenten/Funktionen isoliert. Integrationstest: Prüft das Zusammenspiel mehrerer Komponenten. Systemtest: Prüft das gesamte System gegen die Anforderungen.',
    },
    {
      front: 'Was bedeutet Debugging?',
      back: 'Debugging ist der Prozess des Auffindens und Behebens von Fehlern (Bugs) in einem Programm. Es umfasst das Reproduzieren des Fehlers, die Ursachenanalyse und die Korrektur.',
    },
    {
      front: 'Was ist Git und wozu wird es verwendet?',
      back: 'Git ist ein verteiltes Versionsverwaltungssystem. Es ermöglicht das Nachverfolgen von Änderungen im Quellcode, das parallele Arbeiten in Branches und die Zusammenführung (Merge) von Codeständen.',
    },
    {
      front: 'Was sind agile Methoden in der Softwareentwicklung?',
      back: 'Agile Methoden (z. B. Scrum, Kanban, XP) setzen auf iterative, inkrementelle Entwicklung, enge Kundenzusammenarbeit, Flexibilität gegenüber Änderungen und selbstorganisierte Teams. Das Agile Manifest definiert ihre Grundwerte.',
    },
    {
      front: 'Was ist ein Sprint Review in Scrum?',
      back: 'Das Sprint Review findet am Ende eines Sprints statt. Das Team präsentiert das erarbeitete Inkrement dem Product Owner und Stakeholdern. Es wird bewertet, ob die Sprint-Ziele erreicht wurden.',
    },
    {
      front: 'Was ist eine Sprint Retrospektive?',
      back: 'Die Sprint Retrospektive ist ein Meeting nach dem Sprint Review, bei dem das Scrum-Team den Prozess selbst reflektiert und Verbesserungsmaßnahmen für den nächsten Sprint festlegt.',
    },
  ],
  questions: [
    {
      type: 'mc',
      prompt: 'Welche Rolle gibt es in Scrum NICHT?',
      options: ['Projektleiter', 'Product Owner', 'Scrum Master', 'Entwicklungsteam'],
      correct: [0],
      explanation: 'Scrum kennt Product Owner, Scrum Master und Entwicklungsteam – einen klassischen "Projektleiter" gibt es nicht.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'In welcher Phase des klassischen Software-Lebenszyklus werden die Anforderungen an das System ermittelt?',
      options: ['Implementierung', 'Test', 'Analyse', 'Wartung'],
      correct: [2],
      explanation: 'In der Analysephase werden die Anforderungen des Auftraggebers erhoben und dokumentiert, z. B. im Lastenheft.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welches Merkmal ist charakteristisch für das Wasserfallmodell?',
      options: [
        'Iterative Entwicklung in kurzen Zyklen',
        'Strikte sequenzielle Abfolge der Phasen',
        'Tägliche Synchronisationsmeetings',
        'Kontinuierliche Kundeneinbindung in jeder Phase',
      ],
      correct: [1],
      explanation: 'Das Wasserfallmodell ist durch eine strikt sequenzielle Abfolge der Phasen gekennzeichnet. Jede Phase muss abgeschlossen sein, bevor die nächste beginnt.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was beschreibt das Lastenheft?',
      options: [
        'Die technische Umsetzung durch den Auftragnehmer',
        'Den Projektablaufplan mit Meilensteinen',
        'Die Anforderungen des Auftraggebers (WAS soll gemacht werden)',
        'Die Testergebnisse nach der Implementierung',
      ],
      correct: [2],
      explanation: 'Das Lastenheft beschreibt, was der Auftraggeber wünscht – also die Anforderungen. Das Pflichtenheft des Auftragnehmers beschreibt daraufhin das Wie.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Wie lange dauert ein Sprint in Scrum typischerweise?',
      options: ['1 Tag', '1 bis 4 Wochen', '3 bis 6 Monate', 'Genau 30 Tage'],
      correct: [1],
      explanation: 'Sprints dauern typischerweise 1 bis 4 Wochen. Die Länge wird zu Beginn festgelegt und bleibt innerhalb eines Projekts konstant.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welche Aussage zum V-Modell ist korrekt?',
      options: [
        'Jeder Entwicklungsphase ist eine entsprechende Testart gegenübergestellt.',
        'Es verzichtet vollständig auf Testphasen.',
        'Es ist ein agiles Vorgehensmodell.',
        'Es kennt keine Anforderungsanalyse.',
      ],
      correct: [0],
      explanation: 'Das V-Modell stellt linken Entwicklungsphasen (z. B. Systemanforderungen) rechte Testphasen (z. B. Systemtest) gegenüber und macht so Qualitätssicherung explizit.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was ist das Product Backlog in Scrum?',
      options: [
        'Das Protokoll des letzten Sprint Reviews',
        'Eine geordnete Liste aller Produktanforderungen',
        'Die Liste der erledigten Aufgaben eines Sprints',
        'Der Terminplan des gesamten Projekts',
      ],
      correct: [1],
      explanation: 'Das Product Backlog ist eine priorisierte Liste aller gewünschten Funktionen und Anforderungen an das Produkt. Es wird vom Product Owner verantwortet.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welche drei Größen bilden das Magische Dreieck des Projektmanagements?',
      options: [
        'Personal, Technik, Kommunikation',
        'Zeit, Kosten, Qualität/Umfang',
        'Analyse, Design, Test',
        'Backlog, Sprint, Review',
      ],
      correct: [1],
      explanation: 'Das Magische Dreieck besteht aus Zeit (Termine), Kosten (Budget) und Qualität/Umfang. Veränderungen an einer Größe beeinflussen immer mindestens eine andere.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Wer ist im Scrum-Framework verantwortlich für die Priorisierung des Product Backlogs?',
      options: ['Scrum Master', 'Entwicklungsteam', 'Product Owner', 'Stakeholder'],
      correct: [2],
      explanation: 'Der Product Owner ist für den Inhalt, die Reihenfolge und die Priorisierung des Product Backlogs verantwortlich.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was ist die Aufgabe des Scrum Masters?',
      options: [
        'Fachliche Leitung des Entwicklungsteams',
        'Erstellung aller User Stories',
        'Beseitigung von Hindernissen und Sicherstellung des Scrum-Prozesses',
        'Budgetkontrolle und Ressourcenplanung',
      ],
      correct: [2],
      explanation: 'Der Scrum Master ist ein Prozessbegleiter (Servant Leader), der Hindernisse für das Team beseitigt und dafür sorgt, dass Scrum korrekt angewendet wird.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was versteht man in der Softwareentwicklung unter einem "Bug"?',
      options: [
        'Eine neue Funktion im Programm',
        'Einen Fehler oder Defekt im Programm',
        'Eine Entwurfsmethode für Datenbanken',
        'Einen Kommentar im Quellcode',
      ],
      correct: [1],
      explanation: 'Ein Bug ist ein Fehler oder Defekt in einem Programm, der zu unerwünschtem Verhalten führt. Das Auffinden und Beheben von Bugs wird als Debugging bezeichnet.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welche Testart überprüft einzelne Komponenten oder Funktionen isoliert?',
      options: ['Systemtest', 'Abnahmetest', 'Integrationstest', 'Unit-Test'],
      correct: [3],
      explanation: 'Der Unit-Test (Modultest) prüft einzelne, isolierte Einheiten des Quellcodes (z. B. eine Funktion oder Klasse) auf korrekte Funktion.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was prüft ein Integrationstest?',
      options: [
        'Einzelne Funktionen isoliert voneinander',
        'Das Zusammenspiel mehrerer Komponenten',
        'Die Benutzeroberfläche aus Anwendersicht',
        'Die Einhaltung von Programmierstandards',
      ],
      correct: [1],
      explanation: 'Der Integrationstest prüft das Zusammenspiel mehrerer Komponenten oder Module, nachdem diese einzeln getestet wurden.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welches Diagramm der UML beschreibt die statische Struktur eines Systems mit Klassen und ihren Beziehungen?',
      options: ['Sequenzdiagramm', 'Aktivitätsdiagramm', 'Klassendiagramm', 'Anwendungsfalldiagramm'],
      correct: [2],
      explanation: 'Das Klassendiagramm (Class Diagram) der UML zeigt Klassen, ihre Attribute, Methoden und Beziehungen (Assoziation, Vererbung, Aggregation usw.).',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Wofür steht die Abkürzung UML?',
      options: [
        'Universal Machine Language',
        'Unified Modeling Language',
        'Unified Method Library',
        'Universal Module Linkage',
      ],
      correct: [1],
      explanation: 'UML steht für Unified Modeling Language – eine standardisierte grafische Sprache zur Modellierung von Softwaresystemen.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welches Symbol wird in einem Flussdiagramm für eine Entscheidung (Verzweigung) verwendet?',
      options: ['Rechteck', 'Oval', 'Parallelogramm', 'Raute'],
      correct: [3],
      explanation: 'In Flussdiagrammen steht die Raute (Diamant) für eine Entscheidung/Verzweigung mit Ja-/Nein-Ausgängen. Das Rechteck steht für eine Aktion, das Oval für Start/Ende.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was ist Git?',
      options: [
        'Eine Programmiersprache für Webentwicklung',
        'Ein verteiltes Versionsverwaltungssystem',
        'Eine integrierte Entwicklungsumgebung (IDE)',
        'Ein Datenbankmanagement-System',
      ],
      correct: [1],
      explanation: 'Git ist ein verteiltes Versionsverwaltungssystem (VCS), das Änderungen am Quellcode nachverfolgt und die Zusammenarbeit mehrerer Entwickler ermöglicht.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was versteht man in Git unter einem "Branch"?',
      options: [
        'Eine Sicherungskopie des gesamten Repositorys',
        'Einen parallelen Entwicklungszweig des Quellcodes',
        'Eine Fehlermeldung beim Kompilieren',
        'Den Hauptverantwortlichen eines Projekts',
      ],
      correct: [1],
      explanation: 'Ein Branch (Zweig) in Git ist ein paralleler Entwicklungszweig. Entwickler arbeiten in separaten Branches, die später zusammengeführt (gemergt) werden.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welches Vorgehensmodell ist am ehesten als "agil" zu bezeichnen?',
      options: ['Wasserfallmodell', 'V-Modell', 'Scrum', 'Spiralmodell (klassisch)'],
      correct: [2],
      explanation: 'Scrum ist ein agiles Framework. Wasserfall und V-Modell sind klassische, plangesteuerte Vorgehensmodelle. Das Spiralmodell enthält iterative Elemente, gilt aber nicht als primär agil.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welche Aussage zu Kanban ist FALSCH?',
      options: [
        'Aufgaben werden auf einem Board visualisiert.',
        'Es gibt feste Sprints mit festgelegter Länge.',
        'Der Work-in-Progress (WIP) wird begrenzt.',
        'Karten repräsentieren Aufgaben im System.',
      ],
      correct: [1],
      explanation: 'Kanban arbeitet ohne feste Sprints oder Iterationen – Aufgaben fließen kontinuierlich durch das Board. Feste Sprints sind ein Merkmal von Scrum.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was ist Pseudocode?',
      options: [
        'Eine formale Programmiersprache für eingebettete Systeme',
        'Ein kompilierbarer Code für Testumgebungen',
        'Eine informelle, sprachunabhängige Beschreibung eines Algorithmus',
        'Ein verschlüsselter Quellcode',
      ],
      correct: [2],
      explanation: 'Pseudocode ist eine informelle, gut lesbare Beschreibung eines Algorithmus, die unabhängig von einer konkreten Programmiersprache formuliert wird.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welche Phase im klassischen Lebenszyklus folgt unmittelbar auf die Implementierung?',
      options: ['Analyse', 'Entwurf', 'Test', 'Wartung'],
      correct: [2],
      explanation: 'Im klassischen Lebenszyklus folgt auf die Implementierung die Testphase, in der das entwickelte System auf Fehler geprüft wird.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welche Eigenschaft muss ein korrekter Algorithmus IMMER besitzen?',
      options: [
        'Er muss in Java geschrieben sein.',
        'Er muss nach endlich vielen Schritten terminieren.',
        'Er muss mindestens 100 Zeilen lang sein.',
        'Er muss eine grafische Benutzeroberfläche haben.',
      ],
      correct: [1],
      explanation: 'Ein Algorithmus muss terminieren (nach endlich vielen Schritten enden), eindeutig und ausführbar sein sowie für gültige Eingaben korrekte Ergebnisse liefern.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was ist ein Systemtest?',
      options: [
        'Test einzelner Funktionen durch den Entwickler',
        'Test des Zusammenspiels zweier Module',
        'Test des gesamten Systems gegen die Anforderungen',
        'Test der Benutzeroberfläche durch Endnutzer',
      ],
      correct: [2],
      explanation: 'Der Systemtest prüft das vollständige, integrierte System gegen die festgelegten Anforderungen, um sicherzustellen, dass es die Spezifikationen erfüllt.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'In welchem Dokument beschreibt der Auftragnehmer, WIE er die Anforderungen des Auftraggebers umsetzen will?',
      options: ['Lastenheft', 'Projektplan', 'Pflichtenheft', 'Statusbericht'],
      correct: [2],
      explanation: 'Das Pflichtenheft wird vom Auftragnehmer erstellt und beschreibt, wie die im Lastenheft genannten Anforderungen technisch und organisatorisch umgesetzt werden.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welche Aussage zum Agilen Manifest ist korrekt?',
      options: [
        'Es fordert umfangreiche Dokumentation über funktionierende Software.',
        'Es priorisiert Reaktion auf Veränderung über das Befolgen eines Plans.',
        'Es empfiehlt ausschließlich das Wasserfallmodell.',
        'Es schreibt die Nutzung von Scrum als einziges Framework vor.',
      ],
      correct: [1],
      explanation: 'Das Agile Manifest (2001) formuliert u. a.: "Reaktion auf Veränderung mehr als das Befolgen eines Plans." Es ist framework-unabhängig und legt Grundwerte fest.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Was beschreibt das "Magische Dreieck" im Projektmanagement?',
      options: [
        'Die drei Scrum-Rollen',
        'Die Abhängigkeit zwischen Zeit, Kosten und Qualität/Umfang',
        'Die drei Phasen des Wasserfallmodells',
        'Die drei Diagrammtypen der UML',
      ],
      correct: [1],
      explanation: 'Das Magische Dreieck zeigt, dass Zeit, Kosten und Qualität/Umfang in Wechselwirkung stehen: Wird ein Parameter verändert, hat das Auswirkungen auf mindestens einen anderen.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was versteht man unter einem "Commit" in Git?',
      options: [
        'Das Löschen eines Branches',
        'Das Herunterladen eines Remote-Repositorys',
        'Das Speichern eines Schnappschusses der aktuellen Codeänderungen',
        'Das Zusammenführen zweier Branches',
      ],
      correct: [2],
      explanation: 'Ein Commit speichert einen Schnappschuss (Snapshot) der aktuell vorgemerkten Änderungen dauerhaft im lokalen Repository und erhält eine eindeutige ID.',
      difficulty: 2,
    },
    {
      type: 'truefalse',
      prompt: 'Im Scrum-Framework ist der Scrum Master für die fachliche Priorisierung des Product Backlogs verantwortlich.',
      options: ['Wahr', 'Falsch'],
      correct: [1],
      explanation: 'Falsch. Die Priorisierung des Product Backlogs ist alleinige Aufgabe des Product Owners, nicht des Scrum Masters.',
      difficulty: 2,
    },
    {
      type: 'truefalse',
      prompt: 'Das Wasserfallmodell ist ein iteratives Vorgehensmodell.',
      options: ['Wahr', 'Falsch'],
      correct: [1],
      explanation: 'Falsch. Das Wasserfallmodell ist ein sequenzielles (nicht iteratives) Modell. Iterative Modelle sind z. B. Scrum oder das Spiralmodell.',
      difficulty: 1,
    },
    {
      type: 'truefalse',
      prompt: 'Ein Unit-Test prüft das Zusammenspiel mehrerer Systemkomponenten.',
      options: ['Wahr', 'Falsch'],
      correct: [1],
      explanation: 'Falsch. Ein Unit-Test prüft einzelne Einheiten (Funktionen, Klassen) isoliert. Das Zusammenspiel mehrerer Komponenten wird im Integrationstest geprüft.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist das Ziel der Wartungsphase im Software-Lebenszyklus?',
      options: [
        'Erstmalige Erhebung der Kundenanforderungen',
        'Fehlerbehebung, Anpassung und Weiterentwicklung des produktiven Systems',
        'Erstellung des Pflichtenhefts',
        'Durchführung des Abnahmetests',
      ],
      correct: [1],
      explanation: 'In der Wartungsphase wird das ausgelieferte System betrieben, Fehler werden behoben (korrektiv), Anpassungen vorgenommen (adaptiv) und Verbesserungen eingebaut (perfektiv).',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welches UML-Diagramm zeigt zeitliche Abläufe und Nachrichten zwischen Objekten?',
      options: ['Klassendiagramm', 'Zustandsdiagramm', 'Sequenzdiagramm', 'Komponentendiagramm'],
      correct: [2],
      explanation: 'Das Sequenzdiagramm (UML) stellt den zeitlichen Verlauf von Nachrichten und Interaktionen zwischen Objekten oder Akteuren dar.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Welche Testart ist typischerweise Bestandteil des rechten Astes im V-Modell, der der Systemanforderungsanalyse gegenübergestellt ist?',
      options: ['Unit-Test', 'Integrationstest', 'Systemtest', 'Code-Review'],
      correct: [2],
      explanation: 'Im V-Modell ist dem linken Ast "Systemanforderungen" der rechte Ast "Systemtest" gegenübergestellt. Systemtests prüfen, ob das System die Anforderungen erfüllt.',
      difficulty: 3,
    },
  ],
};

export default topic;
