import type { RawTopic } from '../types';

const topic: RawTopic = {
  slug: 'sprichwoerter',
  title: 'Sprichwörter & Redewendungen',
  description: 'Bekannte Sprichwörter vervollständigen und ihre Bedeutung kennen.',
  flashcards: [
    {
      front: 'Den Nagel auf den Kopf treffen',
      back: 'Etwas genau richtig sagen oder tun; das Wesentliche exakt erfassen.',
    },
    {
      front: 'Die Flinte ins Korn werfen',
      back: 'Aufgeben; bei einer Schwierigkeit zu schnell kapitulieren.',
    },
    {
      front: 'Eulen nach Athen tragen',
      back: 'Etwas Überflüssiges tun; jemandem etwas bringen, das er ohnehin im Überfluss hat.',
    },
    {
      front: 'Ins Gras beißen',
      back: 'Sterben (umgangssprachlich).',
    },
    {
      front: 'Jemandem auf den Zahn fühlen',
      back: 'Jemanden genau ausfragen oder prüfen, um seine wahren Absichten oder sein Wissen herauszufinden.',
    },
    {
      front: 'Morgenstund hat Gold im Mund',
      back: 'Wer früh aufsteht und früh mit der Arbeit beginnt, ist erfolgreicher.',
    },
    {
      front: 'Den Braten riechen',
      back: 'Eine Gefahr oder einen Trick frühzeitig erkennen; misstrauisch werden.',
    },
    {
      front: 'Auf keinen grünen Zweig kommen',
      back: 'Keinen Erfolg haben; nicht vorankommen.',
    },
    {
      front: 'Einen Bock schießen',
      back: 'Einen groben Fehler machen; einen Fauxpas begehen.',
    },
    {
      front: 'Öl ins Feuer gießen',
      back: 'Einen Streit oder eine unangenehme Situation noch verschlimmern.',
    },
    {
      front: 'Die Katze im Sack kaufen',
      back: 'Etwas kaufen oder akzeptieren, ohne es vorher geprüft zu haben; blind vertrauen.',
    },
    {
      front: 'Aus einer Mücke einen Elefanten machen',
      back: 'Eine Kleinigkeit übertreiben; etwas Unwichtiges aufbauschen.',
    },
    {
      front: 'Jemandem einen Bären aufbinden',
      back: 'Jemandem etwas Unwahres erzählen; jemanden belügen oder hereinlegen.',
    },
    {
      front: 'Den Wald vor lauter Bäumen nicht sehen',
      back: 'Das Wesentliche wegen zu vieler Details übersehen; den Überblick verlieren.',
    },
    {
      front: 'Die Kirche im Dorf lassen',
      back: 'Nicht übertreiben; realistisch und bescheiden bleiben.',
    },
    {
      front: 'Jemandem auf der Nase herumtanzen',
      back: 'Jemanden ausnutzen; jemanden nicht ernst nehmen und nach Belieben behandeln.',
    },
    {
      front: 'Schwein haben',
      back: 'Glück haben (umgangssprachlich).',
    },
    {
      front: 'Ins kalte Wasser springen',
      back: 'Etwas wagen, ohne sich lange vorzubereiten; direkt anfangen.',
    },
    {
      front: 'Jemandem den schwarzen Peter zuschieben',
      back: 'Die Schuld oder Verantwortung auf jemand anderen abwälzen.',
    },
    {
      front: 'Einen Zahn zulegen',
      back: 'Schneller werden; sich mehr beeilen oder mehr Einsatz zeigen.',
    },
    {
      front: 'Hinter schwedischen Gardinen sitzen',
      back: 'Im Gefängnis sitzen.',
    },
    {
      front: 'Auf dem Holzweg sein',
      back: 'Sich irren; auf dem falschen Weg sein.',
    },
  ],
  questions: [
    {
      type: 'mc',
      prompt: 'Vervollständige: "Morgenstund hat Gold im ___."',
      options: ['Mund', 'Sack', 'Haus', 'Beutel'],
      correct: [0],
      explanation: '"Morgenstund hat Gold im Mund" – wer früh aufsteht, ist produktiver und hat mehr Erfolg.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "die Flinte ins Korn werfen"?',
      options: ['aufgeben', 'schießen', 'ernten', 'feiern'],
      correct: [0],
      explanation: '"Die Flinte ins Korn werfen" bedeutet, bei einer Schwierigkeit zu früh aufzugeben.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Vervollständige: "Der Apfel fällt nicht weit vom ___."',
      options: ['Stamm', 'Baum', 'Ast', 'Kern'],
      correct: [1],
      explanation: '"Der Apfel fällt nicht weit vom Baum" – Kinder ähneln oft ihren Eltern in Charakter oder Verhalten.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "ins Gras beißen"?',
      options: ['essen', 'hinfallen', 'sterben', 'sich ärgern'],
      correct: [2],
      explanation: '"Ins Gras beißen" ist eine umgangssprachliche Redewendung für sterben.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "Eulen nach Athen tragen"?',
      options: [
        'Etwas Überflüssiges tun',
        'Weise Ratschläge geben',
        'Lange reisen',
        'Tiere transportieren',
      ],
      correct: [0],
      explanation: 'In Athen gab es so viele Eulen, dass es sinnlos gewesen wäre, weitere dorthin zu bringen. Die Redewendung bedeutet, etwas völlig Unnötiges zu tun.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Vervollständige: "Wer anderen eine Grube gräbt, ___ selbst hinein."',
      options: ['schaut', 'fällt', 'springt', 'wirft'],
      correct: [1],
      explanation: '"Wer anderen eine Grube gräbt, fällt selbst hinein" – wer anderen Schaden zufügen will, schadet am Ende sich selbst.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "den Nagel auf den Kopf treffen"?',
      options: [
        'Jemanden verletzen',
        'Etwas genau richtig sagen oder tun',
        'Handwerklich arbeiten',
        'Ein Problem lösen',
      ],
      correct: [1],
      explanation: '"Den Nagel auf den Kopf treffen" bedeutet, etwas genau und treffend zu formulieren oder zu tun.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Vervollständige: "Lügen haben kurze ___."',
      options: ['Arme', 'Wege', 'Beine', 'Finger'],
      correct: [2],
      explanation: '"Lügen haben kurze Beine" – Lügen fliegen nicht weit; die Wahrheit kommt meistens heraus.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "die Katze im Sack kaufen"?',
      options: [
        'Einen Haustier-Laden besuchen',
        'Günstig einkaufen',
        'Etwas kaufen, ohne es vorher geprüft zu haben',
        'Eine Überraschung schenken',
      ],
      correct: [2],
      explanation: '"Die Katze im Sack kaufen" heißt, etwas zu akzeptieren oder zu kaufen, ohne es genau geprüft zu haben.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Vervollständige: "Hochmut kommt vor dem ___."',
      options: ['Aufstieg', 'Ruhm', 'Fall', 'Sieg'],
      correct: [2],
      explanation: '"Hochmut kommt vor dem Fall" – Arroganz und Überheblichkeit führen häufig zu einem Scheitern.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "jemandem auf den Zahn fühlen"?',
      options: [
        'Beim Zahnarzt helfen',
        'Jemanden genau ausfragen oder prüfen',
        'Jemanden aufmuntern',
        'Jemanden kritisieren',
      ],
      correct: [1],
      explanation: '"Jemandem auf den Zahn fühlen" bedeutet, jemanden gründlich zu befragen, um seine wahren Absichten oder sein Wissen zu ermitteln.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Vervollständige: "Ende gut, ___ gut."',
      options: ['alles', 'immer', 'wieder', 'ganz'],
      correct: [0],
      explanation: '"Ende gut, alles gut" – wenn der Ausgang einer Sache gut ist, kann man über den schwierigen Weg dahin hinwegsehen.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "aus einer Mücke einen Elefanten machen"?',
      options: [
        'Tiere vergleichen',
        'Eine Kleinigkeit übertreiben',
        'Mut beweisen',
        'Etwas verkleinern',
      ],
      correct: [1],
      explanation: '"Aus einer Mücke einen Elefanten machen" bedeutet, eine Kleinigkeit maßlos zu übertreiben.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Vervollständige: "Wer zuletzt lacht, lacht am ___."',
      options: ['lautesten', 'besten', 'längsten', 'schönsten'],
      correct: [1],
      explanation: '"Wer zuletzt lacht, lacht am besten" – wer am Ende einer Auseinandersetzung die Oberhand behält, hat tatsächlich gewonnen.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "auf dem Holzweg sein"?',
      options: [
        'Im Wald spazieren gehen',
        'Holz transportieren',
        'Sich irren; auf dem falschen Weg sein',
        'Altmodisch denken',
      ],
      correct: [2],
      explanation: '"Auf dem Holzweg sein" bedeutet, sich in einem Irrtum zu befinden. Der "Holzweg" war ein Weg, der nur zum Holzfällerplatz führte und keinen Weiterweg hatte.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Vervollständige: "Stille Wasser sind ___."',
      options: ['kalt', 'tief', 'treu', 'klar'],
      correct: [1],
      explanation: '"Stille Wasser sind tief" – ruhige, unscheinbare Menschen haben oft mehr Tiefgang, als es zunächst den Anschein hat.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "jemandem einen Bären aufbinden"?',
      options: [
        'Jemandem helfen',
        'Jemanden erschrecken',
        'Jemandem etwas Unwahres erzählen',
        'Jemanden loben',
      ],
      correct: [2],
      explanation: '"Jemandem einen Bären aufbinden" bedeutet, jemanden mit einer Lüge oder einer erfundenen Geschichte hereinzulegen.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Vervollständige: "Der frühe Vogel fängt den ___."',
      options: ['Fisch', 'Käfer', 'Wurm', 'Schmetterling'],
      correct: [2],
      explanation: '"Der frühe Vogel fängt den Wurm" – wer früh und rechtzeitig handelt, hat einen Vorteil gegenüber anderen.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "den Wald vor lauter Bäumen nicht sehen"?',
      options: [
        'Kurzsichtig sein',
        'Im Wald verloren gehen',
        'Das Wesentliche wegen zu vieler Details übersehen',
        'Umweltbewusst handeln',
      ],
      correct: [2],
      explanation: '"Den Wald vor lauter Bäumen nicht sehen" bedeutet, den Überblick zu verlieren, weil man sich zu sehr in Details verliert.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Vervollständige: "Übung macht den ___."',
      options: ['Meister', 'Erfolg', 'Sieger', 'Profi'],
      correct: [0],
      explanation: '"Übung macht den Meister" – durch wiederholtes Üben wird man besser und gelangt zur Meisterschaft.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "die Kirche im Dorf lassen"?',
      options: [
        'Religiös bleiben',
        'Nicht übertreiben; realistisch bleiben',
        'In der Heimat bleiben',
        'Traditionen wahren',
      ],
      correct: [1],
      explanation: '"Die Kirche im Dorf lassen" bedeutet, nicht zu übertreiben und die Dinge in einem angemessenen Rahmen zu halten.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Vervollständige: "Kleider machen ___."',
      options: ['Mode', 'Leute', 'schön', 'reich'],
      correct: [1],
      explanation: '"Kleider machen Leute" – das äußere Erscheinungsbild beeinflusst den ersten Eindruck und die Wahrnehmung durch andere.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "jemandem auf der Nase herumtanzen"?',
      options: [
        'Jemanden zum Lachen bringen',
        'Jemanden respektieren',
        'Jemanden ausnutzen und nicht ernst nehmen',
        'Mit jemandem tanzen',
      ],
      correct: [2],
      explanation: '"Jemandem auf der Nase herumtanzen" bedeutet, jemanden nicht ernst zu nehmen und ihn nach Belieben zu behandeln.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Vervollständige: "Wer anderen eine Grube gräbt, ___ selbst hinein."',
      options: ['schaut', 'blickt', 'fällt', 'steigt'],
      correct: [2],
      explanation: '"Wer anderen eine Grube gräbt, fällt selbst hinein" – Böses, das man anderen antun will, fällt auf einen selbst zurück.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "den Braten riechen"?',
      options: [
        'Kochen können',
        'Hunger haben',
        'Eine Gefahr oder einen Trick frühzeitig erkennen',
        'Angenehme Dinge wahrnehmen',
      ],
      correct: [2],
      explanation: '"Den Braten riechen" bedeutet, eine Gefahr, einen Trick oder eine List frühzeitig zu erkennen und misstrauisch zu werden.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Vervollständige: "Viele Köche verderben den ___."',
      options: ['Abend', 'Brei', 'Tisch', 'Hunger'],
      correct: [1],
      explanation: '"Viele Köche verderben den Brei" – wenn zu viele Menschen bei einer Sache mitreden, kommt oft nichts Gutes dabei heraus.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "auf keinen grünen Zweig kommen"?',
      options: [
        'Nicht in den Wald gehen',
        'Umweltprobleme haben',
        'Keinen Erfolg haben; nicht vorankommen',
        'Neid empfinden',
      ],
      correct: [2],
      explanation: '"Auf keinen grünen Zweig kommen" bedeutet, trotz Bemühungen keinen Erfolg zu haben und nicht voranzukommen.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Vervollständige: "Der Hunger ist der beste ___."',
      options: ['Arzt', 'Koch', 'Freund', 'Ratgeber'],
      correct: [1],
      explanation: '"Der Hunger ist der beste Koch" – wenn man hungrig ist, schmeckt fast alles gut.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "einen Bock schießen"?',
      options: [
        'Jagen gehen',
        'Einen groben Fehler machen',
        'Erfolgreich sein',
        'Etwas riskieren',
      ],
      correct: [1],
      explanation: '"Einen Bock schießen" bedeutet, einen groben Fehler oder Fauxpas zu begehen.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Vervollständige: "Gut Ding will ___ haben."',
      options: ['Zeit', 'Geld', 'Mühe', 'Planung'],
      correct: [0],
      explanation: '"Gut Ding will Weile haben" – etwas Gutes braucht seine Zeit; man sollte nicht hetzen, wenn man ein gutes Ergebnis erzielen will.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "Öl ins Feuer gießen"?',
      options: [
        'Eine Situation beruhigen',
        'Eine schwierige Situation noch verschlimmern',
        'Energie aufwenden',
        'Einen Brand löschen',
      ],
      correct: [1],
      explanation: '"Öl ins Feuer gießen" bedeutet, einen Streit oder eine angespannte Situation noch schlimmer zu machen, statt sie zu beruhigen.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Vervollständige: "Wo ein Wille ist, ist auch ein ___."',
      options: ['Ausweg', 'Weg', 'Ziel', 'Sinn'],
      correct: [1],
      explanation: '"Wo ein Wille ist, ist auch ein Weg" – mit ausreichend Entschlossenheit findet man immer eine Möglichkeit, ein Ziel zu erreichen.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "jemandem den schwarzen Peter zuschieben"?',
      options: [
        'Jemanden betrügen',
        'Die Schuld oder Verantwortung auf jemand anderen abwälzen',
        'Jemanden auszeichnen',
        'Ein Kartenspiel spielen',
      ],
      correct: [1],
      explanation: '"Jemandem den schwarzen Peter zuschieben" bedeutet, die Verantwortung oder Schuld für etwas auf eine andere Person zu schieben.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Vervollständige: "Reden ist Silber, Schweigen ist ___."',
      options: ['Eisen', 'Bronze', 'Gold', 'Platin'],
      correct: [2],
      explanation: '"Reden ist Silber, Schweigen ist Gold" – manchmal ist es klüger zu schweigen als zu reden.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "Schwein haben"?',
      options: ['Ein Haustier besitzen', 'Unverschämt sein', 'Glück haben', 'Fleißig sein'],
      correct: [2],
      explanation: '"Schwein haben" ist eine umgangssprachliche Redewendung für Glück haben.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Vervollständige: "Alte Hasen wissen, wo der ___ läuft."',
      options: ['Hund', 'Hase', 'Fuchs', 'Wolf'],
      correct: [1],
      explanation: '"Alte Hasen wissen, wo der Hase läuft" – erfahrene Menschen kennen sich in einer Sache gut aus und wissen, worauf es ankommt.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "hinter schwedischen Gardinen sitzen"?',
      options: [
        'In Schweden wohnen',
        'Durch ein Fenster schauen',
        'Im Gefängnis sitzen',
        'Sich verstecken',
      ],
      correct: [2],
      explanation: '"Hinter schwedischen Gardinen sitzen" ist eine umgangssprachliche Redewendung dafür, im Gefängnis zu sitzen.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Vervollständige: "Der Schein trügt ___ nicht."',
      options: ['immer', 'selten', 'manchmal', 'oft'],
      correct: [3],
      explanation: '"Der Schein trügt oft" – das äußere Erscheinungsbild entspricht häufig nicht der Realität.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "einen Zahn zulegen"?',
      options: [
        'Zum Zahnarzt gehen',
        'Langsamer werden',
        'Schneller werden; sich mehr beeilen',
        'Sorgfältiger arbeiten',
      ],
      correct: [2],
      explanation: '"Einen Zahn zulegen" bedeutet, das Tempo zu erhöhen und schneller oder mit mehr Einsatz zu handeln.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Vervollständige: "Man soll den Tag nicht vor dem ___ loben."',
      options: ['Morgen', 'Mittag', 'Abend', 'Ende'],
      correct: [2],
      explanation: '"Man soll den Tag nicht vor dem Abend loben" – man soll erst am Ende beurteilen, ob etwas gut ausgegangen ist.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "ins kalte Wasser springen"?',
      options: [
        'Schwimmen lernen',
        'Leichtsinnig sein',
        'Etwas wagen, ohne sich lange vorzubereiten',
        'Einen Fehler begehen',
      ],
      correct: [2],
      explanation: '"Ins kalte Wasser springen" bedeutet, etwas ohne lange Vorbereitung direkt anzugehen und zu wagen.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Vervollständige: "Einem geschenkten Gaul schaut man nicht ins ___."',
      options: ['Auge', 'Ohr', 'Maul', 'Herz'],
      correct: [2],
      explanation: '"Einem geschenkten Gaul schaut man nicht ins Maul" – über Geschenke sollte man nicht meckern, sondern dankbar sein.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "Tomaten auf den Augen haben"?',
      options: [
        'Krank sein',
        'Etwas Offensichtliches nicht wahrnehmen',
        'Sehr gute Augen haben',
        'Gemüse mögen',
      ],
      correct: [1],
      explanation: '"Tomaten auf den Augen haben" bedeutet, etwas Offensichtliches nicht zu sehen oder zu bemerken.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Vervollständige: "Was Hänschen nicht lernt, lernt ___ nimmermehr."',
      options: ['er', 'Hans', 'keiner', 'niemand'],
      correct: [1],
      explanation: '"Was Hänschen nicht lernt, lernt Hans nimmermehr" – was man in der Jugend nicht lernt, ist im Erwachsenenalter nur schwer nachzuholen.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "Butter bei die Fische geben"?',
      options: [
        'Norddeutsch kochen',
        'Das Entscheidende oder den Kern einer Sache benennen; zur Sache kommen',
        'Großzügig sein',
        'Jemanden bestechen',
      ],
      correct: [1],
      explanation: '"Butter bei die Fische geben" bedeutet, zur Sache zu kommen, Klarheit zu schaffen oder das Entscheidende beizusteuern.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Vervollständige: "Wer im Glashaus sitzt, soll nicht mit ___ werfen."',
      options: ['Geld', 'Worten', 'Steinen', 'Dreck'],
      correct: [2],
      explanation: '"Wer im Glashaus sitzt, soll nicht mit Steinen werfen" – wer selbst Fehler hat, sollte andere nicht kritisieren.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "den Teufel an die Wand malen"?',
      options: [
        'Kunstmalen',
        'Abergläubisch sein',
        'Unnötigerweise Unheil oder das Schlimmste heraufbeschwören',
        'Jemanden erschrecken',
      ],
      correct: [2],
      explanation: '"Den Teufel an die Wand malen" bedeutet, unnötig das Schlimmste zu befürchten oder von Unglück zu reden, was dieses angeblich heraufbeschwört.',
      difficulty: 2,
    },
    {
      type: 'fill',
      prompt: 'Vervollständige das Sprichwort: "Wer rastet, der ___."',
      options: ['rostet', 'schläft', 'verliert', 'ruht'],
      correct: [0],
      explanation: '"Wer rastet, der rostet" – wer aufhört, sich zu betätigen und weiterzubilden, verliert seine Fähigkeiten.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "etwas auf die lange Bank schieben"?',
      options: [
        'Etwas verschieben und aufschieben',
        'Etwas sorgfältig planen',
        'Etwas günstig kaufen',
        'Etwas öffentlich machen',
      ],
      correct: [0],
      explanation: '"Etwas auf die lange Bank schieben" bedeutet, etwas immer wieder zu verschieben und aufzuschieben.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Vervollständige: "Hunde, die bellen, ___."',
      options: ['beißen nicht', 'sind gefährlich', 'laufen schnell', 'schlafen viel'],
      correct: [0],
      explanation: '"Hunde, die bellen, beißen nicht" – wer viel droht und prahlt, handelt meistens nicht.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "jemandem einen Korb geben"?',
      options: [
        'Jemandem etwas schenken',
        'Einen Liebesantrag oder eine Bitte ablehnen',
        'Jemanden loben',
        'Jemandem helfen',
      ],
      correct: [1],
      explanation: '"Jemandem einen Korb geben" bedeutet, einen Liebesantrag oder eine Bitte abzulehnen.',
      difficulty: 2,
    },
    {
      type: 'fill',
      prompt: 'Vervollständige: "Alle Wege führen nach ___."',
      options: ['Berlin', 'Paris', 'Rom', 'Wien'],
      correct: [2],
      explanation: '"Alle Wege führen nach Rom" – es gibt viele verschiedene Möglichkeiten, ein Ziel zu erreichen.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "die Spreu vom Weizen trennen"?',
      options: [
        'Landwirtschaft betreiben',
        'Das Gute vom Schlechten unterscheiden',
        'Genau arbeiten',
        'Vorurteile abbauen',
      ],
      correct: [1],
      explanation: '"Die Spreu vom Weizen trennen" bedeutet, das Wertvolle vom Wertlosen zu unterscheiden.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Vervollständige: "Der Klügere gibt ___."',
      options: ['nach', 'auf', 'zu', 'hin'],
      correct: [0],
      explanation: '"Der Klügere gibt nach" – in einem Streit nachzugeben zeugt von Klugheit und Größe, nicht von Schwäche.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "blau machen"?',
      options: [
        'Malen gehen',
        'Einen freien Tag einlegen; der Arbeit oder Schule unentschuldigt fernbleiben',
        'Traurig sein',
        'Sport treiben',
      ],
      correct: [1],
      explanation: '"Blau machen" bedeutet, der Arbeit oder Schule unentschuldigt fernzubleiben und einen freien Tag zu genießen.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Vervollständige: "Es ist noch kein Meister vom ___ gefallen."',
      options: ['Baum', 'Dach', 'Himmel', 'Pferd'],
      correct: [2],
      explanation: '"Es ist noch kein Meister vom Himmel gefallen" – niemand kann etwas von Beginn an perfekt; man braucht Zeit und Übung.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "einen Zahn zulegen"?',
      options: ['Langsamer machen', 'Das Tempo erhöhen', 'Pausen machen', 'Sorgfältig vorgehen'],
      correct: [1],
      explanation: '"Einen Zahn zulegen" bedeutet, das Tempo zu erhöhen und schneller zu werden.',
      difficulty: 2,
    },
    {
      type: 'fill',
      prompt: 'Vervollständige: "Wie man in den Wald hineinruft, so ___ es heraus."',
      options: ['kommt', 'hallt', 'tönt', 'klingt'],
      correct: [1],
      explanation: '"Wie man in den Wald hineinruft, so hallt es heraus" – wie man andere behandelt, so wird man selbst behandelt.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "auf großem Fuß leben"?',
      options: [
        'Große Schuhe tragen',
        'Im Luxus leben; mehr ausgeben als man sich leisten kann',
        'Viel reisen',
        'In einem großen Haus wohnen',
      ],
      correct: [1],
      explanation: '"Auf großem Fuß leben" bedeutet, einen aufwendigen, luxuriösen Lebensstil zu führen, oft über seine Verhältnisse.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Vervollständige: "Morgenstund hat Gold im Mund, und Abendrot ist ___."',
      options: ['sehr schön', 'Schlechtwetterbrot', 'roter Morgenrot', 'nichts wert'],
      correct: [1],
      explanation: 'Im erweiterten Sprichwort lautet die Fortsetzung "Abendrot ist Schlechtwetterbrot" – rotes Abendrot kündigt schlechtes Wetter an.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "jemanden hinters Licht führen"?',
      options: [
        'Jemandem den Weg zeigen',
        'Jemanden täuschen oder betrügen',
        'Jemanden aufklären',
        'Jemandem helfen',
      ],
      correct: [1],
      explanation: '"Jemanden hinters Licht führen" bedeutet, jemanden zu täuschen oder zu betrügen.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Vervollständige: "Kein Rauch ohne ___."',
      options: ['Feuer', 'Wind', 'Asche', 'Gefahr'],
      correct: [0],
      explanation: '"Kein Rauch ohne Feuer" – jedes Gerücht oder jeder Vorwurf hat meist einen wahren Kern.',
      difficulty: 1,
    },
  ],
};

export default topic;
