import type { RawTopic } from '../types';

/**
 * KANONISCHES BEISPIEL-FORMAT für alle Themen-Dateien.
 * - default export ist ein RawTopic (ohne numerische IDs – die vergibt buildContent)
 * - mc-Fragen haben genau 4 Optionen; `correct` enthält den Index der richtigen Option
 * - fill-Fragen: `correct` ist ein Array akzeptierter Schreibweisen (Strings)
 * - jede Frage hat eine `explanation`
 */
const topic: RawTopic = {
  slug: 'synonyme',
  title: 'Synonyme',
  description: 'Wörter mit gleicher oder ähnlicher Bedeutung erkennen.',
  flashcards: [
    { front: 'Synonym', back: 'Ein Wort mit gleicher oder sehr ähnlicher Bedeutung wie ein anderes (z. B. „schnell“ = „rasch“).' },
    { front: 'effizient', back: 'wirkungsvoll, leistungsfähig – mit wenig Aufwand viel erreichen.' },
    { front: 'transparent', back: 'durchsichtig; im übertragenen Sinn: nachvollziehbar, offen.' },
    { front: 'flexibel', back: 'anpassungsfähig, beweglich, biegsam.' },
    { front: 'relevant', back: 'wichtig, bedeutsam, erheblich für eine Sache.' },
    { front: 'kompetent', back: 'fähig, sachkundig, fachkundig.' },
    { front: 'präzise', back: 'genau, exakt, treffend.' },
    { front: 'spontan', back: 'unüberlegt-rasch, aus dem Augenblick heraus, ungeplant.' },
    { front: 'tolerant', back: 'duldsam, nachsichtig, aufgeschlossen gegenüber anderem.' },
    { front: 'modern', back: 'zeitgemäß, neuzeitlich, aktuell.' },
    { front: 'komplex', back: 'vielschichtig, kompliziert, verflochten.' },
    { front: 'optimal', back: 'bestmöglich, ideal.' },
    { front: 'identisch', back: 'gleich, völlig übereinstimmend.' },
    { front: 'temporär', back: 'zeitweilig, vorübergehend, befristet.' },
    { front: 'global', back: 'weltweit, umfassend, gesamt.' },
    { front: 'rational', back: 'vernunftgemäß, sachlich, überlegt.' },
    { front: 'sensibel', back: 'empfindsam, feinfühlig, empfindlich.' },
    { front: 'autonom', back: 'selbstständig, unabhängig, eigenständig.' },
  ],
  questions: [
    { type: 'mc', prompt: 'Welches Wort bedeutet dasselbe wie „effizient“?', options: ['wirkungsvoll', 'langsam', 'teuer', 'unklar'], correct: [0], explanation: 'Effizient = mit wenig Aufwand viel erreichen → wirkungsvoll.', difficulty: 1 },
    { type: 'mc', prompt: 'Synonym für „Beginn“?', options: ['Anfang', 'Ende', 'Mitte', 'Pause'], correct: [0], explanation: 'Beginn = Anfang.', difficulty: 1 },
    { type: 'mc', prompt: 'Synonym für „rasch“?', options: ['schnell', 'müde', 'leise', 'schwer'], correct: [0], explanation: 'Rasch = schnell.', difficulty: 1 },
    { type: 'mc', prompt: 'Synonym für „transparent“ (übertragen)?', options: ['nachvollziehbar', 'geheim', 'farbig', 'eng'], correct: [0], explanation: 'Transparent = durchsichtig/offen → nachvollziehbar.', difficulty: 2 },
    { type: 'mc', prompt: 'Synonym für „relevant“?', options: ['wichtig', 'nebensächlich', 'falsch', 'leer'], correct: [0], explanation: 'Relevant = wichtig, bedeutsam.', difficulty: 1 },
    { type: 'mc', prompt: 'Synonym für „kompetent“?', options: ['sachkundig', 'unwissend', 'unsicher', 'müde'], correct: [0], explanation: 'Kompetent = fähig, sachkundig.', difficulty: 1 },
    { type: 'mc', prompt: 'Synonym für „präzise“?', options: ['genau', 'ungefähr', 'breit', 'langsam'], correct: [0], explanation: 'Präzise = genau, exakt.', difficulty: 1 },
    { type: 'mc', prompt: 'Synonym für „flexibel“?', options: ['anpassungsfähig', 'starr', 'hart', 'fest'], correct: [0], explanation: 'Flexibel = anpassungsfähig, beweglich.', difficulty: 1 },
    { type: 'mc', prompt: 'Synonym für „tolerant“?', options: ['duldsam', 'streng', 'engstirnig', 'laut'], correct: [0], explanation: 'Tolerant = duldsam, nachsichtig.', difficulty: 2 },
    { type: 'mc', prompt: 'Synonym für „modern“?', options: ['zeitgemäß', 'altmodisch', 'kaputt', 'billig'], correct: [0], explanation: 'Modern = zeitgemäß, neuzeitlich.', difficulty: 1 },
    { type: 'mc', prompt: 'Synonym für „komplex“?', options: ['vielschichtig', 'einfach', 'leer', 'kurz'], correct: [0], explanation: 'Komplex = vielschichtig, kompliziert.', difficulty: 2 },
    { type: 'mc', prompt: 'Synonym für „optimal“?', options: ['bestmöglich', 'schlecht', 'mittelmäßig', 'unnötig'], correct: [0], explanation: 'Optimal = bestmöglich, ideal.', difficulty: 1 },
    { type: 'mc', prompt: 'Synonym für „identisch“?', options: ['gleich', 'ähnlich', 'verschieden', 'fremd'], correct: [0], explanation: 'Identisch = völlig gleich (mehr als nur ähnlich).', difficulty: 2 },
    { type: 'mc', prompt: 'Synonym für „temporär“?', options: ['vorübergehend', 'dauerhaft', 'endgültig', 'ewig'], correct: [0], explanation: 'Temporär = zeitweilig, vorübergehend.', difficulty: 2 },
    { type: 'mc', prompt: 'Synonym für „global“?', options: ['weltweit', 'örtlich', 'klein', 'einzeln'], correct: [0], explanation: 'Global = weltweit, umfassend.', difficulty: 1 },
    { type: 'mc', prompt: 'Synonym für „rational“?', options: ['vernünftig', 'gefühlsbetont', 'zufällig', 'wild'], correct: [0], explanation: 'Rational = vernunftgemäß, sachlich.', difficulty: 2 },
    { type: 'mc', prompt: 'Synonym für „sensibel“?', options: ['empfindsam', 'grob', 'gleichgültig', 'hart'], correct: [0], explanation: 'Sensibel = feinfühlig, empfindsam.', difficulty: 2 },
    { type: 'mc', prompt: 'Synonym für „autonom“?', options: ['selbstständig', 'abhängig', 'fremdbestimmt', 'gebunden'], correct: [0], explanation: 'Autonom = unabhängig, selbstständig.', difficulty: 2 },
    { type: 'mc', prompt: 'Synonym für „Aufgabe“?', options: ['Tätigkeit', 'Pause', 'Belohnung', 'Fehler'], correct: [0], explanation: 'Aufgabe = Tätigkeit, zu erledigende Arbeit.', difficulty: 1 },
    { type: 'mc', prompt: 'Synonym für „Ziel“?', options: ['Zweck', 'Weg', 'Start', 'Hindernis'], correct: [0], explanation: 'Ziel = Zweck, angestrebtes Ergebnis.', difficulty: 1 },
    { type: 'mc', prompt: 'Synonym für „Idee“?', options: ['Einfall', 'Pflicht', 'Sorge', 'Regel'], correct: [0], explanation: 'Idee = Einfall, Gedanke.', difficulty: 1 },
    { type: 'mc', prompt: 'Synonym für „Hilfe“?', options: ['Unterstützung', 'Last', 'Strafe', 'Gefahr'], correct: [0], explanation: 'Hilfe = Unterstützung, Beistand.', difficulty: 1 },
    { type: 'mc', prompt: 'Synonym für „Fehler“?', options: ['Irrtum', 'Erfolg', 'Lösung', 'Vorteil'], correct: [0], explanation: 'Fehler = Irrtum, Versehen.', difficulty: 1 },
    { type: 'mc', prompt: 'Synonym für „wichtig“?', options: ['bedeutsam', 'belanglos', 'klein', 'leer'], correct: [0], explanation: 'Wichtig = bedeutsam, von Belang.', difficulty: 1 },
    { type: 'mc', prompt: 'Synonym für „erlauben“?', options: ['gestatten', 'verbieten', 'verhindern', 'zwingen'], correct: [0], explanation: 'Erlauben = gestatten, genehmigen.', difficulty: 1 },
    { type: 'mc', prompt: 'Synonym für „benötigen“?', options: ['brauchen', 'verschenken', 'ablehnen', 'verlieren'], correct: [0], explanation: 'Benötigen = brauchen.', difficulty: 1 },
    { type: 'mc', prompt: 'Synonym für „verbessern“?', options: ['optimieren', 'verschlechtern', 'zerstören', 'ignorieren'], correct: [0], explanation: 'Verbessern = optimieren, aufwerten.', difficulty: 2 },
    { type: 'mc', prompt: 'Synonym für „erklären“?', options: ['erläutern', 'verschweigen', 'verwirren', 'fragen'], correct: [0], explanation: 'Erklären = erläutern, darlegen.', difficulty: 1 },
    { type: 'mc', prompt: 'Synonym für „prüfen“?', options: ['kontrollieren', 'übersehen', 'raten', 'glauben'], correct: [0], explanation: 'Prüfen = kontrollieren, überprüfen.', difficulty: 1 },
    { type: 'mc', prompt: 'Synonym für „entscheiden“?', options: ['festlegen', 'zögern', 'aufschieben', 'fragen'], correct: [0], explanation: 'Entscheiden = festlegen, bestimmen.', difficulty: 2 },
    { type: 'mc', prompt: 'Synonym für „freundlich“?', options: ['nett', 'mürrisch', 'kalt', 'grob'], correct: [0], explanation: 'Freundlich = nett, zuvorkommend.', difficulty: 1 },
    { type: 'mc', prompt: 'Synonym für „mutig“?', options: ['tapfer', 'ängstlich', 'feige', 'müde'], correct: [0], explanation: 'Mutig = tapfer, beherzt.', difficulty: 1 },
    { type: 'mc', prompt: 'Synonym für „ehrlich“?', options: ['aufrichtig', 'falsch', 'verlogen', 'listig'], correct: [0], explanation: 'Ehrlich = aufrichtig, wahrhaftig.', difficulty: 1 },
    { type: 'mc', prompt: 'Synonym für „sparsam“?', options: ['genügsam', 'verschwenderisch', 'großzügig', 'reich'], correct: [0], explanation: 'Sparsam = genügsam, haushälterisch.', difficulty: 2 },
    { type: 'mc', prompt: 'Synonym für „neugierig“?', options: ['wissbegierig', 'gleichgültig', 'müde', 'satt'], correct: [0], explanation: 'Neugierig = wissbegierig, interessiert.', difficulty: 2 },
    { type: 'mc', prompt: 'Synonym für „berühmt“?', options: ['bekannt', 'unbekannt', 'verborgen', 'gewöhnlich'], correct: [0], explanation: 'Berühmt = bekannt, renommiert.', difficulty: 1 },
    { type: 'mc', prompt: 'Synonym für „gefährlich“?', options: ['riskant', 'sicher', 'harmlos', 'ruhig'], correct: [0], explanation: 'Gefährlich = riskant, bedrohlich.', difficulty: 1 },
    { type: 'mc', prompt: 'Synonym für „selten“?', options: ['rar', 'häufig', 'üblich', 'viel'], correct: [0], explanation: 'Selten = rar, ungewöhnlich.', difficulty: 2 },
    { type: 'mc', prompt: 'Synonym für „deutlich“?', options: ['klar', 'verschwommen', 'leise', 'dunkel'], correct: [0], explanation: 'Deutlich = klar, eindeutig.', difficulty: 1 },
    { type: 'mc', prompt: 'Synonym für „nützlich“?', options: ['hilfreich', 'sinnlos', 'schädlich', 'leer'], correct: [0], explanation: 'Nützlich = hilfreich, dienlich.', difficulty: 1 },
    { type: 'mc', prompt: 'Synonym für „beenden“?', options: ['abschließen', 'beginnen', 'starten', 'eröffnen'], correct: [0], explanation: 'Beenden = abschließen, beenden.', difficulty: 1 },
    { type: 'mc', prompt: 'Synonym für „ungefähr“?', options: ['etwa', 'genau', 'exakt', 'sicher'], correct: [0], explanation: 'Ungefähr = etwa, zirka.', difficulty: 1 },
    { type: 'mc', prompt: 'Synonym für „häufig“?', options: ['oft', 'nie', 'selten', 'kaum'], correct: [0], explanation: 'Häufig = oft, vielfach.', difficulty: 1 },
    { type: 'mc', prompt: 'Synonym für „zuverlässig“?', options: ['verlässlich', 'unsicher', 'wankelmütig', 'launisch'], correct: [0], explanation: 'Zuverlässig = verlässlich, vertrauenswürdig.', difficulty: 2 },
    { type: 'mc', prompt: 'Synonym für „anstrengend“?', options: ['mühsam', 'leicht', 'einfach', 'angenehm'], correct: [0], explanation: 'Anstrengend = mühsam, beschwerlich.', difficulty: 1 },
    { type: 'mc', prompt: 'Synonym für „freiwillig“?', options: ['ungezwungen', 'erzwungen', 'pflichtgemäß', 'verpflichtend'], correct: [0], explanation: 'Freiwillig = ungezwungen, aus eigenem Willen.', difficulty: 2 },
    { type: 'mc', prompt: 'Synonym für „vermuten“?', options: ['annehmen', 'wissen', 'beweisen', 'leugnen'], correct: [0], explanation: 'Vermuten = annehmen, mutmaßen.', difficulty: 2 },
    { type: 'mc', prompt: 'Synonym für „erschaffen“?', options: ['erzeugen', 'zerstören', 'kopieren', 'löschen'], correct: [0], explanation: 'Erschaffen = erzeugen, hervorbringen.', difficulty: 2 },
    { type: 'mc', prompt: 'Synonym für „gewöhnlich“?', options: ['üblich', 'außergewöhnlich', 'einzigartig', 'selten'], correct: [0], explanation: 'Gewöhnlich = üblich, normal.', difficulty: 2 },
    { type: 'mc', prompt: 'Synonym für „verständlich“?', options: ['begreiflich', 'rätselhaft', 'unklar', 'wirr'], correct: [0], explanation: 'Verständlich = begreiflich, nachvollziehbar.', difficulty: 2 },
    { type: 'mc', prompt: 'Synonym für „antworten“?', options: ['erwidern', 'fragen', 'schweigen', 'rufen'], correct: [0], explanation: 'Antworten = erwidern, entgegnen.', difficulty: 1 },
    { type: 'fill', prompt: 'Nenne ein Synonym für „Auto“.', correct: ['Wagen', 'Kraftfahrzeug', 'Pkw', 'KFZ', 'Kfz'], explanation: 'Auto = Wagen, Kraftfahrzeug, Pkw.', difficulty: 1 },
    { type: 'fill', prompt: 'Nenne ein Synonym für „schön“.', correct: ['hübsch', 'attraktiv', 'ansehnlich', 'reizvoll', 'wunderschön'], explanation: 'Schön = hübsch, attraktiv, ansehnlich.', difficulty: 1 },
    { type: 'fill', prompt: 'Nenne ein Synonym für „Haus“.', correct: ['Gebäude', 'Eigenheim', 'Wohnhaus', 'Bau'], explanation: 'Haus = Gebäude, Eigenheim, Wohnhaus.', difficulty: 1 },
  ],
};

export default topic;
