import type { RawTopic } from '../types';

const topic: RawTopic = {
  slug: 'technik-naturwissenschaft',
  title: 'Technik & Naturwissenschaft',
  description: 'Einheiten, physikalische und chemische Grundlagen.',
  flashcards: [
    {
      front: 'Wie viele SI-Basiseinheiten gibt es, und nenne sie.',
      back: 'Es gibt 7 SI-Basiseinheiten: Meter (m), Kilogramm (kg), Sekunde (s), Ampere (A), Kelvin (K), Mol (mol), Candela (cd).',
    },
    {
      front: 'In welcher Einheit wird die Kraft gemessen?',
      back: 'Kraft wird in Newton (N) gemessen. 1 N = 1 kg·m/s².',
    },
    {
      front: 'In welcher Einheit wird Energie gemessen?',
      back: 'Energie wird in Joule (J) gemessen. 1 J = 1 N·m = 1 kg·m²/s².',
    },
    {
      front: 'In welcher Einheit wird elektrische Leistung gemessen?',
      back: 'Elektrische Leistung wird in Watt (W) gemessen. 1 W = 1 J/s.',
    },
    {
      front: 'In welcher Einheit wird elektrische Spannung gemessen?',
      back: 'Elektrische Spannung wird in Volt (V) gemessen.',
    },
    {
      front: 'In welcher Einheit wird elektrische Stromstärke gemessen?',
      back: 'Elektrische Stromstärke wird in Ampere (A) gemessen.',
    },
    {
      front: 'In welcher Einheit wird Frequenz gemessen?',
      back: 'Frequenz wird in Hertz (Hz) gemessen. 1 Hz = 1 Schwingung pro Sekunde.',
    },
    {
      front: 'In welcher Einheit wird Druck gemessen?',
      back: 'Druck wird in Pascal (Pa) gemessen. 1 Pa = 1 N/m².',
    },
    {
      front: 'Bei welcher Temperatur kocht Wasser (unter Normaldruck)?',
      back: 'Wasser kocht bei 100 °C (373,15 K) unter Normaldruck (1013,25 hPa).',
    },
    {
      front: 'Bei welcher Temperatur gefriert Wasser (unter Normaldruck)?',
      back: 'Wasser gefriert bei 0 °C (273,15 K) unter Normaldruck.',
    },
    {
      front: 'Wie lautet die chemische Formel von Wasser?',
      back: 'Wasser hat die chemische Formel H₂O (2 Wasserstoffatome + 1 Sauerstoffatom).',
    },
    {
      front: 'Welches chemische Symbol steht für Eisen?',
      back: 'Fe (vom lateinischen "Ferrum") ist das chemische Symbol für Eisen.',
    },
    {
      front: 'Welches chemische Symbol steht für Gold?',
      back: 'Au (vom lateinischen "Aurum") ist das chemische Symbol für Gold.',
    },
    {
      front: 'Welches chemische Symbol steht für Natrium?',
      back: 'Na (vom lateinischen "Natrium") ist das chemische Symbol für Natrium.',
    },
    {
      front: 'Welche drei Aggregatzustände gibt es?',
      back: 'Die drei Aggregatzustände sind: fest (solid), flüssig (liquid) und gasförmig (gaseous).',
    },
    {
      front: 'Wie schnell ist Licht im Vakuum (ungefähr)?',
      back: 'Licht bewegt sich im Vakuum mit ca. 300.000 km/s (genau: 299.792.458 m/s).',
    },
    {
      front: 'Was ist Photosynthese?',
      back: 'Photosynthese ist der Prozess, bei dem Pflanzen mit Hilfe von Sonnenlicht, Wasser (H₂O) und Kohlendioxid (CO₂) Glucose und Sauerstoff (O₂) produzieren.',
    },
    {
      front: 'Was beschreibt die Erdbeschleunigung g?',
      back: 'Die Erdbeschleunigung g ≈ 9,81 m/s² ist die Beschleunigung, die ein frei fallender Körper im Schwerefeld der Erde erfährt.',
    },
    {
      front: 'Welches chemische Symbol steht für Kohlenstoff?',
      back: 'C (vom lateinischen "Carbonium") ist das chemische Symbol für Kohlenstoff.',
    },
    {
      front: 'Was ist der Unterschied zwischen Masse und Gewicht?',
      back: 'Masse (kg) ist eine unveränderliche Eigenschaft eines Körpers. Gewicht (N) ist die Kraft, mit der ein Körper aufgrund der Schwerkraft angezogen wird. Gewicht = Masse × Erdbeschleunigung.',
    },
    {
      front: 'Was bedeutet "absolute Temperatur" und welche Einheit wird verwendet?',
      back: 'Die absolute Temperatur wird in Kelvin (K) gemessen. 0 K (absoluter Nullpunkt) entspricht −273,15 °C. Umrechnung: T(K) = T(°C) + 273,15.',
    },
  ],
  questions: [
    {
      type: 'mc',
      prompt: 'In welcher Einheit wird elektrische Leistung gemessen?',
      options: ['Watt', 'Volt', 'Ampere', 'Joule'],
      correct: [0],
      explanation: 'Elektrische Leistung wird in Watt (W) gemessen. Leistung = Spannung × Stromstärke (P = U × I).',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welche SI-Basiseinheit wird für die Temperatur verwendet?',
      options: ['Celsius', 'Fahrenheit', 'Kelvin', 'Rankine'],
      correct: [2],
      explanation: 'Kelvin (K) ist die SI-Basiseinheit der Temperatur. Celsius und Fahrenheit sind abgeleitete Einheiten, keine SI-Basiseinheiten.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Wie lautet die chemische Formel von Wasser?',
      options: ['HO', 'H₂O₂', 'H₂O', 'H₃O'],
      correct: [2],
      explanation: 'Wasser besteht aus 2 Wasserstoffatomen und 1 Sauerstoffatom: H₂O. H₂O₂ ist Wasserstoffperoxid.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Bei welcher Temperatur kocht Wasser unter Normaldruck?',
      options: ['80 °C', '90 °C', '110 °C', '100 °C'],
      correct: [3],
      explanation: 'Wasser kocht unter Normaldruck (1013,25 hPa) bei genau 100 °C (373,15 K).',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welches chemische Symbol steht für Eisen?',
      options: ['Ei', 'Fe', 'Ir', 'Es'],
      correct: [1],
      explanation: 'Fe steht für Eisen und leitet sich vom lateinischen Wort "Ferrum" ab.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'In welcher Einheit wird Kraft gemessen?',
      options: ['Joule', 'Pascal', 'Watt', 'Newton'],
      correct: [3],
      explanation: 'Kraft wird in Newton (N) gemessen, benannt nach Isaac Newton. 1 N = 1 kg·m/s².',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welches chemische Symbol steht für Gold?',
      options: ['Go', 'Gd', 'Au', 'Ag'],
      correct: [2],
      explanation: 'Au steht für Gold und leitet sich vom lateinischen Wort "Aurum" ab. Ag steht dagegen für Silber (Argentum).',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Wie viele SI-Basiseinheiten gibt es?',
      options: ['5', '6', '8', '7'],
      correct: [3],
      explanation: 'Es gibt genau 7 SI-Basiseinheiten: Meter, Kilogramm, Sekunde, Ampere, Kelvin, Mol und Candela.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'In welcher Einheit wird Druck gemessen?',
      options: ['Newton', 'Pascal', 'Joule', 'Hertz'],
      correct: [1],
      explanation: 'Druck wird in Pascal (Pa) gemessen. 1 Pa = 1 N/m². Benannt nach dem Mathematiker Blaise Pascal.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welches chemische Symbol steht für Natrium?',
      options: ['N', 'Nm', 'Na', 'Nt'],
      correct: [2],
      explanation: 'Na steht für Natrium und leitet sich vom lateinischen "Natrium" ab. N ist das Symbol für Stickstoff (Nitrogen).',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Wie groß ist die Lichtgeschwindigkeit im Vakuum (gerundet)?',
      options: ['300.000 km/s', '30.000 km/s', '3.000.000 km/s', '3.000 km/s'],
      correct: [0],
      explanation: 'Licht bewegt sich im Vakuum mit ca. 300.000 km/s (genauer: 299.792.458 m/s).',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'In welcher Einheit wird Frequenz gemessen?',
      options: ['Watt', 'Hertz', 'Pascal', 'Volt'],
      correct: [1],
      explanation: 'Frequenz wird in Hertz (Hz) gemessen. 1 Hz bedeutet eine Schwingung pro Sekunde.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welches chemische Symbol steht für Wasserstoff?',
      options: ['W', 'Hs', 'H', 'Wa'],
      correct: [2],
      explanation: 'H ist das chemische Symbol für Wasserstoff (englisch: Hydrogen). Es ist das leichteste und häufigste Element im Universum.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welche drei Aggregatzustände des Wassers gibt es?',
      options: ['Fest, flüssig, gasförmig', 'Kalt, warm, heiß', 'Eis, Wasser, Dampf', 'Plasma, Flüssig, Dampf'],
      correct: [0],
      explanation: 'Die drei Aggregatzustände sind fest (Eis), flüssig (Wasser) und gasförmig (Wasserdampf). Diese gelten für alle Stoffe, nicht nur für Wasser.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was beschreibt die Erdbeschleunigung g?',
      options: [
        'Die Geschwindigkeit der Erde um die Sonne',
        'Die Beschleunigung eines frei fallenden Körpers im Schwerefeld der Erde',
        'Die Rotationsgeschwindigkeit der Erde',
        'Den Luftwiderstand in der Atmosphäre',
      ],
      correct: [1],
      explanation: 'Die Erdbeschleunigung g ≈ 9,81 m/s² beschreibt, wie stark ein frei fallender Körper im Schwerefeld der Erde beschleunigt wird.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welches chemische Symbol steht für Sauerstoff?',
      options: ['So', 'S', 'Sa', 'O'],
      correct: [3],
      explanation: 'O ist das chemische Symbol für Sauerstoff (englisch: Oxygen). S steht für Schwefel (Sulfur).',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'In welcher Einheit wird elektrische Spannung gemessen?',
      options: ['Ampere', 'Ohm', 'Volt', 'Watt'],
      correct: [2],
      explanation: 'Elektrische Spannung wird in Volt (V) gemessen, benannt nach Alessandro Volta.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welche Formel beschreibt die elektrische Leistung?',
      options: ['P = U / I', 'P = U + I', 'P = U × I', 'P = I / U'],
      correct: [2],
      explanation: 'Elektrische Leistung P (Watt) = Spannung U (Volt) × Stromstärke I (Ampere). Dies folgt aus dem Ohmschen Gesetz.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Bei welcher Temperatur gefriert Wasser unter Normaldruck?',
      options: ['−10 °C', '0 °C', '4 °C', '−5 °C'],
      correct: [1],
      explanation: 'Wasser gefriert unter Normaldruck bei 0 °C (273,15 K). Bei 4 °C hat Wasser seine höchste Dichte.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist die SI-Basiseinheit für die Stoffmenge?',
      options: ['Gramm', 'Liter', 'Mol', 'Kilogramm'],
      correct: [2],
      explanation: 'Mol (mol) ist die SI-Basiseinheit für die Stoffmenge. 1 Mol enthält ca. 6,022 × 10²³ Teilchen (Avogadro-Konstante).',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was versteht man unter dem absoluten Nullpunkt?',
      options: [
        '0 °C, der Gefrierpunkt von Wasser',
        '−100 °C, der kälteste erreichbare Laborwert',
        '−273,15 °C, die tiefste theoretisch mögliche Temperatur',
        '−200 °C, die Siedetemperatur von Stickstoff',
      ],
      correct: [2],
      explanation: 'Der absolute Nullpunkt liegt bei −273,15 °C (= 0 K). Bei dieser Temperatur kommt jede Wärmebewegung der Atome theoretisch zum Stillstand.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welcher Prozess wandelt Lichtenergie in chemische Energie um?',
      options: ['Atmung', 'Gärung', 'Photosynthese', 'Verbrennung'],
      correct: [2],
      explanation: 'Bei der Photosynthese wandeln Pflanzen Lichtenergie in chemische Energie um: CO₂ + H₂O → Glucose + O₂.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'In welcher Einheit wird Energie gemessen?',
      options: ['Newton', 'Watt', 'Pascal', 'Joule'],
      correct: [3],
      explanation: 'Energie wird in Joule (J) gemessen. 1 J = 1 N·m = 1 kg·m²/s². Benannt nach James Prescott Joule.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist der Unterschied zwischen Masse und Gewicht?',
      options: [
        'Es gibt keinen Unterschied, beide Begriffe sind identisch.',
        'Masse wird in Newton gemessen, Gewicht in Kilogramm.',
        'Masse ist eine Stoffeigenschaft (kg), Gewicht ist eine Kraft (N).',
        'Gewicht beschreibt das Volumen, Masse das Gewicht eines Körpers.',
      ],
      correct: [2],
      explanation: 'Masse (kg) ist eine unveränderliche Eigenschaft eines Körpers. Gewicht ist die Gravitationskraft, die auf diesen Körper wirkt, und wird in Newton (N) gemessen.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welches chemische Symbol steht für Kohlenstoff?',
      options: ['Ko', 'K', 'C', 'Ca'],
      correct: [2],
      explanation: 'C (von lateinisch "Carbonium") steht für Kohlenstoff. K ist das Symbol für Kalium, Ca für Calcium.',
      difficulty: 1,
    },
    {
      type: 'truefalse',
      prompt: 'Die Lichtgeschwindigkeit im Vakuum beträgt ungefähr 300.000 km/s.',
      options: ['Wahr', 'Falsch'],
      correct: [0],
      explanation: 'Richtig. Die Lichtgeschwindigkeit im Vakuum beträgt ca. 299.792.458 m/s ≈ 300.000 km/s.',
      difficulty: 1,
    },
    {
      type: 'truefalse',
      prompt: 'Wasser siedet unter Normaldruck bei 90 °C.',
      options: ['Wahr', 'Falsch'],
      correct: [1],
      explanation: 'Falsch. Wasser siedet unter Normaldruck bei 100 °C. Bei höheren Höhenlagen (geringerem Luftdruck) sinkt der Siedepunkt.',
      difficulty: 1,
    },
    {
      type: 'truefalse',
      prompt: 'Das chemische Symbol für Gold ist "Go".',
      options: ['Wahr', 'Falsch'],
      correct: [1],
      explanation: 'Falsch. Das chemische Symbol für Gold ist "Au", abgeleitet vom lateinischen Wort "Aurum".',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welche SI-Basiseinheit wird für die Lichtstärke verwendet?',
      options: ['Lux', 'Lumen', 'Candela', 'Watt'],
      correct: [2],
      explanation: 'Candela (cd) ist die SI-Basiseinheit der Lichtstärke. Lumen ist die abgeleitete Einheit des Lichtstroms, Lux die der Beleuchtungsstärke.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Welches Gasgemisch besteht die Luft hauptsächlich aus?',
      options: [
        'Ca. 78 % Sauerstoff und 21 % Stickstoff',
        'Ca. 78 % Stickstoff und 21 % Sauerstoff',
        'Ca. 50 % Stickstoff und 50 % Kohlendioxid',
        'Ca. 100 % Sauerstoff',
      ],
      correct: [1],
      explanation: 'Luft besteht zu ca. 78 % aus Stickstoff (N₂) und ca. 21 % aus Sauerstoff (O₂). Die restlichen ~1 % sind vor allem Argon und CO₂.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was beschreibt das Ohmsche Gesetz?',
      options: [
        'U = I × R (Spannung = Stromstärke × Widerstand)',
        'P = U × I (Leistung = Spannung × Strom)',
        'F = m × a (Kraft = Masse × Beschleunigung)',
        'E = m × c² (Energie = Masse × Lichtgeschwindigkeit²)',
      ],
      correct: [0],
      explanation: 'Das Ohmsche Gesetz lautet U = I × R: Die elektrische Spannung U (Volt) ist gleich Stromstärke I (Ampere) multipliziert mit dem Widerstand R (Ohm).',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welche Aussage über den Aggregatzustandswechsel von fest zu flüssig ist korrekt?',
      options: [
        'Dieser Vorgang heißt Verdampfen und findet bei jeder Temperatur statt.',
        'Dieser Vorgang heißt Schmelzen und erfordert Energiezufuhr.',
        'Dieser Vorgang heißt Kondensieren und gibt Energie ab.',
        'Dieser Vorgang heißt Sublimieren und findet nur bei Eis statt.',
      ],
      correct: [1],
      explanation: 'Der Übergang von fest zu flüssig heißt Schmelzen. Dabei muss Energie (Schmelzwärme) zugeführt werden. Verdampfen: flüssig → gasförmig; Kondensieren: gasförmig → flüssig; Sublimieren: fest → gasförmig.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welche Einheit entspricht 1 Joule?',
      options: ['1 kg·m/s', '1 kg·m²/s²', '1 kg·m²/s³', '1 N/m²'],
      correct: [1],
      explanation: '1 Joule = 1 N·m = 1 kg·m²/s². 1 kg·m²/s³ entspricht 1 Watt, und 1 N/m² entspricht 1 Pascal.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Welche Aussage zur Photosynthese ist korrekt?',
      options: [
        'Pflanzen nehmen Sauerstoff auf und geben Kohlendioxid ab.',
        'Photosynthese findet nur in tierischen Zellen statt.',
        'Pflanzen wandeln CO₂ und H₂O mithilfe von Licht in Glucose und O₂ um.',
        'Photosynthese erzeugt ausschließlich Kohlendioxid.',
      ],
      correct: [2],
      explanation: 'Bei der Photosynthese nehmen Pflanzen CO₂ und H₂O auf und produzieren mithilfe von Lichtenergie Glucose (C₆H₁₂O₆) und Sauerstoff (O₂).',
      difficulty: 2,
    },
  ],
};

export default topic;
