import type { RawTopic } from '../types';

const topic: RawTopic = {
  slug: 'textverstaendnis',
  title: 'Textverständnis',
  description: 'Kurze Texte lesen und Aussagen richtig erfassen.',
  flashcards: [
    {
      front: 'Was versteht man unter der Hauptaussage eines Textes?',
      back: 'Die Hauptaussage ist der zentrale Gedanke, den der Text vermittelt – das, worüber der gesamte Text handelt und was der Autor hauptsächlich mitteilen möchte.',
    },
    {
      front: 'Was sind Schlüsselwörter und wozu dienen sie?',
      back: 'Schlüsselwörter sind bedeutungstragende Wörter, die das Thema und den Inhalt eines Textes kennzeichnen. Sie helfen beim schnellen Erfassen des Textthemas und beim gezielten Suchen von Informationen.',
    },
    {
      front: 'Welche W-Fragen helfen beim Textverständnis?',
      back: 'Wer? Was? Wann? Wo? Wie? Warum? Wozu? – Diese sechs W-Fragen helfen dabei, die wesentlichen Informationen eines Textes systematisch zu erschließen.',
    },
    {
      front: 'Was ist der Unterschied zwischen einer Aussage und einer Meinung?',
      back: 'Eine Aussage (Tatsachenbehauptung) ist überprüfbar und kann wahr oder falsch sein. Eine Meinung ist eine subjektive Einschätzung oder Wertung, die nicht objektiv bewiesen werden kann.',
    },
    {
      front: 'Was ist eine Schlussfolgerung im Kontext des Lesens?',
      back: 'Eine Schlussfolgerung ist eine Erkenntnis, die man aus dem Gelesenen ableitet, auch wenn sie nicht direkt im Text steht. Sie ergibt sich logisch aus den im Text genannten Informationen.',
    },
    {
      front: 'Was bedeutet "selektives Lesen"?',
      back: 'Beim selektiven Lesen sucht man gezielt nach bestimmten Informationen im Text, ohne ihn vollständig zu lesen. Man überfliegt den Text und hält Ausschau nach Schlüsselbegriffen oder relevanten Passagen.',
    },
    {
      front: 'Was ist der Unterschied zwischen globalem und detailliertem Lesen?',
      back: 'Globales Lesen (Überfliegender Lesestil) dient dem schnellen Erfassen des Gesamtinhalts. Detailliertes Lesen bedeutet, jeden Satz genau zu lesen, um alle Informationen vollständig zu verstehen.',
    },
    {
      front: 'Was versteht man unter einem impliziten Inhalt eines Textes?',
      back: 'Implizite Inhalte sind Informationen, die nicht direkt im Text stehen, sich aber aus dem Gesagten logisch ergeben oder zwischen den Zeilen gelesen werden können.',
    },
    {
      front: 'Was versteht man unter einem expliziten Inhalt eines Textes?',
      back: 'Explizite Inhalte sind Informationen, die direkt und wörtlich im Text genannt werden. Sie müssen nicht erschlossen werden, sondern sind klar und eindeutig formuliert.',
    },
    {
      front: 'Wie erkennt man die Textstruktur?',
      back: 'Die Textstruktur erkennt man an Gliederungssignalen wie Absätzen, Überschriften, Konnektoren (erstens, dann, deshalb, jedoch) und der logischen Abfolge von Einleitung, Hauptteil und Schluss.',
    },
    {
      front: 'Was ist ein Kontext und warum ist er beim Lesen wichtig?',
      back: 'Der Kontext umfasst den sprachlichen und inhaltlichen Zusammenhang, in dem ein Wort oder eine Aussage steht. Er hilft, die Bedeutung unbekannter Wörter zu erschließen und Aussagen richtig zu verstehen.',
    },
    {
      front: 'Was bedeutet "paraphrasieren" beim Textverständnis?',
      back: 'Paraphrasieren bedeutet, einen Textabschnitt mit eigenen Worten wiederzugeben, ohne den Sinn zu verändern. Es zeigt, ob man den Inhalt wirklich verstanden hat.',
    },
    {
      front: 'Was ist ein Widerspruch im Text und wie erkennt man ihn?',
      back: 'Ein Widerspruch liegt vor, wenn zwei Aussagen im Text einander ausschließen oder unvereinbar sind. Man erkennt ihn, indem man Aussagen miteinander vergleicht und auf logische Konsistenz prüft.',
    },
    {
      front: 'Was ist der Unterschied zwischen "richtig" und "sinngemäß richtig" bei Textfragen?',
      back: '"Richtig" bedeutet: die Antwort steht wörtlich so im Text. "Sinngemäß richtig" bedeutet: die Antwort gibt den Inhalt des Textes korrekt wieder, auch wenn andere Formulierungen verwendet werden.',
    },
    {
      front: 'Was versteht man unter Textkoheränz?',
      back: 'Textkohärenz bezeichnet den inhaltlichen Zusammenhang eines Textes. Ein kohärenter Text ist in sich logisch und widerspruchsfrei – alle Teile hängen sinnvoll zusammen.',
    },
    {
      front: 'Welche Strategie hilft bei der Frage "Was steht NICHT im Text?"',
      back: 'Man liest alle Antwortoptionen und prüft jede einzeln gegen den Text. Die Option, die im Text nicht erwähnt wird oder dem Text widerspricht, ist die gesuchte Antwort.',
    },
    {
      front: 'Was ist ein Leseziel und warum sollte man es vor dem Lesen festlegen?',
      back: 'Ein Leseziel beschreibt, was man durch das Lesen herausfinden möchte. Ein klares Leseziel hilft, relevante Informationen schneller zu finden und sich nicht in Unwichtigem zu verlieren.',
    },
  ],
  questions: [
    // Text 1: Stadtbibliothek
    {
      type: 'mc',
      prompt: 'Was ist die Hauptaussage des Textes?',
      code: 'Die Stadtbibliothek verlängert ab Montag ihre Öffnungszeiten. Künftig ist sie auch samstags bis 18 Uhr geöffnet, um Berufstätigen den Besuch zu erleichtern.',
      options: [
        'Die Bibliothek hat erweiterte Öffnungszeiten, auch samstags.',
        'Die Bibliothek schließt samstags früher als bisher.',
        'Die Bibliothek wird für Berufstätige gebaut.',
        'Die Bibliothek ist ab sofort täglich geschlossen.',
      ],
      correct: [0],
      explanation: 'Der Text nennt explizit die Verlängerung der Öffnungszeiten, einschließlich des Samstags bis 18 Uhr.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welche Aussage steht NICHT im Text?',
      code: 'Die Stadtbibliothek verlängert ab Montag ihre Öffnungszeiten. Künftig ist sie auch samstags bis 18 Uhr geöffnet, um Berufstätigen den Besuch zu erleichtern.',
      options: [
        'Die Änderung gilt ab Montag.',
        'Die Bibliothek ist samstags bis 18 Uhr geöffnet.',
        'Die Maßnahme soll Berufstätigen helfen.',
        'Die Bibliothek kauft neue Bücher an.',
      ],
      correct: [3],
      explanation: 'Der Ankauf neuer Bücher wird im Text nicht erwähnt. Alle anderen Optionen sind im Text enthalten.',
      difficulty: 2,
    },
    // Text 2: Bahnstrecke
    {
      type: 'mc',
      prompt: 'Was ist der Grund für die Streckensperrung laut Text?',
      code: 'Wegen Gleisarbeiten wird die Bahnstrecke zwischen Neustadt und Waldbach vom 10. bis 14. Juni vollständig gesperrt. Reisende werden gebeten, auf den Schienenersatzverkehr auszuweichen, der im 30-Minuten-Takt verkehrt.',
      options: [
        'Ein Unfall hat die Strecke beschädigt.',
        'Gleisarbeiten machen die Sperrung notwendig.',
        'Die Strecke wird dauerhaft eingestellt.',
        'Personalmangel führt zur Sperrung.',
      ],
      correct: [1],
      explanation: 'Der Text nennt "Gleisarbeiten" ausdrücklich als Grund für die Sperrung.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Wie häufig verkehrt der Ersatzverkehr laut Text?',
      code: 'Wegen Gleisarbeiten wird die Bahnstrecke zwischen Neustadt und Waldbach vom 10. bis 14. Juni vollständig gesperrt. Reisende werden gebeten, auf den Schienenersatzverkehr auszuweichen, der im 30-Minuten-Takt verkehrt.',
      options: [
        'Stündlich',
        'Alle 30 Minuten',
        'Alle 15 Minuten',
        'Nur morgens und abends',
      ],
      correct: [1],
      explanation: 'Der Text sagt ausdrücklich, dass der Ersatzverkehr "im 30-Minuten-Takt" verkehrt.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was kann man aus dem Text schlussfolgern?',
      code: 'Wegen Gleisarbeiten wird die Bahnstrecke zwischen Neustadt und Waldbach vom 10. bis 14. Juni vollständig gesperrt. Reisende werden gebeten, auf den Schienenersatzverkehr auszuweichen, der im 30-Minuten-Takt verkehrt.',
      options: [
        'Die Strecke wird nach dem 14. Juni wieder befahrbar sein.',
        'Der Ersatzverkehr fährt dieselbe Route wie der Zug.',
        'Die Arbeiten werden länger dauern als geplant.',
        'Reisende müssen kein Ticket kaufen.',
      ],
      correct: [0],
      explanation: 'Da die Sperrung "vom 10. bis 14. Juni" gilt, ist davon auszugehen, dass die Strecke danach wieder geöffnet ist. Dies lässt sich logisch ableiten.',
      difficulty: 2,
    },
    // Text 3: Impfkampagne
    {
      type: 'mc',
      prompt: 'Was ist die Hauptaussage des Textes?',
      code: 'Das Gesundheitsamt ruft alle Bürgerinnen und Bürger über 60 Jahre zur Grippeschutzimpfung auf. Die Impfung ist kostenlos und kann beim Hausarzt oder in den städtischen Impfzentren durchgeführt werden.',
      options: [
        'Alle Personen über 60 werden automatisch geimpft.',
        'Das Gesundheitsamt empfiehlt älteren Bürgern die kostenlose Grippeimpfung.',
        'Nur Hausärzte dürfen die Impfung durchführen.',
        'Die Impfung ist für alle Altersgruppen kostenlos.',
      ],
      correct: [1],
      explanation: 'Der Text richtet sich an Personen über 60, die Impfung ist kostenlos und kann beim Hausarzt oder in Impfzentren erfolgen.',
      difficulty: 1,
    },
    {
      type: 'truefalse',
      prompt: 'Stimmt es laut Text, dass die Grippeimpfung ausschließlich beim Hausarzt möglich ist?',
      code: 'Das Gesundheitsamt ruft alle Bürgerinnen und Bürger über 60 Jahre zur Grippeschutzimpfung auf. Die Impfung ist kostenlos und kann beim Hausarzt oder in den städtischen Impfzentren durchgeführt werden.',
      options: ['Richtig', 'Falsch'],
      correct: [1],
      explanation: 'Der Text nennt zwei Möglichkeiten: Hausarzt ODER städtische Impfzentren. Die Aussage "ausschließlich beim Hausarzt" ist daher falsch.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welche Personengruppe wird laut Text zur Impfung aufgerufen?',
      code: 'Das Gesundheitsamt ruft alle Bürgerinnen und Bürger über 60 Jahre zur Grippeschutzimpfung auf. Die Impfung ist kostenlos und kann beim Hausarzt oder in den städtischen Impfzentren durchgeführt werden.',
      options: [
        'Alle Bürgerinnen und Bürger',
        'Kinder unter 10 Jahren',
        'Personen über 60 Jahre',
        'Nur Personen mit Vorerkrankungen',
      ],
      correct: [2],
      explanation: 'Der Text nennt ausdrücklich "alle Bürgerinnen und Bürger über 60 Jahre" als Zielgruppe.',
      difficulty: 1,
    },
    // Text 4: Neues Schulgesetz
    {
      type: 'mc',
      prompt: 'Was regelt das neue Gesetz laut Text?',
      code: 'Der Landtag hat ein neues Schulgesetz verabschiedet, das die Klassengrößen an Grundschulen auf maximal 24 Schülerinnen und Schüler begrenzt. Das Gesetz tritt zum Beginn des nächsten Schuljahres in Kraft.',
      options: [
        'Die Ausbildung von Lehrkräften wird neu geregelt.',
        'Klassengrößen an Grundschulen werden auf maximal 24 begrenzt.',
        'Weiterführende Schulen erhalten mehr Finanzmittel.',
        'Das Schuljahr wird um zwei Wochen verlängert.',
      ],
      correct: [1],
      explanation: 'Der Text besagt eindeutig, dass Klassengrößen an Grundschulen auf maximal 24 Schülerinnen und Schüler begrenzt werden.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Wann tritt das Gesetz in Kraft?',
      code: 'Der Landtag hat ein neues Schulgesetz verabschiedet, das die Klassengrößen an Grundschulen auf maximal 24 Schülerinnen und Schüler begrenzt. Das Gesetz tritt zum Beginn des nächsten Schuljahres in Kraft.',
      options: [
        'Sofort nach der Verabschiedung',
        'Zum Ende des laufenden Schuljahres',
        'Zum Beginn des nächsten Schuljahres',
        'In drei Jahren',
      ],
      correct: [2],
      explanation: 'Der Text nennt "zum Beginn des nächsten Schuljahres" als Zeitpunkt des Inkrafttretens.',
      difficulty: 1,
    },
    {
      type: 'truefalse',
      prompt: 'Ist die folgende Aussage korrekt: Das Gesetz gilt für alle Schultypen?',
      code: 'Der Landtag hat ein neues Schulgesetz verabschiedet, das die Klassengrößen an Grundschulen auf maximal 24 Schülerinnen und Schüler begrenzt. Das Gesetz tritt zum Beginn des nächsten Schuljahres in Kraft.',
      options: ['Richtig', 'Falsch'],
      correct: [1],
      explanation: 'Der Text spricht ausdrücklich nur von "Grundschulen". Die Aussage, das Gesetz gelte für alle Schultypen, ist daher falsch.',
      difficulty: 2,
    },
    // Text 5: Parkplatz
    {
      type: 'mc',
      prompt: 'Was ist laut Text der Hauptgrund für die Parkplatzsperrung?',
      code: 'Der Parkplatz vor dem Rathaus wird ab dem 1. Juli für drei Wochen gesperrt. Grund sind notwendige Sanierungsarbeiten am Untergrund. Während dieser Zeit stehen alternative Parkplätze in der Gartenstraße zur Verfügung.',
      options: [
        'Ein Stadtfest findet auf dem Parkplatz statt.',
        'Der Parkplatz wird dauerhaft aufgelöst.',
        'Sanierungsarbeiten am Untergrund sind notwendig.',
        'Die Zufahrt ist durch Bauarbeiten blockiert.',
      ],
      correct: [2],
      explanation: 'Der Text nennt "notwendige Sanierungsarbeiten am Untergrund" als Ursache der Sperrung.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welche Schlussfolgerung kann man aus dem Text ziehen?',
      code: 'Der Parkplatz vor dem Rathaus wird ab dem 1. Juli für drei Wochen gesperrt. Grund sind notwendige Sanierungsarbeiten am Untergrund. Während dieser Zeit stehen alternative Parkplätze in der Gartenstraße zur Verfügung.',
      options: [
        'Nach drei Wochen ist der Parkplatz wieder nutzbar.',
        'Die Gartenstraße wird auch gesperrt.',
        'Sanierungsarbeiten werden täglich durchgeführt.',
        'Das Rathaus bleibt geschlossen.',
      ],
      correct: [0],
      explanation: 'Die Sperrung gilt "für drei Wochen", daher ist davon auszugehen, dass der Parkplatz danach wieder nutzbar ist.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welche Aussage steht NICHT im Text?',
      code: 'Der Parkplatz vor dem Rathaus wird ab dem 1. Juli für drei Wochen gesperrt. Grund sind notwendige Sanierungsarbeiten am Untergrund. Während dieser Zeit stehen alternative Parkplätze in der Gartenstraße zur Verfügung.',
      options: [
        'Die Sperrung beginnt am 1. Juli.',
        'Alternativen gibt es in der Gartenstraße.',
        'Der Parkplatz wird danach kostenpflichtig.',
        'Sanierungsarbeiten sind der Grund der Sperrung.',
      ],
      correct: [2],
      explanation: 'Eine mögliche Kostenpflicht wird im Text nicht erwähnt. Alle anderen Optionen sind im Text enthalten.',
      difficulty: 2,
    },
    // Text 6: Umweltprojekt
    {
      type: 'mc',
      prompt: 'Was ist die Hauptaussage des Textes?',
      code: 'Die Stadt Grüntal startet ein neues Umweltprojekt zur Begrünung von Flachdächern. Eigentümer von Wohngebäuden können einen Zuschuss von bis zu 5.000 Euro beantragen, wenn sie ihr Dach begrünen lassen. Ziel ist es, das Stadtklima zu verbessern und Regenwasser besser zu versickern.',
      options: [
        'Grüntal baut neue Parks in der Innenstadt.',
        'Wohngebäudeeigentümer erhalten Förderung für Dachbegrünung zur Klimaverbesserung.',
        'Alle Flachdächer müssen verpflichtend begrünt werden.',
        'Das Projekt soll den Energieverbrauch senken.',
      ],
      correct: [1],
      explanation: 'Der Text beschreibt ein Förderprogramm für Dachbegrünung mit dem Ziel der Klimaverbesserung und besseren Regenwasserversickerung.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Wie hoch ist der maximale Zuschuss laut Text?',
      code: 'Die Stadt Grüntal startet ein neues Umweltprojekt zur Begrünung von Flachdächern. Eigentümer von Wohngebäuden können einen Zuschuss von bis zu 5.000 Euro beantragen, wenn sie ihr Dach begrünen lassen. Ziel ist es, das Stadtklima zu verbessern und Regenwasser besser zu versickern.',
      options: [
        '1.000 Euro',
        '3.000 Euro',
        '5.000 Euro',
        '10.000 Euro',
      ],
      correct: [2],
      explanation: 'Der Text nennt ausdrücklich einen Zuschuss von "bis zu 5.000 Euro".',
      difficulty: 1,
    },
    {
      type: 'truefalse',
      prompt: 'Stimmt es laut Text, dass das Projekt verpflichtend für alle Gebäudearten gilt?',
      code: 'Die Stadt Grüntal startet ein neues Umweltprojekt zur Begrünung von Flachdächern. Eigentümer von Wohngebäuden können einen Zuschuss von bis zu 5.000 Euro beantragen, wenn sie ihr Dach begrünen lassen. Ziel ist es, das Stadtklima zu verbessern und Regenwasser besser zu versickern.',
      options: ['Richtig', 'Falsch'],
      correct: [1],
      explanation: 'Der Text beschreibt ein freiwilliges Förderprogramm für Eigentümer von Wohngebäuden, keine Verpflichtung für alle Gebäudearten.',
      difficulty: 3,
    },
    // Text 7: Digitale Verwaltung
    {
      type: 'mc',
      prompt: 'Welches Ziel verfolgt die neue digitale Plattform laut Text?',
      code: 'Ab Oktober können Bürgerinnen und Bürger viele Behördengänge bequem online erledigen. Die neue digitale Verwaltungsplattform ermöglicht die Beantragung von Personalausweisen, Ummeldungen und Gewerbeanmeldungen ohne persönliches Erscheinen. Damit soll der Verwaltungsaufwand für alle Beteiligten reduziert werden.',
      options: [
        'Die Anzahl der Behörden soll verringert werden.',
        'Bürger sollen mehr persönlich zu den Ämtern kommen.',
        'Behördengänge sollen online möglich sein und Aufwand reduzieren.',
        'Nur Gewerbetreibende profitieren von der Plattform.',
      ],
      correct: [2],
      explanation: 'Der Text beschreibt eine Online-Plattform, die Behördengänge erleichtert und Verwaltungsaufwand für alle Beteiligten reduziert.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welche Dienstleistung wird im Text NICHT genannt?',
      code: 'Ab Oktober können Bürgerinnen und Bürger viele Behördengänge bequem online erledigen. Die neue digitale Verwaltungsplattform ermöglicht die Beantragung von Personalausweisen, Ummeldungen und Gewerbeanmeldungen ohne persönliches Erscheinen. Damit soll der Verwaltungsaufwand für alle Beteiligten reduziert werden.',
      options: [
        'Beantragung von Personalausweisen',
        'Ummeldung des Wohnsitzes',
        'Gewerbeanmeldung',
        'Beantragung von Baugenehmigungen',
      ],
      correct: [3],
      explanation: 'Baugenehmigungen werden im Text nicht erwähnt. Genannt werden Personalausweise, Ummeldungen und Gewerbeanmeldungen.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was kann man aus dem Text schlussfolgern?',
      code: 'Ab Oktober können Bürgerinnen und Bürger viele Behördengänge bequem online erledigen. Die neue digitale Verwaltungsplattform ermöglicht die Beantragung von Personalausweisen, Ummeldungen und Gewerbeanmeldungen ohne persönliches Erscheinen. Damit soll der Verwaltungsaufwand für alle Beteiligten reduziert werden.',
      options: [
        'Persönliche Besuche bei Behörden sind ab Oktober verboten.',
        'Vor Oktober war kein einziger Behördengang online möglich.',
        'Die Plattform soll Bürger und Verwaltung entlasten.',
        'Die Plattform kostet Bürger eine Gebühr.',
      ],
      correct: [2],
      explanation: 'Der Text sagt, der Aufwand soll "für alle Beteiligten" reduziert werden – das schließt sowohl Bürger als auch die Verwaltung ein.',
      difficulty: 2,
    },
    // Text 8: Hochwasserschutz
    {
      type: 'mc',
      prompt: 'Was ist die Hauptaussage des Textes?',
      code: 'Die Gemeinde Flussdorf investiert 2,3 Millionen Euro in neue Hochwasserschutzmaßnahmen. Geplant sind ein erhöhter Deich entlang des Flussufers sowie die Anlage von Rückhaltebecken im östlichen Ortsbereich. Die Maßnahmen sollen bis Ende des Jahres abgeschlossen sein.',
      options: [
        'Flussdorf erhält einen neuen Sportpark am Fluss.',
        'Die Gemeinde investiert in Hochwasserschutz durch Deich und Rückhaltebecken.',
        'Der Fluss wird für den Schiffsverkehr ausgebaut.',
        'Alle Gebäude im Osten müssen abgerissen werden.',
      ],
      correct: [1],
      explanation: 'Der Text beschreibt eine Investition in Hochwasserschutz mit konkreten Maßnahmen wie Deicherhöhung und Rückhaltebecken.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Wo sollen die Rückhaltebecken laut Text angelegt werden?',
      code: 'Die Gemeinde Flussdorf investiert 2,3 Millionen Euro in neue Hochwasserschutzmaßnahmen. Geplant sind ein erhöhter Deich entlang des Flussufers sowie die Anlage von Rückhaltebecken im östlichen Ortsbereich. Die Maßnahmen sollen bis Ende des Jahres abgeschlossen sein.',
      options: [
        'Im westlichen Ortsbereich',
        'Im Zentrum der Gemeinde',
        'Im östlichen Ortsbereich',
        'Außerhalb der Gemeindegrenzen',
      ],
      correct: [2],
      explanation: 'Der Text nennt ausdrücklich "den östlichen Ortsbereich" als Standort der Rückhaltebecken.',
      difficulty: 1,
    },
    {
      type: 'truefalse',
      prompt: 'Ist folgende Aussage korrekt: Die Maßnahmen kosten mehr als drei Millionen Euro?',
      code: 'Die Gemeinde Flussdorf investiert 2,3 Millionen Euro in neue Hochwasserschutzmaßnahmen. Geplant sind ein erhöhter Deich entlang des Flussufers sowie die Anlage von Rückhaltebecken im östlichen Ortsbereich. Die Maßnahmen sollen bis Ende des Jahres abgeschlossen sein.',
      options: ['Richtig', 'Falsch'],
      correct: [1],
      explanation: 'Laut Text beträgt die Investition 2,3 Millionen Euro – das ist weniger als drei Millionen Euro.',
      difficulty: 2,
    },
    // Text 9: Seniorenzentrum
    {
      type: 'mc',
      prompt: 'Was ist laut Text der Zweck des neuen Seniorenzentrums?',
      code: 'In der Bergstraße entsteht ein neues Seniorenzentrum mit 80 Pflegeplätzen und einem integrierten Tagespflegeangebot. Das Zentrum soll ältere Menschen mit und ohne Pflegebedarf ansprechen und ihnen ein selbstbestimmtes Leben im Alter ermöglichen. Die Eröffnung ist für das Frühjahr geplant.',
      options: [
        'Das Zentrum bietet ausschließlich stationäre Pflege an.',
        'Es sollen Wohnungen für Familien gebaut werden.',
        'Das Zentrum bietet Pflege und Tagesbetreuung für selbstbestimmtes Leben im Alter.',
        'Das Zentrum richtet sich nur an pflegebedürftige Personen.',
      ],
      correct: [2],
      explanation: 'Der Text nennt Pflegeplätze, Tagespflege und das Ziel eines selbstbestimmten Lebens im Alter für Menschen mit und ohne Pflegebedarf.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Wie viele Pflegeplätze hat das neue Zentrum laut Text?',
      code: 'In der Bergstraße entsteht ein neues Seniorenzentrum mit 80 Pflegeplätzen und einem integrierten Tagespflegeangebot. Das Zentrum soll ältere Menschen mit und ohne Pflegebedarf ansprechen und ihnen ein selbstbestimmtes Leben im Alter ermöglichen. Die Eröffnung ist für das Frühjahr geplant.',
      options: [
        '60 Pflegeplätze',
        '80 Pflegeplätze',
        '100 Pflegeplätze',
        '120 Pflegeplätze',
      ],
      correct: [1],
      explanation: 'Der Text nennt ausdrücklich "80 Pflegeplätze".',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welche Aussage steht NICHT im Text?',
      code: 'In der Bergstraße entsteht ein neues Seniorenzentrum mit 80 Pflegeplätzen und einem integrierten Tagespflegeangebot. Das Zentrum soll ältere Menschen mit und ohne Pflegebedarf ansprechen und ihnen ein selbstbestimmtes Leben im Alter ermöglichen. Die Eröffnung ist für das Frühjahr geplant.',
      options: [
        'Das Zentrum liegt in der Bergstraße.',
        'Es gibt ein Tagespflegeangebot.',
        'Das Zentrum wird von der Stadt finanziert.',
        'Die Eröffnung ist für das Frühjahr geplant.',
      ],
      correct: [2],
      explanation: 'Über die Finanzierungsquelle des Zentrums steht nichts im Text. Alle anderen Aussagen sind explizit enthalten.',
      difficulty: 2,
    },
    // Text 10: Radwegenetz
    {
      type: 'mc',
      prompt: 'Was ist die Hauptaussage des Textes?',
      code: 'Der Stadtrat hat beschlossen, das Radwegenetz in den nächsten fünf Jahren um 40 Kilometer zu erweitern. Schwerpunkte sollen Verbindungen zwischen den Stadtteilen und gesicherte Schulwege sein. Das Projekt wird aus EU-Fördermitteln und städtischen Haushaltsmitteln finanziert.',
      options: [
        'Der Stadtrat plant den Abbau bestehender Radwege.',
        'Das Radwegenetz soll in fünf Jahren um 40 km erweitert werden.',
        'Das Projekt wird ausschließlich aus EU-Mitteln finanziert.',
        'Neue Radwege entstehen nur auf Schulgeländen.',
      ],
      correct: [1],
      explanation: 'Der Text beschreibt den Beschluss, das Radwegenetz um 40 Kilometer zu erweitern, mit Schwerpunkt auf Stadtteilverbindungen und Schulwegen.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Woraus wird das Projekt laut Text finanziert?',
      code: 'Der Stadtrat hat beschlossen, das Radwegenetz in den nächsten fünf Jahren um 40 Kilometer zu erweitern. Schwerpunkte sollen Verbindungen zwischen den Stadtteilen und gesicherte Schulwege sein. Das Projekt wird aus EU-Fördermitteln und städtischen Haushaltsmitteln finanziert.',
      options: [
        'Ausschließlich aus EU-Fördermitteln',
        'Ausschließlich aus städtischen Haushaltsmitteln',
        'Aus EU-Fördermitteln und städtischen Haushaltsmitteln',
        'Aus privaten Spenden',
      ],
      correct: [2],
      explanation: 'Der Text nennt beide Quellen: "EU-Fördermitteln und städtischen Haushaltsmitteln".',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was kann man aus dem Text schlussfolgern?',
      code: 'Der Stadtrat hat beschlossen, das Radwegenetz in den nächsten fünf Jahren um 40 Kilometer zu erweitern. Schwerpunkte sollen Verbindungen zwischen den Stadtteilen und gesicherte Schulwege sein. Das Projekt wird aus EU-Fördermitteln und städtischen Haushaltsmitteln finanziert.',
      options: [
        'Der Stadtrat möchte den Fahrradverkehr in der Stadt fördern.',
        'Autos sollen aus der Stadt verbannt werden.',
        'Das Projekt ist bereits vollständig umgesetzt.',
        'Schulen erhalten neue Fahrradabstellplätze.',
      ],
      correct: [0],
      explanation: 'Der Ausbau des Radwegenetzes um 40 km lässt klar schlussfolgern, dass der Stadtrat den Fahrradverkehr fördern möchte.',
      difficulty: 2,
    },
    // Text 11: Feuerwehr
    {
      type: 'mc',
      prompt: 'Was ist die Hauptaussage des Textes?',
      code: 'Die Freiwillige Feuerwehr Kleindorf sucht dringend neue Mitglieder. Durch Wegzüge und Altersgründe ist die Einsatzbereitschaft gefährdet. Interessierte ab 18 Jahren können sich beim Gerätewart oder online bewerben. Vorkenntnisse sind nicht erforderlich.',
      options: [
        'Die Freiwillige Feuerwehr wird aufgelöst.',
        'Die Feuerwehr Kleindorf sucht neue Mitglieder, da die Einsatzbereitschaft gefährdet ist.',
        'Nur Personen mit Feuerwehrerfahrung können sich bewerben.',
        'Die Feuerwehr erhält neue Fahrzeuge.',
      ],
      correct: [1],
      explanation: 'Der Text beschreibt Mitgliedersuche der Freiwilligen Feuerwehr Kleindorf wegen gefährdeter Einsatzbereitschaft.',
      difficulty: 1,
    },
    {
      type: 'truefalse',
      prompt: 'Stimmt es laut Text, dass Vorkenntnisse für eine Bewerbung zwingend erforderlich sind?',
      code: 'Die Freiwillige Feuerwehr Kleindorf sucht dringend neue Mitglieder. Durch Wegzüge und Altersgründe ist die Einsatzbereitschaft gefährdet. Interessierte ab 18 Jahren können sich beim Gerätewart oder online bewerben. Vorkenntnisse sind nicht erforderlich.',
      options: ['Richtig', 'Falsch'],
      correct: [1],
      explanation: 'Der Text sagt ausdrücklich: "Vorkenntnisse sind nicht erforderlich." Die Aussage ist daher falsch.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Ab welchem Alter kann man sich laut Text bewerben?',
      code: 'Die Freiwillige Feuerwehr Kleindorf sucht dringend neue Mitglieder. Durch Wegzüge und Altersgründe ist die Einsatzbereitschaft gefährdet. Interessierte ab 18 Jahren können sich beim Gerätewart oder online bewerben. Vorkenntnisse sind nicht erforderlich.',
      options: [
        'Ab 16 Jahren',
        'Ab 18 Jahren',
        'Ab 21 Jahren',
        'Ab 25 Jahren',
      ],
      correct: [1],
      explanation: 'Der Text nennt "ab 18 Jahren" als Mindestalter für Interessierte.',
      difficulty: 1,
    },
    // Text 12: Wasserverbrauch
    {
      type: 'mc',
      prompt: 'Was ist die Hauptaussage des Textes?',
      code: 'Der Trinkwasserverbrauch in der Region ist im vergangenen Sommer um 15 Prozent gestiegen. Die Wasserbehörde führt dies auf die anhaltende Hitze und die Bewässerung von Gärten zurück. Sie appelliert an die Bevölkerung, Wasser sparsam zu verwenden und auf die Rasenberegnung zu verzichten.',
      options: [
        'Der Trinkwasserverbrauch ist gesunken und die Lage ist entspannt.',
        'Der Wasserverbrauch ist gestiegen und die Behörde ruft zum Sparen auf.',
        'Die Wasserbehörde plant neue Wasserwerke zu bauen.',
        'Gartenbesitzer müssen Bußgelder für Bewässerung zahlen.',
      ],
      correct: [1],
      explanation: 'Der Text beschreibt einen Anstieg des Wasserverbrauchs und den Appell der Wasserbehörde zum sparsamen Umgang mit Wasser.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was nennt die Wasserbehörde als Ursache für den gestiegenen Verbrauch?',
      code: 'Der Trinkwasserverbrauch in der Region ist im vergangenen Sommer um 15 Prozent gestiegen. Die Wasserbehörde führt dies auf die anhaltende Hitze und die Bewässerung von Gärten zurück. Sie appelliert an die Bevölkerung, Wasser sparsam zu verwenden und auf die Rasenberegnung zu verzichten.',
      options: [
        'Bevölkerungswachstum und neue Industrien',
        'Anhaltende Hitze und Gartenbewässerung',
        'Undichte Leitungen und Wasserverluste',
        'Tourismus und öffentliche Veranstaltungen',
      ],
      correct: [1],
      explanation: 'Der Text nennt ausdrücklich "anhaltende Hitze und die Bewässerung von Gärten" als Ursachen.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welche Aussage steht NICHT im Text?',
      code: 'Der Trinkwasserverbrauch in der Region ist im vergangenen Sommer um 15 Prozent gestiegen. Die Wasserbehörde führt dies auf die anhaltende Hitze und die Bewässerung von Gärten zurück. Sie appelliert an die Bevölkerung, Wasser sparsam zu verwenden und auf die Rasenberegnung zu verzichten.',
      options: [
        'Der Verbrauch stieg um 15 Prozent.',
        'Die Behörde empfiehlt, auf Rasenberegnung zu verzichten.',
        'Gartenbesitzer werden mit Bußgeld bestraft.',
        'Die Hitze ist ein Grund für den höheren Verbrauch.',
      ],
      correct: [2],
      explanation: 'Bußgelder werden im Text nicht erwähnt. Die Behörde appelliert lediglich, ohne Sanktionen anzudrohen.',
      difficulty: 3,
    },
  ],
};

export default topic;
