import type { RawTopic } from '../types';

const topic: RawTopic = {
  slug: 'verwaltung-saarland',
  title: 'Öffentliche Verwaltung & Saarland',
  description: 'Grundlagen der öffentlichen Verwaltung und Wissen zum Saarland.',
  flashcards: [
    {
      front: 'Was ist die Hauptstadt des Saarlandes?',
      back: 'Saarbrücken ist die Landeshauptstadt des Saarlandes.',
    },
    {
      front: 'Wann trat das Saarland der Bundesrepublik Deutschland bei?',
      back: 'Das Saarland trat am 1. Januar 1957 der Bundesrepublik Deutschland bei ("Tag X").',
    },
    {
      front: 'An welche Länder und Staaten grenzt das Saarland?',
      back: 'Das Saarland grenzt an Rheinland-Pfalz (Deutschland), Frankreich (Region Grand Est / Lothringen) und Luxemburg.',
    },
    {
      front: 'Welchen Rang nimmt das Saarland unter den Flächenbundesländern ein?',
      back: 'Das Saarland ist das kleinste Flächenbundesland Deutschlands (die Stadtstaaten Berlin, Bremen und Hamburg nicht mitgerechnet).',
    },
    {
      front: 'Wie viele Einwohner hat das Saarland (ungefähr)?',
      back: 'Das Saarland hat etwa 1 Million Einwohner.',
    },
    {
      front: 'Wie ist die Kreisstruktur des Saarlandes aufgebaut?',
      back: 'Das Saarland gliedert sich in den Regionalverband Saarbrücken sowie fünf Landkreise: Merzig-Wadern, Neunkirchen, Saarlouis, Saarpfalz-Kreis und St. Wendel.',
    },
    {
      front: 'Wer ist Ministerpräsidentin des Saarlandes?',
      back: 'Anke Rehlinger (SPD) ist Ministerpräsidentin des Saarlandes.',
    },
    {
      front: 'Was ist die Frankreichstrategie des Saarlandes?',
      back: 'Die Frankreichstrategie ist ein bildungs- und wirtschaftspolitisches Programm des Saarlandes mit dem Ziel, Französisch zur zweiten Landessprache zu machen und die grenzüberschreitende Zusammenarbeit mit Frankreich zu stärken.',
    },
    {
      front: 'Welcher Fluss gibt dem Saarland seinen Namen?',
      back: 'Die Saar, ein Nebenfluss der Mosel, gibt dem Saarland seinen Namen.',
    },
    {
      front: 'Welche Industrien prägten das Saarland historisch?',
      back: 'Das Saarland war ein bedeutendes Kohle- und Stahlrevier. Bergbau und Stahlindustrie prägten die Region über Jahrzehnte, bevor ein tiefgreifender Strukturwandel einsetzte.',
    },
    {
      front: 'Was ist ein Verwaltungsakt nach § 35 VwVfG?',
      back: 'Ein Verwaltungsakt ist jede Verfügung, Entscheidung oder andere hoheitliche Maßnahme, die eine Behörde zur Regelung eines Einzelfalls auf dem Gebiet des öffentlichen Rechts trifft und die auf unmittelbare Rechtswirkung nach außen gerichtet ist.',
    },
    {
      front: 'Was bedeutet der Grundsatz der Gesetzmäßigkeit der Verwaltung?',
      back: 'Die Verwaltung darf nur handeln, wenn sie dazu gesetzlich ermächtigt ist (Vorbehalt des Gesetzes) und muss dabei geltendes Recht einhalten (Vorrang des Gesetzes).',
    },
    {
      front: 'Was versteht man unter dem Verhältnismäßigkeitsprinzip in der Verwaltung?',
      back: 'Staatliche Maßnahmen müssen geeignet, erforderlich und angemessen (verhältnismäßig im engeren Sinne) sein, um ein legitimes Ziel zu erreichen. Übermäßige Eingriffe sind unzulässig.',
    },
    {
      front: 'Was ist der Dienstweg?',
      back: 'Der Dienstweg bezeichnet den vorgeschriebenen Instanzenweg innerhalb einer Behörde oder Verwaltungshierarchie, über den dienstliche Vorgänge weitergeleitet werden müssen.',
    },
    {
      front: 'Was bedeutet Amtsverschwiegenheit?',
      back: 'Beamte und Beschäftigte im öffentlichen Dienst sind verpflichtet, über dienstliche Angelegenheiten Stillschweigen zu bewahren, die nicht zur Veröffentlichung bestimmt sind.',
    },
    {
      front: 'Welche vier Laufbahngruppen gibt es im deutschen öffentlichen Dienst?',
      back: 'Einfacher Dienst, mittlerer Dienst, gehobener Dienst und höherer Dienst.',
    },
    {
      front: 'Was unterscheidet Beamte von Tarifbeschäftigten im öffentlichen Dienst?',
      back: 'Beamte stehen in einem öffentlich-rechtlichen Dienst- und Treueverhältnis zum Staat, erhalten Bezüge und haben besonderen Kündigungsschutz. Tarifbeschäftigte haben einen privatrechtlichen Arbeitsvertrag und erhalten Entgelt nach Tarifvertrag (TVöD).',
    },
    {
      front: 'Wie ist der Behördenaufbau in Deutschland gegliedert?',
      back: 'Der Behördenaufbau folgt der föderalen Struktur: Bundesbehörden (z. B. Bundesministerien), Landesbehörden (z. B. Ministerien des Landes) und kommunale Behörden (z. B. Gemeindeverwaltungen, Bürgerbüros).',
    },
    {
      front: 'Was ist eine Ordnungsverfügung als Beispiel für einen Verwaltungsakt?',
      back: 'Eine Ordnungsverfügung ist ein belastender Verwaltungsakt, mit dem eine Behörde einem Bürger ein Gebot oder Verbot auferlegt, z. B. eine Abrissverfügung für ein baurechtswidriges Gebäude.',
    },
    {
      front: 'Was versteht man unter ordnungsgemäßer Aktenführung in der Verwaltung?',
      back: 'Akten müssen vollständig, wahrheitsgemäß, nachvollziehbar und geordnet geführt werden. Sie dokumentieren das Verwaltungshandeln und dienen der Nachvollziehbarkeit von Entscheidungen.',
    },
    {
      front: 'Welches Parlament hat das Saarland?',
      back: 'Das Saarland hat den Landtag des Saarlandes mit Sitz in Saarbrücken.',
    },
  ],
  questions: [
    {
      type: 'mc',
      prompt: 'Wer ist Ministerpräsidentin des Saarlandes?',
      options: [
        'Anke Rehlinger',
        'Annegret Kramp-Karrenbauer',
        'Malu Dreyer',
        'Julia Klöckner',
      ],
      correct: [0],
      explanation: 'Anke Rehlinger (SPD) ist Ministerpräsidentin des Saarlandes.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist die Hauptstadt des Saarlandes?',
      options: [
        'Neunkirchen',
        'Saarlouis',
        'Saarbrücken',
        'Merzig',
      ],
      correct: [2],
      explanation: 'Saarbrücken ist die Landeshauptstadt des Saarlandes und Sitz des Landtags sowie der Landesregierung.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Wann trat das Saarland der Bundesrepublik Deutschland bei?',
      options: [
        '23. Mai 1949',
        '3. Oktober 1990',
        '1. Januar 1957',
        '1. September 1955',
      ],
      correct: [2],
      explanation: 'Das Saarland trat am 1. Januar 1957 der Bundesrepublik Deutschland bei. Dieser Tag wird als "Tag X" bezeichnet.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'An welche Staaten grenzt das Saarland außer Deutschland?',
      options: [
        'Belgien und Luxemburg',
        'Frankreich und Belgien',
        'Frankreich und Luxemburg',
        'Schweiz und Frankreich',
      ],
      correct: [2],
      explanation: 'Das Saarland grenzt an Frankreich (Region Grand Est / Lothringen) und Luxemburg sowie innerhalb Deutschlands an Rheinland-Pfalz.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Wie viele Landkreise hat das Saarland (ohne Regionalverband Saarbrücken)?',
      options: [
        'Drei',
        'Vier',
        'Fünf',
        'Sechs',
      ],
      correct: [2],
      explanation: 'Das Saarland hat fünf Landkreise: Merzig-Wadern, Neunkirchen, Saarlouis, Saarpfalz-Kreis und St. Wendel. Dazu kommt der Regionalverband Saarbrücken.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welcher Fluss ist namensgebend für das Saarland?',
      options: [
        'Die Mosel',
        'Die Prims',
        'Die Blies',
        'Die Saar',
      ],
      correct: [3],
      explanation: 'Die Saar, ein linker Nebenfluss der Mosel, gibt dem Saarland seinen Namen.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welche historischen Industrien prägten das Saarland besonders?',
      options: [
        'Textil- und Chemieindustrie',
        'Kohle- und Stahlindustrie',
        'Automobilindustrie und Maschinenbau',
        'Landwirtschaft und Forstwirtschaft',
      ],
      correct: [1],
      explanation: 'Das Saarland war über Jahrzehnte ein wichtiges Kohle- und Stahlrevier. Der Strukturwandel nach dem Ende des Bergbaus ist bis heute spürbar.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Wer ist Minister für Inneres, Bauen und Sport im Saarland?',
      options: [
        'Torsten Lang',
        'Reinhold Jost',
        'Peter Strobel',
        'Klaus Bouillon',
      ],
      correct: [1],
      explanation: 'Reinhold Jost ist Minister für Inneres, Bauen und Sport des Saarlandes.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welches Ziel verfolgt die Frankreichstrategie des Saarlandes?',
      options: [
        'Die Einführung des Euro als einziges Zahlungsmittel',
        'Den Beitritt des Saarlandes zur französischen Republik',
        'Französisch als zweite Landessprache zu etablieren und die grenzüberschreitende Zusammenarbeit zu stärken',
        'Die Abschaffung von Grenzkontrollen zu Frankreich',
      ],
      correct: [2],
      explanation: 'Die Frankreichstrategie des Saarlandes zielt darauf ab, Französisch zur zweiten Landessprache zu machen und die grenzüberschreitende wirtschaftliche und kulturelle Zusammenarbeit mit Frankreich zu vertiefen.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welches ist das kleinste Flächenbundesland Deutschlands (Stadtstaaten ausgenommen)?',
      options: [
        'Schleswig-Holstein',
        'Thüringen',
        'Saarland',
        'Sachsen-Anhalt',
      ],
      correct: [2],
      explanation: 'Das Saarland ist mit etwa 2.570 km² das kleinste Flächenbundesland Deutschlands. Berücksichtigt man die Stadtstaaten Berlin, Hamburg und Bremen, liegt das Saarland jedoch nicht an letzter Stelle.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Wie viele Einwohner hat das Saarland ungefähr?',
      options: [
        'Etwa 500.000',
        'Etwa 1 Million',
        'Etwa 2 Millionen',
        'Etwa 3 Millionen',
      ],
      correct: [1],
      explanation: 'Das Saarland hat etwa 1 Million Einwohner und ist damit auch das einwohnerschwächste Flächenbundesland.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist ein Verwaltungsakt gemäß § 35 VwVfG?',
      options: [
        'Jede interne Dienstanweisung innerhalb einer Behörde',
        'Jede hoheitliche Maßnahme zur Regelung eines Einzelfalls mit unmittelbarer Rechtswirkung nach außen',
        'Ein Vertrag zwischen Bürger und Behörde',
        'Eine allgemeine Rechtsvorschrift mit Wirkung für alle Bürger',
      ],
      correct: [1],
      explanation: '§ 35 VwVfG definiert den Verwaltungsakt als Verfügung, Entscheidung oder andere hoheitliche Maßnahme, die eine Behörde zur Regelung eines Einzelfalls auf dem Gebiet des öffentlichen Rechts trifft und die auf unmittelbare Rechtswirkung nach außen gerichtet ist.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was besagt der Grundsatz des Vorbehalts des Gesetzes?',
      options: [
        'Gesetze dürfen nur vom Bundestag erlassen werden.',
        'Die Verwaltung darf nur handeln, wenn sie durch ein Gesetz dazu ermächtigt ist.',
        'Jeder Bürger hat das Recht, Gesetze einzusehen.',
        'Verwaltungsakte sind erst nach Bekanntgabe im Gesetzblatt wirksam.',
      ],
      correct: [1],
      explanation: 'Der Vorbehalt des Gesetzes als Teil der Gesetzmäßigkeit der Verwaltung bedeutet, dass die Verwaltung für belastende Eingriffe in Rechte der Bürger einer gesetzlichen Grundlage bedarf.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was beinhaltet der Verhältnismäßigkeitsgrundsatz der Verwaltung?',
      options: [
        'Die Verwaltung muss alle Bürger gleich behandeln.',
        'Staatliche Maßnahmen müssen geeignet, erforderlich und angemessen sein.',
        'Behörden dürfen nur in dringenden Fällen tätig werden.',
        'Verwaltungsakte müssen immer schriftlich ergehen.',
      ],
      correct: [1],
      explanation: 'Das Verhältnismäßigkeitsprinzip verlangt, dass staatliche Maßnahmen geeignet (tauglich zur Zweckerreichung), erforderlich (mildestes Mittel) und verhältnismäßig im engeren Sinne (angemessen) sind.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welche Laufbahngruppe setzt in der Regel ein abgeschlossenes Hochschulstudium voraus?',
      options: [
        'Einfacher Dienst',
        'Mittlerer Dienst',
        'Gehobener Dienst',
        'Höherer Dienst',
      ],
      correct: [3],
      explanation: 'Der höhere Dienst setzt in der Regel einen Masterabschluss oder ein gleichwertiges Hochschulstudium voraus (z. B. Volljurist, Diplom-Ökonom). Für den gehobenen Dienst genügt meist ein Bachelorabschluss oder ein FH-Diplom.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welcher Dienstgrad im öffentlichen Dienst erfordert typischerweise einen Bachelor- oder FH-Abschluss?',
      options: [
        'Einfacher Dienst',
        'Mittlerer Dienst',
        'Gehobener Dienst',
        'Höherer Dienst',
      ],
      correct: [2],
      explanation: 'Der gehobene Dienst setzt in der Regel einen Bachelor- oder FH-Diplomabschluss voraus. Für den höheren Dienst ist ein Masterabschluss erforderlich.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was versteht man unter dem "Dienstweg" in der öffentlichen Verwaltung?',
      options: [
        'Den physischen Weg zum Dienstgebäude',
        'Den vorgeschriebenen Instanzenweg, über den dienstliche Vorgänge weitergeleitet werden',
        'Den Beförderungsweg eines Beamten innerhalb seiner Laufbahn',
        'Die Fahrtzeit zwischen Wohnort und Dienststelle',
      ],
      correct: [1],
      explanation: 'Der Dienstweg bezeichnet den vorgeschriebenen hierarchischen Weg, auf dem Eingaben, Berichte und Anträge innerhalb der Verwaltung weitergeleitet werden müssen – von der untergeordneten zur übergeordneten Stelle.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Wozu sind Beamte durch die Amtsverschwiegenheit verpflichtet?',
      options: [
        'Alle dienstlichen Vorgänge zu veröffentlichen',
        'Über nicht zur Veröffentlichung bestimmte dienstliche Angelegenheiten Stillschweigen zu bewahren',
        'Nur ihrem Vorgesetzten über Dienstgeheimnisse zu berichten',
        'Dienstliche Informationen an die Presse weiterzugeben',
      ],
      correct: [1],
      explanation: 'Die Amtsverschwiegenheit verpflichtet Beamte, über Angelegenheiten, die ihnen im Dienst bekannt geworden sind und die nicht zur Veröffentlichung bestimmt sind, Stillschweigen zu bewahren – auch nach Beendigung des Dienstverhältnisses.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was unterscheidet einen Beamten von einem Tarifbeschäftigten im öffentlichen Dienst rechtlich grundlegend?',
      options: [
        'Beamte erhalten mehr Gehalt als Tarifbeschäftigte.',
        'Beamte stehen in einem öffentlich-rechtlichen Dienst- und Treueverhältnis; Tarifbeschäftigte haben einen privatrechtlichen Arbeitsvertrag.',
        'Tarifbeschäftigte haben eine höhere Jobsicherheit als Beamte.',
        'Beamte dürfen keine Gewerkschaft gründen, Tarifbeschäftigte schon.',
      ],
      correct: [1],
      explanation: 'Das Beamtenverhältnis ist ein öffentlich-rechtliches Dienst- und Treueverhältnis mit besonderen Pflichten (Verfassungstreue, Amtsverschwiegenheit) und Rechten (Alimentationsprinzip, besonderer Kündigungsschutz). Tarifbeschäftigte werden nach dem TVöD vergütet und haben ein privatrechtliches Arbeitsverhältnis.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Auf welcher Ebene ist das Bürgerbüro in Deutschland typischerweise angesiedelt?',
      options: [
        'Bundesebene',
        'Landesebene',
        'Kommunale Ebene (Gemeinde oder Stadt)',
        'Europäische Ebene',
      ],
      correct: [2],
      explanation: 'Bürgerbüros sind Einrichtungen der kommunalen Selbstverwaltung. Sie bieten Bürgerinnen und Bürgern vor Ort Verwaltungsdienstleistungen an, z. B. Anmeldung, Ausweisangelegenheiten oder Beurkundungen.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welcher Grundsatz verlangt, dass Verwaltungsakten eine klare gesetzliche Grundlage zugrunde liegt?',
      options: [
        'Verhältnismäßigkeitsprinzip',
        'Opportunitätsprinzip',
        'Gesetzmäßigkeit der Verwaltung',
        'Amtshilfe',
      ],
      correct: [2],
      explanation: 'Der Grundsatz der Gesetzmäßigkeit der Verwaltung (Art. 20 Abs. 3 GG) umfasst den Vorrang des Gesetzes (kein Handeln gegen Gesetze) und den Vorbehalt des Gesetzes (belastendes Handeln nur aufgrund gesetzlicher Ermächtigung).',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was ist ein begünstigender Verwaltungsakt?',
      options: [
        'Ein Verwaltungsakt, der einem Bürger eine Pflicht auferlegt',
        'Ein Verwaltungsakt, der ein Recht oder einen rechtlichen Vorteil gewährt',
        'Eine allgemeinverbindliche Rechtsvorschrift',
        'Eine interne Verwaltungsvorschrift ohne Außenwirkung',
      ],
      correct: [1],
      explanation: 'Ein begünstigender Verwaltungsakt (z. B. eine Baugenehmigung oder ein Bewilligungsbescheid) gewährt dem Adressaten ein Recht oder einen rechtlichen Vorteil. Er steht im Gegensatz zum belastenden Verwaltungsakt.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welche Voraussetzung gilt nach dem Dreigliederprinzip für die Verhältnismäßigkeit einer Maßnahme NICHT?',
      options: [
        'Die Maßnahme muss geeignet sein.',
        'Die Maßnahme muss erforderlich sein.',
        'Die Maßnahme muss einstimmig beschlossen werden.',
        'Die Maßnahme muss verhältnismäßig im engeren Sinne (angemessen) sein.',
      ],
      correct: [2],
      explanation: 'Das Verhältnismäßigkeitsprinzip prüft drei Stufen: Geeignetheit, Erforderlichkeit und Angemessenheit (Verhältnismäßigkeit im engeren Sinne). Ein einstimmiger Beschluss ist keine Voraussetzung.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Was ist der Staatssekretär im saarländischen Innenministerium?',
      options: [
        'Reinhold Jost',
        'Anke Rehlinger',
        'Torsten Lang',
        'Peter Strobel',
      ],
      correct: [2],
      explanation: 'Torsten Lang ist Staatssekretär im Ministerium für Inneres, Bauen und Sport des Saarlandes.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Wie wird der "höhere Dienst" in der deutschen Laufbahnordnung üblicherweise eingestuft?',
      options: [
        'Als niedrigste Laufbahngruppe',
        'Als zweite von vier Laufbahngruppen',
        'Als höchste der vier Laufbahngruppen',
        'Als Sondergruppe außerhalb der Laufbahnordnung',
      ],
      correct: [2],
      explanation: 'Der höhere Dienst ist die höchste der vier Laufbahngruppen (einfacher, mittlerer, gehobener, höherer Dienst) im deutschen öffentlichen Dienst. Er erfordert in der Regel ein abgeschlossenes Hochschulstudium (Master oder gleichwertig).',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welches Bundesland grenzt innerhalb Deutschlands an das Saarland?',
      options: [
        'Baden-Württemberg',
        'Hessen',
        'Bayern',
        'Rheinland-Pfalz',
      ],
      correct: [3],
      explanation: 'Das Saarland grenzt innerhalb Deutschlands ausschließlich an Rheinland-Pfalz. Im Übrigen grenzt es an Frankreich und Luxemburg.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welche Partei stellt die Ministerpräsidentin des Saarlandes?',
      options: [
        'CDU',
        'SPD',
        'Grüne',
        'FDP',
      ],
      correct: [1],
      explanation: 'Anke Rehlinger ist Mitglied der SPD und führt seit 2022 als Ministerpräsidentin die saarländische Landesregierung.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was regelt das Prinzip der Amtshilfe in der Verwaltung?',
      options: [
        'Beamte dürfen sich gegenseitig bei privaten Angelegenheiten unterstützen.',
        'Behörden sind verpflichtet, anderen Behörden auf Ersuchen Hilfe zu leisten.',
        'Bürger haben ein Recht auf kostenlose Rechtsberatung durch Behörden.',
        'Behörden dürfen Aufgaben an private Unternehmen delegieren.',
      ],
      correct: [1],
      explanation: 'Amtshilfe (§§ 4–8 VwVfG) verpflichtet jede Behörde, anderen Behörden auf Ersuchen Hilfe zu leisten, soweit dies zur Erfüllung ihrer Aufgaben notwendig ist und keine Verweigerungsgründe vorliegen.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Was ist ein wesentliches Merkmal ordnungsgemäßer Aktenführung in der öffentlichen Verwaltung?',
      options: [
        'Akten dürfen nur elektronisch geführt werden.',
        'Akten müssen vollständig, nachvollziehbar und wahrheitsgemäß geführt werden.',
        'Akten müssen nach spätestens einem Jahr vernichtet werden.',
        'Akten sind nur für interne Zwecke und dürfen Bürgern nie offengelegt werden.',
      ],
      correct: [1],
      explanation: 'Eine ordnungsgemäße Aktenführung verlangt Vollständigkeit, Nachvollziehbarkeit, Wahrheit und Aktualität. Akten dokumentieren das Verwaltungshandeln und bilden die Grundlage für Kontrolle und Rechenschaftspflicht.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Wie bezeichnet man den Grundsatz, dass alle staatlichen Organe an die Grundrechte gebunden sind?',
      options: [
        'Rechtsstaatsprinzip',
        'Grundrechtsbindung der öffentlichen Gewalt',
        'Gesetzmäßigkeit der Verwaltung',
        'Demokratieprinzip',
      ],
      correct: [1],
      explanation: 'Die Grundrechtsbindung der öffentlichen Gewalt (Art. 1 Abs. 3 GG) bedeutet, dass Legislative, Exekutive und Judikative an die Grundrechte als unmittelbar geltendes Recht gebunden sind.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Welches Organ des Saarlandes ist das Landesparlament?',
      options: [
        'Saarländischer Senat',
        'Landtag des Saarlandes',
        'Saarländischer Stadtrat',
        'Saarländischer Landschaftsverband',
      ],
      correct: [1],
      explanation: 'Der Landtag des Saarlandes ist das demokratisch gewählte Landesparlament mit Sitz in Saarbrücken.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welchem übergeordneten Verwaltungsprinzip widerspricht ein Verwaltungshandeln, das eine unverhältnismäßig hohe Geldbuße für eine Bagatellordnungswidrigkeit verhängt?',
      options: [
        'Amtsverschwiegenheit',
        'Dienstweg',
        'Verhältnismäßigkeitsgrundsatz',
        'Gleichbehandlungsgrundsatz',
      ],
      correct: [2],
      explanation: 'Eine übermäßig hohe Sanktion für eine geringe Pflichtverletzung verstößt gegen den Verhältnismäßigkeitsgrundsatz, der verlangt, dass staatliche Maßnahmen angemessen (verhältnismäßig im engeren Sinne) sein müssen.',
      difficulty: 3,
    },
    {
      type: 'truefalse',
      prompt: 'Das Saarland grenzt an die Schweiz.',
      options: ['Richtig', 'Falsch'],
      correct: [1],
      explanation: 'Falsch. Das Saarland grenzt an Frankreich (Grand Est / Lothringen), Luxemburg und innerhalb Deutschlands an Rheinland-Pfalz. An die Schweiz grenzt es nicht.',
      difficulty: 1,
    },
    {
      type: 'truefalse',
      prompt: 'Der "Tag X" bezeichnet den Beitritt des Saarlandes zur Bundesrepublik Deutschland am 1. Januar 1957.',
      options: ['Richtig', 'Falsch'],
      correct: [0],
      explanation: 'Richtig. Am 1. Januar 1957 trat das Saarland als zehntes Bundesland der Bundesrepublik Deutschland bei. Dieser Tag wird als "Tag X" bezeichnet.',
      difficulty: 2,
    },
    {
      type: 'truefalse',
      prompt: 'Ein Verwaltungsakt entfaltet grundsätzlich keine Rechtswirkung gegenüber dem Bürger.',
      options: ['Richtig', 'Falsch'],
      correct: [1],
      explanation: 'Falsch. Ein zentrales Merkmal des Verwaltungsakts nach § 35 VwVfG ist gerade die unmittelbare Rechtswirkung nach außen, also gegenüber dem Bürger.',
      difficulty: 2,
    },
    {
      type: 'fill',
      prompt: 'Das Saarland gliedert sich in den Regionalverband Saarbrücken und ___ Landkreise.',
      options: ['fünf', 'vier', 'sechs', 'drei'],
      correct: [0],
      explanation: 'Das Saarland hat neben dem Regionalverband Saarbrücken genau fünf Landkreise: Merzig-Wadern, Neunkirchen, Saarlouis, Saarpfalz-Kreis und St. Wendel.',
      difficulty: 2,
    },
  ],
};

export default topic;
