import type { RawTopic } from '../types';

const topic: RawTopic = {
  slug: 'weltwissen',
  title: 'Welt- & Kulturwissen',
  description: 'Religionen, Kunst, Wissenschaft und Sport.',
  flashcards: [
    {
      front: 'Welche sind die fünf Weltreligionen?',
      back: 'Christentum, Islam, Judentum, Hinduismus und Buddhismus.',
    },
    {
      front: 'Wie heißt die heilige Schrift des Christentums?',
      back: 'Die Bibel (Altes und Neues Testament).',
    },
    {
      front: 'Wie heißt die heilige Schrift des Islam?',
      back: 'Der Koran (arabisch: al-Quran).',
    },
    {
      front: 'Wie heißt die heilige Schrift des Judentums?',
      back: 'Die Tora (die fünf Bücher Mose) sowie der Talmud.',
    },
    {
      front: 'Wer malte die Mona Lisa?',
      back: 'Leonardo da Vinci (entstanden ca. 1503–1519).',
    },
    {
      front: 'Wer bemalte die Sixtinische Kapelle in Rom?',
      back: 'Michelangelo Buonarroti (Deckengemälde 1508–1512).',
    },
    {
      front: 'Welche Theorie entwickelte Albert Einstein?',
      back: 'Die Relativitätstheorie (Spezielle 1905, Allgemeine 1915).',
    },
    {
      front: 'Wofür ist Isaac Newton bekannt?',
      back: 'Für das Gravitationsgesetz und die drei Newtonschen Axiome.',
    },
    {
      front: 'Welches Werk verfasste Johann Wolfgang von Goethe?',
      back: '"Faust" – das bedeutendste Werk der deutschen Literatur.',
    },
    {
      front: 'Wer erfand den Buchdruck mit beweglichen Lettern?',
      back: 'Johannes Gutenberg (um 1450 in Mainz).',
    },
    {
      front: 'Wie viele Spieler stehen bei einem Fußballspiel pro Mannschaft auf dem Platz?',
      back: '11 Spieler pro Mannschaft (insgesamt 22 Feldspieler).',
    },
    {
      front: 'In welchem Rhythmus finden die Olympischen Sommerspiele statt?',
      back: 'Alle vier Jahre.',
    },
    {
      front: 'In welchen Kategorien wird der Nobelpreis vergeben?',
      back: 'Physik, Chemie, Medizin/Physiologie, Literatur, Frieden und Wirtschaftswissenschaften.',
    },
    {
      front: 'Womit beschäftigte sich Charles Darwin?',
      back: 'Mit der Evolutionstheorie – natürliche Selektion als Mechanismus der Artenentwicklung.',
    },
    {
      front: 'Wofür erhielt Marie Curie den Nobelpreis?',
      back: 'Für ihre Forschungen zur Radioaktivität – zweifache Nobelpreisträgerin (Physik 1903, Chemie 1911).',
    },
    {
      front: 'Welche Komposition schrieb Ludwig van Beethoven trotz seiner Taubheit?',
      back: 'Die 9. Sinfonie mit der "Ode an die Freude" (uraufgeführt 1824).',
    },
    {
      front: 'Wer schrieb "Die Räuber" und "Wilhelm Tell"?',
      back: 'Friedrich Schiller.',
    },
    {
      front: 'Was ist das zentrale Konzept des Buddhismus bezüglich des Leidens?',
      back: 'Die Vier Edlen Wahrheiten: Leiden existiert, hat Ursachen, kann überwunden werden – durch den Edlen Achtfachen Pfad.',
    },
    {
      front: 'Wie heißt der heilige Text des Hinduismus?',
      back: 'Die Veden (älteste Schriften) sowie die Upanishaden, Mahabharata und Ramayana.',
    },
    {
      front: 'Wer komponierte das "Wohltemperierte Klavier"?',
      back: 'Johann Sebastian Bach.',
    },
  ],
  questions: [
    {
      type: 'mc',
      prompt: 'Wer malte die Mona Lisa?',
      options: ['Leonardo da Vinci', 'Michelangelo', 'Raffael', 'Pablo Picasso'],
      correct: [0],
      explanation: 'Die Mona Lisa wurde von Leonardo da Vinci gemalt (ca. 1503–1519).',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Wer bemalte die Decke der Sixtinischen Kapelle?',
      options: ['Leonardo da Vinci', 'Raffael', 'Caravaggio', 'Michelangelo'],
      correct: [3],
      explanation: 'Michelangelo schuf die Deckenfresken der Sixtinischen Kapelle zwischen 1508 und 1512.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welche Theorie ist Albert Einstein zuzuschreiben?',
      options: ['Quantenmechanik', 'Relativitätstheorie', 'Evolutionstheorie', 'Gravitationsgesetz'],
      correct: [1],
      explanation: 'Einstein entwickelte die Spezielle (1905) und Allgemeine Relativitätstheorie (1915).',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Wie viele Spieler stehen bei einem offiziellen Fußballspiel pro Mannschaft auf dem Feld?',
      options: ['9', '10', '11', '12'],
      correct: [2],
      explanation: 'Gemäß den FIFA-Regeln spielen pro Mannschaft genau 11 Spieler auf dem Feld.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'In welchem zeitlichen Abstand finden die Olympischen Sommerspiele statt?',
      options: ['Alle zwei Jahre', 'Alle drei Jahre', 'Alle vier Jahre', 'Alle fünf Jahre'],
      correct: [2],
      explanation: 'Die Olympischen Sommerspiele finden seit 1896 alle vier Jahre statt.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Wer erfand den Buchdruck mit beweglichen Lettern?',
      options: ['Martin Luther', 'Johannes Gutenberg', 'Leonardo da Vinci', 'Galileo Galilei'],
      correct: [1],
      explanation: 'Johannes Gutenberg erfand den Buchdruck mit beweglichen Metalllettern um 1450 in Mainz.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welches Werk stammt von Johann Wolfgang von Goethe?',
      options: ['Die Räuber', 'Faust', 'Nathan der Weise', 'Die Leiden des jungen Werthers II'],
      correct: [1],
      explanation: '"Faust" ist Goethes bedeutendstes Werk. "Die Räuber" stammt von Schiller, "Nathan der Weise" von Lessing.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Wofür erhielt Marie Curie ihren ersten Nobelpreis (1903)?',
      options: ['Chemie', 'Medizin', 'Physik', 'Frieden'],
      correct: [2],
      explanation: 'Marie Curie erhielt 1903 den Nobelpreis für Physik für ihre Erforschung der Radioaktivität. 1911 folgte der Nobelpreis für Chemie.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welche Evolutionstheorie entwickelte Charles Darwin?',
      options: [
        'Theorie der spontanen Entstehung',
        'Natürliche Selektion als Mechanismus der Artenentwicklung',
        'Vererbung erworbener Eigenschaften',
        'Kreationismus',
      ],
      correct: [1],
      explanation: 'Darwin beschrieb in "Über die Entstehung der Arten" (1859) die natürliche Selektion als Triebkraft der Evolution.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'In welchen Kategorien wird der Nobelpreis NICHT vergeben?',
      options: ['Physik', 'Mathematik', 'Chemie', 'Medizin'],
      correct: [1],
      explanation: 'Es gibt keinen Nobelpreis für Mathematik. Die Kategorien sind: Physik, Chemie, Medizin, Literatur, Frieden und Wirtschaftswissenschaften.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welche heilige Schrift gehört zum Islam?',
      options: ['Die Bibel', 'Der Talmud', 'Der Koran', 'Die Veden'],
      correct: [2],
      explanation: 'Der Koran ist die heilige Schrift des Islam, offenbart an den Propheten Mohammed.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist die heilige Schrift des Judentums?',
      options: ['Der Koran', 'Die Bibel', 'Die Tora', 'Das Neue Testament'],
      correct: [2],
      explanation: 'Die Tora (die fünf Bücher Mose) bildet den Kern der jüdischen heiligen Schriften.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welche der folgenden Religionen gehört NICHT zu den fünf Weltreligionen?',
      options: ['Hinduismus', 'Buddhismus', 'Zoroastrismus', 'Islam'],
      correct: [2],
      explanation: 'Der Zoroastrismus ist keine der fünf Weltreligionen. Diese sind: Christentum, Islam, Judentum, Hinduismus, Buddhismus.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welches Werk komponierte Ludwig van Beethoven trotz vollständiger Taubheit?',
      options: ['5. Sinfonie', '6. Sinfonie "Pastorale"', '9. Sinfonie', 'Mondscheinsonate'],
      correct: [2],
      explanation: 'Beethoven vollendete seine 9. Sinfonie mit der "Ode an die Freude" 1824 – zu einem Zeitpunkt, als er bereits vollständig taub war.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Wer schrieb das Drama "Die Räuber"?',
      options: ['Goethe', 'Lessing', 'Schiller', 'Kleist'],
      correct: [2],
      explanation: '"Die Räuber" (1781) ist ein Sturm-und-Drang-Drama von Friedrich Schiller.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Wer formulierte das Gravitationsgesetz?',
      options: ['Albert Einstein', 'Galileo Galilei', 'Isaac Newton', 'Nikola Tesla'],
      correct: [2],
      explanation: 'Isaac Newton formulierte das allgemeine Gravitationsgesetz 1687 in seinem Werk "Principia Mathematica".',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Wo fanden die ersten modernen Olympischen Spiele 1896 statt?',
      options: ['Paris', 'London', 'Athen', 'Rom'],
      correct: [2],
      explanation: 'Die ersten modernen Olympischen Spiele fanden 1896 in Athen, Griechenland statt.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welcher Komponist schrieb das "Wohltemperierte Klavier"?',
      options: ['Wolfgang Amadeus Mozart', 'Ludwig van Beethoven', 'Franz Schubert', 'Johann Sebastian Bach'],
      correct: [3],
      explanation: 'Das "Wohltemperierte Klavier" ist eine Sammlung von Präludien und Fugen, komponiert von Johann Sebastian Bach.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was beschreiben die "Vier Edlen Wahrheiten" im Buddhismus?',
      options: [
        'Die vier Hauptgötter des Buddhismus',
        'Das Wesen des Leidens und den Weg zu seiner Überwindung',
        'Die vier heiligen Orte des Buddhismus',
        'Die vier Lebensabschnitte eines Mönchs',
      ],
      correct: [1],
      explanation: 'Die Vier Edlen Wahrheiten beschreiben: die Existenz von Leiden, seine Ursachen, die Möglichkeit seiner Überwindung und den Weg dazu (Achtfacher Pfad).',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Wie oft findet die FIFA Fußball-Weltmeisterschaft statt?',
      options: ['Alle zwei Jahre', 'Alle drei Jahre', 'Alle vier Jahre', 'Alle sechs Jahre'],
      correct: [2],
      explanation: 'Die FIFA-Fußball-Weltmeisterschaft findet alle vier Jahre statt (seit 1930).',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welches ist das bedeutendste literarische Werk der deutschen Klassik?',
      options: ['Goethes "Faust"', 'Schillers "Wallenstein"', 'Lessings "Emilia Galotti"', 'Kleists "Penthesilea"'],
      correct: [0],
      explanation: 'Goethes "Faust" gilt als das bedeutendste Werk der deutschen Literatur und als ein Höhepunkt der Weltliteratur.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Wo ist der Hauptsitz des Nobelpreiskomitees?',
      options: ['Kopenhagen', 'Oslo und Stockholm', 'Genf', 'Wien'],
      correct: [1],
      explanation: 'Die meisten Nobelpreise werden in Stockholm vergeben; der Friedensnobelpreis wird vom Norwegischen Nobelkomitee in Oslo vergeben.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Was ist ein zentrales Merkmal des Hinduismus?',
      options: [
        'Monotheismus mit dem einzigen Gott Allah',
        'Glaube an Karma und Reinkarnation',
        'Ablehnung jeglicher Götterverehrung',
        'Strenger Monotheismus ohne heilige Bilder',
      ],
      correct: [1],
      explanation: 'Der Hinduismus ist geprägt durch den Glauben an Karma (Taten und ihre Konsequenzen) und Reinkarnation (Wiedergeburt).',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welches Gemälde zeigt die Erschaffung Adams?',
      options: [
        'Die Schule von Athen (Raffael)',
        'Das letzte Abendmahl (Leonardo da Vinci)',
        'Die Erschaffung Adams (Decke der Sixtinischen Kapelle, Michelangelo)',
        'Der Garten der Lüste (Hieronymus Bosch)',
      ],
      correct: [2],
      explanation: 'Die Erschaffung Adams ist ein Teil von Michelangelos Deckenfresko in der Sixtinischen Kapelle und zeigt Gott, der Adam das Leben einhaucht.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Wer verfasste die "Zauberflöte"?',
      options: ['Ludwig van Beethoven', 'Franz Schubert', 'Wolfgang Amadeus Mozart', 'Joseph Haydn'],
      correct: [2],
      explanation: 'Die Zauberflöte ist eine Oper von Wolfgang Amadeus Mozart (KV 620), uraufgeführt 1791.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welche Aussage zur Relativitätstheorie ist korrekt?',
      options: [
        'Sie wurde von Isaac Newton entwickelt',
        'E = mc² beschreibt die Äquivalenz von Masse und Energie',
        'Sie widerlegt die Existenz der Schwerkraft',
        'Sie gilt nur für langsam bewegte Objekte',
      ],
      correct: [1],
      explanation: 'Einsteins berühmte Formel E = mc² besagt, dass Masse und Energie äquivalent sind (E = Energie, m = Masse, c = Lichtgeschwindigkeit).',
      difficulty: 3,
    },
    {
      type: 'truefalse',
      prompt: 'Der Islam ist die zweitgrößte Weltreligion nach Anzahl der Gläubigen.',
      options: ['Wahr', 'Falsch'],
      correct: [0],
      explanation: 'Korrekt. Das Christentum ist mit ca. 2,4 Milliarden Gläubigen die größte Weltreligion, gefolgt vom Islam mit ca. 1,9 Milliarden.',
      difficulty: 2,
    },
    {
      type: 'truefalse',
      prompt: 'Johann Sebastian Bach wurde nach Ludwig van Beethoven geboren.',
      options: ['Wahr', 'Falsch'],
      correct: [1],
      explanation: 'Falsch. Bach (1685–1750) lebte vor Beethoven (1770–1827). Bach gehört dem Barock an, Beethoven der Klassik und Frühromantik.',
      difficulty: 2,
    },
    {
      type: 'truefalse',
      prompt: 'Marie Curie war die erste Frau, die einen Nobelpreis erhielt.',
      options: ['Wahr', 'Falsch'],
      correct: [0],
      explanation: 'Korrekt. Marie Curie erhielt 1903 als erste Frau überhaupt einen Nobelpreis (Physik). Sie ist auch die einzige Person, die in zwei verschiedenen Naturwissenschaften den Nobelpreis erhielt.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welcher Wissenschaftler begründete die moderne Genetik durch Experimente mit Erbsen?',
      options: ['Charles Darwin', 'Louis Pasteur', 'Gregor Mendel', 'Robert Koch'],
      correct: [2],
      explanation: 'Gregor Mendel entdeckte durch Kreuzungsexperimente mit Erbsen die Grundgesetze der Vererbung (Mendelsche Gesetze, 1866).',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welcher Maler ist bekannt für das Gemälde "Sternennacht"?',
      options: ['Paul Gauguin', 'Vincent van Gogh', 'Claude Monet', 'Edvard Munch'],
      correct: [1],
      explanation: '"Die Sternennacht" (1889) ist eines der bekanntesten Gemälde von Vincent van Gogh, gemalt während seines Aufenthalts in der psychiatrischen Anstalt Saint-Paul-de-Mausole.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welche Stadt gilt als Geburtsort der Olympischen Spiele der Antike?',
      options: ['Athen', 'Sparta', 'Olympia', 'Korinth'],
      correct: [2],
      explanation: 'Die antiken Olympischen Spiele fanden in Olympia (Peloponnes) statt und wurden zu Ehren des Gottes Zeus veranstaltet (erste überlieferte Spiele 776 v. Chr.).',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welcher Komponist schrieb die Oper "Don Giovanni"?',
      options: ['Ludwig van Beethoven', 'Richard Wagner', 'Wolfgang Amadeus Mozart', 'Giuseppe Verdi'],
      correct: [2],
      explanation: '"Don Giovanni" (KV 527) ist eine Oper von Wolfgang Amadeus Mozart, uraufgeführt 1787 in Prag.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet der Begriff "Nirvana" im Buddhismus?',
      options: [
        'Ein Paradies voller Freuden',
        'Das Erlöschen von Begehren und Leiden, Zustand der Befreiung',
        'Die Wiedergeburt in höherer Form',
        'Ein heiliger Berg in Indien',
      ],
      correct: [1],
      explanation: 'Nirvana bezeichnet im Buddhismus den Zustand der vollständigen Erleuchtung und Befreiung vom Leidenszyklus (Samsara) durch das Erlöschen aller Begierden.',
      difficulty: 3,
    },
  ],
};

export default topic;
