import type { RawTopic } from '../types';

const topic: RawTopic = {
  slug: 'wirtschaft',
  title: 'Wirtschaft',
  description: 'Ökonomisches Prinzip, Marktformen, Steuern, Börse, Inflation.',
  flashcards: [
    {
      front: 'Was besagt das ökonomische Minimalprinzip?',
      back: 'Ein bestimmtes Ziel soll mit möglichst geringem Mitteleinsatz (Aufwand) erreicht werden.',
    },
    {
      front: 'Was besagt das ökonomische Maximalprinzip?',
      back: 'Mit einem gegebenen (festen) Mitteleinsatz soll ein möglichst großes Ergebnis erzielt werden.',
    },
    {
      front: 'Was ist ein Polypol?',
      back: 'Eine Marktform mit vielen Anbietern und vielen Nachfragern; kein Einzelner hat Marktmacht (z. B. Wochenmarkt).',
    },
    {
      front: 'Was ist ein Oligopol?',
      back: 'Eine Marktform mit wenigen Anbietern und vielen Nachfragern; die Anbieter können den Markt beeinflussen (z. B. Automobilindustrie).',
    },
    {
      front: 'Was ist ein Monopol?',
      back: 'Eine Marktform mit nur einem Anbieter und vielen Nachfragern; der Monopolist bestimmt Preis und Menge (z. B. früher Deutsche Bahn im Fernverkehr).',
    },
    {
      front: 'Was ist Inflation?',
      back: 'Ein anhaltender Anstieg des allgemeinen Preisniveaus; die Kaufkraft des Geldes sinkt.',
    },
    {
      front: 'Was ist Deflation?',
      back: 'Ein anhaltender Rückgang des allgemeinen Preisniveaus; die Kaufkraft des Geldes steigt, Konsum und Investitionen werden aber oft aufgeschoben.',
    },
    {
      front: 'Welches Inflationsziel verfolgt die Europäische Zentralbank (EZB)?',
      back: 'Die EZB strebt mittelfristig eine Inflationsrate von rund 2 % im Euroraum an.',
    },
    {
      front: 'Was ist das Bruttoinlandsprodukt (BIP)?',
      back: 'Der Gesamtwert aller Güter und Dienstleistungen, die innerhalb eines Landes in einem Jahr produziert werden; Maßstab für die Wirtschaftsleistung.',
    },
    {
      front: 'Was unterscheidet direkte von indirekten Steuern?',
      back: 'Direkte Steuern treffen Steuerschuldner und Steuerträger direkt (z. B. Einkommensteuer). Indirekte Steuern werden über den Preis von Waren weitergegeben (z. B. Umsatzsteuer).',
    },
    {
      front: 'Wie hoch ist der allgemeine Umsatzsteuersatz in Deutschland?',
      back: '19 %; der ermäßigte Satz beträgt 7 % (gilt u. a. für Lebensmittel, Bücher, ÖPNV).',
    },
    {
      front: 'Was ist die Lohnsteuer?',
      back: 'Eine Erhebungsform der Einkommensteuer für Arbeitnehmer; sie wird direkt vom Arbeitgeber an das Finanzamt abgeführt.',
    },
    {
      front: 'Was bedeutet progressive Besteuerung?',
      back: 'Mit steigendem Einkommen steigt auch der prozentuale Steuersatz; Geringverdiener zahlen anteilig weniger Steuern als Besserverdienende.',
    },
    {
      front: 'Was ist eine Aktie?',
      back: 'Ein Wertpapier, das einen Anteil am Eigenkapital (und damit am Unternehmen) verbrieft; Aktionäre haben Stimmrechte und Anspruch auf Dividende.',
    },
    {
      front: 'Was ist der DAX?',
      back: 'Der Deutsche Aktienindex; er umfasst die 40 größten und umsatzstärksten deutschen Aktiengesellschaften und gilt als wichtigster Leitindex für den deutschen Aktienmarkt.',
    },
    {
      front: 'Wer gilt als Vater der sozialen Marktwirtschaft in Deutschland?',
      back: 'Ludwig Erhard; er setzte als Wirtschaftsminister die soziale Marktwirtschaft in der Bundesrepublik Deutschland durch.',
    },
    {
      front: 'Was kennzeichnet die soziale Marktwirtschaft?',
      back: 'Sie verbindet freie Marktwirtschaft mit staatlichen Maßnahmen zum Sozialausgleich (z. B. Sozialversicherungen, Wettbewerbsregeln, Verbraucherschutz).',
    },
    {
      front: 'Was ist der Konjunkturzyklus?',
      back: 'Die regelmäßig wiederkehrenden Schwankungen der Wirtschaftsleistung in den Phasen: Aufschwung (Expansion), Hochkonjunktur (Boom), Abschwung (Rezession), Tiefstand (Depression).',
    },
    {
      front: 'Was ist ein Nachfrageüberhang?',
      back: 'Situation, in der die Nachfrage das Angebot übersteigt; dies führt in der Regel zu steigenden Preisen.',
    },
    {
      front: 'Was ist ein Angebotsüberhang?',
      back: 'Situation, in der das Angebot die Nachfrage übersteigt; dies führt in der Regel zu sinkenden Preisen.',
    },
  ],
  questions: [
    {
      type: 'mc',
      prompt: 'Was beschreibt eine Inflation?',
      options: [
        'anhaltender Anstieg des allgemeinen Preisniveaus',
        'anhaltender Rückgang der Preise',
        'gleichbleibende Preise',
        'steigende Löhne bei sinkenden Preisen',
      ],
      correct: [0],
      explanation: 'Inflation = allgemeiner, anhaltender Anstieg des Preisniveaus; Geld verliert an Wert.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welche Marktform liegt vor, wenn es viele Anbieter und viele Nachfrager gibt?',
      options: ['Monopol', 'Oligopol', 'Polypol', 'Monopson'],
      correct: [2],
      explanation: 'Beim Polypol stehen viele Anbieter vielen Nachfragern gegenüber; kein Einzelner hat nennenswerte Marktmacht.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was gilt für das ökonomische Minimalprinzip?',
      options: [
        'Mit maximalem Aufwand ein maximales Ergebnis erzielen.',
        'Ein vorgegebenes Ziel mit geringstmöglichem Aufwand erreichen.',
        'Den Aufwand beliebig variieren, um das Ergebnis zu maximieren.',
        'Das Ergebnis minimieren, um den Aufwand zu senken.',
      ],
      correct: [1],
      explanation: 'Minimalprinzip: festes Ziel, minimaler Mitteleinsatz.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Wie viele Unternehmen sind im DAX gelistet?',
      options: ['20', '30', '40', '50'],
      correct: [2],
      explanation: 'Seit September 2021 umfasst der DAX 40 Unternehmen (zuvor 30).',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Wie hoch ist der allgemeine Umsatzsteuersatz in Deutschland?',
      options: ['7 %', '16 %', '19 %', '21 %'],
      correct: [2],
      explanation: 'Der Regelsteuersatz der Umsatzsteuer beträgt 19 %; der ermäßigte Satz liegt bei 7 %.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welcher Steuersatz gilt in Deutschland für Lebensmittel (Umsatzsteuer)?',
      options: ['19 %', '7 %', '5 %', '10 %'],
      correct: [1],
      explanation: 'Grundnahrungsmittel unterliegen dem ermäßigten Umsatzsteuersatz von 7 %.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist eine Aktie?',
      options: [
        'Ein Schuldschein, den ein Unternehmen bei einer Bank aufnimmt.',
        'Ein staatlich garantiertes Sparbuch.',
        'Ein Wertpapier, das einen Anteil am Eigenkapital eines Unternehmens verbrieft.',
        'Ein Vertrag über eine Versicherungsleistung.',
      ],
      correct: [2],
      explanation: 'Aktionäre sind Miteigentümer des Unternehmens und haben Anspruch auf Dividende und Stimmrecht.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Wer gilt als "Vater der sozialen Marktwirtschaft" in Deutschland?',
      options: ['Konrad Adenauer', 'Ludwig Erhard', 'Walter Eucken', 'Helmut Schmidt'],
      correct: [1],
      explanation: 'Ludwig Erhard (Wirtschaftsminister ab 1949, später Bundeskanzler) prägte und verwirklichte die soziale Marktwirtschaft in der Bundesrepublik.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welches Inflationsziel verfolgt die Europäische Zentralbank (EZB) mittelfristig?',
      options: ['0 %', '1 %', '2 %', '5 %'],
      correct: [2],
      explanation: 'Die EZB strebt eine Inflationsrate von rund 2 % im Euroraum an, um Preisstabilität zu gewährleisten.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was versteht man unter dem BIP (Bruttoinlandsprodukt)?',
      options: [
        'Die Summe aller Steuereinnahmen eines Staates in einem Jahr.',
        'Den Gesamtwert aller im Inland produzierten Güter und Dienstleistungen in einem Jahr.',
        'Das Vermögen aller Bürger eines Landes.',
        'Die gesamten Staatsausgaben eines Jahres.',
      ],
      correct: [1],
      explanation: 'Das BIP misst die wirtschaftliche Leistungsfähigkeit eines Landes innerhalb eines bestimmten Zeitraums.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist ein Oligopol?',
      options: [
        'Viele Anbieter und viele Nachfrager.',
        'Wenige Anbieter und viele Nachfrager.',
        'Ein einziger Anbieter und viele Nachfrager.',
        'Ein einziger Nachfrager und viele Anbieter.',
      ],
      correct: [1],
      explanation: 'Im Oligopol dominieren wenige Anbieter den Markt (z. B. Mineralölwirtschaft, Mobilfunk).',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welche Steuer ist ein typisches Beispiel für eine direkte Steuer?',
      options: ['Umsatzsteuer', 'Energiesteuer', 'Einkommensteuer', 'Tabaksteuer'],
      correct: [2],
      explanation: 'Bei der Einkommensteuer fallen Steuerschuldner und Steuerträger zusammen; sie ist daher eine direkte Steuer.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet progressive Besteuerung?',
      options: [
        'Alle zahlen denselben absoluten Steuerbetrag.',
        'Mit steigendem Einkommen steigt auch der Steuersatz.',
        'Reichere zahlen prozentual weniger Steuern.',
        'Der Steuersatz sinkt mit steigendem Einkommen.',
      ],
      correct: [1],
      explanation: 'Progressive Steuern belasten höhere Einkommen prozentual stärker; dies soll soziale Gerechtigkeit fördern.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'In welcher Phase des Konjunkturzyklus ist die Wirtschaftsleistung am höchsten?',
      options: ['Depression', 'Aufschwung', 'Hochkonjunktur (Boom)', 'Rezession'],
      correct: [2],
      explanation: 'In der Hochkonjunktur (Boom) ist die Produktion auf dem Höhepunkt; Beschäftigung und Preise steigen.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was passiert bei einem Nachfrageüberhang am Markt typischerweise mit dem Preis?',
      options: [
        'Der Preis sinkt, weil die Anbieter mehr verkaufen wollen.',
        'Der Preis steigt, weil mehr gekauft werden will als verfügbar ist.',
        'Der Preis bleibt konstant.',
        'Der Preis wird staatlich reguliert.',
      ],
      correct: [1],
      explanation: 'Übersteigt die Nachfrage das Angebot, konkurrieren Käufer um knappe Güter, was die Preise treibt.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was versteht man unter dem Maximalprinzip in der Wirtschaft?',
      options: [
        'Den Aufwand so weit wie möglich erhöhen.',
        'Mit einem gegebenen Mitteleinsatz ein möglichst großes Ergebnis erzielen.',
        'Ergebnis und Aufwand gleichzeitig maximieren.',
        'Das Ergebnis konstant halten und den Aufwand minimieren.',
      ],
      correct: [1],
      explanation: 'Maximalprinzip: fester Mitteleinsatz, maximales Ergebnis – das Gegenstück zum Minimalprinzip.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welche Marktform beschreibt einen Markt mit nur einem Anbieter?',
      options: ['Polypol', 'Oligopol', 'Monopson', 'Monopol'],
      correct: [3],
      explanation: 'Im Monopol gibt es nur einen Anbieter; er kann Preis und Menge weitgehend selbst bestimmen.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist die Lohnsteuer?',
      options: [
        'Eine eigenständige Steuerart, die Unternehmen zahlen.',
        'Eine Sonderabgabe auf Lohnnebenkosten.',
        'Die Erhebungsform der Einkommensteuer für Arbeitnehmer, abgeführt vom Arbeitgeber.',
        'Ein Teil der Umsatzsteuer auf Dienstleistungen.',
      ],
      correct: [2],
      explanation: 'Die Lohnsteuer ist keine eigene Steuerart, sondern die Vorauszahlung der Einkommensteuer; der Arbeitgeber führt sie direkt an das Finanzamt ab.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was kennzeichnet die soziale Marktwirtschaft im Kern?',
      options: [
        'Vollständige staatliche Planung der Wirtschaft ohne Marktmechanismus.',
        'Freier Markt ohne jegliche staatliche Eingriffe.',
        'Verbindung von freiem Markt mit staatlichem Sozialausgleich und Wettbewerbsregeln.',
        'Ausschließlich genossenschaftlich organisierte Produktion.',
      ],
      correct: [2],
      explanation: 'Die soziale Marktwirtschaft verbindet Marktfreiheit mit sozialer Absicherung und staatlicher Rahmenordnung.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was ist Deflation?',
      options: [
        'Ein anhaltender Anstieg des allgemeinen Preisniveaus.',
        'Ein einmaliger Preisrückgang bei einem einzelnen Produkt.',
        'Ein anhaltender Rückgang des allgemeinen Preisniveaus.',
        'Eine vorübergehende Erhöhung der Inflationsrate.',
      ],
      correct: [2],
      explanation: 'Bei Deflation sinken die Preise dauerhaft; Konsumenten schieben Käufe auf, was die Wirtschaft schwächen kann.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welcher Index gilt als wichtigster Leitindex für den deutschen Aktienmarkt?',
      options: ['MDAX', 'Dow Jones', 'DAX', 'Euro Stoxx 50'],
      correct: [2],
      explanation: 'Der DAX (Deutscher Aktienindex) mit den 40 größten börsennotierten deutschen Unternehmen ist der wichtigste deutsche Leitindex.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist ein Angebotsüberhang?',
      options: [
        'Die Nachfrage übersteigt das Angebot.',
        'Angebot und Nachfrage sind im Gleichgewicht.',
        'Das Angebot übersteigt die Nachfrage.',
        'Der Staat kauft alle nicht verkauften Güter auf.',
      ],
      correct: [2],
      explanation: 'Angebotsüberhang führt meist zu sinkenden Preisen, da Anbieter Käufer gewinnen wollen.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welche der folgenden Steuern ist eine indirekte Steuer?',
      options: ['Körperschaftsteuer', 'Einkommensteuer', 'Umsatzsteuer', 'Erbschaftsteuer'],
      correct: [2],
      explanation: 'Die Umsatzsteuer wird zwar vom Unternehmer abgeführt (Steuerschuldner), aber wirtschaftlich auf den Endverbraucher abgewälzt (Steuerträger) – typisch für indirekte Steuern.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'In welcher Konjunkturphase sinkt das Wirtschaftswachstum und steigt die Arbeitslosigkeit?',
      options: ['Boom', 'Aufschwung', 'Rezession', 'Expansion'],
      correct: [2],
      explanation: 'In der Rezession (Abschwung) schrumpft die Wirtschaftsleistung; Unternehmen bauen Stellen ab.',
      difficulty: 2,
    },
    {
      type: 'truefalse',
      prompt: 'Die Einkommensteuer in Deutschland ist eine progressive Steuer.',
      options: ['Wahr', 'Falsch'],
      correct: [0],
      explanation: 'Richtig: Mit steigendem Einkommen steigt der Grenzsteuersatz der Einkommensteuer in Deutschland.',
      difficulty: 1,
    },
    {
      type: 'truefalse',
      prompt: 'Der DAX enthält 30 Unternehmen.',
      options: ['Wahr', 'Falsch'],
      correct: [1],
      explanation: 'Falsch: Seit September 2021 umfasst der DAX 40 Unternehmen (Reform von 30 auf 40).',
      difficulty: 2,
    },
    {
      type: 'truefalse',
      prompt: 'Bei einem Monopol gibt es nur einen einzigen Anbieter auf dem Markt.',
      options: ['Wahr', 'Falsch'],
      correct: [0],
      explanation: 'Richtig: Das definiert das Monopol – ein Anbieter steht vielen Nachfragern gegenüber.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welches Ziel verfolgt eine Zentralbank, wenn sie die Leitzinsen erhöht?',
      options: [
        'Die Konjunktur ankurbeln und Investitionen fördern.',
        'Die Inflation bekämpfen, indem Kredite teurer werden.',
        'Die Staatsausgaben finanzieren.',
        'Den Export verbilligen.',
      ],
      correct: [1],
      explanation: 'Höhere Leitzinsen machen Kredite teurer, dämpfen Konsum und Investitionen und wirken so inflationsbremsend.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Was versteht man unter dem Gleichgewichtspreis am Markt?',
      options: [
        'Den staatlich festgesetzten Höchstpreis.',
        'Den Preis, bei dem Angebotsmenge und Nachfragemenge übereinstimmen.',
        'Den durchschnittlichen Preis aller Konkurrenten.',
        'Den Mindestpreis, den ein Produzent akzeptiert.',
      ],
      correct: [1],
      explanation: 'Im Marktgleichgewicht stimmen Angebots- und Nachfragemenge überein; es gibt weder Überschuss noch Mangel.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was ist die Dividende bei Aktien?',
      options: [
        'Der Kaufpreis einer Aktie an der Börse.',
        'Die staatliche Förderung für Aktionäre.',
        'Der Gewinnanteil, den eine Aktiengesellschaft an ihre Aktionäre ausschüttet.',
        'Die jährliche Gebühr für das Depot.',
      ],
      correct: [2],
      explanation: 'Die Dividende ist die Ausschüttung eines Teils des Unternehmensgewinns an die Aktionäre; sie ist keine Garantie.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welche Aussage zum ermäßigten Umsatzsteuersatz (7 %) trifft zu?',
      options: [
        'Er gilt für Luxusgüter wie Schmuck.',
        'Er gilt u. a. für Lebensmittel, Bücher und den ÖPNV.',
        'Er wird nur auf importierte Waren angewandt.',
        'Er gilt für alle digitalen Produkte ohne Ausnahme.',
      ],
      correct: [1],
      explanation: 'Der ermäßigte Satz von 7 % gilt u. a. für Grundnahrungsmittel, Bücher, Zeitungen und bestimmte Verkehrsleistungen.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was beschreibt das Gesetz von Angebot und Nachfrage bei steigendem Preis (ceteris paribus)?',
      options: [
        'Die Nachfrage steigt und das Angebot sinkt.',
        'Sowohl Nachfrage als auch Angebot steigen.',
        'Die Nachfrage sinkt und das Angebot steigt.',
        'Weder Nachfrage noch Angebot verändern sich.',
      ],
      correct: [2],
      explanation: 'Bei steigendem Preis sinkt typischerweise die Nachfrage (Nachfragekurve fällt), während Anbieter mehr produzieren (Angebotskurve steigt).',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Was ist charakteristisch für die Phase "Aufschwung" im Konjunkturzyklus?',
      options: [
        'Sinkende Produktion und steigende Arbeitslosigkeit.',
        'Wachsende Wirtschaftsleistung, steigende Beschäftigung und Investitionen.',
        'Stagnierende Wirtschaft bei hoher Inflation.',
        'Maximale Wirtschaftsleistung und Vollbeschäftigung.',
      ],
      correct: [1],
      explanation: 'Im Aufschwung (Expansion) wächst die Wirtschaft: Produktion, Beschäftigung und Investitionen nehmen zu.',
      difficulty: 2,
    },
    {
      type: 'fill',
      prompt: 'Der DAX ist der wichtigste ________ für den deutschen Aktienmarkt.',
      options: ['Leitindex', 'Sparvertrag', 'Schuldenindex', 'Inflationsmaß'],
      correct: [0],
      explanation: 'Der DAX (Deutscher Aktienindex) fungiert als Leitindex und spiegelt die Entwicklung der 40 größten deutschen Aktiengesellschaften wider.',
      difficulty: 1,
    },
  ],
};

export default topic;
