import type { RawTopic } from '../types';

const topic: RawTopic = {
  slug: 'wortanalogien',
  title: 'Wortanalogien',
  description: 'Beziehungen zwischen Wortpaaren erkennen (A : B = C : ?).',
  flashcards: [
    {
      front: 'Analogie-Typ: Beruf : Arbeitsort',
      back: 'Der erste Begriff ist ein Beruf, der zweite der typische Arbeitsort. Beispiel: Arzt : Krankenhaus = Richter : Gericht.',
    },
    {
      front: 'Analogie-Typ: Teil : Ganzes',
      back: 'Der erste Begriff ist ein Teil, der zweite das übergeordnete Ganze. Beispiel: Finger : Hand = Zeh : Fuß.',
    },
    {
      front: 'Analogie-Typ: Ursache : Wirkung',
      back: 'Der erste Begriff ist die Ursache, der zweite die Folge davon. Beispiel: Feuer : Rauch = Regen : Überschwemmung.',
    },
    {
      front: 'Analogie-Typ: Werkzeug : Tätigkeit',
      back: 'Der erste Begriff ist ein Werkzeug, der zweite die damit ausgeführte Tätigkeit. Beispiel: Schere : Schneiden = Hammer : Hämmern.',
    },
    {
      front: 'Analogie-Typ: Steigerung / Intensität',
      back: 'Der zweite Begriff ist eine Steigerung oder intensivere Form des ersten. Beispiel: warm : heiß = nass : durchnässt.',
    },
    {
      front: 'Analogie-Typ: Synonym',
      back: 'Beide Begriffspaare sind bedeutungsgleich oder bedeutungsähnlich. Beispiel: Anfang : Beginn = Ende : Abschluss.',
    },
    {
      front: 'Analogie-Typ: Antonym',
      back: 'Beide Begriffspaare sind jeweils Gegensätze. Beispiel: hell : dunkel = laut : leise.',
    },
    {
      front: 'Analogie-Typ: Tier : Nachwuchs',
      back: 'Der erste Begriff ist das Elterntier, der zweite das Jungtier. Beispiel: Hund : Welpe = Katze : Kätzchen.',
    },
    {
      front: 'Analogie-Typ: Tier : Laut',
      back: 'Der erste Begriff ist ein Tier, der zweite der typische Laut dieses Tieres. Beispiel: Hund : bellen = Kuh : muhen.',
    },
    {
      front: 'Analogie-Typ: Material : Produkt',
      back: 'Der erste Begriff ist das Rohmaterial, der zweite ein daraus hergestelltes Produkt. Beispiel: Wolle : Pullover = Holz : Tisch.',
    },
    {
      front: 'Analogie-Typ: Oberbegriff : Unterbegriff',
      back: 'Der erste Begriff ist die übergeordnete Kategorie, der zweite ein konkretes Exemplar. Beispiel: Fahrzeug : Auto = Instrument : Geige.',
    },
    {
      front: 'Analogie-Typ: Funktion / Zweck',
      back: 'Der zweite Begriff beschreibt den Zweck oder die Funktion des ersten. Beispiel: Messer : Schneiden = Brille : Sehen.',
    },
    {
      front: 'Analogie-Typ: Eigenschaft : Träger',
      back: 'Der erste Begriff ist eine Eigenschaft, der zweite ein typischer Träger dieser Eigenschaft. Beispiel: scharf : Klinge = süß : Zucker.',
    },
    {
      front: 'Analogie-Typ: Ort : Tätigkeit',
      back: 'Der erste Begriff ist ein Ort, der zweite die dort typisch ausgeführte Tätigkeit. Beispiel: Küche : Kochen = Bibliothek : Lesen.',
    },
    {
      front: 'Analogie-Typ: Handlung : Ergebnis',
      back: 'Der erste Begriff ist eine Handlung, der zweite ihr Ergebnis oder Produkt. Beispiel: Backen : Brot = Brauen : Bier.',
    },
    {
      front: 'Analogie-Typ: Mensch : Behausung',
      back: 'Der erste Begriff ist ein Lebewesen, der zweite seine typische Behausung. Beispiel: Mensch : Haus = Vogel : Nest.',
    },
    {
      front: 'Analogie-Typ: Zeitliche Abfolge',
      back: 'Die Begriffspaare stehen in einer zeitlichen oder logischen Reihenfolge. Beispiel: Morgen : Abend = Frühling : Herbst.',
    },
    {
      front: 'Analogie-Typ: Maßeinheit : Messgröße',
      back: 'Der erste Begriff ist eine Maßeinheit, der zweite die zugehörige Messgröße. Beispiel: Kilogramm : Gewicht = Meter : Länge.',
    },
  ],
  questions: [
    {
      type: 'mc',
      prompt: 'Arzt : Krankenhaus = Lehrer : ?',
      options: ['Schule', 'Tafel', 'Schüler', 'Buch'],
      correct: [0],
      explanation: 'Beziehung Beruf : Arbeitsort. Der Lehrer arbeitet in der Schule, so wie der Arzt im Krankenhaus arbeitet.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Hund : bellen = Katze : ?',
      options: ['schnurren', 'zischen', 'miauen', 'jagen'],
      correct: [2],
      explanation: 'Beziehung Tier : typischer Laut. Die Katze miaut, so wie der Hund bellt.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Finger : Hand = Zeh : ?',
      options: ['Nagel', 'Fuß', 'Bein', 'Schuh'],
      correct: [1],
      explanation: 'Beziehung Teil : Ganzes. Der Zeh ist ein Teil des Fußes, so wie der Finger ein Teil der Hand ist.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Wolle : Pullover = Leder : ?',
      options: ['Kuh', 'Schuh', 'Nadel', 'Stoff'],
      correct: [1],
      explanation: 'Beziehung Material : Produkt. Aus Leder wird ein Schuh hergestellt, so wie aus Wolle ein Pullover.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'hell : dunkel = laut : ?',
      options: ['stumm', 'ruhig', 'leise', 'still'],
      correct: [2],
      explanation: 'Beziehung Antonym. Das Gegenteil von laut ist leise, so wie das Gegenteil von hell dunkel ist.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Schere : Schneiden = Pinsel : ?',
      options: ['Farbe', 'Malen', 'Bürste', 'Zeichnen'],
      correct: [1],
      explanation: 'Beziehung Werkzeug : Tätigkeit. Mit einem Pinsel malt man, so wie man mit einer Schere schneidet.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Hund : Welpe = Katze : ?',
      options: ['Kätzchen', 'Kater', 'Kitten', 'Junges'],
      correct: [0],
      explanation: 'Beziehung Tier : Nachwuchs. Das Junge einer Katze heißt Kätzchen, so wie das Junge eines Hundes Welpe heißt.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Richter : Gericht = Pilot : ?',
      options: ['Flugzeug', 'Flughafen', 'Himmel', 'Cockpit'],
      correct: [1],
      explanation: 'Beziehung Beruf : Arbeitsort. Der Pilot arbeitet am Flughafen, so wie der Richter am Gericht.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Feuer : Rauch = Sonne : ?',
      options: ['Hitze', 'Mond', 'Licht', 'Tag'],
      correct: [2],
      explanation: 'Beziehung Ursache : Wirkung. Die Sonne erzeugt Licht, so wie Feuer Rauch erzeugt.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Anfang : Beginn = Ende : ?',
      options: ['Schluss', 'Abbruch', 'Pause', 'Abschluss'],
      correct: [3],
      explanation: 'Beziehung Synonym. Abschluss ist ein Synonym für Ende, so wie Beginn ein Synonym für Anfang ist.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Mensch : Haus = Vogel : ?',
      options: ['Baum', 'Nest', 'Himmel', 'Ei'],
      correct: [1],
      explanation: 'Beziehung Lebewesen : Behausung. Der Vogel lebt im Nest, so wie der Mensch im Haus lebt.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Messer : Schneiden = Brille : ?',
      options: ['Augen', 'Sehen', 'Lesen', 'Glas'],
      correct: [1],
      explanation: 'Beziehung Werkzeug : Funktion. Die Brille dient dem Sehen, so wie das Messer dem Schneiden dient.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Küche : Kochen = Bibliothek : ?',
      options: ['Buch', 'Ruhe', 'Lesen', 'Lernen'],
      correct: [2],
      explanation: 'Beziehung Ort : typische Tätigkeit. In der Bibliothek liest man, so wie man in der Küche kocht.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'warm : heiß = nass : ?',
      options: ['feucht', 'kalt', 'durchnässt', 'trocken'],
      correct: [2],
      explanation: 'Beziehung Steigerung. Durchnässt ist die Steigerung von nass, so wie heiß die Steigerung von warm ist.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Fahrzeug : Auto = Instrument : ?',
      options: ['Musik', 'Geige', 'Melodie', 'Orchester'],
      correct: [1],
      explanation: 'Beziehung Oberbegriff : Unterbegriff. Die Geige ist ein Instrument, so wie das Auto ein Fahrzeug ist.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Kilogramm : Gewicht = Meter : ?',
      options: ['Entfernung', 'Volumen', 'Länge', 'Fläche'],
      correct: [2],
      explanation: 'Beziehung Maßeinheit : Messgröße. Der Meter misst die Länge, so wie das Kilogramm das Gewicht misst.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Morgen : Abend = Frühling : ?',
      options: ['Sommer', 'Winter', 'Herbst', 'Jahreszeit'],
      correct: [2],
      explanation: 'Beziehung zeitliche Abfolge und Gegensatz. Herbst folgt dem Sommer und ist der Gegenpol zum Frühling, analog zu Abend als Gegenteil des Morgens.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Koch : Restaurant = Bauer : ?',
      options: ['Feld', 'Ernte', 'Hof', 'Traktor'],
      correct: [2],
      explanation: 'Beziehung Beruf : Arbeitsort. Der Bauer arbeitet auf dem Hof, so wie der Koch im Restaurant arbeitet.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Blatt : Baum = Seite : ?',
      options: ['Buch', 'Text', 'Zeile', 'Kapitel'],
      correct: [0],
      explanation: 'Beziehung Teil : Ganzes. Die Seite ist ein Teil des Buches, so wie das Blatt ein Teil des Baumes ist.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Kuh : Kalb = Pferd : ?',
      options: ['Hengst', 'Fohlen', 'Stute', 'Esel'],
      correct: [1],
      explanation: 'Beziehung Tier : Nachwuchs. Das Junge des Pferdes heißt Fohlen, so wie das Junge der Kuh Kalb heißt.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Kuh : muhen = Schaf : ?',
      options: ['blöken', 'bellen', 'brummen', 'grunzen'],
      correct: [0],
      explanation: 'Beziehung Tier : typischer Laut. Das Schaf blökt, so wie die Kuh muht.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Backen : Brot = Brauen : ?',
      options: ['Malz', 'Hopfen', 'Bier', 'Fass'],
      correct: [2],
      explanation: 'Beziehung Handlung : Ergebnis. Durch Brauen entsteht Bier, so wie durch Backen Brot entsteht.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Holz : Tisch = Ton : ?',
      options: ['Laut', 'Vase', 'Erde', 'Brennofen'],
      correct: [1],
      explanation: 'Beziehung Material : Produkt. Aus Ton wird eine Vase geformt, so wie aus Holz ein Tisch gefertigt wird.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Architekt : Gebäude = Schriftsteller : ?',
      options: ['Feder', 'Buch', 'Sprache', 'Verlag'],
      correct: [1],
      explanation: 'Beziehung Schöpfer : Werk. Der Schriftsteller schafft ein Buch, so wie der Architekt ein Gebäude entwirft.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Polizist : Wache = Soldat : ?',
      options: ['Waffe', 'Kaserne', 'Krieg', 'Uniform'],
      correct: [1],
      explanation: 'Beziehung Beruf : Arbeitsort. Der Soldat ist in der Kaserne stationiert, so wie der Polizist auf der Wache arbeitet.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Rad : Fahrrad = Flügel : ?',
      options: ['Vogel', 'Flugzeug', 'Luft', 'Feder'],
      correct: [1],
      explanation: 'Beziehung Teil : Ganzes. Der Flügel ist ein Teil des Flugzeugs, so wie das Rad ein Teil des Fahrrads ist.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Schwert : kämpfen = Pflug : ?',
      options: ['Acker', 'ernten', 'pflügen', 'Boden'],
      correct: [2],
      explanation: 'Beziehung Werkzeug : Tätigkeit. Mit dem Pflug pflügt man, so wie man mit dem Schwert kämpft.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Regen : Überschwemmung = Dürre : ?',
      options: ['Wüste', 'Wasserknappheit', 'Hitze', 'Ernte'],
      correct: [1],
      explanation: 'Beziehung Ursache : Wirkung. Dürre führt zu Wasserknappheit, so wie Regen zu einer Überschwemmung führen kann.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Freude : Jubel = Trauer : ?',
      options: ['Weinen', 'Schmerz', 'Sehnsucht', 'Schweigen'],
      correct: [0],
      explanation: 'Beziehung Steigerung / Intensität. Jubel ist die gesteigerte Form der Freude; Weinen ist der intensive Ausdruck der Trauer.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Strom : Elektrizität = Pipeline : ?',
      options: ['Öl', 'Gas', 'Rohr', 'Energie'],
      correct: [1],
      explanation: 'Beziehung Übertragungsweg : transportiertes Medium. Eine Pipeline transportiert Gas, so wie eine Stromleitung Elektrizität überträgt.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Löwe : brüllen = Schlange : ?',
      options: ['fauchen', 'zischen', 'pfeifen', 'bellen'],
      correct: [1],
      explanation: 'Beziehung Tier : typischer Laut. Die Schlange zischt, so wie der Löwe brüllt.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Glas : Flasche = Stahl : ?',
      options: ['Eisen', 'Brücke', 'Metall', 'Schmelze'],
      correct: [1],
      explanation: 'Beziehung Material : Produkt. Aus Stahl wird eine Brücke gebaut, so wie aus Glas eine Flasche hergestellt wird.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Pflanze : Botanik = Sterne : ?',
      options: ['Astronomie', 'Physik', 'Geografie', 'Astrologie'],
      correct: [0],
      explanation: 'Beziehung Forschungsgegenstand : Wissenschaft. Die Astronomie beschäftigt sich mit Sternen, so wie die Botanik Pflanzen erforscht.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Schaf : Wolle = Biene : ?',
      options: ['Stachel', 'Blüte', 'Honig', 'Wachs'],
      correct: [2],
      explanation: 'Beziehung Tier : produzierter Stoff. Die Biene produziert Honig, so wie das Schaf Wolle liefert.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Wort : Satz = Note : ?',
      options: ['Ton', 'Melodie', 'Rhythmus', 'Lied'],
      correct: [1],
      explanation: 'Beziehung Element : zusammengesetzte Einheit. Mehrere Noten ergeben eine Melodie, so wie mehrere Wörter einen Satz ergeben.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Arroganz : Bescheidenheit = Feigheit : ?',
      options: ['Angst', 'Tapferkeit', 'Stärke', 'Mut'],
      correct: [3],
      explanation: 'Beziehung Antonym. Das Gegenteil von Feigheit ist Mut, so wie das Gegenteil von Arroganz Bescheidenheit ist.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Auge : sehen = Nase : ?',
      options: ['atmen', 'riechen', 'schmecken', 'hören'],
      correct: [1],
      explanation: 'Beziehung Sinnesorgan : Funktion. Die Nase dient dem Riechen, so wie das Auge dem Sehen dient.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Säugling : Kind = Knospe : ?',
      options: ['Baum', 'Blume', 'Blüte', 'Samen'],
      correct: [2],
      explanation: 'Beziehung Entwicklungsstufe : spätere Stufe. Aus einer Knospe wird eine Blüte, so wie aus einem Säugling ein Kind wird.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Kapitän : Schiff = Dirigent : ?',
      options: ['Konzert', 'Taktstock', 'Orchester', 'Musik'],
      correct: [2],
      explanation: 'Beziehung Leiter : geleitete Einheit. Der Dirigent leitet das Orchester, so wie der Kapitän das Schiff führt.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Hunger : essen = Durst : ?',
      options: ['schlafen', 'trinken', 'Wasser', 'sättigen'],
      correct: [1],
      explanation: 'Beziehung Bedürfnis : Handlung zur Erfüllung. Durst wird durch Trinken gestillt, so wie Hunger durch Essen gestillt wird.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Frosch : Kaulquappe = Schmetterling : ?',
      options: ['Larve', 'Raupe', 'Puppe', 'Ei'],
      correct: [1],
      explanation: 'Beziehung Tier : Jungtierstadium (Larve). Die Raupe ist das Jungstadium des Schmetterlings, so wie die Kaulquappe das Jungstadium des Frosches ist.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Salz : salzig = Zucker : ?',
      options: ['süßlich', 'süß', 'sauer', 'bitter'],
      correct: [1],
      explanation: 'Beziehung Stoff : zugehörige Eigenschaft / Geschmack. Zucker schmeckt süß, so wie Salz salzig schmeckt.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Zeitung : Journalist = Film : ?',
      options: ['Schauspieler', 'Regisseur', 'Kamera', 'Drehbuch'],
      correct: [1],
      explanation: 'Beziehung Produkt : Hauptverantwortlicher. Der Regisseur verantwortet den Film, so wie der Journalist die Zeitung erstellt.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Biene : Bienenstock = Ameise : ?',
      options: ['Bau', 'Ameisenhaufen', 'Kolonie', 'Tunnel'],
      correct: [1],
      explanation: 'Beziehung Tier : Behausung. Die Ameise lebt im Ameisenhaufen, so wie die Biene im Bienenstock lebt.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Einnahme : Ausgabe = Gewinn : ?',
      options: ['Kosten', 'Verlust', 'Schuld', 'Minus'],
      correct: [1],
      explanation: 'Beziehung Antonym. Das Gegenteil von Gewinn ist Verlust, so wie das Gegenteil von Einnahme die Ausgabe ist.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Pinsel : Maler = Skalpell : ?',
      options: ['Chirurg', 'Arzt', 'Pfleger', 'Zahnarzt'],
      correct: [0],
      explanation: 'Beziehung Werkzeug : Berufsträger. Das Skalpell wird vom Chirurgen benutzt, so wie der Pinsel das Werkzeug des Malers ist.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Geige : Streichinstrument = Trompete : ?',
      options: ['Blasinstrument', 'Blechblasinstrument', 'Schlaginstrument', 'Instrument'],
      correct: [1],
      explanation: 'Beziehung Unterbegriff : Oberbegriff. Die Trompete ist ein Blechblasinstrument, so wie die Geige ein Streichinstrument ist.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Mond : Erde = Erde : ?',
      options: ['Universum', 'Milchstraße', 'Sonne', 'Mars'],
      correct: [2],
      explanation: 'Beziehung Satellit : umkreister Himmelskörper. Die Erde umkreist die Sonne, so wie der Mond die Erde umkreist.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Gesetz : Parlament = Urteil : ?',
      options: ['Anwalt', 'Richter', 'Gericht', 'Polizei'],
      correct: [1],
      explanation: 'Beziehung Ergebnis : verantwortliche Instanz. Das Urteil wird vom Richter gesprochen, so wie das Gesetz vom Parlament beschlossen wird.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Milch : Käse = Traube : ?',
      options: ['Obst', 'Wein', 'Most', 'Saft'],
      correct: [1],
      explanation: 'Beziehung Rohstoff : verarbeitetes Produkt. Aus Trauben wird Wein hergestellt, so wie aus Milch Käse hergestellt wird.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Kran : heben = Bohrer : ?',
      options: ['befestigen', 'schrauben', 'bohren', 'graben'],
      correct: [2],
      explanation: 'Beziehung Werkzeug : Tätigkeit. Mit einem Bohrer bohrt man, so wie mit einem Kran gehoben wird.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Schule : Bildung = Krankenhaus : ?',
      options: ['Operation', 'Heilung', 'Medizin', 'Gesundheit'],
      correct: [1],
      explanation: 'Beziehung Institution : Zweck. Das Krankenhaus dient der Heilung, so wie die Schule der Bildung dient.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Neugier : Entdeckung = Fleiß : ?',
      options: ['Arbeit', 'Erfolg', 'Mühe', 'Talent'],
      correct: [1],
      explanation: 'Beziehung Ursache : Wirkung. Fleiß führt zu Erfolg, so wie Neugier zu Entdeckungen führt.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Stoff : Kleid = Mehl : ?',
      options: ['Brot', 'Backen', 'Teig', 'Korn'],
      correct: [0],
      explanation: 'Beziehung Material : Endprodukt. Aus Mehl wird Brot gebacken, so wie aus Stoff ein Kleid genäht wird.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Tinte : Stift = Farbe : ?',
      options: ['Leinwand', 'Malen', 'Pinsel', 'Bild'],
      correct: [2],
      explanation: 'Beziehung Verbrauchsmittel : zugehöriges Werkzeug. Die Farbe wird mit dem Pinsel aufgetragen, so wie die Tinte im Stift steckt.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Glück : Unglück = Ordnung : ?',
      options: ['Regeln', 'Durcheinander', 'Chaos', 'Unordnung'],
      correct: [3],
      explanation: 'Beziehung Antonym. Das Gegenteil von Ordnung ist Unordnung, so wie das Gegenteil von Glück Unglück ist.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Adler : Horst = Fuchs : ?',
      options: ['Loch', 'Bau', 'Höhle', 'Nest'],
      correct: [1],
      explanation: 'Beziehung Tier : Behausung. Der Fuchs lebt im Bau, so wie der Adler seinen Horst bewohnt.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Sprechen : Stimme = Schreiben : ?',
      options: ['Papier', 'Hand', 'Text', 'Stift'],
      correct: [2],
      explanation: 'Beziehung Tätigkeit : Ergebnis. Durch Schreiben entsteht ein Text, so wie Sprechen eine Stimme bzw. gesprochene Aussage erzeugt.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Wasser : Eis = Dampf : ?',
      options: ['Nebel', 'Wasser', 'Gas', 'Wolke'],
      correct: [1],
      explanation: 'Beziehung Aggregatzustand. Dampf wird zu Wasser (kondensiert), so wie Wasser zu Eis (gefriert) werden kann.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Zahn : Zahnarzt = Herz : ?',
      options: ['Chirurg', 'Internist', 'Kardiologe', 'Arzt'],
      correct: [2],
      explanation: 'Beziehung Organ : zuständiger Facharzt. Der Kardiologe ist der Facharzt fürs Herz, so wie der Zahnarzt für Zähne zuständig ist.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Licht : Dunkelheit = Lärm : ?',
      options: ['Geräusch', 'Stille', 'Ruhe', 'Klang'],
      correct: [1],
      explanation: 'Beziehung Antonym. Das Gegenteil von Lärm ist Stille, so wie das Gegenteil von Licht Dunkelheit ist.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Bibliothek : Bücher = Museum : ?',
      options: ['Geschichte', 'Besucher', 'Exponate', 'Kunst'],
      correct: [2],
      explanation: 'Beziehung Institution : aufbewahrte Gegenstände. Im Museum werden Exponate ausgestellt, so wie in der Bibliothek Bücher aufbewahrt werden.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Säge : Holz = Sense : ?',
      options: ['Metall', 'Korn', 'Gras', 'Ernte'],
      correct: [2],
      explanation: 'Beziehung Werkzeug : bearbeitetes Material. Mit der Sense mäht man Gras, so wie mit der Säge Holz gesägt wird.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Atom : Molekül = Buchstabe : ?',
      options: ['Sprache', 'Wort', 'Satz', 'Alphabet'],
      correct: [1],
      explanation: 'Beziehung kleinste Einheit : zusammengesetzte Einheit. Mehrere Buchstaben bilden ein Wort, so wie mehrere Atome ein Molekül bilden.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Schaf : blöken = Schwein : ?',
      options: ['grunzen', 'quieken', 'brüllen', 'schnarren'],
      correct: [0],
      explanation: 'Beziehung Tier : typischer Laut. Das Schwein grunzt, so wie das Schaf blökt.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Pfleger : Pflegeheim = Richter : ?',
      options: ['Anwalt', 'Gericht', 'Polizeiwache', 'Parlament'],
      correct: [1],
      explanation: 'Beziehung Beruf : Arbeitsort. Der Richter arbeitet am Gericht, so wie der Pfleger im Pflegeheim arbeitet.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Schnee : Lawine = Wind : ?',
      options: ['Sturm', 'Regen', 'Brise', 'Tornado'],
      correct: [3],
      explanation: 'Beziehung Ursache : extreme Wirkung. Ein starker Wind kann zu einem Tornado werden, so wie Schnee eine Lawine auslösen kann.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Roman : Kapitel = Film : ?',
      options: ['Szene', 'Akt', 'Sequenz', 'Abschnitt'],
      correct: [0],
      explanation: 'Beziehung Ganzes : Gliederungseinheit. Ein Film besteht aus Szenen, so wie ein Roman aus Kapiteln besteht.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Chirurg : operieren = Richter : ?',
      options: ['verhören', 'urteilen', 'anklagen', 'verhaften'],
      correct: [1],
      explanation: 'Beziehung Beruf : typische Tätigkeit. Der Richter urteilt, so wie der Chirurg operiert.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Boden : Decke = Keller : ?',
      options: ['Dach', 'Dachboden', 'Stockwerk', 'Erdgeschoss'],
      correct: [1],
      explanation: 'Beziehung räumliche Gegensätze (unten : oben). Der Dachboden ist das Gegenstück zum Keller im Gebäude, so wie die Decke der Gegenpol zum Boden ist.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Architekt : planen = Lehrer : ?',
      options: ['prüfen', 'unterrichten', 'erziehen', 'lernen'],
      correct: [1],
      explanation: 'Beziehung Beruf : typische Tätigkeit. Der Lehrer unterrichtet, so wie der Architekt plant.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Sonne : Tag = Mond : ?',
      options: ['Nacht', 'Licht', 'Dunkel', 'Stern'],
      correct: [0],
      explanation: 'Beziehung Himmelskörper : zugehörige Tageszeit. Der Mond ist mit der Nacht verbunden, so wie die Sonne den Tag erhellt.',
      difficulty: 1,
    },
  ],
};

export default topic;
