import type { RawTopic } from '../types';

const topic: RawTopic = {
  slug: 'zahlensysteme',
  title: 'Zahlensysteme & Einheiten',
  description: 'Binär, Dezimal, Hexadezimal und digitale Einheiten.',
  flashcards: [
    {
      front: 'Was ist das Binärsystem?',
      back: 'Das Binärsystem ist ein Zahlensystem zur Basis 2. Es verwendet nur die Ziffern 0 und 1. Jede Stelle entspricht einer Potenz von 2 (Einerstelle = 2⁰ = 1, nächste = 2¹ = 2, dann 2² = 4 usw.).',
    },
    {
      front: 'Was ist das Dezimalsystem?',
      back: 'Das Dezimalsystem ist das gewöhnliche Zahlensystem mit der Basis 10. Es verwendet die Ziffern 0–9. Jede Stelle ist eine Potenz von 10.',
    },
    {
      front: 'Was ist das Hexadezimalsystem?',
      back: 'Das Hexadezimalsystem hat die Basis 16. Es verwendet die Ziffern 0–9 und die Buchstaben A–F (A=10, B=11, C=12, D=13, E=14, F=15). Hex-Werte werden oft mit dem Präfix 0x oder der Endung h geschrieben.',
    },
    {
      front: 'Was ist das Oktalsystem?',
      back: 'Das Oktalsystem hat die Basis 8. Es verwendet die Ziffern 0–7. Es wird z. B. in Unix-Dateiberechtigungen eingesetzt.',
    },
    {
      front: 'Wie rechnet man eine Binärzahl in eine Dezimalzahl um?',
      back: 'Jede Binärziffer wird mit der entsprechenden Zweierpotenz multipliziert (von rechts beginnend mit 2⁰) und die Ergebnisse addiert. Beispiel: 1010₂ = 1×2³ + 0×2² + 1×2¹ + 0×2⁰ = 8 + 0 + 2 + 0 = 10₁₀.',
    },
    {
      front: 'Wie rechnet man eine Dezimalzahl in eine Binärzahl um?',
      back: 'Man dividiert die Dezimalzahl wiederholt durch 2 und notiert die Reste von unten nach oben. Beispiel: 10 ÷ 2 = 5 R0; 5 ÷ 2 = 2 R1; 2 ÷ 2 = 1 R0; 1 ÷ 2 = 0 R1 → Ergebnis (von unten): 1010₂.',
    },
    {
      front: 'Was ist ein Bit?',
      back: 'Ein Bit (Binary Digit) ist die kleinste Informationseinheit in der Informatik. Es kann genau zwei Zustände annehmen: 0 oder 1.',
    },
    {
      front: 'Was ist ein Byte?',
      back: 'Ein Byte besteht aus 8 Bit. Mit einem Byte lassen sich 2⁸ = 256 verschiedene Werte darstellen (0 bis 255).',
    },
    {
      front: 'Was bedeuten die Speichereinheiten KB, MB, GB, TB?',
      back: '1 KB (Kilobyte) = 1024 Byte; 1 MB (Megabyte) = 1024 KB; 1 GB (Gigabyte) = 1024 MB; 1 TB (Terabyte) = 1024 GB. Die Faktoren basieren auf Potenzen von 2 (2¹⁰ = 1024).',
    },
    {
      front: 'Welche Dezimalwerte entsprechen den Hex-Ziffern A bis F?',
      back: 'A = 10, B = 11, C = 12, D = 13, E = 14, F = 15.',
    },
    {
      front: 'Wie rechnet man eine Hexadezimalzahl in eine Dezimalzahl um?',
      back: 'Jede Hex-Ziffer wird mit der entsprechenden Potenz von 16 multipliziert. Beispiel: 1F₁₆ = 1×16¹ + 15×16⁰ = 16 + 15 = 31₁₀.',
    },
    {
      front: 'Wie rechnet man Binär direkt in Hexadezimal um?',
      back: 'Man fasst die Binärziffern in Vierergruppen zusammen (von rechts) und ersetzt jede Gruppe durch die entsprechende Hex-Ziffer. Beispiel: 1111 0001₂ → F1₁₆ (1111=15=F, 0001=1).',
    },
    {
      front: 'Was ist ASCII?',
      back: 'ASCII (American Standard Code for Information Interchange) ist eine Zeichenkodierung, die 128 Zeichen (0–127) mit 7 Bit darstellt. Zum Beispiel entspricht das Zeichen "A" dem dezimalen Wert 65 (binär: 1000001).',
    },
    {
      front: 'Was ist Unicode?',
      back: 'Unicode ist ein internationaler Zeichensatz, der mehr als 140.000 Zeichen aus zahlreichen Schriftsystemen umfasst. UTF-8 ist die häufigste Kodierung und verwendet 1–4 Byte pro Zeichen. Es ist abwärtskompatibel zu ASCII.',
    },
    {
      front: 'Was ist der Unterschied zwischen Bit und Byte in der Übertragungsrate?',
      back: 'Übertragungsraten (z. B. Internetgeschwindigkeit) werden oft in Megabit pro Sekunde (Mbit/s) angegeben, Speichergrößen in Megabyte (MB). 1 MB/s = 8 Mbit/s.',
    },
    {
      front: 'Welche Binärzahl entspricht der Dezimalzahl 255?',
      back: '255₁₀ = 1111 1111₂. Das ist der größte Wert, der mit 8 Bit (1 Byte) dargestellt werden kann: 2⁸ - 1 = 255.',
    },
    {
      front: 'Was ist der Unterschied zwischen SI-Präfixen und Binärpräfixen?',
      back: 'SI-Präfixe (kilo, mega, giga) stehen für Potenzen von 10 (1000, 1.000.000 usw.). In der IT werden jedoch Binärpräfixe verwendet: 1 KB = 1024 Byte (2¹⁰). IEC-Normen definieren "Kibibyte (KiB)" für 1024 Byte, um Verwechslungen zu vermeiden.',
    },
    {
      front: 'Wie viele Werte kann man mit n Bit darstellen?',
      back: 'Mit n Bit lassen sich 2ⁿ verschiedene Werte darstellen. Beispiele: 1 Bit → 2 Werte, 4 Bit → 16 Werte, 8 Bit → 256 Werte, 16 Bit → 65.536 Werte, 32 Bit → über 4 Milliarden Werte.',
    },
    {
      front: 'Was ist das Zweierkomplement?',
      back: 'Das Zweierkomplement ist die gebräuchlichste Methode zur Darstellung negativer ganzer Zahlen im Binärsystem. Eine negative Zahl wird gebildet, indem alle Bits der positiven Zahl invertiert und 1 addiert wird. Beispiel: -1 wird bei 8 Bit als 1111 1111 dargestellt.',
    },
    {
      front: 'Wie lautet die Binärzahl 15 in Dezimal und Hexadezimal?',
      back: '15₁₀ = 1111₂ = F₁₆. Es ist die größte vierstellige Binärzahl (2⁴ - 1 = 15) und entspricht der letzten einstelligen Hex-Ziffer F.',
    },
  ],
  questions: [
    {
      type: 'mc',
      prompt: 'Welche Dezimalzahl entspricht der Binärzahl 1010?',
      options: ['10', '12', '8', '5'],
      correct: [0],
      explanation: '1010₂ = 1×2³ + 0×2² + 1×2¹ + 0×2⁰ = 8 + 0 + 2 + 0 = 10₁₀.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welche Dezimalzahl entspricht der Binärzahl 1111?',
      options: ['12', '14', '16', '15'],
      correct: [3],
      explanation: '1111₂ = 1×2³ + 1×2² + 1×2¹ + 1×2⁰ = 8 + 4 + 2 + 1 = 15₁₀.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welche Binärzahl entspricht der Dezimalzahl 5?',
      options: ['110', '010', '101', '100'],
      correct: [2],
      explanation: '5₁₀ = 4 + 1 = 1×2² + 0×2¹ + 1×2⁰ = 101₂.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Wie viele Bit hat ein Byte?',
      options: ['4', '16', '2', '8'],
      correct: [3],
      explanation: 'Ein Byte besteht per Definition aus 8 Bit.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Wie viele Byte entsprechen 1 Kilobyte (KB) in der IT?',
      options: ['1000', '512', '2048', '1024'],
      correct: [3],
      explanation: 'In der Informatik gilt: 1 KB = 2¹⁰ Byte = 1024 Byte.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welcher Hexadezimalwert entspricht der Dezimalzahl 255?',
      options: ['EE', 'FE', 'FF', 'EF'],
      correct: [2],
      explanation: '255₁₀ = 15×16¹ + 15×16⁰ = F×16 + F = FF₁₆.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was ist die Basis des Hexadezimalsystems?',
      options: ['2', '8', '10', '16'],
      correct: [3],
      explanation: 'Das Hexadezimalsystem hat die Basis 16 und verwendet die Ziffern 0–9 sowie A–F.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welche Dezimalzahl entspricht der Hexadezimalzahl A?',
      options: ['11', '10', '12', '16'],
      correct: [1],
      explanation: 'Im Hexadezimalsystem steht A für den Dezimalwert 10.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welche Dezimalzahl entspricht der Binärzahl 1000?',
      options: ['4', '16', '8', '6'],
      correct: [2],
      explanation: '1000₂ = 1×2³ + 0×2² + 0×2¹ + 0×2⁰ = 8 + 0 + 0 + 0 = 8₁₀.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Wie viele verschiedene Werte lassen sich mit 8 Bit darstellen?',
      options: ['128', '512', '256', '64'],
      correct: [2],
      explanation: 'Mit 8 Bit lassen sich 2⁸ = 256 verschiedene Werte darstellen (0 bis 255).',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welche Binärzahl entspricht der Dezimalzahl 13?',
      options: ['1110', '1101', '1011', '1100'],
      correct: [1],
      explanation: '13₁₀ = 8 + 4 + 1 = 1×2³ + 1×2² + 0×2¹ + 1×2⁰ = 1101₂.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Wie viele KB entsprechen 1 Megabyte (MB)?',
      options: ['1000', '1024', '512', '2048'],
      correct: [1],
      explanation: '1 MB = 1024 KB, da 1024 = 2¹⁰.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welche Hexadezimalzahl entspricht der Dezimalzahl 16?',
      options: ['F', 'G', '10', '11'],
      correct: [2],
      explanation: '16₁₀ = 1×16¹ + 0×16⁰ = 10₁₆. Im Hexadezimalsystem ist "10" der Wert sechzehn.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welche Dezimalzahl entspricht der Hexadezimalzahl 1F?',
      options: ['15', '16', '31', '30'],
      correct: [2],
      explanation: '1F₁₆ = 1×16¹ + 15×16⁰ = 16 + 15 = 31₁₀.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welche Binärzahl entspricht der Hexadezimalzahl F?',
      options: ['1110', '1010', '1100', '1111'],
      correct: [3],
      explanation: 'F₁₆ = 15₁₀ = 8+4+2+1 = 1111₂.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Wie viele GB entsprechen 1 Terabyte (TB)?',
      options: ['512', '2048', '1000', '1024'],
      correct: [3],
      explanation: '1 TB = 1024 GB, da die Einheiten jeweils um den Faktor 2¹⁰ = 1024 steigen.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welches Zahlensystem wird in Unix-Dateiberechtigungen (chmod) verwendet?',
      options: ['Binär', 'Dezimal', 'Oktal', 'Hexadezimal'],
      correct: [2],
      explanation: 'Unix-Dateiberechtigungen (z. B. chmod 755) verwenden das Oktalsystem (Basis 8), da je 3 Bit einer Oktalziffer entsprechen.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Welche Dezimalzahl entspricht der Binärzahl 11001?',
      options: ['24', '25', '26', '23'],
      correct: [1],
      explanation: '11001₂ = 1×2⁴ + 1×2³ + 0×2² + 0×2¹ + 1×2⁰ = 16 + 8 + 0 + 0 + 1 = 25₁₀.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Welche Binärzahl entspricht der Dezimalzahl 20?',
      options: ['10100', '10010', '10110', '01100'],
      correct: [0],
      explanation: '20₁₀ = 16 + 4 = 1×2⁴ + 0×2³ + 1×2² + 0×2¹ + 0×2⁰ = 10100₂.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Was ist der ASCII-Dezimalwert des Großbuchstabens "A"?',
      options: ['97', '65', '64', '66'],
      correct: [1],
      explanation: 'Im ASCII-Standard hat der Großbuchstabe "A" den Dezimalwert 65 (binär: 1000001).',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Wie groß ist 1 GB in Byte?',
      options: ['1.000.000 Byte', '1.048.576 Byte', '1.073.741.824 Byte', '1.024.000 Byte'],
      correct: [2],
      explanation: '1 GB = 1024 MB = 1024 × 1024 KB = 1024 × 1024 × 1024 Byte = 1.073.741.824 Byte = 2³⁰ Byte.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Welche Aussage über UTF-8 ist korrekt?',
      options: [
        'UTF-8 verwendet immer genau 2 Byte pro Zeichen.',
        'UTF-8 ist nicht kompatibel mit ASCII.',
        'UTF-8 kann 1 bis 4 Byte pro Zeichen verwenden.',
        'UTF-8 unterstützt maximal 128 Zeichen.',
      ],
      correct: [2],
      explanation: 'UTF-8 ist eine variable Kodierung: ASCII-Zeichen belegen 1 Byte, andere Zeichen 2–4 Byte. UTF-8 ist vollständig abwärtskompatibel zu ASCII.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Welche Hexadezimalzahl entspricht der Binärzahl 10110100?',
      options: ['B3', 'B4', 'A4', 'C4'],
      correct: [1],
      explanation: '10110100₂ wird in Vierergruppen aufgeteilt: 1011 | 0100. 1011₂ = 11₁₀ = B₁₆; 0100₂ = 4₁₀ = 4₁₆. Ergebnis: B4₁₆.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Welche Dezimalzahl entspricht der Oktalzahl 17?',
      options: ['17', '15', '14', '16'],
      correct: [1],
      explanation: '17₈ = 1×8¹ + 7×8⁰ = 8 + 7 = 15₁₀.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Wie viele Bit werden benötigt, um 64 verschiedene Werte darzustellen?',
      options: ['8', '4', '16', '6'],
      correct: [3],
      explanation: '2⁶ = 64, also werden genau 6 Bit benötigt, um 64 verschiedene Werte (0 bis 63) darzustellen.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Welche Dezimalzahl entspricht der Binärzahl 0111?',
      options: ['8', '6', '5', '7'],
      correct: [3],
      explanation: '0111₂ = 0×2³ + 1×2² + 1×2¹ + 1×2⁰ = 0 + 4 + 2 + 1 = 7₁₀.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was bedeutet "0xFF" in Dezimal?',
      options: ['240', '256', '254', '255'],
      correct: [3],
      explanation: '0xFF = FF₁₆ = 15×16¹ + 15×16⁰ = 240 + 15 = 255₁₀. Das Präfix "0x" kennzeichnet einen Hexadezimalwert.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welche Binärzahl entspricht der Dezimalzahl 100?',
      options: ['1100100', '1101000', '1010100', '1110100'],
      correct: [0],
      explanation: '100₁₀ = 64+32+4 = 1×2⁶+1×2⁵+0×2⁴+0×2³+1×2²+0×2¹+0×2⁰ = 1100100₂.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Welche Aussage über das Zweierkomplement ist korrekt?',
      options: [
        'Positive und negative Zahlen werden gleich dargestellt.',
        'Das Zweierkomplement von 0000 0001 ist 1111 1111.',
        'Mit 8 Bit lassen sich Zahlen von -128 bis +127 darstellen.',
        'Das Zweierkomplement wird nur im Hexadezimalsystem verwendet.',
      ],
      correct: [2],
      explanation: 'Mit dem Zweierkomplement und 8 Bit lassen sich Zahlen von -128 bis +127 darstellen (256 Werte insgesamt, asymmetrisch wegen der Null).',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Welche Hexadezimalzahl entspricht der Dezimalzahl 171?',
      options: ['AA', 'AB', 'BA', 'BB'],
      correct: [1],
      explanation: '171₁₀: 171 ÷ 16 = 10 Rest 11. Also 10₁₆ = A und 11₁₆ = B → AB₁₆. Probe: 10×16 + 11 = 160+11 = 171. ✓',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Was ist der Hauptunterschied zwischen Mbit/s und MB/s bei Datenübertragungsraten?',
      options: [
        'Es gibt keinen Unterschied, beide sind identisch.',
        '1 MB/s = 8 Mbit/s, da 1 Byte = 8 Bit.',
        '1 Mbit/s = 8 MB/s, da ein Bit kleiner als ein Byte ist.',
        '1 MB/s = 1024 Mbit/s.',
      ],
      correct: [1],
      explanation: 'Da 1 Byte = 8 Bit gilt, ist 1 MB/s = 8 Mbit/s. Internetanbieter geben Geschwindigkeiten oft in Mbit/s an, was häufig zu Verwirrung führt.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welche Binärzahl entspricht der Dezimalzahl 255?',
      options: ['11111110', '11111111', '11110000', '10101010'],
      correct: [1],
      explanation: '255₁₀ = 2⁸ - 1 = 128+64+32+16+8+4+2+1 = 11111111₂. Das ist der Maximalwert eines Byte.',
      difficulty: 2,
    },
    {
      type: 'fill',
      prompt: 'Wie viele Bit hat ein Byte?',
      correct: ['8', 'acht'],
      explanation: 'Ein Byte besteht aus 8 Bit. Dies ist eine grundlegende Definition der Informatik.',
      difficulty: 1,
    },
    {
      type: 'fill',
      prompt: 'Wie lautet die Dezimalzahl für die Binärzahl 1010?',
      correct: ['10', 'zehn'],
      explanation: '1010₂ = 1×8 + 0×4 + 1×2 + 0×1 = 10₁₀.',
      difficulty: 2,
    },
    {
      type: 'fill',
      prompt: 'Wie viele Byte hat 1 Kilobyte (KB) in der Informatik?',
      correct: ['1024'],
      explanation: '1 KB = 2¹⁰ = 1024 Byte. Der Faktor 1024 ergibt sich aus der binären Natur von Computersystemen.',
      difficulty: 1,
    },
    {
      type: 'fill',
      prompt: 'Welcher Dezimalwert hat die Hexadezimalziffer F?',
      correct: ['15', 'fünfzehn'],
      explanation: 'F ist die letzte Ziffer im Hexadezimalsystem und entspricht dem Dezimalwert 15.',
      difficulty: 1,
    },
    {
      type: 'fill',
      prompt: 'Wie viele verschiedene Werte kann man mit 4 Bit (einem Nibble) darstellen?',
      correct: ['16', 'sechzehn'],
      explanation: 'Mit 4 Bit lassen sich 2⁴ = 16 verschiedene Werte darstellen (0 bis 15).',
      difficulty: 2,
    },
    {
      type: 'truefalse',
      prompt: '1 MB entspricht genau 1000 KB.',
      options: ['Richtig', 'Falsch'],
      correct: [1],
      explanation: 'Falsch. In der Informatik gilt 1 MB = 1024 KB (nicht 1000 KB). Die SI-Definition (1000) wird in der IT üblicherweise nicht verwendet.',
      difficulty: 1,
    },
    {
      type: 'truefalse',
      prompt: 'Die Hexadezimalzahl FF entspricht der Dezimalzahl 255.',
      options: ['Richtig', 'Falsch'],
      correct: [0],
      explanation: 'Richtig. FF₁₆ = 15×16 + 15 = 240 + 15 = 255₁₀.',
      difficulty: 2,
    },
    {
      type: 'truefalse',
      prompt: 'ASCII verwendet 8 Bit und kann damit 256 Zeichen darstellen.',
      options: ['Richtig', 'Falsch'],
      correct: [1],
      explanation: 'Falsch. Der originale ASCII-Standard verwendet 7 Bit und definiert 128 Zeichen (0–127). Erst die erweiterten ASCII-Varianten nutzen 8 Bit.',
      difficulty: 2,
    },
    {
      type: 'truefalse',
      prompt: 'Die Binärzahl 1101 entspricht der Dezimalzahl 13.',
      options: ['Richtig', 'Falsch'],
      correct: [0],
      explanation: 'Richtig. 1101₂ = 1×2³ + 1×2² + 0×2¹ + 1×2⁰ = 8 + 4 + 0 + 1 = 13₁₀.',
      difficulty: 2,
    },
  ],
};

export default topic;
