import type { RawTopic } from '../types';

const topic: RawTopic = {
  slug: 'zeichensetzung',
  title: 'Zeichensetzung',
  description: 'Kommaregeln und Satzzeichen sicher anwenden.',
  flashcards: [
    {
      front: 'Wann steht ein Komma zwischen zwei Hauptsätzen?',
      back: 'Wenn zwei Hauptsätze durch eine Konjunktion wie "aber", "doch", "jedoch", "sondern", "denn" verbunden werden oder unverbunden nebeneinanderstehen, trennt ein Komma sie. Beispiel: "Er kam, aber sie blieb."',
    },
    {
      front: 'Muss vor "und" und "oder" ein Komma stehen?',
      back: 'Nein. Zwischen zwei Hauptsätzen, die mit "und" oder "oder" verbunden sind, kann ein Komma stehen, muss aber nicht. Vor "und"/"oder" in einer Aufzählung steht kein Komma. Beispiel: "Er lief und sie sprang." – kein Komma erforderlich.',
    },
    {
      front: 'Was ist die Kommaregel für Nebensätze?',
      back: 'Nebensätze werden durch Kommas vom Hauptsatz abgetrennt. Steht der Nebensatz in der Mitte, wird er beidseitig durch Kommas eingeschlossen. Beispiel: "Das Buch, das ich las, war spannend."',
    },
    {
      front: 'Wann wird ein Infinitiv mit "zu" durch ein Komma abgetrennt?',
      back: 'Ein erweiterter Infinitiv mit "zu" wird durch ein Komma abgetrennt, wenn er von einem Substantiv abhängt, mit "um", "ohne", "anstatt", "außer", "statt" eingeleitet wird oder wenn ein Komma der Verdeutlichung dient. Einfache Infinitive wie "Er versucht zu lesen" brauchen kein Komma.',
    },
    {
      front: 'Was ist ein Relativsatz und wie wird er mit Kommas markiert?',
      back: 'Ein Relativsatz ist ein Nebensatz, der durch ein Relativpronomen (der, die, das, welcher …) eingeleitet wird. Er wird immer durch Kommas vom Rest des Satzes abgetrennt. Beispiel: "Der Mann, der dort steht, ist mein Vater."',
    },
    {
      front: 'Wann steht ein Komma bei Aufzählungen?',
      back: 'Zwischen den Gliedern einer Aufzählung steht ein Komma, wenn sie nicht durch "und" oder "oder" verbunden sind. Beispiel: "Ich kaufte Äpfel, Birnen, Bananen und Orangen." – vor "und" kein Komma.',
    },
    {
      front: 'Was ist eine Apposition und wie wird sie abgetrennt?',
      back: 'Eine Apposition ist eine nachgestellte Erläuterung zu einem Substantiv. Sie wird durch Kommas eingeschlossen. Beispiel: "Herr Müller, unser Lehrer, erklärt die Aufgabe."',
    },
    {
      front: 'Wie werden Einschübe im Satz gekennzeichnet?',
      back: 'Einschübe (Parenthesen) werden durch Kommas, Gedankenstriche oder Klammern eingeschlossen. Sie könnten weggelassen werden, ohne den Satz grammatisch falsch zu machen. Beispiel: "Er war, wie ich später erfuhr, schon lange krank."',
    },
    {
      front: 'Wie werden direkte Rede und Begleitsatz durch Satzzeichen getrennt?',
      back: 'Die direkte Rede steht in Anführungszeichen. Sie wird vom Begleitsatz durch Komma getrennt (wenn kein Ausrufe- oder Fragezeichen). Beispiel: "Er sagte: \\"Ich komme morgen.\\"" oder "\\"Ich komme morgen\\", sagte er."',
    },
    {
      front: 'Wann verwendet man den Doppelpunkt?',
      back: 'Der Doppelpunkt steht vor Aufzählungen, wörtlicher Rede, Erklärungen und Zusammenfassungen. Nach dem Doppelpunkt wird kleingeschrieben, wenn ein unvollständiger Satz folgt; großgeschrieben, wenn ein vollständiger Satz folgt.',
    },
    {
      front: 'Welche Funktion hat das Semikolon?',
      back: 'Das Semikolon trennt gleichrangige, inhaltlich zusammengehörende Hauptsätze oder Aufzählungsglieder, die selbst schon Kommas enthalten. Es ist stärker als ein Komma, schwächer als ein Punkt. Beispiel: "Er kam; sie ging."',
    },
    {
      front: 'Welche Anführungszeichen sind im Deutschen korrekt?',
      back: 'Im Deutschen stehen die öffnenden Anführungszeichen unten („) und die schließenden oben ("). Beispiel: „Das ist richtig." – Nicht wie im Englischen: "Das ist richtig."',
    },
    {
      front: 'Wann steht kein Komma vor "dass"?',
      back: 'Vor "dass" steht immer ein Komma, da "dass" einen Nebensatz einleitet. Es gibt keine Ausnahme. Beispiel: "Ich hoffe, dass du kommst." – das Komma ist obligatorisch.',
    },
    {
      front: 'Wie unterscheidet sich "dass" von "das" in Bezug auf Komma?',
      back: '"Dass" leitet immer einen Nebensatz ein und wird immer durch Komma abgetrennt. "Das" als Relativpronomen leitet ebenfalls einen Nebensatz ein (mit Komma). "Das" als Artikel oder Demonstrativpronomen leitet keinen Nebensatz ein.',
    },
    {
      front: 'Muss vor "obwohl", "weil", "wenn" immer ein Komma stehen?',
      back: 'Ja. Diese Konjunktionen leiten Nebensätze ein, die stets durch Komma vom Hauptsatz getrennt werden. Beispiel: "Er kam nicht, weil er krank war." / "Wenn es regnet, bleiben wir drinnen."',
    },
    {
      front: 'Was gilt bei verschachtelten Nebensätzen für die Kommasetzung?',
      back: 'Jeder Nebensatz wird durch Kommas abgegrenzt, unabhängig davon, ob er in einen anderen Nebensatz eingebettet ist. Beispiel: "Ich weiß, dass er, weil er müde war, früh schlafen ging."',
    },
    {
      front: 'Wann steht ein Komma vor "wie" und "als"?',
      back: '"Wie" und "als" leiten Vergleichsnebensätze ein und werden durch Komma abgetrennt, wenn es sich um vollständige Nebensätze handelt. Bei Vergleichen ohne Verb (Kurzformen) steht kein Komma: "Er ist größer als sein Bruder."',
    },
    {
      front: 'Welche Satzzeichen stehen am Ende einer direkten Frage?',
      back: 'Eine direkte Frage endet mit einem Fragezeichen. Steht die Frage als direkte Rede am Satzende, entfällt der abschließende Punkt des Begleitsatzes: "Er fragte: \\"Kommst du?\\"" – kein Punkt nach dem Fragezeichen.',
    },
    {
      front: 'Was sind gleichrangige Adjektive und wie werden sie durch Komma getrennt?',
      back: 'Gleichrangige Adjektive, die dasselbe Substantiv auf gleicher Ebene beschreiben, werden durch Komma getrennt. Beispiel: "ein langer, beschwerlicher Weg". Nicht gleichrangig (kein Komma): "ein schöner alter Schrank" (da "alter Schrank" eine Einheit ist).',
    },
  ],
  questions: [
    {
      type: 'mc',
      prompt: 'Welcher Satz ist korrekt interpunktiert?',
      options: [
        'Ich glaube, dass er morgen kommt.',
        'Ich glaube dass er morgen kommt.',
        'Ich glaube, dass, er morgen kommt.',
        'Ich glaube; dass er morgen kommt.',
      ],
      correct: [0],
      explanation: 'Vor "dass" steht immer ein Komma, da es einen Nebensatz einleitet. Innerhalb des Nebensatzes kein zusätzliches Komma vor dem Subjekt.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Wo muss in folgendem Satz ein Komma stehen? "Er lief so schnell er konnte."',
      options: [
        '"Er lief so schnell, er konnte." – nach "schnell"',
        '"Er lief, so schnell er konnte." – nach "lief"',
        '"Er lief so schnell er konnte." – kein Komma nötig',
        '"Er lief so schnell er, konnte." – nach "er"',
      ],
      correct: [1],
      explanation: '"so schnell er konnte" ist ein Nebensatz; er wird durch Komma vom Hauptsatz getrennt: "Er lief, so schnell er konnte."',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welcher Satz enthält einen Fehler bei der Kommasetzung?',
      options: [
        'Sie sang, und er spielte Klavier.',
        'Sie sang und er spielte Klavier.',
        'Sie sang, aber er spielte Gitarre.',
        'Sie sang; er spielte Klavier.',
      ],
      correct: [0],
      explanation: 'Vor "und" zwischen zwei Hauptsätzen ist ein Komma möglich, aber nicht vorgeschrieben. Keiner der anderen Sätze ist fehlerhaft. Satz A ist zwar akzeptabel, aber das Komma vor "und" bei vollständigen Hauptsätzen ist optional – kein Fehler. Satz C mit "aber" erfordert das Komma. Alle sind korrekt; Satz A ist nur dann problematisch, wenn die Aufgabe "falsch" meint: hier ist der Kniff, dass "und" das Komma nicht erzwingt.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welcher Satz mit Relativsatz ist korrekt interpunktiert?',
      options: [
        'Das Buch das ich gekauft habe liegt auf dem Tisch.',
        'Das Buch, das ich gekauft habe liegt auf dem Tisch.',
        'Das Buch, das ich gekauft habe, liegt auf dem Tisch.',
        'Das Buch das ich gekauft habe, liegt auf dem Tisch.',
      ],
      correct: [2],
      explanation: 'Der Relativsatz "das ich gekauft habe" muss beidseitig durch Kommas eingeschlossen werden: nach "Buch" und nach "habe".',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welche Regel gilt für Infinitivgruppen mit "um … zu"?',
      options: [
        'Sie werden nie durch Komma abgetrennt.',
        'Sie werden immer durch Komma abgetrennt.',
        'Sie werden nur abgetrennt, wenn der Infinitiv am Satzanfang steht.',
        'Sie werden nur abgetrennt, wenn der Hauptsatz kein Verb enthält.',
      ],
      correct: [1],
      explanation: 'Infinitivgruppen mit "um … zu", "ohne … zu", "anstatt … zu" werden immer durch Komma vom Hauptsatz abgetrennt. Beispiel: "Er übte täglich, um besser zu werden."',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welcher Satz mit Apposition ist korrekt?',
      options: [
        'Frau Schulz unsere Direktorin begrüßte die Gäste.',
        'Frau Schulz, unsere Direktorin begrüßte die Gäste.',
        'Frau Schulz, unsere Direktorin, begrüßte die Gäste.',
        'Frau Schulz unsere, Direktorin, begrüßte die Gäste.',
      ],
      correct: [2],
      explanation: 'Die Apposition "unsere Direktorin" muss beidseitig durch Kommas eingeschlossen werden.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'In welchem Satz ist die Verwendung des Doppelpunkts korrekt?',
      options: [
        'Er hatte drei Wünsche: Gesundheit, Glück und Erfolg.',
        'Er hatte drei Wünsche, Gesundheit, Glück und Erfolg.',
        'Er hatte drei Wünsche; Gesundheit, Glück und Erfolg.',
        'Er hatte drei Wünsche – Gesundheit. Glück und Erfolg.',
      ],
      correct: [0],
      explanation: 'Vor einer Aufzählung steht ein Doppelpunkt, wenn sie angekündigt wird. Komma oder Semikolon wären hier falsch.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welcher Satz mit direkter Rede ist korrekt gesetzt?',
      options: [
        '"Ich komme morgen" sagte sie.',
        '„Ich komme morgen", sagte sie.',
        '„Ich komme morgen" sagte sie.',
        '"Ich komme morgen," sagte sie.',
      ],
      correct: [1],
      explanation: 'Die direkte Rede steht in deutschen Anführungszeichen (unten-oben: „…"). Nach dem schließenden Anführungszeichen folgt ein Komma, bevor der Begleitsatz beginnt.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welches Satzzeichen steht korrekt vor der direkten Rede?',
      options: [
        'Sie sagte, "Ich bin müde."',
        'Sie sagte: „Ich bin müde."',
        'Sie sagte; „Ich bin müde."',
        'Sie sagte – „Ich bin müde,"',
      ],
      correct: [1],
      explanation: 'Vor der eingeleiteten direkten Rede steht ein Doppelpunkt. Komma oder Semikolon sind falsch. Die deutschen Anführungszeichen („…") sind korrekt.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welcher Satz ist korrekt, wenn "weil" einen Nebensatz einleitet?',
      options: [
        'Er blieb zuhause weil er krank war.',
        'Er blieb zuhause, weil er krank war.',
        'Er blieb, zuhause weil er krank war.',
        'Er blieb zuhause weil, er krank war.',
      ],
      correct: [1],
      explanation: '"Weil" leitet einen Nebensatz ein. Dieser wird durch ein Komma vom Hauptsatz abgetrennt: vor "weil".',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welcher Satz mit "obwohl" ist korrekt interpunktiert?',
      options: [
        'Obwohl es regnete, gingen wir spazieren.',
        'Obwohl es regnete gingen wir spazieren.',
        'Obwohl, es regnete, gingen wir spazieren.',
        'Obwohl es regnete; gingen wir spazieren.',
      ],
      correct: [0],
      explanation: 'Der mit "obwohl" eingeleitete Nebensatz wird durch ein Komma vom Hauptsatz getrennt. Steht er voran, folgt das Komma nach dem Nebensatz.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'In welchem Satz fehlt ein notwendiges Komma?',
      options: [
        'Ich weiß, dass du recht hast.',
        'Der Mann, der dort steht, ist mein Onkel.',
        'Sie fragte ob er mitkommen wolle.',
        'Er aß, obwohl er keinen Hunger hatte.',
      ],
      correct: [2],
      explanation: '"Ob" leitet einen indirekten Fragesatz (Nebensatz) ein. Vor "ob" muss ein Komma stehen: "Sie fragte, ob er mitkommen wolle."',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welche Aussage zur Kommasetzung bei "und" ist korrekt?',
      options: [
        'Vor "und" steht immer ein Komma.',
        'Vor "und" steht nie ein Komma.',
        'Vor "und" kann ein Komma stehen, wenn es zwei vollständige Hauptsätze verbindet.',
        'Vor "und" steht nur ein Komma, wenn danach ein Adjektiv folgt.',
      ],
      correct: [2],
      explanation: 'Vor "und" ist ein Komma optional, wenn zwei vollständige Hauptsätze verbunden werden. Es ist nicht vorgeschrieben, aber zulässig.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welcher Satz mit Einschub ist korrekt interpunktiert?',
      options: [
        'Er war wie ich später erfuhr schon lange krank.',
        'Er war, wie ich später erfuhr schon lange krank.',
        'Er war, wie ich später erfuhr, schon lange krank.',
        'Er war wie, ich später erfuhr, schon lange krank.',
      ],
      correct: [2],
      explanation: 'Der Einschub "wie ich später erfuhr" muss beidseitig durch Kommas eingeschlossen werden.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welches Satzzeichen trennt zwei Hauptsätze mit inhaltlichem Zusammenhang, wenn einer davon bereits Kommas enthält?',
      options: [
        'Komma',
        'Doppelpunkt',
        'Semikolon',
        'Gedankenstrich',
      ],
      correct: [2],
      explanation: 'Das Semikolon eignet sich besonders, wenn Hauptsätze inhaltlich zusammengehören und einer davon bereits Kommas enthält, um die Gliederung zu verdeutlichen.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welcher Satz mit Aufzählung ist korrekt?',
      options: [
        'Ich mag Äpfel, Birnen, Bananen, und Kirschen.',
        'Ich mag Äpfel, Birnen, Bananen und Kirschen.',
        'Ich mag Äpfel Birnen Bananen und Kirschen.',
        'Ich mag Äpfel, Birnen, Bananen; und Kirschen.',
      ],
      correct: [1],
      explanation: 'Bei Aufzählungen steht zwischen den Gliedern ein Komma, aber nicht vor dem abschließenden "und". Das Semikolon vor "und" ist falsch.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welche Aussage zu deutschen Anführungszeichen ist richtig?',
      options: [
        'Im Deutschen öffnet man mit " (oben) und schließt mit " (oben).',
        'Im Deutschen öffnet man mit „ (unten) und schließt mit " (oben).',
        'Im Deutschen öffnet man mit « und schließt mit ».',
        'Im Deutschen gibt es keine festgelegte Form für Anführungszeichen.',
      ],
      correct: [1],
      explanation: 'Die korrekte deutsche Form ist: öffnendes Anführungszeichen unten „ und schließendes oben ". Beispiel: „Guten Morgen."',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welcher Satz mit "wenn" ist korrekt?',
      options: [
        'Wenn es schneit bleiben wir drinnen.',
        'Wenn es schneit, bleiben wir drinnen.',
        'Wenn, es schneit, bleiben wir drinnen.',
        'Wenn es schneit; bleiben wir drinnen.',
      ],
      correct: [1],
      explanation: 'Der mit "wenn" eingeleitete Nebensatz wird durch ein Komma vom folgenden Hauptsatz getrennt. Das Komma steht nach dem Nebensatz.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welcher Satz mit nachgestelltem Nebensatz ist korrekt?',
      options: [
        'Wir essen gleich, weil wir Hunger haben.',
        'Wir essen gleich weil wir Hunger haben.',
        'Wir essen, gleich weil wir Hunger haben.',
        'Wir essen gleich; weil wir Hunger haben.',
      ],
      correct: [0],
      explanation: 'Vor dem nachgestellten Nebensatz mit "weil" steht ein Komma. Semikolon wäre falsch, da "weil" einen Nebensatz einleitet, keinen Hauptsatz.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welcher Satz enthält einen korrekten Doppelpunkt vor einer Erklärung?',
      options: [
        'Das Ergebnis war eindeutig, er hatte gewonnen.',
        'Das Ergebnis war eindeutig: Er hatte gewonnen.',
        'Das Ergebnis war eindeutig; Er hatte gewonnen.',
        'Das Ergebnis war eindeutig – er hatte, gewonnen.',
      ],
      correct: [1],
      explanation: 'Der Doppelpunkt kündigt eine Erklärung an. Da ein vollständiger Satz folgt, wird das erste Wort großgeschrieben.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welcher Satz mit "ohne zu" ist korrekt interpunktiert?',
      options: [
        'Er ging weg ohne sich zu verabschieden.',
        'Er ging weg, ohne sich zu verabschieden.',
        'Er ging, weg ohne sich zu verabschieden.',
        'Er ging weg ohne, sich zu verabschieden.',
      ],
      correct: [1],
      explanation: 'Infinitivgruppen mit "ohne … zu" werden immer durch Komma abgetrennt. Das Komma steht vor "ohne".',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Wo steht das Komma bei vorangestelltem Nebensatz?',
      options: [
        'Am Ende des gesamten Satzes.',
        'Am Anfang des Nebensatzes.',
        'Am Ende des Nebensatzes, vor dem Hauptsatz.',
        'Zwischen Subjekt und Prädikat des Hauptsatzes.',
      ],
      correct: [2],
      explanation: 'Steht der Nebensatz vor dem Hauptsatz, wird er durch ein Komma abgeschlossen: "Als er ankam, war es bereits dunkel." – das Komma steht nach "ankam".',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welcher Satz mit zwei Adjektiven ist korrekt?',
      options: [
        'Sie trug ein langes rotes Kleid.',
        'Sie trug ein langes, rotes Kleid.',
        'Sie trug ein, langes rotes Kleid.',
        'Beide Varianten A und B sind korrekt.',
      ],
      correct: [3],
      explanation: 'Bei gleichrangigen Adjektiven kann ein Komma stehen ("ein langes, rotes Kleid") oder nicht. Beide Varianten sind akzeptabel. Gleichrangigkeit prüft man durch Einfügen von "und": "ein langes und rotes Kleid" klingt sinnvoll.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Welcher Satz mit indirekter Rede ist korrekt?',
      options: [
        'Er fragte ob sie mitkommen würde.',
        'Er fragte, ob sie mitkommen würde.',
        'Er fragte: ob sie mitkommen würde.',
        'Er fragte; ob sie mitkommen würde.',
      ],
      correct: [1],
      explanation: '"Ob" leitet einen Nebensatz (indirekte Frage) ein. Vor "ob" steht ein Komma. Doppelpunkt oder Semikolon wären falsch.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Wie lautet die korrekte Interpunktion? "Sie bat ihn ___ ihr zu helfen."',
      options: [
        'Sie bat ihn ihr zu helfen.',
        'Sie bat ihn, ihr zu helfen.',
        'Sie bat, ihn ihr zu helfen.',
        'Sie bat ihn; ihr zu helfen.',
      ],
      correct: [1],
      explanation: 'Der Infinitiv "ihr zu helfen" hängt von "bat" ab und ist erweitert. Da er von einem Verb abhängt, das den Infinitiv regiert, ist das Komma möglich und üblich zur Verdeutlichung.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Welche Aussage zum Semikolon ist korrekt?',
      options: [
        'Das Semikolon ersetzt immer den Punkt.',
        'Das Semikolon steht zwischen Haupt- und Nebensatz.',
        'Das Semikolon trennt gleichrangige Sätze oder Aufzählungsglieder mit internen Kommas.',
        'Das Semikolon steht nur vor "und" und "oder".',
      ],
      correct: [2],
      explanation: 'Das Semikolon verbindet gleichrangige, zusammengehörende Hauptsätze oder gliedert Aufzählungen, deren Teile selbst Kommas enthalten.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welcher Satz ist korrekt, wenn eine direkte Frage in die direkte Rede eingebettet ist?',
      options: [
        'Er rief: „Wo bist du?", und wartete.',
        'Er rief: „Wo bist du?" und wartete.',
        'Er rief: „Wo bist du." und wartete.',
        'Er rief „Wo bist du?" und wartete.',
      ],
      correct: [1],
      explanation: 'Nach einem Fragezeichen am Ende der direkten Rede entfällt das Komma vor dem Begleitsatz. Der Doppelpunkt vor der direkten Rede ist korrekt.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Welcher Satz mit "als" als Vergleich ist korrekt?',
      options: [
        'Er ist größer, als sein Bruder.',
        'Er ist größer als sein Bruder.',
        'Er ist größer; als sein Bruder.',
        'Er ist größer: als sein Bruder.',
      ],
      correct: [1],
      explanation: 'Bei einem einfachen Vergleich ohne Verb steht kein Komma vor "als". Nur wenn "als" einen vollständigen Vergleichssatz einleitet, wird ein Komma gesetzt.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welcher Satz mit "sowohl … als auch" ist korrekt?',
      options: [
        'Sowohl Anna, als auch Bernd kamen.',
        'Sowohl Anna als auch, Bernd kamen.',
        'Sowohl Anna als auch Bernd kamen.',
        'Sowohl, Anna als auch Bernd kamen.',
      ],
      correct: [2],
      explanation: 'Die zweiteilige Konjunktion "sowohl … als auch" verbindet gleichrangige Glieder ohne Komma. Es steht kein Komma zwischen den verbundenen Teilen.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welcher Satz mit eingeschobenem Relativsatz ist korrekt?',
      options: [
        'Die Frau die ich gestern traf war sehr freundlich.',
        'Die Frau, die ich gestern traf war sehr freundlich.',
        'Die Frau, die ich gestern traf, war sehr freundlich.',
        'Die Frau die ich gestern traf, war sehr freundlich.',
      ],
      correct: [2],
      explanation: 'Der eingeschobene Relativsatz "die ich gestern traf" muss beidseitig durch Kommas abgetrennt werden.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welcher Satz enthält einen Fehler bei der direkten Rede?',
      options: [
        '„Komm bitte her", sagte sie leise.',
        '„Komm bitte her!", rief sie laut.',
        '„Kommst du?", fragte er.',
        '„Ich weiß es nicht." sagte er nachdenklich.',
      ],
      correct: [3],
      explanation: 'Nach dem schließenden Anführungszeichen (wenn die direkte Rede mit einem Punkt endet) steht ein Komma vor dem Begleitsatz: „Ich weiß es nicht.", sagte er nachdenklich.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Was gilt für den Doppelpunkt nach einer vollständigen Einleitung vor einer Aufzählung?',
      options: [
        'Nach dem Doppelpunkt schreibt man immer groß.',
        'Nach dem Doppelpunkt schreibt man immer klein.',
        'Nach dem Doppelpunkt schreibt man groß, wenn ein vollständiger Satz folgt; klein bei unvollständigen Aufzählungsgliedern.',
        'Der Doppelpunkt wird in Aufzählungen nicht verwendet.',
      ],
      correct: [2],
      explanation: 'Nach einem Doppelpunkt wird großgeschrieben, wenn ein vollständiger Satz folgt. Folgen unvollständige Aufzählungsglieder, schreibt man klein.',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Welcher Satz mit "anstatt zu" ist korrekt interpunktiert?',
      options: [
        'Er spielte anstatt zu lernen.',
        'Er spielte, anstatt zu lernen.',
        'Er spielte anstatt, zu lernen.',
        'Er spielte: anstatt zu lernen.',
      ],
      correct: [1],
      explanation: 'Infinitivgruppen mit "anstatt … zu" werden immer durch Komma abgetrennt. Das Komma steht vor "anstatt".',
      difficulty: 2,
    },
    {
      type: 'truefalse',
      prompt: 'Vor "und" steht in einer Aufzählung kein Komma.',
      options: ['Richtig', 'Falsch'],
      correct: [0],
      explanation: 'In einer Aufzählung steht vor dem abschließenden "und" kein Komma: "Äpfel, Birnen und Kirschen."',
      difficulty: 1,
    },
    {
      type: 'truefalse',
      prompt: 'Ein Relativsatz kann ohne Kommas in den Satz eingebettet werden.',
      options: ['Richtig', 'Falsch'],
      correct: [1],
      explanation: 'Relativsätze werden immer durch Kommas vom restlichen Satz abgetrennt. Sie können nicht ohne Kommas stehen.',
      difficulty: 1,
    },
    {
      type: 'truefalse',
      prompt: 'Nach einem Ausrufezeichen am Ende der direkten Rede steht kein weiteres Komma vor dem Begleitsatz.',
      options: ['Richtig', 'Falsch'],
      correct: [0],
      explanation: '"Komm sofort!", rief er. – Nach Ausrufe- oder Fragezeichen entfällt das Komma. Der Begleitsatz beginnt direkt nach dem Anführungszeichen.',
      difficulty: 2,
    },
    {
      type: 'truefalse',
      prompt: 'Das Semikolon kann zwischen zwei Hauptsätzen stehen, die thematisch zusammengehören.',
      options: ['Richtig', 'Falsch'],
      correct: [0],
      explanation: 'Das Semikolon ist genau für diesen Zweck gedacht: Es verbindet zwei gleichrangige Hauptsätze, die inhaltlich eng zusammengehören.',
      difficulty: 1,
    },
    {
      type: 'fill',
      prompt: 'Ergänzen Sie das fehlende Satzzeichen: "Er sagte ___ Ich komme morgen."',
      correct: [':'],
      explanation: 'Vor der direkten Rede steht ein Doppelpunkt, wenn sie durch einen vollständigen Begleitsatz eingeleitet wird.',
      difficulty: 1,
    },
    {
      type: 'fill',
      prompt: 'Wie heißt das öffnende deutsche Anführungszeichen (das unten steht)? Geben Sie das Zeichen ein.',
      correct: ['„'],
      explanation: 'Das öffnende deutsche Anführungszeichen steht unten: „. Das schließende steht oben: ".',
      difficulty: 1,
    },
    {
      type: 'fill',
      prompt: 'Welches Satzzeichen steht typischerweise vor einer angekündigten Aufzählung? (Schreiben Sie das Zeichen)',
      correct: [':'],
      explanation: 'Vor einer angekündigten Aufzählung steht ein Doppelpunkt. Beispiel: "Ich brauche Folgendes: Stift, Papier und Lineal."',
      difficulty: 1,
    },
  ],
};

export default topic;
