import type { RawTopic } from '../types';

const topic: RawTopic = {
  slug: 'zeitformen',
  title: 'Zeitformen & Verben',
  description: 'Die sechs Zeitformen, starke/schwache Verben, Perfekt mit haben/sein.',
  flashcards: [
    {
      front: 'Was sind die sechs Zeitformen im Deutschen?',
      back: 'Präsens, Präteritum, Perfekt, Plusquamperfekt, Futur I, Futur II.',
    },
    {
      front: 'Wie wird das Präsens gebildet?',
      back: 'Verbstamm + Personalendung (ich lerne, du lernst, er/sie/es lernt, wir lernen, ihr lernt, sie/Sie lernen).',
    },
    {
      front: 'Wie wird das Präteritum schwacher Verben gebildet?',
      back: 'Verbstamm + -te + Personalendung (ich lernte, du lerntest, er lernte ...).',
    },
    {
      front: 'Wie wird das Perfekt gebildet?',
      back: 'Hilfsverb "haben" oder "sein" im Präsens + Partizip II des Vollverbs (ich habe gelernt / ich bin gegangen).',
    },
    {
      front: 'Wie wird das Plusquamperfekt gebildet?',
      back: 'Hilfsverb "haben" oder "sein" im Präteritum + Partizip II (ich hatte gelernt / ich war gegangen).',
    },
    {
      front: 'Wie wird Futur I gebildet?',
      back: '"werden" im Präsens + Infinitiv des Vollverbs (ich werde lernen).',
    },
    {
      front: 'Wie wird Futur II gebildet?',
      back: '"werden" im Präsens + Partizip II + "haben" oder "sein" (ich werde gelernt haben / ich werde gegangen sein).',
    },
    {
      front: 'Was ist ein schwaches Verb?',
      back: 'Ein regelmäßiges Verb, das den Stamm nicht ändert. Präteritum mit -te, Partizip II mit ge-...-t (lernen – lernte – gelernt).',
    },
    {
      front: 'Was ist ein starkes Verb?',
      back: 'Ein unregelmäßiges Verb mit Stammvokalwechsel. Partizip II endet meist auf -en (fahren – fuhr – gefahren).',
    },
    {
      front: 'Welche Verben bilden das Perfekt mit "sein"?',
      back: 'Bewegungsverben (gehen, fahren, laufen), Zustandsveränderungen (aufwachen, sterben, wachsen) und: sein, bleiben, werden.',
    },
    {
      front: 'Wie lautet das Partizip II von "gehen"?',
      back: '"gegangen" (unregelmäßig; Perfekt: ich bin gegangen).',
    },
    {
      front: 'Wie lautet die Vergangenheitsform von "sein"?',
      back: 'Präteritum: ich war, du warst, er/sie/es war, wir waren, ihr wart, sie/Sie waren.',
    },
    {
      front: 'Wie lauten die drei Grundformen von "haben"?',
      back: 'haben – hatte – gehabt.',
    },
    {
      front: 'Wie lauten die drei Grundformen von "werden"?',
      back: 'werden – wurde – geworden.',
    },
    {
      front: 'Wie lauten die drei Grundformen von "gehen"?',
      back: 'gehen – ging – gegangen.',
    },
    {
      front: 'Was drückt das Plusquamperfekt aus?',
      back: 'Eine Handlung, die vor einer anderen Vergangenheitshandlung abgeschlossen war (Vorvergangenheit). Beispiel: "Er hatte gegessen, bevor sie ankam."',
    },
    {
      front: 'Perfekt von "gehen" (ich) – wie lautet die Form?',
      back: '"ich bin gegangen" – "gehen" ist ein Bewegungsverb und bildet Perfekt mit "sein".',
    },
    {
      front: 'In welcher Zeitform steht "er wird gelaufen sein"?',
      back: 'Futur II – es beschreibt eine zukünftige Handlung, die zu einem bestimmten Zeitpunkt abgeschlossen sein wird.',
    },
    {
      front: 'Was ist der Unterschied zwischen Perfekt und Präteritum in der Alltagssprache?',
      back: 'Im gesprochenen Deutsch wird für vergangene Ereignisse meist das Perfekt verwendet; das Präteritum ist eher schriftsprachlich und bei Hilfsverben (war, hatte) üblich.',
    },
    {
      front: 'Wie lautet das Partizip II von "schreiben"?',
      back: '"geschrieben" (starkes Verb; Stammvokalwechsel ei → ie).',
    },
  ],
  questions: [
    {
      type: 'mc',
      prompt: 'In welcher Zeitform steht der Satz "Er hatte das Buch gelesen, bevor sie ankam"?',
      options: ['Perfekt', 'Präteritum', 'Plusquamperfekt', 'Futur II'],
      correct: [2],
      explanation: 'Das Plusquamperfekt (hatte ... gelesen) drückt eine Handlung aus, die vor einer anderen vergangenen Handlung abgeschlossen war.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Wie lautet das Perfekt von "gehen" in der 1. Person Singular?',
      options: ['ich habe gegangen', 'ich bin gegangen', 'ich hatte gegangen', 'ich werde gegangen sein'],
      correct: [1],
      explanation: '"Gehen" ist ein Bewegungsverb und bildet das Perfekt mit dem Hilfsverb "sein": ich bin gegangen.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welches Hilfsverb wird für das Perfekt von "schlafen" verwendet?',
      options: ['sein', 'werden', 'haben', 'bleiben'],
      correct: [2],
      explanation: '"Schlafen" ist kein Bewegungs- oder Zustandsveränderungsverb und bildet das Perfekt daher mit "haben": ich habe geschlafen.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'In welcher Zeitform steht "sie wird morgen kommen"?',
      options: ['Präsens', 'Futur II', 'Präteritum', 'Futur I'],
      correct: [3],
      explanation: 'Futur I wird mit "werden" + Infinitiv gebildet und drückt eine zukünftige Handlung aus.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welche Form ist das Präteritum von "sein" in der 3. Person Singular?',
      options: ['ist', 'sei', 'war', 'wäre'],
      correct: [2],
      explanation: 'Das Präteritum von "sein" lautet: ich war, du warst, er/sie/es war.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Wie lautet das Partizip II von "fahren"?',
      options: ['gefahrt', 'gefahren', 'fuhr', 'geführt'],
      correct: [1],
      explanation: '"Fahren" ist ein starkes Verb. Das Partizip II lautet "gefahren" (Stammvokalwechsel a → a, Endung -en).',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Was ist ein starkes Verb?',
      options: [
        'Ein Verb, das im Präteritum -te anhängt',
        'Ein Verb mit Stammvokalwechsel in der Vergangenheitsform',
        'Ein Verb, das immer mit "sein" das Perfekt bildet',
        'Ein Verb ohne Partizip II',
      ],
      correct: [1],
      explanation: 'Starke Verben ändern den Stammvokal in der Vergangenheit (z. B. fahren – fuhr – gefahren) und haben kein regelmäßiges -te im Präteritum.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welche Zeitform drückt eine Handlung aus, die in der Zukunft bereits abgeschlossen sein wird?',
      options: ['Futur I', 'Perfekt', 'Futur II', 'Plusquamperfekt'],
      correct: [2],
      explanation: 'Futur II (z. B. "ich werde gegangen sein") beschreibt eine zukünftige Handlung, die zu einem bestimmten Zeitpunkt abgeschlossen sein wird.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Wie wird Futur II gebildet?',
      options: [
        '"werden" + Infinitiv',
        '"haben/sein" im Präteritum + Partizip II',
        '"werden" + Partizip II + "haben" oder "sein"',
        '"haben/sein" im Präsens + Infinitiv',
      ],
      correct: [2],
      explanation: 'Futur II = "werden" im Präsens + Partizip II + "haben" oder "sein" (z. B. "ich werde gelernt haben").',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Welches Verb bildet sein Perfekt mit "sein"?',
      options: ['lernen', 'kaufen', 'lesen', 'aufwachen'],
      correct: [3],
      explanation: '"Aufwachen" bezeichnet eine Zustandsveränderung und bildet daher das Perfekt mit "sein": ich bin aufgewacht.',
      difficulty: 2,
    },
    {
      type: 'truefalse',
      prompt: '"Ich habe geschlafen" ist eine korrekte Perfektform.',
      options: ['Richtig', 'Falsch'],
      correct: [0],
      explanation: '"Schlafen" bildet das Perfekt mit "haben". "Ich habe geschlafen" ist grammatisch korrekt.',
      difficulty: 1,
    },
    {
      type: 'truefalse',
      prompt: '"Ich bin gefahren" ist falsch, weil "fahren" das Perfekt mit "haben" bildet.',
      options: ['Richtig', 'Falsch'],
      correct: [1],
      explanation: '"Fahren" ist ein Bewegungsverb und bildet das Perfekt mit "sein": ich bin gefahren – die Aussage ist also falsch.',
      difficulty: 2,
    },
    {
      type: 'truefalse',
      prompt: 'Das Plusquamperfekt wird mit "haben" oder "sein" im Präteritum + Partizip II gebildet.',
      options: ['Richtig', 'Falsch'],
      correct: [0],
      explanation: 'Korrekt: Plusquamperfekt = Hilfsverb (hatte/war) + Partizip II (z. B. ich hatte gelernt, ich war gegangen).',
      difficulty: 2,
    },
    {
      type: 'truefalse',
      prompt: '"Werden – wurde – geworden" sind die drei Grundformen des Verbs "werden".',
      options: ['Richtig', 'Falsch'],
      correct: [0],
      explanation: 'Die drei Grundformen (Infinitiv, Präteritum, Partizip II) von "werden" lauten: werden – wurde – geworden.',
      difficulty: 1,
    },
    {
      type: 'truefalse',
      prompt: 'Schwache Verben haben im Präteritum immer einen Stammvokalwechsel.',
      options: ['Richtig', 'Falsch'],
      correct: [1],
      explanation: 'Stammvokalwechsel ist ein Merkmal starker Verben. Schwache (regelmäßige) Verben ändern den Stammvokal nicht, sondern hängen -te an (lernte, kaufte).',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welche Zeitform wird im folgenden Satz verwendet? "Als sie ankam, hatten wir schon gegessen."',
      options: ['Perfekt', 'Präteritum', 'Plusquamperfekt', 'Futur I'],
      correct: [2],
      explanation: '"Hatten ... gegessen" ist Plusquamperfekt (hatten + Partizip II) und beschreibt die Vorvergangenheit.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welche Endung erhält das Partizip II schwacher Verben?',
      options: ['-en', '-te', '-t (mit ge- Vorsilbe)', '-end'],
      correct: [2],
      explanation: 'Schwache Verben bilden das Partizip II mit ge- + Stamm + -t (z. B. ge-lern-t, ge-kauf-t).',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welches ist das Präteritum von "gehen" in der 3. Person Singular?',
      options: ['geht', 'gegangen', 'ginge', 'ging'],
      correct: [3],
      explanation: 'Das Präteritum von "gehen" lautet "ging" (starkes Verb mit Stammvokalwechsel).',
      difficulty: 1,
    },
    {
      type: 'fill',
      prompt: 'Ergänzen Sie: "Gestern ___ ich ins Kino gegangen." (Präteritum von "sein")',
      correct: ['bin', 'war'],
      explanation: 'Im Perfekt: "ich bin gegangen" (Hilfsverb "sein" im Präsens). Im Präteritum wäre der Satz "ich war ... gegangen" (Plusquamperfekt). Da "gegangen" das Partizip II ist und das Hilfsverb im Präsens steht, lautet die Antwort "bin".',
      difficulty: 2,
    },
    {
      type: 'fill',
      prompt: 'Das Partizip II von "schreiben" lautet: ___',
      correct: ['geschrieben'],
      explanation: '"Schreiben" ist ein starkes Verb (schreiben – schrieb – geschrieben). Das Partizip II lautet "geschrieben".',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'In welcher Zeitform steht "er wird gelaufen sein"?',
      options: ['Futur I', 'Perfekt', 'Plusquamperfekt', 'Futur II'],
      correct: [3],
      explanation: '"Wird ... gelaufen sein" ist Futur II: werden (Präsens) + Partizip II + sein. Es drückt eine zum Sprechzeitpunkt noch ausstehende, aber zukünftig abgeschlossene Handlung aus.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welche Aussage über "bleiben" ist korrekt?',
      options: [
        '"Bleiben" bildet das Perfekt mit "haben".',
        '"Bleiben" ist ein schwaches Verb.',
        '"Bleiben" bildet das Perfekt mit "sein".',
        '"Bleiben" hat kein Partizip II.',
      ],
      correct: [2],
      explanation: '"Bleiben" gehört zu den Verben, die trotz fehlender Bewegung das Perfekt mit "sein" bilden: ich bin geblieben.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welche der folgenden Formen ist ein korrektes Futur I?',
      options: ['ich werde gegangen', 'ich werde gehen', 'ich bin gegangen', 'ich wurde gehen'],
      correct: [1],
      explanation: 'Futur I = "werden" im Präsens + Infinitiv. Korrekt: "ich werde gehen".',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Wie lautet das Partizip II von "haben"?',
      options: ['gehabt', 'hatte', 'gehaben', 'gehat'],
      correct: [0],
      explanation: 'Das Partizip II von "haben" lautet "gehabt". Die drei Grundformen sind: haben – hatte – gehabt.',
      difficulty: 1,
    },
    {
      type: 'truefalse',
      prompt: '"Futur I" wird mit "werden" im Präsens und dem Partizip II gebildet.',
      options: ['Richtig', 'Falsch'],
      correct: [1],
      explanation: 'Futur I wird mit "werden" + Infinitiv gebildet (ich werde lernen), nicht mit dem Partizip II. Partizip II wird im Futur II verwendet.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welches Verb ist ein starkes Verb?',
      options: ['lernen', 'kaufen', 'singen', 'wohnen'],
      correct: [2],
      explanation: '"Singen" ist ein starkes Verb: singen – sang – gesungen (Stammvokalwechsel i → a). Die anderen Verben sind schwach (regelmäßig).',
      difficulty: 1,
    },
    {
      type: 'fill',
      prompt: 'Ergänzen Sie die Grundformen: "laufen – ___ – gelaufen"',
      correct: ['lief'],
      explanation: '"Laufen" ist ein starkes Verb. Die drei Grundformen lauten: laufen – lief – gelaufen.',
      difficulty: 2,
    },
    {
      type: 'mc',
      prompt: 'Welche Zeitform verwendet man, um ein vergangenes Ereignis im gesprochenen Deutsch auszudrücken?',
      options: ['Präteritum', 'Futur I', 'Perfekt', 'Plusquamperfekt'],
      correct: [2],
      explanation: 'Im gesprochenen Deutsch wird für vergangene Ereignisse überwiegend das Perfekt gebraucht (z. B. "Ich habe gestern gelernt").',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Wie lautet die korrekte Plusquamperfektform von "lernen" (ich)?',
      options: ['ich habe gelernt', 'ich war gelernt', 'ich hatte gelernt', 'ich werde gelernt haben'],
      correct: [2],
      explanation: 'Plusquamperfekt = Hilfsverb im Präteritum + Partizip II. Da "lernen" mit "haben" bildet: ich hatte gelernt.',
      difficulty: 2,
    },
    {
      type: 'truefalse',
      prompt: '"Sein", "bleiben" und "werden" bilden ihr Perfekt stets mit "sein".',
      options: ['Richtig', 'Falsch'],
      correct: [0],
      explanation: 'Korrekt: Diese drei Verben bilden das Perfekt mit "sein" (ich bin gewesen, ich bin geblieben, ich bin geworden).',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Welche Zeitform steht im Satz "Sie lernt jeden Tag Vokabeln"?',
      options: ['Präteritum', 'Perfekt', 'Präsens', 'Futur I'],
      correct: [2],
      explanation: '"Lernt" ist die Präsensform (3. Person Singular). Das Präsens beschreibt gegenwärtige oder regelmäßige Handlungen.',
      difficulty: 1,
    },
    {
      type: 'fill',
      prompt: 'Ergänzen Sie: "Bis morgen Abend werde ich das Buch gelesen ___." (Futur II)',
      correct: ['haben'],
      explanation: 'Futur II mit "lesen" (Perfekt mit "haben"): ich werde gelesen haben. Das fehlende Wort ist "haben".',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Welche Form ist das Präteritum von "haben" in der 1. Person Singular?',
      options: ['habe', 'gehabt', 'hatte', 'hätte'],
      correct: [2],
      explanation: 'Das Präteritum von "haben" lautet: ich hatte, du hattest, er/sie/es hatte. "Hätte" ist der Konjunktiv II.',
      difficulty: 1,
    },
    {
      type: 'mc',
      prompt: 'Welches Partizip II ist korrekt gebildet?',
      options: ['gespringt', 'gespring', 'gesprungen', 'gespringen'],
      correct: [2],
      explanation: '"Springen" ist ein starkes Verb: springen – sprang – gesprungen. Das Partizip II lautet "gesprungen".',
      difficulty: 2,
    },
    {
      type: 'truefalse',
      prompt: 'Das Futur II kann auch eine Vermutung über die Vergangenheit ausdrücken (z. B. "Er wird das Buch gelesen haben").',
      options: ['Richtig', 'Falsch'],
      correct: [0],
      explanation: 'Ja, Futur II drückt neben der vollendeten Zukunft auch Vermutungen über die Vergangenheit aus (epistemische Modalität).',
      difficulty: 3,
    },
    {
      type: 'mc',
      prompt: 'Welches Verb bildet sein Perfekt mit "haben"?',
      options: ['sterben', 'fallen', 'reisen', 'lachen'],
      correct: [3],
      explanation: '"Lachen" ist kein Bewegungsverb und keine Zustandsveränderung – es bildet das Perfekt mit "haben": ich habe gelacht.',
      difficulty: 2,
    },
  ],
};

export default topic;
