import type { RawFlashcard, RawQuestion } from '../types';

const supplement: { flashcards: RawFlashcard[]; questions: RawQuestion[] } = {
  flashcards: [
    { front: "Wer ist Bundeskanzler (Stand 2026)?", back: "Friedrich Merz (CDU, seit 6. Mai 2025)" },
    { front: "Wer ist Bundespraesident (Stand 2026)?", back: "Frank-Walter Steinmeier (SPD, Amtszeit bis 2027)" },
    { front: "Wer ist Bundestagspraesidentin (Stand 2026)?", back: "Julia Kloeckner (CDU)" },
    { front: "Wer ist Praesident des Bundesverfassungsgerichts (Stand 2026)?", back: "Stephan Harbarth" },
    { front: "Wer ist Ministerpraesidentin des Saarlandes (Stand 2026)?", back: "Anke Rehlinger (SPD)" },
    { front: "Wer ist EU-Kommissionspraesidentin (Stand 2026)?", back: "Ursula von der Leyen (seit Dezember 2024 in ihrer 2. Amtszeit)" },
    { front: "Wer ist Praesident des Europaeischen Rates (Stand 2026)?", back: "Antonio Costa" },
    { front: "Wer ist EU-Parlamentspraesidentin (Stand 2026)?", back: "Roberta Metsola" },
    { front: "Wer ist NATO-Generalsekretaer (Stand 2026)?", back: "Mark Rutte (NATO hat 32 Mitglieder)" },
    { front: "Wer ist UN-Generalsekretaer (Stand 2026)?", back: "Antonio Guterres" },
    { front: "Wer ist US-Praesident (Stand 2026)?", back: "Donald Trump (seit Januar 2025)" },
  ],
  questions: [
    {
      type: "mc",
      prompt: "Wer ist seit dem 6. Mai 2025 Bundeskanzler der Bundesrepublik Deutschland?",
      options: ["Olaf Scholz", "Friedrich Merz", "Robert Habeck", "Christian Lindner"],
      correct: [1],
      explanation: "Friedrich Merz (CDU) ist seit dem 6. Mai 2025 Bundeskanzler der Bundesrepublik Deutschland.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Welcher Partei gehoert Bundespraesident Frank-Walter Steinmeier an?",
      options: ["CDU", "FDP", "SPD", "Gruene"],
      correct: [2],
      explanation: "Frank-Walter Steinmeier gehoert der SPD an. Seine Amtszeit laeuft bis 2027.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Wer ist Bundestagspraesidentin (Stand 2026)?",
      options: ["Katrin Goering-Eckardt", "Baerbel Bas", "Julia Kloeckner", "Annalena Baerbock"],
      correct: [2],
      explanation: "Julia Kloeckner (CDU) ist Bundestagspraesidentin.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Wer ist Praesident des Bundesverfassungsgerichts (Stand 2026)?",
      options: ["Andreas Vosskuhle", "Stephan Harbarth", "Peter Huber", "Doris Koenig"],
      correct: [1],
      explanation: "Stephan Harbarth ist Praesident des Bundesverfassungsgerichts.",
      difficulty: 2,
    },
    {
      type: "mc",
      prompt: "Wer ist Ministerpraesidentin des Saarlandes (Stand 2026)?",
      options: ["Malu Dreyer", "Anke Rehlinger", "Manuela Schwesig", "Hannelore Kraft"],
      correct: [1],
      explanation: "Anke Rehlinger (SPD) ist Ministerpraesidentin des Saarlandes.",
      difficulty: 2,
    },
    {
      type: "mc",
      prompt: "Seit wann befindet sich Ursula von der Leyen in ihrer 2. Amtszeit als EU-Kommissionspraesidentin?",
      options: ["Januar 2024", "Juni 2024", "Dezember 2024", "Maerz 2025"],
      correct: [2],
      explanation: "Ursula von der Leyen begann ihre 2. Amtszeit als EU-Kommissionspraesidentin im Dezember 2024.",
      difficulty: 2,
    },
    {
      type: "mc",
      prompt: "Wer ist Praesident des Europaeischen Rates (Stand 2026)?",
      options: ["Charles Michel", "Antonio Costa", "Donald Tusk", "Herman Van Rompuy"],
      correct: [1],
      explanation: "Antonio Costa ist Praesident des Europaeischen Rates.",
      difficulty: 2,
    },
    {
      type: "mc",
      prompt: "Wer ist Praesidentin des Europaeischen Parlaments (Stand 2026)?",
      options: ["Simone Peter", "Ska Keller", "Roberta Metsola", "Manon Aubry"],
      correct: [2],
      explanation: "Roberta Metsola ist Praesidentin des Europaeischen Parlaments.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Wie viele Mitgliedstaaten hat die NATO (Stand 2026), und wer ist ihr Generalsekretaer?",
      options: ["30 Mitglieder, Jens Stoltenberg", "31 Mitglieder, Jens Stoltenberg", "32 Mitglieder, Mark Rutte", "33 Mitglieder, Mark Rutte"],
      correct: [2],
      explanation: "Die NATO hat 32 Mitglieder. Generalsekretaer ist Mark Rutte.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Wer ist UN-Generalsekretaer (Stand 2026)?",
      options: ["Ban Ki-moon", "Kofi Annan", "Antonio Guterres", "Boutros Boutros-Ghali"],
      correct: [2],
      explanation: "Antonio Guterres ist Generalsekretaer der Vereinten Nationen (UN).",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Wer ist seit Januar 2025 US-Praesident?",
      options: ["Joe Biden", "Kamala Harris", "Ron DeSantis", "Donald Trump"],
      correct: [3],
      explanation: "Donald Trump ist seit Januar 2025 wieder US-Praesident.",
      difficulty: 1,
    },
  ],
};

export default supplement;
