import type { RawFlashcard, RawQuestion } from '../types';

const supplement: { flashcards: RawFlashcard[]; questions: RawQuestion[] } = {
  flashcards: [
    { front: "Wer ist Bundeskanzler (Stand 2026)?", back: "Friedrich Merz (CDU, seit 6. Mai 2025)" },
    { front: "Wer ist Bundespräsident (Stand 2026)?", back: "Frank-Walter Steinmeier (SPD, Amtszeit bis 2027)" },
    { front: "Wer ist Bundestagspräsidentin (Stand 2026)?", back: "Julia Klöckner (CDU)" },
    { front: "Wer ist Präsident des Bundesverfassungsgerichts (Stand 2026)?", back: "Stephan Harbarth" },
    { front: "Wer ist Ministerpräsidentin des Saarlandes (Stand 2026)?", back: "Anke Rehlinger (SPD)" },
    { front: "Wer ist EU-Kommissionspräsidentin (Stand 2026)?", back: "Ursula von der Leyen (seit Dezember 2024 in ihrer 2. Amtszeit)" },
    { front: "Wer ist Präsident des Europäischen Rates (Stand 2026)?", back: "Antonio Costa" },
    { front: "Wer ist EU-Parlamentspräsidentin (Stand 2026)?", back: "Roberta Metsola" },
    { front: "Wer ist NATO-Generalsekretär (Stand 2026)?", back: "Mark Rutte (NATO hat 32 Mitglieder)" },
    { front: "Wer ist UN-Generalsekretär (Stand 2026)?", back: "Antonio Guterres" },
    { front: "Wer ist US-Präsident (Stand 2026)?", back: "Donald Trump (seit Januar 2025)" },
  ],
  questions: [
    {
      type: "mc",
      prompt: "Wer ist seit dem 6. Mai 2025 Bundeskanzler der Bundesrepublik Deutschland?",
      options: ["Olaf Scholz", "Friedrich Merz", "Robert Habeck", "Christian Lindner"],
      correct: [1],
      explanation: "Friedrich Merz (CDU) ist seit dem 6. Mai 2025 Bundeskanzler der Bundesrepublik Deutschland.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Welcher Partei gehört Bundespräsident Frank-Walter Steinmeier an?",
      options: ["CDU", "FDP", "SPD", "Grüne"],
      correct: [2],
      explanation: "Frank-Walter Steinmeier gehört der SPD an. Seine Amtszeit läuft bis 2027.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Wer ist Bundestagspräsidentin (Stand 2026)?",
      options: ["Katrin Goering-Eckardt", "Baerbel Bas", "Julia Klöckner", "Annalena Baerbock"],
      correct: [2],
      explanation: "Julia Klöckner (CDU) ist Bundestagspräsidentin.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Wer ist Präsident des Bundesverfassungsgerichts (Stand 2026)?",
      options: ["Andreas Vosskuhle", "Stephan Harbarth", "Peter Huber", "Doris König"],
      correct: [1],
      explanation: "Stephan Harbarth ist Präsident des Bundesverfassungsgerichts.",
      difficulty: 2,
    },
    {
      type: "mc",
      prompt: "Wer ist Ministerpräsidentin des Saarlandes (Stand 2026)?",
      options: ["Malu Dreyer", "Anke Rehlinger", "Manuela Schwesig", "Hannelore Kraft"],
      correct: [1],
      explanation: "Anke Rehlinger (SPD) ist Ministerpräsidentin des Saarlandes.",
      difficulty: 2,
    },
    {
      type: "mc",
      prompt: "Seit wann befindet sich Ursula von der Leyen in ihrer 2. Amtszeit als EU-Kommissionspräsidentin?",
      options: ["Januar 2024", "Juni 2024", "Dezember 2024", "März 2025"],
      correct: [2],
      explanation: "Ursula von der Leyen begann ihre 2. Amtszeit als EU-Kommissionspräsidentin im Dezember 2024.",
      difficulty: 2,
    },
    {
      type: "mc",
      prompt: "Wer ist Präsident des Europäischen Rates (Stand 2026)?",
      options: ["Charles Michel", "Antonio Costa", "Donald Tusk", "Herman Van Rompuy"],
      correct: [1],
      explanation: "Antonio Costa ist Präsident des Europäischen Rates.",
      difficulty: 2,
    },
    {
      type: "mc",
      prompt: "Wer ist Präsidentin des Europäischen Parlaments (Stand 2026)?",
      options: ["Simone Peter", "Ska Keller", "Roberta Metsola", "Manon Aubry"],
      correct: [2],
      explanation: "Roberta Metsola ist Präsidentin des Europäischen Parlaments.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Wie viele Mitgliedstaaten hat die NATO (Stand 2026), und wer ist ihr Generalsekretär?",
      options: ["30 Mitglieder, Jens Stoltenberg", "31 Mitglieder, Jens Stoltenberg", "32 Mitglieder, Mark Rutte", "33 Mitglieder, Mark Rutte"],
      correct: [2],
      explanation: "Die NATO hat 32 Mitglieder. Generalsekretär ist Mark Rutte.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Wer ist UN-Generalsekretär (Stand 2026)?",
      options: ["Ban Ki-moon", "Kofi Annan", "Antonio Guterres", "Boutros Boutros-Ghali"],
      correct: [2],
      explanation: "Antonio Guterres ist Generalsekretär der Vereinten Nationen (UN).",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Wer ist seit Januar 2025 US-Präsident?",
      options: ["Joe Biden", "Kamala Harris", "Ron DeSantis", "Donald Trump"],
      correct: [3],
      explanation: "Donald Trump ist seit Januar 2025 wieder US-Präsident.",
      difficulty: 1,
    },
  ],
};

export default supplement;
