import type { RawFlashcard, RawQuestion } from '../types';
const supplement: { flashcards: RawFlashcard[]; questions: RawQuestion[] } = {
  flashcards: [
    { front: "effizient", back: "wirkungsvoll" },
    { front: "transparent", back: "durchsichtig, nachvollziehbar" },
    { front: "relevant", back: "wichtig, bedeutsam" },
    { front: "obligatorisch", back: "verpflichtend" },
    { front: "optional", back: "freiwillig" },
    { front: "Prioritaet", back: "Vorrang" },
    { front: "Kompetenz", back: "Faehigkeit, Zustaendigkeit" },
    { front: "Kompromiss", back: "Einigung mit Zugestaendnissen" },
    { front: "praezise", back: "genau, exakt" },
    { front: "Diskrepanz", back: "Widerspruch, Abweichung" },
    { front: "Konsequenz", back: "Folge, Beharrlichkeit" },
    { front: "Initiative", back: "erster Schritt, Tatkraft" },
  ],
  questions: [
    {
      type: "mc",
      prompt: "Was bedeutet das Fremdwort 'effizient'?",
      options: ["verschwenderisch", "wirkungsvoll", "zufallig", "verwirrend"],
      correct: [1],
      explanation: "'Effizient' bedeutet wirkungsvoll, also etwas, das mit moeglichst geringem Aufwand das gewuenschte Ergebnis erzielt.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Welche Bedeutung hat das Wort 'transparent'?",
      options: ["undurchsichtig", "unverstaendlich", "nachvollziehbar", "geheimnisvoll"],
      correct: [2],
      explanation: "'Transparent' bedeutet durchsichtig oder nachvollziehbar, also klar und offen einsehbar.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Was bedeutet 'relevant'?",
      options: ["unwichtig", "selten", "bedeutsam", "veraltet"],
      correct: [2],
      explanation: "'Relevant' bedeutet wichtig oder bedeutsam, also fuer einen bestimmten Zusammenhang von Bedeutung.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Ein obligatorisches Kursangebot ist ...",
      options: ["freiwillig", "kostenlos", "verpflichtend", "empfohlen"],
      correct: [2],
      explanation: "'Obligatorisch' bedeutet verpflichtend, also nicht freiwillig, sondern vorgeschrieben.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Was ist die korrekte Bedeutung von 'optional'?",
      options: ["verpflichtend", "freiwillig", "notwendig", "verboten"],
      correct: [1],
      explanation: "'Optional' bedeutet freiwillig, also etwas, das man machen kann, aber nicht muss.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Was bedeutet das Wort 'Prioritaet'?",
      options: ["Gleichwertigkeit", "Nachrang", "Vorrang", "Zufall"],
      correct: [2],
      explanation: "'Prioritaet' bedeutet Vorrang, also die Einstufung von etwas als besonders wichtig.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Welche Bedeutung hat 'Kompetenz'?",
      options: ["Unwissenheit", "Faehigkeit", "Fehler", "Verwirrung"],
      correct: [1],
      explanation: "'Kompetenz' bezeichnet eine Faehigkeit oder Zustaendigkeit in einem bestimmten Bereich.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Was ist ein Kompromiss?",
      options: ["ein einseitiger Befehl", "eine Einigung mit Zugestaendnissen", "ein absoluter Sieg", "eine Ablehnung"],
      correct: [1],
      explanation: "Ein 'Kompromiss' ist eine Einigung, bei der alle Beteiligten Zugestaendnisse machen.",
      difficulty: 2,
    },
    {
      type: "mc",
      prompt: "Was bedeutet 'praezise'?",
      options: ["ungefaehr", "ungenau", "weitschweifig", "genau"],
      correct: [3],
      explanation: "'Praezise' bedeutet genau oder exakt, also ohne Ungenauigkeiten.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Was bezeichnet eine 'Diskrepanz'?",
      options: ["Uebereinstimmung", "Zusammenarbeit", "Widerspruch", "Anerkennung"],
      correct: [2],
      explanation: "'Diskrepanz' bezeichnet einen Widerspruch oder eine Abweichung zwischen zwei Dingen.",
      difficulty: 2,
    },
    {
      type: "mc",
      prompt: "Welche Bedeutung hat das Wort 'Konsequenz'?",
      options: ["Zufaelligkeit", "Folge", "Anfang", "Ausnahme"],
      correct: [1],
      explanation: "'Konsequenz' bedeutet Folge oder Beharrlichkeit, also das, was sich aus einer Handlung oder Entscheidung ergibt.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Was ist eine 'Initiative'?",
      options: ["das Ende eines Projekts", "ein Rueckzug", "der erste Schritt", "eine Ablehnung"],
      correct: [2],
      explanation: "'Initiative' bedeutet erster Schritt oder Tatkraft, also das eigenstaendige Ergreifen von Handlungen.",
      difficulty: 1,
    },
  ],
};
export default supplement;
