import type { RawFlashcard, RawQuestion } from '../types';

const supplement: { flashcards: RawFlashcard[]; questions: RawQuestion[] } = {
  flashcards: [
    { front: "Wie groß ist die Fläche Deutschlands?", back: "Ca. 357.000 km²" },
    { front: "Wie viele Einwohner hat Deutschland?", back: "Ca. 84 Millionen Einwohner" },
    { front: "Welche Klimazone herrscht in Deutschland?", back: "Gemäßigte Klimazone" },
    { front: "Wie viele Nachbarländer hat Deutschland und welche sind es?", back: "9 Nachbarländer: Dänemark, Polen, Tschechien, Österreich, Schweiz, Frankreich, Luxemburg, Belgien, Niederlande" },
    { front: "Was ist der längste Fluss Deutschlands?", back: "Der Rhein" },
    { front: "Was ist der höchste Berg Deutschlands und wie hoch ist er?", back: "Die Zugspitze mit 2.962 m" },
    { front: "Was ist der höchste Berg Europas?", back: "Der Mont Blanc" },
    { front: "Was bildet die Grenze zwischen Europa und Asien?", back: "Das Uralgebirge (Ural)" },
    { front: "Was ist der größte Kontinent der Welt?", back: "Asien" },
    { front: "Was ist der größte Ozean der Welt?", back: "Der Pazifik" },
    { front: "Was ist der längste Fluss der Welt?", back: "Der Nil" },
    { front: "Was ist der höchste Berg der Welt?", back: "Der Mount Everest" },
    { front: "Was ist der tiefste Punkt der Erde?", back: "Das Tote Meer" },
    { front: "An welchem Fluss liegt Dresden, und an welchem liegt Bremen?", back: "Dresden liegt an der Elbe; Bremen liegt an der Weser" },
  ],
  questions: [
    {
      type: "mc",
      prompt: "Wie viele Nachbarländer hat Deutschland?",
      options: ["7", "8", "9", "10"],
      correct: [2],
      explanation: "Deutschland hat genau 9 Nachbarländer: Dänemark, Polen, Tschechien, Österreich, Schweiz, Frankreich, Luxemburg, Belgien und die Niederlande.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Welches ist das größte Bundesland Deutschlands nach Fläche?",
      options: ["Nordrhein-Westfalen", "Baden-Württemberg", "Niedersachsen", "Bayern"],
      correct: [3],
      explanation: "Bayern ist das flächenmäßig größte Bundesland Deutschlands.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Wie hoch ist die Zugspitze, der höchste Berg Deutschlands?",
      options: ["2.962 m", "3.100 m", "2.750 m", "3.500 m"],
      correct: [0],
      explanation: "Die Zugspitze ist 2.962 Meter hoch und damit der höchste Berg Deutschlands.",
      difficulty: 2,
    },
    {
      type: "mc",
      prompt: "Was ist der größte Binnenhafen Deutschlands?",
      options: ["Hamburg", "Bremen", "Köln", "Duisburg"],
      correct: [3],
      explanation: "Duisburg ist der größte Binnenhafen Deutschlands (und auch der weltgrößte Binnenhafen). Hamburg ist der größte Seehafen.",
      difficulty: 2,
    },
    {
      type: "mc",
      prompt: "Welche Insel ist die größte Deutschlands?",
      options: ["Sylt", "Rügen", "Fehmarn", "Usedom"],
      correct: [1],
      explanation: "Rügen ist die größte Insel Deutschlands.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Was ist das größte Land Europas nach Fläche?",
      options: ["Russland", "Ukraine", "Frankreich", "Deutschland"],
      correct: [1],
      explanation: "Die Ukraine ist das größte Land Europas (ohne den russischen Teil, der zu Asien gehört). Bezieht man Russland als europäisches Land ein, wäre Russland das größte.",
      difficulty: 2,
    },
    {
      type: "mc",
      prompt: "Welcher Kanal verbindet das Mittelmeer mit dem Roten Meer?",
      options: ["Panamakanal", "Eurotunnel", "Suezkanal", "Bosporus"],
      correct: [2],
      explanation: "Der Suezkanal in Ägypten verbindet das Mittelmeer mit dem Roten Meer und ist eine wichtige Schifffahrtsroute.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Welchem Land gehören die Kanarischen Inseln?",
      options: ["Portugal", "Frankreich", "Spanien", "Italien"],
      correct: [2],
      explanation: "Die Kanarischen Inseln gehören zu Spanien. Die Azoren hingegen gehören zu Portugal.",
      difficulty: 2,
    },
    {
      type: "mc",
      prompt: "Was ist die Hauptstadt Australiens?",
      options: ["Sydney", "Melbourne", "Brisbane", "Canberra"],
      correct: [3],
      explanation: "Die Hauptstadt Australiens ist Canberra, nicht Sydney oder Melbourne, die zwar größere Städte sind.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Was ist die Hauptstadt Kanadas?",
      options: ["Toronto", "Vancouver", "Ottawa", "Montreal"],
      correct: [2],
      explanation: "Die Hauptstadt Kanadas ist Ottawa. Toronto ist zwar die größte Stadt, aber nicht die Hauptstadt.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Welches ist der größte See der Welt?",
      options: ["Baikalsee", "Viktoriasee", "Kaspisches Meer", "Oberer See"],
      correct: [2],
      explanation: "Das Kaspische Meer ist mit einer Fläche von ca. 371.000 km² der größte See der Welt.",
      difficulty: 2,
    },
    {
      type: "truefalse",
      prompt: "Der Bosporus befindet sich in Istanbul und verbindet das Schwarze Meer mit dem Mittelmeer.",
      options: ["Richtig", "Falsch"],
      correct: [0],
      explanation: "Richtig. Der Bosporus ist eine Meerenge bei Istanbul (Türkei) und verbindet das Schwarze Meer mit dem Marmarameer, das wiederum über die Dardanellen mit dem Mittelmeer verbunden ist.",
      difficulty: 2,
    },
    {
      type: "truefalse",
      prompt: "Die Amtssprache des Bundes in Deutschland ist sowohl Deutsch als auch Englisch.",
      options: ["Richtig", "Falsch"],
      correct: [1],
      explanation: "Falsch. Auf Bundesebene ist Deutsch die einzige Amtssprache Deutschlands.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Welches ist das bevölkerungsreichste Land der Welt?",
      options: ["China", "USA", "Indien", "Indonesien"],
      correct: [2],
      explanation: "Indien ist das bevölkerungsreichste Land der Welt, gefolgt von China und den USA.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Was ist der kleinste Staat Europas?",
      options: ["Monaco", "San Marino", "Liechtenstein", "Vatikan"],
      correct: [3],
      explanation: "Der Vatikan ist mit einer Fläche von ca. 0,44 km² der kleinste Staat der Welt und Europas.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Welche Stadt ist die einwohnerstärkste in Europa?",
      options: ["London", "Paris", "Berlin", "Moskau"],
      correct: [3],
      explanation: "Moskau ist die einwohnerstärkste Stadt Europas mit über 12 Millionen Einwohnern.",
      difficulty: 2,
    },
    {
      type: "mc",
      prompt: "Was ist die Hauptstadt der Schweiz?",
      options: ["Zürich", "Genf", "Basel", "Bern"],
      correct: [3],
      explanation: "Die Hauptstadt (Bundesstadt) der Schweiz ist Bern. Zürich ist zwar die größte Stadt, aber nicht die Hauptstadt.",
      difficulty: 1,
    },
    {
      type: "fill",
      prompt: "Der Äquator hat eine Länge von ca. ___ km.",
      correct: ["40.000", "40000"],
      explanation: "Der Erdumfang am Äquator beträgt ca. 40.000 km.",
      difficulty: 2,
    },
  ],
};

export default supplement;
