import type { RawFlashcard, RawQuestion } from '../types';

const supplement: { flashcards: RawFlashcard[]; questions: RawQuestion[] } = {
  flashcards: [
    { front: "Wer war der erste römische Kaiser?", back: "Augustus war der erste römische Kaiser des Imperium Romanum." },
    { front: "Was unternahm Hannibal während des Zweiten Punischen Krieges?", back: "Hannibal zog mit seinem Heer und Kriegselefanten über die Alpen." },
    { front: "Was bezeichnet man als Hellenismus?", back: "Die Epoche nach den Eroberungen Alexanders des Großen, in der griechische Kultur und Sprache im Mittelmeerraum und Vorderen Orient verbreitet wurden." },
    { front: "Was entdeckte Christoph Kolumbus 1492?", back: "1492 entdeckte Christoph Kolumbus Amerika." },
    { front: "Was gelang Vasco da Gama im Jahr 1498?", back: "Vasco da Gama fand 1498 den Seeweg nach Indien (um Afrika herum)." },
    { front: "Was war die Renaissance und wann fand sie statt?", back: "Die Renaissance war eine europäische Kulturepoche von ca. 1400 bis 1600, die die Rückbesinnung auf die Antike und den Beginn der Neuzeit um 1500 markiert." },
    { front: "Was war der Dreißigjährige Krieg und wann dauerte er?", back: "Der Dreißigjährige Krieg dauerte von 1618 bis 1648 und war ein Konflikt zwischen Katholiken und Protestanten in Europa." },
    { front: "Welches Motto prägte die Französische Revolution von 1789?", back: "Freiheit, Gleichheit, Brüderlichkeit (Liberté, Égalité, Fraternité)." },
    { front: "Was erreichte Bismarck 1871 und was führte er in den 1880er Jahren ein?", back: "1871 wurde Otto von Bismarck erster Reichskanzler. In den 1880er Jahren führte er die Sozialversicherung in Deutschland ein." },
    { front: "Was löste den Ersten Weltkrieg (1914–1918) aus?", back: "Das Attentat von Sarajevo im Jahr 1914 war der Auslöser des Ersten Weltkriegs." },
    { front: "Was geschah 1949 in Deutschland?", back: "1949 wurden die Bundesrepublik Deutschland (BRD) und die Deutsche Demokratische Republik (DDR) gegründet. Das Grundgesetz trat in Kraft und Theodor Heuss wurde erster Bundespräsident." },
    { front: "Was ereignete sich am 9. November 1989 und am 3. Oktober 1990?", back: "Am 9. November 1989 fiel die Berliner Mauer. Am 3. Oktober 1990 fand die Deutsche Wiedervereinigung statt (Tag der Deutschen Einheit)." },
  ],
  questions: [
    {
      type: "mc",
      prompt: "Wer war der erste römische Kaiser?",
      options: ["Julius Caesar", "Nero", "Augustus", "Hadrian"],
      correct: [2],
      explanation: "Augustus war der erste Kaiser des Imperium Romanum, nicht Julius Caesar, der Diktator war.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "In welchem Jahr entdeckte Christoph Kolumbus Amerika?",
      options: ["1488", "1498", "1492", "1510"],
      correct: [2],
      explanation: "Christoph Kolumbus erreichte 1492 Amerika und öffnete damit das Zeitalter der Entdeckungen.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Wer fand 1498 den Seeweg nach Indien?",
      options: ["Christoph Kolumbus", "Ferdinand Magellan", "Amerigo Vespucci", "Vasco da Gama"],
      correct: [3],
      explanation: "Vasco da Gama umrundete 1498 Afrika und fand so den Seeweg nach Indien.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Wann dauerte die Renaissance etwa?",
      options: ["ca. 800–1000", "ca. 1400–1600", "ca. 1700–1850", "ca. 1200–1350"],
      correct: [1],
      explanation: "Die Renaissance fand ca. von 1400 bis 1600 statt und markiert den Beginn der Neuzeit um 1500.",
      difficulty: 2,
    },
    {
      type: "truefalse",
      prompt: "Der Dreißigjährige Krieg dauerte von 1618 bis 1648 und war ein Konflikt zwischen Katholiken und Protestanten.",
      options: ["Richtig", "Falsch"],
      correct: [0],
      explanation: "Richtig. Der Dreißigjährige Krieg (1618–1648) war ein vorwiegend religiöser und politischer Konflikt zwischen Katholiken und Protestanten in Europa.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "In welchem Jahr begann die Französische Revolution?",
      options: ["1776", "1789", "1804", "1815"],
      correct: [1],
      explanation: "Die Französische Revolution begann 1789 mit dem Sturm auf die Bastille unter dem Motto Freiheit, Gleichheit, Brüderlichkeit.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Was führte Otto von Bismarck in den 1880er Jahren in Deutschland ein?",
      options: ["Die allgemeine Schulpflicht", "Das Frauenwahlrecht", "Die Sozialversicherung", "Die Pressefreiheit"],
      correct: [2],
      explanation: "Bismarck führte in den 1880er Jahren die Sozialversicherung (Kranken-, Unfall- und Rentenversicherung) ein.",
      difficulty: 2,
    },
    {
      type: "mc",
      prompt: "Was war der unmittelbare Auslöser des Ersten Weltkriegs?",
      options: ["Der Angriff auf Polen", "Das Attentat von Sarajevo 1914", "Die Bombardierung von London", "Die Julikrise 1870"],
      correct: [1],
      explanation: "Das Attentat von Sarajevo im Juni 1914, bei dem Erzherzog Franz Ferdinand ermordet wurde, gilt als unmittelbarer Auslöser des Ersten Weltkriegs.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Wann dauerte der Zweite Weltkrieg?",
      options: ["1933–1941", "1939–1945", "1941–1947", "1935–1945"],
      correct: [1],
      explanation: "Der Zweite Weltkrieg dauerte von 1939 bis 1945.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Wer war der erste Bundespräsident der Bundesrepublik Deutschland?",
      options: ["Konrad Adenauer", "Kurt Schumacher", "Theodor Heuss", "Ludwig Erhard"],
      correct: [2],
      explanation: "Theodor Heuss wurde 1949 der erste Bundespräsident der neugegründeten Bundesrepublik Deutschland.",
      difficulty: 2,
    },
    {
      type: "truefalse",
      prompt: "Die Berliner Mauer wurde am 9. November 1989 gebaut.",
      options: ["Richtig", "Falsch"],
      correct: [1],
      explanation: "Falsch. Die Berliner Mauer wurde 1961 gebaut. Am 9. November 1989 fiel sie.",
      difficulty: 2,
    },
    {
      type: "mc",
      prompt: "In welchem Jahr wurde die Berliner Mauer gebaut?",
      options: ["1949", "1955", "1961", "1968"],
      correct: [2],
      explanation: "Die Berliner Mauer wurde 1961 errichtet, um die Flucht von DDR-Bürgern in den Westen zu verhindern.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Wann fand die Deutsche Wiedervereinigung statt?",
      options: ["9. November 1989", "3. Oktober 1990", "1. Januar 1991", "3. Oktober 1989"],
      correct: [1],
      explanation: "Die Deutsche Wiedervereinigung fand am 3. Oktober 1990 statt. Dieser Tag wird als Tag der Deutschen Einheit gefeiert.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Wer war der erste Mensch im Weltraum (1961)?",
      options: ["Neil Armstrong", "Buzz Aldrin", "Alan Shepard", "Juri Gagarin"],
      correct: [3],
      explanation: "Der Sowjetrusse Juri Gagarin war 1961 der erste Mensch im Weltraum.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "In welchem Jahr landeten zum ersten Mal Menschen auf dem Mond?",
      options: ["1961", "1965", "1969", "1972"],
      correct: [2],
      explanation: "1969 landeten Neil Armstrong und Buzz Aldrin im Rahmen der Apollo-11-Mission als erste Menschen auf dem Mond.",
      difficulty: 1,
    },
    {
      type: "truefalse",
      prompt: "Hannibal zog mit seinem Heer über die Alpen, um Rom anzugreifen.",
      options: ["Richtig", "Falsch"],
      correct: [0],
      explanation: "Richtig. Hannibal, der karthagische Feldherr, überquerte mit seinem Heer und Kriegselefanten die Alpen, um in der Antike Italien und Rom anzugreifen.",
      difficulty: 2,
    },
  ],
};

export default supplement;
