import type { RawFlashcard, RawQuestion } from '../types';
const supplement: { flashcards: RawFlashcard[]; questions: RawQuestion[] } = {
  flashcards: [
    { front: "Was versteht man unter der Legislative?", back: "Die Legislative ist die gesetzgebende Gewalt. In Deutschland gehoeren dazu der Bundestag und der Bundesrat." },
    { front: "Was versteht man unter der Exekutive?", back: "Die Exekutive ist die ausfuehrende Gewalt. Dazu gehoeren Regierung, Verwaltung und Polizei." },
    { front: "Was versteht man unter der Judikative?", back: "Die Judikative ist die rechtsprechende Gewalt. Dazu gehoeren die Gerichte, insbesondere das Bundesverfassungsgericht." },
    { front: "Welches Ziel verfolgt die Gewaltenteilung?", back: "Die Gewaltenteilung dient der Machtbegrenzung und dem Schutz der Freiheit." },
    { front: "Welche Organe gehoeren zur Legislative in Deutschland?", back: "Bundestag und Bundesrat." },
    { front: "Was ist Foederalismus?", back: "Foederalismus bezeichnet die Aufteilung der Staatsgewalt auf mehrere Ebenen: Bund, Laender und Kommunen." },
    { front: "Wie viele Bundeslaender hat Deutschland?", back: "Deutschland hat 16 Bundeslaender." },
  ],
  questions: [
    {
      type: "mc",
      prompt: "Welche Gewalt ist fuer die Gesetzgebung zustaendig?",
      options: ["Exekutive", "Judikative", "Legislative", "Polizei"],
      correct: [2],
      explanation: "Die Legislative (Gesetzgebung) umfasst in Deutschland Bundestag und Bundesrat.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Welches Organ gehoert NICHT zur Legislative?",
      options: ["Bundestag", "Bundesrat", "Bundesverfassungsgericht", "Keine der genannten"],
      correct: [2],
      explanation: "Das Bundesverfassungsgericht gehoert zur Judikative, nicht zur Legislative.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Was ist das Hauptziel der Gewaltenteilung?",
      options: ["Steigerung der Effizienz der Verwaltung", "Machtbegrenzung und Schutz der Freiheit", "Foerderung des Foederalismus", "Vereinheitlichung der Gesetze"],
      correct: [1],
      explanation: "Die Gewaltenteilung soll Machtkonzentration verhindern und die Freiheit der Buerger schuetzen.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Welche Ebenen gibt es im deutschen Foederalismus?",
      options: ["Bund, Laender und Kommunen", "Bundestag, Bundesrat und Regierung", "Legislative, Exekutive und Judikative", "Bund, Kantone und Gemeinden"],
      correct: [0],
      explanation: "Der deutsche Foederalismus gliedert sich in Bund, Laender und Kommunen.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Wie viele Bundeslaender hat Deutschland?",
      options: ["12", "14", "16", "18"],
      correct: [2],
      explanation: "Deutschland besteht aus genau 16 Bundeslaendern.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Welche der folgenden Institutionen gehoert zur Exekutive?",
      options: ["Bundesverfassungsgericht", "Bundestag", "Polizei", "Bundesrat"],
      correct: [2],
      explanation: "Die Polizei gehoert zur Exekutive (ausfuehrende Gewalt), zusammen mit Regierung und Verwaltung.",
      difficulty: 2,
    },
    {
      type: "truefalse",
      prompt: "Das Bundesverfassungsgericht gehoert zur Judikative.",
      options: ["Wahr", "Falsch"],
      correct: [0],
      explanation: "Richtig. Das Bundesverfassungsgericht ist Teil der Judikative (Rechtsprechung).",
      difficulty: 1,
    },
    {
      type: "truefalse",
      prompt: "Der Bundesrat gehoert zur Exekutive.",
      options: ["Wahr", "Falsch"],
      correct: [1],
      explanation: "Falsch. Der Bundesrat gehoert zur Legislative (Gesetzgebung), nicht zur Exekutive.",
      difficulty: 2,
    },
  ],
};
export default supplement;
