import type { RawFlashcard, RawQuestion } from '../types';
const supplement: { flashcards: RawFlashcard[]; questions: RawQuestion[] } = {
  flashcards: [
    { front: "Welcher Fall fragt mit Wer/Was?", back: "Nominativ. Beispiel: Der Antrag liegt vor." },
    { front: "Welcher Fall fragt mit Wessen?", back: "Genitiv. Beispiel: Die Bearbeitung des Antrags." },
    { front: "Welcher Fall fragt mit Wem?", back: "Dativ. Beispiel: Ich helfe dem Kollegen." },
    { front: "Welcher Fall fragt mit Wen/Was?", back: "Akkusativ. Beispiel: Ich stelle den Antrag." },
    { front: "Was ist ein Nomen?", back: "Ein Hauptwort, z. B. Haus." },
    { front: "Was ist ein Verb?", back: "Ein Taetigkeitswort, z. B. laufen." },
    { front: "Was ist ein Adjektiv?", back: "Ein Eigenschaftswort, z. B. schnell." },
    { front: "Was ist ein Pronomen?", back: "Ein Fuerwort, z. B. er, sie." },
    { front: "Was ist eine Praepositon?", back: "Ein Verhaeltniswort, z. B. auf, unter." },
    { front: "Was ist eine Konjunktion?", back: "Ein Bindewort, z. B. und, weil." },
    { front: "Was ist ein Adverb?", back: "Ein Umstandswort, z. B. heute." },
    { front: "Was ist ein Artikel?", back: "Ein Begleiter des Nomens, z. B. der, ein." },
    { front: "Welche vier Verben verlangen immer den Dativ?", back: "helfen, danken, gratulieren, antworten." },
    { front: "In welchem Fall steht: 'Ich helfe dem Kollegen'?", back: "Dativ (dem Kollegen = Dativobjekt)." },
    { front: "In welchem Fall steht: 'Ich stelle den Antrag'?", back: "Akkusativ (den Antrag = Akkusativobjekt)." },
  ],
  questions: [
    {
      type: "mc",
      prompt: "Mit welcher Frage ermittelt man den Nominativ?",
      options: ["Wessen?", "Wem?", "Wer/Was?", "Wen/Was?"],
      correct: [2],
      explanation: "Der Nominativ fragt mit Wer/Was? Beispiel: Der Antrag liegt vor.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Welches Beispiel steht im Genitiv?",
      options: ["Der Antrag liegt vor.", "Die Bearbeitung des Antrags.", "Ich helfe dem Kollegen.", "Ich stelle den Antrag."],
      correct: [1],
      explanation: "Der Genitiv fragt mit Wessen? und zeigt Zugehoerigkeit: die Bearbeitung des Antrags.",
      difficulty: 2,
    },
    {
      type: "mc",
      prompt: "In welchem Fall steht das Objekt im Satz 'Ich helfe dem Kollegen'?",
      options: ["Nominativ", "Akkusativ", "Genitiv", "Dativ"],
      correct: [3],
      explanation: "Das Verb 'helfen' verlangt den Dativ. Daher steht 'dem Kollegen' im Dativ.",
      difficulty: 2,
    },
    {
      type: "mc",
      prompt: "Mit welcher Frage ermittelt man den Akkusativ?",
      options: ["Wer/Was?", "Wessen?", "Wem?", "Wen/Was?"],
      correct: [3],
      explanation: "Der Akkusativ fragt mit Wen/Was? Beispiel: Ich stelle den Antrag.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Welches der folgenden Verben verlangt den Dativ?",
      options: ["sehen", "kaufen", "danken", "lesen"],
      correct: [2],
      explanation: "Danken, helfen, gratulieren und antworten sind feste Dativ-Verben.",
      difficulty: 2,
    },
    {
      type: "mc",
      prompt: "Welche Wortart ist 'schnell'?",
      options: ["Nomen", "Verb", "Adverb", "Adjektiv"],
      correct: [3],
      explanation: "Schnell ist ein Adjektiv (Eigenschaftswort).",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Welche Wortart ist 'heute'?",
      options: ["Adjektiv", "Adverb", "Konjunktion", "Praeposition"],
      correct: [1],
      explanation: "Heute ist ein Adverb (Umstandswort).",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Was ist die korrekte Beschreibung einer Konjunktion?",
      options: ["Hauptwort, z. B. Haus", "Verhaeltniswort, z. B. auf", "Begleiter, z. B. der", "Bindewort, z. B. und, weil"],
      correct: [3],
      explanation: "Eine Konjunktion ist ein Bindewort, das Saetze oder Woerter verbindet, z. B. und, weil.",
      difficulty: 1,
    },
    {
      type: "truefalse",
      prompt: "'Gratulieren' verlangt immer den Dativ.",
      options: ["Richtig", "Falsch"],
      correct: [0],
      explanation: "Gratulieren gehoert zu den festen Dativ-Verben (helfen, danken, gratulieren, antworten).",
      difficulty: 1,
    },
    {
      type: "truefalse",
      prompt: "Der Genitiv fragt mit 'Wem?'.",
      options: ["Richtig", "Falsch"],
      correct: [1],
      explanation: "Der Genitiv fragt mit 'Wessen?', nicht mit 'Wem?'. 'Wem?' ist die Frage des Dativs.",
      difficulty: 2,
    },
    {
      type: "truefalse",
      prompt: "Ein Pronomen ist ein Fuerwort, z. B. er, sie.",
      options: ["Richtig", "Falsch"],
      correct: [0],
      explanation: "Pronomen sind Fuerwortvoerter, die ein Nomen ersetzen, z. B. er, sie.",
      difficulty: 1,
    },
    {
      type: "fill",
      prompt: "Die vier Faelle des Deutschen sind Nominativ, Genitiv, ___ und Akkusativ.",
      correct: ["Dativ"],
      explanation: "Die vier grammatischen Faelle sind Nominativ, Genitiv, Dativ und Akkusativ.",
      difficulty: 1,
    },
    {
      type: "fill",
      prompt: "Das Verb 'helfen' verlangt den ___ (Fall).",
      correct: ["Dativ"],
      explanation: "Helfen ist ein festes Dativ-Verb. Beispiel: Ich helfe dem Kollegen.",
      difficulty: 2,
    },
    {
      type: "fill",
      prompt: "Ein Nomen ist ein ___, z. B. Haus.",
      correct: ["Hauptwort"],
      explanation: "Nomen werden auch Hauptwoerter genannt, z. B. Haus, Antrag, Kollege.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Welche Wortart ist 'auf' im Satz 'Das Buch liegt auf dem Tisch'?",
      options: ["Konjunktion", "Adverb", "Praeposition", "Artikel"],
      correct: [2],
      explanation: "Auf ist eine Praeposition (Verhaeltniswort), z. B. auf, unter.",
      difficulty: 2,
    },
    {
      type: "mc",
      prompt: "Welche vier Verben verlangen laut Lernskript fest den Dativ?",
      options: [
        "sehen, kaufen, lesen, schreiben",
        "helfen, danken, gratulieren, antworten",
        "helfen, sehen, laufen, danken",
        "antworten, kaufen, gratulieren, lesen",
      ],
      correct: [1],
      explanation: "Die Dativ-Verben aus dem Lernskript sind: helfen, danken, gratulieren, antworten.",
      difficulty: 2,
    },
    {
      type: "mc",
      prompt: "Was ist ein Artikel?",
      options: ["Ein Fuerwort, z. B. er, sie", "Ein Umstandswort, z. B. heute", "Ein Begleiter des Nomens, z. B. der, ein", "Ein Bindewort, z. B. und"],
      correct: [2],
      explanation: "Artikel sind Begleiter des Nomens, z. B. der bestimmte Artikel 'der' oder der unbestimmte Artikel 'ein'.",
      difficulty: 1,
    },
    {
      type: "truefalse",
      prompt: "Im Satz 'Ich stelle den Antrag' steht 'den Antrag' im Dativ.",
      options: ["Richtig", "Falsch"],
      correct: [1],
      explanation: "Den Antrag steht im Akkusativ (Frage: Wen/Was?), nicht im Dativ.",
      difficulty: 3,
    },
    {
      type: "fill",
      prompt: "Eine Praeposition ist ein Verhaeltniswort, z. B. ___ oder unter.",
      correct: ["auf"],
      explanation: "Praepositionen wie auf oder unter beschreiben raeumliche oder andere Verhaeltnisse.",
      difficulty: 2,
    },
    {
      type: "mc",
      prompt: "Welche Wortart verbindet Saetze und Woerter, z. B. 'und' oder 'weil'?",
      options: ["Adverb", "Artikel", "Konjunktion", "Pronomen"],
      correct: [2],
      explanation: "Konjunktionen sind Bindewoerter, z. B. und, weil.",
      difficulty: 1,
    },
  ],
};
export default supplement;
