import type { RawFlashcard, RawQuestion } from '../types';
const supplement: { flashcards: RawFlashcard[]; questions: RawQuestion[] } = {
  flashcards: [
    { front: "Was ist das Grundgesetz und seit wann gilt es?", back: "Das Grundgesetz ist die Verfassung der Bundesrepublik Deutschland, in Kraft seit dem 23.05.1949 (Gruendung der BRD 1949)." },
    { front: "Was besagt Art. 1 GG?", back: "Die Wuerde des Menschen ist unantastbar. Dieser Kern ist durch die Ewigkeitsklausel (Art. 79 Abs. 3 GG) unveraenderbar." },
    { front: "Was ist die Ewigkeitsklausel?", back: "Art. 79 Abs. 3 GG: Bestimmte Grundsaetze des Grundgesetzes (insbesondere die Menschenwuerde nach Art. 1 und die Staatsstrukturprinzipien nach Art. 20) koennen nicht durch Verfassungsaenderung abgeschafft werden." },
    { front: "Welche Staatsstrukturprinzipien nennt Art. 20 GG?", back: "Republik, Demokratie, Bundesstaat, Rechtsstaat und Sozialstaat." },
    { front: "Was enthaelt Art. 20 GG neben den Staatsstrukturprinzipien?", back: "Volkssouvranitaet, Gewaltenteilung und das Widerstandsrecht." },
    { front: "In welchen Artikeln stehen die Grundrechte im Grundgesetz?", back: "Die Grundrechte stehen in Art. 1 bis 19 GG." },
    { front: "Ab wann gelten die Grundrechte und wovor schuetzen sie?", back: "Die Grundrechte gelten ab Geburt und schuetzen vor Eingriffen des Staates." },
    { front: "Welches Grundrecht schuetzt Art. 3 GG?", back: "Art. 3 GG schuetzt die Gleichheit." },
    { front: "Welches Grundrecht schuetzt Art. 4 GG?", back: "Art. 4 GG schuetzt die Religionsfreiheit." },
    { front: "Welches Grundrecht schuetzt Art. 5 GG?", back: "Art. 5 GG schuetzt die Meinungsfreiheit." },
    { front: "Welches Grundrecht schuetzt Art. 8 GG?", back: "Art. 8 GG schuetzt die Versammlungsfreiheit." },
    { front: "Welches Grundrecht schuetzt Art. 12 GG?", back: "Art. 12 GG schuetzt die Berufsfreiheit." },
    { front: "Welches Grundrecht schuetzt Art. 14 GG?", back: "Art. 14 GG schuetzt das Eigentum." },
  ],
  questions: [
    {
      type: "mc",
      prompt: "Seit wann ist das Grundgesetz in Kraft?",
      options: ["17.07.1945", "23.05.1949", "03.10.1990", "01.01.1871"],
      correct: [1],
      explanation: "Das Grundgesetz ist die Verfassung der BRD und trat am 23.05.1949 in Kraft, dem Gruendungsdatum der Bundesrepublik Deutschland.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Was bestimmt Art. 1 GG?",
      options: ["Die Pressefreiheit ist unverletzlich.", "Die Wuerde des Menschen ist unantastbar.", "Alle Menschen sind vor dem Gesetz gleich.", "Jeder hat das Recht, seinen Beruf frei zu waehlen."],
      correct: [1],
      explanation: "Art. 1 GG lautet: 'Die Wuerde des Menschen ist unantastbar.' Dieser Grundsatz ist durch die Ewigkeitsklausel besonders geschuetzt.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Welcher Artikel des Grundgesetzes enthaelt die sogenannte Ewigkeitsklausel?",
      options: ["Art. 1 GG", "Art. 20 GG", "Art. 79 Abs. 3 GG", "Art. 19 GG"],
      correct: [2],
      explanation: "Die Ewigkeitsklausel befindet sich in Art. 79 Abs. 3 GG. Sie macht bestimmte Grundsaetze, insbesondere die Menschenwuerde und die Staatsstrukturprinzipien, unveraenderbar.",
      difficulty: 2,
    },
    {
      type: "mc",
      prompt: "Welches der folgenden Prinzipien ist KEIN Staatsstrukturprinzip des Art. 20 GG?",
      options: ["Sozialstaat", "Rechtsstaat", "Bundesstaat", "Monarchie"],
      correct: [3],
      explanation: "Art. 20 GG nennt als Staatsstrukturprinzipien: Republik, Demokratie, Bundesstaat, Rechtsstaat und Sozialstaat. Eine Monarchie ist nicht darunter – Deutschland ist eine Republik.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Was ist in Art. 20 GG neben den Staatsstrukturprinzipien noch enthalten?",
      options: ["Pressefreiheit, Kunstfreiheit und Wissenschaftsfreiheit", "Volkssouvranitaet, Gewaltenteilung und Widerstandsrecht", "Eigentumsgarantie, Erbrecht und Berufsfreiheit", "Gleichheitsgrundsatz, Religionsfreiheit und Versammlungsfreiheit"],
      correct: [1],
      explanation: "Art. 20 GG enthaelt neben den Staatsstrukturprinzipien auch die Volkssouvranitaet, die Gewaltenteilung und das Widerstandsrecht.",
      difficulty: 2,
    },
    {
      type: "mc",
      prompt: "In welchen Artikeln des Grundgesetzes sind die Grundrechte verankert?",
      options: ["Art. 1 bis 10 GG", "Art. 1 bis 19 GG", "Art. 1 bis 29 GG", "Art. 20 bis 37 GG"],
      correct: [1],
      explanation: "Die Grundrechte stehen in Art. 1 bis 19 GG und gelten ab Geburt als Schutz vor staatlichen Eingriffen.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Welcher Artikel des Grundgesetzes schuetzt die Meinungsfreiheit?",
      options: ["Art. 3 GG", "Art. 8 GG", "Art. 5 GG", "Art. 12 GG"],
      correct: [2],
      explanation: "Art. 5 GG schuetzt die Meinungsfreiheit. Art. 3 schuetzt Gleichheit, Art. 8 Versammlungsfreiheit, Art. 12 Berufsfreiheit.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Welcher Artikel des Grundgesetzes schuetzt das Eigentumsrecht?",
      options: ["Art. 12 GG", "Art. 4 GG", "Art. 8 GG", "Art. 14 GG"],
      correct: [3],
      explanation: "Art. 14 GG schuetzt das Eigentum. Art. 12 schuetzt die Berufsfreiheit, Art. 4 die Religionsfreiheit, Art. 8 die Versammlungsfreiheit.",
      difficulty: 1,
    },
    {
      type: "truefalse",
      prompt: "Die Grundrechte des Grundgesetzes schuetzen Buerger vor Eingriffen des Staates und gelten ab Geburt.",
      options: ["Richtig", "Falsch"],
      correct: [0],
      explanation: "Richtig. Die Grundrechte (Art. 1 bis 19 GG) gelten ab Geburt und sind als Abwehrrechte gegen staatliche Eingriffe konzipiert.",
      difficulty: 1,
    },
    {
      type: "truefalse",
      prompt: "Art. 1 GG (Menschenwuerde) kann durch eine verfassungsaendernde Mehrheit im Bundestag abgeschafft werden.",
      options: ["Richtig", "Falsch"],
      correct: [1],
      explanation: "Falsch. Die Ewigkeitsklausel (Art. 79 Abs. 3 GG) schuetzt die Menschenwuerde und die Staatsstrukturprinzipien vor jeder Abschaffung, auch durch verfassungsaendernde Mehrheit.",
      difficulty: 2,
    },
  ],
};
export default supplement;
