import type { RawFlashcard, RawQuestion } from '../types';
const supplement: { flashcards: RawFlashcard[]; questions: RawQuestion[] } = {
  flashcards: [
    { front: "Was ist das Grundgesetz und seit wann gilt es?", back: "Das Grundgesetz ist die Verfassung der Bundesrepublik Deutschland, in Kraft seit dem 23.05.1949 (Gründung der BRD 1949)." },
    { front: "Was besagt Art. 1 GG?", back: "Die Würde des Menschen ist unantastbar. Dieser Kern ist durch die Ewigkeitsklausel (Art. 79 Abs. 3 GG) unveränderbar." },
    { front: "Was ist die Ewigkeitsklausel?", back: "Art. 79 Abs. 3 GG: Bestimmte Grundsätze des Grundgesetzes (insbesondere die Menschenwürde nach Art. 1 und die Staatsstrukturprinzipien nach Art. 20) können nicht durch Verfassungsänderung abgeschafft werden." },
    { front: "Welche Staatsstrukturprinzipien nennt Art. 20 GG?", back: "Republik, Demokratie, Bundesstaat, Rechtsstaat und Sozialstaat." },
    { front: "Was enthält Art. 20 GG neben den Staatsstrukturprinzipien?", back: "Volkssouveränität, Gewaltenteilung und das Widerstandsrecht." },
    { front: "In welchen Artikeln stehen die Grundrechte im Grundgesetz?", back: "Die Grundrechte stehen in Art. 1 bis 19 GG." },
    { front: "Ab wann gelten die Grundrechte und wovor schützen sie?", back: "Die Grundrechte gelten ab Geburt und schützen vor Eingriffen des Staates." },
    { front: "Welches Grundrecht schützt Art. 3 GG?", back: "Art. 3 GG schützt die Gleichheit." },
    { front: "Welches Grundrecht schützt Art. 4 GG?", back: "Art. 4 GG schützt die Religionsfreiheit." },
    { front: "Welches Grundrecht schützt Art. 5 GG?", back: "Art. 5 GG schützt die Meinungsfreiheit." },
    { front: "Welches Grundrecht schützt Art. 8 GG?", back: "Art. 8 GG schützt die Versammlungsfreiheit." },
    { front: "Welches Grundrecht schützt Art. 12 GG?", back: "Art. 12 GG schützt die Berufsfreiheit." },
    { front: "Welches Grundrecht schützt Art. 14 GG?", back: "Art. 14 GG schützt das Eigentum." },
  ],
  questions: [
    {
      type: "mc",
      prompt: "Seit wann ist das Grundgesetz in Kraft?",
      options: ["17.07.1945", "23.05.1949", "03.10.1990", "01.01.1871"],
      correct: [1],
      explanation: "Das Grundgesetz ist die Verfassung der BRD und trat am 23.05.1949 in Kraft, dem Gründungsdatum der Bundesrepublik Deutschland.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Was bestimmt Art. 1 GG?",
      options: ["Die Pressefreiheit ist unverletzlich.", "Die Würde des Menschen ist unantastbar.", "Alle Menschen sind vor dem Gesetz gleich.", "Jeder hat das Recht, seinen Beruf frei zu wählen."],
      correct: [1],
      explanation: "Art. 1 GG lautet: 'Die Würde des Menschen ist unantastbar.' Dieser Grundsatz ist durch die Ewigkeitsklausel besonders geschützt.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Welcher Artikel des Grundgesetzes enthält die sogenannte Ewigkeitsklausel?",
      options: ["Art. 1 GG", "Art. 20 GG", "Art. 79 Abs. 3 GG", "Art. 19 GG"],
      correct: [2],
      explanation: "Die Ewigkeitsklausel befindet sich in Art. 79 Abs. 3 GG. Sie macht bestimmte Grundsätze, insbesondere die Menschenwürde und die Staatsstrukturprinzipien, unveränderbar.",
      difficulty: 2,
    },
    {
      type: "mc",
      prompt: "Welches der folgenden Prinzipien ist KEIN Staatsstrukturprinzip des Art. 20 GG?",
      options: ["Sozialstaat", "Rechtsstaat", "Bundesstaat", "Monarchie"],
      correct: [3],
      explanation: "Art. 20 GG nennt als Staatsstrukturprinzipien: Republik, Demokratie, Bundesstaat, Rechtsstaat und Sozialstaat. Eine Monarchie ist nicht darunter – Deutschland ist eine Republik.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Was ist in Art. 20 GG neben den Staatsstrukturprinzipien noch enthalten?",
      options: ["Pressefreiheit, Kunstfreiheit und Wissenschaftsfreiheit", "Volkssouveränität, Gewaltenteilung und Widerstandsrecht", "Eigentumsgarantie, Erbrecht und Berufsfreiheit", "Gleichheitsgrundsatz, Religionsfreiheit und Versammlungsfreiheit"],
      correct: [1],
      explanation: "Art. 20 GG enthält neben den Staatsstrukturprinzipien auch die Volkssouveränität, die Gewaltenteilung und das Widerstandsrecht.",
      difficulty: 2,
    },
    {
      type: "mc",
      prompt: "In welchen Artikeln des Grundgesetzes sind die Grundrechte verankert?",
      options: ["Art. 1 bis 10 GG", "Art. 1 bis 19 GG", "Art. 1 bis 29 GG", "Art. 20 bis 37 GG"],
      correct: [1],
      explanation: "Die Grundrechte stehen in Art. 1 bis 19 GG und gelten ab Geburt als Schutz vor staatlichen Eingriffen.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Welcher Artikel des Grundgesetzes schützt die Meinungsfreiheit?",
      options: ["Art. 3 GG", "Art. 8 GG", "Art. 5 GG", "Art. 12 GG"],
      correct: [2],
      explanation: "Art. 5 GG schützt die Meinungsfreiheit. Art. 3 schützt Gleichheit, Art. 8 Versammlungsfreiheit, Art. 12 Berufsfreiheit.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Welcher Artikel des Grundgesetzes schützt das Eigentumsrecht?",
      options: ["Art. 12 GG", "Art. 4 GG", "Art. 8 GG", "Art. 14 GG"],
      correct: [3],
      explanation: "Art. 14 GG schützt das Eigentum. Art. 12 schützt die Berufsfreiheit, Art. 4 die Religionsfreiheit, Art. 8 die Versammlungsfreiheit.",
      difficulty: 1,
    },
    {
      type: "truefalse",
      prompt: "Die Grundrechte des Grundgesetzes schützen Bürger vor Eingriffen des Staates und gelten ab Geburt.",
      options: ["Richtig", "Falsch"],
      correct: [0],
      explanation: "Richtig. Die Grundrechte (Art. 1 bis 19 GG) gelten ab Geburt und sind als Abwehrrechte gegen staatliche Eingriffe konzipiert.",
      difficulty: 1,
    },
    {
      type: "truefalse",
      prompt: "Art. 1 GG (Menschenwürde) kann durch eine verfassungsändernde Mehrheit im Bundestag abgeschafft werden.",
      options: ["Richtig", "Falsch"],
      correct: [1],
      explanation: "Falsch. Die Ewigkeitsklausel (Art. 79 Abs. 3 GG) schützt die Menschenwürde und die Staatsstrukturprinzipien vor jeder Abschaffung, auch durch verfassungsändernde Mehrheit.",
      difficulty: 2,
    },
  ],
};
export default supplement;
