import type { RawFlashcard, RawQuestion } from '../types';
const supplement: { flashcards: RawFlashcard[]; questions: RawQuestion[] } = {
  flashcards: [
    { front: "Was bedeutet das Schutzziel Vertraulichkeit?", back: "Nur befugte Personen dürfen die Daten sehen." },
    { front: "Was bedeutet das Schutzziel Integrität?", back: "Daten sind unverfälscht und unverändert." },
    { front: "Was bedeutet das Schutzziel Verfügbarkeit?", back: "Daten sind im Bedarfsfall abrufbar." },
    { front: "Wofür steht die Abkürzung CIA im IT-Sicherheitskontext?", back: "Confidentiality (Vertraulichkeit), Integrity (Integrität), Availability (Verfügbarkeit) – die drei Schutzziele." },
    { front: "Was ist Malware?", back: "Malware sind Schadprogramme, zum Beispiel Viren, Trojaner oder Ransomware." },
    { front: "Was ist Ransomware?", back: "Ransomware ist Erpressungssoftware, die Daten verschlüsselt und Lösegeld fordert." },
    { front: "Was ist Phishing?", back: "Phishing bezeichnet gefälschte E-Mails, die darauf abzielen, Passwörter oder andere sensible Daten abzugreifen." },
    { front: "Was ist ein DDoS-Angriff?", back: "DDoS (Distributed Denial of Service) ist die gezielte Überlastung eines Servers, um ihn zum Ausfall zu bringen." },
    { front: "Welche Funktion hat eine Firewall?", back: "Eine Firewall kontrolliert den Netzwerkverkehr und wirkt wie ein Türsteher für das Netz." },
    { front: "Was ist die Zwei-Faktor-Anmeldung?", back: "Eine Anmeldemethode, bei der zwei verschiedene Nachweise erbracht werden müssen, um die Sicherheit zu erhöhen." },
    { front: "Was regelt die DSGVO?", back: "Die DSGVO (EU-Datenschutz-Grundverordnung) legt seit dem 25.5.2018 EU-weit fest, wie mit persönlichen Daten umzugehen ist." },
    { front: "Welche Rechte haben Personen laut DSGVO?", back: "Recht auf Auskunft, Berichtigung und Löschung ihrer persönlichen Daten." },
    { front: "Womit wird die DSGVO in Deutschland ergänzt?", back: "In Deutschland wird die DSGVO durch das BDSG (Bundesdatenschutzgesetz) ergänzt." },
    { front: "Was bedeutet E-Government?", back: "E-Government bedeutet, Verwaltungsleistungen online zu erledigen." },
    { front: "Was ist das OZG?", back: "Das Onlinezugangsgesetz (OZG) verpflichtet Behörden, ihre Leistungen auch online anzubieten." },
  ],
  questions: [
    {
      type: "mc",
      prompt: "Welches der folgenden Schutzziele beschreibt, dass Daten unverfälscht und unverändert vorliegen?",
      options: ["Verfügbarkeit", "Integrität", "Vertraulichkeit", "Authentizität"],
      correct: [1],
      explanation: "Integrität bedeutet, dass Daten unverfälscht sind. Vertraulichkeit bezieht sich auf den Zugang, Verfügbarkeit auf die Abrufbarkeit.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Was versteht man unter Vertraulichkeit als IT-Schutzziel?",
      options: ["Daten können jederzeit abgerufen werden", "Daten sind unverändert gespeichert", "Nur befugte Personen dürfen die Daten sehen", "Daten werden regelmäßig gesichert"],
      correct: [2],
      explanation: "Vertraulichkeit stellt sicher, dass nur autorisierte Personen Zugang zu den Daten haben.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Welche Bedrohungsart bezeichnet gefälschte E-Mails, die Passwörter abgreifen sollen?",
      options: ["DDoS", "Ransomware", "Trojaner", "Phishing"],
      correct: [3],
      explanation: "Phishing nutzt gefälschte E-Mails, um Nutzer zur Preisgabe von Passwörtern oder anderen sensiblen Daten zu verleiten.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Was ist Ransomware?",
      options: ["Ein Programm zum Sichern von Backups", "Erpressungssoftware, die Daten verschlüsselt und Lösegeld fordert", "Eine Art Firewall", "Ein Verfahren zur Zwei-Faktor-Anmeldung"],
      correct: [1],
      explanation: "Ransomware ist eine Form von Malware (Schadprogramm), die Daten sperrt und Lösegeld verlangt.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Was ist das Ziel eines DDoS-Angriffs?",
      options: ["Passwörter per E-Mail abzugreifen", "Daten dauerhaft zu löschen", "Einen Server durch gezielte Überlastung zum Ausfall zu bringen", "Dateien zu verschlüsseln und Lösegeld zu fordern"],
      correct: [2],
      explanation: "DDoS steht für Distributed Denial of Service und zielt auf die gezielte Überlastung eines Servers ab.",
      difficulty: 2,
    },
    {
      type: "mc",
      prompt: "Welche Aufgabe hat eine Firewall?",
      options: ["Sie erstellt automatisch Backups", "Sie entschlüsselt verschlüsselte Verbindungen", "Sie erkennt Phishing-Mails und blockiert diese", "Sie kontrolliert den Netzwerkverkehr wie ein Türsteher"],
      correct: [3],
      explanation: "Eine Firewall überwacht und filtert den Netzwerkverkehr und schützt so das Netz vor unerlaubtem Zugriff.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Seit wann gilt die DSGVO in der EU?",
      options: ["1. Januar 2016", "25. Mai 2018", "1. Mai 2020", "25. Mai 2016"],
      correct: [1],
      explanation: "Die DSGVO (Datenschutz-Grundverordnung) ist seit dem 25.5.2018 in der gesamten EU in Kraft.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Welches Recht gewährt die DSGVO betroffenen Personen NICHT ausdrucklich?",
      options: ["Recht auf Auskunft", "Recht auf Berichtigung", "Recht auf Löschung", "Recht auf kostenlosen Internetzugang"],
      correct: [3],
      explanation: "Die DSGVO gewährt Rechte auf Auskunft, Berichtigung und Löschung persönlicher Daten. Ein Recht auf kostenlosen Internetzugang ist nicht Bestandteil der DSGVO.",
      difficulty: 2,
    },
    {
      type: "mc",
      prompt: "Durch welches deutsche Gesetz wird die DSGVO in Deutschland ergänzt?",
      options: ["Telemediengesetz (TMG)", "Bundesdatenschutzgesetz (BDSG)", "Onlinezugangsgesetz (OZG)", "IT-Sicherheitsgesetz"],
      correct: [1],
      explanation: "Das BDSG (Bundesdatenschutzgesetz) ergänzt die DSGVO auf nationaler Ebene in Deutschland.",
      difficulty: 2,
    },
    {
      type: "mc",
      prompt: "Was verpflichtet das Onlinezugangsgesetz (OZG) die Behörden zu tun?",
      options: ["Alle Akten zu digitalisieren und intern zu speichern", "Verwaltungsleistungen auch online anzubieten", "Bürger zur Nutzung von E-Government zu verpflichten", "Datenschutzbeauftragte einzustellen"],
      correct: [1],
      explanation: "Das OZG (Onlinezugangsgesetz) verpflichtet Behörden dazu, ihre Verwaltungsleistungen auch über das Internet zugänglich zu machen.",
      difficulty: 1,
    },
    {
      type: "truefalse",
      prompt: "Phishing ist eine Form von Malware, die sich selbst auf andere Computer kopiert.",
      options: ["Wahr", "Falsch"],
      correct: [1],
      explanation: "Falsch. Phishing bezeichnet gefälschte E-Mails, die Passwörter abgreifen sollen. Sich selbst kopierende Schadprogramme sind Viren.",
      difficulty: 2,
    },
    {
      type: "truefalse",
      prompt: "Die Zwei-Faktor-Anmeldung ist eine empfohlene Schutzmassnahme für IT-Sicherheit.",
      options: ["Wahr", "Falsch"],
      correct: [0],
      explanation: "Wahr. Die Zwei-Faktor-Anmeldung erhöht die Sicherheit, da zwei verschiedene Nachweise zum Anmelden erforderlich sind.",
      difficulty: 1,
    },
  ],
};
export default supplement;
