import type { RawFlashcard, RawQuestion } from '../types';
const supplement: { flashcards: RawFlashcard[]; questions: RawQuestion[] } = {
  flashcards: [
    { front: "Was bedeutet das Schutzziel Vertraulichkeit?", back: "Nur befugte Personen duerfen die Daten sehen." },
    { front: "Was bedeutet das Schutzziel Integritaet?", back: "Daten sind unverfaelscht und unveraendert." },
    { front: "Was bedeutet das Schutzziel Verfuegbarkeit?", back: "Daten sind im Bedarfsfall abrufbar." },
    { front: "Wofuer steht die Abkuerzung CIA im IT-Sicherheitskontext?", back: "Confidentiality (Vertraulichkeit), Integrity (Integritaet), Availability (Verfuegbarkeit) – die drei Schutzziele." },
    { front: "Was ist Malware?", back: "Malware sind Schadprogramme, zum Beispiel Viren, Trojaner oder Ransomware." },
    { front: "Was ist Ransomware?", back: "Ransomware ist Erpressungssoftware, die Daten verschluesselt und Loesegeld fordert." },
    { front: "Was ist Phishing?", back: "Phishing bezeichnet gefaelschte E-Mails, die darauf abzielen, Passwoerter oder andere sensible Daten abzugreifen." },
    { front: "Was ist ein DDoS-Angriff?", back: "DDoS (Distributed Denial of Service) ist die gezielte Ueberlastung eines Servers, um ihn zum Ausfall zu bringen." },
    { front: "Welche Funktion hat eine Firewall?", back: "Eine Firewall kontrolliert den Netzwerkverkehr und wirkt wie ein Tuersteher fuer das Netz." },
    { front: "Was ist die Zwei-Faktor-Anmeldung?", back: "Eine Anmeldemethode, bei der zwei verschiedene Nachweise erbracht werden muessen, um die Sicherheit zu erhoehen." },
    { front: "Was regelt die DSGVO?", back: "Die DSGVO (EU-Datenschutz-Grundverordnung) legt seit dem 25.5.2018 EU-weit fest, wie mit persoenlichen Daten umzugehen ist." },
    { front: "Welche Rechte haben Personen laut DSGVO?", back: "Recht auf Auskunft, Berichtigung und Loeschung ihrer persoenlichen Daten." },
    { front: "Womit wird die DSGVO in Deutschland ergaenzt?", back: "In Deutschland wird die DSGVO durch das BDSG (Bundesdatenschutzgesetz) ergaenzt." },
    { front: "Was bedeutet E-Government?", back: "E-Government bedeutet, Verwaltungsleistungen online zu erledigen." },
    { front: "Was ist das OZG?", back: "Das Onlinezugangsgesetz (OZG) verpflichtet Behoerden, ihre Leistungen auch online anzubieten." },
  ],
  questions: [
    {
      type: "mc",
      prompt: "Welches der folgenden Schutzziele beschreibt, dass Daten unverfaelscht und unveraendert vorliegen?",
      options: ["Verfuegbarkeit", "Integritaet", "Vertraulichkeit", "Authentizitaet"],
      correct: [1],
      explanation: "Integritaet bedeutet, dass Daten unverfaelscht sind. Vertraulichkeit bezieht sich auf den Zugang, Verfuegbarkeit auf die Abrufbarkeit.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Was versteht man unter Vertraulichkeit als IT-Schutzziel?",
      options: ["Daten koennen jederzeit abgerufen werden", "Daten sind unveraendert gespeichert", "Nur befugte Personen duerfen die Daten sehen", "Daten werden regelmaessig gesichert"],
      correct: [2],
      explanation: "Vertraulichkeit stellt sicher, dass nur autorisierte Personen Zugang zu den Daten haben.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Welche Bedrohungsart bezeichnet gefaelschte E-Mails, die Passwoerter abgreifen sollen?",
      options: ["DDoS", "Ransomware", "Trojaner", "Phishing"],
      correct: [3],
      explanation: "Phishing nutzt gefaelschte E-Mails, um Nutzer zur Preisgabe von Passwoertern oder anderen sensiblen Daten zu verleiten.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Was ist Ransomware?",
      options: ["Ein Programm zum Sichern von Backups", "Erpressungssoftware, die Daten verschluesselt und Loesegeld fordert", "Eine Art Firewall", "Ein Verfahren zur Zwei-Faktor-Anmeldung"],
      correct: [1],
      explanation: "Ransomware ist eine Form von Malware (Schadprogramm), die Daten sperrt und Loesegeld verlangt.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Was ist das Ziel eines DDoS-Angriffs?",
      options: ["Passwoerter per E-Mail abzugreifen", "Daten dauerhaft zu loeschen", "Einen Server durch gezielte Ueberlastung zum Ausfall zu bringen", "Dateien zu verschluesseln und Loesegeld zu fordern"],
      correct: [2],
      explanation: "DDoS steht fuer Distributed Denial of Service und zielt auf die gezielte Ueberlastung eines Servers ab.",
      difficulty: 2,
    },
    {
      type: "mc",
      prompt: "Welche Aufgabe hat eine Firewall?",
      options: ["Sie erstellt automatisch Backups", "Sie entschluesselt verschluesselte Verbindungen", "Sie erkennt Phishing-Mails und blockiert diese", "Sie kontrolliert den Netzwerkverkehr wie ein Tuersteher"],
      correct: [3],
      explanation: "Eine Firewall ueberwacht und filtert den Netzwerkverkehr und schuetzt so das Netz vor unerlaubtem Zugriff.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Seit wann gilt die DSGVO in der EU?",
      options: ["1. Januar 2016", "25. Mai 2018", "1. Mai 2020", "25. Mai 2016"],
      correct: [1],
      explanation: "Die DSGVO (Datenschutz-Grundverordnung) ist seit dem 25.5.2018 in der gesamten EU in Kraft.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Welches Recht gewaehrt die DSGVO betroffenen Personen NICHT ausdrucklich?",
      options: ["Recht auf Auskunft", "Recht auf Berichtigung", "Recht auf Loeschung", "Recht auf kostenlosen Internetzugang"],
      correct: [3],
      explanation: "Die DSGVO gewaehrt Rechte auf Auskunft, Berichtigung und Loeschung persoenlicher Daten. Ein Recht auf kostenlosen Internetzugang ist nicht Bestandteil der DSGVO.",
      difficulty: 2,
    },
    {
      type: "mc",
      prompt: "Durch welches deutsche Gesetz wird die DSGVO in Deutschland ergaenzt?",
      options: ["Telemediengesetz (TMG)", "Bundesdatenschutzgesetz (BDSG)", "Onlinezugangsgesetz (OZG)", "IT-Sicherheitsgesetz"],
      correct: [1],
      explanation: "Das BDSG (Bundesdatenschutzgesetz) ergaenzt die DSGVO auf nationaler Ebene in Deutschland.",
      difficulty: 2,
    },
    {
      type: "mc",
      prompt: "Was verpflichtet das Onlinezugangsgesetz (OZG) die Behoerden zu tun?",
      options: ["Alle Akten zu digitalisieren und intern zu speichern", "Verwaltungsleistungen auch online anzubieten", "Buerger zur Nutzung von E-Government zu verpflichten", "Datenschutzbeauftragte einzustellen"],
      correct: [1],
      explanation: "Das OZG (Onlinezugangsgesetz) verpflichtet Behoerden dazu, ihre Verwaltungsleistungen auch ueber das Internet zugaenglich zu machen.",
      difficulty: 1,
    },
    {
      type: "truefalse",
      prompt: "Phishing ist eine Form von Malware, die sich selbst auf andere Computer kopiert.",
      options: ["Wahr", "Falsch"],
      correct: [1],
      explanation: "Falsch. Phishing bezeichnet gefaelschte E-Mails, die Passwoerter abgreifen sollen. Sich selbst kopierende Schadprogramme sind Viren.",
      difficulty: 2,
    },
    {
      type: "truefalse",
      prompt: "Die Zwei-Faktor-Anmeldung ist eine empfohlene Schutzmassnahme fuer IT-Sicherheit.",
      options: ["Wahr", "Falsch"],
      correct: [0],
      explanation: "Wahr. Die Zwei-Faktor-Anmeldung erhoet die Sicherheit, da zwei verschiedene Nachweise zum Anmelden erforderlich sind.",
      difficulty: 1,
    },
  ],
};
export default supplement;
