import type { RawFlashcard, RawQuestion } from '../types';

const supplement: { flashcards: RawFlashcard[]; questions: RawQuestion[] } = {
  flashcards: [
    { front: "Was ist der Bundestag?", back: "Das vom Volk gewählte Parlament. Aufgaben: Gesetzgebung, Wahl des Bundeskanzlers und Kontrolle der Bundesregierung." },
    { front: "Was ist der Bundesrat?", back: "Die Vertretung der 16 Bundesländer auf Bundesebene. Jedes Land hat je nach Einwohnerzahl zwischen 3 und 6 Stimmen." },
    { front: "Was ist die Bundesregierung?", back: "Die Exekutive des Bundes, bestehend aus dem Bundeskanzler und den Bundesministern. Sie bestimmt die Richtlinien der Politik." },
    { front: "Was ist die Aufgabe des Bundespräsidenten?", back: "Er ist das Staatsoberhaupt mit repräsentativer Funktion. Er fertigt Gesetze aus und schlägt dem Bundestag den Bundeskanzler zur Wahl vor." },
    { front: "Was ist das Bundesverfassungsgericht?", back: "Der Hüter des Grundgesetzes. Es prüft die Vereinbarkeit von Gesetzen mit dem Grundgesetz. Sitz ist Karlsruhe." },
    { front: "Welche fünf Verfassungsorgane des Bundes gibt es?", back: "Bundestag, Bundesrat, Bundesregierung, Bundespräsident und Bundesverfassungsgericht." },
    { front: "Wie läuft die Gesetzgebung in 5 Schritten ab?", back: "1. Initiative → 2. Beratung und Beschluss im Bundestag → 3. Zustimmung/Einspruch des Bundesrats → 4. Ausfertigung durch den Bundespräsidenten → 5. Verkündung im Bundesgesetzblatt." },
    { front: "Was ist die Bundesversammlung und was ist ihre Aufgabe?", back: "Die Bundesversammlung ist ein Sondergremium, das ausschließlich den Bundespräsidenten wählt. Sie besteht aus Mitgliedern des Bundestags und Vertretern der Länder." },
    { front: "Wer ist Bundeskanzler (Stand 2026) und seit wann?", back: "Friedrich Merz (CDU) ist Bundeskanzler seit dem 6. Mai 2025." },
    { front: "Wer ist Bundespräsident (Stand 2026) und bis wann läuft seine Amtszeit?", back: "Frank-Walter Steinmeier (SPD). Seine Amtszeit läuft bis 2027." },
    { front: "Wer ist Bundestagspräsidentin (Stand 2026)?", back: "Julia Klöckner (CDU)." },
    { front: "Wer ist Präsident des Bundesverfassungsgerichts (Stand 2026)?", back: "Stephan Harbarth." },
  ],
  questions: [
    {
      type: "mc",
      prompt: "Welche der folgenden Aufgaben gehört NICHT zu den Aufgaben des Bundestags?",
      options: ["Gesetzgebung", "Wahl des Bundeskanzlers", "Wahl des Bundespräsidenten", "Kontrolle der Bundesregierung"],
      correct: [2],
      explanation: "Den Bundespräsidenten wählt die Bundesversammlung, nicht der Bundestag allein. Der Bundestag ist jedoch zuständig für Gesetzgebung, die Wahl des Bundeskanzlers und die Kontrolle der Bundesregierung.",
      difficulty: 2,
    },
    {
      type: "mc",
      prompt: "Wie viele Stimmen hat ein bevölkerungsreiches Bundesland maximal im Bundesrat?",
      options: ["3 Stimmen", "4 Stimmen", "5 Stimmen", "6 Stimmen"],
      correct: [3],
      explanation: "Die Stimmenzahl im Bundesrat richtet sich nach der Einwohnerzahl des jeweiligen Landes und beträgt mindestens 3 und höchstens 6 Stimmen.",
      difficulty: 2,
    },
    {
      type: "mc",
      prompt: "Welches Verfassungsorgan bestimmt die Richtlinien der Politik?",
      options: ["Bundestag", "Bundesrat", "Bundesregierung", "Bundespräsident"],
      correct: [2],
      explanation: "Die Bundesregierung, d. h. der Bundeskanzler gemeinsam mit den Bundesministern, bestimmt die Richtlinien der Politik.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "In welcher Stadt hat das Bundesverfassungsgericht seinen Sitz?",
      options: ["Berlin", "Bonn", "Frankfurt am Main", "Karlsruhe"],
      correct: [3],
      explanation: "Das Bundesverfassungsgericht hat seinen Sitz in Karlsruhe.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Was ist der vierte Schritt im Gesetzgebungsverfahren?",
      options: ["Beratung im Bundesrat", "Verkündung im Bundesgesetzblatt", "Einbringen der Initiative", "Ausfertigung durch den Bundespräsidenten"],
      correct: [3],
      explanation: "Der vierte Schritt ist die Ausfertigung durch den Bundespräsidenten. Erst danach folgt als fünfter Schritt die Verkündung.",
      difficulty: 2,
    },
    {
      type: "truefalse",
      prompt: "Die Bundesversammlung wählt ausschließlich den Bundespräsidenten.",
      options: ["Richtig", "Falsch"],
      correct: [0],
      explanation: "Richtig. Die einzige Aufgabe der Bundesversammlung ist die Wahl des Bundespräsidenten.",
      difficulty: 1,
    },
    {
      type: "truefalse",
      prompt: "Der Bundespräsident leitet die Bundesregierung und bestimmt die Richtlinien der Politik.",
      options: ["Richtig", "Falsch"],
      correct: [1],
      explanation: "Falsch. Die Richtlinienkompetenz liegt beim Bundeskanzler. Der Bundespräsident hat eine repräsentative Funktion als Staatsoberhaupt.",
      difficulty: 2,
    },
    {
      type: "truefalse",
      prompt: "Friedrich Merz ist seit dem 6. Mai 2025 Bundeskanzler und gehört der CDU an.",
      options: ["Richtig", "Falsch"],
      correct: [0],
      explanation: "Richtig. Friedrich Merz (CDU) wurde am 6. Mai 2025 zum Bundeskanzler gewählt.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Wer schlägt dem Bundestag den Bundeskanzler zur Wahl vor?",
      options: ["Der Bundesratspräsident", "Der Bundespräsident", "Der amtierende Bundeskanzler", "Der Bundestagspräsident"],
      correct: [1],
      explanation: "Es ist Aufgabe des Bundespräsidenten, dem Bundestag einen Kandidaten für das Amt des Bundeskanzlers vorzuschlagen.",
      difficulty: 2,
    },
    {
      type: "mc",
      prompt: "Welche Partei gehört Bundespräsident Frank-Walter Steinmeier an?",
      options: ["CDU", "FDP", "SPD", "Grüne"],
      correct: [2],
      explanation: "Frank-Walter Steinmeier ist Mitglied der SPD. Seine Amtszeit als Bundespräsident läuft bis 2027.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Welches Verfassungsorgan überprüft, ob Gesetze mit dem Grundgesetz vereinbar sind?",
      options: ["Bundesrat", "Bundespräsident", "Bundesverfassungsgericht", "Bundesregierung"],
      correct: [2],
      explanation: "Das Bundesverfassungsgericht ist der Hüter des Grundgesetzes und prüft die Verfassungsmäßigkeit von Gesetzen.",
      difficulty: 1,
    },
    {
      type: "fill",
      prompt: "Die Bundestagspräsidentin (Stand 2026) heißt ___.",
      correct: ["Julia Klöckner", "Klöckner"],
      explanation: "Julia Klöckner (CDU) ist Bundestagspräsidentin.",
      difficulty: 2,
    },
    {
      type: "fill",
      prompt: "Der Präsident des Bundesverfassungsgerichts (Stand 2026) heißt ___.",
      correct: ["Stephan Harbarth", "Harbarth"],
      explanation: "Stephan Harbarth ist Präsident des Bundesverfassungsgerichts.",
      difficulty: 2,
    },
    {
      type: "mc",
      prompt: "Welches ist der letzte Schritt im Gesetzgebungsverfahren des Bundes?",
      options: ["Ausfertigung durch den Bundespräsidenten", "Zustimmung des Bundesrats", "Verkündung im Bundesgesetzblatt", "Einbringen der Gesetzesinitiative"],
      correct: [2],
      explanation: "Nach der Ausfertigung durch den Bundespräsidenten wird das Gesetz als fünften und letzten Schritt im Bundesgesetzblatt verkündet und tritt damit in Kraft.",
      difficulty: 2,
    },
  ],
};

export default supplement;
