import type { RawFlashcard, RawQuestion } from '../types';
const supplement: { flashcards: RawFlashcard[]; questions: RawQuestion[] } = {
  flashcards: [
    {
      front: "Wann schreibt man 'das', wann 'dass'?",
      back: "'das' schreibt man, wenn man es durch 'dieses', 'jenes' oder 'welches' ersetzen kann (Artikel oder Pronomen). 'dass' leitet einen Nebensatz ein und ist nicht ersetzbar.",
    },
    {
      front: "Wie lautet die Ersatzprobe bei 'das' / 'dass'?",
      back: "Lässt sich das Wort durch 'dieses', 'jenes' oder 'welches' ersetzen, schreibt man 'das'. Geht das nicht, schreibt man 'dass'.",
    },
    {
      front: "Welche Signalwörter kündigen eine Großschreibung (Substantivierung) an?",
      back: "das, beim, zum, etwas, nichts. Beispiele: das Lesen, beim Schreiben, etwas Neues, nichts Besonderes.",
    },
    {
      front: "Wann schreibt man 'ss', wann 'ß'?",
      back: "Nach einem kurzen Vokal steht 'ss' (Beispiel: Fluss). Nach einem langen Vokal oder einem Doppellaut steht 'ß' (Beispiel: Straße).",
    },
    {
      front: "Warum schreibt man 'Fluss' mit 'ss'?",
      back: "Weil der Vokal 'u' kurz gesprochen wird – nach kurzem Vokal steht 'ss'.",
    },
    {
      front: "Warum schreibt man 'Straße' mit 'ß'?",
      back: "Weil der Vokal 'a' lang gesprochen wird – nach langem Vokal steht 'ß'.",
    },
    {
      front: "Heißt es 'Email' oder 'E-Mail'?",
      back: "E-Mail – mit Bindestrich und großem 'M'. 'Email' ohne Bindestrich ist falsch.",
    },
    {
      front: "Heißt es 'wiederspiegeln' oder 'widerspiegeln'?",
      back: "widerspiegeln – von 'wider' (= entgegen, zurück), nicht von 'wieder' (= erneut).",
    },
    {
      front: "Heißt es 'Adresse' oder 'Addresse'?",
      back: "Adresse – nur ein 'd', dafür Doppel-s.",
    },
    {
      front: "Heißt es 'Standard' oder 'Standart'?",
      back: "Standard – das Wort endet auf '-ard', nicht auf '-art'.",
    },
    {
      front: "Heißt es 'nämlich' oder 'nähmlich'?",
      back: "nämlich – ohne 'h' nach dem 'ä'.",
    },
    {
      front: "Heißt es 'separat' oder 'seperat'?",
      back: "separat – mit 'a' als zweitem Vokal. Eselsbrücke: sep-a-rat.",
    },
    {
      front: "Heißt es 'Ressourcen' oder 'Resourcen'?",
      back: "Ressourcen – mit Doppel-s.",
    },
    {
      front: "Heißt es 'auf jeden Fall' oder 'aufjedenfall'?",
      back: "auf jeden Fall – drei getrennte Wörter. Die Zusammenschreibung ist falsch.",
    },
    {
      front: "Heißt es 'gibts' oder 'gibt's'?",
      back: "gibt's – mit Apostroph. Der Apostroph ersetzt das weggelassene 'e' von 'es'.",
    },
  ],
  questions: [
    {
      type: "mc",
      prompt: "In welchem Satz ist 'das' richtig geschrieben?",
      options: [
        "Ich hoffe, das du kommst.",
        "Das Buch, das ich lese, ist spannend.",
        "Er sagt, das es klappt.",
        "Ich weiß, das sie recht hat.",
      ],
      correct: [1],
      explanation: "In 'das Buch, das ich lese' lässt sich 'das' durch 'welches' ersetzen – also Relativpronomen, korrekt mit einem 's'. In den anderen Sätzen leitet es einen Nebensatz ein und müsste 'dass' heißen.",
      difficulty: 2,
    },
    {
      type: "mc",
      prompt: "In welchem Satz ist 'dass' richtig geschrieben?",
      options: [
        "Das Auto, dass dort steht, gehört mir.",
        "Ich freue mich, dass du da bist.",
        "Weißt du, wo dass Buch liegt?",
        "Er nimmt dass Heft.",
      ],
      correct: [1],
      explanation: "In 'Ich freue mich, dass du da bist' leitet 'dass' einen Nebensatz ein und lässt sich nicht durch 'dieses/jenes/welches' ersetzen. In den anderen Optionen wäre 'das' richtig.",
      difficulty: 2,
    },
    {
      type: "truefalse",
      prompt: "Ersatzprobe: Wenn man das Wort durch 'dieses', 'jenes' oder 'welches' ersetzen kann, schreibt man 'das'.",
      options: ["Richtig", "Falsch"],
      correct: [0],
      explanation: "Genau so funktioniert die Ersatzprobe. Ist die Ersetzung möglich, handelt es sich um Artikel/Pronomen → 'das'. Andernfalls → 'dass'.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Welches Signalwort deutet auf eine Großschreibung (Substantivierung) hin?",
      options: ["und", "aber", "beim", "oder"],
      correct: [2],
      explanation: "'beim' kündigt eine Substantivierung an (z. B. 'beim Schreiben'). 'und', 'aber', 'oder' sind Konjunktionen und kein Signal für Großschreibung.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Welche Schreibweise ist eine korrekt großgeschriebene Substantivierung?",
      options: ["das lesen", "Das Lesen", "beim schreiben", "etwas neues"],
      correct: [1],
      explanation: "'Das Lesen' ist richtig: Das Verb 'lesen' wird nach dem Signalwort 'das' substantiviert und großgeschrieben. Die anderen Varianten haben einen Groß-/Kleinschreibfehler.",
      difficulty: 2,
    },
    {
      type: "mc",
      prompt: "Nach welchem Laut steht 'ß' (wie in 'Straße')?",
      options: [
        "nach einem kurzen Vokal",
        "nach einem langen Vokal oder Doppellaut",
        "immer am Wortende",
        "nur nach Konsonanten",
      ],
      correct: [1],
      explanation: "Nach langem Vokal oder Doppellaut steht 'ß' (Straße). Nach kurzem Vokal steht dagegen 'ss' (Fluss).",
      difficulty: 2,
    },
    {
      type: "mc",
      prompt: "Welches Wort ist nach der ss/ß-Regel korrekt geschrieben?",
      options: ["Flus", "Straase", "Fluss", "Flusss"],
      correct: [2],
      explanation: "In 'Fluss' ist das 'u' kurz, daher 'ss'. 'Flus' (ein s) und 'Flusss' (drei s) sind falsch.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Welche Schreibweise ist korrekt?",
      options: ["Addresse", "Adresse", "Adrresse", "Adrese"],
      correct: [1],
      explanation: "'Adresse' ist richtig – mit einem 'd' und Doppel-s. 'Addresse' mit Doppel-d ist ein häufiger Fehler.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Wie schreibt man das Wort für eine festgelegte Norm korrekt?",
      options: ["Standart", "Standard", "Stantard", "Stanndard"],
      correct: [1],
      explanation: "'Standard' endet auf '-ard'. 'Standart' ist ein sehr häufiger Rechtschreibfehler.",
      difficulty: 1,
    },
    {
      type: "truefalse",
      prompt: "Die korrekte Schreibweise ist 'nähmlich' – mit 'h' nach dem 'ä'.",
      options: ["Richtig", "Falsch"],
      correct: [1],
      explanation: "Falsch. Richtig ist 'nämlich' ohne 'h'. 'nähmlich' ist ein häufiger Fehler.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Welche Schreibweise der elektronischen Post ist korrekt?",
      options: ["email", "Email", "E-Mail", "e-mail"],
      correct: [2],
      explanation: "'E-Mail' ist korrekt: mit Bindestrich und großem 'M'.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Welche Schreibweise ist korrekt?",
      options: ["seperat", "seperrat", "separat", "sepparat"],
      correct: [2],
      explanation: "'separat' ist richtig – mit 'a' als zweitem Vokal. Eselsbrücke: sep-a-rat.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Wie lautet der Plural von 'Ressource' korrekt?",
      options: ["Resourcen", "Ressourcen", "Ressourecen", "Resourccen"],
      correct: [1],
      explanation: "'Ressourcen' ist richtig – mit Doppel-s. 'Resourcen' mit einfachem s ist falsch.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Heißt es 'widerspiegeln' oder 'wiederspiegeln' – und warum?",
      options: [
        "'wiederspiegeln', weil der Spiegel etwas wiederholt",
        "'widerspiegeln', weil das Präfix 'wider-' (entgegen) steckt",
        "Beide Schreibweisen sind gleichwertig",
        "'Widerspiegeln' nur am Satzanfang",
      ],
      correct: [1],
      explanation: "'widerspiegeln' ist richtig. 'wider-' bedeutet entgegen/zurück (wie in Widerspruch); 'wieder-' bedeutet erneut (wie in wiederholen). Etwas spiegelt etwas anderes wider.",
      difficulty: 2,
    },
    {
      type: "truefalse",
      prompt: "'auf jeden Fall' wird als ein Wort zusammengeschrieben: 'aufjedenfall'.",
      options: ["Richtig", "Falsch"],
      correct: [1],
      explanation: "Falsch. 'auf jeden Fall' sind drei getrennte Wörter; 'aufjedenfall' ist falsch.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Wie schreibt man die Kurzform von 'es gibt' korrekt?",
      options: ["gibts", "gibt's", "gibt`s", "Gibs"],
      correct: [1],
      explanation: "'gibt's' mit geradem Apostroph ist richtig. Der Apostroph ersetzt das weggelassene 'e' von 'es'. 'gibts' ohne Apostroph ist falsch.",
      difficulty: 1,
    },
    {
      type: "fill",
      prompt: "Ergänze: Nach kurzem Vokal schreibt man ___, nach langem Vokal oder Doppellaut schreibt man ___ (gemeint sind die beiden s-Schreibweisen).",
      correct: ["ss, ß", "ss und ß", "ss ß"],
      explanation: "Nach kurzem Vokal steht 'ss' (Fluss), nach langem Vokal oder Doppellaut steht 'ß' (Straße).",
      difficulty: 2,
    },
  ],
};
export default supplement;
