import type { RawFlashcard, RawQuestion } from '../types';

const supplement: { flashcards: RawFlashcard[]; questions: RawQuestion[] } = {
  flashcards: [
    { front: "Was regelt das Öffentliche Recht?", back: "Das Verhältnis zwischen Staat und Bürger (z. B. Steuerrecht, Sozialrecht, Verwaltungsrecht, Strafrecht)." },
    { front: "Was regelt das Privatrecht?", back: "Das Verhältnis zwischen Bürger und Bürger (z. B. BGB, Urheberrecht)." },
    { front: "Was sind die Pflichten beim Kaufvertrag?", back: "Verkäufer: Übergabe der Sache. Käufer: Zahlung des Kaufpreises." },
    { front: "Ab wann ist eine Person unbeschränkt geschäftsfähig?", back: "Ab dem vollendeten 18. Lebensjahr." },
    { front: "Was bedeutet beschränkte Geschäftsfähigkeit?", back: "Personen zwischen 7 und 17 Jahren sind beschränkt geschäftsfähig und können nur begrenzt Rechtsgeschäfte abschließen." },
    { front: "Was ist der Taschengeldparagraph?", back: "Minderjährige können mit ihrem eigenen Taschengeld wirksam Käufe tätigen, ohne Zustimmung der Eltern." },
    { front: "Wofür steht die Abkürzung AGB?", back: "AGB steht für Allgemeine Geschäftsbedingungen." },
    { front: "Wann endet das Urheberrecht?", back: "Das Urheberrecht endet 70 Jahre nach dem Tod des Urhebers." },
    { front: "Was ist Justitia?", back: "Justitia ist das Symbol der Gerechtigkeit." },
  ],
  questions: [
    {
      type: "mc",
      prompt: "Welchem Rechtsgebiet gehört das Steuerrecht an?",
      options: ["Privatrecht", "Öffentliches Recht", "Urheberrecht", "Handelsrecht"],
      correct: [1],
      explanation: "Das Steuerrecht regelt das Verhältnis zwischen Staat und Bürger und gehört damit zum Öffentlichen Recht.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Welches Gesetz ist dem Privatrecht zuzuordnen?",
      options: ["Strafgesetzbuch (StGB)", "Verwaltungsgerichtsordnung", "Bürgerliches Gesetzbuch (BGB)", "Steuerrecht"],
      correct: [2],
      explanation: "Das BGB regelt Beziehungen zwischen Bürgern und ist daher dem Privatrecht zuzuordnen.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Was ist die Hauptpflicht des Verkäufers beim Kaufvertrag?",
      options: ["Zahlung des Kaufpreises", "Übergabe der Sache", "Ausstellung einer Rechnung", "Gewährung einer Garantie"],
      correct: [1],
      explanation: "Beim Kaufvertrag ist die Hauptpflicht des Verkäufers die Übergabe der Sache an den Käufer.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Welche Hauptpflicht hat der Käufer beim Kaufvertrag?",
      options: ["Übergabe der Sache", "Abschluss einer Versicherung", "Zahlung des Kaufpreises", "Rückgabe der Ware"],
      correct: [2],
      explanation: "Die Hauptpflicht des Käufers beim Kaufvertrag ist die Zahlung des vereinbarten Kaufpreises.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Ab welchem Alter gilt eine Person in Deutschland als unbeschränkt geschäftsfähig?",
      options: ["16 Jahre", "21 Jahre", "14 Jahre", "18 Jahre"],
      correct: [3],
      explanation: "Mit Vollendung des 18. Lebensjahres tritt die Volljährigkeit und damit die unbeschränkte Geschäftsfähigkeit ein.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "In welchem Alterbereich sind Personen beschränkt geschäftsfähig?",
      options: ["Unter 7 Jahren", "7 bis 17 Jahre", "16 bis 18 Jahre", "Ab 18 Jahren"],
      correct: [1],
      explanation: "Personen zwischen 7 und 17 Jahren sind beschränkt geschäftsfähig und können nur eingeschränkt Rechtsgeschäfte eingehen.",
      difficulty: 2,
    },
    {
      type: "truefalse",
      prompt: "Minderjährige können mit ihrem eigenen Taschengeld wirksam Käufe tätigen (Taschengeldparagraph).",
      options: ["Richtig", "Falsch"],
      correct: [0],
      explanation: "Der sogenannte Taschengeldparagraph erlaubt es Minderjährigen, mit ihrem eigenen Taschengeld ohne elterliche Zustimmung wirksam zu kaufen.",
      difficulty: 2,
    },
    {
      type: "mc",
      prompt: "Wofür steht die Abkürzung AGB?",
      options: ["Allgemeine Gewerbebestimmungen", "Allgemeine Geschäftsbedingungen", "Amtliches Gesetzgebungsblatt", "Anerkannte Grundsätze der Buchführung"],
      correct: [1],
      explanation: "AGB steht für Allgemeine Geschäftsbedingungen, also vorformulierte Vertragsbedingungen.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Wer ist in Deutschland für Beurkundungen zuständig?",
      options: ["Rechtsanwalt", "Richter", "Notar", "Staatsanwalt"],
      correct: [2],
      explanation: "Der Notar ist die zuständige Stelle für notarielle Beurkundungen, z. B. bei Immobilienkäufen oder Gesellschaftsgründungen.",
      difficulty: 2,
    },
    {
      type: "mc",
      prompt: "Wann erlischt das Urheberrecht an einem Werk?",
      options: ["50 Jahre nach dem Tod des Urhebers", "70 Jahre nach dem Tod des Urhebers", "100 Jahre nach Veröffentlichung", "Mit dem Tod des Urhebers"],
      correct: [1],
      explanation: "Das Urheberrecht endet in Deutschland 70 Jahre nach dem Tod des Urhebers.",
      difficulty: 2,
    },
    {
      type: "truefalse",
      prompt: "Das Urheberrecht gehört zum Öffentlichen Recht.",
      options: ["Richtig", "Falsch"],
      correct: [1],
      explanation: "Das Urheberrecht regelt Beziehungen zwischen Bürgern (Urheber und Nutzer) und gehört daher zum Privatrecht, nicht zum Öffentlichen Recht.",
      difficulty: 2,
    },
    {
      type: "mc",
      prompt: "Wofür steht die Abkürzung StPO?",
      options: ["Staatspolizeiordnung", "Strafprozessordnung", "Steuerprüfungsordnung", "Strafgesetzbuchordnung"],
      correct: [1],
      explanation: "StPO steht für Strafprozessordnung, das Gesetz, das das Verfahren in Strafsachen regelt.",
      difficulty: 2,
    },
    {
      type: "mc",
      prompt: "Was symbolisiert Justitia?",
      options: ["Den Staat", "Die Demokratie", "Die Gerechtigkeit", "Das Grundgesetz"],
      correct: [2],
      explanation: "Justitia ist die römische Göttin der Gerechtigkeit und gilt als Symbol der Gerechtigkeit in der Rechtsprechung.",
      difficulty: 1,
    },
  ],
};

export default supplement;
