import type { RawFlashcard, RawQuestion } from '../types';
const supplement: { flashcards: RawFlashcard[]; questions: RawQuestion[] } = {
  flashcards: [
    { front: "Wogegen sichert die Krankenversicherung ab?", back: "Gegen Krankheit sowie Arzt- und Behandlungskosten." },
    { front: "Wogegen sichert die Rentenversicherung ab?", back: "Gegen Alter und Erwerbsminderung." },
    { front: "Wogegen sichert die Pflegeversicherung ab?", back: "Gegen Pflegebedürftigkeit." },
    { front: "Wogegen sichert die Arbeitslosenversicherung ab?", back: "Gegen Arbeitslosigkeit." },
    { front: "Wogegen sichert die Unfallversicherung ab?", back: "Gegen Arbeitsunfälle und Berufskrankheiten." },
    { front: "Wer zahlt die Unfallversicherung?", back: "Ausschliesslich der Arbeitgeber." },
    { front: "Was sind die 5 Säulen der Sozialversicherung?", back: "Krankenversicherung, Rentenversicherung, Pflegeversicherung, Arbeitslosenversicherung und Unfallversicherung." },
    { front: "Wie werden die Sozialversicherungen in der Regel finanziert?", back: "Meist paritätisch, also zu gleichen Teilen von Arbeitgeber und Arbeitnehmer." },
    { front: "Was bedeutet paritätische Finanzierung in der Sozialversicherung?", back: "Arbeitgeber und Arbeitnehmer tragen die Beiträge zu gleichen Teilen." },
    { front: "Handelt es sich bei den Sozialversicherungen um freiwillige oder Pflichtversicherungen?", back: "Es sind Pflichtversicherungen." },
  ],
  questions: [
    {
      type: "mc",
      prompt: "Wogegen sichert die Krankenversicherung ab?",
      options: ["Gegen Arbeitslosigkeit", "Gegen Pflegebedürftigkeit", "Gegen Krankheit, Arzt- und Behandlungskosten", "Gegen Arbeitsunfälle"],
      correct: [2],
      explanation: "Die Krankenversicherung sichert gegen Krankheit sowie anfallende Arzt- und Behandlungskosten ab.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Welche Sozialversicherung sichert gegen Alter und Erwerbsminderung ab?",
      options: ["Pflegeversicherung", "Rentenversicherung", "Unfallversicherung", "Arbeitslosenversicherung"],
      correct: [1],
      explanation: "Die Rentenversicherung schützt Versicherte vor den finanziellen Folgen von Alter und Erwerbsminderung.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Gegen welches Risiko sichert die Pflegeversicherung ab?",
      options: ["Berufskrankheiten", "Arbeitslosigkeit", "Erwerbsminderung", "Pflegebedürftigkeit"],
      correct: [3],
      explanation: "Die Pflegeversicherung deckt das Risiko der Pflegebedürftigkeit ab.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Wer trägt die Beiträge zur Unfallversicherung?",
      options: ["Hälftig Arbeitgeber und Arbeitnehmer", "Ausschliesslich der Arbeitnehmer", "Ausschliesslich der Arbeitgeber", "Der Staat"],
      correct: [2],
      explanation: "Die Unfallversicherung ist eine Ausnahme: Die Beiträge trägt allein der Arbeitgeber.",
      difficulty: 2,
    },
    {
      type: "mc",
      prompt: "Wie viele Säulen hat die Sozialversicherung in Deutschland?",
      options: ["3", "4", "6", "5"],
      correct: [3],
      explanation: "Die Sozialversicherung besteht aus 5 Säulen: Kranken-, Renten-, Pflege-, Arbeitslosen- und Unfallversicherung.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Was bedeutet paritätische Finanzierung der Sozialversicherung?",
      options: ["Der Staat übernimmt alle Beiträge", "Nur der Arbeitnehmer zahlt die Beiträge", "Arbeitgeber und Arbeitnehmer zahlen die Beiträge zu gleichen Teilen", "Nur der Arbeitgeber zahlt die Beiträge"],
      correct: [2],
      explanation: "Paritätisch bedeutet, dass Arbeitgeber und Arbeitnehmer die Beiträge je zur Hälfte tragen.",
      difficulty: 2,
    },
    {
      type: "truefalse",
      prompt: "Die Sozialversicherungen sind Pflichtversicherungen.",
      options: ["Wahr", "Falsch"],
      correct: [0],
      explanation: "Ja, alle 5 Säulen der Sozialversicherung sind Pflichtversicherungen.",
      difficulty: 1,
    },
    {
      type: "truefalse",
      prompt: "Die Unfallversicherung wird paritätisch von Arbeitgeber und Arbeitnehmer finanziert.",
      options: ["Wahr", "Falsch"],
      correct: [1],
      explanation: "Falsch. Die Unfallversicherung ist die Ausnahme: Sie wird ausschließlich vom Arbeitgeber bezahlt.",
      difficulty: 2,
    },
    {
      type: "mc",
      prompt: "Welche Sozialversicherung sichert gegen Arbeitsunfälle und Berufskrankheiten ab?",
      options: ["Krankenversicherung", "Unfallversicherung", "Rentenversicherung", "Pflegeversicherung"],
      correct: [1],
      explanation: "Die Unfallversicherung schützt Arbeitnehmer vor den Folgen von Arbeitsunfällen und Berufskrankheiten.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Welche der folgenden Versicherungen gehört NICHT zu den 5 Säulen der Sozialversicherung?",
      options: ["Arbeitslosenversicherung", "Haftpflichtversicherung", "Pflegeversicherung", "Rentenversicherung"],
      correct: [1],
      explanation: "Die Haftpflichtversicherung ist keine Sozialversicherung. Die 5 Säulen sind: Kranken-, Renten-, Pflege-, Arbeitslosen- und Unfallversicherung.",
      difficulty: 2,
    },
  ],
};
export default supplement;
