import type { RawFlashcard, RawQuestion } from '../types';
const supplement: { flashcards: RawFlashcard[]; questions: RawQuestion[] } = {
  flashcards: [
    { front: "Wogegen sichert die Krankenversicherung ab?", back: "Gegen Krankheit sowie Arzt- und Behandlungskosten." },
    { front: "Wogegen sichert die Rentenversicherung ab?", back: "Gegen Alter und Erwerbsminderung." },
    { front: "Wogegen sichert die Pflegeversicherung ab?", back: "Gegen Pflegebeduerftigkeit." },
    { front: "Wogegen sichert die Arbeitslosenversicherung ab?", back: "Gegen Arbeitslosigkeit." },
    { front: "Wogegen sichert die Unfallversicherung ab?", back: "Gegen Arbeitsunfaelle und Berufskrankheiten." },
    { front: "Wer zahlt die Unfallversicherung?", back: "Ausschliesslich der Arbeitgeber." },
    { front: "Was sind die 5 Saeulen der Sozialversicherung?", back: "Krankenversicherung, Rentenversicherung, Pflegeversicherung, Arbeitslosenversicherung und Unfallversicherung." },
    { front: "Wie werden die Sozialversicherungen in der Regel finanziert?", back: "Meist paritaetisch, also zu gleichen Teilen von Arbeitgeber und Arbeitnehmer." },
    { front: "Was bedeutet paritaetische Finanzierung in der Sozialversicherung?", back: "Arbeitgeber und Arbeitnehmer tragen die Beitraege zu gleichen Teilen." },
    { front: "Handelt es sich bei den Sozialversicherungen um freiwillige oder Pflichtversicherungen?", back: "Es sind Pflichtversicherungen." },
  ],
  questions: [
    {
      type: "mc",
      prompt: "Wogegen sichert die Krankenversicherung ab?",
      options: ["Gegen Arbeitslosigkeit", "Gegen Pflegebeduerftigkeit", "Gegen Krankheit, Arzt- und Behandlungskosten", "Gegen Arbeitsunfaelle"],
      correct: [2],
      explanation: "Die Krankenversicherung sichert gegen Krankheit sowie anfallende Arzt- und Behandlungskosten ab.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Welche Sozialversicherung sichert gegen Alter und Erwerbsminderung ab?",
      options: ["Pflegeversicherung", "Rentenversicherung", "Unfallversicherung", "Arbeitslosenversicherung"],
      correct: [1],
      explanation: "Die Rentenversicherung schuetzt Versicherte vor den finanziellen Folgen von Alter und Erwerbsminderung.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Gegen welches Risiko sichert die Pflegeversicherung ab?",
      options: ["Berufskrankheiten", "Arbeitslosigkeit", "Erwerbsminderung", "Pflegebeduerftigkeit"],
      correct: [3],
      explanation: "Die Pflegeversicherung deckt das Risiko der Pflegebeduerftigkeit ab.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Wer traegt die Beitraege zur Unfallversicherung?",
      options: ["Haelftig Arbeitgeber und Arbeitnehmer", "Ausschliesslich der Arbeitnehmer", "Ausschliesslich der Arbeitgeber", "Der Staat"],
      correct: [2],
      explanation: "Die Unfallversicherung ist eine Ausnahme: Die Beitraege traegt allein der Arbeitgeber.",
      difficulty: 2,
    },
    {
      type: "mc",
      prompt: "Wie viele Saeulen hat die Sozialversicherung in Deutschland?",
      options: ["3", "4", "6", "5"],
      correct: [3],
      explanation: "Die Sozialversicherung besteht aus 5 Saeulen: Kranken-, Renten-, Pflege-, Arbeitslosen- und Unfallversicherung.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Was bedeutet paritaetische Finanzierung der Sozialversicherung?",
      options: ["Der Staat uebernimmt alle Beitraege", "Nur der Arbeitnehmer zahlt die Beitraege", "Arbeitgeber und Arbeitnehmer zahlen die Beitraege zu gleichen Teilen", "Nur der Arbeitgeber zahlt die Beitraege"],
      correct: [2],
      explanation: "Paritaetisch bedeutet, dass Arbeitgeber und Arbeitnehmer die Beitraege je zur Haelfte tragen.",
      difficulty: 2,
    },
    {
      type: "truefalse",
      prompt: "Die Sozialversicherungen sind Pflichtversicherungen.",
      options: ["Wahr", "Falsch"],
      correct: [0],
      explanation: "Ja, alle 5 Saeulen der Sozialversicherung sind Pflichtversicherungen.",
      difficulty: 1,
    },
    {
      type: "truefalse",
      prompt: "Die Unfallversicherung wird paritaetisch von Arbeitgeber und Arbeitnehmer finanziert.",
      options: ["Wahr", "Falsch"],
      correct: [1],
      explanation: "Falsch. Die Unfallversicherung ist die Ausnahme: Sie wird ausschliesslich vom Arbeitgeber bezahlt.",
      difficulty: 2,
    },
    {
      type: "mc",
      prompt: "Welche Sozialversicherung sichert gegen Arbeitsunfaelle und Berufskrankheiten ab?",
      options: ["Krankenversicherung", "Unfallversicherung", "Rentenversicherung", "Pflegeversicherung"],
      correct: [1],
      explanation: "Die Unfallversicherung schuetzt Arbeitnehmer vor den Folgen von Arbeitsunfaellen und Berufskrankheiten.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Welche der folgenden Versicherungen gehoert NICHT zu den 5 Saeulen der Sozialversicherung?",
      options: ["Arbeitslosenversicherung", "Haftpflichtversicherung", "Pflegeversicherung", "Rentenversicherung"],
      correct: [1],
      explanation: "Die Haftpflichtversicherung ist keine Sozialversicherung. Die 5 Saeulen sind: Kranken-, Renten-, Pflege-, Arbeitslosen- und Unfallversicherung.",
      difficulty: 2,
    },
  ],
};
export default supplement;
