import type { RawFlashcard, RawQuestion } from '../types';

const supplement: { flashcards: RawFlashcard[]; questions: RawQuestion[] } = {
  flashcards: [
    { front: "Welche Einheit hat die elektrische Spannung?", back: "Volt (V)" },
    { front: "Welche Einheit hat die elektrische Stromstärke?", back: "Ampere (A)" },
    { front: "Welche Einheit hat der elektrische Widerstand?", back: "Ohm (Ω)" },
    { front: "Welche Einheit hat die elektrische Leistung?", back: "Watt (W)" },
    { front: "Wie lautet das Ohmsche Gesetz?", back: "U = R · I (Spannung = Widerstand mal Stromstärke)" },
    { front: "Was ist Kelvin?", back: "Die absolute Temperaturskala (SI-Basiseinheit für Temperatur)" },
    { front: "Was misst der pH-Wert?", back: "Den Säure- oder Basengehalt einer Lösung" },
    { front: "Wie lang ist eine Seemeile in Metern?", back: "1 Seemeile = 1.852 Meter" },
    { front: "Ab welcher Spannung spricht man von Hochspannung?", back: "Über 1.000 Volt (> 1.000 V)" },
    { front: "Was misst ein Barometer?", back: "Den Luftdruck" },
    { front: "Was misst ein Seismograf?", back: "Erdbeben (seismische Wellen)" },
    { front: "Welcher Planet ist der äußerste in unserem Sonnensystem?", back: "Neptun" },
    { front: "Wer entwickelte die Relativitätstheorie?", back: "Albert Einstein" },
    { front: "Wer erfand den Blitzableiter?", back: "Benjamin Franklin" },
    { front: "Wer erfand das World Wide Web (WWW)?", back: "Tim Berners-Lee" },
    { front: "Wer baute den Z3, den ersten frei programmierbaren Computer?", back: "Konrad Zuse (1941)" },
    { front: "Nach wem ist das Weltraumteleskop benannt, das 1990 in den Orbit gebracht wurde?", back: "Edwin Hubble (Hubble-Weltraumteleskop)" },
    { front: "Welche SI-Basiseinheit misst die Länge?", back: "Meter (m)" },
    { front: "Welche SI-Basiseinheit misst die Masse?", back: "Kilogramm (kg)" },
    { front: "Welche SI-Basiseinheit misst die Zeit?", back: "Sekunde (s)" },
    { front: "In welcher Einheit wird Kraft gemessen?", back: "Newton (N)" },
    { front: "In welcher Einheit wird Energie gemessen?", back: "Joule (J)" },
    { front: "In welcher Einheit wird Druck gemessen?", back: "Pascal (Pa) oder Bar" },
    { front: "In welcher Einheit wird Frequenz gemessen?", back: "Hertz (Hz)" },
    { front: "Was bedeutet das Präfix 'kilo'?", back: "1.000 (Tausend)" },
    { front: "Was bedeutet das Präfix 'Mega'?", back: "1.000.000 (eine Million)" },
    { front: "Was bedeutet das Präfix 'Giga'?", back: "1.000.000.000 (eine Milliarde)" },
    { front: "Was bedeutet das Präfix 'milli'?", back: "0,001 (ein Tausendstel)" },
    { front: "Was bedeutet das Präfix 'zenti'?", back: "0,01 (ein Hundertstel)" },
    { front: "Was bedeutet das Präfix 'mikro'?", back: "0,000001 (ein Millionstel)" },
    { front: "Wie viele Meter sind 1 Kilometer?", back: "1 km = 1.000 m" },
    { front: "Wie viele Gramm sind 1 Kilogramm?", back: "1 kg = 1.000 g" },
    { front: "Wie viele Kilogramm sind 1 Tonne?", back: "1 t = 1.000 kg" },
    { front: "Wie viele Milliliter sind 1 Liter?", back: "1 l = 1.000 ml" },
    { front: "Wie viele Sekunden hat 1 Stunde?", back: "1 h = 3.600 s (60 min × 60 s)" },
  ],
  questions: [
    {
      type: "mc",
      prompt: "Welche Einheit wird für die elektrische Spannung verwendet?",
      options: ["Ampere (A)", "Ohm (Ω)", "Volt (V)", "Watt (W)"],
      correct: [2],
      explanation: "Die elektrische Spannung wird in Volt (V) gemessen. Ampere steht für Stromstärke, Ohm für Widerstand und Watt für Leistung.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Wie lautet das Ohmsche Gesetz?",
      options: ["U = R / I", "U = R · I", "I = U · R", "R = U · I"],
      correct: [1],
      explanation: "Das Ohmsche Gesetz lautet U = R · I, also Spannung (V) gleich Widerstand (Ω) mal Stromstärke (A).",
      difficulty: 2,
    },
    {
      type: "mc",
      prompt: "Was misst ein Barometer?",
      options: ["Erdbeben", "Temperatur", "Windgeschwindigkeit", "Luftdruck"],
      correct: [3],
      explanation: "Ein Barometer misst den Luftdruck. Ein Seismograf misst Erdbeben, ein Thermometer die Temperatur und ein Anemometer die Windgeschwindigkeit.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Welcher Planet ist der äußerste in unserem Sonnensystem?",
      options: ["Saturn", "Uranus", "Neptun", "Jupiter"],
      correct: [2],
      explanation: "Neptun ist der äußerste Planet unseres Sonnensystems. Pluto gilt seit 2006 nicht mehr als Planet.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Wer erfand das World Wide Web (WWW)?",
      options: ["Bill Gates", "Tim Berners-Lee", "Konrad Zuse", "Steve Jobs"],
      correct: [1],
      explanation: "Tim Berners-Lee erfand das World Wide Web im Jahr 1989 am CERN in Genf.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Was baute Konrad Zuse, das in der Informatikgeschichte als Meilenstein gilt?",
      options: ["Den ersten Taschenrechner", "Das erste Betriebssystem", "Den Z3, den ersten frei programmierbaren Computer", "Die erste Festplatte"],
      correct: [2],
      explanation: "Konrad Zuse baute 1941 den Z3, der als erster frei programmierbarer Computer der Welt gilt.",
      difficulty: 2,
    },
    {
      type: "truefalse",
      prompt: "Hochspannung beginnt ab einer Spannung von über 1.000 Volt.",
      options: ["Richtig", "Falsch"],
      correct: [0],
      explanation: "Richtig. Als Hochspannung gilt eine elektrische Spannung von mehr als 1.000 Volt (1 kV).",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Welche Skala wird als absolute Temperaturskala bezeichnet?",
      options: ["Celsius", "Fahrenheit", "Kelvin", "Rankine"],
      correct: [2],
      explanation: "Kelvin ist die absolute Temperaturskala und zugleich die SI-Basiseinheit für Temperatur. 0 Kelvin entspricht dem absoluten Nullpunkt (−273,15 °C).",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Wie lang ist eine Seemeile?",
      options: ["1.000 m", "1.609 m", "1.852 m", "2.000 m"],
      correct: [2],
      explanation: "Eine Seemeile entspricht genau 1.852 Metern. Sie wird vor allem in der Schifffahrt und Luftfahrt verwendet.",
      difficulty: 2,
    },
    {
      type: "mc",
      prompt: "Was misst der pH-Wert?",
      options: ["Den Luftdruck einer Lösung", "Die elektrische Leitfähigkeit einer Lösung", "Den Säure- oder Basengehalt einer Lösung", "Die Temperatur einer Lösung"],
      correct: [2],
      explanation: "Der pH-Wert ist ein Maß für den Säure- oder Basengehalt (Alkalinität) einer wässrigen Lösung. Werte unter 7 sind sauer, über 7 basisch.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Welches Gerät misst Erdbeben?",
      options: ["Barometer", "Hygrometer", "Seismograf", "Anemometer"],
      correct: [2],
      explanation: "Ein Seismograf (auch Seismograph) misst seismische Wellen, die durch Erdbeben entstehen. Ein Barometer misst den Luftdruck.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Wer entwickelte die Relativitätstheorie?",
      options: ["Isaac Newton", "Albert Einstein", "Niels Bohr", "Max Planck"],
      correct: [1],
      explanation: "Albert Einstein formulierte die spezielle Relativitätstheorie (1905) und die allgemeine Relativitätstheorie (1915).",
      difficulty: 1,
    },
    {
      type: "truefalse",
      prompt: "Benjamin Franklin erfand den Blitzableiter.",
      options: ["Richtig", "Falsch"],
      correct: [0],
      explanation: "Richtig. Benjamin Franklin erfand den Blitzableiter im Jahr 1752 und bewies damit die elektrische Natur des Blitzes.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Welche SI-Basiseinheit steht für die Masse?",
      options: ["Gramm (g)", "Kilogramm (kg)", "Tonne (t)", "Newton (N)"],
      correct: [1],
      explanation: "Das Kilogramm (kg) ist die SI-Basiseinheit der Masse. Gramm und Tonne sind abgeleitete Einheiten, Newton ist die Einheit der Kraft.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "In welcher Einheit wird Energie gemessen?",
      options: ["Watt (W)", "Pascal (Pa)", "Joule (J)", "Newton (N)"],
      correct: [2],
      explanation: "Energie wird in Joule (J) gemessen. Watt ist die Einheit der Leistung, Pascal die des Drucks und Newton die der Kraft.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Welche Einheit wird für Frequenz verwendet?",
      options: ["Newton (N)", "Hertz (Hz)", "Joule (J)", "Pascal (Pa)"],
      correct: [1],
      explanation: "Frequenz wird in Hertz (Hz) gemessen. 1 Hz entspricht einem Schwingungsvorgang pro Sekunde.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Was bedeutet das Präfix 'Mega'?",
      options: ["Tausend (1.000)", "Hunderttausend (100.000)", "Eine Million (1.000.000)", "Eine Milliarde (1.000.000.000)"],
      correct: [2],
      explanation: "Das Präfix 'Mega' steht für den Faktor 1.000.000 (eine Million). Beispiel: 1 Megabyte = 1.000.000 Byte.",
      difficulty: 2,
    },
    {
      type: "mc",
      prompt: "Was bedeutet das Präfix 'milli'?",
      options: ["Ein Tausendstel (0,001)", "Ein Hundertstel (0,01)", "Ein Millionstel (0,000001)", "Ein Milliardstel (0,000000001)"],
      correct: [0],
      explanation: "Das Präfix 'milli' steht für den Faktor 0,001 (ein Tausendstel). Beispiel: 1 Millimeter = 0,001 Meter.",
      difficulty: 2,
    },
    {
      type: "mc",
      prompt: "Wie viele Meter sind 1 Kilometer?",
      options: ["100 m", "500 m", "1.000 m", "10.000 m"],
      correct: [2],
      explanation: "1 Kilometer (km) = 1.000 Meter (m). Das Präfix 'kilo' steht für den Faktor 1.000.",
      difficulty: 1,
    },
    {
      type: "truefalse",
      prompt: "1 Tonne entspricht 1.000 Kilogramm.",
      options: ["Richtig", "Falsch"],
      correct: [0],
      explanation: "Richtig. 1 Tonne (t) = 1.000 Kilogramm (kg). Das Präfix 'kilo' steht für 1.000, also ist 1 kg = 1.000 g und 1 t = 1.000 kg.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Wie viele Sekunden hat eine Stunde?",
      options: ["600 s", "1.800 s", "3.600 s", "7.200 s"],
      correct: [2],
      explanation: "1 Stunde = 60 Minuten = 60 × 60 Sekunden = 3.600 Sekunden.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Welches Weltraumteleskop wurde 1990 in den Orbit gebracht und ist nach einem Astronomen benannt?",
      options: ["Kepler-Teleskop", "James-Webb-Teleskop", "Hubble-Weltraumteleskop", "Spitzer-Weltraumteleskop"],
      correct: [2],
      explanation: "Das Hubble-Weltraumteleskop, benannt nach Edwin Hubble, wurde 1990 in den Orbit gebracht und liefert seither hochauflösende Bilder des Universums.",
      difficulty: 2,
    },
    {
      type: "mc",
      prompt: "In welcher Einheit wird Druck gemessen?",
      options: ["Joule (J)", "Watt (W)", "Ampere (A)", "Pascal (Pa)"],
      correct: [3],
      explanation: "Druck wird in Pascal (Pa) oder Bar gemessen. Joule ist die Einheit der Energie, Watt der Leistung und Ampere der Stromstärke.",
      difficulty: 2,
    },
    {
      type: "mc",
      prompt: "Was bedeutet das Präfix 'Giga'?",
      options: ["Eine Million (1.000.000)", "Zehn Millionen (10.000.000)", "Eine Milliarde (1.000.000.000)", "Eine Billion (1.000.000.000.000)"],
      correct: [2],
      explanation: "Das Präfix 'Giga' steht für den Faktor 1.000.000.000 (eine Milliarde). Beispiel: 1 Gigabyte = 1.000.000.000 Byte.",
      difficulty: 2,
    },
  ],
};

export default supplement;
