import type { RawFlashcard, RawQuestion } from '../types';

const supplement: { flashcards: RawFlashcard[]; questions: RawQuestion[] } = {
  flashcards: [
    { front: "Was ist ein Verwaltungsakt?", back: "Eine hoheitliche Maßnahme einer Behörde im Einzelfall. Der schriftliche Verwaltungsakt wird als Bescheid bezeichnet." },
    { front: "Was bedeutet Gesetzmäßigkeit der Verwaltung?", back: "Sie umfasst zwei Prinzipien: Vorrang des Gesetzes (nichts darf gegen ein Gesetz verstoßen) und Vorbehalt des Gesetzes (die Behörde darf nur handeln, wenn ein Gesetz es erlaubt)." },
    { front: "Was ist der Untersuchungsgrundsatz?", back: "Die Behörde ermittelt den Sachverhalt von Amts wegen, also ohne Antrag der Beteiligten." },
    { front: "Was ist Amtshilfe?", back: "Behörden helfen sich gegenseitig bei der Erfüllung ihrer Aufgaben." },
    { front: "Was ist der Unterschied zwischen Rechtsaufsicht und Fachaufsicht?", back: "Die Rechtsaufsicht prüft nur die Rechtmäßigkeit des Handelns. Die Fachaufsicht prüft zusätzlich auch die Zweckmäßigkeit. Beide werden meist durch das Landratsamt ausgeübt." },
    { front: "Welche Laufbahngruppen gibt es im Beamtenrecht und welche Abschlüsse sind typisch?", back: "Einfacher Dienst: ohne Abschluss / Hauptschule. Mittlerer Dienst: mittlere Reife. Gehobener Dienst: Bachelor / Verwaltungs-FH. Höherer Dienst: Master / Staatsexamen." },
    { front: "Was bedeutet Alimentation im Beamtenrecht?", back: "Der Staat ist verpflichtet, Beamte und ihre Familien amtsangemessen zu besolden (Alimentationsprinzip)." },
    { front: "Wie wird ein Beamter auf Lebenszeit?", back: "Ein Beamter auf Probe wird spätestens nach 5 Jahren zum Beamten auf Lebenszeit ernannt, wenn er sich bewährt hat." },
    { front: "Wer ist oberster Dienstvorgesetzter der allgemeinen Verwaltung im Saarland?", back: "Der Innenminister." },
    { front: "Was sind die grundlegenden Fakten zum Saarland?", back: "Hauptstadt: Saarbrücken. Kleinstes Flächenland der Bundesrepublik (außer Stadtstaaten). Ca. 1 Million Einwohner. Grenzt an Frankreich und Luxemburg." },
    { front: "Wer führt die Landesregierung des Saarlandes (Stand 2026)?", back: "Ministerpräsidentin: Anke Rehlinger (SPD). Minister für Inneres, Bauen und Sport: Reinhold Jost. Staatssekretär: Torsten Lang." },
    { front: "Was ergab das Saarstatut-Referendum 1955 und was folgte daraus?", back: "Die Bevölkerung lehnte das Saarstatut ab. Infolgedessen trat das Saarland am 1. Januar 1957 der Bundesrepublik Deutschland bei." },
    { front: "Was ist das LaVa und welche Behörden sind dem Innenministerium des Saarlandes nachgeordnet?", back: "LaVa steht für Landesverwaltungsamt. Nachgeordnete Behörden sind u. a. die Polizei, die Fachhochschule für Verwaltung und die Landesfeuerwehrschule." },
  ],
  questions: [
    {
      type: "mc",
      prompt: "Was versteht man unter einem Bescheid?",
      options: ["Eine mündliche Anweisung einer Behörde", "Der schriftliche Verwaltungsakt einer Behörde", "Eine interne Dienstanweisung", "Ein Urteil des Verwaltungsgerichts"],
      correct: [1],
      explanation: "Der Bescheid ist die schriftliche Form des Verwaltungsakts, also einer hoheitlichen Maßnahme einer Behörde im Einzelfall.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Was bedeutet der Vorbehalt des Gesetzes?",
      options: ["Die Verwaltung darf niemals gegen ein Gesetz verstoßen", "Die Verwaltung darf nur dann handeln, wenn ein Gesetz es ihr erlaubt", "Nur der Gesetzgeber darf Verwaltungsakte erlassen", "Gesetze haben Vorrang vor Verordnungen"],
      correct: [1],
      explanation: "Der Vorbehalt des Gesetzes besagt, dass die Verwaltung nur tätig werden darf, wenn sie dazu durch ein Gesetz ermächtigt ist. Der Vorrang des Gesetzes besagt ergänzend, dass kein Verwaltungshandeln gegen ein Gesetz verstoßen darf.",
      difficulty: 2,
    },
    {
      type: "truefalse",
      prompt: "Der Vorrang des Gesetzes bedeutet, dass die Behörde nur handeln darf, wenn ein Gesetz es erlaubt.",
      options: ["Richtig", "Falsch"],
      correct: [1],
      explanation: "Falsch. Das ist der Vorbehalt des Gesetzes. Der Vorrang des Gesetzes bedeutet, dass die Verwaltung nicht gegen ein bestehendes Gesetz verstoßen darf.",
      difficulty: 2,
    },
    {
      type: "mc",
      prompt: "Was bedeutet der Untersuchungsgrundsatz in der Verwaltung?",
      options: ["Bürger müssen alle Beweise selbst beibringen", "Die Behörde ermittelt den Sachverhalt von Amts wegen", "Das Verwaltungsgericht leitet alle Ermittlungen", "Strafverfolgungsbehörden unterstützen Verwaltungsbehörden"],
      correct: [1],
      explanation: "Nach dem Untersuchungsgrundsatz ermittelt die Behörde den Sachverhalt selbstständig und von Amts wegen, ohne dass die Beteiligten einen entsprechenden Antrag stellen müssen.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Welche Aufsichtsform prüft neben der Rechtmäßigkeit auch die Zweckmäßigkeit kommunalen Handelns?",
      options: ["Rechtsaufsicht", "Fachaufsicht", "Dienstaufsicht", "Verfassungsaufsicht"],
      correct: [1],
      explanation: "Die Fachaufsicht geht über die bloße Rechtmäßigkeitsprüfung der Rechtsaufsicht hinaus und prüft zusätzlich, ob eine Entscheidung auch zweckmäßig ist. Beide Aufsichtsformen werden meist durch das Landratsamt ausgeübt.",
      difficulty: 2,
    },
    {
      type: "mc",
      prompt: "Welcher Abschluss ist für den gehobenen Dienst typisch?",
      options: ["Hauptschulabschluss", "Mittlere Reife", "Bachelor oder Abschluss an der Verwaltungs-FH", "Master oder Staatsexamen"],
      correct: [2],
      explanation: "Für den gehobenen Dienst ist ein Bachelor-Abschluss oder ein Abschluss an der Fachhochschule für Verwaltung typisch. Der höhere Dienst erfordert einen Master oder ein Staatsexamen.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Welcher Laufbahngruppe entspricht der Abschluss mittlere Reife?",
      options: ["Einfacher Dienst", "Mittlerer Dienst", "Gehobener Dienst", "Höherer Dienst"],
      correct: [1],
      explanation: "Die mittlere Reife (Realschulabschluss) ist der typische Zugangsabschluss für den mittleren Dienst.",
      difficulty: 1,
    },
    {
      type: "truefalse",
      prompt: "Ein Beamter auf Probe wird spätestens nach 5 Jahren zum Beamten auf Lebenszeit ernannt.",
      options: ["Richtig", "Falsch"],
      correct: [0],
      explanation: "Richtig. Spätestens nach einer Probezeit von 5 Jahren wird ein bewährter Beamter auf Probe zum Beamten auf Lebenszeit ernannt.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Wer ist oberster Dienstvorgesetzter der allgemeinen Verwaltung im Saarland?",
      options: ["Der Ministerpräsident", "Der Innenminister", "Der Landrat", "Der Staatssekretär"],
      correct: [1],
      explanation: "Oberster Dienstvorgesetzter der allgemeinen Verwaltung im Saarland ist der Innenminister.",
      difficulty: 2,
    },
    {
      type: "mc",
      prompt: "Was ist die Hauptstadt des Saarlandes?",
      options: ["Homburg", "Neunkirchen", "Saarlouis", "Saarbrücken"],
      correct: [3],
      explanation: "Die Hauptstadt des Saarlandes ist Saarbrücken.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "An welche Länder bzw. Staaten grenzt das Saarland?",
      options: ["Belgien und die Niederlande", "Österreich und die Schweiz", "Frankreich und Luxemburg", "Polen und Tschechien"],
      correct: [2],
      explanation: "Das Saarland grenzt im Westen an Luxemburg und im Süden und Südwesten an Frankreich.",
      difficulty: 1,
    },
    {
      type: "truefalse",
      prompt: "Das Saarland ist das flächenmäßig kleinste Bundesland Deutschlands ohne Ausnahme.",
      options: ["Richtig", "Falsch"],
      correct: [1],
      explanation: "Falsch. Das Saarland ist das kleinste Flächenland, aber nur wenn man die Stadtstaaten (Berlin, Bremen, Hamburg) ausklammert. Mit Stadtstaaten gerechnet ist Bremen das kleinste Bundesland.",
      difficulty: 2,
    },
    {
      type: "mc",
      prompt: "Wann trat das Saarland der Bundesrepublik Deutschland bei?",
      options: ["1. Januar 1955", "23. Mai 1949", "1. Januar 1957", "3. Oktober 1990"],
      correct: [2],
      explanation: "Nach dem Saarstatut-Referendum im Jahr 1955, bei dem die Bevölkerung das Saarstatut ablehnte, trat das Saarland am 1. Januar 1957 der Bundesrepublik Deutschland bei.",
      difficulty: 2,
    },
    {
      type: "mc",
      prompt: "Wer ist Ministerpräsidentin des Saarlandes (Stand 2026)?",
      options: ["Heike Raab", "Annegret Kramp-Karrenbauer", "Anke Rehlinger", "Ursula von der Leyen"],
      correct: [2],
      explanation: "Anke Rehlinger (SPD) ist Ministerpräsidentin des Saarlandes.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Wofür steht die Abkürzung LaVa im Saarland?",
      options: ["Landesvertretungsamt", "Landesverwaltungsamt", "Landesverkehrsanstalt", "Landesverfassungsausschuss"],
      correct: [1],
      explanation: "LaVa steht für Landesverwaltungsamt, eine dem Innenministerium des Saarlandes nachgeordnete Behörde.",
      difficulty: 2,
    },
    {
      type: "fill",
      prompt: "Der Minister für Inneres, Bauen und Sport im Saarland (Stand 2026) heißt ___.",
      correct: ["Reinhold Jost", "Jost"],
      explanation: "Reinhold Jost ist der saarländische Minister für Inneres, Bauen und Sport.",
      difficulty: 2,
    },
    {
      type: "mc",
      prompt: "Welche Sprache wird im Saarland besonders gefördert?",
      options: ["Luxemburgisch", "Englisch", "Französisch", "Niederländisch"],
      correct: [2],
      explanation: "Aufgrund der geografischen Lage und der historischen Verbindung zu Frankreich wird Französisch im Saarland besonders gefördert.",
      difficulty: 1,
    },
  ],
};

export default supplement;
