import type { RawFlashcard, RawQuestion } from '../types';

const supplement: { flashcards: RawFlashcard[]; questions: RawQuestion[] } = {
  flashcards: [
    { front: "Welche Religion hat mit ~2,4 Milliarden Anhängern die meisten Mitglieder?", back: "Das Christentum. Zentralfigur ist Jesus Christus, heiliges Buch die Bibel, Symbol das Kreuz." },
    { front: "Wann entstand der Islam und wer ist sein Prophet?", back: "Der Islam entstand im 7. Jahrhundert n. Chr. Der Prophet ist Mohammed, das heilige Buch der Koran, das Symbol der Halbmond." },
    { front: "Welche der drei monotheistischen Religionen ist die älteste?", back: "Das Judentum. Das heilige Buch ist die Tora, das Symbol der Davidstern." },
    { front: "Was unterscheidet Hinduismus und Buddhismus in Bezug auf Götter?", back: "Der Hinduismus ist polytheistisch (viele Götter, v. a. in Indien). Der Buddhismus kennt keinen Schöpfergott; Begründer ist Siddhartha Gautama (Buddha)." },
    { front: "Welche Werke verbindet man mit Goethe und Schiller?", back: "Johann Wolfgang von Goethe schrieb 'Faust'. Friedrich Schiller ist zusammen mit Goethe der wichtigste Vertreter der Weimarer Klassik." },
    { front: "Welche berühmten Gemälde stammen von Leonardo da Vinci und Vincent van Gogh?", back: "Leonardo da Vinci malte die 'Mona Lisa'. Vincent van Gogh malte die 'Sternennacht'." },
    { front: "Welches Musikwerk Beethovens ist die Europahymne?", back: "Beethovens 9. Sinfonie mit der 'Ode an die Freude'. Sie wird als Hymne der Europäischen Union verwendet." },
    { front: "Was ist der Nobelpreis und wo wird er verliehen?", back: "Der Nobelpreis ist die höchste wissenschaftliche Auszeichnung, gestiftet von Alfred Nobel. Die Verleihung findet in Stockholm statt – außer der Friedensnobelpreis, der in Oslo vergeben wird." },
    { front: "Welche Erfindung wird Gutenberg (~1450) zugeschrieben?", back: "Der Buchdruck mit beweglichen Lettern (um 1450)." },
    { front: "Wem werden Glühbirne, Telefon und Penicillin zugeschrieben?", back: "Glühbirne: Thomas Edison. Telefon: Alexander Graham Bell. Penicillin: Alexander Fleming." },
    { front: "Wofür sind Newton, Darwin und Marie Curie bekannt?", back: "Isaac Newton entdeckte die Schwerkraft. Charles Darwin entwickelte die Evolutionstheorie. Marie Curie erforschte die Radioaktivität und erhielt zwei Nobelpreise." },
    { front: "Wie viele Kontinente hat die Erde und wie groß ist die Weltbevölkerung?", back: "Die Erde hat 7 Kontinente. Die Weltbevölkerung beträgt rund 8 Milliarden Menschen." },
  ],
  questions: [
    {
      type: "mc",
      prompt: "Welche Religion hat weltweit die meisten Anhänger (ca. 2,4 Milliarden)?",
      options: ["Islam", "Hinduismus", "Christentum", "Buddhismus"],
      correct: [2],
      explanation: "Das Christentum ist mit rund 2,4 Milliarden Anhängern die weltweit größte Religion.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Welches Symbol steht für den Islam?",
      options: ["Kreuz", "Davidstern", "Om-Zeichen", "Halbmond"],
      correct: [3],
      explanation: "Das Symbol des Islam ist der Halbmond. Das Kreuz steht für das Christentum, der Davidstern für das Judentum.",
      difficulty: 1,
    },
    {
      type: "truefalse",
      prompt: "Der Buddhismus wurde von Siddhartha Gautama begründet und kennt keinen Schöpfergott.",
      options: ["Richtig", "Falsch"],
      correct: [0],
      explanation: "Siddhartha Gautama (Buddha) ist der Begründer des Buddhismus. Der Buddhismus ist keine theistische Religion und kennt keinen Schöpfergott.",
      difficulty: 2,
    },
    {
      type: "mc",
      prompt: "Wer schrieb das literarische Werk 'Faust'?",
      options: ["Friedrich Schiller", "William Shakespeare", "Johann Wolfgang von Goethe", "Heinrich Heine"],
      correct: [2],
      explanation: "Johann Wolfgang von Goethe schrieb 'Faust', eines der bedeutendsten Werke der deutschen Literatur.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Welches Gemälde malte Leonardo da Vinci?",
      options: ["Sternennacht", "Das letzte Abendmahl und die Mona Lisa", "Guernica", "Die Sixtinische Kapelle"],
      correct: [1],
      explanation: "Leonardo da Vinci malte die 'Mona Lisa' (und das 'Letzte Abendmahl'). Die 'Sternennacht' stammt von Van Gogh, 'Guernica' von Picasso.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Wo wird der Friedensnobelpreis verliehen?",
      options: ["Stockholm", "Genf", "Berlin", "Oslo"],
      correct: [3],
      explanation: "Alle Nobelpreise werden in Stockholm vergeben – mit Ausnahme des Friedensnobelpreises, der in Oslo verliehen wird.",
      difficulty: 2,
    },
    {
      type: "mc",
      prompt: "Wer erfand den Buchdruck mit beweglichen Lettern um 1450?",
      options: ["Thomas Edison", "Johannes Gutenberg", "Alexander Bell", "Isaac Newton"],
      correct: [1],
      explanation: "Johannes Gutenberg erfand den Buchdruck mit beweglichen Lettern um das Jahr 1450.",
      difficulty: 1,
    },
    {
      type: "truefalse",
      prompt: "Marie Curie erhielt insgesamt zwei Nobelpreise für ihre Forschung zur Radioaktivität.",
      options: ["Richtig", "Falsch"],
      correct: [0],
      explanation: "Marie Curie ist die einzige Person, die Nobelpreise in zwei verschiedenen Naturwissenschaften erhielt (Physik 1903 und Chemie 1911).",
      difficulty: 2,
    },
    {
      type: "mc",
      prompt: "Welche Sprache wird weltweit am häufigsten als Muttersprache gesprochen?",
      options: ["Englisch", "Spanisch", "Chinesisch", "Arabisch"],
      correct: [2],
      explanation: "Chinesisch (Mandarin) hat die meisten Muttersprachler weltweit, gefolgt von Englisch und Spanisch.",
      difficulty: 2,
    },
    {
      type: "mc",
      prompt: "Wie oft finden die Olympischen Spiele und die Fußball-WM statt?",
      options: ["Alle 2 Jahre", "Alle 3 Jahre", "Alle 4 Jahre", "Alle 5 Jahre"],
      correct: [2],
      explanation: "Sowohl die Olympischen Spiele als auch die Fußball-Weltmeisterschaft werden alle 4 Jahre ausgetragen.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Was symbolisieren die 5 Ringe im olympischen Symbol?",
      options: ["Die 5 Kontinente der Welt", "Die 5 Gründungsländer", "Die 5 Sportarten der ersten Spiele", "Die 5 Werte des Sports"],
      correct: [0],
      explanation: "Die fünf Ringe des olympischen Symbols stehen für die fünf Kontinente der Welt, die durch die Olympischen Spiele vereint werden.",
      difficulty: 2,
    },
    {
      type: "mc",
      prompt: "In welcher Stadt steht die Freiheitsstatue?",
      options: ["Washington D.C.", "Los Angeles", "Chicago", "New York"],
      correct: [3],
      explanation: "Die Freiheitsstatue (Statue of Liberty) steht auf einer Insel im Hafen von New York.",
      difficulty: 1,
    },
    {
      type: "truefalse",
      prompt: "Das Kolosseum befindet sich in Paris.",
      options: ["Richtig", "Falsch"],
      correct: [1],
      explanation: "Das Kolosseum steht in Rom (Italien). Der Eiffelturm befindet sich in Paris.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Wer entwickelte die Evolutionstheorie?",
      options: ["Isaac Newton", "Albert Einstein", "Charles Darwin", "Galileo Galilei"],
      correct: [2],
      explanation: "Charles Darwin entwickelte die Evolutionstheorie, die er 1859 in seinem Werk 'Über die Entstehung der Arten' veröffentlichte.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Welche Währung ist dem Land Japan zugeordnet?",
      options: ["Yuan", "Won", "Yen", "Ringgit"],
      correct: [2],
      explanation: "Die Währung Japans ist der Yen. Der Yuan ist die chinesische Währung, der Won die südkoreanische.",
      difficulty: 2,
    },
    {
      type: "mc",
      prompt: "Beethovens 9. Sinfonie enthält welches berühmte Stück, das als Europahymne dient?",
      options: ["Mondscheinsonate", "Ode an die Freude", "Für Elise", "Stille Nacht"],
      correct: [1],
      explanation: "Die 'Ode an die Freude' aus Beethovens 9. Sinfonie ist die offizielle Hymne der Europäischen Union.",
      difficulty: 1,
    },
  ],
};

export default supplement;
