import type { RawFlashcard, RawQuestion } from '../types';
const supplement: { flashcards: RawFlashcard[]; questions: RawQuestion[] } = {
  flashcards: [
    { front: "Was sind die zwei Zustaende, die ein Computer kennt?", back: "Strom an oder aus, dargestellt als 1 und 0 (Binaersystem, Basis 2)." },
    { front: "Was ist ein Bit?", back: "Ein Bit ist ein einzelner Schalter mit dem Wert 0 oder 1." },
    { front: "Wie viele Bit ergeben ein Byte?", back: "8 Bit = 1 Byte. Ein Byte reicht etwa fuer einen Buchstaben." },
    { front: "Nenne die Reihenfolge der Speichereinheiten von klein nach gross.", back: "Byte, KB, MB, GB, TB. Jede Einheit ist rund 1000-mal so gross wie die vorherige." },
    { front: "Welche Basis hat das Hexadezimalsystem und welche Ziffern verwendet es?", back: "Basis 16. Es verwendet die Ziffern 0-9 sowie die Buchstaben A-F." },
    { front: "Was ist ASCII bzw. Unicode?", back: "Eine Zeichencodierung, die festlegt, welche Zahl fuer welchen Buchstaben steht." },
    { front: "Wie lautet die Dezimaldarstellung der Binaerzahl 1011?", back: "1011 (binaer) = 8 + 0 + 2 + 1 = 11 (dezimal)." },
    { front: "Was ist der Hexadezimalwert von Dezimal 10?", back: "Dezimal 10 entspricht dem Hexadezimalwert A." },
    { front: "Was ist der Hexadezimalwert von Dezimal 15?", back: "Dezimal 15 entspricht dem Hexadezimalwert F (1111 in binaer)." },
    { front: "Wie lautet die Binaerdarstellung von Dezimal 12?", back: "Dezimal 12 = Binaer 1100 = Hex C." },
  ],
  questions: [
    {
      type: "mc",
      prompt: "Welche Basis hat das Binaersystem?",
      options: ["Basis 8", "Basis 10", "Basis 2", "Basis 16"],
      correct: [2],
      explanation: "Computer kennen nur zwei Zustaende (Strom an oder aus), dargestellt als 0 und 1. Daher hat das Binaersystem die Basis 2.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Wie viele Bit ergeben ein Byte?",
      options: ["4 Bit", "16 Bit", "2 Bit", "8 Bit"],
      correct: [3],
      explanation: "8 Bit = 1 Byte. Ein Byte reicht ungefaehr fuer die Speicherung eines Buchstabens.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Welchen Dezimalwert hat die Binaerzahl 1011?",
      options: ["9", "11", "13", "10"],
      correct: [1],
      explanation: "1011 (binaer) wird stellenweise berechnet: 1x8 + 0x4 + 1x2 + 1x1 = 8 + 0 + 2 + 1 = 11 (dezimal).",
      difficulty: 2,
    },
    {
      type: "mc",
      prompt: "Was beschreibt ASCII bzw. Unicode?",
      options: ["Ein Binaer-zu-Dezimal-Umrechnungsverfahren", "Ein Datenkompressionsformat", "Eine Zeichencodierung, die Zahlen Buchstaben zuordnet", "Eine Speichereinheit fuer Textdateien"],
      correct: [2],
      explanation: "ASCII und Unicode sind Zeichencodierungen: Sie legen fest, welche Zahl fuer welchen Buchstaben oder welches Zeichen steht.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Welche Reihenfolge der Speichereinheiten ist korrekt (von klein nach gross)?",
      options: ["KB, Byte, MB, TB, GB", "Byte, KB, MB, GB, TB", "MB, KB, Byte, GB, TB", "Byte, MB, KB, GB, TB"],
      correct: [1],
      explanation: "Die korrekte Reihenfolge ist: Byte, KB, MB, GB, TB. Jede Einheit ist rund 1000-mal so gross wie die vorherige.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Welchem Hexadezimalwert entspricht die Dezimalzahl 10?",
      options: ["9", "B", "A", "F"],
      correct: [2],
      explanation: "Dezimal 10 entspricht im Hexadezimalsystem dem Buchstaben A. Die Umrechnungstabelle zeigt: 10 = 1010 (binaer) = A (hex).",
      difficulty: 2,
    },
    {
      type: "mc",
      prompt: "Wie lautet die Binaerdarstellung von Dezimal 8?",
      options: ["0111", "1001", "1010", "1000"],
      correct: [3],
      explanation: "Dezimal 8 = 1x8 + 0x4 + 0x2 + 0x1 = 1000 im Binaersystem.",
      difficulty: 2,
    },
    {
      type: "fill",
      prompt: "Ergaenze: 8 Bit = 1 ___ (Einheit, die etwa fuer einen Buchstaben reicht).",
      correct: ["Byte"],
      explanation: "8 Bit ergeben 1 Byte. Ein Byte ist die Grundeinheit fuer Zeichenspeicherung und reicht ungefaehr fuer einen Buchstaben.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Welchen Dezimal- und Hexadezimalwert hat die Binaerzahl 1111?",
      options: ["Dezimal 14, Hex E", "Dezimal 15, Hex F", "Dezimal 16, Hex 10", "Dezimal 13, Hex D"],
      correct: [1],
      explanation: "1111 (binaer) = 1x8 + 1x4 + 1x2 + 1x1 = 15 (dezimal) = F (hexadezimal).",
      difficulty: 2,
    },
    {
      type: "mc",
      prompt: "Welche Ziffern verwendet das Hexadezimalsystem?",
      options: ["0-7", "0-9 und A-F", "0-9 und a-z", "0-15"],
      correct: [1],
      explanation: "Das Hexadezimalsystem (Basis 16) verwendet die Ziffern 0-9 und die Buchstaben A-F, wobei A=10, B=11, ... F=15 entspricht.",
      difficulty: 1,
    },
  ],
};
export default supplement;
