import type { RawFlashcard, RawQuestion } from '../types';
const supplement: { flashcards: RawFlashcard[]; questions: RawQuestion[] } = {
  flashcards: [
    { front: "Was ist das Präsens von 'gehen' (ich)?", back: "ich gehe (Gegenwart)" },
    { front: "Was ist das Perfekt von 'gehen' (ich)?", back: "ich bin gegangen (Vergangenheit, gesprochen)" },
    { front: "Was ist das Präteritum von 'gehen' (ich)?", back: "ich ging (Vergangenheit, geschrieben/erzählt)" },
    { front: "Was ist das Plusquamperfekt von 'gehen' (ich)?", back: "ich war gegangen (Vorvergangenheit)" },
    { front: "Was ist das Futur I von 'gehen' (ich)?", back: "ich werde gehen (Zukunft)" },
    { front: "Was ist das Futur II von 'gehen' (ich)?", back: "ich werde gegangen sein (vollendete Zukunft)" },
    { front: "Welche sechs Zeitformen gibt es im Deutschen?", back: "Präsens, Perfekt, Präteritum, Plusquamperfekt, Futur I, Futur II" },
    { front: "Was sind schwache (regelmäßige) Verben? Nenne zwei Beispiele.", back: "Verben mit regelmäßiger Bildung: machen-machte-gemacht; lernen-lernte-gelernt" },
    { front: "Was sind starke (unregelmäßige) Verben? Nenne ein Merkmal.", back: "Verben mit Vokalwechsel im Stamm, z. B. gehen-ging-gegangen; sehen-sah-gesehen" },
    { front: "Mit welchem Hilfsverb bildet man das Perfekt von Bewegungsverben wie 'gehen'?", back: "mit 'sein': ich bin gegangen (nicht: ich habe gegangen)" },
    { front: "Welche Verben bilden das Perfekt mit 'sein'?", back: "Verben der Bewegung/Ortsveränderung (gehen, fahren, kommen), Zustandsänderung (aufstehen, einschlafen) sowie sein, bleiben, werden" },
    { front: "Welche Verben bilden das Perfekt mit 'haben'?", back: "die meisten Verben, z. B. sehen-hat gesehen; nehmen-hat genommen; geben-hat gegeben" },
    { front: "Wie lautet die Reihe: sein (Infinitiv - Präteritum - Perfekt)?", back: "sein - war - ist gewesen" },
    { front: "Wie lautet die Reihe: haben (Infinitiv - Präteritum - Perfekt)?", back: "haben - hatte - hat gehabt" },
    { front: "Wie lautet die Reihe: werden (Infinitiv - Präteritum - Perfekt)?", back: "werden - wurde - ist geworden" },
    { front: "Wie lautet die Reihe: kommen (Infinitiv - Präteritum - Perfekt)?", back: "kommen - kam - ist gekommen" },
    { front: "Wie lautet die Reihe: fahren (Infinitiv - Präteritum - Perfekt)?", back: "fahren - fuhr - ist gefahren" },
    { front: "Wie lautet die Reihe: sehen (Infinitiv - Präteritum - Perfekt)?", back: "sehen - sah - hat gesehen" },
    { front: "Wie lautet die Reihe: nehmen (Infinitiv - Präteritum - Perfekt)?", back: "nehmen - nahm - hat genommen" },
    { front: "Wie lautet die Reihe: geben (Infinitiv - Präteritum - Perfekt)?", back: "geben - gab - hat gegeben" },
    { front: "Wie lautet die Reihe: bringen (Infinitiv - Präteritum - Perfekt)?", back: "bringen - brachte - hat gebracht" },
    { front: "Wie lautet die Reihe: denken (Infinitiv - Präteritum - Perfekt)?", back: "denken - dachte - hat gedacht" },
    { front: "Wofür verwendet man das Präteritum?", back: "Für die Vergangenheit in geschriebenen Texten und beim Erzählen" },
    { front: "Wofür verwendet man das Perfekt?", back: "Für die Vergangenheit in der gesprochenen Sprache" },
    { front: "Was drückt das Plusquamperfekt aus?", back: "Die Vorvergangenheit, d. h. eine Handlung, die vor einer anderen vergangenen Handlung abgeschlossen war" },
  ],
  questions: [
    {
      type: "mc",
      prompt: "Welche Zeitform drückt die Vorvergangenheit aus?",
      options: ["Präteritum", "Perfekt", "Plusquamperfekt", "Futur II"],
      correct: [2],
      explanation: "Das Plusquamperfekt drückt die Vorvergangenheit aus (ich war gegangen).",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Wie lautet das Perfekt von 'gehen' in der 1. Person Singular?",
      options: ["ich habe gegangen", "ich bin gegangen", "ich war gegangen", "ich werde gegangen sein"],
      correct: [1],
      explanation: "'gehen' ist ein Bewegungsverb und bildet das Perfekt mit 'sein': ich bin gegangen.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Was ist das Präteritum von 'sehen' (ich)?",
      options: ["ich sehe", "ich gesehen", "ich habe gesehen", "ich sah"],
      correct: [3],
      explanation: "Das Präteritum von 'sehen' lautet 'sah': ich sah.",
      difficulty: 2,
    },
    {
      type: "mc",
      prompt: "Welches Hilfsverb benutzt 'fahren' im Perfekt?",
      options: ["haben", "sein", "werden", "bleiben"],
      correct: [1],
      explanation: "'fahren' ist ein Bewegungsverb und bildet das Perfekt mit 'sein': ich bin gefahren.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Welche Zeitform drückt die vollendete Zukunft aus?",
      options: ["Futur I", "Präteritum", "Plusquamperfekt", "Futur II"],
      correct: [3],
      explanation: "Das Futur II drückt die vollendete Zukunft aus (ich werde gegangen sein).",
      difficulty: 2,
    },
    {
      type: "mc",
      prompt: "Wie wird das Präteritum des schwachen Verbs 'machen' gebildet?",
      options: ["machte", "gemacht", "macht", "hat gemacht"],
      correct: [0],
      explanation: "Schwache Verben bilden das Präteritum regelmäßig mit -te: machen-machte-gemacht.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Was ist das Perfekt von 'werden' (er)?",
      options: ["er hat geworden", "er wurde", "er ist geworden", "er wird gewesen sein"],
      correct: [2],
      explanation: "'werden' bildet das Perfekt mit 'sein': er ist geworden.",
      difficulty: 2,
    },
    {
      type: "mc",
      prompt: "Welches ist ein Merkmal starker (unregelmäßiger) Verben?",
      options: ["Sie enden im Präteritum immer auf -te.", "Sie haben einen Vokalwechsel im Stamm.", "Sie bilden das Perfekt immer mit 'haben'.", "Sie haben keine Partizipform."],
      correct: [1],
      explanation: "Starke Verben ändern den Stammvokal, z. B. gehen-ging-gegangen; sehen-sah-gesehen.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Wie lautet das Präteritum von 'kommen' (sie, Plural)?",
      options: ["sie kommen", "sie gekommen", "sie kamen", "sie sind gekommen"],
      correct: [2],
      explanation: "Das Präteritum von 'kommen' lautet 'kamen': sie kamen.",
      difficulty: 2,
    },
    {
      type: "mc",
      prompt: "Welches Verb bildet das Perfekt mit 'haben'?",
      options: ["gehen", "fahren", "sehen", "kommen"],
      correct: [2],
      explanation: "'sehen' ist kein Bewegungsverb und bildet das Perfekt mit 'haben': ich habe gesehen.",
      difficulty: 2,
    },
    {
      type: "mc",
      prompt: "Wie lautet das Futur I von 'gehen' (ich)?",
      options: ["ich gehe", "ich werde gehen", "ich werde gegangen sein", "ich bin gegangen"],
      correct: [1],
      explanation: "Das Futur I wird mit 'werden' + Infinitiv gebildet: ich werde gehen.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Welche Zeitform verwendet man vorzugsweise in der gesprochenen Sprache für vergangene Ereignisse?",
      options: ["Präteritum", "Plusquamperfekt", "Perfekt", "Futur I"],
      correct: [2],
      explanation: "Das Perfekt wird in der gesprochenen Sprache für die Vergangenheit verwendet.",
      difficulty: 1,
    },
    {
      type: "truefalse",
      prompt: "Das Verb 'bleiben' bildet das Perfekt mit 'sein' (ich bin geblieben).",
      options: ["Richtig", "Falsch"],
      correct: [0],
      explanation: "Richtig. 'bleiben' gehört zu den Verben, die das Perfekt mit 'sein' bilden.",
      difficulty: 2,
    },
    {
      type: "truefalse",
      prompt: "Das Präteritum von 'haben' lautet 'hatte'.",
      options: ["Richtig", "Falsch"],
      correct: [0],
      explanation: "Richtig. Die Reihe lautet: haben - hatte - hat gehabt.",
      difficulty: 1,
    },
    {
      type: "truefalse",
      prompt: "Das Verb 'denken' ist ein schwaches Verb und bildet das Präteritum regelmäßig mit -te: 'denkte'.",
      options: ["Richtig", "Falsch"],
      correct: [1],
      explanation: "Falsch. 'denken' bildet das Präteritum unregelmäßig als 'dachte' (nicht 'denkte').",
      difficulty: 2,
    },
    {
      type: "truefalse",
      prompt: "Das Verb 'aufstehen' bildet das Perfekt mit 'sein', weil es eine Zustandsänderung ausdrückt.",
      options: ["Richtig", "Falsch"],
      correct: [0],
      explanation: "Richtig. Verben der Zustandsänderung wie 'aufstehen' und 'einschlafen' bilden das Perfekt mit 'sein'.",
      difficulty: 2,
    },
    {
      type: "fill",
      prompt: "Ergänze die Lücke: Das Präteritum von 'bringen' lautet '___'.",
      options: [],
      correct: ["brachte"],
      explanation: "Die Reihe lautet: bringen - brachte - hat gebracht.",
      difficulty: 2,
    },
    {
      type: "fill",
      prompt: "Ergänze die Lücke: Das Partizip II von 'nehmen' lautet '___'.",
      options: [],
      correct: ["genommen"],
      explanation: "Die Reihe lautet: nehmen - nahm - hat genommen.",
      difficulty: 2,
    },
    {
      type: "fill",
      prompt: "Ergänze die Lücke: Das Präteritum von 'fahren' (ich) lautet 'ich ___'.",
      options: [],
      correct: ["fuhr"],
      explanation: "Die Reihe lautet: fahren - fuhr - ist gefahren.",
      difficulty: 2,
    },
    {
      type: "fill",
      prompt: "Ergänze die Lücke: Das Perfekt von 'geben' (er) lautet 'er ___ gegeben'.",
      options: [],
      correct: ["hat"],
      explanation: "'geben' ist kein Bewegungsverb, daher Perfekt mit 'haben': er hat gegeben.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Wie lautet das Präteritum von 'sein' (er)?",
      options: ["er ist", "er wird sein", "er war", "er ist gewesen"],
      correct: [2],
      explanation: "Das Präteritum von 'sein' lautet 'war': er war.",
      difficulty: 1,
    },
    {
      type: "mc",
      prompt: "Welche Zeitform wird durch 'ich werde gegangen sein' dargestellt?",
      options: ["Futur I", "Perfekt", "Präteritum", "Futur II"],
      correct: [3],
      explanation: "Futur II wird mit 'werden' + Partizip II + Infinitiv von 'haben'/'sein' gebildet: ich werde gegangen sein.",
      difficulty: 3,
    },
    {
      type: "mc",
      prompt: "Welches Verb aus der Liste bildet das Perfekt mit 'haben'?",
      options: ["sein", "werden", "geben", "kommen"],
      correct: [2],
      explanation: "'geben' ist kein Bewegungsverb und bildet das Perfekt mit 'haben': er hat gegeben.",
      difficulty: 2,
    },
    {
      type: "truefalse",
      prompt: "Das Futur I wird mit 'werden' und dem Infinitiv des Verbs gebildet.",
      options: ["Richtig", "Falsch"],
      correct: [0],
      explanation: "Richtig. Beispiel: ich werde gehen (Futur I).",
      difficulty: 1,
    },
    {
      type: "fill",
      prompt: "Ergänze die Lücke: Das Präteritum von 'gehen' (ich) lautet 'ich ___'.",
      options: [],
      correct: ["ging"],
      explanation: "Die Reihe lautet: gehen - ging - ist gegangen.",
      difficulty: 1,
    },
  ],
};
export default supplement;
